### ISSUE TITLE
HTTPS Request: Invalid scheme for Http

### ISSUE THREAD

**Issue by kiliankoe** [hyperium/hyper#1009]
I'm currently building against v0.10 and am experiencing some issues trying to send a request on macOS 10.12. 

Here's a minimal example.

```rust
extern crate hyper;

use hyper::Client;
use hyper::Url;

fn main() {
    let url = "https://httpbin.org/get";

    let url = Url::parse(&url).unwrap();
    println!("{:?}", url);

    let client = Client::new();
    let res = client.get(url).send();
    println!("{:?}", res);
}
```

```
"https://httpbin.org/get"
Err(Io(Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("Invalid scheme for Http") }) })
```

When I build against `hyper = { version = "0.9", default-features = false, features = ["security-framework"] }`this example runs just fine, so I'm guessing the issue has something to do with macOS' security-framework handling in hyper? 

The error does not occur when requesting http://httpbin.org/get.

**Comment by seanmonstar** [comment]
hyper no longer includes a default TLS library, so you'll need to pick one. I'd recommend [hyper-native-tls](https://crates.io/crates/hyper-native-tls).

See #985 for reasoning.

**Comment by kiliankoe** [comment]
Ah, I see. Thanks for the link and reasoning!

Would it be possible to make the error messages a little more clear though than they currently are? I tried quite a bit to debug this and was unable to find out anything by looking around with the error message. It probably would've helped if I've looked in the issues here more closely, but a quick search didn't show anything 😕

**Comment by seanmonstar** [comment]
I could certainly see value in adding a `error!("HttpConnector used to connect for HTTPS URL, try using HttpsConnector with an SSL implementation")` or similar just before returning the `Err`.

**Comment by kiliankoe** [comment]
That would be great!

**Comment by seanmonstar** [comment]
Of course, this would only alert you if you had some sort of logger setup...

Separately, I wonder if it makes sense to change from suggesting `Client::new()` to `Client::http()` (or even `Client::plaintext()`?), so it is explicit that the client won't be able to connect to HTTPS.

**Comment by PReinie** [comment]
I guess the good news is that when I searched for http-1009 this was the 2nd entry in Google's results, and the first one I clicked on, so you accomplished making information available for others who need help.

**Comment by LeoTindall** [comment]
Does this work with 0.11.0? It seems that `hyper::net` no longer exists.

**Comment by william20111** [comment]
> Does this work with 0.11.0? It seems that hyper::net no longer exists.

This ^ im currently using 0.10 as hyper::net is gone. Any update on this..?

**Comment by dmizuk** [comment]
You can use [`hyper-tls`](https://crates.io/crates/hyper-tls). The documentation explains how to use it with v0.11.

**Comment by wez** [comment]
Just ran into this.  A couple of suggestions:

* The client guide buries this issue under "Client Configuration" which is several steps too late into the flow.  Please make a point of calling out that an additional crate is required to do TLS.
* Please consider breaking the TLS portion of "Client Configuration" into a separate "Enabling HTTPS" section to make this clearer to folks skimming docs.
* Please make the error message more directive.  This is bubbling up in my first client integration as `Error { repr: Custom(Custom { kind: InvalidInput, error: NotHttp }) }` which doesn't tell me very much about what is going on

**Comment by jhinrichsen** [comment]
Just ran into this. I copy and pasted the snippet from the client guide, and changed the URL to https scheme, boom. This is 2019, please look around: plain http is not used any more. As for your example, http://httpbin.org: if i enter "httpbin.org" into my browser URL, it will use https://httpbin.org.

`By default, a Client can only speak to HTTP addresses.` This is so last year. Compare to

`By default, a Client can only speak to HTTPS addresses using TLS 1.3`

https should be the default, and the #1 rust http client library that shows up on Google (via https) should support it out-of-the-box, or have a feature matrix as the first section that clearly states that https requires extra effort. I'm already prepared to find out hyper doesn't support proxies ;)

**Comment by Hexilee** [comment]
Why does this [code](https://github.com/Hexilee/rust-examples/blob/master/tls/src/main.rs) still run into the error "invalid URL, scheme is not http".

**Comment by sfackler** [comment]
https://docs.rs/hyper/0.13.2/hyper/client/struct.HttpConnector.html#method.enforce_http

**Comment by Hexilee** [comment]
Thx

**Comment by David-OConnor** [comment]
This error is still as-is, in 2022.

**Comment by ash-hashtag** [comment]
I don't know why but it worked for the last month, even with https urls, I didn't use any tls crates, and now it is throwing this error

**Comment by ash-hashtag** [comment]
> You can use [`hyper-tls`](https://crates.io/crates/hyper-tls). The [guide](https://hyper.rs/guides/client/configuration/) explains how to use it with v0.11.

the page is not there anymore
