### ISSUE TITLE
Replace `CowStr` with `Cow<'static, str>` in Headers

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1016]
The newtype `CowStr` is from a time when `Cow<'static, str>` wasn't yet a thing, but we can just get rid of that now.

Specifically, in the `headers/mod.rs`, removing the `struct CowStr(Cow<'static, str>)`, and any fallout throughout the rest of the file.

**Comment by jimmycuadra** [comment]
Which branch is this for? `CowStr` doesn't seem to exist in the master branch.

**Comment by seanmonstar** [comment]
Well crazy me. I must have already done this in master. I was just tweaking some things in the 0.10.x branch, and saw this type and was like 'why does this exist'. Apparently I've already thought this before. No need to fix it in the 0.10.x branch, development is on master now.
