### ISSUE TITLE
Client support for other methods than GET

### ISSUE THREAD

**Issue by pimeys** [hyperium/hyper#1018]
The client has `get` and `request` methods, which should allow different types of HTTP methods. Would be nice if we'd have an interface for at least `post`, `put` and `delete`, allowing to set the request entity if needed.

**Comment by pimeys** [comment]
And at least in some point, when using `request` the method module needs to be public to set the request method:

https://github.com/pimeys/hyper/commit/27a7454f265896bb5ff778242445ef852f9c1890

**Comment by seanmonstar** [comment]
You should be able to use `hyper::Method` to access any of them: https://github.com/hyperium/hyper/blob/master/src/lib.rs#L41

I'm personally uncertain how many additional "helper" methods should exist, when you can customize the method, headers and body on a `Request` and then call `client.request(req)`. There are several of these in 0.10, but I tried to be more conservative this time, figuring `get` was definitely needed. Perhaps also `post`, but I dislike how you may or may not need a body for `POST`, but defining a function would require making you choose...

**Comment by pimeys** [comment]
Ok, didn't notice the methods are available in hyper module. Works now.

**Comment by seanmonstar** [comment]
Since it seems the issue was just being able to use `hyper::Method` in `Request::new`, I'll close this for now. Proposals of convenience functions for `Client` are always welcome, ideally with examples supporting them.
