### ISSUE TITLE
Better client request header setup

### ISSUE THREAD

**Issue by pimeys** [hyperium/hyper#1019]
To modify the request headers, one needs a mutable reference to the `Request` and from that request a mutable reference to `Headers`. Having two mutable references to the same object in the same scope can lead to trouble with the borrow checker, so at least my life was much easier after adding a `set_header` method to the request. Not suggesting this should be the final solution, but the current implementation in `HEAD` might need some refinement.

https://github.com/pimeys/hyper/commit/daf37c274ad08875853dd92872e0020b094488d1

**Comment by seanmonstar** [comment]
You shouldn't need a mutable *reference* to `Request`...

```rust
let mut req = Request::new(Get, url);
req.headers_mut().set(ContentLength(500));
req.headers_mut().set(ContentType::json());

// also!
req.headers_mut().extend(other_headers.iter());

client.request(req)
```

I do think that the client request type is missing some builder methods, similar to the server response type. Adding those would allow this sometimes easier builder pattern:

```rust
client.request(
    Request::new(Get, url)
        .with_header(one)
        .with_header(two)
        .with_body(body)
)
```

**Comment by pimeys** [comment]
I get this tendency of not calling the `headers_mut()` repeatedly as in your example. I know that with Rust it's not slowing it down and the first example works nicely in my case.

I don't know how much of a simple high level interface Hyper needs, or should it be basis for another library to provide it.
