### ISSUE TITLE
Remove usage of Url parse in Uri

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1022]
There is legacy code in the `Uri` type that relies on `Url::parse`, even to parse only parts of the uri. This is unnecessary and slow.

Maybe not the easiest thing to do (regarding the easy label), since it requires making some `parse_scheme` and `parse_authority` and such kind of methods, but it's at least fairly straight forward, and contained to a single module.

**Comment by M3rs** [comment]
I'm interested in giving this a try. Is it just alright to put in a pull request when I have something that passes tests?

**Comment by seanmonstar** [comment]
@M3rs absolutely!

**Comment by seanmonstar** [comment]
I meant to include this originally, but the `parse` function from Go is a good example: https://github.com/golang/go/blob/master/src/net/url/url.go#L469

**Comment by M3rs** [comment]
Question: How do you want the authority with a default port handled? 

Should I refactor the method `pub fn authority(&self) -> Option<&str>` so if the port is a default (80, 443), it just returns the "authority" and not the port portion?

```
related test failures:
---- uri::test_uri_parse_absolute_with_default_port_http stdout ----
	thread 'uri::test_uri_parse_absolute_with_default_port_http' panicked at 'assertion failed: `(left == right)` (left: `Some("127.0.0.1:80")`, right: `Some("127.0.0.1")`)', uri.rs:324

---- uri::test_uri_parse_absolute_with_default_port_https stdout ----
	thread 'uri::test_uri_parse_absolute_with_default_port_https' panicked at 'assertion failed: `(left == right)` (left: `Some("127.0.0.1:443")`, right: `Some("127.0.0.1")`)', uri.rs:335
```

My forked/branched version: [uri.rs](https://github.com/M3rs/hyper/blob/refactor_uri/src/uri.rs)

**Comment by seanmonstar** [comment]
@M3rs perhaps the best to do is include the port if it was in the original URI, and if it wasn't, do not include.

So:

```
http://foo.bar:3333/baz => foo.bar:3333
http://foo.bar:80/baz   => foo.bar:80
http://foo.bar/baz      => foo.bar
```

**Comment by M3rs** [comment]
Ok - I have pushed an update to my [uri.rs](https://github.com/M3rs/hyper/blob/refactor_uri/src/uri.rs) which causes the port to be included.

What are the rules on path? The test_parse! methods give a mixed idea of what it should be expected if no path is given.

Examples:
```
address => path
---
http://127.0.0.1:80 => "/"
http://127.0.0.1:61761/chunks => "/chunks"
localhost:3000 => "" (no path)
```
Is that just a mistake in the test, and in the third case (localhost), the path should be expecting "/" instead of ""?

The `pub fn path(&self) -> &str` method looks like it is defaulting "" when it cannot get a path.

**Comment by seanmonstar** [comment]
It's a good question! It depends on the format of the request-target. If it is `origin-form` or `absolute-form`, (so, `/foo` or `http://host/foo`), then there MUST always be a path, even if not explicitly included. That means `http://127.0.0.1:80 => "/"` is correct.

However, if it is `authority-form` or `asterisk-form`, the there is NOT a path.  Which again, means `localhost:3000 => ""` is correct. The details can found in [this part of the spec](https://tools.ietf.org/html/rfc7230#section-5.3).

**Comment by M3rs** [comment]
Ok - I have updated the `pub fn path(&self) -> &str` method logic to try to check for `absolute-form`<sup>1</sup> and include a path if one is not specified.

However, the `test_uri_parse_error()` no longer appropriately errors. I am considering borrow logic from rust-url's (origin.rs)[https://github.com/servo/rust-url/blob/master/src/origin.rs] to throw an `Error::Method` if it is an opaque scheme.

<sup>1</sup> I am making the assumption that if `self.scheme().is_some()` is `true` that indicates the url is in `absolute-form` and missing a path.

**Comment by seanmonstar** [comment]
That assumption is likely fine for now. It is true for HTTP/1. It will need to be updated slightly when supporting HTTP2, since `scheme` is always included at that point, but we don't need that just yet.
