### ISSUE TITLE
More clearly document how to get working HTTPS

### ISSUE THREAD

**Issue by alex** [hyperium/hyper#1025]
If you're coming from a pre-0.10 hyper, you had working HTTPS out of the box; with 0.10 "some assembly required". It'd be great of the hyper website, and documentation included a pointer to hyper-native-tls (or some other option), and appropriate snippets for integration.

**Comment by frewsxcv** [comment]
It seems like for most people, they'll want to migrate their crates to use [reqwest](https://github.com/seanmonstar/reqwest) instead of Hyper's HTTP client. Maybe this should be mentioned in the CHANGELOG and possibly temporarily the README.

**Comment by seanmonstar** [comment]
I've added some links to the release page: https://github.com/hyperium/hyper/releases/v0.10.0

Would likely also be useful in the docs somewhere, and a guide dedicated to it.

**Comment by antoyo** [comment]
What is the state of HTTPs clients based on tokio?
I looked into `reqwest` and it does not seem to be based on tokio.
What do I need to do to create an HTTPS request based on tokio?
Thanks.

**Comment by seanmonstar** [comment]
@antoyo the easiest way right now is to make use of [hyper-tls](https://github.com/hyperium/hyper-tls). However, the Client in hyper is generic over any kind of connector, so others can be created, with hyper-tls as a example.

**Comment by nayato** [comment]
I think the easiest right now is to use tokio-proto to layer tokio-tls under hyper, here's working sample:
https://github.com/nayato/hyper-test/blob/90add9d2db27503a204294177f4552e0bb11dca2/src/main.rs#L43

**Comment by TerraX-net** [comment]
tokio-tls uses native-tls which isn't "as much in Rust as possible".
[tokio-rusttls](https://github.com/quininer/tokio-rustls) (started as a fork of tokio-tls) sounds promising to me.
rustls is built on top of [ring](https://github.com/briansmith/ring) and [webpki](https://github.com/briansmith/webpki).
ring is a fork of Google's Bo**ring**ssl, which aims to rewrite as much as possible (and meaningful) in Rust. Both projects (ring and boringssl) are working together!
For earlier hyper versions, there was [hyper-rustls](https://crates.io/crates/hyper-rustls). rustls is probably going to get included in Mozilla Servo, a webbrowser written in Rust. With using the system's native TLS implemenation we would not profit from Rust's advantages to have a secure TLS implementation.

**Comment by daboross** [comment]
@TerraX-net at the moment, native TLS is a more secure solution than Rust ring/rustls due to rustls not having any security audits performed on it. When it reaches more maturity, it will definitely be a better default, but for now it's better to use native-tls.

**Comment by dawid-nowak** [comment]
I would echo the comments on lack of TLS documentation in the examples. I would say that lots of people would be discouraged by that given how important TLS is in today's world.

Having said that it seems that latest release of "tonic" project has a good and working example of how to use TLS with hyper. So in my app I copied some of the code from "tonic".

I was wondering if that logic could be pulled into "hyper" library?

**Comment by 89z** [comment]
Just ran into this. I do see that its documented here:

https://github.com/hyperium/hyper/releases/v0.10.0

but thats hardly the place you would look for something like this. I would expect at least a one line short note here:

https://docs.rs/hyper/latest/hyper/client

**Comment by Vagelis-Prokopiou** [comment]
I subscribe to this too.
Setting up a hyper server with TLS, is quite unclear. Some dedicated hyper documentation is necessary in my opinion.
TLS is a sine qua non, and there is a glaring lack of documentation of the feature/setup/config.
Happy to help if guidance is provided.

**Comment by seanmonstar** [comment]
I've added a stub guide about connectors (https://hyper.rs/guides/1/client/connectors/), and a list of crates that provide TLS for hyper. Adding more to the guides is always appreciated! (#3411)
