### ISSUE TITLE
Replace rustc-serialize with base64 crate

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1028]
The rustc-serialize crate is used by the `Basic` authorization header. It's a big crate, we don't need all of it, and the [base64](https://crates.io/crates/base64) is faster anyways.

**Comment by M3rs** [comment]
This just in authorization.rs, right? I can try to swap these.

**Comment by seanmonstar** [comment]
Correct.

**Comment by robinst** [comment]
Looks like this was done on master and is a relatively small change. Would you mind if I opened a PR to backport it to 0.10.x?

**Comment by seanmonstar** [comment]
@robinst sure, that'd be fine!

**Comment by robinst** [comment]
Thanks! For anyone wondering, the above is now also released in 0.10.10.
