### ISSUE TITLE
Cannot download hyper 0.9.16 from crates.io

### ISSUE THREAD

**Issue by saneyuki** [hyperium/hyper#1034]
## The day I confirm this problem

- 2017/Jan/25 23:04:22 +0900

## Step to reproduce

1. Specify `hyper = "0.9.16`
2. Build the sample project.

## Actual 

- `cargo build` says the following error
- https://github.com/rust-lang/crates.io-index/blob/master/hy/pe/hyper does not contains 0.9.16.
  - I saw https://github.com/rust-lang/crates.io-index/blob/8b4006d9158edf759380573c95288aac2539839b/hy/pe/hyper 
- But there is a `hyper 0.9.16` in [crates.io](https://crates.io/crates/hyper/0.9.16).
 
#### the error of `cargo build`
```
 Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching package named `hyper` found (required by `sample_project`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.9.16
versions found: 0.10.2, 0.10.0, 0.9.14, ...
```

## Expected

- Could you re-publish v.0.9.16?
  - This might be the bug of crates.io, but I cannot be sure about it.

**Comment by seanmonstar** [comment]
Thanks for reporting this. Seems there was an error in crates.io when trying to update its index, and so only the DB was updated, but it wasn't put into the crates.io-index.

I cannot republish the version, but I have published 0.9.17 that is the exact same source, and it seems to have updated the index: https://github.com/rust-lang/crates.io-index/commit/d2b7dcc940d95ad59b2300cf84bbf7b2756898b7

**Comment by seanmonstar** [comment]
For 0.9.16, found this was indeed a bug in crates.io. See https://github.com/rust-lang/crates.io/issues/448

**Comment by saneyuki** [comment]
@seanmonstar 

Thank you! I confirmed I can use v0.9.17.
