### ISSUE TITLE
Working with CONNECT tunnels 

### ISSUE THREAD

**Issue by fmonjalet** [hyperium/hyper#1037]
Hi, 

I am currently writing a toy HTTP proxy using hyper with tokio (current master). While plain HTTP proxying was easy to write, I am struggling with how to handle CONNECT tcp tunnels (typically used to proxy https without ssl interception). 

How would you proceed to switch from the Http service to a raw tcp proxy service (such as the one demonstrated in `tokio-socks5`) on the same socket ?

Solving this issue would also be beneficial for _switching protocols_ to websockets or cleartext http2.

Thank you in advance for any advice. 

Florent

**Comment by seanmonstar** [comment]
This is something that Tokio needs to figure, since hyper is using Tokio internally. I've discussed the concept before with the Tokio devs, but apparently there wasn't a tracking issue, so I've filed https://github.com/tokio-rs/tokio-proto/issues/138.

**Comment by fmonjalet** [comment]
Thank you! I'll think of a workaround in the meantime.

**Comment by marcb** [comment]
I'm also interested in CONNECT support. Looking to correlate TLS SNI with the domain name passed to CONNECT, to (dynamically) whitelist and also map the name to another for the resolution of the next hop.

_Context an in-bound forward proxy for one platform to reach other platforms within an enterprise network across DMZs and fronted by reverse proxies_.

Another protocol switch example is to support the [proxy protocol](http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) (aka ELBs) stripping and insertion.

**Comment by sfackler** [comment]
I think this has been resolved by https://docs.rs/hyper/0.12.1/hyper/client/conn/struct.Connection.html#method.poll_without_shutdown, right?

**Comment by seanmonstar** [comment]
Yep, this can be done now with the `server::conn` module, and in the next release, could also be done thanks to #1563.
