### ISSUE TITLE
Client Connection Pool doesn't close stale connections

### ISSUE THREAD

**Issue by rsdy** [hyperium/hyper#1042]
I'm having troubles getting connection pooling to work. I configure my Hyper client like so:

```
const MAX_IDLE_CONNECTIONS: usize = 4;

pub fn get_hyper_client_with_tls(tls_client: hyper_rustls::TlsClient) -> Client {
    use hyper::client::pool;
    use hyper::net::HttpsConnector;

    Client::with_connector(pool::Pool::with_connector(pool::Config {
                                                          max_idle: MAX_IDLE_CONNECTIONS,
                                                      },
                                                      HttpsConnector::new(tls_client)))
}
```

Besides being fairly slow, the application will leave behind TCP connections in TIME_WAIT state, which accumulate over time. It doesn't look like any pooling happens at all. I can't tell what is going wrong.

Edit: Using version 0.10.4

**Comment by rsdy** [comment]
After doing some more debugging, it looks like a server-side configuration issue.
However, the connections are still being closed on a regular basis, with seemingly no way to specify a timeout to keep them around. This behaviour may be best documented?

**Comment by seanmonstar** [comment]
This is known, and a crappy part about hyper in 0.10.x and before. With blocking IO, there isn't a sufficient way for the hyper `Client` to reap stale connections, since detecting one requires doing IO, which could block indefinitely.

The problem doesn't exist in master.

**Comment by rsdy** [comment]
Thanks for clarification. That makes sense perfect sense.
