### ISSUE TITLE
Thread initializers

### ISSUE THREAD

**Issue by DemiMarie** [hyperium/hyper#1059]
This is a feature request for functions that run in each worker thread before that thread handles any requests.  This could be used to set up thread-local storage, or to start per-thread state.

For example, consider a server written in Rust that embeds SpiderMonkey.  SpiderMonkey runtimes cannot be transferred across threads, so one must be started for every worker thread.

**Comment by DemiMarie** [comment]
That makes sense.

It seems that hyper is becoming a base on which other, higher-level HTTP libraries are written, rather than one that is used directly by the end-user.

**Comment by seanmonstar** [comment]
Indeed, it is meant to be a `libhttp`. It is definitely possible for end-users to build things with it. But there are so many additional optional things many people want to when building a server or client, people usually use a framework anyways.
