### ISSUE TITLE
Hyper::Url cannot safely set a non utf-8 query string

### ISSUE THREAD

**Issue by kkartaltepe** [hyperium/hyper#1061]
Reading through the documentation and project it seems that the main purpose of hyper is to be "stringly" typed so this may be out of scope, but is it possible to introduce a way to set uninterpreted or only validated(instead of re-encoded) components of the query pairs? And/Or is it  safe to use invalid utf-8 strings in query parameters?

Currently working on a simple Rust implementation of the BitTorrent protocol which requires sending raw hashes to a tracker urlencoded. Since these are raw bytes they may not correspond to a valid utf-8 string and thus fail being `String`ified. As urlencode-ing was seemingly created to get around your data being interpreted incorrectly somewhere along the way, I'd hate for that issue to be in my HTTP library.

Now there are a couple ways I've found around this currently, I can parse the base url with the query pair I want already urlencoded or I can make an unchecked string out of my bytes and pass it into `append_pair`. Both these produce a `Url::to_str()` that looks correct for my case, but this may be dangerous as I may just be avoiding some case which will fail later due to the `String`ified nature of Hyper.

**Comment by seanmonstar** [comment]
> the main purpose of hyper is to be "stringly" typed so this may be out of scope

What gives you that impression? In fact, hyper actually uses a lot of types that aren't simply strings, to not be stringly-typed HTTP like so many other libraries.

hyper actually re-exports the `Url` type from the [url crate](https://github.com/servo/rust-url). If you have a specific issue with it, you'd probably want to file an issue there. 

In this specific case, you could make use of [percent_encode](https://docs.rs/url/1.4.0/url/percent_encoding/fn.percent_encode.html) to convert your raw bytes into something acceptable in a URL.

> I can make an unchecked string out of my bytes

If it's not valid UTF-8, this is unsafe and can cause unexpected behavior in your app. Do not do that.

**Comment by kkartaltepe** [comment]
>What gives you that impression?
>hyper is a fast, modern HTTP implementation written in and for Rust. It is a low-level typesafe abstraction over raw HTTP, providing an elegant layer over "stringly-typed" HTTP.
This might just be my misinterpretation.

I did not know that the `Url` was a rexport that would explain why I was having issues finding documentation on it. It looks like my question is better answered over on the `Url` repo, and in fact from their docs I see that non UTF-8 query parameters are an off by default feature.

Thanks for the information! Hopefully using hyper with this option turned on in Url wont be an issue.
(I hope its ok that I close this myself as my issue is actually about the Url crate)

**Comment by seanmonstar** [comment]
Oh, that sentence is meant to point out that HTTP/1 (and largely HTTP2) are protocols about sending and receiving strings. hyper tries to make use of Rust's type system to reduce the mistakes that can be made when everything is just a string.
