### ISSUE TITLE
[question] Where is the design direction documented?

### ISSUE THREAD

**Issue by steckel** [hyperium/hyper#1064]
I see that there is an example using a Service object and Future implementation in the code base that isn't supported using the `0.10.*` release currently out. Is there some sort of documentation for the release strategy of `0.11.x` (which I believe may include these changes)? Or is there some sort of document explaining the overall design direction and changes planned for future releases?

**Comment by seanmonstar** [comment]
I'm not quite certain what exactly you're looking for. There isn't a specific document about a release strategy, there is the [Milestones](https://github.com/hyperium/hyper/milestones) that has a super rough look at what things would block a release.

**Comment by steckel** [comment]
That's probably what I was looking for.

My question stemmed from some confusion when I attempted to replicate the code in `examples/hello.rs` using `0.10.*` not realizing that it represented a different design implementation (async io with `Service` and `Future`) that was available in `0.10.0`.

Thank you for pointing me to the Milestones.
