### ISSUE TITLE
Support Opaque origin headers, serializing it to `null`

### ISSUE THREAD

**Issue by samgiles** [hyperium/hyper#1065]
Support Opaque origins:

> An internal value, with no serialization it can be recreated from (it is serialized as "null" per ASCII serialization of an origin), for which the only meaningful operation is testing for equality.

https://html.spec.whatwg.org/multipage/browsers.html#concept-origin

**Comment by seanmonstar** [comment]
Sorry, in what context? The url? The `Origin` header?

**Comment by jdm** [comment]
The origin header.

**Comment by seanmonstar** [comment]
I see. So it can either be `null`, or the full origin. It seems like any way to make this work with hyper's `Origin` header would require a breaking change. Since that's the case, my thinking is something like this, for inclusion in v0.11:

```rust
pub struct Origin(OriginOrNull);

enum OriginOrNull {
    Origin {
        scheme: String,
        host: Host,
    },
    Null,
}

impl Origin {
    pub fn new<S: Into<String>, H: Into<String>>(scheme: S, hostname: H, port: Option<u16>) -> Origin{
        Origin(OriginOrNull::Origin {
            scheme: scheme.into(),
            host: Host::new(hostname.into(), port),
        })
    }

    pub fn null() -> Origin {
        Origin(OriginOrNull::Null)
    }

    pub fn is_null(&self) -> bool;
    pub fn scheme(&self) -> Option<&str>;
    pub fn hostname(&self) -> Option<&str>;
    pub fn port(&self) -> Option<u16>;
}
```
 Whatcha think?

For servo, if you wish to make use of this right away while keeping to hyper 0.10, you could implement an `Origin` header in Servo.

**Comment by samgiles** [comment]
@seanmonstar That looks real similar to the `url` crate's `Origin` implementation, since it's a dependency, could we rely on the serialization algorithms implemented there?

**Comment by seanmonstar** [comment]
Oh I remember this conversation again. We didn't use `url::Origin` because it requires the port. The header has the port optional.

**Comment by seanmonstar** [comment]
Thanks to work in #1121, the breaking change required here is done. This would be pretty easy to implement using an internal private enum, as described in https://github.com/hyperium/hyper/issues/1065#issuecomment-280116120, keeping our use of `Cow` instead of `String.

**Comment by alexeyzab** [comment]
Hi there! I'd like to try implementing this.
