### ISSUE TITLE
ContentType should impl Eq

### ISSUE THREAD

**Issue by bfrog** [hyperium/hyper#1071]
when trying to compare header::ContentType values I get 

```
the trait `std::cmp::PartialEq<hyper::header::ContentType>` is not implemented for `&hyper::header::ContentType`
```

This seems like something most headers should impl, when writing tests its very convenient to do things like assert_eq!() and such.

**Comment by seanmonstar** [comment]
Oh, it's not that the various headers don't implement `PartialEq`, they do! It's that there isn't an impl for `&ContentType`, and all the others as references. How tedious...

**Comment by bfrog** [comment]
Ah right, I completely overlooked that, not really thinking about the difference there.

Using a reference works, but seems strange to me. What am I really comparing here?

``` rust
if req.headers.get::<ContentType>() == Some(&ContentType("text/plain".parse().unwrap())) {
   println!("acceptable content type");
}
```

**Comment by seanmonstar** [comment]
Very true. I wonder, would it be too magical if headers also implemented `PartialEq<Option<&Self>>`?

```rust
if req.headers.get::<ContentType>() == ContentType::plaintext() {

}
```

**Comment by bfrog** [comment]
On the surface that seems nicer than my snippet, though I wonder if people would miss out on the use case without some good examples in the right places. Really the reason to even have that PartialEq impl for Option<&Self> is because headers.get returns it.

Having an example there would make a good deal of sense.
