### ISSUE TITLE
Infinite loop if body sender is dropped

### ISSUE THREAD

**Issue by alexcrichton** [hyperium/hyper#1073]
Originally [reported here](https://github.com/tokio-rs/tokio-core/issues/177#issuecomment-281574226) it looks like this code:

```rust
extern crate env_logger;
extern crate futures;
extern crate hyper;

use hyper::{Body, Error};
use hyper::server::{Request, Response};
use futures::future;

struct MyService;

impl hyper::server::Service for MyService {
    type Request = Request;
    type Response = Response;
    type Error = Error;
    type Future = future::FutureResult<Self::Response, Self::Error>;

    fn call(&self, _req: Request) -> Self::Future {
        let (snd, rcv) = Body::pair();

        // Leak the sender, so rcv never gets chunks and is never closed.
        ::std::mem::forget(snd);

        future::ok(Response::new().with_body(rcv))
    }
}

fn main() {
    env_logger::init().unwrap();
    let addr = "127.0.0.1:1337".parse().unwrap();
    let server = hyper::server::Http::new().bind(&addr, || Ok(MyService)).unwrap();
    println!("Running on http://{}", server.local_addr().unwrap());
    server.run().unwrap();
}

```

sends hyper into an infinite loop [here](https://github.com/hyperium/hyper/blob/435fe84bf52fbbf819068402d6c8e902aa7a6685/src/http/conn.rs#L294).

**Comment by seanmonstar** [comment]
I've been looking in to trying to park and unpark a little less, but one thing here strikes me as odd: if the Sender hasn't sent anything, why would tokio try to flush again, especially if the previous flush already said it was complete?

**Comment by alexcrichton** [comment]
IIRC "flush" in this case basically just happens pretty commonly, but @carllerche would know for sure

**Comment by carllerche** [comment]
There are potentially some extra calls to flush that were added before the park / unpack semantics were figured out. They can probably be removed at some point though I am a bit worried about breaking existing code that happens to rely on it (hyper might be relying on them)
