### ISSUE TITLE
feature: request & response filters

### ISSUE THREAD

**Issue by fzakaria** [hyperium/hyper#1077]
It would be great to write filters so that request or responses can be modified before/after request.
It makes it easier rather than having to muck with `mut_headers` and a bunch of other stuff.
Also the filters can be modular and shareable!

**Comment by seanmonstar** [comment]
The design of how these sorts of things is exactly why various web frameworks pop up. People have different opinions on how they should work. This feature shouldn't be in hyper, but in a server framework.

**Comment by fzakaria** [comment]
I'm talking about from the client side.

I just tried to use Hyper (release not master) and it was impossible to even make any changes to the request object -- especially if I wanted to lets say: calculate an Authorization header based on already set headers.

1. RequestBuilder doesn't allow access to headers
2. Even if I hand form the Request (not using RequestBuilder) there is no method in Client that accepts it. It seems like it must take RequestBuilder and transforms it to Request in send.

A simple trait for `ClientRequestFilter` (Request -> Request) and `ClientResponseFilter` or however you imagine it might be usefu.

PS: Unclear how much of this is resolved in master. I just took the current release which is available on crates.io

**Comment by fzakaria** [comment]
I'll investigate more. 
Thanks for the follow-up

**Comment by seanmonstar** [comment]
Oh, I'm sorry, I just assumed you meant for the server, since filters did sound like a server thing. For the client, in master, there is no more builder off the Client. You construct a Request, which has accessor and mutator methods, and then give it to the Client.
