### ISSUE TITLE
hang when sending large file

### ISSUE THREAD

**Issue by scottlamb** [hyperium/hyper#1078]
```
$ git clone --branch hyper-0.11.x https://github.com/scottlamb/http-entity
$ cd http-entity
$ dd if=/dev/zero of=f bs=1M count=1
$ cargo run --example serve_file -- f
```

Hitting http://localhost:1337/ hangs on my machine after about half a meg. It worked with hyper revision dc97dd7; it hangs with hyper revision a6f7f27. So the commit that fixed the busy loop problem unfortunately also stopped looping in a case that was important. :-(

**Comment by limitee** [comment]
My problem is the same, hyper hangs, telnet is ok, but hyper do nothing.

**Comment by seanmonstar** [comment]
@limitee If you're using 0.10.4, then it's not the same issue here. This bug is in master.
