### ISSUE TITLE
Simpler way to get the whole body of the request

### ISSUE THREAD

**Issue by antoyo** [hyperium/hyper#1083]
Hello.
Here is my function to get the body of a request:
```rust
fn http_get<'a>(url: &str, handle: &Handle) -> impl Future<Item=Vec<u8>, Error=()> + 'a {
    let url = hyper::Url::parse(&url).unwrap();
    let client = Client::new(handle);
    client.get(url).map_err(|_| ()).and_then(|res| {
        res.body().map_err(|_| ()).fold(vec![], |mut acc, chunk| {
            acc.extend_from_slice(&chunk);
            Ok(acc)
        })
    })
        .map_err(|_| ())
}
```
I wonder if there is a simpler way than using `fold()` to get the whole body of the request.
Thanks.

**Comment by seanmonstar** [comment]
Fold gives the maximum control over all the details. There is a request (https://github.com/alexcrichton/futures-rs/issues/390) for a new method on Stream, and likely solution (https://github.com/alexcrichton/futures-rs/pull/394).

**Comment by antoyo** [comment]
Since this is an issue with `futures`, I close this issue.
Thanks.
