### ISSUE TITLE
Link header link_extensions should be an array map of extra fields

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1085]
From https://github.com/hyperium/hyper/pull/1044#discussion_r105328466:

> `LinkValue`'s `link_extension` field should probably be named `link_extensions` and return a `Option<Vec<LinkExtension>>` (or just a `Vec<LinkExtension>`) where `LinkExtension` is something like
>
> ```rust
> struct LinkExtension {
>   name: String,
>   value: Option<String>
> }
> ```

**Comment by tabac** [comment]
@seanmonstar I could do this. I guess nobody else is working on it right?

**Comment by seanmonstar** [comment]
For now, since the implementation was wrong, I removed the methods related to link extensions. Changing them would be a breaking change, so better to do this before releasing 0.11. The proper implementation can be added without breaking.

**Comment by seanmonstar** [comment]
For now, the new version of hyper won't be including the typed headers directly, so I'm closing this here as a won't fix.
