### ISSUE TITLE
Url join does not work more than once

### ISSUE THREAD

**Issue by mgattozzi** [hyperium/hyper#1087]
I was working on my github library and it builds up queries bit by bit. This means I don't join all the endings I want to a base Url. However, it was not working as expected. Here's an example of what was not working.

```rust
let url = Url::parse("https://api.github.com").unwrap();
println!("{:?}", url); // https://api.github.com
let url = url.join("user").unwrap();
println!("{:?}", url); // https://api.github.com/user
let url = url.join("emails").unwrap();
println!("{:?}", url);// https://api.github.com/emails
```

I'd expect url to be a new url with the added ending and that when I call join on it again later it would append to that new url. I was expecting in the above example to get:

```
https://api.github.com/user/emails
```

but got what I put in the example above. I've looked through the docs but there doesn't seem to be another method I would want to use here. Am I missing something or is this actually a bug? Do note I've updated the project to the most recent version on git while trying this in case it was fixed in between the last time I updated it and today. Please let me know if there is anything else you need to help track down the issue or if it needs further explanation.

**Comment by seanmonstar** [comment]
@mgattozzi I'm not entirely certain about the details actually, the `Url` type is re-exported from the [url](https://github.com/servo/rust-url) crate. Sorry about the duplicate work, but I'd suggest opening this issue on that repo.

**Comment by mgattozzi** [comment]
@seanmonstar Thanks for the heads up. I'll open it up on there end or find a solution there. If I get one I'll close this!

**Comment by mgattozzi** [comment]
I've found a work around for now that involves direct String manipulation. Not ideal but it works. I'll close this issue here since it's not Hypers fault.
