### ISSUE TITLE
http request timeout doesn't work

### ISSUE THREAD

**Issue by karlvlam** [hyperium/hyper#1088]
I just set the read/write timeout to 1 second, but it takes more than 2 minutes to return the timeout error. How should I configure the timeout value for a http request?

```rust
use hyper::client::Client;
let mut result = String::new();
let mut client = Client::new();

client.set_read_timeout(Some(Duration::from_millis(1000)));
client.set_write_timeout(Some(Duration::from_millis(1000)));
match client.get("http://IP_NOT_EXISTS/test.html").send() {
    Ok(mut res) => {
        res.read_to_string(&mut result);
    }
    Err(e) => {
        println!("HTTP_GET_ERROR : {} : {:#?}", url, e); 
    }
}   
```

**Comment by seanmonstar** [comment]
For all versions of hyper 0.10.x and before, this is true. Using `std::net::TcpStream::connect(domain)` makes use of blocking `getaddrinfo`, which does not have a timeout and cannot be interrupted. DNS on master does make use of a timeout, and can't really be fixed another way.

There's more in a previous duplicate issue, #721.
