### ISSUE TITLE
Request timeouts

### ISSUE THREAD

**Issue by crackcomm** [hyperium/hyper#1097]
Is it possible to configure request or HTTP client timeouts?
I am interested in master/tokio branch.

**Comment by seanmonstar** [comment]
As of now, there isn't specific timeouts to set that are inside hyper. There are a few reasons why, but the main reason was because using futures makes it quite simple for anyone to deal with timeouts external to hyper. For example:

```rust
let timeout = tokio_core::reactor::Timeout::new(Duration:from_secs(30), &handle))?;
// a tokio timeout doesn't necessarily mean an error,
//  but in our case, always make it an error
// (it could also be used for things like "send this message after this amount of time")
let timeout = timeout.then(|_| Err(io::Error::new(io::ErrorKind::TimedOut, "our timeout")));
// set up our client request
let future_body = client.get(some_url).and_then(|res| {
    res.body().fold(Vec::new(), |mut vec, chunk| {
        vec.extend_from_slice(&chunk);
        Ok(vec)
    })
});

// select on the request and the timeout
// the first one to 'complete' will trigger our callback
// since we converted the timeout to always be an error,
// it will only ever be in the `Err` variant
let work = future_body.select(timeout).then(|result| {
    match result { 
        Ok(body) => {
            // do something with the body
        },
        Err(e) => {
            // could be an http  or io error (including our time out error)
            // inspect to find out which it was
        }
    }
});
handle.spawn(work);
```

**Comment by crackcomm** [comment]
Thanks, that explains a lot.
I can't see any correlation between timeouts and request, how can I ensure that request is cancelled after timeout?

**Comment by carllerche** [comment]
If the request future is dropped, then that can trigger a cancellation. The
example with select above will drop the request future if the timeout
competes first. That is how the request is cancelled.

**Comment by crackcomm** [comment]
@carllerche this is a great mechanism, thank you for this explanation and @seanmonstar thank you for this example.

**Comment by Trenson** [comment]
> As of now, there isn't specific timeouts to set that are inside hyper. There are a few reasons why, but the main reason was because using futures makes it quite simple for anyone to deal with timeouts external to hyper. For example:
> 
> ```rust
> let timeout = tokio_core::reactor::Timeout::new(Duration:from_secs(30), &handle))?;
> // a tokio timeout doesn't necessarily mean an error,
> //  but in our case, always make it an error
> // (it could also be used for things like "send this message after this amount of time")
> let timeout = timeout.then(|_| Err(io::Error::new(io::ErrorKind::TimedOut, "our timeout")));
> // set up our client request
> let future_body = client.get(some_url).and_then(|res| {
>     res.body().fold(Vec::new(), |mut vec, chunk| {
>         vec.extend_from_slice(&chunk);
>         Ok(vec)
>     })
> });
> 
> // select on the request and the timeout
> // the first one to 'complete' will trigger our callback
> // since we converted the timeout to always be an error,
> // it will only ever be in the `Err` variant
> let work = future_body.select(timeout).then(|result| {
>     match result { 
>         Ok(body) => {
>             // do something with the body
>         },
>         Err(e) => {
>             // could be an http  or io error (including our time out error)
>             // inspect to find out which it was
>         }
>     }
> });
> handle.spawn(work);
> ```

Hello, I found your code have compile error. future_body.select need hyper::error

**Comment by rafrafek** [comment]
Will slow download trigger timeout?
