### ISSUE TITLE
Server: Handle a closed connection

### ISSUE THREAD

**Issue by shanegibbs** [hyperium/hyper#1099]
I see https://github.com/hyperium/hyper/issues/707. Is this possible with futures now?

I had a quick test using `tokio_timer`'s `Sleep` future. It didn't appear to drop the service when the client disconnected.

**Comment by seanmonstar** [comment]
What sort of test? What were you hoping to do, or hoping would happen?

**Comment by shanegibbs** [comment]
I modified the Echo example to test it -> [main.rs](https://github.com/shanegibbs/hyper-client-disconnect-example/blob/master/src/main.rs)

I was hoping the sleep future wouldn't complete. And/or the Echo service is `Drop`ed.

Ultimately, rather than waiting for the request to complete, I was interested in doing resource cleanup when the client disconnected. For example, cancel any running database queries.

**Comment by seanmonstar** [comment]
Understanding why doesn't work requires perhaps a bit more of an understanding of how `Future` in general works.

In this case, you've returned a `Future` that is basically `AndThen<Timer, FutureResult>`. So when tokio's internals receive this `Future` to drive the connection forward, it will be polling this `AndThen`. Inside the `AndThen::poll`, it will be calling `Timer::poll` until the timer is ready. Only then will then consider anything later in the chain. Therefore, when you want to add a timeout to any `Future`, you should usually `select` them together. A `Select<Timer, Other>` will poll both futures until one is ready or errors.

----

As for doing what you want, receiving notification that the socket has been closed, that may not actually be always easy to do. You'd need to somehow be `poll`ing on the `Stream` that holds the connection. You would definitely know if you were polling on the `body`, but there other situations that would be harder. 

For example, if you've read in the whole body, and are now doing other work, like talking to a database, there isn't really any way to ask if the socket is still alive. When writing the body, you are also in a tricky situation. If using the default `Body::pair()`, the `Sender` should be able to tell you an error occurred when using `start_send` and `poll_complete`. If using some other `Stream`, you may not be able to know directly. The `Stream` would be dropped once there was a socket error, so I suppose you could know in the `Drop` of a custom `Stream` whether it was consumed or not.

@alexcrichton or @carllerche, any thoughts on how to receive notification when one **isn't** polling the incoming body stream?

**Comment by alexcrichton** [comment]
@seanmonstar I'm not sure I quite understand, could you clarify? Naively it seems like that's a "nothing goes to sleep" situation, but I'm not sure.

**Comment by lhecker** [comment]
@seanmonstar I believe I'm currently facing this problem as well...

> If using the default `Body::pair()`, the `Sender` should be able to tell you an error occurred when using `start_send` and `poll_complete`.

...because that doesn't work for me.

I basically have a handler similar to this:
```rust
let (tx, rx) = hyper::Body::pair();

thread::spawn(move || {
    loop {
        tx = match tx.send(Ok(some_data_chunk)).wait() {
            Ok(tx) => tx,
            Err(err) => break,
        };
    }
});

return Response::new().with_body(rx);
```

Even if the client disconnects the above thread will never quit, because the `Sender` will always return `Ok(_)`. 😕

**Comment by seanmonstar** [comment]
With the new dispatcher in hyper, (used by default *except* when using with `TcpServer::new(Http::new())`) when the socket closes, the response body stream will no longer be polled indefinitely. The internal connection state will be dropped, and a call to `tx.send` should return an error.
