### ISSUE TITLE
Client doesn't appear to flush when waiting to read a response

### ISSUE THREAD

**Issue by alexcrichton** [hyperium/hyper#1108]
I was implementing a custom I/O stream to send requests over and I saw that the request was never actually written when it was waiting for a response. Turns out I was accidentally enabling buffering on the abstraction I was using and so none of the data was being flushed out.

I wonder if perhaps the client could flush the underlying I/O stream once it starts needing to read a request?

I do realize though that buffering at that layer isn't a great idea (and I've since disabled it), but I figured this'd be a semi-relevant issue regardless.

**Comment by seanmonstar** [comment]
Interesting! As `conn.poll_complete()` is called, we take that to mean to flush `Conn`s `write_buf` into the `io`, but then we don't actually call `io.flush()`. I assume that's the missing piece?

**Comment by alexcrichton** [comment]
I think so yeah, that'd make sense. This came up w/ a custom `AsyncRead + AsyncWrite` implementation so a call to `io.flush()` in `poll_complete` would do the trick.
