### ISSUE TITLE
Add struct for TE header field

### ISSUE THREAD

**Issue by sector-f** [hyperium/hyper#1109]
The TE header field is similar to Accept-Encoding, but for the Transfer-Encoding instead of the Content-Encoding

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/TE
Section 14.39 https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by almielczarek** [comment]
I'm interested in helping with this!

Just to make sure I am on the right track, I think what I should do is implement the TE struct using the `header!` macro, passing the `QualityItem<Encoding>` struct as this also has a notion of quality values, and then writing the documentation based off of RFC7230. Does this make sense?
