### ISSUE TITLE
How to use connection pooling with 0.10?

### ISSUE THREAD

**Issue by rsdy** [hyperium/hyper#1117]
I'm trying to use connection pooling with the 0.10 branch, but I'm having no luck. My setup involves several worker threads doing HTTPS requests using `hyper-rustls` against the same server with a [caddy](https://github.com/mholt/caddy) proxy in front of it, and I'd like to avoid the overhead of rotating the TCP connections underneath.

So far I've tried the recommended method mentioned in the documentation, sharing a single `hyper::Client` between the worker threads with no luck. I also tried using dedicated `Client`s for every thread, avoiding hyper's connection pooling code, but that doesn't work either. I'm using the `Connection: keep-alive` header for all requests.

When I start `tcpdump`ing what's going on, I can see that my application will send a FIN after every request, then RSTs the connection. I'm not sure how I could avoid this behaviour.

**Comment by seanmonstar** [comment]
Hi there! If you're not using `Client::new`, but `Client::with_connector`, you would need to configure a [`Pool`](https://hyper.rs/hyper/v0.10.5/hyper/client/pool/struct.Pool.html) also.

As this is a usage question and not really a bug, I'm going to close.

**Comment by rsdy** [comment]
This is the code I have used to initialise the `Client`, ie. explicitly pass in a `Pool`. Sorry I missed this detail:

```
let client = Client::with_connector(Pool::with_connector(PoolConfig { max_idle: 16 },
                                                         HttpsConnector::new(TlsClient::new())));
```

**Comment by rsdy** [comment]
@seanmonstar do you have any other tips why this might not be working? As far as I can tell, I'm using the library correctly, and connection pooling still doesn't work.

**Comment by seanmonstar** [comment]
Sorry, it didn't notify me of the edit.

A very common gotcha with hypers Pool is that you must read the full response for that socket to be reusable. 

Besides that, I assume the host is the same, that the version is HTTTP/1.1 (not 1.0), and there's no Connection close header?

**Comment by rsdy** [comment]
Thanks a lot! Reading the result fully seems to have done the trick. Awesome.
