### ISSUE TITLE
panic! when re-using Client for multiple requests

### ISSUE THREAD

**Issue by dobrite** [hyperium/hyper#1118]
I am using `master` with the new future based `Client` using `tokio`. I am wanting to make many concurrent `POST` requests to an nginx server over localhost.

During load testing I ran into an a panic [here](https://github.com/alexcrichton/futures-rs/blob/master/futures-cpupool/src/lib.rs#L389) when using `Client::new` as I think each `Client` gets 4 `DNS` threads. I then created a single client with 16 threads and re-used it via `client.request`.

cpu pool panic:
```
panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } }'
```

My artificial load test works, but when a real work load is sent through, it fails on the first request with a panic [here](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L160) with the message:

```
panicked at 'unimplemented error handling: Error { repr: Custom(Custom { kind: Other, error: StringError("request / response mismatch") })
```

If I revert back to creating a new `Client` on each request it works (but will panic in `futures-cpupool`).

Is this the right setup for doing what I'd like to do, and any advice on what the error means, or how to fix it?

**Comment by seanmonstar** [comment]
Ah interesting. It seems a few things have gone wrong here.

The `CpuPool` is calling `unwrap` on the spawn of the thread, and when you've created a bunch of hyper `Client`s, and thus a bunch of thread pools, the spawning fails and the unwrap panics. futures-cpupool probably needs to not panic but return a `Result` here. @alexcrichton does that seem reasonable?

-----

The second part is much harder to diagnose. The gist is that the Connection from hyper is receiving a Response, and when given back through tokio-proto's plumbing, tokio finds that there isn't a waiting future to receive it. This could mean that either the waiting future was dropped somehow before getting a response, but the connection was asked for a response anyways (it should have dropped when the `FutureResponse` dropped), or hyper's Connection is receiving, parsing, and notifying of a second `Response` after the first, and so there's no waiting future to receive it.

If you could, a pastebin of logs for `hyper` and `tokio-proto` at the `trace` level would be a great help!

**Comment by alexcrichton** [comment]
Yeah it seems reasonable for there to be a constructor on `CpuPool` which returns a result

**Comment by dobrite** [comment]
I was unable to reproduce the second panic. Everything is working great on my end 👌 . I'll re-open if it happens again and will be sure to get those logs too.

Thanks for all the work everyone does! It has been an amazing experience developing in Rust. 🎉
