### ISSUE TITLE
client: missing IntoFuture implementation on Response?

### ISSUE THREAD

**Issue by lucab** [hyperium/hyper#1132]
Using hyper and futures, I ended in a chain of futures where I am having a hard time combining all the resulting types. In particular, inside a combinator I have a `Response` from one side (the current request) and a `FutureResponse` from the other side (a newly spun request). However I seem not to be able to bridge between the two types as FutureResponse constructor is private, and the IntoFuture/FromFuture traits are not implemented for the conversion to happen. My understanding is that a `into_future()` or `from_future()` should be provided by hyper due to the custom newtype.

I may me misunderstanding something or missing some other easier way to do this, in which case I'll gladly take some hints and close this.

**Comment by seanmonstar** [comment]
`client::FutureResponse` implements `Future`, which means it automatically implements `IntoFuture`. You won't get the `Response` from it until after it resolves, like with `future_resp.and_then(|res| now_i_have_a_response(res))`.

**Comment by lucab** [comment]
I'm fine with `FutureResponse`, the hard times are coming from trying to do an async conversion on an already resolved `Response` (and perhaps doing it the wrong way).

In a simplified snippet similar to my combinator:
```
client1.request(req1).and_then(move |r| {
  if r.status() == StatusCode::ImATeapot {
    client2.request(req2) // This is a FutureResponse
  } else {
     // ... I would have expected a r.into_future() here
 }).flatten().from_err();

**Comment by seanmonstar** [comment]
Oh OK, so you have a closure where you want to return 2 different types, either a `Response`, or a `FutureResponse`. You could probably use the `Either` type from `futures`:

```rust
and_then(move |r| {
  if r.status() == StatusCode::ImATeapot {
    Either::A(client2.request(req2))
  } else {
    Either::B(futures::future::ok(r))
  }
}).flatten()
```

**Comment by lucab** [comment]
First, thanks for the quick feedback (and sorry, I should have provided a snippet earlier)! `future::Either` does indeed fit this scenario and solve my issue (I just missed its existence before).

> so you have a closure where you want to return 2 different types

OTOH, this is not exactly what I was planning to do. I naively wanted to reconcile the already-resolved `Response` back to its async counterpart as I know that all the other branches of that closure will return `FutureResponse`. Wrapping everything in a Either looks like a perfect generic solution, but here I instinctively looked for a simpler async conversion, which looks like is not really possible by design/constraints?

**Comment by seanmonstar** [comment]
I know what you mean, I was just saying that the types are distinct, and so therefore Rust complains. It's common in something like JavaScript where you can return either an immediate value or a promise, it just works. I wonder if that pattern can be made any nicer in Futures...
