### ISSUE TITLE
Connection Keepalive

### ISSUE THREAD

**Issue by bkchr** [hyperium/hyper#1134]
Hi, I'm currently using the hyper master branch. I have written a Service and want that the connection is dropped after each request. I thought that using "Http::keep_alive(false)" should close the connection? But that does not work. Is this a bug or do I use the wrong functionality?

**Comment by seanmonstar** [comment]
Turns out a bug had snuck in, and test coverage wasn't making sure keep-alive turned off worked. New PR with a fix is currently going through CI, fix merged soon. Thanks for the report!

**Comment by bkchr** [comment]
Thx for the fast support :)
