### ISSUE TITLE
why main struct need Clone + Copy

### ISSUE THREAD

**Issue by daogangtang** [hyperium/hyper#1170]
in the example/server.rs

```
#[derive(Clone, Copy)]
struct Echo;

impl Service for Echo {
    type Request = Request;
    type Response = Response;
    type Error = hyper::Error;
    type Future = FutureResult<Response, hyper::Error>;
```
struct Echo need Clone + Copy, this limit is some strict.

**Comment by seanmonstar** [comment]
It shouldn't be required. In fact, since that can be distracting from just showing what is needed to get the example working, those could be removed.

**Comment by daogangtang** [comment]
but, if I remove this, an error will occur later
```
   Compiling sapper v0.1.0 (file:///home/mike/works2/sapper)
error[E0525]: expected a closure that implements the `Fn` trait, but this closure only implements `FnOnce`
   --> src/app.rs:184:13
    |
184 |             || Ok(self_box)
    |             ^^^^^^^^^^^^^^^
    |
note: the requirement to implement `Fn` derives from here
   --> src/app.rs:182:34
    |
182 |         let server = Http::new().bind(
    |                                  ^^^^

error[E0308]: mismatched types

```

**Comment by seanmonstar** [comment]
That's because you've moved a box from outside the closure, and then your try to return (move again) it from the closure. A box can only be moved out of the closure once.

**Comment by daogangtang** [comment]
hi, I can run it now.

https://github.com/sappworks/sapper 

Thx.

Sapper now follow up hyper's latest updates, and I bench them just now, seems nice.
https://github.com/sappworks/sapper/wiki/Dev-version-benchmark.
