### ISSUE TITLE
Add connect timeout, in addition to read/write timeouts for client

### ISSUE THREAD

**Issue by alex** [hyperium/hyper#1172]
Right now you can set a read timeout, and a write timeout on a client, but not a connect timeout. This means certain types of TCP failures will just hang for the OS determined length of time for a TCP connect (2 minutes or something on many OS, IIRC).

**Comment by seanmonstar** [comment]
Unfortunately, there is no connect timeout to specify. The `connect` call ignores any socket option timeout. Additionally, before connect, there's a synchronous DNS lookup `getaddrinfo`, which also does not take a timeout.

Both of these are not a problem with non blocking IO, because you can stop waiting for a non blocking socket whenever you want...

**Comment by alex** [comment]
Right, so the way to implement this would be to create the socket, set it non-blocking, initiate the connect, and the select on it with the timeout value. That should be implementable without changing the blocking API.

For my particular case, I'm not particularly worried about the blocking DNS lookup, so just doing the `fcntl(fd, F_SETFL, O_NONBLOCK)` + `connect()` + `select()` dance would be a huge win.

**Comment by sfackler** [comment]
`HttpConnector` is defined as a unit-struct, so it unfortunately can't support a connect timeout without a breaking change, but everything's luckily pluggable so it should be straightforward to make a connector that wraps the connect/select dance: https://hyper.rs/hyper/v0.10.11/src/hyper/net.rs.html#393

**Comment by sfackler** [comment]
I've implemented this: https://github.com/sfackler/hyper-timeout-connector

Waiting on https://github.com/alexcrichton/socket2-rs/pull/1 to be merged before it can be published, though.

**Comment by sfackler** [comment]
This is now published: https://crates.io/crates/hyper-timeout-connector

**Comment by seanmonstar** [comment]
As 0.10.x is no longer actively developed, I'm going to close this.

**Comment by alex** [comment]
@seanmonstar 👍  tokio made this way easier in that I can just do a `client.get(...).select(timeout)` and it covers everything.
