### ISSUE TITLE
Current master docs for `hyper::server::Http::bind_connection` confusing

### ISSUE THREAD

**Issue by sanmai-NL** [hyperium/hyper#1180]
https://hyper.rs/hyper/master/hyper/server/struct.Http.html#method.bind_connection:
> This method is typically not invoked directly but is rather transitively used *through the `serve` helper method above*. This can be useful, however, when writing mocks or accepting sockets from a non-TCP location.

There's no `serve` helper method above. Did you mean `bind`? I'm not even sure, reading these docs quickly for the first time. As a general suggestion, is it possible to reference items using hyperlinks instead, to make it clearer?

**Comment by seanmonstar** [comment]
My guess is that those docs were written/copied with tokio-proto's `TcpServer` in mind, since `serve` is a method on that type. It should have mentioned `bind` instead, you're correct.
