### ISSUE TITLE
Howto TLS?

### ISSUE THREAD

**Issue by MarkSwanson** [hyperium/hyper#1181]
I'm upgrading Hyper to 0.10.10. I had all of the TLS issues worked out fine in an older Hyper but things seem to have changed quite a bit.
The recommended mechanisms for enabling TLS in Hyper do not allow me to specify my own OpenSSL context. As this worked perfectly fine (for me) in an earlier version I assume this is possible in the 0.10.10 release.

Example: this used to work:

```
let mut server = Server::https(sock_addr, Openssl {context: Arc::new(ssl_ctx)} ).unwrap();
```

What should I do now?

Thanks.

Notes:
hyper_native_tls was recommended, but does not work (no mechanism for specifying certs etc.)

hyper_rustls::TlsServer will not work because it is too simplistic / doesn't provide the functionality I require. (I require the ability to set many of the SslContextBuilder settings)

hyper::net::SslServer -> it seems this trait is required for Server::https() - but the documentation states there are no implementations available.

hyper-tls -> will not work - the examples seem to indicate this is client only.

The documentation for hyper::Server states: You can use any SSL implementation, as long as implements hyper::net::Ssl.
  - However, the trait `hyper::net::SslServer` is not implemented for `openssl::ssl::SslContext`

  - It seems this is from an older Hyper (0.8.0) ?? https://hyper.rs/hyper/0.8.0/hyper/net/struct.Openssl.html  - which does not work with Hyper 0.10.10 ??

I feel like I just googled for the wrong thing, and a correct search would give me an example as the first link :-) ??

**Comment by dmizuk** [comment]
How about [`hyper-openssl`](https://github.com/sfackler/hyper-openssl)?
Its `OpensslServer` implements `hyper::net::SslServer` and `From<openssl::ssl::SslAcceptor>`.

**Comment by MarkSwanson** [comment]
Thanks, but hyper-openssl will not work either because I can't pass it an SslContext.

**Comment by MarkSwanson** [comment]
Ok, I see that if I back down to Hyper 0.9.18 that things seem to be working the same way as the old version I was using, and yet it's new enough that I can resolve my cargo dependency issues.
I've switched to 0.9.18 and I think I'll be happy with that (I say think because I now have so many compile errors to resolve :-)

It looks like the 10.x branch is a major rewrite in this area - so feel free to close this if you feel that this ticket would only distract you from your current plans.

Thanks again for Hyper!

**Comment by seanmonstar** [comment]
By making use of an [`SslAcceptorBuilder`](https://docs.rs/openssl/0.9.12/openssl/ssl/struct.SslAcceptorBuilder.html), you can access the `SslContext`, and then wrap it all up into an `SslAcceptor` used by `hyper-openssl`.

I highly recommend you do that instead of use hyper 0.9.18. The 0.9.x set of version will not receive any more updates or bug fixes.
