### ISSUE TITLE
The restriction on the length of the content with a high RPS

### ISSUE THREAD

**Issue by vovagp** [hyperium/hyper#1184]
```
curl --head http://127.0.0.1:3000/
HTTP/1.1 200 OK
Content-Length: 8115
Date: Thu, 11 May 2017 21:45:09 GMT
```

8115 + 78 (headers size) = 8193

And wrk resut:
```
Requests/sec:    226.73
```

For
```
curl --head http://127.0.0.1:3000/
HTTP/1.1 200 OK
Content-Length: 8114
Date: Thu, 11 May 2017 21:48:14 GM
```

result is
```
Requests/sec: 127066.00
```

wrk runned as:

```
-t8 -c300 -d30s --latency --timeout 2s http://localhost:3000/
```

Hyper 0.10.10

**Comment by seanmonstar** [comment]
It appears to be a bug in wrk. You can exercise it without hyper, just tcp streams, using this program here: https://gist.github.com/seanmonstar/a24424bc625f633c13dac5ab5eb20c64

hyper is using the `BufWriter` from `std`, which has an 8192 byte buffer. First the headers are buffered, and then the body is written. However, `BufWriter` will check if it can fit the bytes in its buffer, and if it cannot, it will first flush the current buffer, and then write the next bytes. So in your example, that ends up meaning to 2 syscalls to `write`. On wrk's end, it doesn't seem to handle needing to read a second time in an efficient manner.

The pasted gist shows this same behavior, even with a tiny payload, as long as it was split over 2 writes.

**Comment by vovagp** [comment]
Well, that's your opinion. But I still think that this is a problem on the server side. In this case, in the Hyper logic.

OFFTOPIC:

Example for [Netty](https://netty.io/):

```
$ curl -I http://127.0.0.1:8080/
HTTP/1.1 200 OK
Content-Type: text/html
X-Netty: 4.1.10.Final
Content-Length: 60000
Connection: keep-alive
```

```
$ wrk -t8 -c300 -d30s --latency --timeout 2s http://127.0.0.1:8080/
Running 30s test @ http://127.0.0.1:8080/
  8 threads and 300 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    27.67ms   17.31ms 251.93ms   84.73%
    Req/Sec     1.40k   348.24     5.00k    69.85%
  Latency Distribution
     50%   22.78ms
     75%   34.00ms
     90%   48.13ms
     99%   91.91ms
  332801 requests in 30.09s, 18.63GB read
Requests/sec:  11061.49
Transfer/sec:    634.15MB
```

Same version of wrk work correctly.

**Comment by sanmai-NL** [comment]
@vovagp: So what you mean is you want to control the buffer size? @seanmonstar: Maybe I'm missing something but is this possible? That seems to provide the reporter what he needs to attain the performance he expects.

**Comment by vovagp** [comment]
@sanmai-NL If possible. With biggest or dynamic buffer size we will get more than 226 RPS in highload system when content size more than 8192 bytes.

**Comment by seanmonstar** [comment]
I remembered that the 2nd write could be delayed due to Nagle's, and sure enough, call `sock.set_nodelay(true)` in the example program makes it fast, no matter how big the various writes are.

Disabling Nagle's by default isn't typically done, as it is usually useful. Disabling it should only be done when measuring shows it has. You could call `set_nodelay` in a custom `NetworkListener`.
