### ISSUE TITLE
Docs needed: how protect transport to server with TLS?

### ISSUE THREAD

**Issue by sanmai-NL** [hyperium/hyper#1186]
Given `hyper` in the `master` branch, how can you set up TLS based on [`rustls`](https://github.com/ctz/rustls)? Is the [`tokio-rustls`](https://github.com/quininer/tokio-rustls) crate appropriate and should it be combined with [`bind_connection`](https://hyper.rs/hyper/master/hyper/server/struct.Http.html#method.bind_connection)? There are a number of other GitHub repos available that are supposed to do something with TLS and `hyper`. It would be great of the confusion can be reduced with at least a short note/pointer in the docs.

**Comment by seanmonstar** [comment]
I have not followed rustls' development at all, so I couldn't give a recommendation. hyper's master branch hasn't been released yet, but I imagine when it is, all the `hyper_*` TLS crates will update to make use of it.

**Comment by sanmai-NL** [comment]
Alright, I thought you were about to release the redesigned `hyper` very soon, and so the TLS story we may want to document in advance.

**Comment by seanmonstar** [comment]
Yes, I'd love to release. I don't maintain all the various TLS implementations, though. I know the tokio-tls crate works with hyper master. I'm not sure I'd want to point at a specific library as THE TLS library to use, when many seem to have different pros and cons.

**Comment by sanmai-NL** [comment]
Ah, then we had a miscommunication. I was merely suggesting `rustls` as an example implementation (that I happen to be interested in most). Currently, AFAICT, there is no documentation on how to set up an HTTP server with TLS given current `hyper` master at all. Could you point me to such docs, and if absent/incomplete/misplaced, tell me what you'd like the docs to be? Maybe others like me can do the documentation work then.

**Comment by lucab** [comment]
Related https://github.com/ctz/hyper-rustls/pull/19. AFAICT the server part is missing from there.

**Comment by sanmai-NL** [comment]
I think this can be closed now, since @lucab wrote [the example](https://github.com/ctz/hyper-rustls/blob/f6182e52b6b965538629ef0c4bf40fbd6bcd0889/examples/server.rs).
