### ISSUE TITLE
Linking to Hyper API docs question

### ISSUE THREAD

**Issue by matthewkmayer** [hyperium/hyper#1193]
Thanks for the hard work on the crate, it's much appreciated!

A question came up in Rusoto (https://github.com/rusoto/rusoto/issues/567) on how to link to Hyper docs.  Since we have a *lot* of docs to generate, we only generate docs for our library using this command: `cargo doc --all --no-deps`.

This leads to broken links.  For example, Rusoto code using Hyper [refers to a Hyper Client](https://rusoto.github.io/rusoto/rusoto_core/request/trait.DispatchSignedRequest.html) but the link 404s.  Said link is the `Client` link at the bottom of the page.  It takes you to:

`https://hyper.rs/hyper/v0.10.10/hyper/hyper/client/struct.Client.html`

instead of the correct URL of

`https://hyper.rs/hyper/v0.10.9/hyper/client/struct.Client.html`.

Note the extra `hyper` in the first URL.  I assume the version difference of `0.10.10` vs `0.10.9` is due to Hyper release docs not being pushed for 0.10.10 but I could be mistaken. 😄 

How should we fix the autogenerated link so it points to the right spot?

**Comment by dtolnay** [comment]
There are two problems.

- Docs for 0.10.10 have not been published to hyper.rs.
- The html_root_url [here](https://github.com/hyperium/hyper/blob/v0.10.10/src/lib.rs#L1) should not have the last `/hyper` on the end.

These are breaking the documentation of reqwest as well.

Let's release 0.10.11 with a fixed html_root_url and upload documentation for both 0.10.10 and 0.10.11.

**Comment by seanmonstar** [comment]
There is now a v0.10.11 published, docs are uploaded, and proper doc attribute set. Sorry about the inconvenience.

**Comment by matthewkmayer** [comment]
👍 upgraded the Hyper dep and ran docs locally, the link now works. Thanks!
