### ISSUE TITLE
Reimplement StatusCode and HttpVersion using associated constants

### ISSUE THREAD

**Issue by dtolnay** [hyperium/hyper#1195]
The associated constants feature is *almost* ready. https://github.com/rust-lang/rust/issues/29646

Something like:

```rust
pub struct StatusCode(pub u16);

impl StatusCode {
    pub const OK: StatusCode = StatusCode(200);
    /* ... */
}
```

A few advantages:

- We can easily add new codes as the relevant standards change. Currently adding a new status code would involve a breaking change to hyper.
- Resolves the ambiguity around whether StatusCode::Ok is equal to StatusCode::Unregistered(200).
- The size of a status code goes from 4 bytes to 2 bytes which is what it should be.

**Comment by seanmonstar** [comment]
Blocked by https://github.com/rust-lang/rust/issues/29646

**Comment by seanmonstar** [comment]
This was done in the [http](https://crates.io/crates/http) crate. The types there will replace the ones here in hyper in v0.12.
