### ISSUE TITLE
futures dependency has a very specific version pin

### ISSUE THREAD

**Issue by jbg** [hyperium/hyper#1197]
The futures dependency is defined as

```futures = "0.1.11"```

I have been maintaining a fork for a little while with it defined as

```futures = "0.1"```

in order to get a few fixes in `.12/.13/.14` and haven't had any trouble. Is there a reason for the very specific version pin?

**Comment by seanmonstar** [comment]
The version defined in the Cargo.toml is a minimum version (but less than 0.2). If you cargo update, it will use the newer patch versions.

The reason for the minimum futures is to force anyone who has hyper with an older version to upgrade futures to when it gained `Stream::concat`.

**Comment by jbg** [comment]
Thanks for the explanation. I had not run `cargo update` and was having problems with multiple versions of futures being installed, which lead to me making the fork. This can be closed!
