### ISSUE TITLE
Should  hyper point at docs.rs for published docs?

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1205]
It's useful to have https://hyper.rs/hyper/master, but for published versions, perhaps it's better to just point at https://docs.rs/hyper. The existence of https://hyper.rs/hyper is from before docs.rs was created.

**Comment by Thomspoon** [comment]
Is there away to provide the unannounced [guides](https://hyper.rs/guides/) in a way that makes sense?

**Comment by seanmonstar** [comment]
Done with v0.10.12, and will be done for v0.11 too.
