### ISSUE TITLE
under hyper::server::Request, remote_addr() is a None

### ISSUE THREAD

**Issue by TerraX-net** [hyperium/hyper#1208]
When I search for "remote_addr" in this repository, there aren't much results.
My current thought is that this is not implemented in master yet (for the new futures etc.).
```
 let remote_addr = match req.remote_addr() {
	None => "empty".to_string(),
	Some(x) => {
			println!("user's ip: {}",x.ip());
			format!("{}:{}", x.ip(), x.port())
	}
};
println!("[{}] {} {} {}", time, method, path, remote_addr);
```

console output:
`[2017-06-05 15:11:37.476951754 UTC] GET / empty`

I expected to get the client IP and Port of the visitor here.

And scheme(), host(), port() of [req.uri()](https://hyper.rs/hyper/master/hyper/struct.Request.html#method.uri) seem also to be empty.

Edit:
Maybe this is because of tokio-rustls
( https://github.com/quininer/tokio-rustls/ ).

**Comment by TerraX-net** [comment]
I would like to apologize, tokio-rustls causes this behavior.

**Comment by seanmonstar** [comment]
To clarify, the `Request` has the ability to store the `remote_addr`. If you use hyper's easy-mode server, `Http::bind()`, it will fill it in. The reason it isn't always there is `Http` is an implementation of `ServerProto` from tokio, and is generic over the IO stream used. Some streams might not have socket addrs, like `UnixStream`, and there's not generic way (not in any of the traits) to get the remote address, for that reason.
