### ISSUE TITLE
Client error handling on ChunkedBody

### ISSUE THREAD

**Issue by d33d33** [hyperium/hyper#1210]
I can not figure out how to catch error emitted by ChunkedBody::read.

It's look like they are simply discarded, see: https://github.com/hyperium/hyper/blob/0.10.x/src/client/mod.rs#L335

**Comment by seanmonstar** [comment]
You are seeing an error reading a chunked response from a server, or there is an error occurring in the `read` function of a `Body` provided for a client request?

**Comment by d33d33** [comment]
The error occur inside the `read` function of a `Body` provided to a client.
Still a wip but it may help you to understand the issue: https://github.com/runabove/beamium/blob/threads/src/sink.rs#L305

**Comment by seanmonstar** [comment]
I see it, fixed committed. Will be in 0.10.12. Thanks!

**Comment by d33d33** [comment]
So fast :D
You rocks!

**Comment by apoelstra** [comment]
FYI this changes the behaviour when sending on stale connections from returning a `ConnectionAborted` error to returning a `BrokenPipe` error. Code which detected this when deciding whether to just retry sending or treat it like a real error will break.
