### ISSUE TITLE
HTTP Parsing & Custom Headers in 0.11

### ISSUE THREAD

**Issue by illegalprime** [hyperium/hyper#1223]
I'm excited about the `0.11` release because that means I can finally get rid of the glue I have between synchronous hyper and asynchronous websockets. I'd like to upgrade to the newest hyper (see cyderize/rust-websocket#132). From preliminary tries I've run into two issues:

1. There is no way to parse raw requests / responses (`::from_wire` is private)
2. There is no way to make custom headers (some dependent traits are private)

Granted my use case isn't common, so I'm wondering how to move forward. I like hyper's headers system and that's the main reason I'm using it. Maybe something like a `hyper-headers` crate?

**Comment by seanmonstar** [comment]
1. I imagine I'd keep `from_wire` private for now, but parsing some bytes and constructing a `Request` or `Response` manually is possible right now. You can use a parser, like `httparse`, and the constructors `Request::new` and `Response::new` are public.
2. What dependent traits prevent creating custom headers? The doctests for the `Header` trait effectively run in a separate crate (the design of rustdoc), and they show creating new custom traits: https://docs.rs/hyper/0.11.0/hyper/header/index.html

**Comment by illegalprime** [comment]
1. I wanted to parse some bytes into hyper headers, what would be the best way to do that?
2. I was talking about `HeaderClone` and `GetType`, but I see your example, thanks!

**Comment by seanmonstar** [comment]
If you have bytes, you can use `headers.set_raw` to add them.
