### ISSUE TITLE
Handle wildcard character for AccessControlAllowMethods

### ISSUE THREAD

**Issue by KiChjang** [hyperium/hyper#1235]
The [fetch specification](https://fetch.spec.whatwg.org/#http-access-control-allow-methods) has defined a new ABNF form for the header as follows:
```
Access-Control-Allow-Methods     = #method / wildcard
wildcard                         = "*"
```

whereas hyper currently supports the following ABNF:
```
Access-Control-Allow-Methods: "Access-Control-Allow-Methods" ":" #Method
```

**Comment by seanmonstar** [comment]
For now, the new version of hyper won't be including the typed headers directly, so I'm closing this here as a won't fix.
