### ISSUE TITLE
[question: Client] Is there ProxyConnector that works with HttpConnector from hyper-tls

### ISSUE THREAD

**Issue by timgluz** [hyperium/hyper#1236]
Hi,

i'm currently refactoring from `0.10.x` to `0.11` and i like cleaner and simpler interface of `0.11`;

I am just wondering how i could replace `Client::with_proxy()` so i could get proxy support.
Is there a cargo for ProxyConnector like `hyper-tls` is for SSL?
If not, how big tasks it will be for newbie to get it started?

Or is there any better solution?

**Comment by seanmonstar** [comment]
I'd recommend trying reqwest. The newest version  on master includes the upgrade to hyper 0.11, and has proxy support. It's not yet released on crates.io, trying to get that out this week.

It also includes an async API, marked unstable.

**Comment by seanmonstar** [comment]
I'm going to close, since this is a usage question, instead of a bug. Cheers!

**Comment by timgluz** [comment]
Ok, thanks;
