### ISSUE TITLE
Sharing data Arc<Mutex<SharedData>> with the Service trait

### ISSUE THREAD

**Issue by RCasatta** [hyperium/hyper#1239]
I have two thread, one which is populating some SharedData, the other one which is serving this SharedData through http. I am trying to use Mutex to share data between threads

I changed the hyper server example like this:
```
struct HelloWorld {
    shared_data : Arc<Mutex<SharedData>>,
}

pub fn start(my_data : Arc<Mutex<SharedData>>) {
    let addr = "127.0.0.1:3000".parse().unwrap();

    let server = Http::new().bind(&addr, || Ok(HelloWorld{
        shared_data : my_data
    })).unwrap();
    server.run().unwrap();
}

```

but it fails with:
```
error[E0525]: expected a closure that implements the `Fn` trait, but this closure only implements `FnOnce`
```

I cannot derive the copy trait `#[derive(Clone, Copy)]` for a struct containing `Arc`

what should I do?

**Comment by hjr3** [comment]
@RCasatta I believe Rust is making this closure of type `FnOnce` because you are closing over the `my_data` value. In order to make it a closure of type `Fn` we need to move `my_data` into the closure and then clone it.

```rust
    let server = Http::new().bind(&addr, move || Ok(HelloWorld{
        shared_data : my_data.clone()
    })).unwrap();
```

**Comment by RCasatta** [comment]
It works, thanks and sorry for the more rust than hyper question, I am a rust newbie
