### ISSUE TITLE
Way of going from server::Request to the SSL connection

### ISSUE THREAD

**Issue by alex** [hyperium/hyper#1241]
hyper 0.10 had https://docs.rs/hyper/0.10.12/hyper/server/request/struct.Request.html#method.ssl to take you from a server request to the SSL connection. This was needed for things like client certificates.

I don't see an equivilant to this functionality in 0.11, it'd be great to bring it back!

**Comment by seanmonstar** [comment]
One could currently implement a `ServerProto` that is able to check the transport for anything before saying it is OK to be used with a `Service`.

**Comment by alex** [comment]
I'm still learning my way around the tokio ecosystem, but for my application just being able to filter before my application isn't enough, I need the actual contents of the client certificates in the app itself.

**Comment by seanmonstar** [comment]
A `Service` serves a connection. Would you need the certificate within the context of each request made on the same connection?

**Comment by alex** [comment]
Yup. (https://github.com/alex/ct-tools is the application, it's an app specifically geared to help people interact with their client certs + certificate transparency)

**Comment by seanmonstar** [comment]
So, we're considering that `Request` and `Response` gain a typemap-like thing that can contain extensions. The original thought is that it would be able to contain HTTP2 extensions, but it could be used to store anything. Perhaps a wrapper can set `req.extensions_mut().set(some_cert)`, and users' services can check for the `req.extensions().get::<Cert>()` (or whatever the type is).

**Comment by alex** [comment]
I'm not very familiar with the internals of hyper -- is the hyper 0.10 approach of exposing the `ssl<T>()` method no longer technically possible, or just not consistent with the API you're trying to offer?

**Comment by seanmonstar** [comment]
The `Request` and `Response` have no concept of the underlying transport by design. So that previous method can't really work.

**Comment by alex** [comment]
I suppose the extensions dealio makes as much sense as anything, given that constraint.

**Comment by seanmonstar** [comment]
Another alternative is that since the `Service` is constructed at the start of the connection and used to serve all requests on it, the certificate could be grabbed in a `NewService` implementation and stored on the `Service`.

```rust
struct ClientCertService {
    cert: Option<Cert>,
}

impl Service for ClientCertService {
    fn call(req: Request) -> Self::Future {
        // check self.cert
    }
}
```

This would require `NewService` to gain a way to inspect the transport...

**Comment by alex** [comment]
Hmmm, that makes a fair bit of sense to me.
