### ISSUE TITLE
Don't close a keep-alive connection on 204 (No Content) Response from server

### ISSUE THREAD

**Issue by lumasepa** [hyperium/hyper#1242]
Right now Hyper closes the connection when the server responds with status code 204 and the connection have the keep-alive header and the client have the keep-alive setting. This is a problem because even if the server says that there is no content the client may want to request more resources

Finagle had the same problem, for reference https://github.com/twitter/finagle/issues/563.

**Comment by seanmonstar** [comment]
Thanks for the report! There used to be code to properly handle 204s and 304s, but it was lost in the redesign to async. I'm adding it back in. The fix will be included when 0.11.2 is released.
