### ISSUE TITLE
Allow more than one AccessControlAllowOrigin header

### ISSUE THREAD

**Issue by asajeffrey** [hyperium/hyper#1243]
This came up in the context of https://github.com/servo/servo/pull/16508#issuecomment-312916582, and is causing web platform tests that use more than one `Access-Control-Allow-Origin` header. Currently, hyper only allows one of them (https://github.com/hyperium/hyper/blob/7ce31211320d76c1bc60493b62d1e9ecfbff8048/src/header/common/access_control_allow_origin.rs#L64).

**Comment by jdm** [comment]
Note - there are a ton of search results for "multiple access-control-allow-origin" that imply that servers that return multiple values are incorrect. The solution here may not be to change the header definition.

**Comment by asajeffrey** [comment]
Hmm, the CORS spec here is, er, unenlightening: https://www.w3.org/TR/cors/#access-control-allow-origin-response-header. The grammar allows more than one origin, but there is a note "In practice the origin-list-or-null production is more constrained. Rather than allowing a space-separated list of origins, it is either a single origin or the string "null"."

The web platform tests are quite explicit about adding more than one such header (https://github.com/w3c/web-platform-tests/blob/b37004f3d52b3b53a5db51cfc488ed415bd6b610/fetch/api/resources/preflight.py#L10-L11):
```python
    for origin in request.GET['origin'].split(", "):
        headers.append(("Access-Control-Allow-Origin", origin))
```
I think the note in the CORS spec isn't normative, so the implementation should allow more than one header?

**Comment by seanmonstar** [comment]
Probably related: #1235 

I'm fine with making whichever change is needed to keep up with the spec. It would probably mean a breaking change, so it couldn't be released super quickly. If the change is made, it's probably a good idea to close up the internals of the header, to allow future changes to not be breaking...

Also, if needed more quickly, the header can also be defined in Servo.

**Comment by asajeffrey** [comment]
Yes, this is a breaking change, sigh.

**Comment by seanmonstar** [comment]
For now, the new version of hyper won't be including the typed headers directly, so I'm closing this here as a won't fix.
