### ISSUE TITLE
info! level logging for every request

### ISSUE THREAD

**Issue by markuskobler** [hyperium/hyper#1247]
Commit [04d34f4b651ca4d9fb3d5e5a803419457618afee](https://github.com/hyperium/hyper/commit/04d34f4b651ca4d9fb3d5e5a803419457618afee) seems to have introduced `info!` level logging for every request.

What was the thinking for introducing this change and should this level of logging be made configurable as it can be very chatty for apps that use the `log` crate?

**Comment by seanmonstar** [comment]
The thinking was that up until now, hyper has pretty much only used `trace` and `debug`, and those are incredibly noisy. To improve debugging for users, I wanted to make better use of the levels. An incoming request seems about an `info` level item.

As for being configurable, the `log` crate makes that possible, any logger can filter via module path and level.

**Comment by markuskobler** [comment]
Ok makes sense. For anyone else that stubbles across this you can simply write something like 
```
