### ISSUE TITLE
Getting started with a Client documentation is incomplete

### ISSUE THREAD

**Issue by markstory** [hyperium/hyper#1248]
I'm having some troubles getting the [getting started with a client tutorial](https://hyper.rs/guides/client/basic/) working. I created a blank new project with cargo (using rust-nightly):

```bash
cargo init --bin hyper-demo
```

Then updated the `Cargo.toml` to look like:

```toml
[package]
name = "hyper-demo"
version = "0.1.0"
authors = ["Mark Story <mark@mark-story.com>"]

[dependencies]
hyper = "0.11"
```

and updated my `src/main.rs` to contain the following based on the first steps of the tutorial

```rust
extern crate futures;
extern crate hyper;
extern crate tokio_core;

fn main() {
    println!("Hello, world!");
}
```

And attempted to build the project, but got the following error from rustc

```bash
$ cargo run
    Blocking waiting for file lock on build directory
   Compiling hyper v0.11.1
   Compiling hyper-demo v0.1.0 (file:///Users/markstory/Sites/rustlang/hyper-demo)
error[E0463]: can't find crate for `futures`
 --> src/main.rs:1:1
  |
1 | extern crate futures;
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: Could not compile `hyper-demo`.
```

The only way I could get the project to build was to update my `Cargo.toml` to contain `futures` and `tokio_core`. Is that something that should be added to the tutorial, or have I missed a step?

**Comment by seanmonstar** [comment]
Hm, you're right, I didn't remember to include a section on dependencies in the Client guide. I kind of took for granted the knowledge that an `extern crate` requires a corresponding dependency in your `Cargo.toml`.

**Comment by markstory** [comment]
Would you be open to having the docs updated to be more noob friendly? I am happy to make the changes of you can tell me where to find to guide sources.

**Comment by seanmonstar** [comment]
I can get it soon, but if you want, the guide is at https://github.com/hyperium/hyperium.github.io/blob/master/_guides/client/basic.md

**Comment by markstory** [comment]
Thanks for pointing me in the right direction. I will try to have a pull request up this weekend.

**Comment by faraazahmad** [comment]
[You're Welcome.](https://github.com/hyperium/hyperium.github.io/pull/10) :smile: 
My first PR related to Rust.

**Comment by seanmonstar** [comment]
The docs were updated to include the `Cargo.toml` part, thanks @faraazahmad!
