### ISSUE TITLE
UNIX domain socket support

### ISSUE THREAD

**Issue by jgillich** [hyperium/hyper#126]
I would to to access an UNIX socket with hyper. `TcpStream` and `UnixStream` are very similar, but I assume it would still require some heavy changes (or, looking at `net::HttpStream`, maybe not?). So before I waste any time on this, do you guys think it would make sense to have this in hyper?

**Comment by jimmycuadra** [comment]
I am also interested in this for use with the [https://github.com/coreos/fleet](fleet) API. At least some Ruby HTTP clients support requests to UNIX sockets, e.g. [Excon](https://github.com/excon/excon).

**Comment by softprops** [comment]
This may be of interest to you folks. I just published a new crate called [hyperlocal](https://github.com/softprops/hyperlocal) which provides hyper interfaces for unix domain sockets. I realized that while working on a [docker client](github.com/softprops/shiplift) which also supports unix domain sockets that I could support both tcp and domain socket interfaces using hyper's client interface. I'll be rolling hyperlocal into that soon to replace the hand crafted http unix domain socket interface I'm currently using.

**Comment by jimmycuadra** [comment]
That's awesome, softprops! Thank you.

**Comment by jgillich** [comment]
Very cool :) I guess this can be closed then.

**Comment by softprops** [comment]
I really want to emphasize how well designed hyper's internals were made. It made it very straight forward to extend it in this way. +100 @seanmonstar

**Comment by myfreeweb** [comment]
Would be nice if hyper itself could listen on unix sockets, without an additional crate.

It also should support listening on user-provided (already opened) sockets (for both tcp and unix), e.g. acquired via socket activation or file descriptor passing.

Actually I think socket activation should be handled in hyper itself as well… even though there's a brilliant pun opportunity for naming a crate that does it ;-)

**Comment by prepor** [comment]
It's an essential feature for http client library, most popular http client libraries support it. We also have already have support of unix sockets in tokio (https://github.com/tokio-rs/tokio-uds). Is there a chance that such feature will be accepted in case of PR?

**Comment by seanmonstar** [comment]
I wouldn't expect hyper to explicitly include a UNIX socket implementation. It's already possible to just use any external implementation by using a custom `Connect` in the `Client`. hyper's goal is provide HTTP, and be generic over whatever the transport is underneath.

Being built in to a client would make sense for a more batteries-included kind of library, and for this exact feature, see https://github.com/seanmonstar/reqwest/issues/39

**Comment by softprops** [comment]
FYI, I'm planning on adapting to hypers interfaces for uds in https://github.com/softprops/hyperlocal as soon as there's a new release for hyper

**Comment by myfreeweb** [comment]
> hyper's goal is provide HTTP, and be generic over whatever the transport is underneath

Well, it has a `bind` method that starts a TCP listener…

Looking at the master documentation, `bind_connection` seems like the right API though :)

**Comment by prepor** [comment]
@seanmonstar ok, hyperlocal of @softprops looks good, waiting for a release ;)

**Comment by 25519** [comment]
@seanmonstar, can you please reopen this? I wanted @softprops's hyperlocal server to support `run_until` so I [implemented it](https://github.com/25519/hyperlocal/blob/run_until/src/server/mod.rs). The file is almost entirely copy+pasted from a subset of [this one in hyper](https://github.com/hyperium/hyper/blob/master/src/server/mod.rs) but with UnixListener instead of TcpListener. I think it would make a lot more sense for `hyper::server::Server` to just have a type argument for listener instead of `TcpListener`.

To avoid breaking changes perhaps we could have a `Server2<S, B, L>` with `listener: L` and `Server<S, B> = Server2<S, B, TcpListener>` or something to that effect.

**Comment by seanmonstar** [comment]
I do expect `Server` to have a generic type for the incoming stream in 0.12. On master, there is `Serve` which is already this, and will likely evolve and replace the current `Server` as the tokio reform stuff is completed.

I don't think this issue itself needs to be opened for that, as this was around building in UDS support by default, instead of allowing it to be used.

**Comment by softprops** [comment]
Hi there. I'm open to prs for if anyone needs a change https://github.com/softprops/hyperlocal/blob/master/README.md

**Comment by portstrom** [comment]
I find it strange and surprising that Hyper doesn't support Unix domain sockets. It's a basic and very well-supported feature in any descent programming language (i.e. not Java). Node supports it. Python supports it. I use it a lot for running various services proxied behind Nginx. The crate `hyperlocal` depends on an old version of Hyper. If I were to change to TCP sockets I can't even set permissions.

**Comment by myfreeweb** [comment]
Yeah. And looks like there's still no easy way to provide a custom `TcpListener`/`UnixListener` (e.g. from [listenfd](https://github.com/mitsuhiko/rust-listenfd)).

**Comment by olix0r** [comment]
Now that Hyper uses a recent Tokio, it should definitely be possible to instrument Hyper around [tokio-uds](https://github.com/tokio-rs/tokio-uds).

**Comment by sfackler** [comment]
@myfreeweb 

```rust
unix_listener.for_each(|(socket, _)| {
    let connection = Http::new().serve_connection(socket, MyService);
    tokio::spawn(connection);
    Ok(())
});
```

**Comment by seanmonstar** [comment]
@portstrom Both hyper's client and server allow providing any custom connector or listener, so you can plug in UDS easily, as others have shown.

Does it really seem **so** common to use UDS that it should actually be built in to hyper directly? If it is, at this point, it wouldn't be that much work to provide a `hyper::client::connect::UdsConnector` and a listener for the server. *If* it seems common enough, @portstrom would you be interested in adding it, so others aren't "surprised" in the future?

**Comment by softprops** [comment]
I have a crate that supports tokio uds in the meantime https://github.com/softprops/hyperlocal

**Comment by seanmonstar** [comment]
Thinking more, it really doesn't seem **that** common. I'm fine with it being a separate thing.
