### ISSUE TITLE
Make client generic over future executor

### ISSUE THREAD

**Issue by jimmycuadra** [hyperium/hyper#1262]
I'm writing a bunch of tests for an API client that uses Hyper, and non-blocking I/O doesn't matter. It'd be nice to just be able to call `Future::wait()` in each test, but the client seems to need a Tokio event loop in order to function, so I have to set up a `Core` and use it to run the future in every test. Would it be feasible for the client to be generic over future executors so it could be used in a blocking manner (or with futures_cpupool) in addition to Tokio?

**Comment by seanmonstar** [comment]
Sort of. It is a goal (vaguely, not exactly sure of which parts exactly).

There has been some progress towards making things generic over `T: Executor` in both the futures crate and tokio. Still, so far, the `Handle` is needed by tokio-proto's `BindClient` type. The default connector in hyper (`HttpConnector`) also needs one, as the `TcpStream`s are registered to the related core with it. So, that `Core` does need to run in order for the underlying IO transport to process events.

It could be possible, with a change to `BindClient`, for some connector that creates blocking sockets, which are managed by a different thread, to eventually work...

**Comment by jimmycuadra** [comment]
Do the changes proposed in the [Tokio reform RFC](https://github.com/tokio-rs/tokio-rfcs/pull/3) affect this at all?

**Comment by seanmonstar** [comment]
Yes, the reform will most likely affect this issue.

**Comment by seanmonstar** [comment]
The `Client` actually can now take a generic `Executor` for spawning it's background connection tasks in!
