### ISSUE TITLE
Hyper server hangs in busy loop 

### ISSUE THREAD

**Issue by 3Hren** [hyperium/hyper#1267]
Hi!

Hyper server is published behind nginx.

After opening production load it immediately hangs forever somewhere inside: https://github.com/hyperium/hyper/blob/7ce31211320d76c1bc60493b62d1e9ecfbff8048/src/http/conn.rs#L363. Hyper version is 0.11.1.

No syscalls is done (the last ones are `epoll_wait` a long time ago) only busy looping.

Currently I'm unable to reproduce the issue artificially, only using production load.

Viewing sources didn't give much :(

**Comment by 3Hren** [comment]
Also found out that there is a 0-sized slice write attempt here: https://github.com/hyperium/hyper/blob/master/src/http/h1/encode.rs#L51.

**Comment by 3Hren** [comment]
Seems like (not sure 100%, but gdb prints that `msg` has 0 length) that there is an attempt to write a zero-sized slice here: https://github.com/hyperium/hyper/blob/master/src/http/h1/encode.rs#L51, which results in EWOULDBLOCK. Then flushing (here: https://github.com/hyperium/hyper/blob/7ce31211320d76c1bc60493b62d1e9ecfbff8048/src/http/conn.rs#L365) succeeds, because `tokio_core::net::tcp::TcpStream::flush` is a no-op (https://github.com/tokio-rs/tokio-core/blob/master/src/net/tcp.rs#L507).

Any ideas how it can be?

**Comment by seanmonstar** [comment]
Ah yes, that does indeed seem like a problem. That it likely trigger when the `Stream` for the body includes a zero-length chunk. I've just pushed a fix to master, so hopefully this should be fixed in 0.11.2.

**Comment by 3Hren** [comment]
Thanks for the answer!

Well, hanging was fixed, but now nginx replies with `upstream prematurely closed connection while reading response header from upstream`.

Not sure these issues are connected.

**Comment by seanmonstar** [comment]
Would it be possible to include logs (from hyper) when the issue occurs?

**Comment by 3Hren** [comment]
Sure, will do tomorrow.

**Comment by 3Hren** [comment]
The following things happened:

```bash
Jul 18 12:03:28.262 TRCE parse(b"GET\x20/brconfigs__prestable__v012/get-brconfigs/known_antivirus?brandID=yandex&partnerID=common-yandex\x20HTTP/1.1\r\nHost:\x20api.browser.yandex.net\r\nX-Real-IP:\x20185.58.188.40\r\nX-Request-Id:\x2082effe37adf42c9a\r\nX-Forwarded-For-Y:\x20185.58.188.40\r\nIf-None-Match:\x20\"94aa7472983570cc5f2ac69ad00a2a5039c8ae988857c6f4758f98227013af75\"\r\nUser-Agent:\x20Mozilla/5.0\x20(Windows\x20NT\x206.1)\x20AppleWebKit/537.36\x20(KHTML,\x20like\x20Gecko)\x20Chrome/58.0.3029.110\x20YaBrowser/17.6.1.749\x20Yowser/2.5\x20Safari/537.36\r\nAccept-Encoding:\x20gzip,\x20deflate,\x20br\r\n\r\n")
Jul 18 12:03:28.262 TRCE Request.parse([Header; 100], [u8; 502])
Jul 18 12:03:28.262 TRCE httparse Complete(502)
Jul 18 12:03:28.262 TRCE maybe_literal not found, copying "X-Real-IP"
Jul 18 12:03:28.262 TRCE maybe_literal not found, copying "X-Request-Id"
Jul 18 12:03:28.262 TRCE maybe_literal not found, copying "X-Forwarded-For-Y"
Jul 18 12:03:28.262 TRCE expecting_continue(version=Http11, header=None) = false
Jul 18 12:03:28.262 TRCE should_keep_alive(version=Http11, header=None) = true
Jul 18 12:03:28.262 TRCE is_eof? Decoder { kind: Length(0) }
Jul 18 12:03:28.262 INFO Request::new: addr=[::1]:49786, "GET /brconfigs__prestable__v012/get-brconfigs/known_antivirus?brandID=yandex&partnerID=common-yandex HTTP/1.1"
Jul 18 12:03:28.263 DEBG Request::new: headers={"Host": "api.browser.yandex.net", "X-Real-IP": "185.58.188.40", "X-Request-Id": "82effe37adf42c9a", "X-Forwarded-For-Y": "185.58.188.40", "If-None-Match": ""94aa7472983570cc5f2ac69ad00a2a5039c8ae988857c6f4758f98227013af75"", "User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 YaBrowser/17.6.1.749 Yowser/2.5 Safari/537.36", "Accept-Encoding": "gzip, deflate, br"}
...
...
...
Jul 18 12:03:28.373 TRCE Headers.set( "X-Request-Id", "82effe37adf42c9a" )
Jul 18 12:03:28.373 TRCE Headers.set_raw( "Content-Disposition", Raw([b"attachment;\x20filename=known_antivirus"]) )
Jul 18 12:03:28.373 TRCE Headers.set_raw( "Etag", Raw([b"\"94aa7472983570cc5f2ac69ad00a2a5039c8ae988857c6f4758f98227013af75\""]) )
Jul 18 12:03:28.373 TRCE Conn::poll()
Jul 18 12:03:28.373 TRCE poll when on keep-alive
Jul 18 12:03:28.373 TRCE Headers.set( "X-Powered-By", "cocaine-http-proxy/0.3.7" )
Jul 18 12:03:28.373 TRCE Conn::start_send( frame=Message { message: MessageHead { version: Http11, subject: NotModified, headers: {"X-Request-Id": "82effe37adf42c9a", "Content-Disposition": "attachment; filename=known_antivirus", "Etag": ""94aa7472983570cc5f2ac69ad00a2a5039c8ae988857c6f4758f98227013af75"", "X-Powered-By": "cocaine-http-proxy/0.3.7"} }, body: true } )
Jul 18 12:03:28.373 TRCE should_keep_alive(version=Http11, header=None) = true
Jul 18 12:03:28.373 TRCE WriteBuf reserving initial 8192
Jul 18 12:03:28.373 TRCE ServerTransaction::encode head=MessageHead { version: Http11, subject: NotModified, headers: {"X-Request-Id": "82effe37adf42c9a", "Content-Disposition": "attachment; filename=known_antivirus", "Etag": ""94aa7472983570cc5f2ac69ad00a2a5039c8ae988857c6f4758f98227013af75"", "X-Powered-By": "cocaine-http-proxy/0.3.7"} }, has_body=true, method=Some(Get)
Jul 18 12:03:28.373 TRCE Headers.remove( "Transfer-Encoding" )
Jul 18 12:03:28.373 DEBG encode headers = {"X-Request-Id": "82effe37adf42c9a", "Content-Disposition": "attachment; filename=known_antivirus", "Etag": ""94aa7472983570cc5f2ac69ad00a2a5039c8ae988857c6f4758f98227013af75"", "X-Powered-By": "cocaine-http-proxy/0.3.7"}
Jul 18 12:03:28.373 TRCE Conn::start_send( frame=Body { chunk: [] } )
Jul 18 12:03:28.374 ERRO writing illegal frame; state=KeepAlive, frame=Body { chunk: [] }
```

**Comment by 3Hren** [comment]
Finally!

Can be reproduced if set NotModified status with empty body.

```bash
Jul 18 13:43:01.841 TRCE Conn::poll()
Jul 18 13:43:01.842 TRCE Conn::read_head
Jul 18 13:43:01.842 TRCE parse(b"GET\x20/\x20HTTP/1.1\r\nHost:\x20localhost:8080\r\nUser-Agent:\x20curl/7.51.0\r\nAccept:\x20*/*\r\n\r\n")
Jul 18 13:43:01.842 TRCE Request.parse([Header; 100], [u8; 78])
Jul 18 13:43:01.842 TRCE httparse Complete(78)
Jul 18 13:43:01.843 TRCE expecting_continue(version=Http11, header=None) = false
Jul 18 13:43:01.843 TRCE should_keep_alive(version=Http11, header=None) = true
Jul 18 13:43:01.843 TRCE is_eof? Decoder { kind: Length(0) }
Jul 18 13:43:01.843 INFO Request::new: addr=[::1]:60373, "GET / HTTP/1.1"
Jul 18 13:43:01.843 DEBG Request::new: headers={"Host": "localhost:8080", "User-Agent": "curl/7.51.0", "Accept": "*/*"}
Jul 18 13:43:01.844 TRCE Conn::poll()
Jul 18 13:43:01.844 TRCE poll when on keep-alive
Jul 18 13:43:01.844 TRCE parking current task
Jul 18 13:43:01.845 TRCE Conn::poll_complete()
Jul 18 13:43:01.845 TRCE Conn::write_queued()
Jul 18 13:43:01.845 TRCE flushed State { reading: KeepAlive, writing: Init, keep_alive: Busy, method: Some(Get), read_task: Some(Task) }
Jul 18 13:43:01.845 TRCE Conn::flush = Ok(Ready(()))
Jul 18 13:43:01.852 TRCE Conn::poll()
Jul 18 13:43:01.852 TRCE poll when on keep-alive
Jul 18 13:43:01.853 TRCE Headers.set_raw( "X-Powered-By", Raw([b"Cocaine"]) )
Jul 18 13:43:01.853 TRCE Conn::start_send( frame=Message { message: MessageHead { version: Http11, subject: NotModified, headers: {"X-Powered-By": "Cocaine"} }, body: true } )
Jul 18 13:43:01.853 TRCE should_keep_alive(version=Http11, header=None) = true
Jul 18 13:43:01.853 TRCE WriteBuf reserving initial 8192
Jul 18 13:43:01.853 TRCE ServerTransaction::encode head=MessageHead { version: Http11, subject: NotModified, headers: {"X-Powered-By": "Cocaine"} }, has_body=true, method=Some(Get)
Jul 18 13:43:01.853 TRCE Headers.remove( "Transfer-Encoding" )
Jul 18 13:43:01.854 DEBG encode headers = {"X-Powered-By": "Cocaine"}
Jul 18 13:43:01.854 TRCE Conn::start_send( frame=Body { chunk: [] } )
Jul 18 13:43:01.854 ERRO writing illegal frame; state=KeepAlive, frame=Body { chunk: [] }
```

**Comment by 3Hren** [comment]
Well, I think according to [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) this is my fault: **The 304 response MUST NOT contain a message-body**.

What do you think: should handling such cases be done by hyper or left for user's responsibility?

**Comment by seanmonstar** [comment]
I think that hyper can easily inspect if the body chunk is actually empty, and just ignore it. However, if the body has bytes, and HTTP specifies that the a message is not allowed to have bytes, I would prefer hyper to return an error. Unfortunately, the error handling in tokio isn't as fleshed out as we'd like, so the way for a user to know about this error isn't that easy...

**Comment by 3Hren** [comment]
I'd easily can check it by myself (already did), but it almost fully copies this part of code: https://github.com/hyperium/hyper/blob/85c6bec98bc189aac5c0dfbdc769e543782f9f8f/src/http/h1/parse.rs#L147

**Comment by 3Hren** [comment]
The same error I've got on attempt to reply with body (empty too) on HEAD request.

**Comment by seanmonstar** [comment]
I'll add a check for if the chunk itself is actually zero bytes, like this: https://github.com/hyperium/hyper/blob/85c6bec98bc189aac5c0dfbdc769e543782f9f8f/src/http/conn.rs#L440

An error will happen though if someone tries to send a real body...

**Comment by seanmonstar** [comment]
And I've just pushed that to master...

**Comment by 3Hren** [comment]
Thanks! I think this issue can be closed, because hyper no more hangs.

**Comment by 3Hren** [comment]
> I think that hyper can easily inspect if the body chunk is actually empty, and just ignore it. However, if the body has bytes, and HTTP specifies that the a message is not allowed to have bytes, I would prefer hyper to return an error. Unfortunately, the error handling in tokio isn't as fleshed out as we'd like, so the way for a user to know about this error isn't that easy...

I'm OK if hyper would panic on such RFC violations, but it should be mentioned in docs.

**Comment by seanmonstar** [comment]
To be clear, hyper won't cause a `panic!`. It currently returns an `Err` back to tokio with the message of `illegal frame`. Eventually, that means tokio will drop the socket and close everything about it. We definitely want to improve tokio's handling of errors there.

**Comment by 3Hren** [comment]
Yeah, I know)

But it **can** panic for some cases and that's ok. The other solution may be introducing some kind of strongly-typed `Response`, for example to statically forbid replying with body for HEAD requests. This won't saves from NotModified statuses with body, thus.
At last, yes, tokio error handling can be improved, but I can't imagine how.
