### ISSUE TITLE
hyper::Uri incorrectly splits IPv6 addresses

### ISSUE THREAD

**Issue by kulshrax** [hyperium/hyper#1272]
It looks like `hyper::Uri` relies on [splitting on the first found colon](https://github.com/hyperium/hyper/blob/master/src/uri.rs#L164) to determine the host from the authority part of the URI. This is problematic because it breaks when the host is an IPv6 address or the authority section contains a `username:password` pair. 

For example, given a URI like `http://[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:8080/`, Hyper will attempt to resolve `[2001` via DNS. This effectively prevents sending requests to URIs containing IPv6 addresses.

**Comment by seanmonstar** [comment]
Thanks for reporting this. This should instead do a reverse search for a semi colon, and make sure that the section found between the semi colon and the end is a u16, so that something like `:7334]` isn't found in an IPv6 address with no port.

**Comment by seanmonstar** [comment]
Fixed in https://github.com/hyperium/hyper/commit/7081c4498e707c1240c7e672d39ba4948fffb558, referred to wrong issue in commit message.

This will be in 0.11.2 shortly.
