### ISSUE TITLE
Send an Executor instead of Handle to BindClient

### ISSUE THREAD

**Issue by antoyo** [hyperium/hyper#1274]
Hello.
Please update the call to [`bind_client()`](https://github.com/hyperium/hyper/blob/master/src/client/mod.rs#L171) to send an [`Executor`](https://github.com/tokio-rs/tokio-proto/pull/172) instead of a `Handle`.
Thanks.

**Comment by seanmonstar** [comment]
The tokio-proto crate has not seen a new release yet.

**Comment by sanmai-NL** [comment]
@seanmonstar: Hyper doesn’t use `tokio-proto` anymore since some recent commits of yours, right?

**Comment by seanmonstar** [comment]
Ah yes, it seems so. The client no longer uses `BindClient` what-so-ever.

There may be a desire to give `hyper::Client` some other executor that isn't a `Handle`, but if so, we can open a new issue about that.
