### ISSUE TITLE
Exits with no error msg.

### ISSUE THREAD

**Issue by limitee** [hyperium/hyper#1278]
I write a website with hyper, and find something strange, the program has exited with no error message many times.What should I do now...Is there an bug in the tokio's event loop? or how can I get the error message like normal rust program.

**Comment by DemiMarie** [comment]
My suggestions:

* running under `gdb` and placing a break on `_exit`.
* checking your logs to ensure that there is no panic message.

**Comment by sfackler** [comment]
https://github.com/tokio-rs/tokio-proto/issues/176

**Comment by seanmonstar** [comment]
Is there no log at the `error` level, either from `hyper` or from `tokio_proto`?

**Comment by sfackler** [comment]
Nope
