### ISSUE TITLE
Broken pipe when making HTTP/2 requests

### ISSUE THREAD

**Issue by rytone** [hyperium/hyper#1283]
```rust
client.get(uri)
```
works, but
```rust
let mut request = Request::new(Method::Get, uri);
client.request(request)
```
results in a broken pipe.

`hyper` 0.11.2
`hyper-tls` 0.1.2
`tokio-core` 0.1.9

Tested on Windows 10 and Arch Linux.

**Comment by seanmonstar** [comment]
I suspect there is something else that is different in your example. `client.get` literally calls the exact same code you pasted as failing.

**Comment by rytone** [comment]
Mistake on my part - the issue only occurs when calling `request.set_version(HttpVersion::H2)`. I thought I had tested that, but I guess not. The server I am making requests to is HTTP/2 capable.

**Comment by seanmonstar** [comment]
Ah OK. hyper currently doesn't support H2. It's being actively worked on,so not too far in the future...

**Comment by seanmonstar** [comment]
Fixed in https://github.com/hyperium/hyper/commit/41c47241cd81e5140a04a970adfcb1bffae29473 (surprised GitHub doesn't seem to auto link it anymore, even though it auto closed it?).
