### ISSUE TITLE
0.11 analog for network listener 

### ISSUE THREAD

**Issue by softprops** [hyperium/hyper#1284]
I maintain a little crate that adapts serde interfaces to Unix domain sockets ( https://github.com/softprops/hyperlocal ). 

In 0.10 and below extending hyper was pretty straight forward. Implement a networkconnector for  clients a and networklistener for servers.

 I've started the process of portng this to hyper 0.11. I was happy to see the new connect interface made it even easier for clients but I'm stuck of finding the analog for a network listener. Tokio uds should provide the backing listener support I need but I'm not sure how to adapt that to the newer hyper server model. So far I've found many great examples of extending the client model with the Connect trait but I feel like I'm the first one extending the server model so I cant find any examples.

Could you provide some insight and/or direction?

**Comment by seanmonstar** [comment]
There's 2ish ways to do it: "manually" or the "proto onion".

- Manually: `hyper::server::Http` has a `bind_connection` method that is generic over the IO transport. So, someone can set up a `Core`, any sort of listener, and then use `bind_connection` on new transports.

    ```rust
    let mut core = Core::new()?;
    let handle = core.handle();
    let listener = UnixListener::bind(path, &handle)?;
    let server = listener.incoming().for_each(move |(sock, addr)| {
        Http::new().bind_connection(&handle, sock, addr, HelloWorld);
        Ok(())
    }).map_err(|_| ()); 
    ```

- Proto onion: The 'tokio-proto way' is to compose `ServerProto` things, and have some sort of driver that can use them. Look at tokio-proto's `TcpServer` to see how it works with TCP. It works with hyper's `Http`, or someone can wrap that `Http` in a `TlsServer<Http>`, or any other protocol, and give that to `TcpServer::new()`.

    ```rust
    TcpServer::new(Http::new(), addr)
        .serve(|| Ok(HelloWorld));
    ```

  A caveat to the onion way: tokio-proto is in flux. There will likely be a newer/better way to do those things in a couple months...

**Comment by softprops** [comment]
Amazing. Thanks for the fast feedback and for such careful and thoughtful design choices. Hyper continues to be a source of inspiration for me.

**Comment by softprops** [comment]
If anyone happens upon this thread and is curious, https://github.com/softprops/hyperlocal/ is the result of that migration. thanks @seanmonstar!
