### ISSUE TITLE
Save 418

### ISSUE THREAD

**Issue by porglezomp** [hyperium/hyper#1285]
There's currently a movement going around to remove the 418 status code from the HTTP languages of various languages. (See http://save418.com/ for references to some of the cases). I feel like any attempt to remove it at this point without any current considerations to use the status code is mean-spirited, and we should commit to keeping the variant unless the IANA someday decides to assign it another value, so that nobody wastes their time making a PR to remove it.

**Comment by seanmonstar** [comment]
![wat](https://user-images.githubusercontent.com/51479/29222861-24b22140-7e79-11e7-8d27-7ca31b184524.jpg)

**Comment by porglezomp** [comment]
(Fair enough.)
