### ISSUE TITLE
Redirect policies support

### ISSUE THREAD

**Issue by application-developer-DA** [hyperium/hyper#1286]
I checked the existent and closed issue for "redirect" mentions. It seems that in the past some sort of a `RedirectionPolicy` entity was present in hyper, then some parts were moved to a separate `reqwest` library. So I'm not sure about the current state and decided to ask a question: is there a planned support for some sort of redirect rules which the user can specify for a `Request` or for a `Client` or is it supposed to be implemented by `hyper` users?

**Comment by seanmonstar** [comment]
There's no active plans. hyper has been shedding less critical features, and while trying to be sure the tools are there for anyone else to build them on top. Maybe some day some of those features come back, I don't know.
