### ISSUE TITLE
Documentation fails to mention "futures" dependency.

### ISSUE THREAD

**Issue by slimsag** [hyperium/hyper#1288]
Hi, I've followed the getting started guide: https://hyper.rs/guides/ like a real n00b (😄) and after running `cargo new --bin myserver`, followed the instructions to add:

```
[dependencies]
hyper = "0.11"
```

To my `Cargo.toml` and then went onward to the [Server Guide](https://hyper.rs/guides/server/hello-world/). Unfortunately, that just leaves you in this state:

```
$ cargo run
   Compiling myserver v0.1.0 (file:///Users/stephen/myserver)
error[E0463]: can't find crate for `futures`
 --> src/main.rs:2:1
  |
2 | extern crate futures;
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error(s)

error: Could not compile `myserver`.

To learn more, run the command again with --verbose.
```

I'm smart enough to fix the issue after some googling and assumptions about  https://crates.io/crates/futures listing the right version, but I think that given it's a guide it would be cool if it mentioned this? Maybe just even in the footer of https://hyper.rs/guides/server/hello-world/ a little code block like:

> Note: You will also need to add the `futures` dependency to your `Cargo.toml`:
>
> ```TOML
> [dependencies]
> futures = "0.1"
> ```

What do you think?

**Comment by seanmonstar** [comment]
Looks like the [client guide](https://hyper.rs/guides/client/basic/) was fixed, but server still needs this.

**Comment by Thomspoon** [comment]
Should be fixed now that the PR was merged.
