### ISSUE TITLE
website has no favicon

### ISSUE THREAD

**Issue by slimsag** [hyperium/hyper#1289]
Feel free to close if not useful.. I just noticed and thought I'd mention in case it was missed by accident.

![image](https://user-images.githubusercontent.com/3173176/29296600-3f32f2d0-8110-11e7-9c27-491fc6cd61b7.png)

**Comment by PENGUINLIONG** [comment]
It sometimes happens although I have placed a favicon in the root directory, but it's not detected by a browser until some time after. I'm surprised MS Edge can do it right all the time.

**Comment by seanmonstar** [comment]
There isn't really a logo for hyper yet, so I'd settle for just a orange square of the same color as the website... :D
