### ISSUE TITLE
Completely broken documentation

### ISSUE THREAD

**Issue by Crandel** [hyperium/hyper#1290]
I want to create simple http request with header Authorization. I try [this](https://hyper.rs/guides/client/basic/)  documentation and there are a lot of errors, starting with Uri creation and Core initiation. So hard to understand, how it works and need to look inside code to fix errors and find right API.
How exactly I could include Authorization header to request?

**Comment by seanmonstar** [comment]
What errors do you get? The "completely broken documentation" is compiled and tests with every commit to the documentation, so it does work.

By the way, consider [reqwest](https://crates.io/crates/reqwest) if you just want a super simple client to get out of the way.

**Comment by Crandel** [comment]
Sorry, my mistake, go deeper into documentation and find all answers
