### ISSUE TITLE
How can I copy the Request or its Body?

### ISSUE THREAD

**Issue by XX** [hyperium/hyper#1300]
The `concat2` (or `fold`) operation requires consumption the request body. How can I do this and saving the request for other operations? For example:
```rust
pub fn foo(request: Request) -> Response {
    let body = request.body();
    let total = body.concat2().wait().unwrap();
    println!("{:?}", total);
    bar(&request)
}
```
Produces an error:
```
error[E0382]: use of moved value: `request`
  --> src/controller/user.rs:28:10
   |
25 |     let body = request.body();
   |                ------- value moved here
...
28 |     bar(&request)
   |          ^^^^^^^ value used here after move
   |
   = note: move occurs because `request` has type `hyper::Request`, which does not implement the `Copy` trait
```
But I can not clone the request or its body.

**Comment by mehcode** [comment]
@XX You probably want [`Request::deconstruct`](https://docs.rs/hyper/0.11/hyper/struct.Request.html#method.deconstruct).

```rust
pub fn foo(request: Request) -> Response {
    let (method, uri, version, headers, body) = request.deconstruct();
    let total = body.concat2().wait().unwrap();
    println!("{:?}", total);

    // method, uri, version, and headers are still usable
}
```

**Comment by XX** [comment]
@mehcode Thanks for the help. How can I again construct this request after deconstruction to transfer it to another function?

**Comment by Thomspoon** [comment]
@XX You could just create a new [Hyper::Request](https://docs.rs/hyper/0.11/hyper/struct.Request.html) using the [Request::new](https://docs.rs/hyper/0.11/hyper/struct.Request.html#method.new) method, and construct the remaining information with [Request::set_version](https://docs.rs/hyper/0.11/hyper/struct.Request.html#method.set_version) and [Request::set_body](https://docs.rs/hyper/0.11/hyper/struct.Request.html#method.set_body). Finally, to add your headers, just utilize [Request::header_mut](https://docs.rs/hyper/0.11/hyper/struct.Request.html#method.headers_mut), which returns a mutable header struct for your newly constructed request.

**Comment by XX** [comment]
@Thomspoon Why does not the Request implement a Clone? Is there any reason for this?

**Comment by seanmonstar** [comment]
The `Request` type will be replaced with [`http::Request`](https://carllerche.github.io/http/http/request/struct.Request.html) eventually, which has better ways of pulling out the body and putting together a new `Request` without the body.

**Comment by philippludwig** [comment]
@Thomspoon that does not work; adding the headers fails since: 

````
for header in headers.iter() {
	req_copy.headers_mut().set(header);
                             ``^^^ the trait `hyper::header::Header` is not implemented for hyper::header::HeaderView<'_>``
}

**Comment by hskang9** [comment]
This is not even complete as new version does not even support `deconstruct()` method. @seanmonstar At least put a guide on how to do this in newer version.

**Comment by hskang9** [comment]
Recent version comes with `into_body` method and it seems it is working.
```
async fn clone_request(req: Request<Body>) -> Result<(Request<Body>, Request<Body>), Error> {
    let uri = req.uri();
    let uri_string = match uri.query() {
        None => format!("https://www.snoyman.com{}", uri.path()),
        Some(query) => format!("https://www.snoyman.com{}?{}", uri.path(), query),
    };
    // turn local request path to the path to the upstream server
    let request_builder = Request::builder().uri(uri_string.clone());
    let second_request_builder = Request::builder().uri(uri_string);
    let body_str = hyper::body::to_bytes(req.into_body()).await?;

    let req1 = request_builder
        .body(Body::from(body_str.clone()))?;
    let req2 = second_request_builder
        .body(Body::from(body_str.clone()))?;

    Ok((req1, req2))
}
```

**Comment by hskang9** [comment]
It seems `deconstruct()` method is now `into_body()`.

```
async fn clone_response(resp: Response<Body>) -> Result<(Response<Body>, Response<Body>), Error> {
    // turn local request path to the path to the upstream server
    let body_bytes = hyper::body::to_bytes(resp.into_body()).await?;

    let resp1 = Response::builder().body(Body::from(body_bytes.clone()))?;
    let resp2 = Response::builder().body(Body::from(body_bytes.clone()))?;

    Ok((resp1, resp2))
}
```

**Comment by abdolence** [comment]
> It seems deconstruct() method is now into_body().

To be exact now this is:
- `into_parts()` for deconstruct the request
- `Request::from_parts()` to create it from parts
