### ISSUE TITLE
Hyper server, parse request json body

### ISSUE THREAD

**Issue by srgsuchkov** [hyperium/hyper#1306]
Hello, sorry for stupid question, but I can't find an example how to parse json body from POST request in hyper server.

request example:

curl -X POST "127.0.0.1:3000/user/319/update" -d '{"name": "Name1", "age": 20...}'

**Comment by seanmonstar** [comment]
Hey there! There's a [guide](https://hyper.rs/guides/client/json/) showing how to do this on the hyper website. Also, you may find the reqwest crate even easier to user, such as [this Response.json example](https://docs.rs/reqwest/*/reqwest/struct.Response.html#method.json).

**Comment by srgsuchkov** [comment]
I use something like this :

```
struct TestSt;

impl Service for TestSt {
    type Request = Request;
    type Response = Response;
    type Error = hyper::Error;
    type Future = FutureResult<Response, hyper::Error>;
    fn call(&self, req: Request) -> Self::Future {
        futures::future::ok(match req.method() {
            &Post => {
                req.body().concat2().and_then(move |body: Chunk| {
                                                let v: Value = serde_json::from_slice(&body).unwrap();
                                                println!("{:?}", v);
                                                Ok(())
                });
                Response::new().with_status(StatusCode::Ok)
            },
            _ => {
                Response::new().with_status(StatusCode::NotFound)
            }
       })
    }
}

fn main() {
    let addr = "0.0.0.0:3000".parse().unwrap();
    let server = Http::new().keep_alive(true).bind(&addr, || Ok(TestSt)).unwrap();
    server.run().unwrap();
}
```

when I run the server and make some requests
curl -X POST -H "Content-Type: application/json" "127.0.0.1:3000/u" -d '{"name": "Name1", "age": 20}'
I expect to see println with this data but got nothing.

Could you pls explain what I'm doing wrong ?

**Comment by srgsuchkov** [comment]
Sorry, I'm newbie in rust, mb I can't understand some thing, but if I rewrite me code to:

```
&Post => {

        req.body()
           .concat2()
           .and_then(move |body: Chunk| {
                let v: Value = serde_json::from_slice(&body).unwrap();
                println!("{:?}", v);
                Ok(())
            })
            .and_then(|_| {
                Ok(Response::new().with_status(StatusCode::Ok))
            });
},
```

I got error : 
```
note: expected type `hyper::Response`
 found type `()`
```

How can I unwrap hyper::Response from futures::AndThen ?

**Comment by srgsuchkov** [comment]
Thank you so much, explains everything for me.
