### ISSUE TITLE
Uri.host() returning None incorrectly

### ISSUE THREAD

**Issue by chrxr** [hyperium/hyper#1310]
I could be missing something here, but it doesn't seem obvious to me if I am.

Sending a request from an html form with JS. Running both the webform and the rust script on a local Vagrant box.

Successfully sending the request to `http://localhost:3000/tdfg/gdfgd?grg`.

`Uri.path()` and `Uri.query()` both return correct results ("/tdfg/gdfgd/" and "grg" respectively). But Uri.host() returns `None`

```Rust
extern crate hyper;
extern crate futures;

use hyper::Post;
use hyper::server::{Http, Request, Response, Service};
use futures::Stream;
use futures::future::*;
use std::str;
use hyper::Uri;

struct WebService;

impl Service for WebService {
    type Request = Request;
    type Response = Response;
    type Error = hyper::Error;
    type Future = Box<futures::Future<Item = Self::Response, Error = Self::Error>>;

    fn call(&self, req: Request) -> Self::Future {
        let response = Response::new();

        match req.method() {
            &Post => {
                let uri: Uri = req.uri().clone();

                match uri.host() {
                    Some(v) => println!("{:?}", v),
                    None => println!("NONE!!!"),
                }

                Box::new(futures::future::ok(response))
            },
            _ => Box::new(futures::future::ok(response))
        }
    }
}

fn main() {
    let addr = "0.0.0.0:3000".parse().unwrap();
    let server = Http::new().bind(&addr, || Ok(WebService)).unwrap();
    server.run().unwrap();
}
```

**Comment by chrxr** [comment]
Cargo.toml dependencies

futures = "0.1.14"
hyper = "0.11.2"
tokio-core = "0.1.9"

**Comment by seanmonstar** [comment]
In HTTP/1.1, most commonly requests are sent in origin-form, which means your request begins like this:

```
POST /tdfg/gdfgd?grg HTTP/1.1
```

So, that means the `Uri` has a path and query, but no other information. In HTTP/1.1, a `Host` header is also sent, contains the host. You can get that via `req.headers().get::<Host>()`.

**Comment by chrxr** [comment]
Ah! Got it, thanks. Is it also possible to get the uri scheme in a similar way? This method also currently returns None for me but Scheme isn't included in the Host header.

**Comment by seanmonstar** [comment]
HTTP/1 does not define a way to pass on the scheme, unfortunately. The only way you have it so notice if the incoming socket is using TLS :(

In HTTP/2, there is a `:scheme` pseudo header that is sent...

**Comment by chrxr** [comment]
Thanks! HTTP/2 FTW

**Comment by Benjamin-Yim** [comment]
> In HTTP/1.1, most commonly requests are sent in origin-form, which means your request begins like this:
> 
> ```
> POST /tdfg/gdfgd?grg HTTP/1.1
> ```
> 
> So, that means the `Uri` has a path and query, but no other information. In HTTP/1.1, a `Host` header is also sent, contains the host. You can get that via `req.headers().get::<Host>()`.

Should we help users solve this problem instead of letting users know about the solution?
