### ISSUE TITLE
Something wrong happens with header! macro and proc_macro feature

### ISSUE THREAD

**Issue by 3Hren** [hyperium/hyper#1311]
When defined `proc_macro` feature, a `header!` macro breaks in some way, emitting `cannot find type <Header> in this scope` when trying to use defined headers.

**Comment by seanmonstar** [comment]
I have no idea what could be happening, I haven't use proc macros. However, as that is an unstable nightly feature, it is likely a bug in the compiler. It'd be useful to them if you filed on the rust repo, with steps to reproduce and any error messages that occur.
