### ISSUE TITLE
Reason for Sync + Send + 'static

### ISSUE THREAD

**Issue by mersinvald** [hyperium/hyper#1327]
Hello!

Can you please explain reasoning behind `Sync + Send + 'static` bound on the `NewService` here
https://github.com/hyperium/hyper/blob/77bfcd95156e6f19c0618d7493ea092b4e055655/src/server/mod.rs#L88-L92
and here
https://github.com/hyperium/hyper/blob/77bfcd95156e6f19c0618d7493ea092b4e055655/src/server/mod.rs#L339-L342

I've been writing my custom `NewService` and ran into problems with this bounds.

Are they necessary since `hyper` moved to async single-thread mode with `Tokio`?
Removing them will allow to write simpler and way more effective single-thread async code.

**Comment by seanmonstar** [comment]
This has been addressed in master, and the linked PRs have reasoning around it.
