### ISSUE TITLE
Allow hyper::Body to be created from Read or AsyncRead

### ISSUE THREAD

**Issue by cetra3** [hyperium/hyper#1328]
I'd like to be able to construct a response from a static File or a Read interface.  Not sure if this is already possible.

I.e, 

```
    let f = File::open("example.txt").unwrap();
    let body = hyper::Body::from(f);
```

**Comment by srijs** [comment]
Hi @cetra3! When building a response, you are not forced to use `hyper::Body`. In fact, you can use any other type that implements `futures::Stream`.

To get from a `std::io::File` to a `Stream` you can use the [`futures-fs`](https://crates.io/crates/futures-fs) crate, for instance.

**Comment by srijs** [comment]
@seanmonstar should we add this to the guide?

**Comment by seanmonstar** [comment]
Sorry, didn't write here as the user also asked on Reddit, and got several answers.

The guide does try to touch on the stream being able to be changed, but it might not be that obvious. Probably the guide should be more properly designed, instead of the sort of mishmash I've put together so far...

**Comment by xinghun92** [comment]
I use a Stream to construct a Request like this.
```
let mut request = ::hyper::Request::new(::hyper::Method::Post, ::hyper::Uri::from_str("http://www.google.com").unwrap());
let pool = FsPool::default();
let file_read_stream = pool.read("test.txt");
request.set_body(file_read_stream);
```

And I can not compile it, the error is 
```
the trait `std::convert::From<futures_fs::FsReadStream>` is not implemented for `hyper::Body`
```

How to fix it? thank you!

**Comment by srijs** [comment]
@xinghun92 Try explicitly creating a `Request<FsReadStream`:

```rust
let mut request: ::hyper::Request<FsReadStream> = ::hyper::Request::new(::hyper::Method::Post, ::hyper::Uri::from_str("http://www.google.com").unwrap());
let pool = FsPool::default();
let file_read_stream = pool.read("test.txt");
request.set_body(file_read_stream);
```

**Comment by xinghun92** [comment]
It fails when send this request using client.
```
let mut core = tokio_core::reactor::Core::new().unwrap();
let handle = core.handle();
let client = Client::new(&handle);
let work = client.request(request).and_then(|res| {
    println!("Response: {}", res.status());
    println!("Headers: \n{}", res.headers());

    res.body().for_each(|chunk| {
        io::stdout().write_all(&chunk).map_err(From::from)
    })
}).map(|_| {
    println!("\n\nDone.");
});
```

The error is 
```
let work = client.request(request).and_then(|res| {
    |                               ^^^^^^^ expected struct `hyper::Body`, found struct `futures_fs::FsReadStream`
```

**Comment by srijs** [comment]
You gotta make the generic types for body align across client and request. I'm actually surprised that the type inference is not being more helpful here. Try changing to

```rust
let client = Client::configure().body::<FsReadStream>().build(&handle);
```

And then you probably also need to change

`request.set_body(file_read_stream);`

to

`request.set_body(file_read_stream.map_err(hyper::Error::from));`

in order to align the two error types.

**Comment by srijs** [comment]
Hmm, seems like this is starting to become more tricky. Your current problem would be solved by using `Client::configure().body::<FsReadStream>().build()`, but then the next problem will be that `FsReadStream` has error type `std::io::Error`, where `Config::build()` expects the body to have error type `hyper::Error`

@seanmonstar Can you think of anything that might make this easier? For instance, could we change `Config::build` to be able to automatically cast errors?

I'm thinking something like

```rust
impl<B> Config<UseDefaultConnector, B>
where B: Stream,
      B::Item: AsRef<[u8]>,
      B::Error: Into<hyper::Error>
{
    ...
}
```

**Comment by seanmonstar** [comment]
Having `Into` there would probably be nice. This is actually a case of why #1129 exists. I would wish that users would not have to give a `hyper::Error` **back** to hyper to signify that the stream is busted...

**Comment by cetra3** [comment]
@srijs I'm using the [shio-rs](https://github.com/mehcode/shio-rs) framework that requires a `hyper::Body` to be sent in the response so the proposed methods here don't work.

I've implemented a workaround using the `hyper::Body::pair()` function, but it's very complex to do so, and has [its own issues with futures](https://github.com/alexcrichton/futures-rs/issues/587).

So it is possible to still use hyper::Body with a file stream which is good, but the ergonomics around it is pretty bad.

**Comment by mehcode** [comment]
@cetra3 Could  you open an issue on Shio? We should generalize and support this.
