### ISSUE TITLE
Allow HttpConnector to be provided an Executor

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1330]
The default connector in hyper, the `HttpConnector`, uses a `CpuPool` to do blocking DNS resolution. It would be useful to be able to provide a `futures::future::Executor`, so that users can try to share a `CpuPool` with other blocking tasks as well.

**Comment by jonhoo** [comment]
If I want to not use a thread pool for DNS resolution, but instead do it synchronously on the current thread, is creating two `Core`s [like this](https://github.com/mit-pdos/distributary/commit/009ea2222a270974e794b69161a70674443448ff) the only way to do so?

**Comment by seanmonstar** [comment]
@jonhoo probably not! In the linked example, the `Core` is dropped immediately, so it will never actually be running, and so won't execute the DNS queries!

However, running them on the same `Core` is probably also not desirable in 99% of cases. It will completely block the thread while calling `getaddrinfo`, which could take a couple seconds to complete. While doing that, the thread cannot make any progress on any other requests, and it's a server, any responses are also blocked.

If you wanted to use the same thread pool executor for all `Client`s, you could create one like from `futures-cpupool`, and pass that handle as an argument when constructing a `Client`.

**Comment by jonhoo** [comment]
> In the linked example, the `Core` is dropped immediately
Where? `core` goes into the returned `ControllerHandle` struct, whereas `core_dns` goes into the `Client`, so I don't think either is dropped?

> However, running them on the same `Core` is probably also not desirable in 99% of cases. It will completely block the thread while calling getaddrinfo, which could take a couple seconds to complete.

In this particular case there are no other outstanding requests. I actually want fully blocking, synchronous operation :)

**Comment by seanmonstar** [comment]
Oh woops, I misread, apologies! I see what you did now. I hadn't realized that `Core` implements `Executor`. It perhaps shouldn't... since passing it directly like that means the `HttpConnector` owns it, but doesn't know anything about other than it's an `Executor`. However, the `Core` must be `run`ning in order for any spawned future to be completed.

You *could* just pass the `Handle` of your main core as the `Executor` as well, if you really wanted to block the main thread :)
