### ISSUE TITLE
Strict-Transport-Security header does not support 'preload'

### ISSUE THREAD

**Issue by raphaelcohn** [hyperium/hyper#1334]
To allow for HTTPS pinning, browsers can check for the value of `preload` in `Strict-Transport-Security` header. Hyper doesn't support this.

**Comment by raphaelcohn** [comment]
see <https://hstspreload.org/>

**Comment by seanmonstar** [comment]
Thanks to `StrictTransportSecurity` having all of its fields public, it's a breaking change to add a new one, so adding this would need to be part of 0.12. (While in there, the fields should be made private with getter and setter methods instead, so we can add more fields in the future...)

**Comment by gabibbo97** [comment]
Hello, if no one is working on this I would like to start an implementation

**Comment by seanmonstar** [comment]
I haven't seen a pull request, so fair game! Note that as pointed out earlier, this would be a breaking change and so couldn't be released soon...

**Comment by seanmonstar** [comment]
For now, the new version of hyper won't be including the typed headers directly, so I'm closing this here as a won't fix.
