### ISSUE TITLE
From-trait based error conversion for request bodies

### ISSUE THREAD

**Issue by srijs** [hyperium/hyper#1338]
Picking up that particular thread from #1328, I was wondering whether it might be worth it to implement a From/Into-based error coercion for request bodies.

This would be different from #1129 in so far as I believe that it should be possible to ship it as a non-breaking change, ergo before 0.12, and therefore solve at least one pain point in the short-term which users are currently experiencing when using custom request bodies.

What do you think?

**Comment by seanmonstar** [comment]
That seems fine to me. I think I tried it out a few months ago, and ran into issues propagating the generics everywhere, but maybe I did it wrong!
