### ISSUE TITLE
Create easier way to get a string from a body

### ISSUE THREAD

**Issue by MoritzFago** [hyperium/hyper#1340]
I needed a String containing the contents of a http-served document.
I found it extremely difficult to create a function for this.
This is what i came up with:
```rust
fn get_string_from_url(url: &String) -> String {
    let mut core = Core::new().unwrap();
    let client = Client::new(&core.handle());

    let uri = url.parse().unwrap();
    let mut core = Core::new().unwrap();
    let client = Client::new(&core.handle());

    let work = client.get(uri);
    //String::from_utf8(
    let bodyvec: Vec<u8> = core.run(work)
        .unwrap()
        .body()
        .concat2()
        .wait()
        .unwrap()
        .to_vec();

    String::from_utf8(bodyvec).unwrap()

}
```
I regard this code as more complicated and hacky than it should be.
I think there should be a easier and more asyncronous way with better documentation.

I open this issue here, because I think this is a lack in the documentation.

To be honest: I am a rust beginnger, all errors are mine.

**Comment by seanmonstar** [comment]
You may find that the [reqwest crate](https://crates.io/crates/reqwest) has easier ways of doing some of these things.

**Comment by MoritzFago** [comment]
Yes it would be simpler, but i hoped, that i could use the async functions of hyper

**Comment by seanmonstar** [comment]
The pasted example is blocking (thread is blocked at core.run() and the wait() call), so I assumed you didn't actually want it. So, what part then did you hope would be shorter?

Still, if you do, reqwest does have an async client. Needs the "unstable" feature enabled on it.
