### ISSUE TITLE
why is there still the 0.8.0 doc on hyper.rs

### ISSUE THREAD

**Issue by MoritzFago** [hyperium/hyper#1341]
Why is there still the 0.8.0 documentation under `https://hyper.rs/hyper/0.8.0/hyper/index.html`?
As far as i get it, the current version is 0.11 and it confuses the search results, because there is outdated info in it.

**Comment by seanmonstar** [comment]
The same reason older version of docs are still up on https://doc.rs: it's rude to break the internet by removing sites that people may have linked to.
