### ISSUE TITLE
More arguments for closures

### ISSUE THREAD

**Issue by soqe** [hyperium/hyper#1344]
Don't understand how to push values to a vector outside of a closure. Maybe need more arguments provided to the closure which has taken by functions of the Future trait?

Example code:
```rust
let mut cookies: Vec<String> = Vec::new();
let request = client.get("<adress>".parse().unwrap()).and_then(|res| {
  for header in res.headers().iter() {
    if header.name() == "Cookie" {
      cookies.push(header.value_string()); // error
    }
  }
  res.body().concat2()
});
```

**Comment by seanmonstar** [comment]
You'd probably need to move the `cookies` vector into the closure, with the change to `and_then(move |res| {`.

Separately, you could do `res.headers.get::<hyper::header::Cookie>()` instead of looking in a loop.

**Comment by soqe** [comment]
Had tried to use ```rust move```. Got a message "value used after move". Don't understand how to copy a value and use it after.

**Comment by seanmonstar** [comment]
I'm sorry, I don't have the full context on that you issue could actually be. It sounds like a more general Rust usage question. Could I suggest coming up with an example of code that has the error you're seeing, and ask either in something like [Rust's IRC channel](https://chat.mibbit.com/?server=irc.mozilla.org&channel=%23rust-beginners), or something like StackOverflow?

(As this isn't a bug in hyper, I'm going to close the issue.)
