### ISSUE TITLE
The entire body is consumed unconditionally

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#1352]
The code doing this lives in tokio-proto, but I'm filing this here to keep it in mind for #1342. If a server only reads part of a request body, or a client only reads part of a response body, I would expect the connection to be dropped. Instead, the entire body is read and thrown away: https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L204.

This can be not-great when dealing with large bodies when you e.g. ran into an error early in the processing of the body and decided not to deal with the remainder.

**Comment by sfackler** [comment]
As an example, `cat /dev/zeroes | curl http://some-server` will run forever with zero ability to change that behavior.

**Comment by seanmonstar** [comment]
I believe this may be fixed in v0.11.7 if `no_proto` is set, but there isn't a test case in hyper directly...

**Comment by seanmonstar** [comment]
In most cases, the internal hyper dispatch is now used, which will correctly stop reading if the stream is dropped. If still using `TcpServer::new(Http::new())`, you'll see this... so don't use that anymore :D
