### ISSUE TITLE
Need help with script

### ISSUE THREAD

**Issue by BROADACRES16xFS17MAP** [hyperium/hyper#1357]
Hi just wondering if anyone explain to me how you got this to work.Looking at doing it on my github and found yours. Easy detailed explanation would be great. Thanks in advance.

![2017-10-18](https://user-images.githubusercontent.com/7673205/31715081-f84a4766-b449-11e7-9216-b396f717f2c6.png)

**Comment by seanmonstar** [comment]
This is shown because there is a CONTRIBUTING file in the repository. You can learn more here: https://help.github.com/articles/setting-guidelines-for-repository-contributors/
