### ISSUE TITLE
Performance on body access

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [hyperium/hyper#1361]
Hi,

I have a performance error to get data from the body.
I wrote a small sample and the problem come from this [line](https://github.com/hyperium/hyper/blob/master/tests/client.rs#L102) which took 5 seconds to get the content body.

Do you have any idea why it's so long ?
Remark: the body is only 512 bytes long...

Thanks,
Marc-Antoine

**Comment by seanmonstar** [comment]
I cannot say without some more context. Other instances do not take 5 seconds to ready 500 bytes. It's possible it's the way the code is written, or it could be latency on the network, or something else...

**Comment by MarcAntoine-Arnaud** [comment]
Yes it look like a network issue (I have test on other provider and it works as attending)
