### ISSUE TITLE
ETags must be ‘ASCII’, yet `EntityTag::weak` accepts UTF-8 Strings

### ISSUE THREAD

**Issue by sanmai-NL** [hyperium/hyper#1363]
[ETags must be ASCII](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag). Or more precisely, they must be recognized by the grammar in [the standard](https://tools.ietf.org/html/rfc7230#section-3.2.6) quoted in the docs for  `EntityTag::weak`. However, this call does not fail with `hyper` `master`:

```rust
EntityTag::weak("☃".into());
```

Perhaps types from [the `ascii` crate](https://tomprogrammer.github.io/rust-ascii/ascii/index.html) can be used instead. I happened to encounter this bug, and I suspect it will be applicable to more headers produced with `hyper`.

**Comment by seanmonstar** [comment]
For now, the new version of hyper won't be including the typed headers directly, so I'm closing this here as a won't fix.
