### ISSUE TITLE
Conn should call shutdown on the inner stream when dropping

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#1380]
This is pretty important for TLS connections so that they can perform the TLS connection shutdown messaging to allow for session reuse.

**Comment by sfackler** [comment]
@seanmonstar could you reopen? We still need to handle the client side.

**Comment by seanmonstar** [comment]
To clarify, is there a situation in the client where this doesn't happen? It look like in `Dispatcher::poll`, shutdown is called before returning `Async::Ready(())` in all cases.

**Comment by sfackler** [comment]
Yep, looks like it is!
