### ISSUE TITLE
Stale connections are returned from the connection pool

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#1382]
I have a Hyper (no proto) client talking to a Netty-based server over TLS. I make one request, and we keapalive the connection. After idling for 30 seconds, the server sends a TLS shutdown alert and a TCP FIN. After some period of time, the client makes another request to the same server. It pulls the same connection out of the pool, sends the request, and then immediately hits an EOF trying to read the response out of the already closed connection with an error: `end of file reached before parsing could complete`.

Idle connections should probably be constantly reading to detect hangups.

We were seeing occasional broken pipe errors out of tokio-proto before upgrading to 0.10.7 and switching to no-proto, but it's now *way* more common.

This commit seems suspicious: https://github.com/hyperium/hyper/commit/7c4b814e. Isn't the example test case a pretty straightforward protocol violation? Why wouldn't that be an error?

**Comment by seanmonstar** [comment]
For a client connection, if a message has been read to the end of its framing, it shouldn't be expecting more data until a new request is sent, right? Should the behavior be adjust to try to read anyways, and if not expecting anything, return some protocol error?

**Comment by seanmonstar** [comment]
I believe the error that commit was fixing was the case of a `HEAD` request where the response returns a body anyways, so by not continuing to read, a protocol error wasn't yelled after a HEAD.

Come to think of it, that would just mean that the socket would return a protocol error the next time, and ruin a new request... I suppose it's best to point out early when a response had extra unexpected bytes...

**Comment by sfackler** [comment]
Yeah, it seems like it'd be okay to either have the HEAD request report a protocol error, or just have the connection close out in the pool due to unexpected data.

**Comment by seanmonstar** [comment]
This is fixed in 0.11.8.

**Comment by ernestas-poskus** [comment]
Still getting:

```
ERROR:tokio_proto::streaming::pipeline::client: pipeline error: unexpected end of file

ERROR:tokio_proto::streaming::pipeline::client: pipeline error: end of file reached before parsing could complete
```

with 

```
[[package]]
name = "hyper"
version = "0.11.8"
```

**Comment by seanmonstar** [comment]
Those logs by themselves seem fine: sometimes connections are bad.

Do you mean the logs are incorrect?

**Comment by ernestas-poskus** [comment]
> Do you mean the logs are incorrect?

I am not sure if they are correct or not, need to add more verbosity.
