### ISSUE TITLE
6-7x performance drop when using no_proto

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#1384]
I haven't looked into it in detail yet, but after switching to no_proto on the server side, there's a pretty severe, but non-consistent performance hit. Some ETE tests that used to take ~.5 seconds now take ~30, but others are unaffected.

**Comment by sfackler** [comment]
Welp, this turns out to have been a PEBCAK. I was returning the serve_connection future into my for_each loop rather than spawning it, so exactly one connection was running on a selector thread at a time... >_>

**Comment by seanmonstar** [comment]
I do want to make it easier to spawn all connections onto an executor. Though, I also think the tokio reform will change slightly how we should expose this...
