### ISSUE TITLE
How to send a big file, but not read the entire file to RAM(example: Vec<u8>) before send? 

### ISSUE THREAD

**Issue by biluohc** [hyperium/hyper#1385]

**Comment by biluohc** [comment]
To avoid large file wasted memory.
Read  a(some) u8 from File and write it to socket?

**Comment by kamyuentse** [comment]
You can try to use:
```
let (tx, rx) = mpsc::channel::<Result<Chunk, Error>>(buffer);
resp = resp.with_header(ContentLength(...))
                   .with_header(ContentType(...))
                   .with_status(...)
                   .with_body(rx);

// Send data using tx
```

Or use something like `bytes: from-to` to split the file transferred in multi-request/response.

**Comment by biluohc** [comment]
Oh, Thanks you very much.
But I do not understand the second method?
What's is the bytes, this [crate](https://docs.rs/bytes)?

**Comment by kamyuentse** [comment]
Sorry for my laziness. The second way is using the range request. `bytes: from-to` is one of the header formats.
Refer [RFC-7233: Range Requests](https://tools.ietf.org/html/rfc7233) for more information.

**Comment by biluohc** [comment]
Oh, but HTTP Range Requests is another thing.

**Comment by lnicola** [comment]
See also https://docs.rs/futures-fs/0.0.3/futures_fs/.

**Comment by seanmonstar** [comment]
I would recommend the futures-fs crate, as suggested before.
