### ISSUE TITLE
entered unreachable code in src/proto/conn.rs

### ISSUE THREAD

**Issue by P-E-Meunier** [hyperium/hyper#1391]
Using Hyper 0.11.7, I sometimes get the following error:

```
panicked at 'internal error: entered unreachable code', src/proto/conn.rs:387:17
```

That line is now [here](https://github.com/hyperium/hyper/blob/master/src/proto/conn.rs#L372).

**Comment by seanmonstar** [comment]
Thanks for the report, I believe I see what is happening. I'll have a fix shipped in 0.11.8.
