### ISSUE TITLE
My hyper server freezes sometimes

### ISSUE THREAD

**Issue by P-E-Meunier** [hyperium/hyper#1392]
Hi! This may be related to #1391, and I don't know whether this issue is a Tokio issue or a Hyper one, but FreeBSD users are able to freeze https://nest.pijul.com by simply doing `pijul clone https://nest.pijul.com/pjiul_org/pijul` (which basically just sends a few GET requests to the server).

I can't reproduce the bug, even in a virtual machine, and I suspect VirtualBox uses the Linux networking stack. I've described the issue further in tokio-rs/tokio-io#92

**Comment by seanmonstar** [comment]
It looks like in the linked issue, the problem was found and fixed, so I'm going to close this.
