### ISSUE TITLE
Getting unexpected eof after upgrade to 0.11.8

### ISSUE THREAD

**Issue by mathstuf** [hyperium/hyper#1396]
After upgrading our application (which only uses `hyper` directly for the `header!` macro in a dependent library and `reqwest` otherwise) to 0.11.8, we've started getting this error showing up:

```
pipeline error: unexpected end of file
```

which comes from [`tokio-proto`](https://github.com/tokio-rs/tokio-proto/blob/f6bf8c3a5421920e3773cdbf42280a402d1c0408/src/streaming/pipeline/client.rs#L76). We've narrowed it down to `hyper` changing in commit 95e0164e8f0f03742f71868cb2828bcd4bfa5cfc. Is there some way that we're using `reqwest` improperly that would cause this?

All of our calls using `reqwest` are contained in [this file](https://gitlab.kitware.com/utils/rust-gitlab/blob/master/src/gitlab.rs) and this is a long-lived structure, though we're seeing errors right after startup. Does `reqwest` need changes related to its connection pool?

Cc: @bradking

**Comment by seanmonstar** [comment]
Does the connection send bytes it shouldn't? Such as, is there a body to a head request, or some extra bytes after the end of a response body?

**Comment by mathstuf** [comment]
I doubt it; we're talking to Gitlab which is using Grape for its REST API and I'd expect it to be well-behaved in that respect. I'll check the logs though to see if that's happening.

**Comment by mathstuf** [comment]
I'm only seeing `200 OK` responses with full JSON data objects.

**Comment by seanmonstar** [comment]
Would it be possible to turn on logs from hyper and (after sanitizing) paste the ones that appear around the error log? I'm setting up a super simple program to just hit some public API end points on Gitlab and not seeing this error log, so I could use a little more on how to investigate this.

**Comment by mathstuf** [comment]
We see it when running the queries through Rayon, so it could be something to do with saturating `reqwest`'s connection pool. Currently dumping logs out (there's lots of activity and it's taking a while to get a week's worth of logs).

**Comment by mathstuf** [comment]
Is there an email address that would be good to send it to? I anonymized it by removing all of the `received data` bits (they now just say `Object()` or `Array()`).

**Comment by seanmonstar** [comment]
You could send it to sean@seanmonstar.com.

**Comment by seanmonstar** [comment]
The most likely cause for this was that the connection was being closed immediately after the end of a response body was read. The internal implementation would not have adjusted its state that an EOF was OK at that point (only doing so in `flush`), and the tokio-proto dispatcher was calling `poll` again (since the previous one succeeded).

Merged to master is a fix to update its state that the message has completed and so an EOF is not unexpected. Would you be able to test using hyper master, to confirm?

**Comment by bradking** [comment]
> Would you be able to test using hyper master, to confirm?

Yes, it works as of `v0.11.9`, thanks!
