### ISSUE TITLE
Large chunked responses are corrupted using no_proto on the server side

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#1399]
After switching to using the no-proto stuff server side, we're seeing large requests getting corrupted in kind of weird ways. At the transport layer, it looks like we receive chunks up to some point and then no more. The final two bytes are `\r\n` and it looks like the final chunk was roughly the right size. However, there seems to be some corruption internally as well - if we use a gzip content-encoding, we break due to a decompression failure before getting wedged.

Here's curl --trace output for a larger and hung uncompressed response: https://gist.github.com/sfackler/f05bfcd4f3d5fb48f08937643679c987. A smaller and working response: https://gist.github.com/sfackler/87f4df214f773adc2df9f51e5de3e436. A compressed and corrupted response: https://gist.github.com/sfackler/56ec86bf38e15faaf1a1beee4400b1f9. A compressed response that ended up wedged because we didn't tell curl to try to decompress it: https://gist.github.com/sfackler/2639b51616308f2a8101b151a94c345a.

Here are trace level logs for both uncompressed requests - the larger and hung one happened first on thread `selector-7` and the smaller and working one happened second on `selector-1`:

https://gist.github.com/sfackler/d36c93e4333962082fa46a758e056588

**Comment by sfackler** [comment]
The error seems to be nondeterministic and larger responses have a higher chance to get wedged so I think it's some combination of events that cause the issues.

**Comment by sfackler** [comment]
Ah, we were on 0.11.7 and I can't seem to repro on 0.11.9. Any idea what the fix was?

**Comment by sfackler** [comment]
Seems like it's probably https://github.com/hyperium/hyper/commit/121b5eef19e65acfecb8261d865554e173f2fc78 right?

**Comment by seanmonstar** [comment]
Yes, that commit did fix an issue that sounds just like this one.

**Comment by sfackler** [comment]
Cool, thanks!
