### ISSUE TITLE
sendfile support

### ISSUE THREAD

**Issue by reem** [hyperium/hyper#140]
http://linux.die.net/man/2/sendfile

**Comment by seanmonstar** [comment]
This is tricky with non-blocking IO, and doesn't work over HTTPS or with HTTP/2. I don't believe the gains are worth the effort. Still, if someone wished to do this in their `Handler`, it should be possible to do if `Encoder` were to implement `AsRawFd`. It'd then just be `sendfile(file.as_raw_fd(), encoder.as_raw_fd())`.

**Comment by virtuallynathan** [comment]
FWIW, Linux and FreeBSD both support kTLS, so HTTPS / HTTP/2 with sendfile() is possible now, https://blog.filippo.io/playing-with-kernel-tls-in-linux-4-13-and-go/

**Comment by dekellum** [comment]
I suggest (with my own bias) prototyping it and include benchmark comparing your impl to using _body-image_ as body in `MemMap` state, or `Fs` state.  If its clearly faster, then the author might be receptive to supporting it *nix.

**Comment by virtuallynathan** [comment]
That’s a good idea, I’ll see if I’m able to get around to that, but at this
point I’m a rust newbie :)

FWIW, this is what Netflix does to serve video at 220Gbps:
https://netflixtechblog.com/serving-100-gbps-from-an-open-connect-appliance-cdb51dda3b99
(220G is the latest record using an AMD EPYC CPU, and adding NUMA
awareness).
