### ISSUE TITLE
How to read Body of a request for server?

### ISSUE THREAD

**Issue by GildedHonour** [hyperium/hyper#1411]
This #1137 suggests 2 ways to read the body. However:

1) no method named `concat` found for type `hyper::Body` in the current scope

2) no method named `fold` found for type `hyper::Body` in the current scope

How to read the body?

**Comment by sfackler** [comment]
Did you `use futures::Stream`?

**Comment by hjr3** [comment]
That issue is out of date now. Have you read https://hyper.rs/guides/client/json/ yet?

**Comment by GildedHonour** [comment]
thx
