### ISSUE TITLE
is there a way to run a hyper server on my own separate reactor core?

### ISSUE THREAD

**Issue by awestlake87** [hyperium/hyper#1417]
I want to run a hyper server as a future on my own reactor core instead of using the core owned by the hyper server. is there a way to just convert the server into a future and run it on another core? 

if not, I think this would be a good feature to have. anything that runs on a tokio core can be represented by a future, so it seems to me that the core does not necessarily need to be tied to the server. it would also mean that a user could choose to run several hyper servers on a single core if they choose to do so.

**Comment by seanmonstar** [comment]
Yes, there is. Have a look at this example: https://github.com/hyperium/hyper/blob/master/examples/multi_server.rs
