### ISSUE TITLE
Up to date example of post

### ISSUE THREAD

**Issue by GildedHonour** [hyperium/hyper#1420]
is there up to date example of sending a post request in hyper with some form data which compiles?

**Comment by seanmonstar** [comment]
I tried giving an answer in #1415. I suggested using the reqwest crate, as it does a lot of the boiler plate for you. If you don't want to use it, then you'd need to manually construct the bytes of the form data yourself, and then send them, similar to the example sending JSON in this [client guide](https://hyper.rs/guides/client/advanced/).

There's no need to open duplicate issues to ask the same question, though.

**Comment by GildedHonour** [comment]
Where is form data in that example?

**Comment by GildedHonour** [comment]
>There's no need to open duplicate issues to ask the same question, though.


There is a need, and even a neccessity. I've asked a concrete question: how to do that in **HYPER!**
