### ISSUE TITLE
enable tcp keepalive for connections

### ISSUE THREAD

**Issue by ensc** [hyperium/hyper#1423]
Please enable TCP keep alive for the `TCPStream` connections.  Else, uncleanly terminated requests (e.g. unplugging of network cable) will stay forever and consume more and more filedescriptors.

Receive/transmit timeouts would be perhaps a better solution.  But they seem to be non-trivial to implement while TCP keep alives come with nearly zero costs (see https://tokio-rs.github.io/tokio-core/tokio_core/net/struct.TcpStream.html#method.set_keepalive).

**Comment by ensc** [comment]
> On most operating systems, TCP keepalive is enabled by default

really?  RFC1122 "4.2.3.6  TCP Keep-Alives says" that it MUST be off by default and that's the case with Linux too.  Keepalive parameters can be configured (with Linux) only globally but not per-process.

> hyper (with client::Connect or server::Http::serve_*)

mmh... (at least) `server::Http::serve_...` seem to be very difficulty to use and probably a lot of hyper internal code must be replicated to make it usable like `bind()`.  E.g. (I do not know why, but) `bind()` allows a lambda expression with non-`'static` elements, while every try with `serve_*` fails due to `'static` related lifetime issues (which are imo a severe design problem of tokio). 

See https://gist.github.com/ensc/155b28cbc07af11c3309348f7b19d9df for an example; `foo()` which uses `bind()` is ok, while `bar()` which tries to reimplement parts of hyper's `run_until()`, fails.


Enabling TCP keepalive in hyper are a few lines of code (one in `Listener::poll()` and perhaps some functions to change the default keep alive time).  I can not imagine a case were a (long running) http server does not want to drop dead connections.

**Comment by seanmonstar** [comment]
Hm, my mistake, some references I found suggested TCP keepalive was enabled by default on Linux.

I guess it seems fine for the default of hyper to just enable these, and if anyone hates them, they can do the more involved config to remove them.

**Comment by mc10** [comment]
I believe this is fixed by 39e03a91e28ef3d42b8a4d1a70fbca3367779155.

**Comment by seanmonstar** [comment]
Yes, this is fixed and in 0.11.19.
