### ISSUE TITLE
Rapid client requests result in "Connection reset by peer"

### ISSUE THREAD

**Issue by PlasmaPower** [hyperium/hyper#1424]
I'm calling `tokio_core.run(hyper_future)` in a loop, and it's resulting in a `Connection reset by peer` which is no fault of the server.

Edit: previously I thought it was a `Connection refused` instead.

Here's what it looks like in Wireshark:

![Wireshark capture](https://user-images.githubusercontent.com/6006498/35311172-680c6268-0072-11e8-9c16-dbee7f831f73.png)

Then a connection refused happens, which hyper doesn't always catch. Sometimes it just hangs.

As you can see, `hyper` (or a library beneath it) is incorrectly reusing a TCP stream for another HTTP request.

This occurs on `0.11.15`, `0.11.0`, and the latest git master. I'll work on reproducing it outside of my larger codebase.

**Comment by sfackler** [comment]
Why do you say it's incorrectly reusing the stream? Does the response contain a `Connection: close`?

**Comment by PlasmaPower** [comment]
Oh, I forgot that was a thing. You're right, the server isn't sending `Connection: close`. It looks like this is a problem with the server after all. I think it should be sending `Connection: close`, as it only breaks when multiple requests are grouped into one TCP stream.
