### ISSUE TITLE
A regression in client response times

### ISSUE THREAD

**Issue by pimeys** [hyperium/hyper#1437]
So I upgraded one of our consumers from hyper 0.11.10 to 0.11.17 today and noticed a considerable regression in the response times we get.

We use hyper to send requests to a single server, keeping the connection alive and requesting thousands of times per second, sending a small JSON body every time. Here's a graph to alleviate the issue:

![response_time3](https://user-images.githubusercontent.com/34967/35871060-9218efbc-0b63-11e8-9f78-88c126483197.png)

So the first spike up (around 16:45) was the deployment from 0.11.10 to 0.11.17, resulting twice slower responses (p50, p70 and especially the p95). Then a bit later around 17:13 a downgrade to 0.11.16 gave us about 10% faster results, but still slow compared to the earlier. A deployment from 0.11.16 to 0.11.15 at 17:23 then returned us back to the original performance.

So something gave a massive regression in the version 0.11.16 and then a change in 0.11.17 (probably https://github.com/hyperium/hyper/commit/265ad67c86379841a5aa821543a01648ccc8c26c) made requesting 10% slower.

**Comment by seanmonstar** [comment]
I'll take a look. That commit specifically could be a measurable increase in atomic operations, causing a 10% slow down in scheduling (it'd be most noticeable if connections are kept alive, always reused, and bodies are small).

For the large regression... just curious, are you using TLS (HTTPS)?

**Comment by pimeys** [comment]
Yes. We're using https. This is the client code:

https://github.com/panicbit/fcm-rust/blob/master/src/client/mod.rs#L42

**Comment by seanmonstar** [comment]
Ok, for the large regression, this is my suspicion:

0.11.16 added improvements to how it does buffering and writing, which greatly helps large bodies, even more so when streaming and chunked encoding are applied. This was done by making use of vectored IO. However, TLS can't really use vectored IO, and I believe most async TLS rust libs just use the default `write_buf` method, which packs up each individual chunk into its own TLS record. If so, that would mean that before 0.11.16, when the write buf was a single flat vector, writes of the headers and payload could fit in the same TLS record (and probably the same IP packet, if not too big). With 0.11.16 using vectored IO, it probably means the headers are in 1 record, and the body is in another.

Ideally, TLS libraries would change to not use the default `write_buf` implementation, but would flatten the bufs themselves. But, we can't really control that, so, perhaps hyper can try to adjust itself.

Here's what I'm thinking: hyper's buffer strategy grows the ability to notice if after a call to `io.write_buf(bufs)`, if only 1 of the bufs was written, it will try to update itself to automatically flatten all bufs for that IO object from then on. It would mean that the very first write could still be split, but if the connection lives for many requests, it will perform better for all the subsequent writes.

Another option, and not necessarily mutually exclusive, is to expose a config option to enable vectored IO, or to always flatten into a single buffer.

**Comment by pimeys** [comment]
I'd say a config option would sound better for Hyper and then again the automatic split for Reqwest. Being able to have more control how the client works in Hyper is one of the things why we'd use it over Reqwest, but for systems triggering requests with more random payloads and endpoints I'd say an automatic solution would work better.

**Comment by seanmonstar** [comment]
Having knobs to twist does seem reasonable. I think it's probably best for hyper to try to automatically be faster when it can, though.

So, as of right now, hyper master contains:

- An auto detector of its write buffer strategy, that will try to notice if no `IoVec`s are used. If it detects that aren't, it will convert itself into a flattening buffer. This means that for brand new connections that don't support vectored writes well, there may be a single write that is smaller, but after that, it will switch to using a single buffer to improve writes with those transports.
- `client::Config::http1_writev(bool)` now exists to allow anyone to disable this auto-detection: simply set that value to `false`. By default, the auto strategy will be used.

**Comment by seanmonstar** [comment]
After reports in IRC that this did fix the issue, this has been published in v0.11.18.

Again, thanks so much for the graph and being able to pin it down to some versions!
