### ISSUE TITLE
Replacing `bind_connection` with `serve_connection`

### ISSUE THREAD

**Issue by juanibiapina** [hyperium/hyper#1447]
I couldn't find information on the changelog. The documentation just says "consider", but no further input.

Maybe this should be written somewhere?

**Comment by seanmonstar** [comment]
Hmm, indeed, some docs on what do to do switch would be a good idea!

**Comment by seanmonstar** [comment]
There's now some example code for `serve_connection: https://docs.rs/hyper/0.11.19/hyper/server/struct.Http.html#method.serve_connection
