### ISSUE TITLE
Two identical Service traits

### ISSUE THREAD

**Issue by DustinByfuglien** [hyperium/hyper#1460]
Why there are two Service traits: hyper::client::Service and hyper::server::Service?
As I believe a Service trait need not depend from client or server nature of things.

May be use hyper::Service instead? Or only hyper::server::Service?

**Comment by seanmonstar** [comment]
Yea, they don't really need to be as different exports. I suppose I was thinking you'd do `use hyper::client::{Client, Request, Service}` and what-not... Could be cleaned up.

**Comment by DustinByfuglien** [comment]
I agree. Two exports of one thing brings some discourage.

**Comment by DustinByfuglien** [comment]
Ops.. I'm accidentally close a topic.

I agree. Two exports of one thing brings some discourage.

**Comment by seanmonstar** [comment]
This should be handled with #1461, likely just export `hyper::Service`.

**Comment by DustinByfuglien** [comment]
Thanx.
hyper::Service sounds reasonably.
