### ISSUE TITLE
Update Service trait from tokio-service to tower

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1461]

**Comment by kamyuentse** [comment]
Hi, I want to have a try, any mentoring instructions for this change?

**Comment by seanmonstar** [comment]
This wouldn't be too much work in hyper directly, but it does require [tower](https://github.com/tower-rs/tower) to publish a version to crates.io. I'd probably expect it to do so only after futures 0.2, since it needs to update to the new futures.
