### ISSUE TITLE
Create Body from Stream

### ISSUE THREAD

**Issue by danneu** [hyperium/hyper#1468]
Body implements Stream, but there doesn't seem to be a simple way to turn a chunk stream back into a Body.

For example, the most obvious gzip middleware would look like this:

```rust
fn gzip(body: Body) -> Body {
    let stream = body.and_then(|chunk| compress(chunk));
    Body::stream(Box::new(stream))
}

let response = Response::new();
let gzipped = Response::new().with_body(gzip(response.body()))
```

But as far as I can tell, the only tool Body gives us is `Body::pair()` so I suppose we do something like this:

```rust
fn gzip(pool: CpuPool, body: Body) -> Body {
    let stream = body.and_then(|chunk| compress(chunk));
    let (tx, body) = Body::pair();
    pool.spawn(tx.send_all(stream.map(Ok).map_err(|_| unreachable!())))
        .forget();
    body
}
```

It's not very user friendly. Nor am I sure if I implemented that correctly. It doesn't seem like the right abstraction for when you just want to transform the chunk stream.

For example, imagine if:

- The body::Inner enum had a new variant `Stream(Box<Stream<Chunk, Error>>)`
- Body's poll() impl had a new branch `Stream(stream) => stream.poll()`
- Body had a new constructor `Body::stream(stream)`

**Comment by scottlamb** [comment]
I think you're in luck. (And me; I've been wanting this too.) Looks like 0.12.x is going to add it. See `Body::wrap_stream` on master and #1438.

**Comment by scottlamb** [comment]
btw, even now on 0.11.x, you don't have to use `Body` at all; you can instead use something like `hyper::Response<Box<Stream<Item = Vec<u8>, Error = Error> + Send>>`. The downside is that you may be giving up compatibility with libraries/frameworks that expect `Body`.

**Comment by danneu** [comment]
Sweet, thanks for illuminating. I look forward to trying 0.12.x.
