### ISSUE TITLE
Simpler way to transform response body, `response.deconstruct()`

### ISSUE THREAD

**Issue by danneu** [hyperium/hyper#1469]
If you want to transform a response's body, there doesn't seem to be a nice way to consume the old response into a new response but with a different body. For example, this isn't so great:

```rust
let response2 = Response::new()
    .with_status(response.status().clone())
    .with_headers(response.headers().clone())
    .with_body(transform(response.body()))
```

Looking around hyper's code, it looks like `hyper::proto::response::{from_wire, split}` are ideal, but they are private functions. But this is exactly what I want to do in middleware:

```rust
use hyper::proto::response::{from_wire, split};

let (head, body) = split(response);
let response2 = from_wire(head, transform(body))
```

I'm not super experienced, so I might be missing something that suits my fancy. But so far `response.body()` has been a nuisance because it consumes the response but only moves out the body.

Moving the status, headers, and body out of the response in one go, like `Request#deconstruct()`, and a way to construct them back into a response would be much more helpful in middleware.

**Comment by seanmonstar** [comment]
In 0.12.x, hyper will move to `http`s Response type. It provides a few methods to do what you're saying, such as [map](https://docs.rs/http/0.1.*/http/response/struct.Response.html#method.map).

**Comment by danneu** [comment]
@seanmonstar Great stuff. I made my two issues at a bad time. Didn't realize hype was in the middle of a transition.

Looks good, thanks.
