### ISSUE TITLE
Example code provided does not compile :(

### ISSUE THREAD

**Issue by dataf3l** [hyperium/hyper#1472]
When I copy and paste the examples, the examples do not compile, here is my toml file:

[dependencies]
futures = "0.1.17"
hyper = "0.11.22"
pretty_env_logger = "0.2.2"
tokio = "0.1.3"

All I ever did was choose the wrong dependencies I guess?

https://github.com/hyperium/hyper/blob/5db85316a10d0b7bdd36524d85a746a23bd10190/examples/web_api.rs#L1

error[E0599]: no associated item named `GET` found for type `hyper::Method` in the current scope
  --> main.rs:32:15
   |
32 |             (&Method::GET, "/") | (&Method::GET, "/index.html") => {
   |               ^^^^^^^^^^^

error[E0599]: no associated item named `GET` found for type `hyper::Method` in the current scope
  --> main.rs:32:37
   |
32 |             (&Method::GET, "/") | (&Method::GET, "/index.html") => {
   |                                     ^^^^^^^^^^^

error[E0599]: no associated item named `GET` found for type `hyper::Method` in the current scope
  --> main.rs:36:15
   |
36 |             (&Method::GET, "/test.html") => {
   |               ^^^^^^^^^^^

error[E0599]: no associated item named `POST` found for type `hyper::Method` in the current scope
  --> main.rs:55:15
   |
55 |             (&Method::POST, "/web_api") => {
   |               ^^^^^^^^^^^^

error[E0061]: this function takes 0 parameters but 1 parameter was supplied
  --> main.rs:34:60
   |
34 |                 Box::new(futures::future::ok(Response::new(body)))
   |                                                            ^^^^ expected 0 parameters

error[E0308]: mismatched types
  --> main.rs:38:56
   |
38 |                 let client = Client::configure().build(&self.0);
   |                                                        ^^^^^^^ expected struct `tokio_core::reactor::Handle`, found struct `tokio::reactor::Handle`
   |
   = note: expected type `&tokio_core::reactor::Handle`
              found type `&tokio::reactor::Handle`

error[E0599]: no function or associated item named `builder` found for type `hyper::Request<_>` in the current scope
  --> main.rs:39:27
   |
39 |                 let req = Request::builder()
   |                           ^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `POST` found for type `hyper::Method` in the current scope
  --> main.rs:40:29
   |
40 |                     .method(Method::POST)
   |                             ^^^^^^^^^^^^

error[E0599]: no function or associated item named `wrap_stream` found for type `hyper::Body` in the current scope
  --> main.rs:47:32
   |
47 |                     let body = Body::wrap_stream(web_res.into_body().into_stream().map(|b| {
   |                                ^^^^^^^^^^^^^^^^^

error[E0599]: no method named `into_body` found for type `hyper::Response` in the current scope
  --> main.rs:47:58
   |
47 |                     let body = Body::wrap_stream(web_res.into_body().into_stream().map(|b| {
   |                                                          ^^^^^^^^^
   |
   = help: did you mean `set_body`?

error[E0277]: the trait bound `[u8]: std::marker::Sized` is not satisfied
  --> main.rs:47:89
   |
47 |                     let body = Body::wrap_stream(web_res.into_body().into_stream().map(|b| {
   |                                                                                         ^ `[u8]` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `[u8]`
   = note: all local variables must have a statically known size

error[E0061]: this function takes 0 parameters but 1 parameter was supplied
  --> main.rs:52:35
   |
52 |                     Response::new(body)
   |                                   ^^^^ expected 0 parameters

error[E0599]: no function or associated item named `wrap_stream` found for type `hyper::Body` in the current scope
  --> main.rs:57:28
   |
57 |                 let body = Body::wrap_stream(req.into_body().into_stream().map(|chunk| {
   |                            ^^^^^^^^^^^^^^^^^

error[E0599]: no method named `into_body` found for type `hyper::Request` in the current scope
  --> main.rs:57:50
   |
57 |                 let body = Body::wrap_stream(req.into_body().into_stream().map(|chunk| {
   |                                                  ^^^^^^^^^
   |
   = help: did you mean `set_body`?

error[E0277]: the trait bound `futures::Future<Item=hyper::Response, Error=hyper::Error> + 'static: std::marker::Send` is not satisfied
  --> main.rs:46:17
   |
46 | /                 Box::new(web_res_future.map(|web_res| {
47 | |                     let body = Body::wrap_stream(web_res.into_body().into_stream().map(|b| {
48 | |                         Chunk::from(format!("before: '{:?}'<br>after: '{:?}'",
49 | |                                             std::str::from_utf8(LOWERCASE).unwrap(),
...  |
52 | |                     Response::new(body)
53 | |                 }))
   | |___________________^ `futures::Future<Item=hyper::Response, Error=hyper::Error> + 'static` cannot be sent between threads safely
   |
   = help: the trait `std::marker::Send` is not implemented for `futures::Future<Item=hyper::Response, Error=hyper::Error> + 'static`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<futures::Future<Item=hyper::Response, Error=hyper::Error> + 'static>`
   = note: required because it appears within the type `std::boxed::Box<futures::Future<Item=hyper::Response, Error=hyper::Error> + 'static>`
   = note: required because it appears within the type `hyper::client::FutureResponse`
   = note: required because it appears within the type `futures::Map<hyper::client::FutureResponse, [closure@main.rs:46:45: 53:18]>`
   = note: required for the cast to the object type `futures::Future<Item=hyper::Response, Error=hyper::Error> + std::marker::Send`

error[E0061]: this function takes 0 parameters but 1 parameter was supplied
  --> main.rs:62:60
   |
62 |                 Box::new(futures::future::ok(Response::new(body)))
   |                                                            ^^^^ expected 0 parameters

error[E0599]: no function or associated item named `builder` found for type `hyper::Response<_>` in the current scope
  --> main.rs:66:46
   |
66 |                 Box::new(futures::future::ok(Response::builder()
   |                                              ^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `NOT_FOUND` found for type `hyper::StatusCode` in the current scope
  --> main.rs:67:54
   |
67 |                                              .status(StatusCode::NOT_FOUND)
   |                                                      ^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `serve_addr` found for type `hyper::server::Http<_>` in the current scope
  --> main.rs:83:33
   |
83 |         let serve = Http::new().serve_addr(&addr, move || Ok(ResponseExamples(handle.clone()))).unwrap();
   |                                 ^^^^^^^^^^

error: aborting due to 19 previous errors

error: Could not compile `sync`.

Life is but tragedy, an eternal struggle against the forces of nature.

**Comment by seanmonstar** [comment]
The master branch is now 0.12.x, a work-in-progress. It does not match the release 0.11.22 version.

You can view the examples in https://github.com/hyperium/hyper/tree/0.11.x, and https://hyper.rs/guides will always use the current release version.

**Comment by dataf3l** [comment]
@seanmonstar Thank you, that solved my problem, I'm now using these Cargo.toml file:


[dependencies]
futures = "0.1.17"
hyper = "0.11.22"
pretty_env_logger = "0.2.2"
tokio-core = "0.1.15"

and that seems to have solved the problem, Thank you for your help!
