### ISSUE TITLE
TCP_NODELAY on client

### ISSUE THREAD

**Issue by 1tgr** [hyperium/hyper#1473]
How can I set nodelay on an HTTP client connection? If it's not exposed by hyper, can I get access to the underlying `TcpStream` so I can call [`TcpStream::set_nodelay`](https://tokio-rs.github.io/tokio-core/tokio_core/net/struct.TcpStream.html#method.set_nodelay)?

**Comment by seanmonstar** [comment]
There's no super easy way currently. You could make a connector that wraps the `HttpConnector`, accessing the TcpStream there.

I'd be fine with this being an option on `HttpConnector` directly ...

**Comment by 1tgr** [comment]
Thanks, I came up with this wrapper for now:

```rust
pub struct HttpNoDelayConnector(HttpConnector);

impl Service for HttpNoDelayConnector {
    type Request = Uri;
    type Response = TcpStream;
    type Error = io::Error;
    type Future = Box<Future<Item=Self::Response, Error=Self::Error>>;

    fn call(&self, uri: Uri) -> Self::Future {
        Box::new(self.0.call(uri).map(|s| {
            s.set_nodelay(true).unwrap();
            s
        }))
    }
}
```

Will see if I can put together a pull request to set this directly on `HttpConnector`. With HTTP, I'm not sure there's a reason not to make `TCP_NODELAY` the default.
