### ISSUE TITLE
Replace futures-timer usage with tokio-timer

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1484]

**Comment by srijs** [comment]
I'll happily take this one!

**Comment by kamyuentse** [comment]
@srijs I try to port it last night, but tokio-timer require work with `Runtime`, so in many test cases, `res.join(...).wait()` not work well. Good luck!

**Comment by seanmonstar** [comment]
Oh, interesting! If tokio's `current_thread` executor could be updated to use a timer as well, we could probably change all `wait`s to use that, but it doesn't currently do so.

**Comment by seanmonstar** [comment]
I've also been thinking that hyper could have some `common::Timer` internal type, kind of like `common::Exec`. Doing this would probably even be easier than switching all `wait`s over. Benefits:

- Finer control over a specific timer, if someone doesn't want to use the implicit default.
- Would support making the tokio Runtime optional, in case someone wanted to build hyper with their own runtime.
- Would allow it to work with `wait`.

If no timer were available, timeouts and intervals would effectively just be disabled. That shouldn't be a problem. Here's some code I was thinking of:

```rust
enum TimerImpl {
    Default,
    Empty,
    Timer(Arc<Timer>),
}

trait Timer {
    type Delay: Future;
    fn delay(&self, until: Instant) -> Self::Delay;
}
```

The default would use tokio-timer implicitly, the empty would simply return `future::empty()`, and the trait would allow for custom timers. We'd implement `Timer` for `tokio_timer::Handle`.

Probably the types wouldn't be exported publicly, but the client and server builders could have `timer` functions like their respective `executor` functions.

**Comment by kamyuentse** [comment]
Maybe the "require" not correct, use `wait()` directly  will get a `Shutdown` error, but it work fine with `Runtime::spawn(..)`. I can't find a doc clarify this behavior. Maybe it can work with the `current_thread`.

**Comment by srijs** [comment]
I like the idea of making the timer optional, that seems like it would work well with keeping the current calls to `wait()` as they are, and just not use a timer in those cases (unless the test explicitly tests timeouts/intervals).

However I'm not sure if it's worth abstracting away `tokio-timer`? The `Timer` logic in `tokio-timer` can be used independently of the tokio runtime, so it should be flexible enough for most use-cases.

**Comment by seanmonstar** [comment]
That's probably fine too. I mostly was thinking that there are cases where you could want to use hyper, but already have some other runtime. For that reason, I do expect to make the tokio dependency optional (enabled by default) likely by the 0.12 release.

I also figured people might already be using a different timer implementation, such as using the older tokio-core.

But it's not required to provide that yet. I just would rather not actually expose a dependency on tokio-timer in a type signature, so I actually would rather box a trait object, like is done with `Executor`, instead of accepting tokio's `TaskExecutor` directly.
