### ISSUE TITLE
Can't wrap hyper Client easily since FutureResponse has private fields

### ISSUE THREAD

**Issue by mthebridge** [hyperium/hyper#1510]
This feels like a limitation in hyper, but it may be intentional so querying here first.

I'm trying to write a generic wrapper around `hyper::Client`, to do some request/response tracking.  To do this, I have implemented something that implements `Service` with the same associated types as `hyper::Client`.

The rough API I want is as follows.

```rust
struct MyWrapperClient<T> { inner: T };

impl<T> hyper::Service for MyWrapperClient<T> 
where T: Service<
        Request = hyper::Request<hyper::Body>,
        Response = hyper::Response,
        Error = hyper::Error,
        Future = hyper::client::FutureResponse,
    > {

type Request = <T as Service>::Request;
    type Response = <T as Service>::Response;
    type Error = <T as Service>::Error;
    type Future = <T as Service>::Future;

   fn call(&self, req: Self::Request) -> Self::Future {
    //  Wrap the call to`self.inner.call()` with some extra work before and after.
  }
},
```
The problem is that `hyper::client::FutureResponse` has no public constructor.  So I can't just chain the inner `call` method with something else without changing the returned `Future` type, which means my new wrapper can't just be slotted in in place of a `hyper::Client`.
Is this intentional?  It seems like an asymmetry because the same thing works fine on the server side - hyper is not opinionated about the exact type there.

Would it be possible to add a conversion method into hyper?  Then we could write wrappers that can slot in anywhere a hyper client is currently used.  Something like this:

```rust
impl<T> From<T> for FutureResponse 
where T: Future<Item=Response, Error=Error>
```

I'd be happy to submit a PR for this change if you'd like?

**Comment by sfackler** [comment]
The associated future type for a service is going to either be a `Box<Future>` or be unique to every implementation. Consumers shouldn't generally care what the specific future type is.

**Comment by sfackler** [comment]
> At the moment, I can't write a method that can consume either a hyper:client::Client or my new wrapper,

Why not?

```rust
fn foo<T>(service: T)
where
    T: Service<Request = hyper::Request<hyper::Body>, Response = hyper::Response, Error = hyper::Error>
{
    // ...
}
```

**Comment by mthebridge** [comment]
This is what happens when you try and simplify your code down to a minimal example...

It's a bit more complicated than that because I need this to be a trait object. :) I have some existing code that uses a `Box<Service<...>>`, with the same associated types as the `Service` implementation for `hyper:;client:;Client`.  And it is that trait object which I want to be able to be either a standard client crated from `hyper::Client::new()`, or my wrapper type.

I guess I could always define a new trait and implement that for the existing client and my new type, and then require a boxed version of that trait.  It still feels like a slightly weird asymmetry - I can chain Services together easily on the server side, but it feels much harder to do so on the client side.

**Comment by seanmonstar** [comment]
Wrapping the client should mean that the new service provides a new `impl Future` over the wrapped service. This is a pretty common pattern, which we do a lot of in Conduit. For instance, see this simple timeout middleware: https://github.com/tower-rs/tower/blob/master/tower-timeout/src/lib.rs#L60

The reason for hyper's future to have private internals is so that we can change it around, adding new functionality or making optimizations, without being a breaking change.

**Comment by mthebridge** [comment]
Sorry for delay.  I've been back at this and realized that it was our existing other code that was wrong - I've fixed that up and it all works.  Happy to close this down.
