### ISSUE TITLE
Add a README to the examples directory explaining them

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1511]
It'd be really useful when going to the `examples` directory to see a `README.md` explaining what each is. Some examples of other repos that do this nicely:

- [tokio](https://github.com/tokio-rs/tokio/tree/master/examples)
- [gotham](https://github.com/gotham-rs/gotham/tree/master/examples)

**Comment by meven** [comment]
I am on it !

**Comment by meven** [comment]
By the way the send_file example seems not to function.
