### ISSUE TITLE
Add an http1_only configuration for the server

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1512]
The default server now supports both HTTP/1 and 2 automatically. Just like there is an option to set `http2_only`, there should probably also be an `http1_only` option, if for some reason someone didn't want to allow HTTP2 support.

**Comment by ubnt-intrepid** [comment]
When the `http1_only` mode is added, the behavior when the argument of `http2_only(enabled)` is `false` becomes undefined (there are two possible modes whether the fallback is required or not).

**Comment by ubnt-intrepid** [comment]
I've just created an PR for resolving this issue, just adding `http1_only` to `Connection` and `Builder`.

The flag field `http2` in the struct `Http` has replaced with an enum which has three modes (http1_only, http2_only and fallback).
When `http2_only(false)` or `http1_only(false)` are called, the inner mode is set to "fallback".
