### ISSUE TITLE
Why use the high-level server API?

### ISSUE THREAD

**Issue by bluetech** [hyperium/hyper#1513]
This is a general design question, I hope that's appropriate.

`hyper::server` has a high-level API (`Server`, `Builder`) and a low-level API (`Http`, `Connection`). Given a program like this:

```rust
let addr = std::net::SocketAddr::from(([127, 0, 0, 1], 3000));

let new_service = || {
    hyper::service::service_fn_ok(|_req| {
        hyper::Response::new(hyper::Body::from("Hello World"))
    })
};

let server = ...;

tokio::run(server);
```

The high-level API looks like this:

```rust
let server = Server::bind(&addr).serve(new_service).map_err(|e| {
    eprintln!("server error: {}", e));
});
```

The low-level API looks like this:

```rust
let http = hyper::server::conn::Http::new();
let server = tokio::net::TcpListener::bind(&addr)?.incoming().for_each(move |io| {
    let conn = http.serve_connection(io, new_service()).map_err(|e| {
        eprintln!("connection error: {}", e);
    });
    tokio::spawn(conn);
    Ok(())
}).map_err(|e| {
    eprintln!("server error: {}", e);
});
```

I think the "low-level" code is actually preferable:

The server structure is clear: listen on a TCP socket; accept connections; wrap them up in an HTTP protocol; spawn tasks to handle them. The flow is about the same as a threaded synchronous std TCP server. It is clear which errors occur and where they originate. It is not really harder to read or write.

In the high-level API however these important details are hidden.

I suppose my question is: why does the high-level API exist? Or to put it differently, what does one lose by not using it?

Thanks!

**Comment by seanmonstar** [comment]
I think this area is rather subjective. Having written a lot of examples and tests, I think having a way to skip the boilerplate is *very* appealing. I also wonder if the low-level version is preferable to you because you're familiar with all the pieces, but someone wanting to focus on just handling requests may find it annoying or ugly.

Turning the question around, is there a reason to not include it?

**Comment by bluetech** [comment]
I wrote some paragraphs about why I don't think things like binding TCP or spawning tasks are boilerplate, and how the things that `Server` does currently (tcp keepalive, tcp nodelay, sleep on error, graceful shutdown in the future?) would be better handled at a generic TCP level IMO¹. But I decided to spare you all of that - shorter examples/appearing less scary is a good enough reason, even if I don't agree :)

¹ There is also an `AddrStream` type which is a wrapper around `TcpStream` but additionally keeps track of a `remote_addr` for each connection. But `remote_addr` isn't used so I'm not sure what functionality this type serves. (Also not sure why it keeps track of the remote addr itself when `TcpStream::peer_addr()` is available.)

**Comment by lnicola** [comment]
@bluetech there's a saying that goes like "make the easy things easy and the hard things possible". I think it works well in this case.

**Comment by bluetech** [comment]
@lnicola I prefer the ["Simple vs. Easy"](https://github.com/matthiasn/talk-transcripts/blob/master/Hickey_Rich/SimpleMadeEasy.md) idea that nice composable "simple" primitives are preferable to "easy" abstractions. Personally, I don't think Rust should aim for "easy", that fight is quite hopeless compared to other languages. But this is a discussion that is more appropriate for another venue.

**Comment by ddosoff** [comment]
That's strange for me too that low level api prohibited.
