### ISSUE TITLE
should Body implement From<Box<Stream<...>>?

### ISSUE THREAD

**Issue by scottlamb** [hyperium/hyper#1515]
I'm wondering if `Body` could provide something like this:

```rust
impl From<Box<Stream<Item=Chunk, Error=Box<::std::error::Error + Send + Sync>> + Send>> for Body {
    #[inline]
    fn from(stream: Box<Stream<Item=Chunk, Error=Box<::std::error::Error + Send + Sync>> + Send>)
            -> Body {
        Body::new(Kind::Wrapped(stream))
    }
}
```

in addition to or instead of `Body::wrap_stream`.

A couple reasons this seems handy while working on a crate that handles byte range serving:

   * I want it to support either using `Body` or plugging in your own `Payload` type. It needs to do stream ops like `unfold` and `flatten` (see [implementation](https://github.com/scottlamb/http-serve/blob/master/src/serving.rs)), so it ends up with a boxed stream that it wants to turn into your payload type. The most straightforward way to do this that I can think of would be to require this `From` implementation, but then it won't work with `Body`. I could add some extra custom trait and pre-implement it for `Body`, but then there's another thing you need to import for it to work / then either the `Payload` implementation has to depend on my crate or vice versa.
   * when I already have a boxed stream, wrapping it with another box (as `Body::wrap_stream` does) adds an unnecessary allocation.

**Comment by lnicola** [comment]
This is what I had in mind with https://github.com/hyperium/hyper/pull/1505, but it's quite possible it's not general enough.

**Comment by scottlamb** [comment]
Oh, I hadn't noticed #1505. It's double-boxing, though. Yeah, something like `S: Into<Box<Stream<...>>>` sounds promising.

**Comment by lnicola** [comment]
I'm not sure how to do that without running into conflicting implementations :confused:.

**Comment by lnicola** [comment]
@scottlamb #1516
