### ISSUE TITLE
How to set parameters programatically for GET request with hyper?

### ISSUE THREAD

**Issue by da2018** [hyperium/hyper#1520]
Hi, guys, how can I set parameters programatically for GET request?

I read this question from Stackoverflow [Pass data for GET request using Hyper
](https://stackoverflow.com/questions/34757075/pass-data-for-get-request-using-hyper).

But it seems the method has been removed, so how can I do this trick?

**Comment by pimeys** [comment]
Check the `Uri` from the `http` crate:

https://docs.rs/http/0.1.5/http/uri/index.html

**Comment by McGradyDa** [comment]
@pimeys  Both of them(`http` and `hyper`) are http library, so do we need to install two same library to do this?

**Comment by pimeys** [comment]
All http types were moved to another library called http, so yes.

**Comment by pimeys** [comment]
For batteries included crate, that uses hyper under the surface, you should check reqwest:

https://github.com/seanmonstar/reqwest/

**Comment by McGradyDa** [comment]
@pimeys  Thanks.
