### ISSUE TITLE
Payload is not polled to completion

### ISSUE THREAD

**Issue by olix0r** [hyperium/hyper#1521]
We have a `Payload`-wrapper implementation that wants to take some action (e.g. record stats) once the payload is complete.  I expect `poll_data` to be called until _None_ is returned or until `is_end_stream` returns _true_. However, in practice I see that `poll_data` is called just once, returns data (not _None_), and is just dropped by hyper.

Now, of course, I can just implement `Drop`; but it would be helpful to clarify the contract for `Payload`s. Should they be polled to completion? Should they typically be dropped before `is_end_stream` returns true?

**Comment by seanmonstar** [comment]
In the usual case, the payload should be polled to completion. Here's the cases I can think of where it wouldn't be:

- There was an error on the connection.
- After a poll, `is_end_stream` claimed it was done.
- The body was not allowed, such as in response to a HEAD request, or as a 204 or 304 status code.
- The headers (or the `content_length` method of the payload) declared a length, and the state machine detects the length has been reached. Any extra chunks would be wasted.

**Comment by olix0r** [comment]
In the specific case I'm encountering, Conduit is proxying an HTTP/1 request with a Hyper server and client.

1. The client receives a response (and Body) and returns it to the server.
2. We wrap the client's body type with an implementation that does some extra accounting. 
3. When we `poll_data` the underlying body, we get data that matches content-length.

At this point I expect that `body.is_end_stream()` should return _true_, but it does not.

> * After a poll, `is_end_stream` claimed it was done.
> * The headers (or the `content_length` method of the payload) declared a length, and the state machine detects the length has been reached. Any extra chunks would be wasted.

Is it a bug that `body.is_end_stream()` returns false even though the complete body data has been returned from `poll_data`?

**Comment by sfackler** [comment]
is_end_stream is a hint:

https://github.com/hyperium/hyper/blob/c3c35e866c06d8d0f7347cebff86b0442b33e2b3/src/body.rs#L57-L70

**Comment by olix0r** [comment]
@sfackler thanks for the clarification!
