### ISSUE TITLE
HTTP redirects in client as a hyper service.

### ISSUE THREAD

**Issue by oa-metaswitch** [hyperium/hyper#1526]
Hi all. I've run into a bit of an issue with handling 302 redirects and I'm wondering if there's a good way to do it.

Briefly, I'm trying to write a hyper service which wraps a client, and which will follow HTTP redirects if it receieves a 302 response. For design reasons I'd rather not use reqwest, and would like to implement this as a hyper service. That way our client code can remain fairly simple.

So as an outline it would look like

```
struct<T> RedirectService<T: Service<Request, ...>> {
   client: T
}

impl<T: Service> Service for RedirectService<T> {
    ...
    fn call(&self, req: http::Request) -> Self::Future {
        let result = self.client.call(req.clone())?;
        match result.status() {
            TemporaryRedirect => //handle the redirect
            ...
        }
    }
}
```
Obviously this is grossly simplified, apologies for that.

The issue I've run into is that redirects require you to store off a copy of the HTTP request in case you get a 302 back. As far as I can tell, this can only be done by deconstructing the request, cloning each component (except the extensions), and then consuming the body before cloning it. Then I have to reconstruct the request again.

So, I'm wondering:
  - Are there better ways of cloning the request off that I'm just not seeing. Alternatively could we have request impl clone if the body type implements it?
  - Any thoughts on whether this is a good fit for the service pattern, and if so if there's a better way of doing it?

Thanks.

**Comment by seanmonstar** [comment]
Hm, it would be nice if `Request<CloneableBody>` were `Clone`, that's true! But, I think `Extensions` are going to prevent that from being possible.

Otherwise, I think your approach is very similar to what I would do myself!

**Comment by oa-metaswitch** [comment]
Thanks! I've got a prototype version up and running and it seems to be working fine.
