### ISSUE TITLE
Request struct from Server is not compatible to send with Client

### ISSUE THREAD

**Issue by daxhuiberts** [hyperium/hyper#1532]
I've been trying to build a simple proxy with hyper for a short while. With the release of v0.12.0 this tweet showed up (https://twitter.com/olix0r/status/1002690454691897344) showing a simple proxy. That intrigued me, because when I initially started writing my proxy I couldn't get it to work. So tried it again and still it does not work. It gives the following error `request error: an IO error occurred: invalid URI for Client Request`.

When a request comes in the hostname and path segment are split up like this:
`Request { method: GET, uri: /foo/bar, version: HTTP/1.1, headers: {"host": "localhost:2000", "user-agent": "curl/7.54.0", "accept": "*/*"}, body: Body }`

But when sending a request with Client it requires a complete URI in `uri` field.

Is this something which is intended to work?

**Comment by seanmonstar** [comment]
This is known, and why I called it a very naive proxy. It can only work if the proxy received an absolute-form request target. That is what is described as well in RFC7230. A proper proxy would also handle relative URIs, assuming they were trying to talk directly to the proxy.
