### ISSUE TITLE
unresolved import `hyper::header::SetCookie`

### ISSUE THREAD

**Issue by Empty2k12** [hyperium/hyper#1536]
I am trying to readout cookies sent by the server: 

```
match res.headers().get::<SetCookie>() {
    Some(&SetCookie(ref content)) => println!("Cookie: {:?}", content),
    _ => println!("No cookie found"),
}
```

However, the import for `SetCookies`, `use hyper::header::SetCookie` does not work. I'd greatly appreciate any hints and updated documentation on this.

**Comment by seanmonstar** [comment]
If trying to use 0.12, the reason the import doesn't work is because it is no longer there.
