### ISSUE TITLE
Starting a Service

### ISSUE THREAD

**Issue by gsquire** [hyperium/hyper#1541]
I looked through the guides and noticed that the examples use the `service_fn_ok` function to create a type that can be used to `serve` connections for a `Server`.

I also noticed that `NewService` is implemented for:

```rust
Fn() -> R where R: IntoFuture<Item = S>, S: Service ...
```

I tried creating a closure that would return `future::ok` with an instance of my `Service` but it implements `FnOnce` since it moves the value. Is there an obvious way to start a `Service` that I am missing?

Thanks for your time.

**Comment by seanmonstar** [comment]
The `NewService` gets called for *every* connection, so it cannot be `FnOnce`. You could either construct a new `Service` each time, or if you want to share some state, then you could clone it.

**Comment by gsquire** [comment]
Ok, I'll give that shot. I think I misunderstood the idea of a `Service` before but this makes more sense now.

**Comment by gsquire** [comment]
I'm not reopening this but if you have a second, [this](https://github.com/gsquire/reroute/pull/18) is what I came up with. I'm not convinced it's entirely ideal at the moment but it at least works.
