### ISSUE TITLE
Incoming HTTP2 bodies should know content_length

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1546]
When receiving a body over HTTP2, the `Body::content_length` call should be able to say how big it is if the `content-length` header was present.

## Steps to fix

- Update `Kind::H2` variant of `Body` to include an `Option<u64>`.
- Update the `Body::h2` constructor to take a secong argument, `Option<u64>`.
- Update both `proto::h2::client` and `proto::h2::server` to look for and parse a `content-length` header before calling `Body::h2`.

**Comment by joshleeb** [comment]
Is it worth `Body::content_length()` returning the content length of the received response even if the header isn't present?

I assuming that a request without a `content-length` header is still valid, and that we can simple figure out the content length by taking the length of the body.

**Comment by lnicola** [comment]
I think this is about returning the value of the `Content-Length` header. `hyper` doesn't buffer the message, so if the other side doesn't send the header, `Body::content_length()` has no way of knowing what to return.

**Comment by joshleeb** [comment]
That makes sense. Thanks @lnicola

**Comment by seanmonstar** [comment]
Exactly as @lnicola said. This is about when a user receives a `hyper::Body` from hyper, the `<Body as Payload>::content_length()` call can try to give more information. This is especially useful if using that body to stream to a different message, such as in a proxy, having made a client request, and gotten a response back, and then returning that body as your own server's body.

As the documentation of `content_length` says, it's OK to not know the answer. It's just a hint to allow hyper to add a `content-length` header if not present. This in turn means that several common body cases will include a `content-length` header without forcing the user to remember it (like returning `Body::from("hello world")`.

**Comment by lnicola** [comment]
@joshleeb Do you want to take this?
