### ISSUE TITLE
HTTP2 should cancel quickly if stream is reset

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1549]
When sending a body over HTTP2, if it takes a while to generate another chunk (so, `Payload::poll_data` returned `NotReady`), and the remote sends a `RST_STREAM`, the body should be canceled at that moment. Currently, hyper won't notice the `RST_STREAM` until once `Payload::poll_data` notifies the task that a new chunk is ready, and then hyper tries to write it via `send_data`.

In a similar vein, in the server, if a `Future` for a `Response` takes a while, we should also be sure to cancel that `Future` immediately if the client sends a `RST_STREAM` for it.

## Steps to fix

- Essentially, the fix is applying what was done in tower-h2, in [this commit](https://github.com/tower-rs/tower-h2/commit/a9eb8fcc4ef0941a8f04807a5a63dc3452ade7b9).

**Comment by joshleeb** [comment]
I'd like to take this one on 😄

**Comment by joshleeb** [comment]
@seanmonstar apologies for taking so long to get to this.

I've used the `tower-h2` code as a guide but I'm not sure if I'm on the right track.
