### ISSUE TITLE
Cannot compile example client.rs

### ISSUE THREAD

**Issue by cSchubes** [hyperium/hyper#1552]
Hi,

I am trying to compile and use the most basic example for a client, client.rs. My Cargo.toml looks like:
```
[dependencies]
hyper = "0.12"
```
And I have copied the code exactly. However, on the `rt::run(rt::lazy(move || ` line, I am getting a trait bound error:
```
the trait bound `(): hyper::rt::Future` is not satisfied

the trait `hyper::rt::Future` is not implemented for `()`

note: required because of the requirements on the impl of `futures::future::IntoFuture` for `()`
note: required by `futures::future::lazy::Lazy`
```
What is going on here?

**Comment by seanmonstar** [comment]
Hey there! You have the exact same source as https://github.com/hyperium/hyper/blob/master/examples/client.rs ? We have CI run on every commit, and it's compiling. I suspect something may have snuck in. For instance, a semi colon on the end of the client request chain.

Zooming out, the error is that `future::lazy` requires the returned result of the closure to implement `IntoFuture`, but instead, `()` is being returned. `()` is implicitly returned if *nothing* is returned, as well.

**Comment by cSchubes** [comment]
Hi Sean,

Thanks for getting back to me so quickly. Something was off on my system - cloning the entire repo fixed everything. Good to know that about future::lazy.
