### ISSUE TITLE
server panic when sending data after connection upgrade

### ISSUE THREAD

**Issue by bubaflub** [hyperium/hyper#1553]
I'm trying to follow http://seanmonstar.com/post/172531530657/http-upgrades-with-hyper and https://github.com/hyperium/hyper/blob/master/tests/server.rs#L1084 to create a server that:

1. accepts a CONNECT request
1. creates a TcpStream to the host & port specified in the request
1. if that's unsuccessful return an error code
1. otherwise return a 200 OK and splice the client and upstream connections together

I'm seeing the following panic:
```
thread 'main' panicked at 'assertion failed: self.state.cached_headers.is_none()', /Users/bob/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.1/src/proto/h1/conn.rs:437:17
```

Even though I've done something like:
```
    let listen_addr = env::args().nth(1).unwrap_or("127.0.0.1:8081".to_string());
    let listen_addr = listen_addr.parse::<SocketAddr>().unwrap();

    // Create a TCP listener which will listen for incoming connections.
    let listener = TcpListener::bind(&listen_addr).unwrap();
    println!("Listening on: {}", listen_addr);
    ...
    let fut = listener.incoming()
        .map_err(|e| println!("error accepting socket; error = {:?}", e))
        .into_future()
        .map_err(|_| -> hyper::Error { unreachable!() })
        .and_then(|(item, _incoming)| {
            let socket = item.unwrap();
            ...
            let conn = Http::new()
                .serve_connection(socket, service_fn(move |req: Request<Body>| {
                    let upstream_addr = req.uri().authority_part().unwrap().as_str()
                                        .parse::<SocketAddr>().unwrap();
                    let upstream_conn = TcpStream::connect(&upstream_addr);
                    let mut res = Response::new(Body::empty());
                    match upstream_conn.wait() {
                        Ok(v) => *upstream_clone.borrow_mut() = Some(v),
                        Err(e) => *res.status_mut() = StatusCode::NOT_FOUND,
                    };
                    Ok::<_, hyper::Error>(res)
                }));
            ...
            let mut conn_opt = Some(conn);
            future::poll_fn(move || {
                try_ready!(conn_opt.as_mut().unwrap().poll_without_shutdown());
                Ok(conn_opt.take().unwrap().into())
            })
        });
    let client_conn = fut.wait().unwrap().into_parts().io;
    ...
```

I expected the `.serve_connection` to fire only on `accept()` and for the first HTTP request/response pair but after that to have underlying TcpStream object available without hyper parsing any of the requests.

I'll try to reduce this to a minimal test-case.

**Comment by seanmonstar** [comment]
So, I have discovered that `CONNECT` requests don't actually trigger the upgrade code like responding with a 101 does. Woops!

I've got a new test for that, and a fix, which should at least get that part working. I haven't yet seen this assert triggered, though.

**Comment by seanmonstar** [comment]
The newest commit to master includes a fix to treat `CONNECT`s as upgrades.

**Comment by seanmonstar** [comment]
And the next commit after that, I believe I found what was triggering the debug assert. The connection had replied once with a response, and so cached the header map allocation to be used for a new request. Then, the connection, since it wasn't "upgraded", treated the next read bytes an HTTP parse error, trying to write a 400 response. When writing the response, the debug assert noticed I had "forgotten" to re-use the cached headers.
