### ISSUE TITLE
Loose type constraint on `hyper::server::Builder::Serv`?

### ISSUE THREAD

**Issue by yjh0502** [hyperium/hyper#1561]
It seems that some `Send` and `Sync` contraints could be removed on `hyper::server::Builder::Serv`. Because of those constraints, I cannot reuse a service written for hyper `0.11`, which does not implements `Send`. Is there any reason for those constraints?

Here's my patch for loosing those constraints.

https://github.com/yjh0502/hyper/commit/859115ec18799aab51f18abe0824a4d9a5aa24fd

**Comment by sfackler** [comment]
Does that patch compile? The server runs in a thread pool in 0.12 so futures can be sent from one thread to another.

**Comment by yjh0502** [comment]
Yes it compiles.

```
$ git branch
* loose_types
  master
$ git log HEAD~1..HEAD
commit 859115ec18799aab51f18abe0824a4d9a5aa24fd (HEAD -> loose_types, yjh0502/loose_types)
Author: Jihyun Yu <yjh0502@gmail.com>
Date:   Mon Jun 11 12:16:10 2018 +0900

    loose type constraint on `serv`
$ cargo clean && cargo check
   Compiling nodrop v0.1.12
   Compiling libc v0.2.42
   Compiling cfg-if v0.1.3
   Compiling lazy_static v1.0.1
   Compiling memoffset v0.2.1
   Compiling byteorder v1.2.3
   Compiling scopeguard v0.3.3
   Compiling futures v0.1.21
   Compiling slab v0.4.0
   Compiling lazycell v0.6.0
   Compiling fnv v1.0.6
   Compiling indexmap v1.0.1
   Compiling string v0.1.0
   Compiling try-lock v0.1.0
   Compiling httparse v1.2.4
   Compiling crossbeam-utils v0.3.2
   Compiling log v0.4.2
   Compiling arrayvec v0.4.7
   Compiling crossbeam-epoch v0.4.1
   Compiling iovec v0.1.2
   Compiling net2 v0.2.32
   Compiling num_cpus v1.8.0
   Compiling rand v0.4.2
   Compiling time v0.1.40
   Compiling bytes v0.4.8
   Compiling crossbeam-deque v0.3.1
   Compiling mio v0.6.14
   Compiling http v0.1.5
   Compiling tokio-io v0.1.6
   Compiling tokio-executor v0.1.2
   Compiling want v0.0.4
   Compiling futures-cpupool v0.1.8
   Compiling tokio-threadpool v0.1.4
   Compiling tokio-timer v0.2.4
   Compiling tokio-reactor v0.1.1
   Compiling tokio-fs v0.1.0
   Compiling tokio-udp v0.1.0
   Compiling tokio-tcp v0.1.0
   Compiling tokio v0.1.7
   Compiling h2 v0.1.9
   Compiling hyper v0.12.1 (file:///home/jihyun/repo/git/hyper)
    Finished dev [unoptimized + debuginfo] target(s) in 7.93 secs
```

**Comment by sfackler** [comment]
Ah right, server doesn't manage its own event loop anymore.

**Comment by yjh0502** [comment]
I found more `Send` that could be removed.

https://github.com/yjh0502/hyper/commit/450bc9b78d9de747c6f9886b0a96de67992e83ee

**Comment by seanmonstar** [comment]
For what it's worth, I've been working on a branch to add HTTP upgrades to a higher-level API, such as `Client` and `Server`. It's relying on the transport being `AsyncRead + AsyncWrite + Send + 'static` to allow passing it as a boxed trait object in the `Body`. Removing these bounds here would make the current approach impossible.

Is there need for the IO type to be `!Send`?

**Comment by yjh0502** [comment]
Sorry for late reply. I'm trying to migrate from `0.11` to `0.12`. The hardest part is about `Send`, which is not required on `0.11` because it runs on single tokio core. My code has quite amount of `std::rc::Rc` and `std::ref::RefCell` to represent shared internal state across multiple http requests. Those should be changed to `std::arc::Arc` and `std::sync::Mutex` to be `Send`. The amount of code for those changes for quite large so I'm trying to find a way to run hyper on single thread, as `0.11` does.

It seems that even if those constraints are relaxed hyper cannot run on single thread because of an executor, which forces the future to be `Send`.

https://github.com/hyperium/hyper/blob/d127201ef22b10ab1d84b3f2215863eb2d03bfcb/src/common/exec.rs#L20-L38

The problem could be solved by using `tokio::executor::current_thread::spawn` instead of `tokio_executor::spawn` [1]. The patch is reasonably small so I think I can maintain patched hyper while migrating to `std::arc::Arc`.

[1] https://github.com/yjh0502/hyper/commit/1353f849cb7d693257d37a9d487e87e397a2c574
