### ISSUE TITLE
Can't create or modify hyper::client::connect::Destination

### ISSUE THREAD

**Issue by kpcyrd** [hyperium/hyper#1564]
I'm trying to write a connector that takes a destination, modifies it and passes it to the next connector. It seems this is currently not possible because there's no way to get a mutable reference to the internal state and only hyper can create new `Destination` objects.

My usecase is having a custom dns resolver as a Connector that resolves the domain before passing it to the final HttpConnector that creates the connection.

**Comment by seanmonstar** [comment]
I definitely get the use case! I'd like to find a way to support it, but I'd also like to list why the constructor was so far private:

- The `Destination` type *may* gain more fields, such as in #1485 to support ALPN.
- I worried that if a `Destination` gained more fields in new release, and a connector didn't know that and could create their own, then it could be possible for some intent on the connect action could be silently lost.

What if, without adding a constructor, you could just mutate the internal URI of the `Destination`?

**Comment by kpcyrd** [comment]
that would work for me as well

**Comment by sfackler** [comment]
This would be nice for me as well. In hyper 0.11, I had a "stack" of composed connectors: `HttpsConnector<ProxyConnector<HttpConnector>>`. The ProxyConnector handled CONNECT tunneling for HTTPS proxies, and so needs to tell the underlying connector to point to the proxy address. In 0.12, that isn't currently possible so I ended up using a non-connector type under the ProxyConnector that just took a host/port.
