### ISSUE TITLE
How to share Tokio::core

### ISSUE THREAD

**Issue by nappa85** [hyperium/hyper#1567]
Im building an authentication microservice, ldap3 crate uses tokio too, if I use it inside hyper it panics with "cannot recursively call into `Core`".
ldap3 accepts a reference to core as a parameter, but I can't find how to share the same tokio::core between hyper and ldap3.

**Comment by seanmonstar** [comment]
What version of hyper are you using? The latest version, 0.12, doesn't use `tokio_core` anymore, and doesn't need to own a reactor, but instead is better at supporting an external reactor.

**Comment by nappa85** [comment]
I'm using 0.12.1

**Comment by nappa85** [comment]
After a little inspection, the problem is given by tokio-threadpool, dependency of tokio.
The backtrace is:
   1: tokio_executor::enter::enter
             at tokio-executor-0.1.2/src/enter.rs:40
   2: tokio_threadpool::worker::Worker::do_run::{{closure}}
             at tokio-threadpool-0.1.4/src/worker/mod.rs:113
   3: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:290
   4: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:244
  5: tokio_threadpool::worker::Worker::do_run
             at tokio-threadpool-0.1.4/src/worker/mod.rs:106
  6: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
             at tokio-threadpool-0.1.4/src/pool/mod.rs:411

tokio_executor::enter is callable only once, I can't use tokio::core in an hyper-based application.

**Comment by seanmonstar** [comment]
The last part isn't quite true. You *can* use `tokio-core` along with `tokio`. What you *can't* do, is try to call `Core::run()` from inside a future that is already executing on a tokio executor.
