### ISSUE TITLE
Using tokio_threadpool::blocking for getaddrinfo

### ISSUE THREAD

**Issue by srijs** [hyperium/hyper#1570]
I'm wondering how viable it would be to use tokio's [`blocking`](https://docs.rs/tokio-threadpool/0.1.4/tokio_threadpool/fn.blocking.html) feature for dns lookups, removing the need to spawn a thread pool internally.

This could take the shape of something like `HttpConnector::default` which could be used by default in `Client::new`.

I know that `blocking` is used successfully in `tokio-fs`, but given that a DNS lookup tends to have a much higher worse-case latency, I'm unsure if this is a good idea.

Do you have any thoughts on it?

**Comment by sfackler** [comment]
`blocking` will only work if you're running with the threadpool executor, (and not e.g. the current thread executor), so you'd need to be able to configure this. #1517 is related.

**Comment by seanmonstar** [comment]
I have thought about it briefly, and as you mentioned, I worried about the generally much longer blocking of a DNS lookup vs reading a file that may be in cache.

However, as mentioned, this would prevent the connector from working with any other executor.

**Comment by seanmonstar** [comment]
I'm going to close for now, since making `HttpConnector` require `tokio-threadpool` is not really possible. It should be possible to explore a separate connector that does what this issue describes, though!
