### ISSUE TITLE
Error http2 general error: protocol error: frame with invalid size

### ISSUE THREAD

**Issue by avkonst** [hyperium/hyper#1574]
I am not sure if it relates to the lack of [ALPN support](https://github.com/hyperium/hyper/issues/1485) or not, but forced http2 connection from hyper client to https://nghttp2.org/ causes "frame with invalid size" error. The test server supported protocols are documented [here](https://github.com/nghttp2/nghttp2#public-test-server)

The same error is observed when I hit the server based on Jetty HTTP 2 server.

The reproducer is the following:
```toml
[package]
name = "test_hyper"
version = "0.1.0"

[dependencies]
hyper = "0.12"
hyper-tls = "0.2.1"
pretty_env_logger = "0.2.0"
```

Notice the client forces http2 only.
```rust
#![deny(warnings)]
extern crate hyper;
extern crate hyper_tls;
extern crate pretty_env_logger;

use std::env;
use std::io::{self, Write};

use hyper::Client;
use hyper::rt::{self, Future, Stream};

use hyper_tls::HttpsConnector;

fn main() {
    pretty_env_logger::init();

    // Some simple CLI args requirements...
    let url = match env::args().nth(1) {
        Some(url) => url,
        None => {
            println!("Usage: client <url>");
            return;
        }
    };

    let url = url.parse::<hyper::Uri>().unwrap();
    rt::run(fetch_url(url));
}

fn fetch_url(url: hyper::Uri) -> impl Future<Item=(), Error=()> {

    let https = HttpsConnector::new(4).unwrap();
    let client = Client::builder()
        .http2_only(true)
        .build::<_, hyper::Body>(https);

    client
        // Fetch the url...
        .get(url)
        // And then, if we get a response back...
        .and_then(|res| {
            println!("Response: {}", res.status());
            println!("Headers: {:#?}", res.headers());

            // The body is a stream, and for_each returns a new Future
            // when the stream is finished, and calls the closure on
            // each chunk of the body...
            res.into_body().for_each(|chunk| {
                io::stdout().write_all(&chunk)
                    .map_err(|e| panic!("example expects stdout is open, error={}", e))
            })
        })
        // If all good, just tell the user...
        .map(|_| {
            println!("\n\nDone.");
        })
        // If there was an error, let the user know...
        .map_err(|err| {
            eprintln!("Error {}", err);
        })
}
```

Run as:
```
cargo run https://nghttp2.org/
```

**Comment by sfackler** [comment]
HTTP2 over TLS must be negotiated via ALPN according to the spec, so the server might be refusing to perform the handshake.

**Comment by avkonst** [comment]
The server does alpn negotiation according to the description. The other
server (based on jetty in java) also does alpn negotiation. I had many
clients in various languages successfully communicating with my server but
rust client does not.

**Comment by sfackler** [comment]
The client isn't using ALPN.

**Comment by avkonst** [comment]
@sfackler what should I change in the posted reproducer code in order to make it using ALPN?

**Comment by sfackler** [comment]
You'd have to switch to a TLS implementation that supports ALPN such as hyper-openssl, and configure it to be turned on:

```rust
extern crate openssl;
extern crate hyper;
extern crate hyper_openssl;

use hyper::client::connector::HttpConnector;
use hyper_openssl::HttpsConnector;
use openssl::ssl::{SslMethod, SslConnector};

let mut ssl = SslConnector::builder(SslMethod::tls()).unwrap();
ssl.set_alpn_protos(b"\x02h2").unwrap();
let http = HttpConnector::new(4);
let connector = HttpsConnector::with_connector(connector, ssl);
```

**Comment by seanmonstar** [comment]
(Just tossing this in here, while it's annoying to have configure manually, there is #1485 to discuss an API to allow enabling it more automatically.)

**Comment by avkonst** [comment]
Thanks, I will try this.

**Comment by seanmonstar** [comment]
Since this seems like it's not a bug in hyper, I'm going to close. There is #1485 to track adding ALPN support to the Client.

**Comment by avkonst** [comment]
Could you please clarify one moment? I see hyper-tls uses native-tls, which uses openssl on Linux. Is it expected that [the proposed change](https://github.com/hyperium/hyper/issues/1574#issuecomment-399266306) is already supported by native-tls by default?

**Comment by sfackler** [comment]
native-tls doesn't yet support ALPN, but I'm going to be working on adding it after cutting a new release.

**Comment by avkonst** [comment]
@sfackler, thank you! is there a ticket for native-tls to subscribe to? how long do you think it will take?

**Comment by sfackler** [comment]
https://github.com/sfackler/rust-native-tls/issues/49

Not sure - the implementation needs to land in schannel-rs and then we need to figure out the semantics of how it works in native-tls. Shouldn't be more than a week or two though.

**Comment by helinwang** [comment]
I wanted to use hyper with http2_only and using rustls. So I need to turn on ALPN for rustls. Haven't found a tutorial on this. I figured it out myself, thought this could help someone:

```rust
// imports, some may be not useful.
extern crate hyper;
extern crate hyper_rustls;
extern crate rustls;
extern crate webpki_roots;

use hyper::client::HttpConnector;
use hyper::header::HeaderValue;
use hyper::rt::{self, Future, Stream};
use hyper::{Body, Client, Method, Request};
use hyper_rustls::HttpsConnector;
use rustls::ClientConfig;
use std::io::{self, Write};

        let mut http = HttpConnector::new(2);
        http.enforce_http(false);
        let mut config = ClientConfig::new();
        config.set_protocols(&["h2".into()]);
        config
            .root_store
            .add_server_trust_anchors(&webpki_roots::TLS_SERVER_ROOTS);
        let https: HttpsConnector<HttpConnector> = (http, config).into();
        let client = Client::builder()
            .keep_alive(true)
            .keep_alive_timeout(None)
            .http2_only(true)
            .build::<_, hyper::Body>(https);
```
