### ISSUE TITLE
Creating a Destination

### ISSUE THREAD

**Issue by yashsriv** [hyperium/hyper#1576]
Hi I am trying to create a `Destination` externally for proxying. The code is something like this:

```
                return Box::new(self.https.connect(proxyURI).map(|(io, connected)| (Conn::Normal(io), connected)));
```

Basically, I am writing a wrapper connector around the base connector for proxying purposes. But, since proxyURI is specified by the user, it isn't a `Destination` and I have no way of creating one.

This is in reference to updating seanmonstar/reqwest

**Comment by seanmonstar** [comment]
With 0.12.2, it should be possible to mutate the Destination before passing it to the next one. There are setters.
