### ISSUE TITLE
"parsed HTTP message from remote is incomplete" when upgrading hyper

### ISSUE THREAD

**Issue by saarw** [hyperium/hyper#1591]
Upgraded a hyper client from 0.11.25 -> 0.12.5 but some requests are returning "parsed HTTP message from remote is incomplete"

Haven't been able to replicate in a small test case, but my client is running both long-poll requests and quick sends in the same hyper client and it's the long-polls that fail with this message.

**Comment by seanmonstar** [comment]
The point of the error is to suggest that parsing of the response started, but then the connection was closed before the response completed. (I say point because it's possible there's a bug in hyper :)).

It'd be useful to see what the responses look like that cause the error message.

**Comment by saarw** [comment]
Nevermind, turned out it was a problem with full nginx disk that caused it to fail some requests but not other. Sorry about the bother.
