### ISSUE TITLE
Add `reuse_address(true)` to client connections

### ISSUE THREAD

**Issue by EliSnow** [hyperium/hyper#1599]
I'm experimenting with using hyper to run load tests and ephemeral port exhaustion is a real problem. Can `reuse_address(true)` be added to the client connection code ([here](https://github.com/hyperium/hyper/blob/5b5e3090955c1b6c1e7a8cb97b43de8d099f5303/src/client/connect.rs#L413), and [here](https://github.com/hyperium/hyper/blob/5b5e3090955c1b6c1e7a8cb97b43de8d099f5303/src/client/connect.rs#L425), I believe)?

Would making the change here also apply to tls connections made using hyper_tls?

**Comment by seanmonstar** [comment]
I haven't thought this through at all, so some questions: would this cause problems for people who weren't expecting this? Could people assume that they normally would have different ports? If so, perhaps this would just be an option on `HttpConnector`?

**Comment by EliSnow** [comment]
I would be perfectly fine with just having the option of enabling it. Does that mean hyper_tls would have to add an option for `reuse_address` to apply to https connections?

**Comment by seanmonstar** [comment]
hyper-tls has a constructor that allows you configure a connector first, so it wouldn't need any changes.
