### ISSUE TITLE
Hyperium Glitch?

### ISSUE THREAD

**Issue by ShadowPenguinLX** [hyperium/hyper#1603]
I was playing on the hyperium client (B18 version) the title screen is empty. Last thing I remember doing was clicking "Change Menu Background" and typing in a url. Next thing I know the entire screen is empty. If anyone knows who to fix please tell. Thx
![hyperium bug](https://user-images.githubusercontent.com/41241564/42728006-aba6ab6c-8765-11e8-8506-95fe13ad904d.PNG)

**Comment by seanmonstar** [comment]
Hey there! It seems you're looking for something different, a game called Hyperium, whereas this project is about https://hyper.rs, an HTTP library in the Rust programming language. I don't know where to point you, though, as a quick google search suggests there's various games with the name.
