### ISSUE TITLE
Handling of large bodies in request

### ISSUE THREAD

**Issue by hntd187** [hyperium/hyper#1605]
Hi!

So if I have a very large JSON body in a request. I could just do `concat2()` for the body, but I'd like to take advantage of the streaming of the body and break the json up since I know it'll be delimited by newlines. There doesn't seem to be an obvious way to do this, but also if i were to operate on individual chunks I think I run the risk of incomplete JSON crossing the chunk threshold. So what is the proper way to accomplish this? My naive concat2 method works right now, but if I were say posting a body of several gbs that might become a memory problem, right?

**Comment by seanmonstar** [comment]
Hey there! You're right to be hesitant about simply concatenating the full body in memory. There isn't currently anything in hyper to do this sort of thing, but the building blocks are there.

You'd essentially want to poll for a chunk, and with each chunk, determine if you could parse a JSON object from it. If not, you'll want to just buffer that, and poll for a new one. Also may be worth looking at #1335 as well, that has some example code to do this.

**Comment by hntd187** [comment]
Thanks, this is exactly what I was looking for!
