### ISSUE TITLE
Questions on the commit "feat(lib): replace types with those from http crate"

### ISSUE THREAD

**Issue by Gowee** [hyperium/hyper#1611]
Hi!

The commit "[feat(lib): replace types with those from http crate](https://github.com/hyperium/hyper/commit/3cd48b45fb622fb9e69ba773e7f92b9d3e9ac018)" removes plenty of codes and instead uses types from *hyperium/http*. But at the same time, some features were removed permanently and not contained in *hyperium/http*.

For example:[*src/header/common/content_disposition.rs*](https://github.com/hyperium/hyper/commit/3cd48b45fb622fb9e69ba773e7f92b9d3e9ac018#diff-297685c7a5d16073303713fae0e925e5) contains `struct ContentDisposition` involving parsing and constructing `Content-Disposition` HTTP header. These codes are removed from *hyper* and the functionalities are not covered by *hyperium/http*.

Changes introduced by this commit are so many. I do not know the exact amount of features that are not present in either *hyper* or *http* now. But at a glance, I find a lot of other codes relating to parsing of other headers are also deleted. So it seems not to be the only feature getting lost after this commit.

Do you have any plans to bring these functionalities (typically, parsing those HTTP headers) back into *hyperium/hyper* or re-implement them in *hyperium/http*?

**Comment by lnicola** [comment]
See https://github.com/hyperium/hyper/issues/189.
