### ISSUE TITLE
Document the `runtime` feature

### ISSUE THREAD

**Issue by sanmai-NL** [hyperium/hyper#1613]
Only found this: https://github.com/hyperium/hyper/commit/d127201ef22b10ab1d84b3f2215863eb2d03bfcb. In general, all features should be documented esp. if they are mentioned in e.g. the changelog (i.e. not internal/temporary/experimental).

Question the docs would address:
1. What is the value of the Tokio runtime itself?
2. Pointers on how to use alternative runtimes?

**Comment by seanmonstar** [comment]
Good point! Where is a good place for this to appear? In the module documentation of `hyper::rt`?

**Comment by sanmai-NL** [comment]
Imagine someone new to `hyper`. First thing he or she will do is adding it as dependency. Then they’ll ask themselves what features to enable in `Cargo.toml`. So, the best place would be the README being the first encounter with docs. This short overview of features can contain a pointer perhaps to some elaboration in the API docs.

**Comment by danieleades** [comment]
I am using hyper (or reqwest) in a couple of projects now, and i'd like to experiment with other runtimes (such as https://github.com/rustasync/runtime). Hyper and reqwest appear to be implicitly dependent on the tokio runtime. Is there a away around this dependency?

**Comment by danieleades** [comment]
Ah thanks, that makes perfect sense

Found this a really interesting read-

https://users.rust-lang.org/t/poll-async-await-lets-talk-about-executors/31753

It's about trying to find a consistent way across the ecosystem to make Executor/Spawn generic. Zero consensus of course.

**Comment by lorislibralato** [comment]
We can close this because of 1.0 runtime future remove

**Comment by seanmonstar** [comment]
Good point!
