### ISSUE TITLE
Error on making client sync call

### ISSUE THREAD

**Issue by madmaxio** [hyperium/hyper#1615]
I'm trying to block client call and get data back, without runtime. Perhaps I'm doing something wrong, client panics with error, please check this repo https://github.com/madmaxio/hyper-cases - start the server, after start the client.

> panicked at 'called Result::unwrap() on an Err value: Error { kind: Execute, cause: None }', libcore\result.rs:945:5

**Comment by seanmonstar** [comment]
The problem turns out to have been using `tokio_current_thread`, just the executor, and not using a runtime. Using `tokio::runtime::current_thread` works correctly.

**Comment by liufuyang** [comment]
```
// rt::run(fut);
let mut runtime = Runtime::new().unwrap();

match runtime.block_on(fut) {
     Ok(s) => {
            println!("After wait: SMReslt: {:#?}", &s);
      }
      Err(_) => (),
};
```

**Comment by madmaxio** [comment]
I think https://tokio-rs.github.io/tokio/tokio/runtime/current_thread/fn.block_on_all.html from tokio master branch should work, have not tested though.
