### ISSUE TITLE
TE "trailers" header incorrectly stripped from HTTP/2 requests

### ISSUE THREAD

**Issue by okready** [hyperium/hyper#1642]
According to the HTTP/2 spec (https://http2.github.io/http2-spec/#rfc.section.8.1.2.2), connection-specific headers are not supposed to be in HTTP/2 messages, but a TE header is allowed for request messages as long as it only contains the value "trailers". `hyper` currently strips all connection-specific headers, including TE, regardless of whether the header is a TE "trailers" header belonging to an HTTP/2 request.

**Comment by seanmonstar** [comment]
Yep, looks like hyper is being too eager here.
