### ISSUE TITLE
What is the suggested way to shutdown a server with a signal on v0.12.8 ?

### ISSUE THREAD

**Issue by tamoyal** [hyperium/hyper#1645]
I am migrating from 0.11.x to 0.12.8 and noticed that `run_until` is now gone which allowed me to send a signal to shutdown the server like...

```
server.run_until(rx.then(|_| Ok(()))).unwrap()
```

I also noticed on master, this is made more convenient with the `with_graceful_shutdown` method.

However, on v0.12.8 it's not obvious how to do this. Any suggestions?

**Comment by seanmonstar** [comment]
If you want what existed in 0.11, you simply would "select" on your signal with the `Server` future, something like this:

```rust
let fut = server.select(rx.then(|_| Ok(())));
tokio::spawn(fut); // or tokio::run, or whatever
```

The new `with_graceful_shutdown` that will be released soon will ease this, but will also gracefully close the connections instead of abruptly canceling them.

**Comment by tamoyal** [comment]
When I do that, I get this error:
```
rt::run(server);
^^^^^^^ expected tuple, found ()
```

**Comment by seanmonstar** [comment]
That's probably from `Future::select`, which yields `(Item, NotFinishedFuture)`. You can just map that to `()`.

**Comment by tamoyal** [comment]
This is what I have going on now (let me know if you want a full example):
```
...
let new_service = move || {
  service_fn(...)
};

let server = Server::bind(&addr)
    .serve(new_service);

let f = server
  .map_err(|e| panic!("server error: {}", e))
  .select(shutdown_rx.then(|_| {
     println!("Got shutdown_rx");
    Ok(())
})).then(|_| Ok(()));
rt::run(f);
println!("Server shutdown");
```

I do get the "Got shutdown_rx" message but never the "Server shutdown" message so I still cannot invoke a server shutdown

**Comment by seanmonstar** [comment]
This is because `rt::run` (which is really [`tokio::run`](https://docs.rs/tokio/0.1.8/tokio/runtime/fn.run.html)) will wait until all futures have finished. If you specifically want to only run until that specific future is finished, you can use [`Runtime::block_on`](https://docs.rs/tokio/0.1.8/tokio/runtime/struct.Runtime.html#method.block_on).

**Comment by seanmonstar** [comment]
Related, v0.12.9 is now published, making `with_graceful_shutdown` also available.

I'm going to close this, as it doesn't seem like there's a bug in hyper.
