### ISSUE TITLE
Add Conditional Requests (IETF RFC 7232) support in the client

### ISSUE THREAD

**Issue by dwijnand** [hyperium/hyper#1647]
It would be lovely if the hyper client supported https://tools.ietf.org/html/rfc7232.

My downstream usage is in https://github.com/softprops/hubcaps/issues/104.

It looks like there's already a rust implementation in servo: https://github.com/servo/servo/blob/master/components/net/http_cache.rs, if that helps. That also seems to implement https://tools.ietf.org/html/rfc7234 (Caching).

**Comment by seanmonstar** [comment]
Supporting conditional requests is certainly useful, but I think it may be out of scope for hyper. It should be possible to do this entirely outside of hyper (as shown by Servo's implementation).

It might be cool to see if Servo would be interested in extracting it's cache implementation into a library.
