### ISSUE TITLE
Disabling the runtime feature breaks client creation in compile-time

### ISSUE THREAD

**Issue by gngeorgiev** [hyperium/hyper#1653]
Hi,

In my application, I need to tightly control the threads spawned, so I want to use my own runtime for futures.

Disabling the default features (which appears to only be the runtime) like this:

```toml
[dependencies.hyper]
version = "0.12"
default-features = false
```

Raises the following error at compile-time: 

```
error[E0599]: no function or associated item named `new` found for type `hyper::Client<_, _>` in the current scope
  --> src/main.rs:32:18
   |
32 |     let client = hyper::Client::new();
   |                  ^^^^^^^^^^^^^^^^^^ function or associated item not found in `hyper::Client<_, _>`
```

Cargo:

```
$ cargo 1.30.0-nightly (b917e3524 2018-09-09)
```

Am I missing something here?

**Comment by seanmonstar** [comment]
`Client::new()` is not available if the `runtime` feature is disabled, since it defaults to using an `HttpConnector`, which makes use of parts of the runtime.

Are you using a different runtime than tokio? Or you simply wish to customize the tokio runtime specifically? If the latter, you don't need to disable it in hyper; hyper doesn't *build* its own runtime. The `runtime` feature simply provides built in support to make use of a provided tokio runtime.

**Comment by seanmonstar** [comment]
Those 4 threads are part of the [`HttpConnector`](https://docs.rs/hyper/0.12.9/hyper/client/struct.HttpConnector.html), which it uses exclusively to perform blocking DNS lookups (so they don't block the runtime thread).

If you wanted everything to always use a single thread, you could try using a different `Connect` that does non-blocking DNS lookups, perhaps using something like https://github.com/bluejekyll/trust-dns

**Comment by gngeorgiev** [comment]
@seanmonstar Thank you for your replies they were very helpful.

Implementing `Connect` is definitely on the table but I will leave that optimization for further along. For the time being, I opted for creating an `HttpConnector` with a smaller pool.

```
let connector = hyper::client::HttpConnector::new(1);
let client: hyper::Client<hyper::client::HttpConnector, hyper::body::Body> =
        hyper::client::Builder::default().build(connector);
```

I will close this issue now, hopefully it will help someone in the future.
