### ISSUE TITLE
no `Authorization` in `header`

### ISSUE THREAD

**Issue by johnkarasev** [hyperium/hyper#1656]
I was trying to run the following code: 
<img width="933" alt="image" src="https://user-images.githubusercontent.com/37842273/45777003-721c8780-bc09-11e8-8cfa-5c16fbb29816.png">

But I got this error: 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/37842273/45777018-79dc2c00-bc09-11e8-8d51-079c01809512.png">

This was in doc but for some reason it does not work

**Comment by seanmonstar** [comment]
As the compiler error suggests, there is no `Authorization` type in `hyper::header` anymore. You can set the header directly, via `headers.insert("authorization", some_str.parse().unwrap())`.

Typed headers are being worked on in https://github.com/hyperium/headers.

**Comment by johnkarasev** [comment]
ok thanks

**Comment by johnkarasev** [comment]
is it in crates.io?
