### ISSUE TITLE
Server closure example

### ISSUE THREAD

**Issue by paperplanes53** [hyperium/hyper#1663]
I used the example in the for fn serve in the link below.
 
[hyper serve example](https://docs.rs/hyper/0.12.10/hyper/server/struct.Builder.html#method.serve)
The type of the `new_service` variable is `hyper::Server<_, [closure@src/installed.rs:105:35: 109:18]>`. However, isn't the type supposed to resolve to Server<_, hyper::Body>. 

Do you have any ideas on how to fix this or know if I am using Server incorrectly?

**Comment by seanmonstar** [comment]
Sorry, I don't quite understand, what problem are you running into?

> However, isn't the type supposed to resolve to Server<_, hyper::Body>.

No, the type reported is correct. It's supposed to a `Server<IncomingConnectionsImpl, NewServiceImpl>`.

**Comment by paperplanes53** [comment]
Okay, I see. Now, when I do `let server = Server::bind(&addr).serve(new_service);` I get `hyper::Server<hyper::server::conn::AddrIncoming, [closure@src/installed.rs:105:35: 109:18]>`.

I have a struct with a server field and have now set the type to `Option<Server<AddrIncoming, NewService>>`.

`NewService` is highlighted with the following errors:

- error[E0191]: the value of the associated type `ReqBody` (from the trait `hyper::service::NewService`) must be specified

- error[E0191]: the value of the associated type `Error` (from the trait `hyper::service::NewService`) must be specified
  
- error[E0191]: the value of the associated type `Service` (from the trait `hyper::service::NewService`) must be specified
  --> src/installed.rs:67:41

- error[E0191]: the value of the associated type `Future` (from the trait `hyper::service::NewService`) must be specified

- error[E0191]: the value of the associated type `InitError` (from the trait `hyper::service::NewService`) must be specified
 
Looking at the [new_service.rs code](https://docs.rs/hyper/0.12.10/src/hyper/service/new_service.rs.html#9-34) , I thought the implementation section set the types already.

**Comment by seanmonstar** [comment]
`NewService` is a trait, you can't declare a type that holds a generic with the exact trait. Any type could implement it, and they could be different sizes in memory. If you wish to be able to hold any type as well, you need to make your type generic, similar to how `hyper::Server` is.

**Comment by paperplanes53** [comment]
The error makes sense then, thank you.
