### ISSUE TITLE
Access hyper::Error types 

### ISSUE THREAD

**Issue by paperplanes53** [hyperium/hyper#1664]
I want to input a hyper::Error type to an enum but I can not use a specific kind directly. 

For example,  my goal is to do ` fn new() {
      ans: A::Error(hyper::Error::TooLarge)   
  }
` 
with ` pub enum A {
    Error(hyper::Error),
    Success,
    OtherField,
  }
`. 

 I get the error `associated item not found in hyper::Error` when I use hyper::Error::TooLarge since a lot of the hyper::Error code uses pub(crate).

**Comment by seanmonstar** [comment]
You cannot create a `hyper::Error` yourself, they happen *inside* hyper. If you have specific error conditions that can happen in your app, you should create your own error type that can describe them.
