### ISSUE TITLE
Single threaded Server

### ISSUE THREAD

**Issue by ubnt-intrepid** [hyperium/hyper#1667]
The current implementation of `hyper::server::Server` is based on the Tokio's default runtime based on work stealing threadpool. It is appropriate for most use cases, but the value of `NewService` must satisfy the bounds on thread safety (i.e. `Send + 'static`).
Today, Tokio provides the single threaded runtime. If there is another implementation of `Server` based on it, it is possible to allow user to write `NewService` without satisfying thread safety (using `Rc` or borrowing to external instance).
Do you have any plan to implement such `Server` at this time?

**Comment by seanmonstar** [comment]
I have seen multiple requests to relax the `Send` requirement in hyper, and in principle, I'm fine with it. 

The tricky part has been around dealing with the `Executor` that is used to spawn the tasks. To support both `tokio::spawn` and alternative executors, while not needing an explosion of generics, it's simply required to be `Executor<Box<Future + Send>>`. As of now, the tasks that are spawned are: a) for `hyper::Server`, the `hyper::server::conn::Connection` which will include the `Future` from a user's `Service`, and b) if the protocol is detected as HTTP2, then internal `H2Stream` futures are spawned for each request/response future, also based on the user's `Service`.
