### ISSUE TITLE
Switch from Travis and AppVeyor to GitHub Actions

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1673]
AppVeyor is quite slow, and the current script in hyper tests Windows nightly, which can mean Windows testing can be flaky. It'd be nice to move to Travis-CI's new Windows support, running the tests on the same matrix as AppVeyor, but probably sticking with just stable Rust.

**Comment by seanmonstar** [comment]
I'm noticing this more and more, since AppVeyor won't build any jobs in parallel, nor branches, so if a couple PRs appear, it can take a couple hours to get run (and even just a single PR will run 4 jobs at around ~6-7minutes each, for ~30mins total).

**Comment by seanmonstar** [comment]
Previous attempt: https://github.com/hyperium/hyper/pull/1690

**Comment by jonas-schievink** [comment]
Apparently [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/?nav=min) allows up to 10 parallel builds for open source projects, so that might be an alternative. It also supports Windows, macOS and Linux.
