### ISSUE TITLE
Add reverse proxy API

### ISSUE THREAD

**Issue by felipenoris** [hyperium/hyper#1677]
I suggest to incorporate reverse proxy functions to this project.

See https://github.com/brendanzab/hyper-reverse-proxy

**Comment by seanmonstar** [comment]
Would you mind expanding what you mean with your suggestion? hyper is an HTTP implementation, a reverse proxy is one tool someone may want that makes use of HTTP...

**Comment by felipenoris** [comment]
Yes, the idea is to have something similar to go's httputils. See https://golang.org/pkg/net/http/httputil/#ReverseProxy .

I understand that this might seem too high level for this library, in which case you can just reject this idea and close this issue.

**Comment by seanmonstar** [comment]
It does seem too high level, since there's so many design decisions to be made. For anyone wanting a starting point, there's a [reverse proxy example](https://github.com/hyperium/hyper/blob/master/examples/proxy.rs) in this repo.
