### ISSUE TITLE
Client returning Incomplete consistently when using a reqwest client w/rayon

### ISSUE THREAD

**Issue by mackeyja92** [hyperium/hyper#1679]
I am using rayon to map over an vec and posting that data to an API. I am using reqwest to handle the client and setting up my timeouts. If I reduce my threadpool down to 1 the issue goes away so I am thinking it is some sort of race condition between threads and some sort of shutdown that happens.

 Here is the error:
`RequestError(Inner { kind: Hyper(Error { kind: Incomplete, cause: None }), url: Some("http://localhost:5001/mypath/") })`

I can send over trace logging to an email, if that helps.

**Comment by seanmonstar** [comment]
The "incomplete" error means a request was written, but the server closed the connection before a response could be read.

This could also happen if the request was written on a kept alive socket that the server was just about to close...

**Comment by mackeyja92** [comment]
I can’t reproduce this with any other client nor am I able to reproduce it with hyper when I’m doing it with only a single thread on rayon. It seems the client is shutting down before some of the parallel requests are finished. 

The requests themselves can take awhile to process (30ish seconds). The keep alive on the server is 600 seconds.

**Comment by seanmonstar** [comment]
What does the reqwest code look like? If it can't be reproduced with just hyper, it may be something wrong in reqwest.
