### ISSUE TITLE
hyper 0.10.14 fails tests

### ISSUE THREAD

**Issue by cuviper** [hyperium/hyper#1682]
I got the following test results on hyper 0.10.14 (using rust 1.29.2):

```text
failures:

---- server::tests::test_check_continue_reject stdout ----
thread 'server::tests::test_check_continue_reject' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[72, 84, 84, 80, 47, 49, 46, 49, 32, 52, 49, 55, 32, 69, 120, 112, 101, 99, 116, 97, 116, 105, 111, 110, 32, 70, 97, 105, 108, 101, 100, 13, 10, 13, 10]`', src/server/mod.rs:494:9

---- server::tests::test_check_continue_default stdout ----
thread 'server::tests::test_check_continue_default' panicked at 'index 25 out of range for slice of length 0', libcore/slice/mod.rs:1932:5


failures:
    server::tests::test_check_continue_default
    server::tests::test_check_continue_reject

test result: FAILED. 274 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
```

One note is that I patched out the test `deny(warnings)`, otherwise you don't even get this far due to deprecated `AsciiExt`.  Your Travis build also failed on these deprecations on stable+beta+nightly.
https://travis-ci.org/hyperium/hyper/builds/445836611
(The 1.17 build failed on a `pub(crate)` in `unicode-normalization`.)

**Comment by seanmonstar** [comment]
Thanks for noticing! Seems the test was fragile, but I've gotten it back to the passing behavior. I'll also disable the warnings and minimum version in CI, since 0.10.x is no longer actively maintained.

**Comment by cuviper** [comment]
Looks good -- thanks for the quick fix!
