### ISSUE TITLE
How to use hyper server with custom TLS/TCP/service handling

### ISSUE THREAD

**Issue by alex** [hyperium/hyper#1689]
I apologize in advance, as I'm not sure the best way to describe this issue.

I'm using hyper's server, along with rustls. My service supports client certificates, and I need information about them in the server, so I had to write some pretty gnarly integration code: https://github.com/alex/ct-tools/blob/master/src/main.rs#L345-L438

This relied on `hyper::server::Http::bind_connection`, which has been removed in the latest version of `hyper`.

Is there a better way to connect hyper to my custom rustls server? As far as I can tell, there's no way to get the client certificate from a hyper request, so I still need the custom connector code.

**Comment by seanmonstar** [comment]
You can get similar functionality by using [`Http::serve_connection`](https://docs.rs/hyper/0.12.*/hyper/server/conn/struct.Http.html#method.serve_connection).

See #1650 for the general issue of accessing the socket when constructing a `Service`.

**Comment by alex** [comment]
Thanks!
