### ISSUE TITLE
Add an example of implementing a server service to the documentation

### ISSUE THREAD

**Issue by alex** [hyperium/hyper#1691]
Right now all the server examples just use a function. It'd be helpful if the docs showed an example of implementing a service, so you can put some state on your server.

**Comment by KenanSulayman** [comment]
I think this should be a top-priority.

In the wild you'll only find massively interweaved examples of hyper being used via trait, and frankly it's what stopped me from migrating to hyper 0.11 / 0.12 so far -- I'd very much appreciate a complete example (i.e. a server with a redis-backed store, ...) and if possible a guide on what to consider when migrating from 0.9, 0.10 to 0.12.

**Comment by akatechis** [comment]
I'm particularly interested in an example, where a `MakeService` is used to create multiple `Service`s with a shared resource. I spent some time spelunking in the docs, trying to figure this out, and still haven't been able to wrangle the types.

My use case is I'd like to construct a single instance of a struct representing my datastore, and share it will all the Services that are spawned in order to handle requests.

**Comment by ashthespy** [comment]
Also came looking for an example of implementing the `Service` trait and serving it with hyper 0.13. 
Most of the examples out there seem to all use the `service_fn` and `make_service_fn` helpers.. 
The closest examples I could find were over on [docs](https://docs.rs/hyper/0.13.4/hyper/service/trait.Service.html#server) but I don't completely get what the best way to go from `Service` -> `MakeService` should be. Currently I've based it off the [`tower_server`](https://github.com/hyperium/hyper/blob/master/examples/tower_server.rs) example, but wondering if there is a better way!

**Comment by LucioFranco** [comment]
This code hasn't been updated to the new version of tower but it should give you an idea https://github.com/tower-rs/examples/blob/master/src/http-server.rs#L36

I would love for someone to update it though!

**Comment by tkbrigham** [comment]
I think I managed to spin up something minimal that should serve this need. Putting together a PR now.

**Comment by tkbrigham** [comment]
@LucioFranco @seanmonstar opened a linked PR, and not sure what next steps are for getting it reviewed. I went through CONTRIBUTING.md, but let me know if I missed anything!

(thanks for the awesome crate)
