### ISSUE TITLE
Detailed analysis of http(s) requests

### ISSUE THREAD

**Issue by MartyIX** [hyperium/hyper#1693]
Hi guys,

Is this crate sufficient when one wants to implement a program that makes HTTP(s) requests and want to track how long SSL handshake take and other statistics? 

Generally I would like to know "everything possible" about the HTTP request/response. Whether an error occurred, whether there was some validation error, etc.

Or is it better to write this kind of program in C?

Best regards,
Martin

**Comment by seanmonstar** [comment]
> want to track how long SSL handshake take and other statistics?

The `Client` can take any custom `Connect`, so you can instrument a connect to record statistics around DNS, TCP handshake, SSL handshake, etc.

> Whether an error occurred, whether there was some validation error, etc.

hyper will give you an `Error` if the request fails in any way. I can't say whether it will fit your needs perfectly, but with the vague description, it sounds like it will!

**Comment by MartyIX** [comment]
Thank you very much :-)
