### ISSUE TITLE
Default `sleep_on_errors` to `false`

### ISSUE THREAD

**Issue by sanmai-NL** [hyperium/hyper#1712]
The behavior in https://docs.rs/hyper/0.12.14/hyper/server/conn/struct.AddrIncoming.html#method.set_sleep_on_errors (PR https://github.com/hyperium/hyper/pull/1450) is speculative. It shouldn’t default to `true`, since it masks error conditions and does not appreciably reduce the risk of service unavailability, as intended (#1358). 

I suggest to default this parameter to `false` or, better yet, remove this code.

**Comment by sanmai-NL** [comment]
Although the implementer notes an error log entry would be emitted, he/she does not indicate how to control and view this error log. E.g., what env. var. should be set and for which path?

**Comment by seanmonstar** [comment]
Sleeping on TCP accept errors is actually common in other libraries, like nginx, nodejs, Netty... 

Was it masking an actual problem in your server?

**Comment by seanmonstar** [comment]
- nginx: https://github.com/nginx/nginx/blob/1028d71/src/event/ngx_event_accept.c#L99-L127
- Netty: https://github.com/netty/netty/commit/dcf78961724abf97fea9e768cca02ba65146b324
