### ISSUE TITLE
Parse content-length from header

### ISSUE THREAD

**Issue by leohahn** [hyperium/hyper#1714]
I am learning hyper (using `hyper = "0.12"`) and trying to get the `Content-Length` header from a response. The only way I figured out is to convert the `HeaderValue` into a string and then parse the number. Is there a more straight forward way of doing this? I did not find on the examples as well. Here is how I am doing it:

```rust
 let content_length_val: &header::HeaderValue = res.headers().get(header::CONTENT_LENGTH).unwrap();
 let content_length_str = content_length_val.to_str().unwrap();
 let content_length: u64 = content_length_str.parse::<u64>().unwrap();
```

And realistically in each step I would have to handle the error, making it really verbose.

**Comment by seanmonstar** [comment]
You could try a more "functional" style of getting it:

```rust
// type is Option<u64>
let content_length = res
    .headers()
    .get(CONTENT_LENGTH)
    .and_then(|val| val.to_str().ok())
    .and_then(|s| s.parse::<u64>().ok());
```

Work has been happening on a new "typed headers" repo, https://github.com/hyperium/headers. Once the final pieces have stabilized, it would have code like this:

```rust
// type is Option<ContentLength(u64)>
let content_length = res.headers().typed_get::<ContentLength>();
```

(As this is more a usage question and not a bug in hyper, I'm going to close :D)

**Comment by leohahn** [comment]
Thank you very much for the answer!
