### ISSUE TITLE
using Stream on Body not possible

### ISSUE THREAD

**Issue by nifker** [hyperium/hyper#1715]
I am unable to properly use the Stream implementation for Body because it gets consumed here.
https://play.integer32.com/?version=stable&mode=debug&edition=2015&gist=0d0100ca20727177e0068fafaf3691f6
How should this be done?
Or how can I read chunk-wise from the body?

**Comment by sfackler** [comment]
You can use `response.into_body()` rather than `response.body()` to get the body by-value rather just a reference.

**Comment by nifker** [comment]
Fixed using hyper::rt::spawn().
