### ISSUE TITLE
Connection leak

### ISSUE THREAD

**Issue by luben** [hyperium/hyper#1717]
In certain cases I see connection leaks. I have a simple reproduction in: https://github.com/luben/repro-hyper

The behavior I observe:

* with small requests everything works OK
* with bigger request (e.g. 1 MiB payload) there is one connection per request leaked between the worker and the broker.
* if I switch the worker/broker communication to HTTP/2 by uncommenting https://github.com/luben/repro-hyper/blob/master/src/bin/worker.rs#L16 - there is no more leaks.

**Comment by seanmonstar** [comment]
Thanks, I'll try out the repro locally.

Do you have any more details that would help me while I look? Is it consistently leaking the connection immediately, or only occassionally?

**Comment by luben** [comment]
It's consistently leaking.

**Comment by luben** [comment]
I have just added a negative example with src/bin/worker-non-stream.rs - if we .concat2() the body (i.e. not stream it back) there is no leak.

**Comment by seanmonstar** [comment]
Is the leak in broker, or in worker?

**Comment by luben** [comment]
The connection between both in not closed from both sides.

**Comment by seanmonstar** [comment]
I see, it seems the dispatcher after having written the headers for some reason doesn't continue to do work, but stalls. I'll look more into it.

**Comment by seanmonstar** [comment]
I've published v0.12.16 with a fix for this, thanks for reporting and for the reproducible instructions!
