### ISSUE TITLE
Make the Referer header fully conforming

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#172]
See https://tools.ietf.org/html/rfc7231#section-5.5.2
----------------------------------------------
EDIT(reem): Summarizing below, the current implementation doesn't allow relative-only urls.

**Comment by pyfisch** [comment]
Referer header is already part of hyper: https://github.com/hyperium/hyper/blob/5d93a3bd9132f1cee405b553e5a0893693b3d78b/src/header/common/referer.rs

So close this issue and open eventually a new one for the relative URLs.

**Comment by seanmonstar** [comment]
Closing for the same reason as #243
