### ISSUE TITLE
Make the MakeServiceRef trait public

### ISSUE THREAD

**Issue by vorner** [hyperium/hyper#1727]
Hello

Would it be possible to make the `MakeServiceRef` trait public? It currently is the trait bound of [Builder::serve](https://docs.rs/hyper/0.12.16/hyper/server/struct.Builder.html#method.serve). If I want to decorate that/forward something into that method, I have quite hard time writing my trait bounds in a way it satisfies it. I ended up with this eventually, but it is a huge unreadable beast:

https://github.com/vorner/spirit/blob/8c00a34bfea3fa49f0ef27d734e2ca2439d0f68b/spirit-hyper/src/lib.rs#L133

Being able to reference the trait instead of copying the bounds from its blanket implementation would reduce it somewhat I think.

**Comment by seanmonstar** [comment]
Yea, I that is a monster!

I had originally hoped that such a trait wouldn't be necessary, but without it, I had similarly gross bounds in hyper. The "trait alias" made it cleaner, and should still work for people *implementing* `MakeService`. I suppose the trait could be moved over to `hyper::service`, and exported...
