### ISSUE TITLE
An example or a way to shutdown a server

### ISSUE THREAD

**Issue by JeffLabonte** [hyperium/hyper#1729]
## Description

It would be useful to be able to close a socket! 

### Issue related to missing feature

On Linux, I wouldn't be able to run my tests properly, the socket would hang open and I would be unable to close it.

**I have realised that running the server would block my thread, so I run the server on a different thread**

**Comment by seanmonstar** [comment]
There is [graceful shutdown](https://docs.rs/hyper/0.12.*/hyper/server/struct.Server.html#method.with_graceful_shutdown) supported on the `Server`.
