### ISSUE TITLE
Body is not Sync

### ISSUE THREAD

**Issue by TheNeikos** [hyperium/hyper#1730]
I'm currently trying to use `Body` and want to extract the Bytes from it.

However, `Body` currently does not implement `Sync`. I understand that this would be a breaking change, however, is this something that could be added, or am I on the wrong path? 

In case you've encountered this before, do you know how this could be fixed currently?

I've reproduced it in a play: 
https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=3b1c8afbf124923366b460de3ee58043

**Comment by seanmonstar** [comment]
Do you really require the `+ Sync` bounds on the return `impl Future`? If you just remove that, it would work.

**Comment by TheNeikos** [comment]
Sorry for the delay!

So, the reason why I needed this to be Sync, is because the Error type of MakeService has a Sync bound, and I had in my error chain `then` which caused the Body to be entangled in all of that.

It took some time but I managed to untangle the futures to find this. Hence my question if you had made similar experiences before with Body being required Sync.

————

In general I’d like to thank you for answering my questions and I’m sorry if they seem a bit odd at times, futures are still quite new and hyper a large library.
