### ISSUE TITLE
Unable to run hype::rt::spawn

### ISSUE THREAD

**Issue by JeffLabonte** [hyperium/hyper#1731]
## Description

I am trying to use the `hyper::rt::spawn` function to run my server, but it isn't working.

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', libcore/result.rs:1009:5
Error an error occurred trying to connect: Connection refused (os error 111)
```

If I run hyper::rt::run(server), it works like a charm!

**Comment by seanmonstar** [comment]
`spawn` is to be used from inside running futures. Take a look at this [Tokio guide](https://tokio.rs/docs/getting-started/runtime/).
