### ISSUE TITLE
Broken Link in Documentation 

### ISSUE THREAD

**Issue by jgould22** [hyperium/hyper#1732]
Just a heads up it seems the link to **Tokio’s guide on Futures.** Under the **Runtime** section of https://hyper.rs/guides/client/basic is broken. It sends you to https://hyper.rs/guides/client/basic/Tokio%20Futures which is throwing a github pages 404

edit: actually it looks like this should belong over at https://github.com/hyperium/hyperium.github.io

**Comment by seanmonstar** [comment]
Thanks for reporting this! I've pushed a fix for the link.
