### ISSUE TITLE
how can I append response status error handler when execute get request

### ISSUE THREAD

**Issue by dimmy82** [hyperium/hyper#1738]
I want to append response status error handler (like if the status is not 200, skip parsing body to json, and return the error directly)

I referenced this example [client_json.rs](https://github.com/hyperium/hyper/blob/master/examples/client_json.rs)

```!rust
    client
        // Fetch the url...
        .get(url)
        // And then, if we get a response back...
        .and_then(|res| {
            // asynchronously concatenate chunks of the body
            res.into_body().concat2()
        })
        .from_err::<FetchError>()
        // use the body after concatenation
        .and_then(|body| {
            // try to parse as json with serde_json
            let users = serde_json::from_slice(&body)?;
            Ok(users)
        })
        .from_err()
```
where can I append the error handler

**Comment by davidbarsky** [comment]
I want to ask a clarifying question—why do you want to skip the body parsing? In most of the APIs I've interacted with, non-200 status codes often contain useful errors, and I'd opt for _not_ throwing away potentially useful errors.

**Comment by seanmonstar** [comment]
You'll need to make use of [`futures::future::Either`](https://docs.rs/futures/0.1.*/futures/future/enum.Either.html), since the `and_then(|res|` would *either* return an error immediately, or return the concat future.

For example:

```rust
use futures::future;

client
    // Fetch the url...
    .get(url)
    .from_err::<FetchError>()
    // And then, if we get a response back...
    .and_then(|res| {
        // Can check ranges with `is_*` methods on `StatusCode`
        // Or for a specific status, `res.status() == StatusCode::OK`
        if !res.status().is_success() {
            future::Either::A(future::err(FetchError::Status(res.status()))
        } else {
            // asynchronously concatenate chunks of the body
            future::Either::B(res.into_body().concat2().from_err())
        }
    })

    // use the body after concatenation
    .and_then(|body| {
        // try to parse as json with serde_json
        let users = serde_json::from_slice(&body)?;
        Ok(users)
    })
    .from_err()
```

----

As this seems to be a usage question and not a bug in hyper, I'm going to close :)

**Comment by nerdrew** [comment]
I spent a bit of time trying to figure this out recently. Might be nice to add this to an example.
