### ISSUE TITLE
custom callback after a response has been sent

### ISSUE THREAD

**Issue by kahing** [hyperium/hyper#1744]
one of the things I want to do is after a response is returned (the entire body is sent to the eyeball), spawn a new future to run some other code. The use case here is request/response logging without blocking/delaying the response.

Currently my `Service` returns a `Future<Response>` and hyper consumes that response entirely, and internally de-constructs it into parts when it's sent out. One way to approach this is to extend the `Service` trait to add another function to be called after the response is done, and within hyper the response is re-assembled from parts (obviously the body won't be available anymore, so maybe we will just get `response::Parts`. That's sufficient for my needs as long as I can have some way to record the number of outgoing bytes, which I can do by providing my own `Payload`).

Thoughts?

**Comment by seanmonstar** [comment]
We don't copy the values into the `Payload` either. We record request and response info immediately, and basically store a key to those metrics in the payload, and then insert bytes and latency at drop.

**Comment by kahing** [comment]
that's an interesting strategy but unfortunately doesn't fit into our logging scheme.
