### ISSUE TITLE
No means to flag proxy in 0.12

### ISSUE THREAD

**Issue by frenchtoastbeer** [hyperium/hyper#1746]
I can see that src/client/connect/mod.rs's `Connected` contains `is_proxied`, and there's a `.proxy()` setter for it, but I don't believe that can be accessed from outside the library.  Nowhere within hyper do I see a .proxy(true) or an `is_proxied: true`, so am I correct in assuming this can never be set?

I believe this is necessary for correct behavior of non-secure, plaintext proxy requests, I'm getting around this issue by changing the proxy to support invisible proxy.

**Comment by seanmonstar** [comment]
A `Connect` implementation can do so by returning a `Connected::new().proxy(true)`.

BTW, if you're looking for an HTTP library that easily can use proxies, consider [reqwest](https://crates.io/crates/reqwest).

**Comment by frenchtoastbeer** [comment]
OK thanks.  I was avoiding reqwest as it didn't have async when I first looked, but now that I'm looking again - it appears it might?

**Comment by seanmonstar** [comment]
Yep, it has an [async interface](https://docs.rs/reqwest/0.9.*/reqwest/async/index.html)!
