### ISSUE TITLE
set maximum header size client will accept

### ISSUE THREAD

**Issue by kahing** [hyperium/hyper#1748]
all headers are effectively stored in memory (as oppose to body which is streamed) and that's no way to cap how much memory is used. In my case I need to make many concurrent requests to servers I don't control and want to cap the amount of memory used by each request.

**Comment by seanmonstar** [comment]
It'd probably be useful if there were more knobs to configure here, but I can at least explain what limits currently exist:

- There is a maximum number of headers set at [100](https://github.com/hyperium/hyper/blob/6bce753f32b35865c22b4a3d3601c87d8fb5d55a/src/proto/h1/role.rs#L14). This doesn't affect how long each header can be.
- There's a default max read buffer size set to [~400KB](https://github.com/hyperium/hyper/blob/6bce753f32b35865c22b4a3d3601c87d8fb5d55a/src/proto/h1/io.rs#L23). If the headers haven't finished by that limit, the response will be canceled.
- There's an option to change the max read buffer size on the Server side, but not the Client. Likely just an oversight.

**Comment by kahing** [comment]
a client side configurable max read buffer size sounds exactly what I need

**Comment by almielczarek** [comment]
I'd like to work on this.
