### ISSUE TITLE
Error: Upgrade expected but low level API in use

### ISSUE THREAD

**Issue by ddosoff** [hyperium/hyper#1752]
I tried to implement current thread TLS websocket server based on example code:

    ...
    let tls_cx = tokio_tls::TlsAcceptor::from(tls_cx);

    let new_service = || {
        service_fn_ok(|req: Request<Body>| {
            let mut res = Response::new(Body::empty());

            // Send a 400 to any request that doesn't have
            // an `Upgrade` header.
            if !req.headers().contains_key(UPGRADE) {
                *res.status_mut() = StatusCode::BAD_REQUEST;
                return res;
            }

            let on_upgrade = req
                .into_body()
                .on_upgrade()
                .map_err(|err| eprintln!("upgrade error: {}", err))
                .and_then(|upgraded| {
                    // We have an upgraded connection that we can read and
                    // write on directly.
                    //
                    // Since we completely control this example, we know exactly
                    // how many bytes the client will write, so just read exact...
                    tokio::io::read_exact(upgraded, vec![0; 7])
                        .and_then(|(upgraded, vec)| {
                            println!("server[foobar] recv: {:?}", &vec);

                            // And now write back the server 'foobar' protocol's
                            // response...
                            tokio::io::write_all(upgraded, b"bar=foo")
                        })
                        .map(|_| println!("server[foobar] sent"))
                        .map_err(|e| eprintln!("server foobar io error: {}", e))
                });

            current_thread::spawn(on_upgrade);

            // Now return a 101 Response saying we agree to the upgrade to some
            // made-up 'foobar' protocol.
            *res.status_mut() = StatusCode::SWITCHING_PROTOCOLS;
            res.headers_mut()
                .insert(UPGRADE, HeaderValue::from_static("foobar"));

            return res;
        })
    };

    let addr = "127.0.0.1:12345".parse().unwrap();
    let srv = TcpListener::bind(&addr).expect("Error binding local port");

    // Use lower lever hyper API to be able to intercept client connection
    let http_proto = Http::new();
    let http_server = http_proto
        .serve_incoming(
            srv.incoming().and_then(move |socket| {
                tls_cx
                    .accept(socket)
                    .map_err(|e| io::Error::new(io::ErrorKind::Other, e))
            }),
            new_service,
        )
        .then(|res| match res {
            Ok(conn) => Ok::<_, io::Error>(Some(conn)),
            Err(e) => {
                eprintln!("[1] Error: {}", e);
                Ok(None)
            }
        })
        .for_each(|conn_opt| {
            if let Some(conn) = conn_opt {
                current_thread::spawn(
                    conn.and_then(|c| c.map_err(|e| panic!("[2] Hyper error {}", e)))
                        .map_err(|e| eprintln!("[3] Connection error {}", e)),
                );
            }

            Ok(())
        });

    println!("Listening on {}", addr);

    current_thread::block_on_all(http_server).expect("http server finished with error");

And I got error when on_upgrade future executed: upgrade expected but low level API in use.

How to use high level api to create TLS server?

**Comment by ddosoff** [comment]
Thanks!

**Comment by ddosoff** [comment]
If you googled this thread, I added boilerplate code: https://github.com/ddosoff/hyper-boilerplate

**Comment by mjibson** [comment]
I'm running into this issue too, but am not able to use the builder pattern like above. Our tcp connection needs to be handled by something else, and sometimes we hand it off to hyper to process web stuff. Is there any more guidance about how to fix this in that case? What about connection is it that would prevent hyper from upgrading it?

**Comment by alecmocatta** [comment]
@mjibson Perhaps [`Connection::with_upgrades`](https://docs.rs/hyper/0.13.9/hyper/server/conn/struct.Connection.html#method.with_upgrades) might work in that case?

**Comment by seanmonstar** [comment]
If using `Http`:

```rust
let conn = http.serve_connection(socket, svc).with_upgrades();
```

**Comment by mjibson** [comment]
Yes! That did it! Thanks so much.
