### ISSUE TITLE
"Can't assign requested address"

### ISSUE THREAD

**Issue by kud1ing** [hyperium/hyper#1757]
I am using reqwest to access a local server. The client aborts with

    Error: Error { kind: Hyper(Error { kind: Connect, cause: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" } }), url: Some("http://127.0.0.1:4567/fooBar") }

* Thousands of URLs are queried. This error happens at a random one.
* The abort is less likely when compiled without `--release`.
* The offending URL can be accessed successfully from a web browser everytime.

There seems to be a timing problem somewhere.
Any idea? This is hyper 0.12.23

**Comment by sfackler** [comment]
Is another process already using port 4567?

**Comment by kud1ing** [comment]
Yes, on the client.

**Comment by kud1ing** [comment]
I've noticed this only happens when compiled with `--release`.

**Comment by kud1ing** [comment]
I wonder, since i query approx. 30.000 URLs and this seems to be timing related (it's more likely with `--release`): is it possible that i hit an OS limitation? E.g. connections are not closed fast enough?

**Comment by kud1ing** [comment]
If hyper is not holding on to anything longer than necessary, i tend to close this.

**Comment by karasjoh000** [comment]
On Linux, there is a command that could be called for OS to not hold the port when it is released. 

```c
  // allow reuse of socket without waiting 3 min before using again.
  if ( setsockopt( listenfd, SOL_SOCKET, SO_REUSEADDR, &on, sizeof( on ) ) < 0 )
    return -1;
  if ( bind( listenfd, /*assigns a name to an unnamed socket*/
             ( struct sockaddr * ) servAddr, sizeof( *servAddr ) ) < 0 ) {
    return -1;
  }

```

**Comment by binarynightowl** [comment]
Can we get this issue reopened by chance? 

I am having the same issue where the OS is holding the ports too long since it is not setting the SO_REUSEADDR option. 

Is there a way I can do this with hyperium that I am not seeing?

**Comment by seanmonstar** [comment]
hyper does not create the listener, the user does. You can configure it before accepting connections.

If you have further difficulties, try asking in Discord or in a new discussion. I'm locking this one since it's so old, not keep pinging others.
