### ISSUE TITLE
How to test a Hyper service?

### ISSUE THREAD

**Issue by theronic** [hyperium/hyper#1760]
What kind of test harness do I need to test against `call` of my service, e.g. a POST request? I'm relatively new to Rust and having a hard time testing a Hyper service. I tried to call `let response = service.call(req);` and got an error about, "must run in tokio runtime."

In Clojure I'm able to write request handlers as plain functions that take a request as a hash-map (e.g. `{:method :post :uri "/upload" :body ...}`) and return a response map (e.g. `{:status 201 :body "Uploaded"}`). I would like to be able to have a similar convenience using Hyper in Rust. Thanks!

**Comment by davidbarsky** [comment]
Short answer: I'd suggest using Tokio's [`block_on`](https://tokio-rs.github.io/tokio/tokio/runtime/struct.Runtime.html#method.block_on) method. I haven't tested this code, but it should look something like this:

```rust
#[test]
fn post_endpoint() {
  use tokio::runtime::Runtime;
  // Create the runtime
  let mut rt = Runtime::new().unwrap();
  // `resp` assumed to be defined elsewhere.
  let resp = rt.block_on(resp);
}
```
Long answer—every future created by Hyper must be run in the context of Tokio's event loop. Unlike, say, Node, there isn't a default/global event loop in Rust, so you have to create instances/handles to Tokio yourself.

(If you can send a PR that uses this to test endpoints, that'd be greatly appreciated!)

**Comment by seanmonstar** [comment]
As you've noticed, you can largely just test your `Service` without needing to start up a full server. However, depending on what that service is doing, you may need a runtime active. Like if you service spawns sub tasks/futures (like the hyper Client does), or using `tokio-fs`, which needs the threadpool available.

But in other examples, you can just call it. The Hello World example in hyper can just be called, as you described.
