### ISSUE TITLE
Enhance `Connect` trait.

### ISSUE THREAD

**Issue by quininer** [hyperium/hyper#1765]
Sometimes we want to use different connection strategies when send different requests.

For example, I want to use [0-RTT](https://github.com/quininer/tokio-rustls/pull/28) for some unimportant requests, but I don't want it to affect security of other requests.

Can we allow `Request` to pass an `Extra` to the `Connector`?

**Comment by seanmonstar** [comment]
Hm, maybe!

Since the `Connect` trait is related and/or may be superseded by a similar trait in tower, cc @carllerche @davidbarsky @LucioFranco.

**Comment by LucioFranco** [comment]
@quininer in tower we have been working on this trait right here https://github.com/tower-rs/tower/blob/master/tower-util/src/make_connection.rs#L21 would this work for your use case? It allows you to use your own generic parameter for the `connect` function.

**Comment by carllerche** [comment]
+1 on `MakeConnection`.

**Comment by quininer** [comment]
@LucioFranco Ah, this looks like what I want!

**Comment by quininer** [comment]
After reading it, I found that `tower-hyper` will actually reimplement a `Client`. It currently lacks many of the capabilities that `hyper` should have, such as h2 and connection pool.

@LucioFranco Will `tower-hyper` re-implement these? Still possible to reuse `hyper`?

**Comment by carllerche** [comment]
AFAIK, tower-hyper is an experiment. At some point, hyper proper will support tower types & traits.

**Comment by LucioFranco** [comment]
@quininer so `tower-hyper`'s goals are to just provide a sort of compat layer between hypers low level components and the middleware of `tower`. `tower-hyper` itself only exposes an interface for `MakeService` and then the `Service` generated from that. If you combine, a lot of the middleware already in tower you will get the connection pool, load balancing (between connections), retries, reconnecting the transport etc. hyper already includes h2 so you just need to setup the connection builder to force http2.

**Comment by quininer** [comment]
@carllerche I am looking forward!

@LucioFranco This sounds reasonable. but the `tower-hyper` `Connector` dropped `Connected`, which made `hyper` unable to use h2 via alpn.

**Comment by LucioFranco** [comment]
@LucioFranco Right, I havent gotten far enough to try http2 yet, that is my next goal for it. I still need to get that part figured out 😄 .

**Comment by LucioFranco** [comment]
@quininer I did some playing around, so without the need to upgrade etc http2 works with tower-hyper, just need to setup the correct request versions etc. I believe the ALPN negotiation can be done inside the `make_connection` future that returns a `AsyncReady + AsyncWrite` which means that the transport provided by `MakeConnection` is http2 ready. I'm not too versed, _yet_, with http2 so Im not totally sure if that is the right approach. But it does return a future from the trait allowing you to do more connection based io, like TLS, DNS, etc. If you are wanting to look more into `tower-hyper` feel free to create an issue in that repo or come talk to us on the tower gitter.

**Comment by quininer** [comment]
@LucioFranco It's interesting! I will try to use tower.
