### ISSUE TITLE
Migration to Rust 2018

### ISSUE THREAD

**Issue by Murakami-Int** [hyperium/hyper#1777]
I think this can be done before `std::future` stabilized.
Currently, hyper doesn't follow some Rust 2018 manner;

* module rules (include `extern crate`)
* hidden lifetime parameter
* bare trait

**Comment by seanmonstar** [comment]
hyper has tried when possible to link new compiler requirements with breaking changes. While we can sometimes use config flags to only enable things on newer version, I don't think there's a way to do that here, since this also requires putting `edition = "2018"` in the `Cargo.toml`...

**Comment by vorot93** [comment]
@seanmonstar hyper does not really have to support Rust pre-1.31 since futures 1.0 have been stabilized and will trigger async ecosystem migration in July anyway.

**Comment by seanmonstar** [comment]
I've placed this in the 0.13 milestone.
