### ISSUE TITLE
Issue with graceful shutdown from custom future

### ISSUE THREAD

**Issue by leorik** [hyperium/hyper#1785]
Hello fellow fungi people!

First off, I'm not quite sure this is the right place for the issue, since it's not a direct bug report or feature request for Hyper, but rather a question about some strange behavior I found, but I haven't found dedicated "help wanted" forum specific to Hyper. And to be honest I'm not particularly well versed in Futures/Hyper/Tokio, so feel free to close this issue and I'd like to apologize in advance if I missed my mark.

**TL; DR:** It looks like custom futures for Hyper service graceful shutdown doesn't get polled as frequent as `futures::sync` channels. Yeah, sounds ridiculus.

Long story: the problem I trying to solve here is fairly simple - I need to signal to halt Hyper server from external (relative to Tokio loop) source.
In my case I'm running Windows service that need to be shutdown by [SERVICE_CONTROL_STOP](https://docs.microsoft.com/en-us/windows/desktop/api/winsvc/nf-winsvc-controlservice) signal, if it matters.

So it looks like `Server::with_graceful_shutdown` is just what I need, and, indeed, it works perfectly if I'm running it with `futures::sync::oneshot::channel()` (as in docs for `Server::with_graceful_shutdown` function).

If we run this:
```rust
const TEXT: &str = "Hello, World!";
const SLEEP_TIMER_SECS: u64 = 30;

fn main() {
    let addr = ([127, 0, 0, 1], 9000).into();

    let new_svc = || service_fn_ok(|_req| Response::new(Body::from(TEXT)));

    let (tx, rx) = oneshot::channel();

    let server = Server::bind(&addr)
        .serve(new_svc)
        .with_graceful_shutdown(rx)
        .map_err(|e| eprintln!("server error: {}", e));

    // We emulating external signal source with designated thread here
    thread::spawn(move || {
        thread::sleep(Duration::new(SLEEP_TIMER_SECS, 0));

        tx.send(());
    });

    hyper::rt::run(server);
}
```

and issue at least one request[1] to created service, server get stopped fairly quickly, within 15s from shutdown signaling.

But, there is one problem: [windows-service](https://crates.io/crates/windows-service) crate I'm using demands `Fn` callback for service event handlers (since it goes out in native code) and `futures::sync::oneshot::Sender::send` consumes `Sender` itself, making any function that uses it `FnOnce`. So `futures::sync::oneshot` is not an option here.

To circumvent this I created "erzats" oneshot future:
```rust
struct ShutdownSignaler {
    state: Arc<Mutex<bool>>,
}

impl ShutdownSignaler {
    fn send(&self, _: ()) { // to match API of oneshot::Sender::send()
        match self.state.lock() {
            Ok(mut is_signaled) => {
                if *is_signaled == false {
                    *is_signaled = true;
                }
            }
            Err(_) => unreachable!(),
        }
    }
}

struct ShutdownReceiver {
    state: Arc<Mutex<bool>>,
}

impl Future for ShutdownReceiver {
    type Item = ();
    type Error = ();

    fn poll(&mut self) -> Result<Async<Self::Item>, Self::Error> {
        self.state
            .try_lock()
            .map(|is_signaled| {
                if *is_signaled == true {
                    return Async::Ready(());
                }

                return Async::NotReady;
            })
            .map_err(|_| ())
    }
}

fn custom_channel() -> (ShutdownSignaler, ShutdownReceiver) {
    let channel_state = Arc::new(Mutex::new(false));

    let tx = ShutdownSignaler {
        state: Arc::clone(&channel_state),
    };
    let rx = ShutdownReceiver {
        state: channel_state,
    };

    (tx, rx)
}
```

that get called in similar to `futures::sync::oneshot` fashion:
```rust
const TEXT: &str = "Hello, World!";
const SLEEP_TIMER_SECS: u64 = 30;

fn main() {
    let addr = ([127, 0, 0, 1], 9000).into();

    let new_svc = || service_fn_ok(|_req| Response::new(Body::from(TEXT)));

    let (tx, rx) = custom_channel(); // <- creating custom "channel"

    let server = Server::bind(&addr)
        .serve(new_svc)
        .with_graceful_shutdown(rx)
        .map_err(|e| eprintln!("server error: {}", e));

    // We emulating external signal source with designated thread here
    thread::spawn(move || {
        thread::sleep(Duration::new(SLEEP_TIMER_SECS, 0));

        tx.send(());
    });

    hyper::rt::run(server);
}
```

And here comes the trouble: after issuing single request[1], server will never stop by himself. Instead, user must wait ~15 minutes(!) after we send shutdown signal and than issue another request to server, and only then our custom future get polled and server will halt.

That 15 minute delay and manual action requirement (one last request) is kinda unacceptable in my use case (it breaks CD for starter), and, more importantly, it baffles me: How come? What am I doing wrong here?
I was pretty quick to put blame on some kind of `Mutex` deadlock here, but no: according to debugger, `Mutex` works fine and its the future that getting polled after that horrific delay.
Likewise, if we debug `futures::sync::oneshot` example it will become evident that `Receiver` got polled almost immediately. Reading through `futures::sync::oneshot::Inner::recv` haven't highlighted any red flags in my code but it's clear that my understanding of futures is not sufficient for the task.

I'm stuck with this, so it's less of "how do I fix it?" and more like "what am I getting wrong here?" question. Will appreciate any help, and sorry for the long post.

My OS is Windows 10 (64-bit), toolchain is `stable-x86_64-pc-windows-gnu`, full example code is in https://github.com/leorik/hyper_halting_issue repository.

Notes:
1 - It is important to issue at least one request after server got started and before shutdown signal got sent or server will successfully stop in both cases.

**Comment by seanmonstar** [comment]
The issue you're seeing is that you've returned `Async;:NotReady`, but not scheduled a way to notify when the future *would* be ready (doing something with `futures::task::current()`).

However, it's pretty easy to fix your original issue (since it looks like you can use `FnMut`):

```rust
let (tx, rx) = futures::sync::oneshot::channel();

let mut tx = Some(tx);

windows_register(name, move |_| {
    if let Some(tx) = tx.take() {
        let _ = tx.send(());
    }
});
```

**Comment by leorik** [comment]
@seanmonstar Ah, gotcha! Need to `notify` receiver task when I `send` shutdown signal.

Unfortunately I can't use `FnMut`, but transfering ownership of consumables to wrapping `Option` and then `take`-ing them is a cool trick, would be useful! Haven't guessed it by myself.

Anyway, much thanks! It looks like my issue is solved, and some of `futures` magic is unveiled. 😊

And while we are on it, may be you could tell me - does `Task` of the future changes between `poll` calls?

**Comment by seanmonstar** [comment]
Yes, the `Task` *can* change, but many times it won't. If you want to, you can check `task.will_notify_current()` before replacing with a new one.

**Comment by leorik** [comment]
@seanmonstar Ok, thank you very much!
I feel like I would dig this topic for a long time without your guidance.
