### ISSUE TITLE
How do I use server::conn::Connection::poll_without_shutdown?

### ISSUE THREAD

**Issue by vi** [hyperium/hyper#1786]
It seems to require type parameter `E` to implement some private trait, with a default bind to some private type.

The closest I can get:

```rust
use hyper; // 0.12.24
use hyper::server::conn::Connection;
use hyper::service::Service;
use tokio::prelude::{AsyncRead,AsyncWrite,Future};

struct MyWrapper<T:AsyncRead+AsyncWrite,S:Service,E>
(pub Connection<T,S,E>)
//where Connection<T,S,E>: Future<Item=(),Error=()>
;


impl<T:AsyncRead+AsyncWrite,S:Service,E> MyWrapper<T,S,E> where Connection<T,S,E> : Future<Item=(),Error=()> 
{
    fn poll(&mut self) {
        self.0.poll(); // works
        self.0.poll_without_shutdown(); // compile fail
    }
}
```

```
   = note: the method `poll_without_shutdown` exists but the following trait bounds were not satisfied:
           `hyper::common::exec::Exec : hyper::common::exec::H2Exec<<S as hyper::service::service::Service>::Future, _>`
```

Or is there another way to do HTTP upgrades without high-level API?

**Comment by vi** [comment]
Looks like the answer is using `futures::future::poll_fn`, but it may be a problem to get IO back from Connection.

**Comment by ubnt-intrepid** [comment]
Here is an example of retrieving I/O after `poll_without_shutdown`:

https://github.com/hyperium/hyper/blob/fc18b680a5656a0c31bc09c1c70571956a1fd013/tests/server.rs#L1157-L1162

The returned future from `poll_fn` has the signature `Future<Item = Parts<I, S>, Error = hyper::Error>` and you could retrieved the upgraded I/O as follows:

```rust
let mut conn = Some(http.serve_connection(stream, service));
poll_fn(move || -> hyper::Result<_> {
    try_ready!(conn.as_mut().unwrap().poll_without_shtudown());
    Ok(conn.take().unwrap().into_parts().into())
})
.and_then(|Parts { io, read_buf, service, .. }| {
    /* do some stuff... */
})
```

(It might be useful to be enable to write...)

```rust
poll_fn(move || conn.poll_with_upgrade()) // impl Future<Item = Parts<I, S>, Error=Error>
    .and_then(|Parts { io, read_buf, service, .. }| {
        ...
    })
```

**Comment by vi** [comment]
Thanks, something like this should be in docs.

**Comment by seanmonstar** [comment]
I'd be happy to improve the docs here. What do you think would help? Putting these examples right in the documentation of the method?

**Comment by vi** [comment]
If some form of #1787 goes in, then it should be just a pointer to `poll_fn` and `try_ready!` as the recommended way to use the function. If no #1787, then entire example from https://github.com/hyperium/hyper/issues/1786#issuecomment-476696825 should go in.
