### ISSUE TITLE
How to attach header to request

### ISSUE THREAD

**Issue by gilgameshskytrooper** [hyperium/hyper#1792]
I apologize in advance if my question is stupid since I am new to Rust coming from a mostly Go background.

I am trying to attach a basic auth header like the following curl command `curl -u "api_key:api_token" https://api.voiceit.io/users`

```rust
extern crate base64;
extern crate hyper;
extern crate hyper_tls;
use base64::encode as base64encode;
use hyper::header::AUTHORIZATION;
use hyper::rt::{self, Future, Stream};
use hyper::{Client, HeaderMap};
use hyper_tls::HttpsConnector;
use std::io::{self, Write};

fn run() {
        rt::run(rt::lazy(|| {
            let mut headers = HeaderMap::new(),
            headers.insert(
                AUTHORIZATION,
                    base64encode(&format!("{}:{}", api_key, api_token))
                        .parse()
                        .unwrap(),
           );

            let https = HttpsConnector::new(4).unwrap();
            let client = Client::builder().build::<_, hyper::Body>(https);

            client
                .get((base_url.to_string() + "users").parse().unwrap())
                .and_then(|res| {
                    println!("Response: {}", res.status());
                    res.into_body()
                        // Body is a stream, so as each chunk arrives...
                        .for_each(|chunk| {
                            io::stdout()
                                .write_all(&chunk)
                                .map_err(|e| panic!("example expects stdout is open, error={}", e))
                        })
                })
                .map_err(|err| {
                    println!("Error: {}", err);
                })



        }))
}
```

My question is how can I attach the headers `HeaderMap` object to my client/HTTP GET request. I went over your docs at https://docs.rs/hyper/0.12.25/hyper/struct.HeaderMap.html and I can't find the documentation of how to attach this to an actual request.

Thank you

**Comment by seanmonstar** [comment]
You can create a `Request::default()`, and then attach the header via `req.headers_mut().insert(name, val)`, and call `client.request(req)`, instead of using `client.get()`.

----

If you want, the [reqwest](https://crates.io/crates/reqwest) library has convenience methods for basic auth, among plenty of other client utilities you may normally expect.

**Comment by gilgameshskytrooper** [comment]
Thanks a bunch (and the plug for reqwest. Unfortunately, the OpenSSL dependency will not work in my situation as I am trying to find a minimal dependency solution).

On that note, another question I have is does `hyper-tls` also depend on OpenSSL libraries?

**Comment by davidbarsky** [comment]
@gilgameshskytrooper hyper-tls does, but [rustls](https://github.com/ctz/rustls) via [hyper-rustls](https://github.com/ctz/hyper-rustls) would allow you to side-step the OpenSSL dependency.

**Comment by gilgameshskytrooper** [comment]
O ok. Thanks a bunch.

**Comment by seanmonstar** [comment]
reqwest uses native-tls by default (which uses openssl on Linux), but it's possible to build reqwest without TLS by setting `default-features = false`, or also by adding rustls support.

**Comment by gilgameshskytrooper** [comment]
If i need to access a TLS encrypted endpoint, will `default-features = false` still work in reqwest?

Like i am talking about something like Go's stdlibs http package will handle TLS handshakes and whatnot with native Go code (crypto/x509) without relying on OpenSSL?

**Comment by seanmonstar** [comment]
Without enabling the `rustls-tls` feature, but disabling the default, then no TLS code will be built. You could do:

```toml
reqwest = { version = "0.9", default-features = false, features = ["rustls-tls"] }
```

To get something like Go. rustls is a library built on *ring*, a gradual translation of Google's BoringSSL into Rust.

**Comment by gilgameshskytrooper** [comment]
I see. Thank you
