### ISSUE TITLE
Hyper should skip automatic Content-Length header for HTTP 304 responses

### ISSUE THREAD

**Issue by xfix** [hyperium/hyper#1797]
It's unnecessary, see [RFC 7232](https://tools.ietf.org/html/rfc7232#section-4.1).

Currently Hyper for empty bodies with Content-Length header unset automatically sets the value 0 which is incorrect for HTTP 304 responses, the correct values are either to not provide Content-Length (recommended by specification)  or to provide Content-Length of a full response.

**Comment by seanmonstar** [comment]
This gets set here: https://github.com/hyperium/hyper/blob/8d70baca611869c1997571e8513717396b13328b/src/proto/h1/role.rs#L479

A check could be added there for cases when there should be no header added.
