### ISSUE TITLE
building on nightly with futures_api

### ISSUE THREAD

**Issue by prasannavl** [hyperium/hyper#1798]
Any thoughts on getting it to build with latest nightly, after the breaking changes to futures_api? `futures-preview-0.3.0-alpha.14` is now required. Tokio seems to builds fine. 

It looks like the futures_api has come to a reasonable state to start getting an alpha on it? No way to compile projects with hyper otherwise on later nightlies.

**Comment by seanmonstar** [comment]
> No way to compile projects with hyper otherwise on later nightlies.

Care to expand what you mean? As far as I know, you can still use the nightly futures API with hyper by using the 0.3 compat, same as with Tokio.

**Comment by prasannavl** [comment]
Oh no! I'm terribly sorry. It's just the problem with tokio `async-await-preview` feature (since that hasn't been cut into a release yet). 

Sorry again - was sleep deprived and didn't dig in properly. Closing.
