### ISSUE TITLE
Implement TryFrom for Destination

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1808]
With `TryFrom` now stable, we can provide a `TryFrom<Uri>` for `Destination`. To prevent *requiring* the new Rust compiler, this can include a `#[cfg]` attribute that is set in the `build.rs`.

**Comment by M3rs** [comment]
I'd like to give this a shot. I think I have the implementation working, but I don't know a lot about ```#[cfg]``` in ```built.rs```.

**Comment by seanmonstar** [comment]
Similar to how it's currently checking for Rust 1.30, and if found, printing `cargo:rustc-cfg=error_source`, a new check can be added for Rust 1.34, and if found, print `cargo:rustc-cfg=try_from`. Then add the `#[cfg(try_from)]` attribute to the `impl TryFrom<Uri> for Destination`.

When doing so, it'd be best to only call `version().unwrap()` once, since that's invoking a child process to run `rustc -V`...
