### ISSUE TITLE
server::Builder stream/connection window size methods work by reference

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#1814]
All of the other setters on the builder type operate by-value, but http2_initial_connection_window_size and http2_initial_stream_window size work by-reference.

**Comment by seanmonstar** [comment]
Ah man, that's an unfortunate mistake. I'll assign this breaking change to be done in 0.13.

**Comment by seanmonstar** [comment]
As an interim, we could add new methods that are by-value, with an underscore prefix... 🤷‍♂️
