### ISSUE TITLE
Concurrent requests performance with SimpleHTTPServer

### ISSUE THREAD

**Issue by phra** [hyperium/hyper#1816]
i am writing a rust implementation of a web content buster https://github.com/phra/rustbuster/blob/feat/loop/src/fetcher.rs

the relevant code looks like this:

```rust
pub fn _run(urls: Vec<hyper::Uri>) {
    rt::run(lazy(|| {
        let client = Client::new();

        for url in urls {
            rt::spawn(_fetch_url(&client, url));
        }

        Ok(())
    }));
}
```

at the moment the generated binary runs really slow, 8 seconds for 80 http request.

while debugging the performance issue i noticed that if i use `strace -f` to trace it, it runs fast as expected (1,5 seconds)

![image](https://user-images.githubusercontent.com/984628/57790012-3905ca00-773a-11e9-89b4-4ae5fce5c61e.png)

setup:
- `rustc = "1.34.1"`
- `hyper = "0.12.28"`

**Comment by phra** [comment]
maybe related to https://github.com/hyperium/hyper/issues/1813

**Comment by seanmonstar** [comment]
I see you've linked a commit, do you think that it's related because older versions of hyper aren't affected?

**Comment by phra** [comment]
i have manually profiled my code and most of the time is spent between `client.get()` and `and_then()`, the futures are spawned all together very fast, and then hyper seems to lose time while executing them in an unsorted fashion. using a profiler like `valgrind` make the execution going fast as with `strace -f`

**Comment by phra** [comment]
using `npx http-server -p 8000` instead of `python -m SimpleHTTPServer 8000` solve the performance issue.. however i consider it a bug anyway because i don't have issues with the python http server and other buster written in other languages..

**Comment by DoumanAsh** [comment]
@phra `Connection: close` means you're asking to close connection as soon as message exchange is finished

**Comment by seanmonstar** [comment]
Is it really slow to actually fetch all the URLs, or does it fetch them all quickly and then take a few seconds for the runtime to shutdown?

**Comment by phra** [comment]
it slowers over time. i also noticed that using a big wordlist (230K lines) make the problem appear again also with `Connection: keep-alive`.

**Comment by seanmonstar** [comment]
> 8 seconds for 80 http request.

So I adjusted the `hello.rs` example to send just `Connection: close`, and the `client.rs` to accept an integer parameter and spawn that many requests aimed at the `hello.rs` server. It does 100 requests in 0.16 seconds, and 1000 requests in 0.4s. So there must be something else I'm missing...

**Comment by phra** [comment]
Try with 230000 request.

**Comment by seanmonstar** [comment]
> Try with 230000 request.

I'm not sure what I'd be looking for, and with the many requests, the logs will be very noisy. I was trying to reproduce with the smaller number, to make it easier to read the log output to see where an issue may be. By sending `connection: close`, I'd hoped that would achieve your original issue. I guess a difference I missed is that the Python `SimpleHTTPServer` is sending the file contents of the directory, and I was just sending an empty body. I'll check that out.

**Comment by seanmonstar** [comment]
Just tried with Python `SimpleHTTPServer` and it is indeed super slow with 100 requests. I'll look more into why.

**Comment by seanmonstar** [comment]
After digging through logs all day, I've noticed that a similar client using Nodejs sees the same kind of slow down. The logs suggest that its mostly waiting at `epoll_wait`, because the sockets haven't been written to on the server. It seems more likely the issue is with `SimpleHTTPServer`.

**Comment by phra** [comment]
@seanmonstar i don't have the problem with my nodejs project https://github.com/phra/nodebuster

**Comment by seanmonstar** [comment]
Here's the nodejs client I used that also has the problem:

```js
const http = require('http');

const MAX = 100;
const LOG_MOD = Math.max(Math.floor(MAX / 10), 1);
const START = Date.now();

let completed = 0;
for (let i = 0; i < MAX; i++) {
  let url = 'http://127.0.0.1:3000/LICENSE';
  http
    .request(url, (res) => {
      let my_i = ++completed;
      if (my_i % LOG_MOD === 0) {
        console.log(`Response ${(my_i / MAX) * 100}% (${my_i} of ${MAX}) took ${since()}: ${res.statusCode}`);
      }
      res.destroy();
    })
    .on('error', (e) => {
      console.error(`request error: ${e.message}`);
    })
    .end();
}

function since() {
  return `${(Date.now() - START) / 1000}s`;
}
```

Searching very briefly about `SimplHTTPServer` shows many results that it hangs with concurrent connections. Perhaps a difference is that the client in your "nodebuster" is not making requests concurrently?

Anyway, since it seems to be a problem with some other server implementation, and not hyper specifically, I'm going to close.

**Comment by phra** [comment]
@seanmonstar thanks for the snippet. i am trying to investigate the issue.. https://github.com/phra/nodebuster doesn't have the specific problem but i cannot fix you snippet..

![image](https://user-images.githubusercontent.com/984628/58089568-64b70300-7bc5-11e9-9df5-67108654d0a9.png)
