### ISSUE TITLE
Right way to get a Handle for use with other tokio crates?

### ISSUE THREAD

**Issue by singpolyma-shopify** [hyperium/hyper#1819]
For example https://docs.rs/tokio-memcache/0.0.3/tokio_memcache/struct.Client.html requires a `Handle` -- but since `hyper::rt::run` inits tokio for me, I'm unclear on the right way to get the `Handle`.  Or do I have to switch to lower-level APIs than the Runtime if I want to use other crates like this?

**Comment by seanmonstar** [comment]
Looks like that is using `tokio-core`, which is deprecated. You *can* still use `tokio-core` with crates using `tokio`, but it's more annoying, and not something I recall off the top of my head.

**Comment by singpolyma-shopify** [comment]
Ok, so really it's just this one case is an old API and I should probably skip that crate but generally won't need this otherwise?

**Comment by seanmonstar** [comment]
Yea, the new tokio now will lookup a `Handle` automatically when needed (and there's APIs to set a specific one if you so desire, but it's usually never needed).
