### ISSUE TITLE
Handling preflight

### ISSUE THREAD

**Issue by glennpierce** [hyperium/hyper#1825]
Hi I am building a very simple json webservice but have to handle a post from a different domain.

Is there an example of how to handle the preflight OPTIONS request ?
I have looked around but can't find anything.

Thanks

**Comment by seanmonstar** [comment]
In your service, you can check the `Request::method()` for `Method::OPTIONS`, and then respond accordingly.

You may find it easier to use a server web framework that can handle CORS and other routing for you. If you want something building on top of hyper, check out [https://crates.io/crates/warp](warp) (which has a CORS helper built-in).
