### ISSUE TITLE
Bad tail latency: always-ready connection can starve others

### ISSUE THREAD

**Issue by ry** [hyperium/hyper#1828]
We compare a [hyper hello-world server](https://github.com/denoland/deno/blob/3dff147d0ca1a2cd8d264d20a178d71cb38b1c4e/tools/hyper_hello.rs)'s performance against our own (dynamic language) web server. We've noticed that hyper has very bad tail latency - sometimes as much as 2 seconds.

You can see it here https://deno.land/benchmarks.html#max-latency
<img width="718" alt="Screen Shot 2019-06-14 at 2 08 55 PM" src="https://user-images.githubusercontent.com/80/59529067-fdcbf780-8ead-11e9-8d23-1b3a12638c51.png">

We debugged this a bit, thinking at first it was our setup. But concluded that it was indeed a bug in hyper after making these changes: https://github.com/denoland/deno_third_party/compare/1902aba524c96f56c1dd654f04660a1fc3ebf80d...d8fb68ccfb72ad6a8b306dfcc3573efafa3c340f

cc @piscisaureus @carllerche

**Comment by seanmonstar** [comment]
Thanks for report! It does look like if a connection is always ready, that task will keep looping on it, which could starve the others. It's probably pretty difficult for this to happen in the real world, but a patch is pretty simple, coming up shortly!
