### ISSUE TITLE
hyper server refuses body without `Content-Length` or `Transfer-Encoding: chunked`

### ISSUE THREAD

**Issue by mdonoughe** [hyperium/hyper#1842]
This is used for Icecast streaming, where the client just opens the connection, sends the header, then just sends data until the connection is closed. You can reproduce the problem with curl using `curl -X PUT http://localhost:5000/stream -d test -H 'Content-Length:'`.

You'll get a message `[2019-07-05T20:50:55Z DEBUG hyper::proto::h1::conn] parse error (connection closed before message completed) with 4 bytes` written to the logger as hyper discards the request body.

I don't know if this is something hyper should support. Obviously if the client can't signal to the server that it is done sending data then the server can't send a response, or it needs to send the response before it has received the entire request body.

**Comment by seanmonstar** [comment]
This is required by [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.3.3). If a request doesn't have a `Transfer-Encoding: chunked` or `Content-Length` header, then:

> 6.  If this is a request message and none of the above are true, then the message body length is zero (no message body is present).

**Comment by LeviSchuck** [comment]
@mdonoughe according to https://gist.github.com/ePirat/adc3b8ba00d85b7e3870 Transfer encoding chunked is expected

**Comment by mdonoughe** [comment]
Only the new protocol uses transfer encoding chunked. Older clients just send an infinite body.
