### ISSUE TITLE
Re-enable tests for 0.13

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1848]
As part of merging #1836 (related to #1805), running the tests in CI was disabled. They should be re-enabled as we go along.

- [x] The `--lib` tests
- [x] `benches` directory
- [x] `tests/client`
- [x] `tests/server`
- [x] `tests/integration`

**Comment by jakubadamw** [comment]
The `tests/client` bit is done in #1881.

**Comment by apiraino** [comment]
@seanmonstar or anyone else, could you pls also add an example on how to use the `Service` and `MakeService` trait?

(I'm on Hyper 0.12 and having a hard time to figure that out. I'd be happy if for 0.13 that to be more discoverable).

thanks :+1: 

By the way: examples are *of the essence* for a library and I thank you so much for having written them! More of them, pls :-)

**Comment by Mathspy** [comment]
I think this is finally closed by https://github.com/hyperium/hyper/pull/1882

**Comment by weihanglo** [comment]
@Mathspy 
Not really. Some tests under `src/client` are still disabled. Most related to a new mock service implementations.

**Comment by seanmonstar** [comment]
I'm going to close this, as almost all tests have been re-enabled. I've removed the warning about the missing tests in `client/tests.rs`, as re-writing them is rather tricky.
