### ISSUE TITLE
Update the examples for 0.13

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1849]
Most of the `examples/*.rs` files still need to be updated to work with `std::future::Future`. Most can be more easily written using `#[tokio::main]`, like in [this example](https://github.com/tokio-rs/tokio/blob/master/tokio/examples/hello_world.rs).

**Comment by liufuyang** [comment]
Can I try update a simple example? Looks like you already got the hello example updated, right?
https://github.com/hyperium/hyper/blob/master/examples/hello.rs

And I should try further update it to use `#[tokio::main]` ? :)

**Comment by liufuyang** [comment]
I made a simple change like this: https://github.com/hyperium/hyper/pull/1852
let me know whether that is the right thing to do :)
