### ISSUE TITLE
Update h2 to std::future

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1851]
As part of the upgrade to `std::future` (#1805), the HTTP2 support was left as `unimplemented!`. This needs to be re-enabled, but depends on the `h2` crate updating.

**Comment by Kobzol** [comment]
Is there an issue/PR/branch that is tracking the update of h2 to `std::future`, is anyone working on it currently?

**Comment by seanmonstar** [comment]
Related issue in the h2 repo: https://github.com/hyperium/h2/issues/385

**Comment by seanmonstar** [comment]
The relevant work in the `h2` crate has merged! Next up: re-enabling the http2 stuff inside hyper. It should be a bit easier, mostly just translating old `Future` to new.
