### ISSUE TITLE
Broken link to upgrades example in docs and readme

### ISSUE THREAD

**Issue by peterjoel** [hyperium/hyper#1869]
These pages have a [broken link](https://github.com/hyperium/hyper/blob/master/examples/upgrades.rs):

* https://docs.rs/hyper/0.12.32/hyper/upgrade/index.html
* https://github.com/hyperium/hyper/blob/master/examples/README.md

**Comment by seanmonstar** [comment]
Thanks for the report! I've published 0.12.33 with updated links to the 0.12.x branch.
