### ISSUE TITLE
Remove re-export of `tokio::main`

### ISSUE THREAD

**Issue by tesaguri** [hyperium/hyper#1878]
You cannot use the `hyper::rt::main` attribute macro as it is without depending on `tokio` crate, so the re-export is not quite useful as a shorthand. I fear that it could be rather a source of confusion.

**Comment by seanmonstar** [comment]
Very good point, I hadn't considered that, and just noticed that it worked in the examples, but that's because there's already `tokio` in the `dev-dependencies`. We should remove it for now.
