### ISSUE TITLE
Getting Started with a Server guide doesn't work

### ISSUE THREAD

**Issue by kobenauf** [hyperium/hyper#1886]
The Getting Started with a Server guide has steps to create a Cargo.toml and main.rs, but it doesn't compile, with several errors.
1. use of undeclared type or module `tokio`
2. `main` has invalid return type `impl std::future::Future`
`main` can only return types that implement `std::process::Termination`
3. failed to resolve: use of undeclared type or module `pretty_env_logger`
4. the trait `hyper::service::make_service::MakeService<&'a hyper::server::tcp::addr_stream::AddrStream>` is not implemented for `hyper::service::make_service::MakeServiceFn<[closure@src/main.rs:18:32: 25:10]>`
5. the trait bound `impl std::future::Future: futures::future::Future` is not satisfied

**Comment by toplinuxsir** [comment]
I have the same problem

**Comment by dvic** [comment]
@kobenauf what does your `Cargo.toml` look like? The master branch of hyper is currently being refactored to use `std::future::Future` (as well as `tokio`), from the README:

> NOTE: hyper's master branch is currently preparing breaking changes, for most recently released code, look to the 0.12.x branch.

**Comment by kobenauf** [comment]
@dvic I used the Cargo.toml in the guide:
```
[dependencies]
hyper = "0.12"
```

**Comment by LucioFranco** [comment]
@kobenauf https://github.com/hyperium/hyper/tree/0.12.x contains all the guides and examples for the current released version of hyper `0.12.x`. The master branch is going to become the new breaking release of `0.13.x`.

**Comment by jellybobbin** [comment]
me too
