### ISSUE TITLE
Update futures preview 0.3.0-alpha.17 to 0.3.0-alpha.18

### ISSUE THREAD

**Issue by paulzhang5511** [hyperium/hyper#1897]
The futures-rs 0.3.0-alpha.18 is released. [futures-preview](https://crates.io/crates/futures-preview/0.3.0-alpha.18)

**Comment by seanmonstar** [comment]
This is blocked on tokio upgrading.

**Comment by mrjoe7** [comment]
Tokio 0.2.0-alpha.2 is now using futures-rs 0.3.0-alpha.18

**Comment by DoumanAsh** [comment]
Is there actual need to bump version? `cargo update` should pick up latest automatically

**Comment by Nemo157** [comment]
@DoumanAsh during these alphas there is no guarantee of semver compatibility, so crates that are willing to track the unstable edge should all be aggressively bumping their versions up to the latest release to provide the highest chance of interoperability.
