### ISSUE TITLE
hyper tail latency is sometimes worse than a node.js server

### ISSUE THREAD

**Issue by ry** [hyperium/hyper#1898]
<img width="697" alt="Screen Shot 2019-08-12 at 8 56 53 PM" src="https://user-images.githubusercontent.com/80/62908002-d07fb680-bd43-11e9-9987-1d8392386db6.png">

Over at https://deno.land/benchmarks.html#max-latency we measure hyper hello-world performance against a number of dynamic language web servers. We sometimes see hyper performing worse than the corresponding node.js server. This measures 90% latency as measured with `wrk --latency`. This is measuring wrk's default of 10 concurrent keep-alive connections.

[hyper_hello.rs](https://github.com/denoland/deno/blob/master/tools/hyper_hello/hyper_hello.rs)
[node_http.js](https://github.com/denoland/deno/blob/master/tools/node_http.js)

Previously (https://github.com/hyperium/hyper/issues/1828, https://github.com/hyperium/hyper/pull/1829) latency in hyper was much worse.

**Comment by seanmonstar** [comment]
Is this a regression, or the improvement is still there, and it still sometimes has latency spikes? What version of hyper does this measure?

**Comment by ry** [comment]
> Is this a regression, or the improvement is still there, and it still sometimes has latency spikes? What version of hyper does this measure?

The improvement is still there - this is much better than before. This is hyper 0.12.33.

**Comment by seanmonstar** [comment]
This *might* be a consequence of running the hello_world server on the multi-threaded runtime, while also running `wrk` on the same machine. It could be that in some runs, different number of connections get accepted to different threads that must compete on the VM.

You could try the following:

```rust
extern crate tokio;

// Previous hyper stuff...

tokio::runtime::current_thread::run(server)
```
