### ISSUE TITLE
Change `Connect` trait to alias `Service`

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1902]
After #1782 is done, the `Connect` trait should be changed to basically an alias for a `Service<Destination>`. This would allow more composability, being able to use `ServiceExt` to customize connectors.

**Comment by seanmonstar** [comment]
I just remember there is also `MakeConnection` in tower, perhaps that can just be used instead. One difference is that hyper's `Connect` currently returns a `Connected` metadata type.

**Comment by LucioFranco** [comment]
@seanmonstar I totally missed this issue! But we should drop the connected struct and use `http_connection::HttpConnection` trait. Which pretty much does the same but allows us to be a bit more flexible. I'm honestly in the boat that we should just drop Connect or have it be what https://github.com/tower-rs/tower-http/blob/master/tower-http-util/src/connection.rs#L15 was.
