### ISSUE TITLE
How to get http query param ?

### ISSUE THREAD

**Issue by toplinuxsir** [hyperium/hyper#1911]
In hyper how to get  url params,
for exmaple Http://server/?p1=a&p2=b
how to get p1 and p2?
Thanks !

**Comment by seanmonstar** [comment]
You can use [`Uri::query()`](https://docs.rs/http/0.1.*/http/uri/struct.Uri.html#method.query) to get the optional query.

```rust
let uri = Uri::from_static("http://server/?p1=a&p2=b");
assert_eq!(uri.query(), Some("p1=a&p2=b"));
```
