### ISSUE TITLE
How to convert hyper::Request to http:Request?

### ISSUE THREAD

**Issue by ecumene** [hyperium/hyper#1914]
Related reddit post: https://www.reddit.com/r/rust/comments/crrdob/hyper_staticfile_handling_hyper_request/

I'm attempting to convert hyper:Request to http:Request, so I can have a unified HTTP and WS server. Here's what I have, I'm using the Server::http() syntax because it was used in the example for websocket-rs.

```
Server::http("0.0.0.0:80")
.unwrap()
.handle(move |req: Request, res: Response| {
    let resolve_future = hyper_staticfile::resolve(&root, &req);
    let response_future = resolve_future.map(move |result| {
        hyper_staticfile::ResponseBuilder::new()
            .build(&req, result)
            .unwrap()
    }
    // ... ?
 });
```

The problem is here:

```
let request_http = http::Request::from_parts(request.into_parts());
```

```
no method named `into_parts` found for type `hyper::server::request::Request<'_, '_>` in the current scoperustc(E0599)
```

The curious thing is there is an impl for `into_parts` in the docs... Am I doing something wrong here?

Thanks for helping a web-dev and hyper noobie, and for the great library!

**Comment by seanmonstar** [comment]
That sample code looks like an older version of hyper (0.11). In 0.12, hyper uses the `http` crate directly.

**Comment by ecumene** [comment]
After all, actix-web had pre-build actors with basically everything my app needed to run http and websockets in the same thread

Thanks again for the help, and the great lightweight library!
