### ISSUE TITLE
Consider `Stream`s instability

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#1920]
The `Stream` trait isn't stable like `Future` is, and hyper uses it in a couple places. Is it worth putting all usage behind some `unstable` feature flag?

- `impl Stream for Body`: this exists for convenience so users can use stream combinators. Easily optional.
- `Body::wrap_stream`: this exists to allow users to easily wrap stream combinators into an `HttpBody`. Easily optional.
- `hyper::Server::builder(impl Stream)`: this allows using a hyper server with a stream of incoming connections besides just TCP. This is pretty fundamental. An alternative could be to define an `Accept` trait that functions similarly. And then an optional `AcceptStream<impl Stream>` can exist unstably.

**Comment by LucioFranco** [comment]
@seanmonstar I think the first two sound good. For the last one, I think the custom trait works well 👍.

**Comment by seanmonstar** [comment]
This has been done.
