### ISSUE TITLE
Remove Chunk in favor of using Bytes directly

### ISSUE THREAD

**Issue by abonander** [hyperium/hyper#1931]
Compared to `Bytes`, `Chunk` is pointless and kinda frustrating:

* It's a trivial wrapper around `Bytes` but `Bytes` is exposed via the `From`/`Into` impl anyways so it's not like it's keeping it out of the public API
* `Chunk` adds 0 new functionality over `Bytes`, all of its methods forwards to `Bytes` anyway
* There's no way to split a `Chunk` without round-tripping through `Bytes`
* Any third-party crate that wants to build on `Stream<Item = Bytes>` needs special adapters to work with `hyper::Body`

That last one is a real problem for me because I'm finally updating `multipart-async` and trying to maximize interop by generifying the API as much as possible. Because `hyper::Body` doesn't implement `AsyncRead` I've instead standardized around a `Stream<Item = impl BodyChunk>` API where `BodyChunk` covers two operations: splitting and dereffing to `&[u8]`. My final constraint is that I want to be able to return the same `impl BodyChunk` type, mostly to make it easy to drop `multipart-async` into existing request handlers.

Without implementing `BodyChunk` specifically for `hyper::Chunk` while still having an applicable impl for it, I would need an impl that's generic over `T: From<Bytes>, Bytes: From<T>, T: AsRef<[u8]>`. My hangup on this is that I now cannot implement `BodyChunk` for `&[u8]` directly, which complicates testing as I have to convert all bytestring literals to `Bytes`. (I also want to avoid a generic impl based on `Into<Bytes>` as that operation may perform implicit copies and I'm trying to be near-zero-copy.)

I realize `Chunk` exists because it used to be a custom implementation of `Bytes` but at this point it can be changed to just be a type alias and basically nothing will break (except usages of `Chunk::into_bytes()`, ironically).

**Comment by davidbarsky** [comment]
I'm a firm +1 to this suggestion. I'd also be okay with _maybe_ replacing `Bytes` usage with _just_ `Vec<u8>`, but I feel less strongly about the latter point.

**Comment by abonander** [comment]
I haven't checked if `BytesMut` is reused internally once all strong refs are gone. I assumed that was the major reason for using `Bytes` in the first place.

**Comment by davidbarsky** [comment]
I think it might be, but I’m not qualified to give an answer on that at the moment. Disregard my comment about Bytes!

**Comment by seanmonstar** [comment]
This could work out. I'd just hope all the same convenient constructors match up (I think in bytes 0.4, `Bytes::from(static_str)` will make a copy, but that's fixed in 0.5.x).

**Comment by davidbarsky** [comment]
When you say "same convenient constructors match up", are you referring to the constructors on Bytes in 0.5.x, or something else?

**Comment by seanmonstar** [comment]
Yea, I think my concerns are fixed in 0.5.x, so I'd probably wait until that is available before making the change in hyper.

**Comment by bstrie** [comment]
@seanmonstar , I interpreted this issue as implying that you wanted to make Chunk into a type alias, but it's also possible that you intended that Chunk should be removed entirely. I've just submitted a PR for the former.
