### ISSUE TITLE
git tag for 0.12.35 seems to be missing

### ISSUE THREAD

**Issue by benesch** [hyperium/hyper#1943]
Hey, noticed that 0.12.35 is released on crates.io but doesn't seem to have a corresponding Git tag/GitHub release.

**Comment by seanmonstar** [comment]
I must have forgotten to push the tag. I'll push it in the morning when I'm back at a computer.

**Comment by seanmonstar** [comment]
Pushed! https://github.com/hyperium/hyper/releases/tag/v0.12.35

**Comment by benesch** [comment]
Thanks, @seanmonstar!
