### ISSUE TITLE
Client builder's executor setter is confusing for new tokio 0.2 alpha

### ISSUE THREAD

**Issue by zimond** [hyperium/hyper#1944]
Currently in hyper, the `Builder::executor<E>()` setter requires a `for<'a> &'a E: tokio_executor::Executor` bound. Which, in latest tokio (`=0.2.0-alpha.4`), only `Sender` meets this bound.

However, `Sender` is now not exported anymore by tokio. There seems to be no easy way to set custom executor.

**Comment by seanmonstar** [comment]
Yea, some impls could probably be added to Tokio... However, it seems like the `tokio::Executor` trait may go away. I've been thinking that instead hyper should just accept `impl FnMut(Fut) -> Result<(), E>` instead, so as to not need to depend on any external trait.

**Comment by danieleades** [comment]
what about depending on https://doc.rust-lang.org/1.28.0/std/task/trait.Executor.html?

**Comment by sparky8251** [comment]
I'm currently facing this issue as well.

Code is 

```rust
let runtime = tokio::runtime::Builder::new().build().unwrap();

let mut https = HttpsConnector::new().unwrap();
https.https_only(true);

let client = hyper::Client::builder()
    .executor(runtime.executor())
    .build::<_, hyper::Body>(https);
```

Anyone have a good way to work around this issue currently or am I stuck waiting for an official hyper/tokio fix?

**Comment by zimond** [comment]
@sparky8251 Currently you need to create a new executor, something like this:

```rust

struct DefaultExecutor(TaskExecutor);


impl Executor for DefaultExecutor {
    fn spawn(
        &mut self,
        future: Pin<Box<dyn Future<Output = ()> + Send>>
    ) -> Result<(), tokio_executor::SpawnError> {
        Ok(self.0.spawn(future))
    }

    #[inline]
    fn status(&self) -> Result<(), tokio_executor::SpawnError> {
        self.0.status()
    }
}

impl Executor for &DefaultExecutor {
    fn spawn(
        &mut self,
        future: Pin<Box<dyn Future<Output = ()> + Send>>
    ) -> Result<(), tokio_executor::SpawnError> {
        Ok(self.0.spawn(future))
    }

    fn status(&self) -> Result<(), tokio_executor::SpawnError> {
        self.0.status()
    }
}
```

**Comment by danieleades** [comment]
[futures::task::Spawn](https://docs.rs/futures/0.3.1/futures/task/trait.Spawn.html) has landed.
