### ISSUE TITLE
Updating from old version - what happened to Struct hyper::header::Authorization?

### ISSUE THREAD

**Issue by FractalMatt** [hyperium/hyper#1950]
I'm trying to update to version 0.12.35 of hyper. I can't figure out how to update 
"headers.set(Authorization(Basic {..." to work with the newest version.

This one: https://crates.parity.io/hyper/header/struct.Authorization.html

Anyone have any advice for me?

**Comment by seanmonstar** [comment]
Typed headers got moved out of hyper directly. You can use headers as a string-like hashmap via: https://docs.rs/http/0.1.*/http/header/struct.HeaderMap.html

Or, separately there is a new typed headers crate that is similar to the old API: https://docs.rs/headers

**Comment by FractalMatt** [comment]
Thanks Sean, I very much appreciate all the work you've done on hyper and you answering questions so promptly.

Are there any examples of the headers crate? Having trouble figuring out how to use it with hyper.  In fact, if I were to give feedback, I would suggest that you added more examples to hyper and work on improving documentation.

I'm particularly not sure how to use the Bearer token and I would just  use the string version but seems like a few formats are valid and I'm not sure exactly how the string should look.

Thank you again!

**Comment by FractalMatt** [comment]
In case anyone else stumbles across this, think this is the format for Bearer and Basic authorization headers. Still need to test but need to finish this entire update first so it'll build.

    let mut headers = HeaderMap::new();
    headers.insert(AUTHORIZATION,format!("Bearer {}",access_token).parse().unwrap());

    headers.insert(AUTHORIZATION, base64::encode(format!("{}:{}",Username,Password)).parse().unwrap());

**Comment by abdolence** [comment]
> @seanmonstar Would still prefer to use https://docs.rs/headers header to prevent typos.

It seems this is exactly what happened here for basic auth. You missed 'Basic" part in header value:

Should be
```
headers.insert(AUTHORIZATION, base64::encode(format!("Basic {}:{}",Username,Password)).parse().unwrap());
```
instead, isn't?

Thanks for the snippet, though.

**Comment by vityafx** [comment]
I don't think it is pretty much clear for everyone how to use the `headers` crate for injecting headers into hyper's `HeaderMap`. Can anyone provide an example, please?

**Comment by davidpdrsn** [comment]
You can use `typed_insert` provided by the extension trait https://docs.rs/headers/0.3.4/headers/trait.HeaderMapExt.html#tymethod.typed_insert

**Comment by whs-dot-hk** [comment]
> I don't think it is pretty much clear for everyone how to use the `headers` crate for injecting headers into hyper's `HeaderMap`. Can anyone provide an example, please?
> 
> Let's say we have this:
> 
> ```rust
> use headers::Authorization;
> 
> let mut headers = hyper::header::HeaderMap::new();
> let auth_header = Authorization::basic(&user_name, &api_key);
> // what to do here?
> ```

```rust
use headers::{Authorization, HeaderMapExt};

let basic = Authorization::basic("Aladdin", "open sesame");
let mut req = Request::builder() // Incomplete line build the request here
let headers = req.headers_mut();
headers.typed_insert(basic);
```
