### ISSUE TITLE
Rename Service alias to HttpService

### ISSUE THREAD

**Issue by shepmaster** [hyperium/hyper#1952]
The docs say

> While it's possible to implement `Service` for a type manually [...]

But now that the trait is sealed, this doesn't seem accurate.

**Comment by seanmonstar** [comment]
It *is* possible to implement `tower::Service`, but the current situation is unnecessarily confusing. The current `hyper::service::Service` is a pseudo trait alias, really only meant to simplify bounds, as it has a blanket `where S: Service<http::Request<B1>, Response = http::Response<B2>>`.

To clear things up, I think we should make these changes:

- Rename `hyper::service::Service` to `HttpService`.
- Update its documentation describing that its a pseudo alias.
- Re-export `tower::Service` as `hyper::service::Service`.

**Comment by seanmonstar** [comment]
Done in #1985.
