### ISSUE TITLE
Sender regression in hyper 0.12.35

### ISSUE THREAD

**Issue by DemiMarie-parity** [hyperium/hyper#1954]
See <https://github.com/paritytech/substrate/issues/3685> for details.

**Comment by seanmonstar** [comment]
Would you mind explaining what behavior change you've noticed? I can't find in that repo the referenced test case.

**Comment by seanmonstar** [comment]
As described [in this comment](https://github.com/paritytech/substrate/issues/3685#issuecomment-535635245), I don't think this is a regression in the `Sender`, but rather the consequences of a bug fix around `GET` chunked bodies.

**Comment by DemiMarie-parity** [comment]
For anyone else who finds this, Substrate was trying to send a body on a `GET` request that didn’t have one.  <https://github.com/hyperium/hyper/pull/1926> made the Substrate bug visible, but it had been there before.
