### ISSUE TITLE
`AddrListener` should accept IntoSocketAddrs

### ISSUE THREAD

**Issue by nagisa** [hyperium/hyper#1959]
What it says on the tin: `TcpListener` allows for multiple addresses to be provided. I haven’t looked too deeply into whether `AddrListener` is stuck with a single address, but if it isn’t it should support binding to multiple addresses!

**Comment by seanmonstar** [comment]
`TcpListener::bind` will resolve a list of addresses, and try to bind in the order received until one successfully binds. It won't bind to multiple addresses at once, though.

**Comment by nagisa** [comment]
Well I would usually have a list of `SockAddrV6` and `SockAddrV4`, both with an UNSPECIFIED address.

Is that not something one should be doing?

**Comment by seanmonstar** [comment]
It certainly makes sense to listen on multiple addresses. I'd probably just multiple `Server`s, one with each address.

**Comment by nagisa** [comment]
@seanmonstar just making sure, was that PR intended to close this?

**Comment by seanmonstar** [comment]
Hrm, nope, that was a typo :(

However, I don't know what more to do with this issue.

**Comment by nagisa** [comment]
Its fine to keep it closed in that case. Thanks!
