### ISSUE TITLE
Update intro doc

### ISSUE THREAD

**Issue by darakian** [hyperium/hyper#1965]
Hey all,

I'm looking through your docs and it looks like there's a big difference between the hyper homepage and the docs.rs intros for writing an http server.  
https://hyper.rs/guides/server/hello-world/   
https://docs.rs/hyper/0.13.0-alpha.4/hyper/server/index.html  

The later seems like it might be a newer approach, but doesn't compile as is. Any chance I can ask for an update to the introductory docs? If not, are there any recent guides that exist outside of the `hyper.rs` domain? Thanks.

**Comment by seanmonstar** [comment]
The 0.13 version is not stable yet (requires `async`/`await` to be stabilized in Rust 1.39). The current "release" version of that doc page would be here: https://docs.rs/hyper/0.12.*/hyper/server/index.html

**Comment by darakian** [comment]
Gotcha. I'll keep an eye on it then. Thanks :)
