### ISSUE TITLE
Changelog mentions wrong feature name

### ISSUE THREAD

**Issue by jplatte** [hyperium/hyper#1966]
Moved from #1957 (which maybe never got looked at bc. failing CI?):

There's a typo in `CHANGELOG.md`:

> put `Stream` impl for `Body` behind `stream` feature

`stream` should be `unstable-stream`.

**Comment by seanmonstar** [comment]
This should be a simple change! Sorry I missed the PR, though it would probably be better to not include the newline normalization.

**Comment by hamzamuric** [comment]
Can I change it?
