### ISSUE TITLE
Client Performance

### ISSUE THREAD

**Issue by Phara0h** [hyperium/hyper#1970]
Testing against the tech-power client with the following code. I am only seeing around 20,000 rps vs using wrk I am seeing around 40,000 rps with  1 thread and 1 connection. Are these the expect performance numbers for hyper's client? Your servers performance is on a next level for speed making me expect your client would also be as performant. Now it could be this code I wrote is horrible, or something else going on here. However it would be nice to know what is going on. 

```rust
let url: hyper::Uri = "http://127.0.0.1:1237".parse().unwrap();
let client = Client::new();
let requests_til_done = loop_fn(0, move |counter| {
    client
        .get(url.clone())
        .and_then(move |_| {
            if counter < (100000) {
                Ok(Loop::Continue(counter + 1))
            } else {
                Ok(Loop::Break(()))
            }
        })
}).map_err(|err| eprintln!("error: {}", err));

hyper::rt::run(requests_til_done);
```

**Comment by seanmonstar** [comment]
Some things to consider:

- `wrk` is specially designed to minimally support HTTP1, just enough to load a server. This allows it to *do* less, and just focus on writing and reading the same bytes on a connection as quickly as possible.
- `hyper::Client` includes code to manage a connection pool. It's possible to just use a single connection without the pool logic via the types in `hyper::client::conn`.
- `hyper::rt::run` will by default start up a multi-threaded runtime. That runtime will try to use as many threads as CPUs you have (while one of those CPUs may be running your server in another process). You can use a single-threaded runtime via `tokio::runtime::current_thread::run(fut)`.

Now then, are there ways to optimize the internal client code in hyper? Probably always. But it's likely that the `Client` is indeed performant for most use cases. For a production example, take at look at [these linkerd benchmarks](https://linkerd.io/2019/05/18/linkerd-benchmarks/), which uses hyper for its server and client.
