### ISSUE TITLE
Question: panic: error creating server listener: No such file or directory

### ISSUE THREAD

**Issue by xDarksome** [hyperium/hyper#1976]
I'm trying to run [`cargo web`](https://github.com/koute/cargo-web) `start`, but as I can see it is hyper error. Any thoughts on what could be wrong? The port is not in use.

`thread 'main' panicked at 'error binding to 0.0.0.0:8000: error creating server listener: No such file or directory (os error 2)', /home/darksome/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/server/mod.rs:116:17`

**Comment by seanmonstar** [comment]
The only thing hyper is doing there is trying to `bind` to the address, and the OS said "nope". Typical causes are that something else *is* indeed listening on that port.
