### ISSUE TITLE
Body should have a poll_next method

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#1979]
Unless the async-stream feature is enabled, the only way to get parts of a body is through the `next` async function. That doesn't work well when not in an async context (for example, when wrapping the body in an `AsyncWrite` or `Stream` implementation.

**Comment by seanmonstar** [comment]
`Body` implements `http_body::Body`, which has a `poll_data` method. That `async fn next` should probably be removed now that there's `http_body::Body::data()`, and hyper should probably re-export the trait (and remove `Payload`).

**Comment by sfackler** [comment]
Ah cool, makes sense.
