### ISSUE TITLE
(Server) Notification when remote closes the connection

### ISSUE THREAD

**Issue by singpolyma-shopify** [hyperium/hyper#1980]
It would be great if there were some way for my code to be "notified" when a client that has connected to my server and issued a request closes the connection on their end.  That way, I could halt processing and save CPU building up a response that cannot be delivered anyway.

**Comment by sfackler** [comment]
The server will generally drop the future if it detects that the connection has closed. In HTTP/1, you'll want to disable https://docs.rs/hyper/0.13.0-alpha.4/hyper/server/struct.Builder.html#method.http1_half_close to make sure that happens.

**Comment by seanmonstar** [comment]
In #1981, the default will be changing so that its assumed read hups are closures.
