### ISSUE TITLE
Server::local_addr() cannot be called with executor

### ISSUE THREAD

**Issue by njaard** [hyperium/hyper#1988]
Similar to https://github.com/hyperium/hyper/issues/1638 but I think the problem is about the executor:

    let addr: &str = ...;
    let exec = tokio::runtime::current_thread::TaskExecutor::current();
    let server = hyper::Server::bind(&addr.parse().expect("parsing address"))
      .executor(exec)
      .serve(new_service);
    let _ = server.local_addr();

    // no method named `local_addr` found for type    `hyper::server::Server<hyper::server::tcp::AddrIncoming, [closure@main.rs:206:5: 216:6 main:_], tokio_current_thread::TaskExecutor>` in the current scope

Simply removing the `.executor(exec)` line solves the problem

I can't tell why `local_addr` depends on the executor's type.

**Comment by seanmonstar** [comment]
Probably the `impl<S> Server<AddrStream, S>` block needs to add a generic for the executor, like `impl<S, E> Server<AddrStream, S, E>`...

**Comment by seanmonstar** [comment]
Closed by #2029
