### ISSUE TITLE
Trying to `futures::executor::block_on(run_server())` gives runtime error.

### ISSUE THREAD

**Issue by FabienTregan** [hyperium/hyper#1995]
I'm just learning Hyper (and Rust), and wrote the following code :

```rust
use {
    futures::executor::block_on,
    hyper::{
        service::{make_service_fn, service_fn},
        Body, Method, Request, Response, Server, StatusCode,
    },
    std::convert::Infallible,
    tokio::main,    
};

async fn hello_world(req: Request<Body>) -> Result<Response<Body>, hyper::Error> {
    let response = Response::new(Body::from("Hello, world."));

    Ok(response)
}

async fn run_server() {
    let addr = ([127, 0, 0, 1], 3000).into();

    let make_svc = make_service_fn(|_| {
        async {
            Ok::<_, Infallible>(service_fn(hello_world))
        }
    });

    let server = Server::bind(&addr).serve(make_svc);

    if let Err(err) = server.await {
        println!("server error: {}", err);
    }
}

fn main() {
    block_on(run_server());
}
```
It compiles, but gives a runtime error :
```
thread 'main' panicked at 'timer error: timer is shutdown', [...]\tokio-timer-0.3.0-alpha.6\src\delay.rs:119:23
error: process didn't exit successfully: `target\debug\baku-gazō.exe` (exit code: 101)
```
I finally found that in hyper's documentation comments (hyper 0.13.0-alpha-4) that instead of main I could have written :
```rust
#[tokio::main]
async fn main() {
    block_on(run_server());
}
```
(which then seems to use the `tokio` `executor` which starts the timer instead of using `futures-preview`'s one.)

Anyway it seems there is a dependency on tokio, or at least with tokio default configuration, which :
 - can not be caught at compilation time
 - isn't clearly stated in some documentation comments*
 - doesn't hint you about that dependency in the runtime error message.

--

.* : e.g. : https://github.com/hyperium/hyper/blob/b5e70a0dd1988ecee7ba6a788cd0cccb15cc5e26/src/service/make.rs#L107-L142 shows an empty `fn main() {}` which, as a beginner,  you think you can just replace with what you learn from [https://rust-lang.github.io/async-book/01_getting_started/04_async_await_primer.html](Asynchronous Programming in Rust - 1.3

cargo.toml :
```
[dependencies]
hyper = { git = "https://github.com/hyperium/hyper", branch = "master" }
futures-preview = "0.3.0-alpha.19"
tokio = "0.2.0-alpha.6"
```

**Comment by seanmonstar** [comment]
Good point, the panic messages should be improved in tokio to better describe why it failed.

**Comment by seanmonstar** [comment]
I've filed https://github.com/tokio-rs/tokio/issues/1713 to track improving the messages.

**Comment by expenses** [comment]
Is it possible to get around this issue by not using `hyper` with the `runtime` feature?

**Comment by Nemo157** [comment]
@expenses Yes, if you want to integrate hyper with a non-tokio runtime that is possible by disabling the `runtime` feature and implementing adaptors to provide the expected trait implementations for hyper, e.g. <https://gist.github.com/Nemo157/7fb644b8ae222bf0159ab8a33ff67978> shows the current alpha running on top of `async-std`. You miss out on the ergonomic APIs like `hyper::Server::bind`, but those are something that could be easily provided by a utility crate for each runtime.
