### ISSUE TITLE
How to split Upgraded?

### ISSUE THREAD

**Issue by ibaryshnikov** [hyperium/hyper#2003]
Is there a way to split Upgraded into ReadHalf and WriteHalf?

**Comment by seanmonstar** [comment]
You should be able to just use [`AsyncRead::split`](https://docs.rs/tokio-io/0.1.12/tokio_io/trait.AsyncRead.html#method.split).

**Comment by ibaryshnikov** [comment]
At first I also thought it should work, but then I got an error
```
error[E0599]: no method named `split` found for type `hyper::upgrade::Upgraded` in the current scope
  --> src/main.rs:51:34
   |
51 |     let (read, write) = upgraded.split();
   |                                  ^^^^^ method not found in `hyper::upgrade::Upgraded`
```
Do I need to import something else? I already do
```rust
use hyper::upgrade::Upgraded;
use tokio::io::{AsyncRead, AsyncWrite, AsyncReadExt, AsyncWriteExt};
```
and
```toml
[dependencies]
hyper = "0.13.0-alpha.4"
tokio = "0.2.0-alpha.6"
```

**Comment by seanmonstar** [comment]
Oh, didn't realize you were using the alphas. In that case, I think it's `let (read, write) = tokio::io::split(upgraded);`.

**Comment by ibaryshnikov** [comment]
@seanmonstar thanks, it helped!
