### ISSUE TITLE
upgrade expected but low level API in use when using gotham w/ websocket

### ISSUE THREAD

**Issue by SchrodingerZhu** [hyperium/hyper#2006]
Gotham's example of websocket is broken on my computer. Its hyper keeps complaining "upgrade expected but low level API in use".

https://github.com/gotham-rs/gotham/tree/master/examples/websocket

**Comment by seanmonstar** [comment]
In order to use `hyper::Body::on_upgrade`, the server needs to enable upgrades on the server `Connection`. Looks like Gotham is using `Http::server_connection(socket, service)`, it needs to add `.with_upgrades()` to that.
