### ISSUE TITLE
How read whole chunk from transfer-encoding=chunked body?

### ISSUE THREAD

**Issue by bronfo** [hyperium/hyper#2010]
My web server and client are both writing with the hyper crate. when server response a body with a large chunk (eg. 3634bytes), then my client read with body.next().await method, I will get two chunks (2803bytes and 831bytes).
How can I get whole chunk per one reading?

**Comment by seanmonstar** [comment]
That's because hyper *streams* the body content to you. You can concatenate the body as you receive it (usual caveats that you may wish to handle a max size, as this may end up using a *lot* of memory).

```rust
let mut full = Vec::new();
while let Some(chunk) = body.next().await {
    full.extend(chunk?);
}
```

**Comment by inv2004** [comment]
How to understand that one chunk is ended and you continue with another chunk?
