### ISSUE TITLE
Upgrade to stable futures 0.3

### ISSUE THREAD

**Issue by ebkalderon** [hyperium/hyper#2013]
Currently, Hyper is not semver compatible with stable upstream `futures` >= 0.3.0 because the manifest pins the version to `futures-core-preview = "=0.3.0-alpha.19"`. This means that projects depending on non-prerelease versions of `futures` 0.3 are not interoperable with Hyper or with downstream crates that depend on Hyper, specifically when working with streams or the combinator `FutureExt` API. Most notably, see https://github.com/hyperium/tonic/issues/139 in the hyperium/tonic repo for an example.

This requires downstream crates to version-pin their crates to `futures-preview = "=0.3.0-alpha.19"` as well, which is undesirable in the long term as the `futures` API evolves. Considering the `futures` crate is now currently at version 0.3.1 and seems to have picked up its release cadence, it would be nice to have Hyper depend on `futures` 0.3.0 at minimum for increased flexibility.

**Comment by seanmonstar** [comment]
This was done in #2007.

**Comment by alex** [comment]
Would it be possible to do another alpha release with this? Thanks!
