### ISSUE TITLE
Example of using `make_service_fn` and modifying the Response before returning

### ISSUE THREAD

**Issue by EverlastingBugstopper** [hyperium/hyper#2020]
I want to preface this by saying this is a general question and not a bug or an "issue", but it might be something worth adding to the examples!

I'm struggling to understand the right way to go about this - I want to take a `Response` and modify its `ResponseHeaders`,  except that the `make_service_fn` paradigm I've followed up until this point requires a `ResponseFuture` to be returned. 

```rust
let https = HttpsConnector::new().expect("TLS initialization failed");
let client = Client::builder().build::<_, Body>(https);

let make_service = make_service_fn(move |_| {
    let client = client.clone();
    async move {
        Ok::<_, failure::Error>(service_fn(move |req| {
            make_request(req, client.to_owned())
        }))
    }
});

let server = Server::bind(listening_address).serve(make_service);
println!("Listening on http://{}", listening_address_str);
if let Err(e) = server.await {
    eprintln!("server error: {}", e);
}

fn make_request(
    req: Request<Body>,
    client: Client<HttpsConnector<HttpConnector>>,
) -> ResponseFuture {
  client.request(req)
}
```

Perhaps I need to switch up the paradigm here, I'm generally trying to MITM all requests and make some small modifications in the middle. 

I tried going down this path but I was getting warnings that I can't use `.await` in the top level closure. This also may ruin the whole point of async by adding an await here - all I need to do is modify the headers, I don't need to do anything to the body.

```rust
async fn make_request(
    req: Request<Body>,
    client: Client<HttpsConnector<HttpConnector>>,
) -> Result<Response> {
  let response = client.request(req).await?
  // make response modifications
  response
}
```

**Comment by hwchen** [comment]
Do you mean something like this? From my understanding, you want to do modifications like you indicate in the last example, except you want to be able to do it outside the fn in the `service_fn` closure.

If so, I had struggled with something similar, async block usage was not natural to me.
```rust
    let make_service = make_service_fn(move |_| {
        let client = client.clone();
        async move {
            Ok::<_, failure::Error>(service_fn(move |req| {
                let client = client.clone();
                async move {
                    let mut resp = make_request(req, client).await?;
                    resp.headers_mut().insert(HOST, HeaderValue::from_static("world"));

                    Ok::<_, failure::Error>(resp)
                }
            }))
        }
    });
```
I use this example to learn from: https://github.com/hyperium/hyper/blob/master/examples/state.rs, I haven't checked other examples to see if they're also helpful.

**Comment by EverlastingBugstopper** [comment]
Beautiful!! I missed that example. Thank you so so much @hwchen :)
