### ISSUE TITLE
support for futures::io::AsyncRead/Write

### ISSUE THREAD

**Issue by Licenser** [hyperium/hyper#2024]
It seems that hyper uses tokio's AsyncRead / Write trait not the futures-0.3 one which makes it hard to mix with other libraries - would it be possible to implement both of the traits for hyper?

For context: I'm trying to upgrade a http connection to a websocket connection using async-tungstenite

**Comment by davidbarsky** [comment]
I don't think this will happen happen for a bit. For additional details, see: https://github.com/tokio-rs/tokio/pull/1744.

If I recall correctly, there _is_ a crate that provides compatibility between Tokio's `AsyncRead/Write` and Futures' `AsyncRead/Write`, but I can't seem to find it right now.

**Comment by Licenser** [comment]
No worries I gave up and put the web server on its own port, in fortunate that I can do that right now. There are more issues like different runtimes that make it impossible even when working around this. I’ll just go back to my cave for a few month and hope the Async ecosystem has stabilized in n something

**Comment by seanmonstar** [comment]
Yea, as mentioned, the reason we're using Tokio's traits is because we'd like to consider alternative designs to the one proposed in `futures-io`.

**Comment by jinq0123** [comment]
hyper-futures
Compatibility layer for futures to use AsyncRead and AsyncWrite traits with hyper

> If I recall correctly, there _is_ a crate that provides compatibility between Tokio's `AsyncRead/Write` and Futures' `AsyncRead/Write`, but I can't seem to find it right now.

async-compat
v0.2.4
Compatibility adapter between tokio and futures

**Comment by jinq0123** [comment]
Trait [tokio_util](https://docs.rs/tokio-util/latest/tokio_util/index.html)::[compat](https://docs.rs/tokio-util/latest/tokio_util/compat/index.html)::[FuturesAsyncReadCompatExt](https://docs.rs/tokio-util/latest/tokio_util/compat/trait.FuturesAsyncReadCompatExt.html#)
Extension trait that allows converting a type implementing futures_io::AsyncRead to implement tokio::io::AsyncRead.

**Comment by jinq0123** [comment]
Struct [smol_hyper](https://docs.rs/smol-hyper/latest/smol_hyper/index.html)::[rt](https://docs.rs/smol-hyper/latest/smol_hyper/rt/index.html)::[FuturesIo](https://docs.rs/smol-hyper/latest/smol_hyper/rt/struct.FuturesIo.html#)
This type implements [hyper](https://docs.rs/hyper/1.1.0/x86_64-unknown-linux-gnu/hyper/index.html) I/O traits for [futures-io] implementors.
