### ISSUE TITLE
Update to tokio 0.2

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2025]
- [ ] Blocked on `h2`: https://github.com/hyperium/h2/milestone/2

**Comment by liufuyang** [comment]
looks like the blocker is gone now? :)

**Comment by bikeshedder** [comment]
The h2 change was just commited to the code repository and no new release uploaded to `crates.io`. :disappointed:

**Comment by alex** [comment]
A follow up change is needed to `h2` to restore all behavior: https://github.com/hyperium/h2/pull/429

Please keep in mind that in the US it's Thanksgiving weekend, so many folks will not be looking at github, instead spending time with friends and family and over eating.

**Comment by bstrie** [comment]
hyperium/h2#429 has merged, though for the remaining blocker of publishing a new h2 release let's utilize threads in the relevant repo: https://github.com/hyperium/h2/issues/430

**Comment by seanmonstar** [comment]
Yep, `h2` updated its `tokio` dependency, there's one last remaing thing there: we need a new `http` release since `tokio` uses a newer `bytes`.

This is my highest priority this week!

**Comment by fenhl** [comment]
Is an alpha release with this planned soon?
