### ISSUE TITLE
Clarify use of `#[tokio::main]`

### ISSUE THREAD

**Issue by hwchen** [hyperium/hyper#2028]
The `#[tokio::main]` macro is used in most (all?) of the examples, and also shows up in [documentation](https://docs.rs/hyper/0.13.0-alpha.4/hyper/server/index.html).

However, it's not a part of the `hyper` crate (and was explicitly removed from reexport https://github.com/hyperium/hyper/issues/1878).

I feel like this could be a confusing spot for people new to hyper/tokio, perhaps it would be good to mention pulling in `tokio` as a dependency for this feature more explicitly.

**Comment by hwchen** [comment]
Now the cargo dep should be:
```
tokio = { version = "0.2.3", features = ["macros"] }
```

**Comment by kellytk** [comment]
Related issue: https://github.com/hyperium/hyper/issues/1613

**Comment by seanmonstar** [comment]
I've updated the examples README about dependencies required.
