### ISSUE TITLE
Rename `unstable-stream` feature to just `stream`

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2034]
While hyper is pre-1.0, it's not really fair to say other pre-1.0 dependencies are unstable.

Should `stream` be enabled by default?

**Comment by hwchen** [comment]
To me, `stream` seemed like a core trait, just like `future`, so I was surprised when I had to switch it on in hyper.

I know that the reality around what’s core at the moment is a bit more complicated at the moment, but the above is just my initial reaction.

I would vote yes for `stream` as default,  but perhaps there’s downsides I didn’t think of.

**Comment by davidbarsky** [comment]
I think it should be. Worst comes to worst, Hyper can issue a smaller `0.14` release that walks back on the on-by-default `stream` feature.

**Comment by davidbarsky** [comment]
I forgot to note this, but: I think it's reasonable to say that a hypothetical 0.14 release will come out in a half a year to a year's time. I don't believe `Stream` will be in the standard library six months from now.
