### ISSUE TITLE
HTTP/1.1 server sends chunks in response progressively

### ISSUE THREAD

**Issue by wangjia184** [hyperium/hyper#2049]
HTTP/1.1 server.
Transfer-Encoding : chunked

How can I send chunk in response progressively? it seems this feature is missing?

**Comment by seanmonstar** [comment]
The title claims it "sends", but your comment is asking how to do so. hyper is able to send buffered and streaming bodies. What are you trying to do? What currently isn't working the way you'd expect?

**Comment by wangjia184** [comment]
Hi @seanmonstar 
may I know how to produce streaming body via hyper ?

**Comment by sfackler** [comment]
https://docs.rs/hyper/0.13.0-alpha.4/hyper/struct.Body.html#method.channel

**Comment by seanmonstar** [comment]
You have a few options:

- If you wish to use `hyper::Body`, and/or want to spawn a new task that will progressively produce data and send it on a channel, you can use `hyper::Body::channel()`.
- However, hyper is generic over the response body type, you can implement `hyper::body::HttpBody` (`hyper::body::Payload` in v0.12.x) that can yield chunks as they become available.
