### ISSUE TITLE
wrk(1) sees a huge slowdown for chunked body

### ISSUE THREAD

**Issue by FauxFaux** [hyperium/hyper#2054]
I have a server which sends chunked responses. It performs fine, and (significantly) outperforms most load testing tools. [wrk](https://github.com/wg/wrk), however, sees it going multiple orders of magnitude slower in some cases. `wrk` uses http keepalive by default; you can resolve this issue by disabling keepalives.

| server sends | wrk claims reqs/sec | data rate |
| -- | -- | -- |
| 15 chunks of 1 byte | 45,000 | 9MB/s |
| 15 chunks of 10 bytes | 45,000 | 16MB/s |
| 15 chunks of 100 bytes | 45,000 | 80MB/s |
| 15 chunks of 1000 bytes | 42,000 | 680MB/s |
| *16* chunks of 1 bytes | 1,000 | 0.2MB/s |
| 16 chunks of 10 bytes | 1,000 | 0.3MB/s |
| 16 chunks of 100 bytes | 30 | 0.05MB/s |
| 16 chunks of 1000 bytes | 45 | 0.6MB/s |

This seems .. off. Any ideas?

---

I'm pretty sure hyper is acting reasonably, at least, as far as reaching the `writev` calls; I see them being called and the data as flushed before `wrk` tries to read the data. `wrk` still occasionally blocks, though, for around 42ms, waiting for the data. This is all on `localhost`.

I'm, unfortunately, also pretty sure that `wrk` is doing the right thing. I tried [fiddling with its non-blocking reads](https://github.com/wg/wrk/pull/408), and I tried its `select` backend (instead of `epoll`); no difference.

The most suspicious thing I've seen is a delayed ACK:

![delayed ACK](https://user-images.githubusercontent.com/328180/70355173-64ccd680-1869-11ea-9250-4b929a85a889.png)

[hyper-chunky is my test server](https://github.com/FauxFaux/hyper-chunky). It has the appropriate logging enabled, so you can see what's happening in real time, if your terminal is fast enough.

e.g.
```
% ./wrk -d 1 -c 1 -t 1 http://localhost:4432/chunked/16/1
..
  1085 requests in 1.00s, 196.20KB read
Requests/sec:   1084.37
Transfer/sec:    196.08KB
```

Tested on: amd64 ubuntu 19.10 (5.3), i7-8; amd64 ubuntu 18.04 (4.15), xeon e3; someone else's random machine.

**Comment by seanmonstar** [comment]
Interesting... well, the number 16 isn't too magical, it's the internal `MAX_BUF_LIST_BUFFERS` value. Once the internal `WriteBuf` deque has that many user buffers enqueued, it applies back-pressure by not polling the `Body` until some data has been flushed.

I've found that the OS is usually able to handle the local TCP connection by just basically being a pipe, thus allowing a *much* bigger `SND_BUF`. So, when all the buffers can fit in the deque, it usually only takes 1 `write` call to flush the whole thing, no matter how big the individual buffers were.
