### ISSUE TITLE
Question : how to handle streaming body in request?

### ISSUE THREAD

**Issue by wangjia184** [hyperium/hyper#2057]
HTTP/1.1 server using hyper.
Http Client establishes an connection to server, and send a chunk every 3 seconds in body.  It is an endless http request.
Please how can I receive chunks in this case?

Thanks

**Comment by seanmonstar** [comment]
The `Body` part of the `Response` can be streamed. In order to help you, we need to know a little more about your usage. What version of hyper is this?

**Comment by wangjia184** [comment]
Hi @seanmonstar 

`Transfer-Encoding: chunked` can appear in http response but also http request. 
e.g. A sensor establishes an HTTP/1.1 connection and keeps sending data.
The reason not using UDP or other TCP protocol is, HTTP is more friendly to existing network devices (firewall / waterwall / proxy / load balance / etc)

In my case, my server currently implements this by using `actix-web`. I want to replace it with `hyper`. and I am waiting for the comming version of `hyper` depending on `tokio v2.x` :)

Generally I expect my method to be called by hyper when http request headers are received, then my server watches the data on body stream. The connection won't be dropped by server before it is disconnected by client or network.

Br

**Comment by seanmonstar** [comment]
You can see various examples of this in the `examples` directory.
