### ISSUE TITLE
Transfer-Encoding: identity

### ISSUE THREAD

**Issue by m0ppers** [hyperium/hyper#2058]
I have a web service that returns its content with "Transfer-Encoding: identity". If I read the spec correctly that means that the content should not be touched and interpreted as it is.

Unfortunately hyper seems to assume that whenever transfer encoding is present in a response header it interprets the content as if it would be chunked.

I modified the following line locally to CLOSE_DELIMITED and now it works for me (tm)

https://github.com/hyperium/hyper/blob/0.12.x/src/proto/h1/role.rs#L768

interestingly the code comment doesn't really match the actual code. not sure what the background of this is.

**Comment by seanmonstar** [comment]
Yep, that line looks wrong indeed!
