### ISSUE TITLE
Docs.rs build of 0.13 failed

### ISSUE THREAD

**Issue by nate-onesignal** [hyperium/hyper#2065]
The 0.13.0 build failed on docs.rs, so there are no docs when you search for Hyper on docs.rs.

- https://docs.rs/crate/hyper/0.13.0/builds
- https://docs.rs/crate/hyper/0.13.0/builds/204724

**Comment by seanmonstar** [comment]
Yea I noticed this too, seems there was a compiler bug.

I'm checking the docs-rs chatroom to see if I can get it rebuilt.

**Comment by seanmonstar** [comment]
Thanks to the heroic work of @pietroalbini, it's been re-built!

**Comment by pietroalbini** [comment]
Well, what can I say, hyper is the first and hopefully the last crate on docs.rs  built with beta instead of nightly :sweat_smile:
