### ISSUE TITLE
Consider implementing HttpBody for Request and Response

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2067]
In https://github.com/hyperium/http/issues/107, we didn't implement `Stream` for `http::{Request, Response}` so as to not have the external dependency. However, in `http-body`, since we define the trait and import `http`, we could provide this implementation.

It'd make these slightly nicer:

```rust
while let Some(data) = req.data().await {}

let buf = hyper::body::aggregate(req);
```

**Comment by LucioFranco** [comment]
I think this makes sense but forces http to be async I guess unless we put it behind a feature flag. Otherwise, I think this could be a great addition.

**Comment by seanmonstar** [comment]
How does it force http to be async? It'd only implement in the `http-body` crate.

**Comment by LucioFranco** [comment]
Ah you're right, if the impl is in the http-body crate then I am +1
