### ISSUE TITLE
Cannot Implement Connection Trait

### ISSUE THREAD

**Issue by kevinastone** [hyperium/hyper#2082]
The Connection trait was made private, seemingly preventing implementation of non-TcpStream `Connect` implementations.  I'm trying to use `tokio-rustls` to wrap a `TcpStream` resulting in a a `tokio_rustls::client::TlsStream` that implements the appropriate `AsyncRead+Write` traits, but cannot implement the `connected()` trait method to return the additional connection info for this steam.

> ^ the trait `hyper::client::connect::Connection` is not implemented for `tokio_rustls::client::TlsStream<tokio::net::tcp::stream::TcpStream>`

Here's my full implementation:

```
impl Service<Uri> for TestConnect {
    type Response = TlsStream<TcpStream>;
    type Error = CompatError;
    type Future =
        Pin<Box<dyn Future<Output = std::result::Result<Self::Response, Self::Error>> + Send>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<std::result::Result<(), Self::Error>> {
        Ok(()).into()
    }

    fn call(&mut self, req: Uri) -> Self::Future {
        let tls = TlsConnector::from(self.config.clone());

        TcpStream::connect(self.addr)
            .map_err(|e| Error::from(e).compat())
            .and_then(move |stream| {
                let domain = DNSNameRef::try_from_ascii_str(req.host().unwrap()).unwrap();
                tls.connect(domain, stream)
                    .inspect(|s| info!("Client TcpStream connected: {:?}", s))
                    .map_err(|e| {
                        info!("TLS TestClient error: {:?}", e);
                        Error::from(e).compat()
                    })
            })
            .boxed()
    }
}
```

**Comment by sfackler** [comment]
As the documentation for the Connect trait states, you don't implement it directly: https://docs.rs/hyper/0.13.1/hyper/client/connect/trait.Connect.html#trait-alias

**Comment by kevinastone** [comment]
@sfackler I'm referring to `Connection`, not `Connect`.  I didn't (and can't) implement `Connect` directly.  Please see the code example above.

**Comment by sfackler** [comment]
Oh sorry. You make a wrapper type, or just use the existing hyper-rustls crate: https://docs.rs/hyper-rustls/0.19.0/hyper_rustls/

**Comment by seanmonstar** [comment]
The `Connection` trait isn't private: https://docs.rs/hyper/0.13.*/hyper/client/connect/trait.Connection.html

**Comment by kevinastone** [comment]
Thanks for the pointers.  I thought I tried importing it and it was private.  Guess I'm mis-remembered.
