### ISSUE TITLE
Move HTTP upgrades API off the Body type

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2086]
Introduced in https://github.com/hyperium/hyper/pull/1563, the HTTP Upgrade/`CONNECT` API currently is accessed via `hyper::Body::on_upgrade`. This has some downsides that I'd like to address with a modified API:

- It makes the `Body` type fatter.
- It requires people keep the `Body` around, meaning they can't use stream combinators to read the body first, *and then* wait for the upgrade to finish. This also makes it more annoying for users who may wish adjust their `http::Request<Body>` into some `http::Request<Doodad>`.

## Proposed API

Similar to the proposal in #1586, the change would be to pass the `http::Request` or `http::Response` to a free function.

- `hyper::upgrade::on(req_or_resp) -> OnUpgrade`
  - We can also allow passing just a mutable reference, thus not consuming the request or response.
- Optional other functions could be added, but not necessary: `has_upgrade`, etc.

## Implementation Plan

The types would be inserted into the `http::Extensions` of the request/response (though with a private wrapper type to hide the exact details).

- Add the new `hyper::upgrade::on` function.
- The `Body::on_upgrade` method would become `#[deprecated]`.
- So as to not be a behavioral breaking change, the `OnUpgrade` would need to be placed in both the `Body` *and* the `Extensions`, wrapped in some `Arc<Lock>` that only allows taking it once.

I'd like to in a future release be able to *not* put it in an `Arc<Lock>` and place it in the `Body`, but I'm not sure how that could really be done in 0.13.x. (I knew I'd find something I forgot to change after finally releasing XD).

**Comment by dekellum** [comment]
Just my 2¢, and I don't know how you or other would feel about it, but at this early stage it should be fine IMO to just release a 0.14 with it changed to the way you believe it should be.  I suspect that only a few of us users have gone far upgrading to 0.13 yet and and its just another version to bump in our Cargo.toml.  Said from the opposite direction a quick 0.14 turnover is less concerning than breaking changes in 0.13.4 or whatever.

Maybe 0.13 just wasn't your lucky number?

If I had managed to release anything with an "^0.13" dependency already I might feel a little different, but not much.

**Comment by dekellum** [comment]
A related question: should any of this updated API actually go in the _http_ crate?

**Comment by VecrsIssues** [comment]
Should support for intermediate 1xx responses also be added?

https://tools.ietf.org/html/rfc7231#section-6.2

This could be useful for 103: Early Hints, or something else added in the future.
