### ISSUE TITLE
slow compilation

### ISSUE THREAD

**Issue by ghost** [hyperium/hyper#2088]
a binary crate that just has hyper as dependency takes 4.5 minutes to compile with a 4 core cpu. Can this be made faster? it seems really long for a low level library.

**Comment by seanmonstar** [comment]
Wow, that is a long time! Mind sharing more details? What version of hyper? What compilation settings are you using? (I don't see nearly such compile times).

**Comment by oezgurmakkurt** [comment]
Sorry for misinformation I had tokio-postgres in dependencies as well. hyper version is 0.13. cargo build takes 1 minute, cargo build --release takes 1 minutes 39 seconds. I think this is still somewhat long though.
