### ISSUE TITLE
Examples should have Cargo.toml

### ISSUE THREAD

**Issue by foxx** [hyperium/hyper#2095]
Had some issues getting the examples to run as there was no clear `Cargo.toml` for referencing the correct dependancies and versions etc.

Here's what worked for me, could we add it to the examples folder or the README?

```
$ cat Cargo.toml
[dependencies]
hyper = "0.13.1"
tokio = { version = "0.2", features = ["full"] }
pretty_env_logger = "0.3.1"
```

**Comment by andrewtj** [comment]
Are you perhaps not aware that examples can be run with `cargo run --example [name]`?

**Comment by seanmonstar** [comment]
I added a section to the examples README.
