### ISSUE TITLE
Can't set mutiple cookies in single response

### ISSUE THREAD

**Issue by quanbrew** [hyperium/hyper#2100]
```rust
response.headers_mut().insert(SET_COOKIE, HeaderValue::from_static("madoka=god"));
response.headers_mut().insert(SET_COOKIE, HeaderValue::from_static("hello=world"));
```

the second `SET_COOKIE` will overwritten the first:

![image](https://user-images.githubusercontent.com/34709816/71768756-4d5e3780-2f54-11ea-9a06-916d74e46acc.png)

**Comment by seanmonstar** [comment]
`insert` will replace any existing values. To add multiple, use `append`.
