### ISSUE TITLE
Possible to use Tokio with `tokio::runtime::Builder` instead of `tokio::main`?

### ISSUE THREAD

**Issue by BatmanAoD** [hyperium/hyper#2106]
I'm trying to use Hyper in a program that spawns a number of threads determined at runtime (and does not use the Tokio runtime default number of threads). To do this, I am using `tokio::runtime::Builder`, but it seems that without `tokio::main`, Hyper cannot detect that it is running inside of a Tokio reactor. (Or possibly I'm not using `tokio::runtime` correctly, but my usage looks very similar to the [example provided in the Tokio docs](https://docs.rs/tokio/0.2.8/tokio/runtime/index.html).)

As a minimum example, I've taken the [`client` Hyper example](https://github.com/hyperium/hyper/blob/master/examples/client.rs) and renamed the `main` function to `run`, then used `runtime::block_on` to run it. Here's the code: https://github.com/BatmanAoD/hyper-custom-runtime/blob/master/src/main.rs

(I am using Hyper 0.13.1 and Tokio 0.2.8 at the moment.)

 The new `main` function is:

```
fn main() -> Result<()> {
    let mut rt = tokio::runtime::Builder::new()
        .core_threads(4)
        .build()
        .unwrap();

    rt.block_on(async {
        run().await
    })?;

    Ok(())
}
```

Attempting to run it with some URL (I'm using `http://google.com` for testing), this panics with the message that there is no reactor running:

```
thread 'main' panicked at 'no current reactor', src/libcore/option.rs:1185:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by sfackler** [comment]
You need to enable bits of the runtime and pick a scheduler: https://docs.rs/tokio/0.2.8/tokio/runtime/struct.Builder.html#method.enable_io

**Comment by BatmanAoD** [comment]
@sfackler Okay, that makes sense now, and it works. Thanks!
