### ISSUE TITLE
unix socket

### ISSUE THREAD

**Issue by IThawk** [hyperium/hyper#2110]
use tokio::net::UnixListener;
{
let path = "/root/test.sock";
    if let Err(err) = fs::remove_file(path) {
        if err.kind() != io::ErrorKind::NotFound {
            eprintln!(".......");
        }
    }
    let unix_listener = UnixListener::bind(path).unwrap();
    let acceptor = hyper::server::accept::from_stream(unix_listener.incoming());
    // For every connection, we must make a `Service` to handle all
    // incoming HTTP requests on said connection.
    let make_svc = make_service_fn(|_conn| {

        async { Ok::<_, Infallible>(service_fn(hello)) }
    });
    let server_i = Server::builder(acceptor);
    let server = server_i.serve(make_svc);
    
    server.await?;

    Ok(())}

29 |     let acceptor = hyper::server::accept::from_stream(unix_listener.incoming());
   |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `futures::Stream` is not implemented for `future_ex::future_ex::tokio::net::unix::Incoming<'_>`

_Originally posted by @IThawk in https://github.com/hyperium/hyper/issues/2102#issuecomment-574475394_

**Comment by FedericoPonzi** [comment]
Can you please fix the formatting, add your deps with versions and the complete error?

**Comment by IThawk** [comment]
use std::convert::Infallible;

use hyper::service::{make_service_fn, service_fn};
use hyper::{Body, Request, Response, Server};
use std::{fs, io};
use tokio::net::UnixListener;
async fn hello(_: Request<Body>) -> Result<Response<Body>, Infallible> {
    Ok(Response::new(Body::from("Hello World!")))
}

#[tokio::main]
pub async fn run_http_server() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
//    pretty_env_logger::init();

    let path = "/root/test.sock";
    if let Err(err) = fs::remove_file(path) {
        if err.kind() != io::ErrorKind::NotFound {
            eprintln!(".......");
        }
    }
    let unix_listener = UnixListener::bind(path).unwrap();
    let acceptor = hyper::server::accept::from_stream(unix_listener.incoming());
    // For every connection, we must make a `Service` to handle all
    // incoming HTTP requests on said connection.
    let make_svc = make_service_fn(|_conn| {

        async { Ok::<_, Infallible>(service_fn(hello)) }
    });
    let server_i = Server::builder(acceptor);
    let server = server_i.serve(service_fn(hello));

    server.await?;

    Ok(())
}

**Comment by IThawk** [comment]
tikio = "0.2.9"
hyper ="0.13:

**Comment by IThawk** [comment]
error[E0277]: the trait bound `future_ex::future_ex::tokio::net::unix::Incoming<'_>: futures::Stream` is not satisfied
  --> src/hyper_ex/uds_server.rs:26:55
   |
26 |     let acceptor = hyper::server::accept::from_stream(unix_listener.incoming());
   |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `futures::Stream` is not implemented for `future_ex::future_ex::tokio::net::unix::Incoming<'_>`
   | 
  ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/server/accept.rs:82:8

**Comment by njaard** [comment]
@IThawk could it be as simple as that you forgot the feature?

`tokio={ version="*", features=["full"] }`

(little wish: I think tokio should have some more batteries included per default features)
