### ISSUE TITLE
How to print the final set of headers before sending them?

### ISSUE THREAD

**Issue by svenstaro** [hyperium/hyper#2116]
My application has a verbose option that allows it to print the final headers that are about to be sent to the client. Sadly, I can only get a limited set of headers (those that I add myself) but not those added by hyper (such as `content-length`).

```
impl Service<Request<Body>> for Svc {
    type Response = Response<Body>;
    type Error = hyper::Error;
    type Future = future::Ready<Result<Self::Response, Self::Error>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Ok(()).into()
    }

    fn call(&mut self, req: Request<Body>) -> Self::Future {
        let rsp = Response::builder();

        let uri = req.uri();
        if uri.path() != ROOT {
            let body = Body::from(Vec::new());
            let rsp = rsp.status(404).body(body).unwrap();
            return future::ok(rsp);
        }

        let body = Body::from(Vec::from(&b"heyo!"[..]));
        let rsp = rsp.status(200).body(body).unwrap();
        dbg!(&rsp);
        future::ok(rsp)
    }
}
```

Going with the `tower_server.rs` example, I added a `dbg!(&rsp);` to figure out which headers I can actually see and it seems to me that this array doesn't contain the final set of headers. Is there any way I can force hyper to actually show me the final set?

**Comment by seanmonstar** [comment]
hyper doesn't have an option to log the headers just before they are written. I suppose you have a few options:

- Add these headers yourself, if you already know it should use `content-length` or `transfer-encoding`. Then you can log them.
- Use a custom IO type that can log from inside `AsyncWrite::poll_write`.

---

I'm going to close as this isn't a bug in hyper.
