### ISSUE TITLE
How do I properly shut down hyper?

### ISSUE THREAD

**Issue by MaikKlein** [hyperium/hyper#2120]
The documentation shows the following code:
```Rust
// Make a server from the previous examples...
let server = Server::bind(&([127, 0, 0, 1], 3000).into())
    .serve(make_service);

// Prepare some signal for when the server should start shutting down...
let (tx, rx) = tokio::sync::oneshot::channel::<()>();
let graceful = server
    .with_graceful_shutdown(async {
        rx.await.ok();
    });

// Await the `server` receiving the signal...
if let Err(e) = graceful.await {
    eprintln!("server error: {}", e);
}

// And later, trigger the signal by calling `tx.send(())`.
let _ = tx.send(());
```
But what if you want to start a new server on the same port after `let _ = tx.send(());`? How do you make sure that it is actually shut down?

My first thought was be to create a [shared future](https://docs.rs/futures/0.3.1/futures/future/trait.FutureExt.html#method.shared)

```Rust

server.with_graceful_shutdown(shared);
let _ = tx.send(());
block_on(shared);
// Spawn hyper again
```

But that also does not seem 100% correct as I don't think that the completion of the future guarantees that I can bind to `localhost:3000` again.

Is that possible with the current api?

**Comment by seanmonstar** [comment]
Once the future from `Server::with_graceful_shutdown` completes, the listener and all opened connections have closed. So you could wrap the example server code in a loop, to start a new server after the previous one finishes.

(Note, there is usually an OS-level option that determines how long the related port is still considered used.)

**Comment by MaikKlein** [comment]
Thanks
