### ISSUE TITLE
tokio dependency is no longer optional in 0.13.x

### ISSUE THREAD

**Issue by tamird** [hyperium/hyper#2121]
Dependency on h2 was added in https://github.com/hyperium/hyper/commit/c119097fd072db51751b100fa186b6f64785954d, and since h2 depends on tokio non-optionally, hyper now does too.

We'd like to upgrade hyper to 0.13.x in fuchsia, but we'd like to avoid importing tokio.

**Comment by sfackler** [comment]
h2 only pulls in IO traits and synchronization primitives, not the full runtime: `tokio = { version = "0.2", features = ["io-util", "sync"] }`

**Comment by tamird** [comment]
I see that, but when I upgrade to hyper 0.13.1 I do see the tokio runtime get pulled in.

Here's the (relevant part of the) output of `cargo tree`.
```
├── hyper v0.13.1
│   ├── bytes v0.5.4
│   ├── futures-channel v0.3.1 (*)
│   ├── futures-core v0.3.1 (*)
│   ├── futures-util v0.3.1 (*)
│   ├── h2 v0.2.1
│   │   ├── bytes v0.5.4 (*)
│   │   ├── fnv v1.0.6 (*)
│   │   ├── futures-core v0.3.1 (*)
│   │   ├── futures-sink v0.3.1 (*)
│   │   ├── futures-util v0.3.1 (*)
│   │   ├── http v0.2.0
│   │   │   ├── bytes v0.5.4 (*)
│   │   │   ├── fnv v1.0.6 (*)
│   │   │   └── itoa v0.4.3 (*)
│   │   ├── indexmap v1.0.2
│   │   ├── log v0.4.8 (*)
│   │   ├── slab v0.4.2 (*)
│   │   ├── tokio v0.2.11
```

**Comment by tamird** [comment]
Maybe you mean to say that it doesn't link in the runtime, but it result in us having to vendor the code. Is that what you meant?

**Comment by sfackler** [comment]
You see the tokio *crate* pulled in. There are many Cargo features controlling what bits of the crate are actually compiled. h2 itself does not need any of the "main" components of tokio like the `Runtime`. For example, if you depend on hyper with `default-features = false`, tokio does not depend on mio.

**Comment by tamird** [comment]
Understood, thanks.
