### ISSUE TITLE
Return ownership of the Request on failure

### ISSUE THREAD

**Issue by jean-airoldie** [hyperium/hyper#2129]
## Use case
Currently `Client::request` takes ownership of the request. This can be a problem if the request fails for some reason not caused by the user code and has to be retried. Currently the user has to manually recreate the request and retry.

### Make Request impl Clone if Body: Clone
This works but adds constant overhead. Also works better than `reqwest::Request::try_clone` because we know if the request is clonable at compile time.

### Return ownership of the `Request` on failure
It would work with no additional overhead. It might even be possible to return the collected `Body` if it is a stream (assuming that the stream is kept in its entirety).

### Allow passing a `Arc<Request<B>>`
This would also work from the user's perspective at a small overhead cost. However this wouldn't work properly if the `Body` is a stream.

From the API's side, I'm thinking of something like this:

```rust
enum RequestKind<T> {
  Owned(Request<T>),
  Shared(Arc<Request<T>>),
}
```

```rust
pub fn request(&self, req: T) -> ResponseFuture where T: Into<RequestKind<B>> { ... }

impl<T> From<Request<T>> for RequestKind { ... }
impl<T> From<Arc<Request<T>>> for RequestKind { ... }
```

**Comment by seanmonstar** [comment]
It would be a lot of work to *try* to return the `Request` on failure. I'd recommend trying something like [`tower::retry`](https://docs.rs/tower/0.3.*/tower/retry/index.html) for structured request retries.

**Comment by akashgurava** [comment]
tower::retry::Policy needs a clone_request function for retry. Which is not possible currently

**Comment by vsuharnikov** [comment]
@akashgurava I had the same issue. So I pass a function that creates a request instead of cloning, e.g.:
```rust
pub async fn run_repeatable<ResponseT: DeserializeOwned, MkRequestFn>(&self, mk_req: MkRequestFn) -> hyper::Result<ResponseT>
  where MkRequestFn: Fn() -> hyper::Request<hyper::Body> {
```
Not ideal, but works.
