### ISSUE TITLE
Website: add "edit on Github" badge to guides pages

### ISSUE THREAD

**Issue by UmerMIB** [hyperium/hyper#2131]
I would like to contribute by adding some  documentation written on the website but didn't find any way how to achieve it . It would be more convenient if a feature add like this  
![Screenshot from 2020-02-13 22-34-51](https://user-images.githubusercontent.com/47888725/74462095-6c37de00-4eb1-11ea-9247-28ad2f03a2d1.png)

**Comment by seanmonstar** [comment]
The website source is available at https://github.com/hyperium/hyperium.github.io/

Adding a badge to each guide page might be nice, similar to how [Tokio](https://tokio.rs/docs/getting-started/hello-world/) does it.

**Comment by polybuildr** [comment]
I've just submitted a PR to add a simple text link for this in the footer. Let me know what you think! Happy to make changes to improve this basic attempt.
