### ISSUE TITLE
Lack of case sensitive headers prevent using hyper for porting

### ISSUE THREAD

**Issue by DenisKolodin** [hyperium/hyper#2133]
I know this topic discussed many times, but... there is a real world case when case sensitive headers really needed 😢 

We are porting a microservice to rust+hyper that handles tons of customers, but we can't release it, because our legacy version had some headers with mixed/title cases. If we will change all headers to lowercase it will broke a lot of customers' code that can be not so reliable and can use like case-sensitive 'grep's to extract headers from the output. We produce quite delicate information and can't release breaking changes.

Add a patch to proxies/balancers to patch headers looks not so good.

Is it possible to use mixed headers on servers without patching the code of the crate?

Thanks for your help!

**Comment by seanmonstar** [comment]
I'm sorry this is causing you problems. The points from the previous discussions are still valid, and that's where I still stand. Perhaps you can do as AWS did, which was to introduce a new version with fancy new features, and include the change there, so clients are incentivized to upgrade.
