### ISSUE TITLE
How do I catch "connection error"?

### ISSUE THREAD

**Issue by m9xiuz** [hyperium/hyper#2134]
I need to catch [this error](https://github.com/hyperium/hyper/blob/0eaf304644a396895a4ce1f0146e596640bb666a/src/server/conn.rs#L891) because I need to free some resources when a client (e.g. a web browser) closes an event stream (which I create using `Response::new(Body::wrap_stream(stream))`), but I don't see how to do it.
I get the following error:
```
DEBUG hyper::server::conn::spawn_all > connection error: connection error: An existing connection was forcibly closed by the remote host. (os error 10054)
```
Could you help me please?

**Comment by seanmonstar** [comment]
Does the `stream` you pass to `wrap_stream` not own resources? If it does, it should be able to clean up automatically when the stream is dropped once the connection errors.

Or do you really really specifically need to obverse that connection error case?

**Comment by m9xiuz** [comment]
I create a channel and form the stream from its `rx` half whereas its `tx` half I add to `subscriptions: Arc<Mutex<HashMap<Id, ...>>>`. When "connection error" happens, I still have the key value pair in the hash map and I would like to remove it at that moment.

Currently, I use a workaround. I run a task that every n seconds removes all closed subscriptions (I check if [`tx` is closed](https://docs.rs/futures/0.3.4/futures/channel/mpsc/struct.UnboundedSender.html#method.is_closed).) But I don't like this solution.

**Comment by seanmonstar** [comment]
You can create a new type that wraps your `stream` and removes the sender half on `Drop`. Something like:

```rust
struct YourStream {
    rx: Receiver,
    subscriptions: Weak<Mutex<HashMap<..>>>,
}

impl Stream for YourStream {
    // ..
}

impl Drop for YourStream {
    fn drop(&mut self) {
        // try to remove from `self.subscriptions`
    }
}
```

**Comment by m9xiuz** [comment]
It works. The idea to implement `Drop` for my own stream struct didn't come to my mind. Thank you.
