### ISSUE TITLE
thread 'async-std/executor' panicked at 'Receiver::next_message called after `None`', src/libcore/option.rs:1188:5

### ISSUE THREAD

**Issue by dgollub** [hyperium/hyper#2141]
## Description
I am using [roa](https://github.com/Hexilee/roa) (master branch), which in turn uses hyper.

I run into the following [issue](https://github.com/Hexilee/roa/issues/1#issuecomment-591143582) (copy pasting it here for easier access):

------
> I used Chrome and the assets/index.html file on the http://localhost:8000/ endpoint provided in this example and uploaded a simple PNG file.
> In both cases I run into a crash/error when this line is reached:
```
io::copy(&mut field.into_async_read(), &mut file).await?
```
> The error is
```
 Finished dev [unoptimized + debuginfo] target(s) in 1m 37s
     Running `/Users/dkg/projects/others/roa/target/debug/multipart-example`
 INFO  multipart_example > Server is listening on 127.0.0.1:8000
 INFO  roa::logger       > --> GET /
 INFO  roa::logger       > <-- GET / 1ms 240 B 200 OK
 INFO  roa::logger       > --> POST /file
 INFO  multipart_example > image/png
thread 'async-std/executor' panicked at 'Receiver::next_message called after `None`', src/libcore/option.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Abort trap: 6
```
> I am on macOS 10.14.6 (18G1012) and my Rust compiler is rustc 1.41.0 (5e1a79984 2020-01-27).
------

You can find the full [stacktrace uploaded](https://github.com/Hexilee/roa/issues/1#issuecomment-591262813) there as well. 

Roa uses hyper version [0.13](https://github.com/Hexilee/roa/blob/master/Cargo.toml#L38).

The author of roa, Hexilee, thinks it may be a bug on [this line](https://github.com/hyperium/hyper/blob/master/src/body/body.rs#L267) in the hyper code. 

I do not know enough Rust nor hyper yet to confirm this. So any help would be appreciated.

## Steps to reproduce the bug

1. `git clone https://github.com/Hexilee/roa.git`
2. `RUST_BACKTRACE=full RUST_LOG=info cargo run`
3. Open `http://localhost:8000/` in Chrome or FF or $BROWSER
4. Upload a file with the form that is displayed in your $BROWSER
5. Witness crash

I hope someone can let me know why this happens and whether or not this really is a bug with hyper or some other library.

Thank you.

**Comment by seanmonstar** [comment]
That panic is coming from within `futures_channel::mpsc::Receiver::poll_next`, which `hyper::Body` is calling internally. It's claiming that the `Stream` was polled again after returning that it finished (returned `None`).

However, hyper doesn't do any extra calling of that method, it forwards its `Stream::poll_next` inward, so I'd say the error is that something using `hyper::Body` is polling it again after receiving `None`.

**Comment by dgollub** [comment]
Thanks for looking into it. Sorry for the delayed response. The roa author mentioned something similar. So it is a bug in roa it seems.
