### ISSUE TITLE
Attaching meta data to a Connection

### ISSUE THREAD

**Issue by jeromegn** [hyperium/hyper#2150]
We implement a custom `Connect` (well `tower::Service`) in our proxy and I'm trying to figure out if it's possible to carry information from the established connection to the `Response`?

Our use case is: We load balance connections from the `Connect` implementation. The chosen backend has a unique identifier which we use as labels for our metrics. I can't record our "http response time" metric labeled with this backend identifier.

Is it currently possible to attach meta data? If not, is there a way to work around this?

**Comment by sfackler** [comment]
https://docs.rs/hyper/0.13.3/hyper/client/connect/struct.Connected.html#method.extra

**Comment by jeromegn** [comment]
@sfackler Thanks, I looked for it, but probably with the wrong keywords.
