### ISSUE TITLE
Hyper client and async-std

### ISSUE THREAD

**Issue by bugproof** [hyperium/hyper#2156]
Tried this but I get:

> thread 'main' panicked at 'not currently running on the Tokio runtime.'

```rust
#[async_std::main]
async fn main() {
    let client = hyper::Client::new();
    let response = client.get(Uri::from_static("https://google.com/")).await;
    println!("{}", response.unwrap().status());
}
```

Is tokio required for hyper to work?

https://hyper.rs/guides/client/basic/

> We have to setup some sort of runtime. By default, hyper can make use of the Tokio runtime.

**Comment by seanmonstar** [comment]
As stated, by default hyper assumes the Tokio runtime is used. You can disable the default features, and provide your own [connector](https://docs.rs/hyper/0.13.*/hyper/client/struct.Builder.html#method.build) for the Client.
