### ISSUE TITLE
test failure in body::body::tests::test_size_of on 32bit architectures

### ISSUE THREAD

**Issue by decathorpe** [hyperium/hyper#2158]
When running the unit tests on fedora, I'm getting the following error on i686:

```
failures:
---- body::body::tests::test_size_of stdout ----
thread 'body::body::tests::test_size_of' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `28`: Body', src/body/body.rs:568:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    body::body::tests::test_size_of
test result: FAILED. 75 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
```

And the following error on armv7hl:

```
test proto::h1::decode::tests::test_read_chunked_async ... ok
failures:
---- body::body::tests::test_size_of stdout ----
thread 'body::body::tests::test_size_of' panicked at 'assertion failed: `(left == right)`
  left: `40`,
 right: `28`: Body', src/body/body.rs:568:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    body::body::tests::test_size_of
test result: FAILED. 75 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
```

Looking at the source for the failing test:

https://github.com/hyperium/hyper/blob/master/src/body/body.rs#L565-L572

It looks like the test is relying on the specific value of `usize`, which is architecture dependent. From the Rust docs:

> The size of this primitive is how many bytes it takes to reference any location in memory. For example, on a 32 bit target, this is 4 bytes and on a 64 bit target, this is 8 bytes.

See: https://doc.rust-lang.org/std/primitive.usize.html

**Comment by seanmonstar** [comment]
I was assuming that all the pointers and variants would be the same size as `usize`, but it's apparently a little more complex than that.

Really, the test is mostly to catch growing the size of `Body` too big unexpectedly, so it should probably just be changed to a less-than, and `u64`s should be used on the right-hand side...

**Comment by decathorpe** [comment]
> I was assuming that all the pointers and variants would be the same size as `usize`, but it's apparently a little more complex than that.
>
> Really, the test is mostly to catch growing the size of `Body` too big unexpectedly, so it should probably just be changed to a less-than, and `u64`s should be used on the right-hand side...

I assumed as much (there's even a helpful comment in the test!), and I think we can just skip this test for now. But I wanted you to be aware that there's architecture-dependent test failures here, even if they're not fatal :)
