### ISSUE TITLE
Rate-limiting support?

### ISSUE THREAD

**Issue by nabijaczleweli** [hyperium/hyper#2163]
During research for an issue I got on http, I found exactly one non-root rate-limiting solution in the form of trickle, (which doesn't work because we fork) for POSIX, and none for Win32, so I'm opening this issue to see if this is something you think makes sense implementing here.

Downstream issue: https://github.com/thecoshman/http/issues/102

**Comment by LucioFranco** [comment]
You most likely want to go through something like `tower-limit`.

**Comment by nabijaczleweli** [comment]
AFAICT, the `tower-limit` crate seems to deal in limiting the amount of concurrent threads, as opposed to bandwidth?

**Comment by seanmonstar** [comment]
Most often in the context of HTTP, rate-limiting refers to the number of requests.

You wish to limit the speed that bytes are written, or read? Bodies in hyper are streamed, so you have control over read or writing when you want.

**Comment by thecoshman** [comment]
Yes, we are looking a way to restrict the bandwidth

**Comment by nabijaczleweli** [comment]
This should've been opened against iron, since that's our direct upstream and the hyper version they target is wildly outdated anyway. Closing, and apologies for the noise.
