### ISSUE TITLE
example of stream response

### ISSUE THREAD

**Issue by keepsimple1** [hyperium/hyper#2166]
Is there a good example of streaming response from http server using Hyper?

In my particular case, upon the client's request,  the server would read a big file, decrypt it chunk by chunk and return the plain data back to the client. What is the best practice or pattern of doing that in Hyper?

I've posted [this](https://stackoverflow.com/questions/60876434/how-to-create-stream-when-reading-a-file-in-rust) with code details but wanted to also ask here if it's okay.

**Comment by rousan** [comment]
It is possible via [Body::channel()](https://docs.rs/hyper/0.13.4/hyper/struct.Body.html#method.channel) method and [Bytes](https://docs.rs/bytes/0.5.4/bytes/struct.Bytes.html#impl-From%3CBytesMut%3E) struct, but you have to create `Bytes` for every chunk to be written to channel and it requires a lot of memory allocation/deallocation, unfortunately, there is no way to send a byte slice `&[u8]` and reuse a buffer instead of allocation/deallocation.

@alex @seanmonstar, Any other way to write a large file in a stream way instead of loading the whole file in a buffer, I am also stuck at this situation?

**Comment by keepsimple1** [comment]
Now I understand more about `Stream` and have implemented the stream for this case. It is basically like this: 

```
pub struct DecryptFileStream {
    f: File,
<other_fields>,
}

impl Stream for DecryptFileStream {
    type Item = io::Result<Vec<u8>>;

    fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<io::Result<Vec<u8>>>> {
    <business_logic> 
    if decrypted.len() > 0 {
         Poll::Ready(Some(Ok(decrypted)))
    } else {
         Poll::Ready(None)
    }
}
}

//. then use the above stream: 

            let stream = DecryptFileStream::new(...);
            Response::new(Body::wrap_stream(stream))

```

**Comment by rousan** [comment]
Check it out, it might help you:
https://github.com/rousan/stream-body

**Comment by nickkuk** [comment]
@keepsimple1, @rousan, [bytes](https://crates.io/crates/bytes) crate was initially developed to minimize memory allocations. The only magical method is [BytesMut::reserve](https://docs.rs/bytes/0.5.4/bytes/struct.BytesMut.html#method.reserve) which reuses the same buffer if all other handles have been dropped.

[tokio](https://crates.io/crates/tokio) framework already have helpers that do conversion AsyncRead -> Stream in [tokio-util](https://crates.io/crates/tokio-util) crate. See an example [here](https://docs.rs/tokio-util/0.3.1/tokio_util/codec/struct.BytesCodec.html).

Here is my attempt to test that buffer is reused: [link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8206e10c03cdd2a1b9b537718f057802).

**Comment by keepsimple1** [comment]
thanks @nickkuk . I'm not ready to use AsyncRead yet, so I was not able to use Stream from `tokio` directly. And it turns out that implementing Stream trait for my own struct is not that bad.

**Comment by nickkuk** [comment]
[send_file example](https://github.com/hyperium/hyper/blob/203621e3be6b0dab6b79d1914482c556075a19ff/examples/send_file.rs) was updated with suggested approach.

**Comment by rousan** [comment]
@nickkuk,

> send_file example was updated with suggested approach.
 in this example, does the `FramedRead` re-uses a `Bytes` instance on every data chunk? or it creates one `Bytes` instance for each data chunk, if so, isn't it inefficient in terms of memory?

**Comment by seanmonstar** [comment]
The `FramedRead` re-uses a `BytesMut`, which will use the same buffer if possible.

**Comment by alshdavid** [comment]
I have tried to generalize the stream to support both `"Content-Type", "text/event-stream"` and "Content-Transfer-Encoding", "chunked"`:

Not 100% but essentially this:

```rust
let (writer, reader) = tokio::io::duplex(512);

let reader_stream = tokio_util::io::ReaderStream::new(reader)
  .map_ok(hyper::body::Frame::data)
  .map_err(|_item| panic!());

let stream_body = StreamBody::new(reader_stream);

let boxed_body = BoxBody::<HyperBytes, Infallible>::new(stream_body);

let res: http::Response<BoxBody<HyperBytes, Infallible>> = res.body(boxed_body)?;

tokio::task::spawn(async move {
  while let Some(bytes) = rx_bytes.recv().await {
    if writer.write_all(bytes).await.is_err() {
      break;
    }
  }
});

return Ok(res);
```

It doesn't matter if within the async task I obtain bytes from a channel or `File::open` - the performance is worse than the equivalent code in Nodejs or Golang. I'm puzzled as to why that's the case
