### ISSUE TITLE
`hyper::body::aggregate(body)` hangs forever

### ISSUE THREAD

**Issue by m9xiuz** [hyperium/hyper#2167]
`hyper::body::aggregate(body)` hangs forever if `content-length` value is greater than the actual length of the payload.

Please forgive me if it's not a bug and it should work that way.

**Comment by sfackler** [comment]
The value of the content-length header is by definition the actual length of the payload.

**Comment by m9xiuz** [comment]
I mean I can send "wrong" content-length, e.g.:
`curl -i -XPATCH http://localhost:3030/asdf -H 'content-length: 144' -d '{"test":123}'`
and then it hangs in aggregate.

**Comment by m9xiuz** [comment]
Sorry, it's probably how it should work, it's waiting for the rest of the data, but nothing is coming, so it hangs.
I shouldn't create this issue.
