### ISSUE TITLE
Release a security advisory for RUSTSEC-2020-0008

### ISSUE THREAD

**Issue by Demi-Marie** [hyperium/hyper#2173]
This request smuggling vulnerability was fixed in [0.12.34](https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v01234-2019-09-04).  I did not find the bug, but I did discover the security implications of it and requested the RUSTSEC advisories.

**Comment by LucioFranco** [comment]
I am not quite sure what you are asking here but from what I can tell there is a security advisory? https://rustsec.org/advisories/RUSTSEC-2020-0008.html

**Comment by DemiMarie-parity** [comment]
> I am not quite sure what you are asking here but from what I can tell there is a security advisory? https://rustsec.org/advisories/RUSTSEC-2020-0008.html

I meant a GitHub advisory so a CVE can be assigned.

**Comment by seanmonstar** [comment]
It looks like there is already an advisory in RustSec. So I'm going to close here.
