### ISSUE TITLE
[Question] How to access the Connection object

### ISSUE THREAD

**Issue by sapessi** [hyperium/hyper#2179]
I'm trying to build an HTTP proxy that can act as a man-in-the-middle for HTTPS connections as an exercise. I found [this example](https://github.com/nlevitt/monie/blob/master/Cargo.toml#L23-L24) but it relies on a modified version of hyper that makes the `connection_for` method of `Client` public. I would like to use the latest version of hyper without modifications. So far as I can tell, the `Connect` trait on the `HttpsConnector` is what I need to handle the Upgrade request of the CONNECT method ([as they do here](https://github.com/nlevitt/monie/blob/master/src/lib.rs#L166)). However, the `Connect` trait is public but requires an `Internal` struct that is not. What am I missing?

```rust
HttpsConnector::new().connect(Internal, uri)
```

If this is not possible, I guess the feature request would be to make a version of the `connection_for` method public along with the `PoolClient`.

**Comment by seanmonstar** [comment]
Let's zoom out slightly. You just want to make a connection? You could use `TcpStream::connect`. Or do you specifically want to use `HttpsConnector`? In that case, it implements `Service<Uri>`.

**Comment by sapessi** [comment]
I want to use the `HttpsConnector`. I know I will proxy to AWS endpoints so they will always be HTTPS.

**Comment by seanmonstar** [comment]
```rust
use hyper::service::Service;

let result = https_connector.call(Uri::from_static("https://example.local")).await;
```

**Comment by sapessi** [comment]
Think I'm with you, thank you! That call will return the connection stream and I can catch the upgrade on it. I'll go back to the gitter chat if I get badly stuck again. If I get this to a decent state and you don't mind I may send a PR to add it as an https proxy example.
