### ISSUE TITLE
async stream body to file

### ISSUE THREAD

**Issue by danjenson** [hyperium/hyper#2190]
I've asked in rust discord and googled for the last day to figure out how to stream from a `hyper::body::Body` to a file using `tokio::io::AsyncWriteExt` or `tokio::io::{AsyncRead,AsyncWrite}`, but no one can seem to provide an answer because code snippets like this prevent converting from a `std::io::Error` to a `hyper::error::Error` in 0.13.5:

```
req.into_body().try_fold(file, |file, chunk| async move {
    file.write_all(chunk.as_ref()).await.map(|_| file)
});
```
I also couldn't find any examples in the documentation. Is there a simple way to async stream a `hyper::body::Body` to a file?

**Comment by nickkuk** [comment]
You can create combined error type, e.g.:
```rust
use tokio::{io::AsyncWriteExt, stream::StreamExt};

enum Error {
  FileError(std::io::Error),
  NetError(hyper::Error),
}

async fn body_to_file(mut body: hyper::Body, mut file: tokio::fs::File) -> Result<(), Error> {
  while let Some(chunk) = body.next().await {
    let chunk = chunk.map_err(Error::NetError)?;
    file.write_all(&chunk).await.map_err(Error::FileError)?;
  }
  Ok(())
}
```
Also you can derive `std::error::Error` trait for `Error` type by using e.g. [thiserror](https://crates.io/crates/thiserror) crate.

**Comment by danjenson** [comment]
awesome thanks!
