### ISSUE TITLE
Merged cookies break python

### ISSUE THREAD

**Issue by mrkurt** [hyperium/hyper#2196]
We're using Hyper to proxy http2 -> http1.1, and the way it combines cookies breaks for Python apps. The built in Python cookie parser splits multiple cookie values on `, ` (note the space), while Hyper combines them with just a `,` and no space. Hyper isn't _wrong_ to do this, but the Python devs are being obstinate and it seems like an easy-ish workaround to just add the space in Hyper. 

Stupid Python bug: https://bugs.python.org/issue23930

**Comment by seanmonstar** [comment]
What do you mean by merging cookies? How are you doing that?

**Comment by mrkurt** [comment]
We're not intentionally merging cookies. We're just taking a request from an HTTP server and handing it off as a request to the HTTP client, we do add some headers but don't touch cookies.

**Comment by seanmonstar** [comment]
Hm, could you share a little more what code you are using? Because in hyper itself, headers aren't merged either when parsing or when serializing.

**Comment by seanmonstar** [comment]
I don't *think* this is happening inside hyper. I've search through the HTTP/1 and HTTP/2 parts internally, and I don't see any values being concatenated together. If you have more details, we can re-open.
