### ISSUE TITLE
When SETTINGS_MAX_CONCURRENT_STREAMS is hit, should the client pool establish a new connection?

### ISSUE THREAD

**Issue by nerdrew** [hyperium/hyper#2197]
I _think_ I'm hitting an issue where I can only have 128 aws lambda requests in parallel per lambda client (and hence per hyper client). Pure speculation: if lambda only allows 128 streams per connection, I think I'd see only 128 requests in flight, even if more requests are sent. If this is true, should the hyper client establish a new connection when the stream max is hit?

Related to https://github.com/rusoto/rusoto/issues/1738.

Also looks like it might be similar to: https://github.com/golang/go/issues/27044

**Comment by seanmonstar** [comment]
My understanding from reading the spec that a client *should not* open new connections to get around a max concurrency setting.

[See here](https://httpwg.org/specs/rfc7540.html#rfc.section.9.1):

> Clients SHOULD NOT open more than one HTTP/2 connection to a given host and port pair [..]

**Comment by nerdrew** [comment]
That seems pretty clear :). Though, my case is the same as the linked go issue with an AWS load balancer. The stream limit is weird when connecting to a load balancer or proxy. It seems like it should be fine to open another connection then...

Is there a way to disable http2 for a hyper client? I don't see anything obvious in the builder.

**Comment by seanmonstar** [comment]
Sorry, just saw the last question: the `Client` will only use HTTP/2 if either a) you enable `http2_only(true)`, or b) your `Connector` negotiates via ALPN to use `h2`.
