### ISSUE TITLE
Pending at `Acceptor`

### ISSUE THREAD

**Issue by daxpedda** [hyperium/hyper#2200]
I found some time today to revisit https://github.com/seanmonstar/warp/pull/431 and finally think I understood the issue.

<details><summary>SSCCE:</summary>

```rust
use futures::ready;
use hyper::{
    server::{
        accept::Accept,
        conn::{AddrIncoming, AddrStream},
    },
    service::{make_service_fn, service_fn},
    Body, Response, Server,
};
use std::{
    io::Error,
    net::SocketAddr,
    pin::Pin,
    str::FromStr,
    task::{Context, Poll},
};

#[tokio::main]
async fn main() {
    let incoming = Acceptor::new(
        AddrIncoming::bind(&SocketAddr::from_str("127.0.0.1:8000").unwrap()).unwrap(),
    );

    let make_svc = make_service_fn(|_| async {
        Ok::<_, Error>(service_fn(|_| async {
            Ok::<_, Error>(Response::new(Body::from("Hello World")))
        }))
    });

    Server::builder(incoming).serve(make_svc).await.unwrap();
}

struct Acceptor {
    incoming: AddrIncoming,
    pended: bool,
}

impl Acceptor {
    fn new(incoming: AddrIncoming) -> Self {
        Self {
            incoming,
            pended: false,
        }
    }
}

impl Accept for Acceptor {
    type Conn = AddrStream;
    type Error = Error;

    fn poll_accept(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Option<Result<Self::Conn, Self::Error>>> {
        let pin = self.get_mut();
        if pin.pended {
            println!("already pended!");
            match ready!(Pin::new(&mut pin.incoming).poll_accept(cx)) {
                Some(Ok(sock)) => Poll::Ready(Some(Ok(sock))),
                Some(Err(e)) => Poll::Ready(Some(Err(e))),
                None => Poll::Ready(None),
            }
        } else {
            println!("pended once!");
            pin.pended = true;
            Poll::Pending
        }
    }
}

```

</details>

So as far as I understood, returning `Poll::Pending` from `Accept::poll_accept` isn't handled or I'm not handling it properly.

**Comment by sfackler** [comment]
The acceptor is responsible for arranging for its task to be woken (via Context::waker) at the appropriate time.

**Comment by daxpedda** [comment]
Alright, so if I understand correctly, the issue I was having in https://github.com/seanmonstar/warp/pull/431 was because `poll_peek` doesn't arrange the task to be awoken?

**Comment by sfackler** [comment]
The issue in your example above is that the else branch does not arrange the task to be awoken.

**Comment by daxpedda** [comment]
Thank you so much.

To explain the context I was referring to:
```rust
fn poll_accept(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Option<Result<Self::Conn, Self::Error>>> {
        let pin = self.get_mut();
        match ready!(Pin::new(&mut pin.incoming).poll_accept(cx)) {
            Some(Ok(mut sock)) => {
                let mut byte = [0];
                // `poll_peek` doesn't arrange the task to be awoken again
                // therefore on `Poll::Pending` this will never awaken again
                ready!(sock.poll_peek(cx, &mut byte))?;
                Poll::Ready(Some(Ok(sock)))
            }
            Some(Err(e)) => Poll::Ready(Some(Err(e))),
            None => Poll::Ready(None),
        }
    }
```

So basically my question is how do I arrange the task to be awoken properly when trying to use `poll_peek`. I was looking through the code and found this: https://docs.rs/tokio/0.2.20/src/tokio/net/tcp/stream.rs.html#270-289.
Which tells me that `poll_peek` should work appropriately.
So unless I did something else wrong up there, there is some bug in tokio/mio that prevents this example from working?

I will close this because it seems there is no issue with hyper and this has become a "help me" thread instead.

**Comment by sfackler** [comment]
If the socket does not immediately have a byte available to peek, that code throws it away and tries to accept a new connection.

**Comment by daxpedda** [comment]
Thanks.
I think I finally narrowed it down.

In https://github.com/seanmonstar/warp/pull/431 I fixed the problem of not throwing away the socket and trying to accept a new connection, but the problem was when the client would come back with a HTTPS connection I already gave away the socket to handle the upgrade.

So I guess this PR is gonna have to involve some more work.

Thank you so much again.
