### ISSUE TITLE
how to share stuct based data using hyper?

### ISSUE THREAD

**Issue by aohan237** [hyperium/hyper#2203]
in the example state.rs, there is a simple exmaple for sharing usize data.

but how to share a struct data.
`
struct example { name: String}
`
like this.

if using make_service_fn ,  any borrow or Arc will have lifetime issue or move or mut issue?

so what's the solution for sharing state in hyper?

**Comment by seanmonstar** [comment]
That depends on your needs. As the `state.rs` example shows, you can put the value inside an `Arc` so multiple connections can reference the same value.

**Comment by aohan237** [comment]
@seanmonstar  i tried. 
for example. 
```rust
handler(test:Arc<Test>,req:Request<Body>) -> Result<Response<Body>>{}
struct Test { name: String}
let test1 = Test {name:"test".to_string()}
let test2 = Arc::new(test1);
    let make_service = make_service_fn(move |_| {
        let test3= test2.clone();
        async move {
            Ok::<_, Error>(service_fn(move |_req| {
                async move { Ok::<_, Error>(handler(test,req)) }
            }))
        }
    });
```

this will have clone life time issue

**Comment by aohan237** [comment]
using #[tokio::main] and async/await

**Comment by aohan237** [comment]
@seanmonstar   can you kindly show me a sample code as for Arc<Struc>?

**Comment by aohan237** [comment]
the rustc said that i have clone life time issue.

but when i get some new code, and the more errors come out, after i fix these errors.

the life time issue is gone.

maybe the cargo check is not that trustable.  

mark it for anyone else , who encounter wired problems
