### ISSUE TITLE
net2 has been deprecated, use socket2 instead

### ISSUE THREAD

**Issue by Shadow53** [hyperium/hyper#2205]
A GitHub action using RUSTSEC recently created an issue with the above description on a project I work on, and I thought I would inform the dependencies that use `net2`. Here's a link to the [related advisory](https://rustsec.org/advisories/RUSTSEC-2020-0016.html).

**Comment by seanmonstar** [comment]
We can certainly upgrade (I don't quite understand why it's that relevant to rust-sec :shrug:).

**Comment by Shadow53** [comment]
I'm not very familiar with rust-sec, but maybe the authors requested it because it's fairly commonly used? :man_shrugging: Glad you're aware of the deprecation, though.

**Comment by jyn514** [comment]
I can help work on this.
