### ISSUE TITLE
Outdated IRC info in Readme

### ISSUE THREAD

**Issue by atouchet** [hyperium/hyper#2218]
> There are two main avenues for real-time chatting about hyper: a Gitter room and irc.mozilla.org/hyper. They are mirrored, so choose whichever format you prefer.

Mozilla IRC is no longer and clicking that IRC link returns "We couldn't connect to that server :( Unknown domain name or host". I assume this section of the Readme is out of date.

**Comment by seanmonstar** [comment]
I updated the README with Discord links in #2243.
