### ISSUE TITLE
The HTTP proxy example doesn't work.

### ISSUE THREAD

**Issue by Jason5Lee** [hyperium/hyper#2224]
When I run the that example and try to `all_proxy=127.0.0.1:8080 curl https://www.domain.com/` , it outputs `curl: (56) Received HTTP code 400 from proxy after CONNECT` , and the proxy server logs `CONNECT host is not socket addr: www.domain.com:443`

**Comment by anderson916** [comment]
Same here. 

`
curl -i https://www.google.com
HTTP/1.1 400 Bad Request
content-length: 35
date: Fri, 19 Jun 2020 01:39:49 GMT

curl: (56) Received HTTP code 400 from proxy after CONNECT
`
http proxy stdout:

`
req: Request { method: CONNECT, uri: www.google.com:443, version: HTTP/1.1, headers: {"host": "www.google.com:443", "user-agent": "curl/7.64.1", "proxy-connection": "Keep-Alive"}, body: Body(Empty) }
CONNECT host is not socket addr: www.google.com:443
`

**Comment by seanmonstar** [comment]
The error message gives a hint: this simple proxy requires the `host` header to be a socket address.

**Comment by shirshak55** [comment]
You can use trust dns or std library socket addr or Hyper GaiResolver too?
