### ISSUE TITLE
Export request and response with default type parameter

### ISSUE THREAD

**Issue by Austaras** [hyperium/hyper#2230]
Basically title, it makes sense to export a new request and response type like
``` rust
type Response<T = Body> = HttpResponse
```
since hyper already provide Body

**Comment by seanmonstar** [comment]
I get what you mean, it could be useful. But I also don't know a good name, and it's only useful in default cases. It's probably also not too much to ask users to make their own type alias in their projects when they decide what kind of body to use...

**Comment by Austaras** [comment]
Yes I am currently using one so I'm wondering if there's any reason not to use. Also since they are essentially the same I just
``` rust
use hype::Response as HttpResponse;
pub type Response<T = Body> = HttpResponse
```
I'm quite new to rust so I don't if there is any circumstance this new type will break compilation, if not, maybe just call it Response is enough

**Comment by seanmonstar** [comment]
Yea that should work for your app just fine.

I don't think there's anything actionable here for hyper, though. We can't provide a good name directly, seeing two types in the docs may be confusing, and it's easy for an app to do this themselves.
