### ISSUE TITLE
Body::wrap_stream question

### ISSUE THREAD

**Issue by gterzian** [hyperium/hyper#2232]
https://docs.rs/hyper/0.13.6/hyper/struct.Body.html#method.wrap_stream

I'm wondering if this API requires a bit more documentation in terms of how this affects the underlying networking, and also regarding the requirements on the stream. 

I tried using this in Servo to support streaming uploads(using this as the body of a request), and this didn't seem to work, although I don't know if it's the server that didn't like the request or if I did something wrong using the API.

I noticed the following output from the server:

```
 0:04.54 INFO STDERR: 127.0.0.1 - - [13/Jun/2020 18:22:08] code 400, message Bad request syntax ('4')
 0:04.54 INFO STDERR: 127.0.0.1 - - [13/Jun/2020 18:22:08] "4" 400 -
```

When sending a request whose body would be the string "Test". 

So I'm guessing this actually matches the concept of https://en.wikipedia.org/wiki/Chunked_transfer_encoding#Encoded_data, where the `4` is the first line indicating that the chunk is of size 4?

I have to say that I did end-up setting the "Transfer-encoding" chunked header, although I think I was seeing this error even before, which would seem to indicate that Hyper itself switches to that protocol when using a `Stream` as a request body? If so, I think it is worth documenting in more details. 

Also, are there any requirements on how to use the corresponding `Sink`, for example the need to gracefully close it and so on?

**Comment by seanmonstar** [comment]
If the body's `size_hint` method does not return an exact size, the hyper will check if you've included a specific header to describe the body. If that doesn't exist either, hyper will resort to a streaming body, which over HTTP/1.1, will use chunked transfer-encoding. It *should* automatically add the header.

**Comment by gterzian** [comment]
thanks for the info!
