### ISSUE TITLE
hyper::client::ResponseFuture to String or Bytes 

### ISSUE THREAD

**Issue by king-etc** [hyperium/hyper#2233]
Hello I've had some problems and I want to get a response to the text
```
let client = Client::new();
let req = Request::builder()
        .method("POST")
        .uri("http://127.0.0.1:9999/echo")
        .body(Body::from("Hallo!"))
        .expect("request builder");
let future = client.request(req);
```
How to convert future:hyper::client::ResponseFuture  to String or Bytes
Thank u.

**Comment by seanmonstar** [comment]
You need to await the future to get a response, and from there, you can stream the body. The [getting started guide](https://hyper.rs/guides/client/basic/) may help some.

You'd be looking for code like:

```rust
let resp = client.request(req).await?;
let bytes = hyper::body::to_bytes(resp).await?;
```

Since this isn't a bug, I'm going to close this issue.
