### ISSUE TITLE
Support HTTP/2 websocket requests (:protocol header)

### ISSUE THREAD

**Issue by Koxiaet** [hyperium/hyper#2238]
I am trying to support [HTTP/2 websockets](https://tools.ietf.org/html/rfc8441) on my Hyper server but I don't think Hyper supports using the `:protocol` pseudo-header (which is required to implement it). Ideally Hyper would provide a module specifically for HTTP/2 websockets like it does with HTTP/1.1 upgrades.

**Comment by seanmonstar** [comment]
You can't access `req.headers()[":protocol"]`?

**Comment by seanmonstar** [comment]
To answer my own question, `http::HeaderName` considers it illegal, since `:` is not allowed by RFC 7230.

Instead of making that legal, the way forward would probably be to add websocket upgrade support (without the websocket part) to `h2`.

**Comment by Koxiaet** [comment]
[There is already an issue on h2 for this](https://github.com/hyperium/h2/issues/347) so I will close this one.
