### ISSUE TITLE
hyper::client::ResponseFuture is not Sync

### ISSUE THREAD

**Issue by Alexis211** [hyperium/hyper#2240]
Currently, Hyper's `hyper::client::ResponseFuture` type doesn't implement the Sync trait. This is blocking me as I am using the Hyper client library to make RPC calls between instances of my service, inside code that expects futures/async functions to be Sync because it is itself the code of an HTTP service (using Hyper's server module). How come `ResponseFuture` isn't Sync and how hard would it be to make it so? Or do I have another solution?

Thanks.

**Comment by Alexis211** [comment]
Alright so my issue was that I was trying to build a response with `wrap_stream` using a stream that itself did some HTTP calls and thus was not Sync. Just noticed that 0.13.6 fixed `wrap_stream` to accept non-Sync streams so my issue is solved. However, `ResponseFuture` not being Sync might still cause problems for other reasons. Not sure if I should leave this open or not.

**Comment by seanmonstar** [comment]
A future not being `Sync` shouldn't usually be an issue. I'm going to close until some specific case manifests.

**Comment by kdy1** [comment]
@seanmonstar `warp` requires `Send + Sync` for `.boxed()`. Is there a way to make it `Sync` from user side?

**Comment by kdy1** [comment]
Btw, I'm not sure why it is not `Sync` because the field is stored in `SyncWrapper`.
Also, docs.rs says it implements `Sync`.

**Comment by kdy1** [comment]
Nvm, I updated `hyper` and it works.
