### ISSUE TITLE
Service Example doesn't increment the counter

### ISSUE THREAD

**Issue by richardpringle** [hyperium/hyper#2241]
The `service_struct_impl` doesn't actually increment the counter between requests

**Comment by seanmonstar** [comment]
Not sure what you mean, it does right here: https://github.com/hyperium/hyper/blob/8f6d0a2f7ec23882c93a1cc0e1bf40db806f8249/examples/service_struct_impl.rs#L51

Do you mean that the counter isn't shared with other connections? That's true, you'd need change the `usize` into something that shares and synchronizes memory (like an `Arc<AtomicUsize>`).

**Comment by richardpringle** [comment]
Yeah, I meant not shared across connections. For what it's worth, I think the example is a little contrived, I can't do any more than what I can do with https://github.com/hyperium/hyper/blob/master/examples/tower_server.rs and I could just hardcode that counter. 

I'm trying to build a proxy that splits requests based on some body-params but I ended up just using Warp even though it seems like overkill for my use-case (thanks for Warp by the way haha).

**Comment by richardpringle** [comment]
Sorry for the spam... I have my head stuck in vanilla HTTP 1, one connection per request. this example makes a lot more sense now.
