### ISSUE TITLE
Implement `AsRawFd` for `AddrStream` behind feature flag?

### ISSUE THREAD

**Issue by tedsta** [hyperium/hyper#2245]
Hi, I have a use-case where I want to access the file descriptor of a long-lived stream (it becomes a websocket) for monitoring purposes (specifically linux's `send-q` stat, the amount of unacknowledged outbound bytes) - [see here](https://github.com/seanmonstar/warp/issues/428).

Would you be ok with implementing `AsRawFd` for `AddrStream`, maybe behind a feature flag? Or otherwise provide a way to get a `&tokio::net::TcpStream` from a `&AddrStream`? If it helps and you are open to it I can prepare a PR.

**Comment by seanmonstar** [comment]
Seems fair and simple to me (Adding `AsRawFd` support on Linux.)
