### ISSUE TITLE
Mongo CRUD example?

### ISSUE THREAD

**Issue by JimLynchCodes** [hyperium/hyper#2248]
Hello, love the examples here.

Just an idea, a mongo CRUD example would be epic...

Thanks much! ❤

**Comment by seanmonstar** [comment]
Thanks for the suggestion! I think I wouldn't add a Mongo example to repo, just because I don't want to decide on a library and "bless" it from the hyper project.

I do think this could make a cool blog post if you have one, though!

**Comment by JimLynchCodes** [comment]
Cool, I'll start working on it! 👍
