### ISSUE TITLE
Error: method not found in `tokio::task::JoinError`

### ISSUE THREAD

**Issue by JohnMartin95** [hyperium/hyper#2250]
On line 145 of src/client/connect/dns.rs
> if join_err.is_cancelled() {

The minimum tokio version required in the Cargo.toml is 0.2.5 but the `is_cancelled` method was only added to `tokio::task::JoinError` in tokio 0.2.11 leading to potential compile errors.

Fix would be bumping the required tokio version to at least 0.2.11

**Comment by seanmonstar** [comment]
Thanks for reporting! You're right, it'd be a simple fix. Want to submit a PR?

**Comment by JohnMartin95** [comment]
Sure thing!
