### ISSUE TITLE
Add cargo features for http1 and http2

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2251]
It's likely some people only need to support certain protocol versions, and it would be nice if they could reduce the amount of code they have to depend on or compile if they don't need all of them. It likely makes sense to add `http1` and `http2` Cargo features, and the relevant code using those `cfg`s.

- [x] `http1`
- [x] `http2`

**Comment by operutka** [comment]
This would be very useful. I'm working on a REST API for a small embedded device where the amount of flash memory is very limited. According to `cargo bloat`, the HTTP 2 protocol alone is responsible for a lot of code.

**Comment by seanmonstar** [comment]
As I wrap up adding `http1`, the question now arises: what should happen if you don't have any HTTP version enabled?

- **`compile_error!`**: This could be the choice to start, since it's not a breaking change to eventually remove the compile error. However, if we have all features disabled by default, it could be jarring to see the build fail as soon as you add `hyper` and didn't configure any features...
- **An empty crate**: it doesn't break, but it's otherwise not really useful...
- **A shell**: Include the re-exports from `http`, `body`, and `error`. This could allow someone to build support crates using just the core types, without having to enable a specific protocol version.

**Comment by davidbarsky** [comment]
> As I wrap up adding http1, the question now arises: what should happen if you don't have any HTTP version enabled?

My gut feeling is that the "shell crate" option is the best option.

**Comment by xfix** [comment]
I think it would make sense to provide full crate but without functionality to actually construct clients or servers. However, methods like `Client::request` could stay (you cannot create an instance of `Client` anyway).

**Comment by seanmonstar** [comment]
Both `http1` and `http2` features are merged! I'll file a separate issue about making them all default off.
