### ISSUE TITLE
SSL error for *.gitlab.io but not *.github.io

### ISSUE THREAD

**Issue by joshua-maros** [hyperium/hyper#2257]
Rust 1.44, hyper 0.13.7 (using reqwest 0.10.7), running on Ubuntu 19.10.

The URL I am testing is https://code_cube.gitlab.io/audio-bench/index.html, which loads fine in a web browser. Inspecting the certificate with Firefox shows that it is registered for the domain `*.gitlab.io`. Loading it with `reqwest` results in an error due to the domain name not matching the one in the URL.

Code to reproduce:
```rust
// main.rs

fn main() {
    if let Err(err) = reqwest::blocking::get("https://code_cube.gitlab.io/audio-bench/index.html") {
        println!("{:#?}", err);
    }
}
```
```toml
# Cargo.toml

[package]
name = "bug-cert-glob"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["blocking"] }
```

Error it produces:
```rust
reqwest::Error {
    kind: Request,
    url: "https://code_cube.gitlab.io/audio-bench/index.html",
    source: hyper::Error(
        Connect,
        Ssl(
            Error {
                code: ErrorCode(
                    1,
                ),
                cause: Some(
                    Ssl(
                        ErrorStack(
                            [
                                Error {
                                    code: 337047686,
                                    library: "SSL routines",
                                    function: "tls_process_server_certificate",
                                    reason: "certificate verify failed",
                                    file: "../ssl/statem/statem_clnt.c",
                                    line: 1919,
                                },
                            ],
                        ),
                    ),
                ),
            },
            X509VerifyResult {
                code: 62,
                error: "Hostname mismatch",
            },
        ),
    ),
}
```

**Comment by joshua-maros** [comment]
Using `{}` instead of `{:#?}` gives the following error: `error sending request for url (https://code_cube.gitlab.io/audio-bench/index.html): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1919: (Hostname mismatch)`.

A NodeJS project has [experienced the same issue](https://github.com/grpc/grpc-node/issues/663), so maybe it is a problem with a dependency? However, the discussion on the linked issue seems to go back and forth on whether or not wildcards were actually the cause of the problem.

**Comment by joshua-maros** [comment]
My initial guess turned out to be wrong, the site https://square.github.io/ also uses a cert with a wildcard (`*.github.io`) but loading it in the same manner as above does not cause an error. I'm not sure what difference between the two certificates could be causing the problem. I've attached the information Firefox shows for each certificate.
[github.pdf](https://github.com/hyperium/hyper/files/5005010/github.pdf)
[gitlab.pdf](https://github.com/hyperium/hyper/files/5005011/gitlab.pdf)

**Comment by andrewtj** [comment]
It's not the certificate, it's the underscore in the hostname. `reqwest` works okay if you switch to the `rustls` backend, so I guess either the `native-tls` backend isn't being given the correct name or it doesn't handle underscores.

**Comment by joshua-maros** [comment]
Thanks, that workaround works! To be specific, the test code is now:
```rust
fn main() {
    if let Err(err) = reqwest::blocking::ClientBuilder::new()
        .use_rustls_tls()
        .build()
        .unwrap()
        .get("https://code_cube.gitlab.io/audio-bench/index.html")
        .send()
    {
        println!("{}", err);
    }
}
```
And the feature `rustls-tls` is enabled for `reqwest`. I'll open an issue for rust-native-tls.
