### ISSUE TITLE
[Question] How to obtain a mutable response from a request?

### ISSUE THREAD

**Issue by 3NdR1m** [hyperium/hyper#2258]
The `Client` struct have an async method `request(&self, mut req: Request<B>)` that can be used to get a `Response`. However this `Response` instance is not mutable and not clonable, but my app need to edit it's body before proxying it back to a remote client.

What can I do about that?

My code:
```rust
let https = HttpsConnector::new();
let client = Client::builder().build::<_, hyper::Body>(https);
let response: Result<Response<Body>, Error> = client.request(req).await;

match response {
  Ok(r) => {
    // if `r`'s body is HTML, edit it's content
    Ok(r)
  }
  Err(e) => {
    error!("{}", e);
    Ok(Response::new(Body::default()))
}
```

Thanks in advance.

**Comment by seanmonstar** [comment]
You're given ownership of the `Response`, so you can mutate it.

**Comment by 3NdR1m** [comment]
@seanmonstar You're right... After further investigation, turns out my problem was just a forgotten "mut" in a match arm. Thanks for the lead!
