### ISSUE TITLE
Hyper turns on the `log` feature of `tracing`

### ISSUE THREAD

**Issue by msvbg** [hyperium/hyper#2273]
Hyper turns on the `log` feature of `tracing`, which can be a little bit annoying if you are using another library which records a lot of tracing spans. By using `hyper` in my project, my logs get filled with traces from a different library. It would be nice if it were possible to turn this off.

**Comment by seanmonstar** [comment]
This is a known issue, it was required for backwards compatibility of switching to tracing. It should be fixed in the next breaking change.

**Comment by hawkw** [comment]
The `"log"` feature (not the `"log-always"` feature) _should_ only emit `log` records when no `tracing` subscriber has been set as the default. If a default subscriber has ever been set by the program, `log` records shouldn't be emitted by any `tracing` spans or events. If this is not the case, that could be a `tracing` bug, and we'd love a bug report issue.
