### ISSUE TITLE
Why there is a blocking?

### ISSUE THREAD

**Issue by persevereVon** [hyperium/hyper#2274]
Hello there, I have two tokio runtime, one for http server, and the other is doing something about http request. I want to use shared reqwest client instance.
But I ran into some problems, I write some code to illustrate.
```rust
use crossbeam_channel::unbounded;
use reqwest::Client;
use warp::Filter;

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_thread_ids(true)
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .init();

    let client = reqwest::Client::new();

    let routes = warp::any()
        .and(with_client(client.clone()))
        .and_then(dyn_reply);

    let (s, r) = unbounded();

    tokio::spawn(async move {
        loop {
            tokio::time::delay_for(std::time::Duration::from_secs(10)).await;
            s.send(1).unwrap();
        }
    });

    std::thread::spawn(move || {
        let mut threaded_rt = tokio::runtime::Builder::new()
            .basic_scheduler()
            .enable_all()
            .build()
            .unwrap();

        threaded_rt.block_on(async {
            loop {
                let msg = r.recv().unwrap();
                client
                    .get("http://192.168.1.104:9200")
                    .body("the exact body that is sent")
                    .send()
                    .await;
            }
        });
    });

    warp::serve(routes).run(([127, 0, 0, 1], 3030)).await;
}

fn with_client(
    client: Client,
) -> impl Filter<Extract = (Client,), Error = std::convert::Infallible> + Clone {
    warp::any().map(move || client.clone())
}

async fn dyn_reply(client: Client) -> Result<Box<dyn warp::Reply>, warp::Rejection> {
    client
        .get("http://192.168.1.104:9200")
        .body("the exact body that is sent")
        .send()
        .await;
    Ok(Box::new("w"))
}
```
First, run it. After 10 seconds, the message has been received, and a request to `http://192.168.1.104:9200` has been sent. If I request to `localhost:3030`, it's been blocking until the next message has been received.
If the request to `http://192.168.1.104:9200` is not keep-alive, the problem won't occur.
I tracked the log, It feels like there might have been a problem getting a connection. I want to know what's going on. thank you.

**Comment by seanmonstar** [comment]
You're using a crossbeam channel, which has blocking semantics. That means in your loop, after sending a request, the `r.recv().unwrap()` will block the thread until another message is ready. Since the thread is blocked, it cannot run any other tasks on the runtime, like the one watching the connection that is kept alive.

Try switching to `tokio::sync::mpsc`. Also, at least in this example, you don't really need to have 2 runtimes, you could use the same one for both the server and client. But perhaps in your larger app, there is a compelling reason to have them on separate threads.
