### ISSUE TITLE
IncompleteMessage

### ISSUE THREAD

**Issue by silence-coding** [hyperium/hyper#2275]
Use the tokio-rustls to implement the client and server. In the case of 20 KB request body, 3 KB response body, and wrk 1000 connection, the client reports the IncompleteMessage error for a few requests.

Request chain：
wrk -> Server[hyper server and client with tokio-rustls]  ->  Server[hyper with tokio-rustls]

**Comment by silence-coding** [comment]
What are the conditions that cause the connection to be closed during the keepalive period?

**Comment by seanmonstar** [comment]
It could be closed for lots of reasons:

- Some OS configured idle timeout
- Some app configured idle timeout
- The connection being broken
- All of the request or response body not being read

**Comment by silence-coding** [comment]
@seanmonstar thanks
