### ISSUE TITLE
Chunks splitting during long polling

### ISSUE THREAD

**Issue by alexfedoseev** [hyperium/hyper#2293]
We have an endpoint which implements long polling by passing a stream as a body. Once results are available, JSON chunk gets pushed to a client. I noticed that sometimes valid chunk of JSON (let's say `AB`) is pushed as 2 set of bytes (`A` and `B`) so each set becomes an invalid JSON but when concatenated (`A + B`) it can be deserialized. Is there a way to avoid that? Or if it's an unavoidable protocol limitation, can we before dispatching the result, determine if JSON is too big and split it manually (e.g. one vec would be sent as 2 vecs) so client wouldn't ever fail to deserialize data on each push?

At the moment I'm working around it by introducing a temporary cache on a client side, so on each push it attempts to deserialize the data and, if it fails, adds it to a cache, then on the next push, it concatenates cache contents and tries to deserialize again until the success. But it's our local development workaround and we would prefer to not exposing such detail to consumers of the api.

**Comment by seanmonstar** [comment]
This is just the nature of HTTP, the bytes of data will be split over multiple IP packets and may arrive at different times depending on congestion along the way.

A common way to handle this in networking protocols is to make the messages length-delimited. Include the number of bytes as the first part of the message, and then send the actual message. The client then knows how much it needs to buffer before it can understand the message.

**Comment by sfackler** [comment]
If you're transmitting JSON, delimiting messages on newlines is also a common approach.

**Comment by alexfedoseev** [comment]
Line feed worked perfectly. Thanks @seanmonstar @sfackler
