### ISSUE TITLE
Upgrade to Tokio v0.3

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2302]
Tokio v0.3 [just released](https://tokio.rs/blog/2020-10-tokio-0-3), we should upgrade as part of hyper v0.14.

Prerequisites:

- [x] Upgrade `h2` to Tokio v0.3
- [ ] Add back functionality to Tokio v0.3
  - [x] Reintroduce `oneshot::Sender::poll_closed` https://github.com/tokio-rs/tokio/pull/3032
  - [ ] ~~Add back TCP socket options (`set_keepalive`, `set_send_buffer_size`, `set_recv_buffer_size`)~~
  - [ ] Add back vectored write support

**Comment by alex** [comment]
https://github.com/hyperium/h2/pull/491 is a PR for updating `h2`.

**Comment by Urhengulas** [comment]
> [hyperium/h2#491](https://github.com/hyperium/h2/pull/491) is a PR for updating `h2`.

The PR just landed 🎉 
As soon it is part of a new release we can proceed here 😄

**Comment by zonyitoo** [comment]
Hello, what's the status of upgrading to tokio v0.3? @seanmonstar
