### ISSUE TITLE
How to control raw_fd before send?

### ISSUE THREAD

**Issue by TongxiJi** [hyperium/hyper#2308]

**Comment by seanmonstar** [comment]
Can you explain more what you are trying to do?

**Comment by TongxiJi** [comment]
Sometimes,we want to add mark to a connection.

`
mark = 100;
setsockopt(client_socket, SOL_SOCKET, SO_MARK, &mark, sizeof(mark));
`

**Comment by seanmonstar** [comment]
There's nothing in hyper to do that on a per-request basis. If you only need it once per connection, you can make a custom connector that does that upon connect, and use that with the hyper Client.
