### ISSUE TITLE
Error: Thread panicked, must be called from the context of Tokio runtime

### ISSUE THREAD

**Issue by ibraheemdev** [hyperium/hyper#2314]
Running the simple example from `hyper.rs`:
```rust
async fn handle(_: Request<Body>) -> Result<Response<Body>, Infallible> {
    Ok(Response::new("Hello, World!".into()))
}

#[tokio::main]
async fn main() {
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    let make_svc = make_service_fn(|_conn| async {
        Ok::<_, Infallible>(service_fn(handle))
    });
    let server = Server::bind(&addr).serve(make_svc);
    if let Err(e) = server.await {
        eprintln!("server error: {}", e);
    }
}
```

Causes a panic:
```bash
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/io/driver/mod.rs:202:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running other examples like [mini-redis](https://tokio.rs/tokio/tutorial/hello-tokio) is totally fine. I suspect this has something to do with the tokio-0.2.22 dependency of h2 and hyper.

### Environment
```bash
$ rustc -V
=> rustc 1.46.0 (04488afe3 2020-08-24)

OS: macOS Catalina 10.15.7

[dependencies]
hyper = "0.13.8"
tokio = { version = "0.3.1", features = ["full"] }
```

**Comment by ibraheemdev** [comment]
@davidbarsky So hyper is unusable right now without `tokio-compat` until #2302 is complete???

**Comment by sfackler** [comment]
It is usable with the version of tokio it is developed against.

**Comment by davidbarsky** [comment]
Hyper 0.13 depends on Tokio 0.2. You can use Hyper 0.13 with Tokio 0.3 _if_ you use the provided compatibility library, [tokio-compat-02](https://docs.rs/tokio-compat-02/0.1.2/tokio_compat_02/). If you don't to use tokio-compat-02, you'll need to wait until #2302 is complete.

**Comment by ibraheemdev** [comment]
Ok, got it, thanks
