### ISSUE TITLE
Re-enable vectored writes

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2320]
Tokio 0.3 removed an API to do vectored writes. During the upgrade, hyper disabled its support, but we should try to re-enable before releasing 0.14.

This requires a proposal for a new API in Tokio proper.

**Comment by seanmonstar** [comment]
Proposal in Tokio: https://github.com/tokio-rs/tokio/issues/3135

**Comment by bikeshedder** [comment]
tokio-rs/tokio#3149 has been merged and `tokio 0.3.4` was released 2 days ago which [includes this feature](https://github.com/tokio-rs/tokio/blob/master/tokio/CHANGELOG.md#added). :tada:

**Comment by seanmonstar** [comment]
It's being worked on in https://github.com/hyperium/hyper/pull/2338 :D
