### ISSUE TITLE
Refactor HTTP upgrades into Extensions

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2340]
In #2086, it was outlined how the HTTP upgrades should be moved off the `Body` type (and into `Extensions`). The public facing part was done, now we just need to update the internal `proto::h1` stuff to stash them into the `Extensions` instead of on a private `Body` field.

In order to do so, the `proto::MessageHead` will need to gain an `extensions` field, so we can place them there.

**Comment by aknuds1** [comment]
I'd like to try solving this if it's OK? I started a draft PR https://github.com/hyperium/hyper/pull/2353, but could use some guidance as I'm unsure about a few things (some basic Rust things, and how to get state into the extensions of Requests and Responses f.ex.).
