### ISSUE TITLE
Known vulnerability in dependency 'pnet' v 0.25.0

### ISSUE THREAD

**Issue by FlyingRatBull** [hyperium/hyper#2347]
I ran `cargo audit` on the current master and got a match for a known vulnerability in pnet 0.25.0:

__ID__: RUSTSEC-2019-0037
__Package__: pnet
__Version__: 0.25.0
__Fixed in__: not yet fixed
__Title__: Compiler optimisation for next_with_timeout in pnet::transport::IcmpTransportChannelIterator flaws to SEGFAULT
__Description__: Affected versions of this crate were optimized out by compiler, which caused dereference of uninitialized file descriptor which caused segfault.
__Issue__: [pnet GitHub issue #449](https://github.com/libpnet/libpnet/issues/449)

**Comment by taiki-e** [comment]
> **Fixed in**: >=0.26.0

> **Issue**: [pnet GitHub issue #449](https://github.com/libpnet/libpnet/issues/449)

This doesn't really seem to have been fixed yet. (https://github.com/libpnet/libpnet/pull/455)

**Comment by FlyingRatBull** [comment]
> > **Fixed in**: >=0.26.0
> 
> > **Issue**: [pnet GitHub issue #449](https://github.com/libpnet/libpnet/issues/449)
> 
> This doesn't really seem to have been fixed yet. ([libpnet/libpnet#455](https://github.com/libpnet/libpnet/pull/455))

Good catch, I will file an update to the security advisory database.

**Comment by seanmonstar** [comment]
Thanks for the report, definitely worth getting a fix in. Good news is that its only used in hyper's unit tests, so not part of the actually library

**Comment by mrmonday** [comment]
Additionally, it looks like the unit tests do not use any of the code in libpnet which is affected by this vulnerability.

**Comment by FlyingRatBull** [comment]
Thanks to the quick reply of the pnet devs, the pull request has been merged and the issue fixed in 0.27.2
