### ISSUE TITLE
HttpConnector should not error if a socket option fails

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2359]
An error trying to set a socket option should not error the entire connect attempt. Instead, they should just be logged (perhaps at `warn` level).

**Comment by aeryz** [comment]
I am interested in this but I have a question. Should we just log all socket option failures and continue to connect? Are there any fatal ones?

**Comment by seanmonstar** [comment]
What do you propose? I think if the option is required to function, then of course error. But most aren't.
