### ISSUE TITLE
Allow HTTP/2 request multiplexing with low-level client API

### ISSUE THREAD

**Issue by fasterthanlime** [hyperium/hyper#2375]
(👋  first off, hyper is *awesome*, thanks to all contributors for it!)

We're using a custom connection pool internally that's based on the low-level api, ie [conn::Builder::handshake](https://docs.rs/hyper/0.14.1/hyper/client/conn/struct.Builder.html#method.handshake) and [conn::SendRequest](https://docs.rs/hyper/0.14.1/hyper/client/conn/struct.SendRequest.html) instead of [Client](https://docs.rs/hyper/0.14.1/hyper/client/struct.Client.html).

However, the built-in `Client` uses the private type `Http2SendRequest`, which turns the `dispatch::Sender` into a `dispatch::UnboundedSender`, which as I understand it, allows multiplexing HTTP/2 requests over a single connection. 

Without the `UnboundedSender`, even though the inner type of `dispatch::Sender` is an `mpsc::UnboundedSender`, sending is limited by the `Giver`, so a new request will only be accepted once the previous one has been fully processed.

The comment for `Http2SendRequest` seems to indicate it's not ready for prime time / one wouldn't want to commit to it as part of hyper's public API:

```rust
// A `SendRequest` that can be cloned to send HTTP2 requests.
// private for now, probably not a great idea of a type...
```

Are there any alternative approaches that would be suitable as part of the public API? If not, would you consider exposing it publicly when a cargo feature is enabled (maybe `unstable_h2_send_req`, to indicate that it may change at any time without notice?).

Our immediate workaround is forking hyper to expose it - I'd love for that solution to be as short-term as possible - if there were ambient ideas on what a better API could be, I'd be happy to contribute making it happen.

**Comment by seanmonstar** [comment]
I believe even the `SendRequest` should allow for HTTP/2 request multiplexing. It doesn't require the response to be returned to send a new request, it's just trying to propagate the backpressure if the h2 connection has hit the remote's max concurrent streams setting.

**Comment by seanmonstar** [comment]
Just checking in here: with my comment, was it possible to get multiplexing working without forking?

**Comment by fasterthanlime** [comment]
> Just checking in here: with my comment, was it possible to get multiplexing working without forking?

Sorry for the delay, multiple things happened in that 20-day interval — I've still got "do actual packet capture and determine if HTTP/2 multiplexing is in fact used" on my TODO list, will get to it soon :TM: and will update you here.

**Comment by fasterthanlime** [comment]
Was finally able to put some time into this!

Here's the sort of behavior I'm currently seeing:

![image](https://user-images.githubusercontent.com/7998310/104787734-a03a1400-5790-11eb-8293-07a063eb10ed.png)

(There's a single `SendRequest` involved here, `TCP_NODELAY` is *disabled* here.)

By contrast, here's `h2load` (that comes with ng2http) sending 50 requests in a single TCP packet:

![image](https://user-images.githubusercontent.com/7998310/104787916-30785900-5791-11eb-9253-a1da3090075c.png)

---

I'm going to do some further tests, but I'm closing this since, yes, technically HTTP/2 request multiplexing does happen with the low-level client API, ie. several requests are sent (on several streams) before the responses come in — how they're distributed across TCP packets is beyond the scope of this!
