### ISSUE TITLE
server response with http 0.9 instead of http2

### ISSUE THREAD

**Issue by frbimo** [hyperium/hyper#2378]
i did the example https://docs.rs/hyper/0.14.1/hyper/server/index.html#example 
and tried to call it using : `curl --http2  http://127.0.0.1:3000`

it returns
```
curl: (1) Received HTTP/0.9 when not allowed
```
similar when using httpie:

```
http: error: ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) while doing GET request to URL: http://127.0.0.1:3000/

```

OS: pop OS 20.04
hyper: 0.14.1

**Comment by paolobarbolini** [comment]
If you don't have `http1` enabled and your server isn't https you also have to pass `--http2-prior-knowledge`.

**Comment by seanmonstar** [comment]
Exactly as Paolo mentioned, so I'm going to close (we can re-open if it's found to be a genuine bug).
