### ISSUE TITLE
instant.elapsed() will panic

### ISSUE THREAD

**Issue by silence-coding** [hyperium/hyper#2385]
this method is panic.  hyper::client::pool::702
![image](https://user-images.githubusercontent.com/32766901/103480903-4c374300-4e12-11eb-942f-8e69ac939081.png)

![image](https://user-images.githubusercontent.com/32766901/103480922-70931f80-4e12-11eb-8187-6cdac9d5f52c.png)

**Comment by silence-coding** [comment]
![image](https://user-images.githubusercontent.com/32766901/103481245-ae914300-4e14-11eb-939e-1be709ffe10b.png)

**Comment by seanmonstar** [comment]
Hm. This should never happen, sounds like a bug in libstd.

**Comment by silence-coding** [comment]
I don't think of how to trigger the scene yet, which seems unlikely to happen.

![image](https://user-images.githubusercontent.com/32766901/103497321-22b30180-4e7c-11eb-9c87-34708744275a.png)

**Comment by silence-coding** [comment]
Is the obtained CLOCK_MONOTONIC in multi-core CPU scenarios incorrect?

**Comment by malaire** [comment]
What OS?
`std::time::Instant` contains code to fix non-monotonic monotonic clocks but it's not used on some platforms which have so far worked without it: https://doc.rust-lang.org/src/std/time.rs.html#224-264

**Comment by silence-coding** [comment]
Whether to replace elapsed with saturation_duration_since？

**Comment by yonip23** [comment]
I came across a similar problem once, I think the solution is to use the [chrono](https://docs.rs/chrono/0.4.19/chrono/) crate instead.

**Comment by silence-coding** [comment]
> Whether to replace elapsed with saturation_duration_since？

@seanmonstar Whether hyper will fix this issue, if it is waiting for std to fix it, then I will close the issue.

**Comment by seanmonstar** [comment]
Fixed in #2746
