### ISSUE TITLE
How to forcibly shut down the server?

### ISSUE THREAD

**Issue by helgoboss** [hyperium/hyper#2386]
@sfackler mentioned [here](https://github.com/hyperium/hyper/issues/1885#issuecomment-754827116_) that this is done by dropping the server instead of using `graceful_shutdown()`. But I can't figure out how to do that exactly. See the following attempts.

### Attempt 1
I can't figure out how to drop the server *within* the runtime because I'm `await`ing it. To illustrate the problem, here's some example code that should shut the server down after 20 secs and then keep waiting for a while:

```rust
#[tokio::main]
pub async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let make_svc = make_service_fn(|_conn| async { Ok::<_, Infallible>(service_fn(hello)) });
    let addr = ([127, 0, 0, 1], 3000).into();
    let server = Server::bind(&addr).serve(make_svc);
    let wait_a_bit_and_close_server = move || async {
        println!("Waiting 20 secs");
        delay_for(Duration::from_secs(20)).await;
        println!("Shutting down server...");
        // TODO Shutdown/drop ... but how?
    };
    async fn wait_longer_to_delay_exit() {
        delay_for(Duration::from_secs(1000));
    };
    println!("Listening on http://{}", addr);
    let _ = tokio::join!(
        server,
        wait_a_bit_and_close_server(),
        wait_longer_to_delay_exit()
    );
    Ok(())
}
```
Any idea what I need to do differently to drop the server?

### Attempt 2
In my particular case I build the runtime myself within a new dedicated thread and then call `block_on()` with the hyper server future (well, actually warp but it shouldn't matter here).

Side note: I used a dedicated thread and `block_on()` because initially I wanted to use `basic_scheduler()`.

```rust
        let server_thread_join_handle = std::thread::Builder::new()
            .name("ReaLearn server".to_string())
            .spawn(move || {
                let runtime = tokio::runtime::Builder::new()
                    .threaded_scheduler()
                    .enable_all()
                    .build()
                    .unwrap();
                runtime.block_on(...);
                runtime.shutdown_timeout(Duration::from_secs(10));
            });
```

So I naively thought, maybe one way to drop the hyper server would be to use `spawn()` instead of `block_on()`, store the `runtime` somewhere, call `shutdown_timeout()` on it when the user demands the server to be stopped and then drop the runtime. The runtime shuts down, but not completely. The ports are still bound (but don't give responses anymore). Increasing the shutdown timeout doesn't help either.

**Comment by seanmonstar** [comment]
You could make use of [`select!`](https://docs.rs/tokio/1.*/tokio/macro.select.html) to await both the `Server`, and the some signal, and if the signal completes, you just drop the `Server` at that point (don't await on it again).

**Comment by helgoboss** [comment]
@seanmonstar Thanks for the tip! That indeed gives me the opportunity to drop the server. However, after dropping the server the endpoint still responds to request. I'm confused. Here's the complete `main.rs`. Probably doing something wrong.

```rust
use std::convert::Infallible;

use hyper::service::{make_service_fn, service_fn};
use hyper::{Body, Request, Response, Server};
use std::time::Duration;
use tokio::time::delay_for;

async fn hello(_: Request<Body>) -> Result<Response<Body>, Infallible> {
    Ok(Response::new(Body::from("Hello World!")))
}

#[tokio::main]
pub async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    pretty_env_logger::init();
    let make_svc = make_service_fn(|_conn| async { Ok::<_, Infallible>(service_fn(hello)) });
    let addr = ([127, 0, 0, 1], 3000).into();
    let mut server = Server::bind(&addr).serve(make_svc);
    println!("Listening on http://{}", addr);
    tokio::select! {
        _ = wait_20_secs() => {
            println!("20 secs passed first");
        }
        _ = &mut server => {
            println!("server ended first");
        }
    };
    println!("Dropping server...");
    drop(server);
    println!("Keeping process alive for some more time to check if server still reachable...");
    // Server still reachable :(
    delay_for(Duration::from_secs(1000)).await;
    Ok(())
}

async fn wait_20_secs() {
    println!("Waiting 20 secs...");
    delay_for(Duration::from_secs(20)).await;
    println!("20 secs passed");
}
```

**Comment by seanmonstar** [comment]
Yes, dropping the `Server` will just drop the acceptor of new connections. Existing connections will still be functioning. Exiting the process is one option. Or, you can not use `hyper::Server`, and instead use `hyper::server::Http` to manage the connections yourself.

**Comment by helgoboss** [comment]
Now that you mention it ... yes, it only responded to existing connections. As soon as I closed the whole browser, they were gone and the ports were finally freed (observed that using Sysinternals Process Explorer).

**Insight: So actually, dropping the `Server` struct doesnt really forcibly shut the server down.**

Exiting the process is no option in my case because it's a plug-in that runs within a host process. Using `hyper::server::Http` only seems a bit too low-level for me, especially considering that in my real-world app I use the even higher-level warp (thanks for all those amazing crates by the way!).

Which leads me back to my initial question in issue #1885:

> In my particular case, I need a "not so graceful" shutdown. It's absolutely essential to shut down the server *as fast as possible* without having to wait for connections that have unfinished business. My server lives in a desktop app plug-in that can be added/removed by the user at any time. From a UX perspective it would be a dealbreaker to force the user to wait and figure out which of his devices/browsers are still connected to the server. However, it would be totally okay if established connections are abruptly closed by the server side.
>
> As a [dirty workaround](https://github.com/helgoboss/hyper/commit/d85bbc12279f978780bf022598902ee798266e6a), I patched hyper to make `graceful_shutdown()` forcibly close a HTTP 1.1 connection. It does the job. Does anyone know if this is the right approach if one can afford to close connections forcibly? I'm considering to create a PR with some method like `forceful_shutdown()` to support this use case.

@seanmonstar What would you think about a `forceful_shutdown()` method?

**Comment by helgoboss** [comment]
@seanmonstar I'm at the moment stuck with my customized version that contains this [small workaround](https://github.com/helgoboss/hyper/commit/d85bbc12279f978780bf022598902ee798266e6a). Would you consider a PR that adds a `forceful_shutdown()` method which does essentially the same thing as in the workaround code?

**Comment by helgoboss** [comment]
Closing this issue because I eventually found an example which implements a forceful shutdown (which doesn't wait for open connections to close) on top of unmodified hyper (see [axum-server](https://github.com/programatik29/axum-server/blob/bb10c5e7e388a2055efe7b466c026208b8c01733/src/handle.rs#L46)).

**Comment by kkk-yu** [comment]
@helgoboss Can you describe roughly how axum-server implements forced shutdown? I don't think it implements forced shutdown after reading the source code.

**Comment by helgoboss** [comment]
> @helgoboss Can you describe roughly how axum-server implements forced shutdown? I don't think it implements forced shutdown after reading the source code.

I can't remember to be honest ;) I just know that I didn't have that particular issue anymore once I moved to Axum. At least last time I checked it didn't hold on to open connections (when using e.g. `runtime.shutdown_timeout(Duration::from_secs(1))` to shutdown the Tokio runtime).
