### ISSUE TITLE
Switch from pin-project to pin-project-lite

### ISSUE THREAD

**Issue by jplatte** [hyperium/hyper#2388]
futures-rs [just switched](https://github.com/rust-lang/futures-rs/pull/2273) and tokio has been using the `-lite` one since 0.2.0. I haven't used either so I don't actually know how hard switching is, but it seems like a good idea since it greatly improves compile times for people who don't depend on syn & quote otherwise.

**Comment by seanmonstar** [comment]
Considered, and agreed! It should be done!

**Comment by taiki-e** [comment]
This may require https://github.com/taiki-e/pin-project-lite/pull/43.

**Comment by jplatte** [comment]
I'll take a stab at implementing this.

**Comment by paolobarbolini** [comment]
Depends on https://github.com/taiki-e/pin-project-lite/pull/25

**Comment by jplatte** [comment]
Just found that out myself. Thanks for the link 🙂

**Comment by jplatte** [comment]
Also depends on https://github.com/taiki-e/pin-project-lite/issues/3 because of

https://github.com/hyperium/hyper/blob/c9c46ed60bd43484d67a98a63496ad0277c791a2/src/server/conn.rs#L163-L165

**Comment by taiki-e** [comment]
> Also depends on [taiki-e/pin-project-lite#3](https://github.com/taiki-e/pin-project-lite/issues/3) because of
> 
> https://github.com/hyperium/hyper/blob/c9c46ed60bd43484d67a98a63496ad0277c791a2/src/server/conn.rs#L163-L165

pin-project-lite#3 is about attributes that apply only to the original struct/enum.
Proper handling of cfg/cfg_attr on *fields and variants* requires a more complex approach than the fix for pin-project-lite#3 (it needs to be aware of the kind of attribute and propagate some of it to projected type). [Even pin-project could not find the correct solution other than "leave to the compiler"](https://github.com/taiki-e/pin-project/issues/68#issuecomment-528318870). And it is impossible to use the same trick in pin-project-lite.

However, there is [a known workaround](https://github.com/taiki-e/pin-project/issues/68#issuecomment-528318870) for the cfg issue, and probably hyper can use it as well.

> for now, it is preferable to create a type alias / new type or create structs for each `cfg`.

Something like:

```rust
#[cfg(all(feature = "http1", feature = "http2"))]
#[derive(Clone, Debug)]
enum Fallback<E> { ... }

#[cfg(not(all(feature = "http1", feature = "http2")))]
#[derive(Clone, Debug)]
struct Fallback<E>(std::marker::PhantomData<E>);

pin_project! {
    pub struct Connection<T, S, E = Exec>
    where
        S: HttpService<Body>,
    {
        pub(super) conn: Option<ProtoServer<T, S::ResBody, S, E>>,
        fallback: Fallback<E>,
    }
}
```

**Comment by jplatte** [comment]
> pin-project-lite#3 is about attributes that apply only to the original struct/enum.

The title and issue description are exactly about this. Anyway, thanks for providing a workaround, I'll apply that after taiki-e/pin-project-lite#25 is merged and I can finish my PR.

**Comment by jplatte** [comment]
Hmm, by the way that struct is not using `#[pin]` at all, should it even be using `pin_project!`?

**Comment by taiki-e** [comment]
> The title and issue description are exactly about this.

Well, I agree that it is confusing.

> Hmm, by the way that struct is not using `#[pin]` at all, should it even be using `pin_project!`?

Technically, `pin_project!` is not required for types that do not use `#[pin]`.

**Comment by taiki-e** [comment]
> after [taiki-e/pin-project-lite#25](https://github.com/taiki-e/pin-project-lite/pull/25) is merged

I think I can merge that this weekend or the next week. (it only needs docs and tests)

**Comment by seanmonstar** [comment]
I had to revert in https://github.com/hyperium/hyper/pull/2422, an issue was found after releasing: https://github.com/hyperium/hyper/issues/2421

**Comment by jplatte** [comment]
I had a look, [this is the problematic type](https://github.com/hyperium/hyper/pull/2393/files#diff-bf5263b889c2bb696a1671b7d3778a67c468f73755166d3e4ed0410cb9acf109R80-R94): an enum that uses `#[cfg]` on its variants. The two solutions I can think of:

* always have the variant but containing an uninhabited type if the corresponding feature is disabled. Probably requires adding extra `Self::Foo { bar } => match bar {},` branches
* three declarations of the type for the three possible feature combinations (assuming that it just doesn't need to exist if both `http1` and `http2` are disabled, otherwise four)

**Comment by jplatte** [comment]
Working on this again, using the first solution I mentioned above (if still applicable).
