### ISSUE TITLE
Bandwidth Rate limiting

### ISSUE THREAD

**Issue by staticgc** [hyperium/hyper#2398]
Use-Case: Large buffers (~ 1MB) and large number of them (~millions) are to be transferred by the client and exploring hyper for it. Need a way to limit the network bandwidth used.

I see a similar ticket [2163](https://github.com/hyperium/hyper/issues/2163) which was closed and hence opening a new one.

Is there a way to control n/w bandwidth in hyper?

**Comment by aeryz** [comment]
As @seanmonstar said (https://github.com/hyperium/hyper/issues/2163#issuecomment-604497970), hyper uses streamed bodies so you should be able to control the rate of reads and writes.

**Comment by staticgc** [comment]
How on earth did I miss that comment? It seems I read it but did not process it seems.
Thanks @aeryz

**Comment by staticgc** [comment]
> hyper uses streamed bodies

I explored it and I am still confused.

My understanding is that hyper Client has a pool of tcp connections. So at a client level (i.e. `hyper::client::Client`) if I have to control the bytes written, how can I do that?

This implies that consumer of the client will specify say "do not use more than 20 MB/s".  This needs to be split across underlying connections, which is further complicated by the fact that number of connections is dynamic.

**Comment by staticgc** [comment]
How about this?

I have used the limiter in the crate: [async-speed-limit](https://docs.rs/async-speed-limit)

Now we:

* Create a new type `MyStream` which wraps `tokio::net::TcpStream` and implements `AsyncWrite` & `AsyncRead`
* Implement a connector `MyConnector` similar to `HttpConnector` which helps to create new `MyStream`
* Instantiate [Limiter](https://docs.rs/async-speed-limit/0.3.1/async_speed_limit/limiter/struct.Limiter.html) and attach to `MyConnector` 
* `MyConnector` attaches cloned instance of `Limiter` to every new `MyStream` (done via `fn call` in `MyConnector`)

The `Limiter` is thread-safe & cheaply clone-able. They all share the same bucket wrapped in Arc. 

The `MyStream`'s `fn poll_write` calls the limiter to "consume" and wait if not enough tokens.

Reference gist: [here](https://gist.github.com/staticgc/f3df4ba3499d00b51c13ac4d898f3b5e)

### Does it work?

Initial results does seem to suggest that it is working, but I would like to see others try

**Comment by aeryz** [comment]
Hey, although I haven't tried it yet, your solution looks good to me. Since all connections use the same limiter, it would be able to limit the overall bandwidth rate perfectly.
