### ISSUE TITLE
Client/serve_connection hangs on 0.14, some platforms

### ISSUE THREAD

**Issue by dekellum** [hyperium/hyper#2402]
On upgrade to hyper 0.14, tokio 1.0 I found certain tests of a project started failing (by never completing) on Windows and MacOS in CI, but not Linux.  These tests spawn a future to serve a fixed number of requests from a hyper `Client` via `conn::Http::serve_connection`.

I have minimized a reproduction of the issue in a separate repro with github actions CI, as shown:

https://github.com/dekellum/repro-hyper-client-hang/blob/main/src/lib.rs

You can see the various versions of this I tried in the commit history here:

https://github.com/dekellum/repro-hyper-client-hang/commits/main

And on a `tokio-0.2` branch I back-port to hyper 0.13, tokio 0.2, where it still works on all the same platforms:

https://github.com/dekellum/repro-hyper-client-hang/commits/tokio-0.2

I'm not currently well setup to debug this on MacOS or Windows (thus the efforts with CI). In my real project, I was able to workaround the issue by simply replacing all uses of `serve_connection` with a full fledged `hyper::Server` and `with_graceful_shutdown` channel.  I'm reporting this because it seems like it might indicate a more important underlying issue.

**Comment by seanmonstar** [comment]
> And on a tokio-0.2 branch I back-port to hyper 0.13, tokio 0.2, where it still works on all the same platforms:

When you say "it still works", do you mean you can trigger the hang with the older versions, or that it works *correctly*?

**Comment by dekellum** [comment]
Sorry, that wasn't clear: If run on the referenced branch with the old versions, it works as expected (doesn't hang) on _all_ the same platforms.

**Comment by seanmonstar** [comment]
Could you enable tracing for the CI jobs, so we can see what's going on on those targets?

**Comment by dekellum** [comment]
Enabled on main branch. I'll let the Windows and MacOS CI jobs run for 10 minutes (hung) again before cancelling them.

**Comment by dekellum** [comment]
Only the Linux run makes it past the following step in log output:

https://github.com/dekellum/repro-hyper-client-hang/runs/1743300896?check_suite_focus=true#step:4:178

(Mac and Windows hang at this point.)

**Comment by seanmonstar** [comment]
Hm, I notice this is making a `std::net::TcpListener`, and then converting that into a `tokio::net::TcpListener`. Is this a necessary step to trigger the hang? I was looking through [here](https://github.com/hyperium/hyper/blob/4d2125c67c8087de863f74278a017c4caf37e6a9/src/server/tcp.rs#L34-L37), and noticed this comment about not setting `O_NONBLOCK`...

**Comment by dekellum** [comment]
It was done originally, I think, just because these tests didn't require and async bind.  Good suggestion, as exclusively using `tokio::net::TcpListener` appears to avoid the issue (on all platforms), as in: dekellum/repro-hyper-client-hang@9d9f8ba6.

I'll also try setting O_NONBLOCK directly, just to confirm that's the difference.

I wonder if older version of hyper or tokio would have set this itself? If this is the cause, then maybe its worth a sentence in `conn::Http::serve_connection` rustdoc?

**Comment by sfackler** [comment]
Older versions of tokio switched sockets to nonblocking in from_std.

**Comment by dekellum** [comment]
Yep, so explicitly setting O_NONBLOCK also fixes the original (std) Tcp Listener (dekellum/repro-hyper-client-hang@6b644c6).

And I see now that tokio documents it:

https://docs.rs/tokio/0.2.25/tokio/net/struct.TcpListener.html#method.from_std
> The platform specific behavior of this function looks like:
> * On Unix, the socket is placed into nonblocking mode and connections can be accepted as normal

https://docs.rs/tokio/1.1.1/tokio/net/struct.TcpListener.html#method.from_std
> The conversion assumes nothing about the underlying listener; it is left up to the user to set it in non-blocking mode.

I might have saved  us some time had I seen this in the tokio 1.0.0 release notes!

So I guess from a hyper perspective, you have the choice of considering this user error with tokio (1.0) _and/or_ an undocumented invariant of `conn::Http::serve_connection`?  I'm not sure of the mechanics of the hang only on non-Linux platforms. Its possibly just comes down to timing differences, or behavior of epoll vs others?

**Comment by seanmonstar** [comment]
hyper doesn't treat the sockets any differently for different platforms. The hang is coming from hyper doing a read after finishing reading the body, to register for a hangup in case the socket closes.

Looks like this isn't an issue with hyper directly, so I'm going to close here.

**Comment by dekellum** [comment]
Fair enough. Thanks for the help in tracking down the Tokio change in O_NONBLOCK behavior.
