### ISSUE TITLE
Can I choose the HTTP transporter?

### ISSUE THREAD

**Issue by lucaszanella** [hyperium/hyper#2408]
Can I generate raw http queries so I can transport in my own transporter instead of relying on the default socket from the library?

**Comment by seanmonstar** [comment]
hyper's client API allows you to specify a connector with a connection type, yes.

**Comment by lucaszanella** [comment]
On https://docs.rs/hyper/0.14.2/hyper/service/trait.Service.html, it gives a `impl Service<Request<Vec<u8>>> for HelloWorld {`. I tried reproducing it but it says that my `Response<Vec<u8>>` should implement `AsyncRead` and `AsyncWrite`, which I cannot do because `Response` is a struct outside my project:

`the trait bound `hyper::Response<std::vec::Vec<u8>>: tokio::io::AsyncRead` is not satisfied`

I even tried to create my own `Response`: 

```
struct MyResponse {

}


impl tokio::io::AsyncRead for MyResponse {
///...
}

impl tokio::io::AsyncWrite for MyResponse {
///...
}
```

but then I get

`the trait `hyper::client::connect::Connection` is not implemented for `custom_req::MyResponse``


How should I implement a custom transporter? 

Thanks

**Comment by seanmonstar** [comment]
The docs for `Service` are just showing 1 example, it is generic over any "request" and "response" type. For hyper's connectors, it's a `Service` where the request is a destination, and the response is an IO type. See https://docs.rs/hyper/0.14.*/hyper/client/connect/index.html for more.

**Comment by lucaszanella** [comment]
@seanmonstar Thank you very much! I created a CustomTransporter to test and return a fake request but I get 

`Error: hyper::Error(ChannelClosed)`

If you could take a look it'd be very awesome, I couldn't find examples of this on the web

https://github.com/lzunsec/rust_hyper_custom_transporter/blob/334d0f160255082e40c76e7b96d11ef1d006bce1/src/custom_req.rs

I'd love to make this available for others to learn

**Comment by lucaszanella** [comment]
Here's my new, more clean `CustomTransporter`:

https://github.com/lzunsec/rust_hyper_custom_transporter/blob/c0fb75d9ed8fdf854888ccd605063ca433383689/src/custom_req.rs

Could somebody help me? I traced the problem to this line:

https://github.com/hyperium/hyper/blob/4c946af49cc7fbbc6bd4894283a654625c2ea383/src/client/client.rs#L389

This is where the error comes from.

Adding some verbosity, I I got this specific error:

received unexpected 325 bytes on an idle connection

right from this line:

https://github.com/hyperium/hyper/blob/4c946af49cc7fbbc6bd4894283a654625c2ea383/src/proto/h1/conn.rs#L326

Looks like something in my code calls `require_empty_read`.

I spent some days reading the code but there are lots of things to understand, maybe someone with the knowledge could find the problem right away.

**Comment by lucaszanella** [comment]
Found the problems.

First, you need to wait for the request to answer it. I was trying to send the HTTP response before even receiving the HTTP request, that's why the channel got closed.

Then, I aldo needed to use wake on the poll_read so I could give the answer when needed. It tried to poll while I didn't have received the GET request, and thus I returned Pending. It won't try again, so I need to call wake on the context's waker
