### ISSUE TITLE
h2c upgrade request ignored

### ISSUE THREAD

**Issue by haskonv** [hyperium/hyper#2411]
I'm attempting to test upgrading a request to http2 via curl.  `curl -w "%{http_code}|%{http_version}" --http2 http://...` The feature in cargo is set to all for hyper. When I read the [rfc](https://tools.ietf.org/html/rfc7540#section-3.2) it indicates the that upgrade h2c should work. Is this not supported? Or am I doing something wrong?

**Comment by seanmonstar** [comment]
hyper does not have support for HTTP2 upgrades. It was considered, but after noticing that browsers don't bother because too many servers react badly to an unexpected `upgrade` header, we just didn't see much value in adding the support.

**Comment by sinloss** [comment]
Considering `server-to-server` requests via `http/2` over a secure (*which is quite easy to achieve between servers*) network, using the `upgrade: h2c` will cut down the TLS encryption/decryption costs, hence making it more efficient. I mean, cut the whole thing down!

I stumbled here after seeing that the underlying `hyper` would (*kindly, yet heartbreakingly*) reject HTTP/1.0 connections when `http2_only` is set, while I'm attempting to use the [reqwest](https://github.com/seanmonstar/reqwest) to do `server-to-server` requests...

**Comment by seanmonstar** [comment]
You don't need `upgrade: h2c` support for hyper to use HTTP/2 without TLS. You can either use ALPN, or you can use what the spec calls "prior knowledge".

**Comment by sinloss** [comment]
I need to do some more googling now... I'll try it.
