### ISSUE TITLE
Build Broken When Using ASAN

### ISSUE THREAD

**Issue by kamulos** [hyperium/hyper#2431]
System: Arch Linux
Rust: rustc 1.52.0-nightly (0fc6756b4 2021-02-08)
Linker: LLD 11.0.1 (compatible with GNU linkers)
Affected Hyper Version: > 0.14.2

## Reproduction
Build hyper using `RUSTFLAGS="-Zsanitizer=address -Clink-arg=-fuse-ld=lld" cargo +nightly build --target=x86_64-unknown-linux-gnu`

Output:

```
  = note: ld.lld: error: undefined hidden symbol: __start_asan_globals
          >>> referenced by 108v8orxopd2lq03
          >>>               /home/xxx/target/x86_64-unknown-linux-gnu/debug/deps/hyper.108v8orxopd2lq03.rcgu.o:(asan.module_ctor)
          >>> referenced by 108v8orxopd2lq03
          >>>               /home/xxx/target/x86_64-unknown-linux-gnu/debug/deps/hyper.108v8orxopd2lq03.rcgu.o:(asan.module_dtor)

          ld.lld: error: undefined hidden symbol: __stop_asan_globals
          >>> referenced by 108v8orxopd2lq03
          >>>               /home/xxx/target/x86_64-unknown-linux-gnu/debug/deps/hyper.108v8orxopd2lq03.rcgu.o:(asan.module_ctor)
          >>> referenced by 108v8orxopd2lq03
          >>>               /home/xxx/target/x86_64-unknown-linux-gnu/debug/deps/hyper.108v8orxopd2lq03.rcgu.o:(asan.module_dtor)
          collect2: error: ld returned 1 exit status
```

## Git Bisect

```
3ae1581a539b67363bd87d9d8fc8635a204eec5d is the first bad commit
commit 3ae1581a539b67363bd87d9d8fc8635a204eec5d
Author: Sean McArthur <sean@seanmonstar.com>
Date:   Thu Jan 7 17:22:12 2021 -0800

    feat(ffi): Initial C API for hyper
```

**Comment by kamulos** [comment]
This seems to break it:
1. checkout `v0.14.2`
2. add the following to Cargo.toml
```
[lib]
crate-type = ["lib", "cdylib"]
```

**Comment by seanmonstar** [comment]
Hum, so if a library produces a cdylib, it cannot be used with ASAN? If there's nothing else that hyper did specially, I'd probably consider that a bug in cargo or rustc.

(I do wish there was more control over being able to enable the crate-type through a CLI argument, but slightly off-topic...)

**Comment by kamulos** [comment]
ok fair enough. I did some more minimization and opened rust-lang/cargo#9159 . No idea if it is cargo or rustc though.
