### ISSUE TITLE
Force HTTP/1 version

### ISSUE THREAD

**Issue by lucassith** [hyperium/hyper#2433]
I need the ability to force a specific version of HTTP. I know that I can build a client with http2_only function. 
Unfortunately there is no option to force a different protocol version and as far as I can see the 'Ver' enum has two values, Auto and Http2. 

Do I understand correctly that the 'Auto' value does not strictly guarantee the use of HTTP/1 and is there any way to do that? 

I know that theoretically using Http/2 is not possible without TLS, so disabling encryption would result in using HTTP/1 but in my case HTTP/1 is necessary along with SSL. 
Disabling 'http2' feature is also not an option since I need to be able to request HTTP/2 as well.

**Comment by staticgc** [comment]
Can you try setting the http version on request builder: [here](https://docs.rs/http/0.2.2/http/request/struct.Builder.html#method.version)?

There is an issue [2417](https://github.com/hyperium/hyper/issues/2417) for setting the version but it is for HTTP/2.
Setting HTTP/1 might work.

**Comment by lucassith** [comment]
I did as you suggested. It looks like, hyper automatically tries to use HTTP/2 even if I don't suggest it anywhere.

```rust
async fn fetch_url() -> Result<()> {
    let client = Client::builder()
        .http2_only(false)
        .build::<_, hyper::Body>(HttpConnector::new());

    let req = http::request::Builder::new()
        .method("GET")
        .uri("http://svc.watch:80")
        .version(hyper::Version::HTTP_11)
        .body(Body::empty())
        .unwrap();

    match client.request(req).await {
        Ok(res) => {
            println!("Response: {:#?}", res.version());
            println!("Headers: {:#?}\n", res.headers());
        }
        Err(e) => {
            println!("Err: {:#?}", e)
        }
    }

    Ok(())
}
```

With this code, if the server only supports HTTP/1, there will always be a 'FRAME_SIZE_ERROR' error but if it supports HTTP/2 then the protocol will automatically switch and the request will succeed, unfortunately I still won't know if the site supports the older protocol. Just to be sure, I called the request via curl and the page responds to HTTP/1 request.

```
 λ curl -I -v svc.watch        
*   Trying 94.152.2.95:80...
* Connected to svc.watch (94.152.2.95) port 80 (#0)
> HEAD / HTTP/1.1
> Host: svc.watch
> User-Agent: curl/7.75.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Fri, 12 Feb 2021 07:33:10 GMT
Date: Fri, 12 Feb 2021 07:33:10 GMT
< Server: Apache
Server: Apache
< Vary: Accept-Encoding
Vary: Accept-Encoding
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8

< 
* Connection #0 to host svc.watch left intact
```

My dependencies:
```toml
[dependencies]
tokio = { version = "1.2", features = ["full"]}
hyper = { version = "0.14", features = ["http2", "client", "tcp"]}
hyper-tls = "0.5"
hyper-alpn = "0.3"
http = "0.2"
```

**Comment by seanmonstar** [comment]
You may have already noticed, but the issue was that you had only enabled the `http2` crate feature, and so it didn't have the HTTP1 code even built-in.
