### ISSUE TITLE
Provide a hook for arbitrary SSL verification methods

### ISSUE THREAD

**Issue by Manishearth** [hyperium/hyper#244]
Currently we use a `VerifyCallback`, however there's a lot of in built verification in `SslContext` (eg you can just provide it with a root CA file and it does the rest).  Making `HttpConnector` take a `fn(&mut SslContext)` would be more useful (one can still attach verify callbacks directly, so no functionality is lost)

I have a pre-unboxed closure patch [here](https://github.com/Manishearth/hyper/commit/a815cddecfa1d1ac86b436bf1456c87b6ed06552), if its design feels okay I can move it to unboxed closures.

**Comment by seanmonstar** [comment]
Makes sense to me!
