### ISSUE TITLE
Need to document how to clone clonable objects like Arc<> into a service_fn() in Hyper

### ISSUE THREAD

**Issue by adamierymenko** [hyperium/hyper#2446]
In the existing example code, the way to get your own clonable objects like Arc<> into a Hyper service is extremely non-obvious. It took me hours to figure it out. Sure more experience Rust users might find it easier, but it'd be helpful to newer Rust programmers to show and explain such a common thing. Also doesn't help that async is newer in Rust and documentation for how to do common things in async is still somewhat sparse.

Here's how I did it:

```
        let service = service.clone();
        let server = tokio::task::spawn(builder.serve(make_service_fn(move |_| {
            let service = service.clone();
            async move {
                Ok::<_, Infallible>(service_fn(move |req: Request<Body>| {
                    let service = service.clone();
                    async move {
                        web_handler(service, req).await
                    }
                }))
            }
        })).with_graceful_shutdown(async { let _ = shutdown_rx.await; }));
```

**NOTE**: `service` is something from my code, not the hyper "service."

The "service" is an Arc<> containing a Sync+Send object. If you do the obvious thing and use simple "async move" closures, you get some rather cryptic errors about inability to move blah blah blah. You instead have to give it conventional function closures that clone the object and then return an async closure with a copy per async closure.

This way clone() happens for each web request and you get the expected behavior of Arc<> in the context of asynchronous "pseudo-threads." (Async tasks are not threads but can be thought of as almost threads re: ownership and reference counting semantics.)

**Comment by davidpdrsn** [comment]
I have been in the exact same situation several times and I agree the errors messages aren't great. I'll try and work on adding a better example to [the server docs](https://docs.rs/hyper/0.14.7/hyper/server/index.html).

For your particular example I would probably write it like this:

```rust
let service = service.clone();

let hyper_service = service_fn(move |req: Request<Body>| web_handler(service.clone(), req));

let make_service = make_service_fn(move |_| {
    let hyper_service = hyper_service.clone();
    async move { Ok::<_, Infallible>(hyper_service.clone()) }
});

let server = builder.serve(make_service).with_graceful_shutdown(async {
    let _ = shutdown_rx.await;
});

let server_join_handle = tokio::task::spawn(server);
```

I haven't actually tested this but I believe it should compile. Its not a big improvement but might be slightly easier to read.

I'm also working on a fix for https://github.com/hyperium/hyper/issues/2154 which will improve the ergonomics quite a bit.
