### ISSUE TITLE
How to implement hyper request timeout 

### ISSUE THREAD

**Issue by kushwahashiv** [hyperium/hyper#2448]
Hi All

I'm facing hyper request timeout implement/migration issue. earlier implementation is similar to below
https://github.com/hyperium/hyper/issues/1097

Now I am not sure what is the best practice to implement request timeout using futures and tokio.

Any link or help will be appreciated. I tried finding but could not find one.

Thanks in advance.

/Shiv

**Comment by davidbarsky** [comment]
Does something like this help  (`timeout` is https://docs.rs/tokio/1.2.0/tokio/time/fn.timeout.html)?

```rust
use hyper::{Client, Uri};
use tokio::time::timeout;
use std::time::Duration;

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let client = Client::new();
    let future = client.get(Uri::from_static("http://httpbin.org/ip"));
    
    match timeout(Duration::from_millis(30), future).await {
        Ok(_) => println!("Got response"),
        Err(_) => println!("timed out"),
    };
    
    Ok(())
}
```
