### ISSUE TITLE
Defends against slow HTTP attacks.

### ISSUE THREAD

**Issue by silence-coding** [hyperium/hyper#2457]
I think hyper needs to add capabilities such as client_header_timeout and client_body_timeout to defend against slow attacks.

The Nginx defense method is as follows:
https://www.nginx.com/blog/mitigating-ddos-attacks-with-nginx-and-nginx-plus/#client_header_timeout

**Comment by mjbshaw** [comment]
Should #2675 have fully closed this? Seems like the second half of this issue is `client_body_timeout`, which is still unimplemented.

**Comment by seanmonstar** [comment]
I believe a user can handle a body timeout outside of a hyper, since you can add a timeout to any waiting on a body chunk. Is there something specific about it that hyper would need to do directly?

**Comment by mjbshaw** [comment]
Yeah, that should be sufficient. Sorry; when I read #2675 I noticed it said it partially addressed this issue, and that this issue's second half was `client_body_timeout`. But you're right. Thanks!

**Comment by DFINITYManu** [comment]
PR #2675 does not actually defend against slowloris attacks.  From my comment there:

> Valiant effort, but still there is no way to set a timeout for clients that connect only to send no data (by experimentation I discovered that the timeout does not fire if I just telnet into the TCP port and hang on there -- it only fires if I send the actual headers too late). Which means it's trivial to gum up a hyper server just by sending a lot of connections and nothing else.
