### ISSUE TITLE
http1 options are exposed through client::Builder but not lower-level client::conn::Builder interface

### ISSUE THREAD

**Issue by acfoltzer** [hyperium/hyper#2461]
`http1_read_buf_exact_size`, `http1_max_buf_size`, and `http1_title_case_headers` are all configuration methods on `hyper::client::Builder`, but not `hyper::client::conn::Builder`. I notice that the methods are present on the latter type but are `pub(super)` rather than `pub`. 

Currently, I believe users of the `conn` interface are stuck with the default values of these settings. Are there any reasons not to make these `pub` with similar docstrings to the higher-level API? I'd be happy to provide a PR if not.

**Comment by seanmonstar** [comment]
I believe it is simply an oversight. I'd say more of the builder options also make sense on the `conn` types (besides pooling, listener config, the obvious).
