### ISSUE TITLE
Access rustls::Session from hyper::Service

### ISSUE THREAD

**Issue by ipetr0v** [hyperium/hyper#2463]
Currently the parameters of [`hyper::Service::call`](https://docs.rs/hyper/0.14.4/hyper/service/trait.Service.html#tymethod.call) only include a [`Request`](https://docs.rs/hyper/0.14.4/hyper/struct.Request.html). And I'm curious if it's possible to access TCP/TLS connection internals somewhere from the [`Service`](https://docs.rs/hyper/0.14.4/hyper/service/trait.Service). For example access [`rustls::Session`](https://docs.rs/rustls/0.19.0/rustls/trait.Session.html) .

Accessing TLS session could be useful for multiple reasons, for example for implementing applications that rely on the [TLS Keying Material](https://tools.ietf.org/html/rfc5705) (provided by [`rustls::Session::export_keying_material`](https://docs.rs/rustls/0.19.0/rustls/trait.Session.html#tymethod.export_keying_material)).

Originally posted in https://github.com/ctz/hyper-rustls/issues/146

cc @tiziano88

**Comment by seanmonstar** [comment]
If it's connection related data, you could collect that and make it part of your `impl Service`, such that on each request you can just access `self.tls_session` or what-not.

For example:

```rust
// probably in a while loop?
let socket = listener.accept().await?;

// probably spawn the TLS handshake into a new task to not block the accept loop?
let tls = rustls_accept(socket, config).await?;

let session = tls.session().clone();
let svc = MyAppSvc { session };
hyper::server::conn::Http::new().serve_connection(tls, svc).await?
```

**Comment by ipetr0v** [comment]
Is it possible to do a similar thing on the client side?

IIUC there is an [`HttpsConnector::call`](https://docs.rs/hyper-rustls/0.22.1/hyper_rustls/struct.HttpsConnector.html) that can return a [`TlsStream`](https://docs.rs/tokio-rustls/0.22.0/tokio_rustls/client/struct.TlsStream.html), from which TLS session can be accessed.

But the problem is that there is no way to use this session afterwards with [`hyper::Client`](https://docs.rs/hyper/0.14.7/hyper/client/struct.Client.html), because it will try to create a new session, since it has already been `call`ed.

**Comment by sfackler** [comment]
You can make a wrapper around the HttpsConnector that adds whatever data you need via the [`Connected::extras`](https://docs.rs/hyper/0.14.7/hyper/client/connect/struct.Connected.html#method.extra) method, which will end up in the extensions field in the response.

**Comment by ipetr0v** [comment]
The question is more about how to extract a `TlsSession` (and corresponding KeyingMaterial), while still being able to use `hyper::Client` to connect to the server.

**Comment by ipetr0v** [comment]
If I understand correctly, the only way to access [`TlsStream`](https://docs.rs/tokio-rustls/0.22.0/tokio_rustls/client/struct.TlsStream.html) is to do [`HttpsConnector::call`](https://docs.rs/hyper-rustls/0.22.1/hyper_rustls/struct.HttpsConnector.html)
```rust
let mut https_connector = hyper_rustls::HttpsConnector::from((http_connector, tls_config));
let mut https_stream = https_connector.call(dst).await.unwrap();
let keying_material = match https_stream {
    MaybeHttpsStream::Https(ref mut tls_stream) => {
        let (tcp_stream, session) = tls_stream.get_mut();
        KeyingMaterial::export(session).expect("Couldn't generate keying material")
```

But the problem is that I cannot use this `https_connector` in the `Client` after this, since it already created a connection, and the `Client` will just create a new TLS connection.

I also tried to create a custom `HttpsConnector` and do all the keying material negotiation inside the `call` function:
```rust
impl<T> Service<Uri> for CustomConnector<T>
...
    fn call(&mut self, dst: Uri) -> Self::Future {
        let http_connector = self.http_connector.clone();
        let tls_config = self.tls_config.clone();
        let result = async move {
            let mut https_connector = hyper_rustls::HttpsConnector::from((http_connector, tls_config));
            let mut https_stream = https_connector.call(dst).await.unwrap();
            match https_stream {
                MaybeHttpsStream::Https(ref mut tls_stream) => {
                    let keying_material = {
                        let (tcp_stream, session) = tls_stream.get_mut();
                        KeyingMaterial::export(session).expect("Couldn't generate keying material")
                    };
                    // Send keying material in a separate HTTP request.
            Ok(https_stream)
        };
        Box::pin(result)
    }
```

But the problem is similar: once I get `tls_stream`, I cannot use `hyper::Client` and have to send and receive raw HTTP requests through [`tokio_rustls::client::TlsStream`](https://docs.rs/tokio-rustls/0.22.0/tokio_rustls/client/struct.TlsStream.html).
