### ISSUE TITLE
Support multiple Content-Length values

### ISSUE THREAD

**Issue by ghostd** [hyperium/hyper#2470]
Hi,

I try to work on some [failing tests](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/fetch/content-length/resources/content-lengths.json) of servo. To summarize the issue : the `fetch` specification has been recently updated to handle multiple values for the [`Content-Length` header](https://fetch.spec.whatwg.org/#content-length-header). I found Hyper client does not handle the header as expected by the specification. To be more precise, hyper does not handle the multiple values into only one header entry : `Content-Length: 42,42`. I don't know if we want to update hyper to follow this specification or not.

I reproduced the error with the [example client](https://github.com/hyperium/hyper/blob/master/examples/client.rs) and the following node http server code:
```js
var http = require('http');

http.createServer(function (req, res) {
    res.writeHead(200, {'Content-Length': '42,42'});
    res.write('012345678901234567890123456789012345678901');
    res.end();
}).listen(8080);
```

**Comment by seanmonstar** [comment]
I coulda sworn hyper supported this, and so dug a little. hyper _does_ correctly support if the multiple values are on multiple lines, but not if comma-separated. So, this works:

```
HTTP/1.1 200 OK
content-length: 3
content-length: 3

hey
```

But not `content-length: 3,3`. Seems like something to fix, and add a test case for.

**Comment by seanmonstar** [comment]
The relevant code is this function: https://github.com/hyperium/hyper/blob/eb0e7186963bbe4fa1ad4478ac493f75ddc92ae5/src/headers.rs#L40

**Comment by ghostd** [comment]
Ok, i'll provide a PR

**Comment by shadowcat-mst** [comment]
@seanmonstar it's not particularly important now, but the original ticket did say "to be more precise, hyper does not handle the multiple values into only one header entry" - which I read as meaning that multiple header entries would work as you independently found. No harm in you having dug to confirm it, obviously, but a principle of "credit where due" meant it seemed worth pointing out that @ghostd had spotted that bit already too :)
