### ISSUE TITLE
Support the HTTP status code parsing as defined by the fetch specification

### ISSUE THREAD

**Issue by ghostd** [hyperium/hyper#2477]
Hi,

The [fetch specification](https://fetch.spec.whatwg.org/#statuses) updated its requirements to parse the HTTP status code. The update makes the parser less strict than the HTTP specification, the allowed range is 0 <= status code <= 999.

The WPT tests are [here](https://github.com/web-platform-tests/wpt/blob/master/fetch/h1-parsing/status-code.window.js)

Will you accept a PR to extend the hyper implementation or do you prefer to stick to the stricter HTTP specification?

It seems a potential PR would involve [hyperium/http](https://github.com/hyperium/http/blob/master/src/status.rs) and something else?

Regards

**Comment by seanmonstar** [comment]
🤔 Hm, I'm pretty sure that change in the Fetch spec is *wrong*. The same working group thinks differently in [this issue](https://github.com/httpwg/http-core/issues/684). Even if not, there's far too many parsers that assume the `3DIGIT` rules for parsing a status code, so it's just not practical to make 0-99 valid status codes.

**Comment by ghostd** [comment]
You're right, the issue you're pointing led to this [explicit commit](https://github.com/httpwg/http-core/commit/39bcebb43e8b270d8c97389de16c5e8b2e46664c).
It seems the fetch authors wish to accept some [legacy behaviors](https://github.com/whatwg/fetch/issues/1142#issuecomment-764456981)... not sure how to handle this in servo :-/
