### ISSUE TITLE
How to use Server in V1.4.*

### ISSUE THREAD

**Issue by daiguadaidai** [hyperium/hyper#2493]
hyper version: 1.4.*
in `lib.rs` file:
```
cfg_feature! {
    #![all(feature = "server")]

    pub mod server;
    #[cfg(any(feature = "http1", feature = "http2"))]
    #[doc(no_inline)]
    pub use crate::server::Server;
}
``` 
IDE`Clion+Rust Pulgin` can not import `Server`

hyper version: 1.3.*
```
pub use crate::server::Server;
...
pub mod server;
``` 
IDE can import `Server`

**Comment by davidbarsky** [comment]
Try declaring the `hyper` dependency in your `Cargo.toml` with the `full` feature flag:

```toml
hyper = { version = "0.14", features = ["full"] }
```

The documentation explains what `full` enables: https://docs.rs/hyper/0.14.5/hyper/#optional-features.
