### ISSUE TITLE
Document that hyper is using tracing

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2498]
The main `lib.rs` page would benefit from a section explaining how to view logs in hyper.

**Comment by nox** [comment]
Would it be best to do that while carrying #2261 to completion?

**Comment by seanmonstar** [comment]
I think they can happen separately. Really, a larger tracing effort would be good to organize for hyper, as there's several metrics people would like to know, and some simple placement of spans and proper key-value designations in some events in hyper could allow them to more easily get that info.

**Comment by taqtiqa-mark** [comment]
@seanmonstar not sure if the docs [here](https://github.com/hyperium/hyper/pull/2697/files?authenticity_token=QGM7ib6nf7liG6WrZAmg%2BCGdlgERiX0%2FN%2Fm24OaG7k76wriSEm07gDh3mvkLsAgxXzTqW68HZq44qTswA4Qeig%3D%3D&file-filters%5B%5D=.rs#diff-8e6412c29b9579988c7b6c7620cc1c903e312f50482ee8687281cd20aaf8d314) are sufficient to close this? 

 They'll expand as the implementation roles out, but right now have a 10,00ft view of what tracing in Hyper means (OTel semantic conventions).

**Comment by seanmonstar** [comment]
The 1.0 docs now mention that `tracing` is available as an unstable feature. I think that's enough for now.
