### ISSUE TITLE
How to get response headers size in bytes

### ISSUE THREAD

**Issue by let4be** [hyperium/hyper#2501]
For statistical purposes I would like to record exact size of headers in an http response(n of bytes), is this possible?

I guess I could estimate this size by running across `headers()` and summing string lengths, but this seems dirty and slow. Is there a better way?

**Comment by seanmonstar** [comment]
The number would be different depending on HTTP/1 and HTTP/2. In HTTP/1, hyper emits a trace event about bytes read and parsed into headers. We could probably make that a slightly better structured `tracing` event with better key/values, so that you can then grab it in a tracing subscriber.
