### ISSUE TITLE
【Help】【H2】 manany request is pending

### ISSUE THREAD

**Issue by silence-coding** [hyperium/hyper#2503]
We use Hyper + Rustls to develop a proxy service as the entrance to the website. After H2 is enabled for the proxy service (other backend services do not enable H2), there is a possibility that a large number of pending pages may be generated. You must close all tabs of the browser before you can access it again. Strangely, the response header has been received in the pending request. When H2 is not enabled, there is no large number of pending requests.
![image](https://user-images.githubusercontent.com/32766901/114882454-8c0cbe00-9e36-11eb-8e9d-752d900a4429.png)
![image](https://user-images.githubusercontent.com/32766901/114882658-bfe7e380-9e36-11eb-94a9-2c92f0fc676e.png)

Only these are the exception logs.:
[2021-04-15 22:06:13 WARN hyper::proto::h2 63] Connection header illegal in HTTP/2: connection
[2021-04-15 22:06:13 WARN hyper::proto::h2 63] Connection header illegal in HTTP/2: connection
[2021-04-15 22:06:13 WARN hyper::proto::h2 63] Connection header illegal in HTTP/2: connection
[2021-04-15 22:07:12 WARN hyper::proto::h2 45] Connection header illegal in HTTP/2: keep-alive
[2021-04-15 22:07:12 WARN hyper::proto::h2 63] Connection header illegal in HTTP/2: connection

**Comment by seanmonstar** [comment]
Hm, strange. It's "pending" even though you've received the headers? Do they not include a status code? They probably do... How are you using hyper and h2? What version are you using, and how are you configuring the server?

**Comment by silence-coding** [comment]
I use the hyper server to receive the request from the browser and then forward the request to the backend service through the hyper client according to internal rules. If all  use HTTP1/1, not found a large number of pending requests. However, when H2 is used from the browser to the hyper server and Http1/1 is used from the hyper client to the backend service, a large number of pending requests occasionally occur.



Hyper 0.13.7  tokio-rustls 0.13.1  tokio 0.2.13


configuring like that
`
server:

let incoming = hyper::server::accept::from_stream(incoming);
hyper::Server::builder(incoming)
        .http1_max_buf_size(sctx.accept.http1_max_buf_size)
        .http1_half_close(true)
        .serve(hyper::service::make_service_fn(service)
        .with_graceful_shutdown(xxx).await

client:
impl Service<Uri> for HttpConnector {
     type Response = HttpConnection;
}
impl Connection for HttpConnection {
   fn connected(&self) -> Connected {
        let c = Connected::new();
        if self.h2 {
            c.negotiated_h2()
        } else {
            c
        }
    }
}
`

**Comment by silence-coding** [comment]
Firefox also has this problem.

**Comment by seanmonstar** [comment]
Are all the requests using the same connection, or are they using different connections?

**Comment by silence-coding** [comment]
same connection

**Comment by silence-coding** [comment]
I've updated with more information on this issue at https://github.com/hyperium/h2/issues/573

**Comment by silence-coding** [comment]
@seanmonstar Can you help me see if my tests and guesses are correct?
According to the current test, the pending cause may be that the value of http2_initial_connection_window_size is smaller than the value of initial_stream_window_size. As a result, packets on a stream occupy the connection for a long time, and requests on other stream can only wait.

**Comment by silence-coding** [comment]
It's a problem in H2, and I'm going to close the hyper issue.
