### ISSUE TITLE
Support CONNECT over h2

### ISSUE THREAD

**Issue by nox** [hyperium/hyper#2508]
There is [a h2 issue](https://github.com/hyperium/h2/issues/234) but even if support for CONNECT was perfect in h2, there are still details to sort out on hyper itself too. I'm filing this issue because I started working on that today and will probably need some help.

**Comment by nox** [comment]
AFAICT for the client part we mostly want to patch this match arm:

https://github.com/hyperium/hyper/blob/117cc492a62c4051c75e7eec0f624b30db8a20e5/src/proto/h2/client.rs#L217-L290

Specifically, ultimately we want to patch this snippet so that it inserts an `OnUpgrade` extension in the returned response, with its inner oneshot channel already sent to with a `Upgraded` built from the `SendStream<_>` that was returned by `self.h2_tx.send_request` and the `RecvStream` returned from the `ResponseFuture`:

https://github.com/hyperium/hyper/blob/117cc492a62c4051c75e7eec0f624b30db8a20e5/src/proto/h2/client.rs#L270-L280

The first issue I'm experiencing is that the `SendStream<_>` is a `SendStream<SendBuf<B as Body>::Data>>` and we need this to be the `AsyncWrite` half of the `Upgraded` IO object and I have no damn clue how we can possibly do that.

**Comment by nox** [comment]
I guess I can change the struct `SendBuf` to an enum like this:

```rust
enum SendBuf<B> {
    Buf(B),
    Cursor(Cursor<Box<[u8]>>),
    None,
}
```

where `SendBuf::Cursor` is only ever used in the impl of `AsyncWrite` for the h2 upgraded stream.

**Comment by nox** [comment]
To implement `AsyncRead` over `RecvStream`, I need https://github.com/hyperium/h2/pull/532.

**Comment by nox** [comment]
I'm also not exactly sure what `poll_flush` and `poll_shutdown` should do.

**Comment by nox** [comment]
AFAIK `poll_shutdown` can just send an empty data frame with the EOS flag set, but we definitely need something in h2 to properly implement `poll_flush`.

**Comment by nox** [comment]
So, I implemented `poll_flush` as a noop and tried adding upgrades to the server-side of Hyper, and I encountered a quite pesky blocker.

To implement `Io` over an H2 stream, I wrote this:

```rust
struct H2Upgraded<B>
where
    B: Buf,
{
    ping: Recorder,
    send_stream: SendStream<SendBuf<B>>,
    recv_stream: RecvStream,
    buf: Bytes,
}

impl<B> AsyncRead for H2Upgraded<B>
where
    B: Buf,
{
    fn poll_read(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        read_buf: &mut ReadBuf<'_>,
    ) -> Poll<Result<(), io::Error>> {
        let mut polled_stream = false;
        Poll::Ready(loop {
            if !self.buf.is_empty() {
                let cnt = std::cmp::min(self.buf.len(), read_buf.remaining());
                read_buf.put_slice(&self.buf[..cnt]);
                self.buf.advance(cnt);
                let _ = self.recv_stream.flow_control().release_capacity(cnt);
            }
            if polled_stream || read_buf.remaining() == 0 {
                break Ok(());
            }
            debug_assert!(!self.buf.is_empty());
            self.buf = match ready!(self.recv_stream.poll_data(cx)) {
                None => break Ok(()),
                Some(Ok(buf)) => {
                    self.ping.record_data(buf.len());
                    buf
                }
                Some(Err(e)) => {
                    return Poll::Ready(Err(h2_to_io_error(e)));
                }
            };
            polled_stream = true;
        })
    }
}

impl<B> AsyncWrite for H2Upgraded<B>
where
    B: Buf,
{
    fn poll_write(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &[u8],
    ) -> Poll<Result<usize, io::Error>> {
        if buf.is_empty() {
            return Poll::Ready(Ok(0));
        }
        self.send_stream.reserve_capacity(buf.len());
        Poll::Ready(match ready!(self.send_stream.poll_capacity(cx)) {
            None => Ok(0),
            Some(Ok(cnt)) => self.write(&buf[..cnt], false).map(|()| cnt),
            Some(Err(e)) => Err(h2_to_io_error(e)),
        })
    }

    fn poll_flush(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Result<(), io::Error>> {
        Poll::Ready(Ok(()))
    }

    fn poll_shutdown(
        mut self: Pin<&mut Self>,
        _cx: &mut Context<'_>,
    ) -> Poll<Result<(), io::Error>> {
        Poll::Ready(self.write(&[], true))
    }
}
```

So far so good, right?

Then in the server code, I pass an `H2Upgraded` to `Upgraded::new` and this is where I am stuck.

`Upgraded` wants a `Send` I/O object, but all we get from the `h2` crate is a `SendStream<SendBuf<<B as Body>::Data>`, and the system has no `Send` bound on `B::Data`. I'll try to propagate this bound everywhere but AFAIK that's a breaking change.

**Comment by nox** [comment]
Ah right, it also wants `B::Data` to be `'static`.

**Comment by jvimal** [comment]
@nox Thanks for implementing this -- is it complete so I can give it a try?

I kind of worked around this by issuing a lower-case "connect" request and passing around a streaming body for the "connect" request.  The streaming body is basically one end of the pipe (I used tokio's DuplexStream, but I just need a HalfDuplexStream).  The other end of this pipe, and the response's streaming body become a custom H2Upgraded struct that satisfies the trait bound `AsyncRead+AsyncWrite+Unpin+'static`, so I can use it anywhere to spawn servers or whatever.

**Comment by nox** [comment]
This PR only includes support for CONNECT over h2 on the server side, not the client, but yeah it works!
