### ISSUE TITLE
404 link in HeaderMap docs

### ISSUE THREAD

**Issue by malaire** [hyperium/hyper#2518]
The `HeaderName` link here is 404:
https://docs.rs/hyper/0.14.7/hyper/struct.HeaderMap.html

**Comment by mohsen-alizadeh** [comment]
Created a PR to fix this

https://github.com/hyperium/hyper/pull/2525

**Comment by davidpdrsn** [comment]
Fixed in https://github.com/hyperium/hyper/pull/2525
