### ISSUE TITLE
Returning a byte array as server response

### ISSUE THREAD

**Issue by fctorial** [hyperium/hyper#2519]
I'm getting an error saying:

    the trait `HttpBody` is not implemented for `&'static [u8]`

If I try to return a byte array with the server response. This is a minimal example that demonstrates this issue:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=38435dcc56380800b437eba37344a828

What is the correct way of returning a byte array with response?

**Comment by fctorial** [comment]
I think I need to wrap the byte array and implement `HttpBody` for the wrapper, but I'm struggling with the implementation. This is what I came up with:

```
struct S {
    bs: Option<&'static [u8]>
}

impl HttpBody for S {
    type Data = &'static [u8];
    type Error = std::io::Error;

    fn poll_data(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Result<Self::Data, Self::Error>>> {
        Poll::Ready(match self.bs {
            None => None,
            Some(bs) => Some(Ok(bs))
        })
    }

    fn poll_trailers(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<Option<HeaderMap>, Self::Error>> {
        Poll::Ready(Ok(Some(HeaderMap::default())))
    }
}
```

If I run this code, the `poll_data` function is called repeatedly and cpu usage of one core is maxed out. How do I implement this trait for byte arrays?

**Comment by paolobarbolini** [comment]
What you'll probably want to use is [`hyper::Body`](https://docs.rs/hyper/0.14.7/hyper/struct.Body.html), which already implements `HttpBody`
