### ISSUE TITLE
Mucell often breaks Hyper

### ISSUE THREAD

**Issue by pyfisch** [hyperium/hyper#252]
Mucell breaks Hyper really often. Like for example just now: https://travis-ci.org/hyperium/hyper/builds/47357537 I do not really know what mucell makes it superior to the standard library types, but for me it looks like it only provides a minor speed increasement. So do we really need it or could we switch to another builtin type?

**Comment by reem** [comment]
@pyfisch it's fixed now, but I do see your concern.

**Comment by seanmonstar** [comment]
I guess a benchmark (of hyper) using both mucell and refcell would be useful to know if it's worth using something outside of std.
