### ISSUE TITLE
Header parsing and formatting methods.

### ISSUE THREAD

**Issue by pyfisch** [hyperium/hyper#253]
## Current state ##
Currently headers have one method for parsing: `Header` `fn parse_header(raw: &[Vec<u8>]) -> Option<Self>` that accepts a vector of slices of bytes.

To format headers we use `HeaderFormat` `fn fmt_header(&self, fmt: &mut fmt::Formatter) -> fmt::Result;`. This method accepts a formatter and returns a string. This means there is currently no way to format a header containing binary. This is allowed by the RFCs but discouraged, headers should be ASCII. (All our headers fail to parse if there are non UTF-8 sequences contained in the value)

## Proposal ##
As discussed in #243 we need to pass context to the parsing function. This means adding an extra argument. Since our headers all work with UTF-8 only, and it is unlikely to change we do not really need a method to pass bytes to headers. If one wants to access the byte slice they can still use the raw headers.

So I propose to create parsing functions like this:
```rust
pub trait ParseHeader {
    fn parse_header<T: HttpContext>(v: &[&str], context: &T) -> Option<Self>;
}

// As a shortcut to create headers, works only for single headers
pub trait FromStr {
    // Calls from_str_with_context with empty context
    fn from_str(s: &str) -> Option<Self>;
}
```

The formatting function should be `std::fmt::String` and replace `fmt_header`. The `Show` trait can use the default implementation provided by Rust.

With this proposal hyper headers use a minimum of custom traits and fit well into Rust.

Unsolved problems: Set-Cookie header should not be folded. Currently we use a hack to format multiple Set-Cookie fields: https://github.com/hyperium/hyper/blob/master/src/header/common/set_cookie.rs#L51

**Comment by reem** [comment]
Just a note, but it would have to be `&[String]`, since `&[&str]` implies that you have a backing `Vec<&str>`, which we don't.

**Comment by reem** [comment]
Closing because this is stale, feel free to bring it up again.
