### ISSUE TITLE
Statically linked program segfaults

### ISSUE THREAD

**Issue by fctorial** [hyperium/hyper#2537]
This project uses `+crt-static` feature to build a statically linked executable.

[hyper_segfault.zip](https://github.com/hyperium/hyper/files/6426302/hyper_segfault.zip)

You can run the program with `cargo run --target x86_64-unknown-linux-gnu`, it will segfault after a minute or so.

```
$ cargo --version
cargo 1.51.0 (43b129a20 2021-03-16)
$ uname -a
Linux nixos 5.10.15 #1-NixOS SMP Wed Feb 10 08:29:23 UTC 2021 x86_64 GNU/Linux
```

**Comment by fctorial** [comment]
Correct demo project:

[hyper_segfault.zip](https://github.com/hyperium/hyper/files/6426302/hyper_segfault.zip)

**Comment by seanmonstar** [comment]
Huh... Could you include more debug info? Does it output a message or dump when segfaulting? Could you use something `gdb` to grab the stack frame before it aborts?

**Comment by fctorial** [comment]
This is the stacktrace: https://gist.github.com/fctorial/2bf62e46da319181bd8c66f155ffac0f

It was generated using this `main.rs`:

```
use hyper::{Request, Method, Body};
use hyper::client::Client;
use hyper::header::CONTENT_TYPE;
use hyper::Error;
use std::time::Duration;

static URI : &str = "http://jsonplaceholder.typicode.com/posts";
async fn request() -> Result<String, Error> {
    let req = Request::builder()
        .method(Method::POST)
        .uri(URI)
        .header(CONTENT_TYPE, "application/json")
        .body(Body::from(format!("{{\"n\": {}}}", 1))).unwrap();
    let client = Client::new();
    let resp = client.request(req).await?;
    return Ok(std::str::from_utf8(hyper::body::to_bytes(resp.into_body()).await?.as_ref()).unwrap().to_string());
}



#[tokio::main]
pub async fn main() {
    loop {
        println!("{:?}", request().await);
        std::thread::sleep(Duration::from_secs(10));
    }
}
```

**Comment by fctorial** [comment]
The glibc version is `2.31-74`

**Comment by sfackler** [comment]
Statically linking to glibc is not really supported, particularly for gethostbyname which needs to dynamically link to libnss: https://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo.

You should build against MUSL libc if you want a fully static binary.
