### ISSUE TITLE
How do I use persistent connections (keepalives) in the client?

### ISSUE THREAD

**Issue by jkleint** [hyperium/hyper#255]
Re-using a Client and adding the KeepAlive header doesn't seem to do it.  If this is possible, can anybody share the basic idea or a quick example?

**Comment by seanmonstar** [comment]
It's not currently built into the Client. You could do so manually, using
Request and Response. But my next planned feature is a keepalive in the
Client.

**Comment by reem** [comment]
Closing as a dupe of #41
