### ISSUE TITLE
Support for digest authentication?

### ISSUE THREAD

**Issue by aar3** [hyperium/hyper#2552]
### Issue Type

- [x] Question
- [ ] Bug
- [ ] Feature request

### Description

Does hyper currently support digest authentication? I read over this thread here https://github.com/hyperium/hyper/issues/773, and saw the PR never went through. I'm currently trying to authenticate my hyper client request in the same way that `--digest` works with curL

Full curL command I'm trying to replicate is

```bash
curl \
-u foo:$MY_SECRET \
--digest \
http://1.1.1.1:5555/json_rpc \
-d '{"foo":"bar"}' \
-H 'Content-Type: application/json'
```

If hyper indeed _does not_ support this, can someone give best advice on a workaround? I'm on the 5 yard line, so it'd be pretty sucky to have to completely change my approach at this point.

### Version and Platform Specs

Cargo.toml dependencies

```text
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1", features = ["full"] }
bb8 = "0.7"
bb8-redis = "0.9"
futures-util = "0.3"
websocket = "0.26"
dotenv = "0.15"
dotenv_codegen = "0.15"
digest-headers = { version = "0.2", features = ["use_hyper"] }
```

Rust environment

```text
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.52.0-nightly (a15f484b9 2021-02-22)`
➜  xmrpcio git:(master) ✗ rustc --version
rustc 1.52.0-nightly (a15f484b9 2021-02-22)
```

Platform

Mac OSX Catalina 10.15

**Comment by davidpdrsn** [comment]
I'm working on an auth middleware in tower-http https://github.com/tower-rs/tower-http/pull/70.

It's still work in progress, and tower-http isn't on crates.io yet.

You might be able to get some inspiration there though.

You can also manually implement it in your request handler that you use when starting the hyper server.

**Comment by aar3** [comment]
@davidpdrsn Took a cursory look over the project, I'm guessing it plays nicely with Hyper?

Just for kicks I took a look at how Python's requests library implemented this [here](https://github.com/psf/requests/blob/f6d43b03fbb9a1e75ed63a9aa15738a8fce99b50/requests/auth.py#L108) and while it doesn't look crazy complex, it does look a bit more complex than I was willing to go

> You can also manually implement it in your request handler that you use when starting the hyper server

This was another approach I was thinking, however I couldn't find what the _exact_ implementation of this digest constitutes (which is why I had to see how the Python devs did it).

At first I thought it would be as simple has just hashing some data and including it in a header, but as I poke around, I'm seeing that `--digest` can actually be _way_ more complex than that (which is unfortunate)

**Comment by davidpdrsn** [comment]
> @davidpdrsn Took a cursory look over the project, I'm guessing it plays nicely with Hyper?

Yep very much by design. There is a hyper example in the root module docs https://github.com/tower-rs/tower-http/blob/master/tower-http/src/lib.rs#L48-L79.

I actually think I misread your OP. I thought you wanted "basic" auth. I actually don't anything about "digest auth" so its possible that it would be hard to implement manually. Sorry about that. tower-http doesn't have anything for digest auth but I guess it would make sense to add.

**Comment by aar3** [comment]
Closing this as I found a workaround using https://docs.rs/curl/0.4.6/curl/easy/struct.Easy.html
