### ISSUE TITLE
What does make_service_fn and service_fn mean?

### ISSUE THREAD

**Issue by kingluo** [hyperium/hyper#2554]
I found each HTTP request incoming, make_service_fn gets called once, and server_fn also gets called once.
What's the definition of make_service_fn and service_fn? Why not just one service function instead of two nested functions?

I am very confused, please help!

**Comment by seanmonstar** [comment]
Does looking at the [service](https://docs.rs/hyper/0.14.*/hyper/service/index.html) docs help?

**Comment by kingluo** [comment]
MakeService accepts connections, while Service handles requests of one connection.

My understanding is correct?

**Comment by davidpdrsn** [comment]
Yes that sounds correct.

Said with a few more words: `MakeService` receives the address of the incoming connection and produces a service that will handle requests from that connection. If your request handling code only cares about the request and not the connection then `MakeService` might seem a bit redundant. However some use cases requires the address as well for example to set the [`Forwarded` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) on responses.

I have a PR that adds a utility to bypass `make_service_fn` if you don't need it https://github.com/hyperium/hyper/pull/2541
