### ISSUE TITLE
Allows users to configure the idletimeout  and idle check interval.

### ISSUE THREAD

**Issue by silence-coding** [hyperium/hyper#2555]
The current idle check time and interval are the same parameter. The idle timeout and idle check interval can be configured separately.

https://github.com/hyperium/hyper/blob/4cd06bf25661d7e43e2fdf43eabdb8508055cf3a/src/client/pool.rs#L408
https://github.com/hyperium/hyper/blob/4cd06bf25661d7e43e2fdf43eabdb8508055cf3a/src/client/pool.rs#L448

**Comment by seanmonstar** [comment]
Could you explain the motivation for wanting to configure them separately? That it's an interval at all is just an internal detail that I wouldn't normally consider exposing, but I'm curious.

**Comment by silence-coding** [comment]
One way to configure idle time is to avoid that when the client sends a request, the server is disconnected. Therefore, a mandatory requirement is that the idle time configured on the client must be less than the idle time configured on the server.

**Comment by silence-coding** [comment]
The idle precision of the current implementation is poor. Therefore, the current practice is to set the idle time as conservative as possible.

**Comment by silence-coding** [comment]
Is there a follow-up to this question? If not, I will close this issue.
