### ISSUE TITLE
Which header is invalid?

### ISSUE THREAD

**Issue by bagder** [hyperium/hyper#2569]
Closely related to #2083: when we use curl+hyper to get a HTTP response the only error message hyper gives is `invalid HTTP header parsed` - which is really hostile in the cases we got maybe 20 different headers back and maybe we're not up to date on the details of the RFC.

We need a way for hyper to be more specific. Which exact header did it find a problem with? Example response to prove my point. This has an uppercase o instead of a zero in the Content-Length header.
~~~
HTTP/1.1 200 OK swsclose
Date: Tue, 09 Nov 2010 14:49:00 GMT
Server: test-server/fake
Last-Modified: Tue, 13 Jun 2000 12:10:00 GMT
ETag: "21025-dc7-39462498"
Accept-Ranges: bytes
Content-Length: 5O
Connection: close
Content-Type: text/html
Funny-head: yesyes
~~~

**Comment by seanmonstar** [comment]
Agreed, this can and should be better. As I fiddle around with this in the code base, there's two classes of "header parse error":

- Generic name-value parser noticed an illegal token
- A few key headers have their values checked for specific rules (like `content-length` or `transfer-encoding`)

It's straightforward to add specific messages for the more specific parsing.

The general token error, though, would be harder to report. At least for now, the general parser doesn't report more details of an invalid token. We could try, but the normal ways would be a "breaking change" to a separate dependency. Even then, if the token is in the middle of a name (name rules are stricter than values), we couldn't report much. Maybe the "position" of the first illegal byte.

Perhaps that's OK though, it would be far more common to have a bad content-length than to include an illegal header name.
