### ISSUE TITLE
`http1_preserve_header_case = true` has no effect

### ISSUE THREAD

**Issue by SergioBenitez** [hyperium/hyper#2574]
The docs currently state:

> Set whether HTTP/1 connections will write header names as provided at the socket level.

Presumably this means that if I set a header with specific casing, then Hyper will write that header out as written. Unfortunately there are no examples nor any more specific notes, so I apologize if I've arrived at the wrong conclusion about what this actually means.

Here's an application that does this without the desired effect:

```rust
use std::convert::Infallible;

use hyper::service::{make_service_fn, service_fn};
use hyper::{Body, Request, Response, Server};

async fn hello(_: Request<Body>) -> Result<Response<Body>, Infallible> {
    let response = Response::builder()
        .status(200)
        .header("X-Custom-Foo", "Bar")
        .body(Body::from("Hello, world!"))
        .unwrap();

    Ok(response)
}

#[tokio::main]
pub async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let make_svc = make_service_fn(|_conn| {
        async { Ok::<_, Infallible>(service_fn(hello)) }
    });

    let addr = ([127, 0, 0, 1], 3000).into();
    let server = Server::bind(&addr).http1_preserve_header_case(true).serve(make_svc);
    println!("Listening on http://{}", addr);
    server.await?;

    Ok(())
}
```

Here's a netcat-like log:

```
+ connected to 127.0.0.1:3000 (escaping, hex)
GET / HTTP/1.1\r\n\r\n
+ sent 18 byte(s) to remote
00000000 │ 47 45 54 20 2F 20 48 54 54 50 2F 31 2E 31 0D 0A │ GET / HTTP/1.1..
00000010 │ 0D 0A                                           │ ..
+ received 108 byte(s) from remote
< HTTP/1.1 200 OK
< x-custom-foo: Bar
< content-length: 13
< date: Wed, 09 Jun 2021 02:55:06 GMT
< Hello, world!
<00000000 │ 48 54 54 50 2F 31 2E 31 20 32 30 30 20 4F 4B 0D │ HTTP/1.1 200 OK.
<00000010 │ 0A 78 2D 63 75 73 74 6F 6D 2D 66 6F 6F 3A 20 42 │ .x-custom-foo: B
<00000020 │ 61 72 0D 0A 63 6F 6E 74 65 6E 74 2D 6C 65 6E 67 │ ar..content-leng
<00000030 │ 74 68 3A 20 31 33 0D 0A 64 61 74 65 3A 20 57 65 │ th: 13..date: We
<00000040 │ 64 2C 20 30 39 20 4A 75 6E 20 32 30 32 31 20 30 │ d, 09 Jun 2021 0
<00000050 │ 32 3A 35 35 3A 30 36 20 47 4D 54 0D 0A 0D 0A 48 │ 2:55:06 GMT....H
<00000060 │ 65 6C 6C 6F 2C 20 77 6F 72 6C 64 21             │ ello, world!
```

And `curl`:

```
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-custom-foo: Bar
< content-length: 13
< date: Wed, 09 Jun 2021 02:57:51 GMT
< 
* Connection #0 to host localhost left intact
Hello, world!% 
```

`x-custom-foo` is expected to be `X-Custom-Foo`. This is tested on ea8b0cd86efe7543d9f6d7d368b2596c7341fa76.

**Comment by seanmonstar** [comment]
Ah, this seems like a docs bug. It doesn't accurately describe what the option currently does.

Enabling that option will make hyper record the original cases into a type in the extensions, and if that type is present when _sending_, it will use those cases instead of the default. But we didn't make the type public, so there's no way to currently query what they were or set cases for outgoing.

**Comment by SergioBenitez** [comment]
Is there a means to preserve casing in the manner I had assumed this flag worked?

**Comment by nox** [comment]
No, but you can use `http1_title_case_headers` to title case all headers, and that will send `X-Custom-Foo`, `Content-Lenght` and `Date`.

**Comment by SergioBenitez** [comment]
How are header names stored internally? Will that option introduce overhead of any sort?

**Comment by davidpdrsn** [comment]
I'm still confused about what the option actually does 😜 I thought it worked the same way as Sergio is describing.

**Comment by seanmonstar** [comment]
The header names are stored in `http::HeaderMap` as an enum of either a variant for a common name, or as a lowercased version of the header name if not common.

The options to output different casings have some overhead: preserving the case includes a secondary mapping of names to cases, while the title-case option doesn't store anything extra, it just passes through a format function to map the first letter and ever letter after a dash as uppercase.
