### ISSUE TITLE
Allow a means to determine if the server has been successfully initialized

### ISSUE THREAD

**Issue by martinomburajr** [hyperium/hyper#2578]
It would be helpful for there to be a handler function that one can run right when the server has successfully began that can be used for various purposes e.g. printing a log that the server has been successfully initialized or even informing other services that the server is ready to accept requests.

```rust
// Build server
        let server = Server::builder(HyperAcceptor {
            acceptor: Box::pin(incoming_tls_stream),
        }).serve(service);

        // Run the future, keep going until an error occurs.
        println!("[https-server]: Starting to serve on https://{}.", config.fqdn);

        server
            .await
            .map(|v| {
                println!("STARTED SERVER!"); // This never executes unfortunately
            })
            .map_err(|e| {
                eprintln!("[https-server]: error: {:?}", e);
            })
            .unwrap();
```

**Comment by seanmonstar** [comment]
The server future doesn't finish when the server is started. You can print your message just before awaiting it (or spawning it in a task, etc).

**Comment by martinomburajr** [comment]
@seanmonstar thanks for the response. I see what you mean.

Is there a way to know when the server has fully initialized such that subsequent dependent actions can be taken e.g. kickoff a job, write logs, inform a local client that the server can now begin receiving requests etc?

**Comment by seanmonstar** [comment]
Once you've "built" the server, everything is ready at that point (I guess unless some custom acceptor internally will still delay accepting for some reason, but we can't know that). The only caveat is that if you do something _else_ before `await`ing the server future, since it's not being polled it cannot accept connections.
