### ISSUE TITLE
Manually creating Upgraded for testing purposes

### ISSUE THREAD

**Issue by ErwanDL** [hyperium/hyper#2579]
Hello, does the current `upgrade` API allow for manually creating an `Upgraded` object by any means ? I am trying to test a Websocket application using tokio-tungstenite + hyper, and can't seem to find a way to create an `Upgraded` object from a ` Request` without having to spin up a full-fledged Hyper server (which is very cumbersome for unit testing).

Here is my attempt (which panics because the `upgrade::on(req)` call returns a `NoUpgrade` error):
```rust
async fn create_ws() -> WebSocketStream<Upgraded> {
    let req = Request::builder()
        .header(header::UPGRADE, "websocket")
        .header(header::CONNECTION, "upgrade")
        .header(header::SEC_WEBSOCKET_VERSION, "13")
        .header(header::SEC_WEBSOCKET_KEY, "dGhlIHNhbXBsZSBub25jZQ==")
        .body(Body::empty())
        .unwrap();

    let ws = WebSocketStream::from_raw_socket(
        upgrade::on(req).await.unwrap(),
        protocol::Role::Server,
        None,
    ).await;
    ws
}
```

What is the recommended approach to doing this ?

PS: Thank you for the great work on hyper.

**Comment by seanmonstar** [comment]
There is no way to create an `Upgraded` manually. For testing purposes, you should be able to be generic over `T: AsyncRead + AsyncWrite`, and then provide some testing transport type (maybe from `tokio-test`).
