### ISSUE TITLE
Send the appropriate status code for parse errors

### ISSUE THREAD

**Issue by reem** [hyperium/hyper#258]
Right now we just `error!` when there is an error. This is bad and we should instead send correct responses, i.e. 413 if a header is too long.

**Comment by luxvio** [comment]
Hi !
I was looking at the issues and this one turned up a question for me: how headers are dealt with?   
   
I kinda had a clue looking at `hyper/src/http/h1.rs`, but I can't find references to how a a too long header field is dealt with (i.e: a Content-Type with an massive amount of chars as value) and how a massive amount of header fields is dealt with (I kinda crossed my eyes at MAX_HEADERS, but my Rust is not so advanced :c)

Ty for reading !

**Comment by xaviershay** [comment]
I tried and failed. Field notes:

Tried to write a test in `src/http/h1.rs` (after temporarily making `MAX_BUFFER_SIZE` public).

``` rust
    #[test]
    fn test_parse_too_large() {
        let mut request : Vec<u8> = b"GET / HTTP/1.1\r\nHost:  ".iter().cloned().collect();
        let mut long_header = vec!(b'X', MAX_BUFFER_SIZE as u8 + 1);
        let mut footer : Vec<u8> = b"\r\n\r\n".iter().cloned().collect();
        request.append(&mut long_header);
        request.append(&mut footer);
        let mut raw = MockStream::with_input(&request[..]);
        let mut buf = BufReader::new(&mut raw);
        println!("{:?}", parse_request(&mut buf));
    }
```

Was able to get a `Err(Header)` result, but then wasn't sure whether a) that was correct, or b) what might then map that to a status. I was trying to elicit an `Error::TooLarge` response from `parse` method (line 867):

``` rust
        match try!(rdr.read_into_buf()) {
            0 if rdr.get_buf().is_empty() => {
                return Err(Error::Io(io::Error::new(
                    io::ErrorKind::ConnectionAborted,
                    "Connection closed"
                )))
            },
            0 => return Err(Error::TooLarge),
            _ => ()
        }
```

`BufReader` itself won't return an error condition, it does call `try!(read)` on the internal buffer though. Couldn't figure a way to wire up `MockStream` to it in a way that would fail properly.

Then I tried a different approach: try to elicit failure with an end-to-end test.

``` rust
extern crate hyper;

use std::io::Read;

use hyper::Client;
use hyper::header::Connection;
use hyper::header::UserAgent;

fn main() {
    let client = Client::new();

    let res = client.get("http://localhost:3000/")
        .header(Connection::close())
        .header(UserAgent(std::iter::repeat("X").take(1000000).collect::<String>()))
        .send().unwrap();

    println!("{:?}", res.status);
}
```

This panics on the `unwrap`:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Custom(Custom { kind: ConnectionAborted, error: StringError("Connection closed") }) })',
```

Running against `http://google.com` (sorry google) I found a sweet spot at 100000 chars, where I get a `PayloadToLarge` response, which I can't get from hyper. Bigger than that I get a broken pipe error.

I also tested against a naive Ruby webrick server and wasn't able to get a failure, it just takes longer and longer to parse the request (seems bad).

Back to hyper, maybe the server is explicitly terminating the connection if some buffer size is exceeded? I tried using the server from the README and enabling logging with `export RUST_LOG=trace` (I see there are `trace!` calls already), but that only enabled tracing withing `cargo` and `rustc`, not my test binary or hyper. I placed a `println!` and a `trace!` next to each other right at the hyper entry point and only the `println!` worked.

Then I gave up :(

Potential next steps for anyone who wants to pick this up:

* Figure out how to enable tracing (this should be straightforward...)
* Find where (if?) hyper is explicitly closing the connection on large headers, using the test client code above.
* Work backwards from there.

**Comment by reem** [comment]
To enable logging with `RUST_LOG`, you need to initialize the logger implementation which reads that environment variable via the `env_logger` crate. Just add `env_logger::init().unwrap()` at the top of your main and run with `RUST_LOG=hyper=trace` to get all logs from hyper only.

**Comment by ctjhoa** [comment]
Hi @reem @seanmonstar,
I've made some work on this but I'm stuck with a test.
https://github.com/ctjhoa/hyper/commit/d1b4563ada8821df308cbd3ab88696fe854b5a50
In `test_check_error_431` the mock return 2 responses and I don't know why.

Can you tell me what am I doing wrong and if the structure meet your expectations?
Thanks.

**Comment by seanmonstar** [comment]
This will be deferred to the user's `Handler`, as described in #881
