### ISSUE TITLE
The URL needs to be normalized.

### ISSUE THREAD

**Issue by silence-coding** [hyperium/hyper#2580]
In the process of using the URL, I found that Hyper did not standardize the URL processing according to the URL standard, which I thought was unreasonable. Indicates whether to replace the underlying library. The [URL crate](https://crates.io/crates/url) is used to implement this function. 
```
    // url
    let expect = "https://github.com/rust/issues?labels=E-easy&state=open";
    let url_str = "https://github.com/rust-lang/../rust/issues?labels=E-easy&state=open";
    let url = Url::parse(url_str).unwrap();
    assert_eq!(expect, url.to_string());
    let url_str = "https://github.com/rust-lang/%2E./rust/issues?labels=E-easy&state=open";
    let url = Url::parse(url_str).unwrap();
    assert_eq!(expect, url.to_string());

    // hyper
    let url = hyper::Uri::from_str(url_str).unwrap();
    // panic, url not normalize
    assert_eq!(expect, url.to_string());
```

**Comment by silence-coding** [comment]
I've found that nginx has also fixed this problem, and I think hyper should also fix this problem, and if it can't be fixed in a short time, I expect hyper to display a declaration of this problem to let developers know.

```
http://nginx.org/en/CHANGES

Changes with nginx 1.17.5                                        22 Oct 2019

    *) Bugfix: "/." and "/.." at the end of the request URI were not
       normalized.
```

**Comment by davidbarsky** [comment]
Hyper uses *URI*s, not URLs. This means that the normalization you want won't happen in Hyper. See this discussion for more details: https://github.com/hyperium/http/issues/73.

**Comment by silence-coding** [comment]
@davidbarsky Thanks

**Comment by nox** [comment]
Closing this, Hyper is a lower-level HTTP library, normalizing has caused issues in the past for some proxies out there, it shouldn't be Hyper's job to do the normalizing.
