### ISSUE TITLE
Do not omit lower level underlying cause on failure in send_request_retryable

### ISSUE THREAD

**Issue by tomers** [hyperium/hyper#2590]
In `send_request_retryable` when failing on `dispatch dropped without returning error`, the lower level underlying cause is not shown and is muted, due to the use of `Err(_)` instead of `Err(err)`:

```rust
    pub(super) fn send_request_retryable(
        &mut self,
        req: Request<B>,
    ) -> impl Future<Output = Result<Response<Body>, (crate::Error, Option<Request<B>>)>> + Unpin
    where
        B: Send,
    {
        match self.dispatch.try_send(req) {
            Ok(rx) => {
                Either::Left(rx.then(move |res| {
                    match res {
                        Ok(Ok(res)) => future::ok(res),
                        Ok(Err(err)) => future::err(err),
                        // this is definite bug if it happens, but it shouldn't happen!
                        Err(_) => panic!("dispatch dropped without returning error"),
                    }
                }))
            }
```
This makes it hard to debug the cause of the issue. 
It would be really helpful to present the whole context of the error, starting from the outermost context to the innermost, as is done for example by [`anyhow::Context`](https://docs.rs/anyhow/1.0.21/anyhow/trait.Context.html).

**Comment by nox** [comment]
The error there is a [`tokio::sync::oneshot::error::RecvError`](https://docs.rs/tokio/1.11.0/tokio/sync/oneshot/error/struct.RecvError.html), which does not carry any more information, closing this issue.
