### ISSUE TITLE
About client side pipelining

### ISSUE THREAD

**Issue by qiujiangkun** [hyperium/hyper#2596]
I wanted to acheive maximum throghput in client side, and pipelining is a must. However, the current implementation (at least http/1.1 and connection pool) will not send a second request until the first one is completed.
![image](https://user-images.githubusercontent.com/33482468/125328469-ebfffb80-e376-11eb-9dff-8eef04cf31b9.png)

I managed to acheive one implementation, but requires some `pub` in `hyper` and modifications in `Conn`
https://github.com/qiujiangkun/speedy-http

I wonder could hyper expose more functions and make `Conn` pipelining compatible, or support it in hyper so that I don't have to roll my own.

**Comment by seanmonstar** [comment]
Hey there! hyper purposefully *doesn't* support HTTP/1.1 pipelining. HTTP/1 doesn't handle multiple requests simultaneously as well as HTTP/2. Problems with an early request can cause all the rest of the requests to fail and require being resubmitted. So, browsers have all disabled support as well, and it's largely a deprecated and dying feature of HTTP/1.
