### ISSUE TITLE
Hyper errors when unable to parse "a token" on poor network connectivity

### ISSUE THREAD

**Issue by DRG-developer** [hyperium/hyper#2606]
**Version**
No idea, all versions I tried, but the issue is hard to reproduce.

**Platform**
Linux pop-os 5.11.0-7614-generic #15~1618626693~20.04~ecb25cd-Ubuntu SMP Thu Apr 22 16:20:32 UTC  x86_64 x86_64 x86_64 GNU/Linux

**Description**
When on poor network connectivity, hyper will panic with the message "hyper::Error(Parse(Header(Token)))", with reqwest as the high level library

[short summary of the bug]

You make a request with poor network connectivity, and arround one in 3 times it fails, but not reliably. Curl works no problem.

[code sample that causes the bug]
#[tokio::main]
async fn main() {
    reqwest::get("https://cdiscount.com").await;
}

I expected to see this happen: 
No panic

Instead, this happened:
hyper::Error(Parse(Header(Token)))

Again, it's hard to reproduce this issue reliably, especialy since my network reliability has resolved itself (I was on vacation).

**Comment by seanmonstar** [comment]
I'm curious, does it actually `panic!`? Or does it just return an error?

**Comment by DRG-developer** [comment]
It actually paniced if i remember correctly, but i don't have logs of it anymore...

Though with logic it probably didn't panic.

**Comment by seanmonstar** [comment]
I don't think hyper will panic on that error, it will just return it. If you `.unwrap()`, that will panic if it's an error.

As for this error, I haven't been able to reproduce it. Are you able to reproduce and record what bytes are sent from the server?

**Comment by DRG-developer** [comment]
I asked in the tokio discord when i was having this issue if there was a way to print out the value as bytes that hyper couldn't parse, but that yielded no response (I asked it two times). The issue is only on poor network connectivity, so it probably has nothing to do with what bytes are send, but how the bytes are received.

**Comment by seanmonstar** [comment]
You can use a tool like Wireshark to intercept and view network traffic.

In reqwest itself, you can set `ClientBuilder::connection_verbose(true)`, and then enable logging for reqwest, and it will show you all the bytes reqwest writes and reads.

**Comment by seanmonstar** [comment]
I'm going to close as likely a transient network issue. If you can record the bytes that caused the problem, we can investigate further!
