### ISSUE TITLE
capi: hyper_waker_wake() accepts NULL pointer only to die a horrible death later on

### ISSUE THREAD

**Issue by bagder** [hyperium/hyper#2620]
**Version**
0.14.11 built from commit 684f2fa76d44fa2b

**Platform**
Linux

**Description**

I accidentally called `hyper_waker_wake()` with a NULL pointer argument.  That leads to a subsequent segfault deep inside hyper at a later point which makes it difficult to debug. (25 stack frames in from my C code no less).

I expected to see this happen: in a debug-version of hyper maybe an assert should trigger. Or the NULL should just be ignored. It should **not** lead to a crash much later (when the executor poll is called).

**Comment by seanmonstar** [comment]
Heh, yea, kaboom indeed. Several of the functions that return a `hyper_code` do check for any passed NULLs and return a "bad argument" error. Other functions that don't expect to fail, I could add a debug assert. Silently ignoring may make things worse...

**Comment by bagder** [comment]
Yes, I totally see how this was my fault. It just turned out rather hard to figure out exactly where the problem was since the crash happens so far away from my error.
