### ISSUE TITLE
ability to configure maximum connections

### ISSUE THREAD

**Issue by ahicks92** [hyperium/hyper#2640]
**Is your feature request related to a problem? Please describe.**
We're considering moving to Hyper for lower-level control of HTTP servers, in an environment with a lot of concerns around things like endpoint QoS and similar.  We want to be able to limit the maximum number of incoming connections that the server will accept, so that the internal backlogs don't grow forever (e.g., handle backpressure at the accept queue).

Currently Hyper doesn't appear to support this as far as I can find, and will just ingest and spawn connections as fast as it can.  We can probably use the low-level API for it, but it would be nice to not have to do so.

Sorry in advance if I'm missing something obvious.  If I am, then perhaps we should change this to a documentation problem.

**Describe the solution you'd like**

Something like `server::Builder::max_connections(128)` or similar, which will make Hyper wait until connections close before accepting new ones.

**Describe alternatives you've considered**

It looks like you can use the low-levle API but it would be really nice to have a plug-and-play solution.  I've also considered tower, but it looks like Tower middleware isn't going to play nice because of makeService.  I don't think you can handle backpressure until after the connections are accepted because you need middleware on MakeService but only the services used by the connection know enough to do it.  I've considered doing things with semaphores and Drop but that seems rather hacky unless Hyper is going to guarantee when services get dropped (e.g. maybe the service stays around too long, then it's stuck).

**Additional context**
Not much for this bit.  It's early days, I'm working on preparing a proposal for the team, and we need to be able to handle this one way or the other.

Nginx is a common solution, one which we do use, but we still want this in both places if we can get it.  being as it looks like we can write it ourselves, this is perhaps not super high priority.

**Comment by seanmonstar** [comment]
Looking at tower is definitely the right idea! It should be easier than you initially thought. The `MakeService` is used to create a service per connection, so you can make use of the [`ConcurrencyLimit`](https://docs.rs/tower/0.4.*/tower/limit/struct.ConcurrencyLimit.html) middleware. The `MakeService:poll_ready` is checked before accepting a new connection, so once the limit is reached, it will leave connections in the kernel queue, until some have finished.

You could use a `ServiceBuilder` to add other layers, but using just that one middleware can also be done like this:

```rust
let make_svc = make_service_fn(make_my_service);
let limited = ConcurrentLimit::new(make_svc, 128);

hyper::Server::bind(addr).serve(limited).await?;
```

**Comment by davidpdrsn** [comment]
I'm not confident but wouldn't `ConcurrentLimit::new(make_svc, 128)` mean that you can only have `128` "make service futures" running concurrently? Once the future resolves to a connection another connection can be established, even though the first connection is still being used. Once a response has been produced I don't think `ConcurrentLimit` is involved any longer.

**Comment by ahicks92** [comment]
The problem I see with this is that `MakeService` returns a service and doesn't handle the request.  Won't what you're suggesting basically do nothing, since the `MakeService` is done responding as soon as it hands out the service that will actually handle the requests, at which point tower lets more in even though they're still being handled?

**Comment by seanmonstar** [comment]
Whoops, yes, you're both absolutely correct. You'd need a `MakeService` that checks an `Arc<Semaphore>` in `poll_ready`, and then save the permit in the returned `impl Service`, so it lives as long as the connection/service do.

**Comment by ahicks92** [comment]
Can we consider that to be contractual though?  "Hyper will always drop your service promptly" seems like the kind of thing which is hard to break but also like the kind of thing that should be documented somewhere/guaranteed not to if we're going to rely on it.

but it would still be nice to see this, and maybe something else that makes this play nicer with Tower middleware.  I bet a lot of people are getting it wrong; in fact the only examples I could find of how to do it at all apply the middleware to the `MakeService`.

**Comment by sfackler** [comment]
If you want to have more control, you can also just handle the accept loop yourself and set up each connection individually rather than using `server::Builder`.

**Comment by seanmonstar** [comment]
hyper v1 no longer accepts connections, that's up to the application. The advice in here can help you, using a semaphore.
