### ISSUE TITLE
Panic via reqwest when sending large body in debug mode

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [hyperium/hyper#2643]
**Version**
hyper-0.14.12
reqwest-0.11.4 (blocking)

**Platform**
Manjaro Linux x86_64

**Description**
When sending large requests **repeatedly too fast**, a panic happens in debug mode.
I tried this code in debug mode:
```
fn main() {
    let client = reqwest::blocking::Client::new();
    let body = "x".repeat(10_000_000);
    loop {
        match client
            .post("http://localhost:8000")
            .body(body.clone())
            .send()
        {
            Ok(_) => println!("Success!"),
            Err(e) => eprintln!("{}", e),
        }
    }
}
```
For the server, I used this actix-web script:
```
use actix_web::{post, App, HttpResponse, HttpServer, Responder};
use std::io;

#[post("/")]
async fn root() -> impl Responder {
    HttpResponse::Ok()
}

#[actix_web::main]
async fn main() -> io::Result<()> {
    HttpServer::new(|| App::new().service(root))
        .bind("localhost:8000")?
        .run()
        .await
}
```

I expected to see this happen: "Success!" is repeatedly output

Instead, this happened: "Success!" is output once, then the following:

```
thread 'reqwest-internal-sync-runtime' panicked at 'assertion failed: !self.queue.has_remaining()', /home/<redacted>/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.12/src/proto/h1/io.rs:559:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'reqwest-internal-sync-runtime' panicked at 'dispatch dropped without returning error', /home/<redacted>/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.12/src/client/conn.rs:316:35
thread 'main' panicked at 'event loop thread panicked', /home/<redacted>/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.4/src/blocking/client.rs:1028:5
```

Since [this here](https://github.com/hyperium/hyper/blob/master/src/client/conn.rs#L316-L317) states that if this panic is triggered there is a "definite bug", I thought this should be reported.

**Comment by seanmonstar** [comment]
Thanks for the report, yep, definitely a bug! I'll take a look-see.

**Comment by seanmonstar** [comment]
Huh, so I set up an example just as you did, but with hyper as the server, and instead of a panic, I see an IO error since the hyper server closed the connection after writing the 200 OK. I'm guessing actix does something a little different, and that's why we haven't noticed here. Looking further....

**Comment by seanmonstar** [comment]
Yea, that was it. Found it. Cool, _cool_...

**Comment by Niklas-Eckhoff** [comment]
Oh, nice! Seems like you won't need it anymore, but here I set up a project to reproduce the bug: https://github.com/Niklas-Eckhoff/hyper-bug-report

**Comment by nox** [comment]
@seanmonstar So can the second panic currently happen whenever the HttpBody of the response body panics, too?

**Comment by seanmonstar** [comment]
Eh, probably yes 😅
