### ISSUE TITLE
Intermittent `connection error: not connected` and `connection error: broken pipe` errors

### ISSUE THREAD

**Issue by casey** [hyperium/hyper#2674]
**Version**

- hyper 0.14.13
- h2 0.3.6
- rustls 0.19.1
- tokio-rustls 0.22.0
- rustls-acme 0.1.7

**Platform**

`Darwin x.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64`

**Description**

We have a server that uses `hyper`, with `rustls_acme` to retrieve SSL certs from Let's Encrypt and `tokio-rustls`.

We're serving connections with `hyper::server::Http::serve_connection`, which is working, but `serve_connection` is sometimes returning errors with the message `connection error: not connected` or `connection error: broken pipe`.

The code where we handle SSL and pass the connection to our request handler is [here](https://github.com/agora-org/agora/blob/a41d6250e2dce5d87b1ad2a4d966aa218affe99e/src/https_request_handler.rs#L67).

The `log::debug!` that's firing is [here](https://github.com/agora-org/agora/blob/a41d6250e2dce5d87b1ad2a4d966aa218affe99e/src/https_request_handler.rs#L106).

This is only occurring intermittently. The error seems to only happen when we're concurrently accessing the server with multiple clients. 

This isn't causing any problems for us, although we'd like to be able to stop ignoring this error, in case it masks more serious errors in the future, so we wanted to ask if you've seen this error before, or if you had any ideas as to what might be the problem. We assume there's some kind of bad interaction between how we're interfacing hyper and rustls, but don't have any concrete ideas.

This can be reproduced on [this commit](https://github.com/agora-org/agora/commit/f591c2dbb8368841beaba9d74154b07fd2e2234c) with the following command:

```
RUST_LOG=debug cargo test --all-features serves_multiple_clients_through_https -- --nocapture
```

Look for:

```
[2021-10-22T21:55:09Z DEBUG agora::https_request_handler] Error closing TLS connection: connection error: broken pipe
```

Or:

```
[2021-10-22T21:57:36Z DEBUG agora::https_request_handler] Error closing TLS connection: connection error: not connected
````

**Comment by p-alik** [comment]
We are getting `connection error: not connected` from [tonic::transport::Server](https://docs.rs/tonic/0.1.0-alpha.1/tonic/transport/struct.Server.html) 

```
DEBUG Connection{peer=Server}: Sending warning alert CloseNotify    
DEBUG connection error: connection error: not connected
```

```
grep tonic Cargo.toml 
tonic = {version = "0.5.2", features = ["tls"]}
```

**Comment by seanmonstar** [comment]
This is coming from an IO error on the socket, [`ErrorKind::NotConnected`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.NotConnected). It lines up with the errno `ENOTCONN` (to help your searches). Reading up on the error, it simply means the connection has been ended, perhaps abruptly by the remote, but without having sent a TCP RST packet.

I don't believe there's anything for hyper to do with this.
