### ISSUE TITLE
Issue on arm64 arch

### ISSUE THREAD

**Issue by bastien-solutions** [hyperium/hyper#2683]
**Version**
hyper-0.14.14

**Platform**
Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

**Description**
On Mac M1 (arm64) the build of hyper fail with this message :

```
error[E0277]: the trait bound `HeaderMap<bytes::Bytes>: Clone` is not satisfied
   --> /Users/bvigneron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.14/src/ext.rs:30:33
    |
29  | #[derive(Clone, Debug)]
    |          ----- in this derive macro expansion
30  | pub(crate) struct HeaderCaseMap(HeaderMap<Bytes>);
    |                                 ^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `HeaderMap<bytes::Bytes>`
```

No issue on x86_64 with exactly the same code.

I tried this code:

The code that fail to compile is (on ext.rs) : 
```rust ext.rs
#[derive(Clone, Debug)]
pub(crate) struct HeaderCaseMap(HeaderMap<Bytes>);
```

I expected to see this happen: no issue

Instead, this happened: can't compile.

**Comment by seanmonstar** [comment]
This sounds like an environment issue. There's nothing special in hyper that would make that `Clone` code not work. You might need to run `cargo clean`, or check if you have any patch rules set.

**Comment by bastien-solutions** [comment]
Hello no patch rules set and the issue still remain after a cargo check.
