### ISSUE TITLE
`undefined reference` to linker error when using from nightly rustc

### ISSUE THREAD

**Issue by fpoli** [hyperium/hyper#2684]
In our project we use `rustc nightly-2021-10-15` and we encountered a [compiler bug](https://github.com/rust-lang/rust/issues/82151) that prevents us upgrading from `hyper 0.13, warp 0.2, reqwest 0.10, tokio 0.2` to `hyper 0.14, warp 0.3, reqwest 0.11, tokio 1.2` ([working](https://github.com/viperproject/prusti-dev/pull/750/commits/b36d6a4f80c6d77fb1fe815375aeb368778363fc), [not working](https://github.com/viperproject/prusti-dev/pull/750/commits/5727de30367dba4c9f93904a7546036fdbc4f0ca) commit).

It seems that the cause is the C ffi:

https://github.com/hyperium/hyper/blob/80627141ede3cdaf37b833ee91d08be0af0f5c84/Cargo.toml#L23

Removing that line solves the issue: https://github.com/alexkornitzer/hyper/commit/119904864b3dc91d77cf443af11f697821759336

I know that this is not exactly a bug in `hyper`, but since the C API is unstable I wonder if there is a way to set that `crate-type` only in the build that generates the C library. At least, until the compiler is fixed.

**Comment by seanmonstar** [comment]
Unfortunately we currently _can't_. There's no way for people to enable only a `cdylib` on-demand. But #2685 is tracking that.

**Comment by sfackler** [comment]
Couldn't the C interface be moved to a separate crate from `hyper` itself?

**Comment by seanmonstar** [comment]
The C interface makes uses of private details, so to use them in a separate crate would require making those "public".

**Comment by bjorn3** [comment]
An option would be to only expose them when a certain cfg is used. If it is something like `foo` and not `feature = "foo"` you can only set it using `RUSTFLAGS` and not when specifying it as dependency.
