### ISSUE TITLE
Make cdylib only build when C API required

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2685]
There's some problems with compiling hyper as a `cdylib` (https://github.com/rust-lang/rust/issues/82151), and even without problems, it's extra compilation work if you don't need to build a C library. The goal is to make it so users can opt-in to building a `cdylib`, instead of it being always on. To that end, we've pushed a bit in the tooling to allow this, and here's the steps that need to be done:

- [x] Open an RFC to allow `cargo rustc --crate-type cdylib` (https://github.com/rust-lang/rfcs/pull/3180)
- [x] RFC is approved and merged
- [x] Feature is added to cargo ([One PR](https://github.com/rust-lang/cargo/pull/8789))
- [x] https://github.com/rust-lang/cargo/issues/10356
- [x] Remove `cdylib` from hyper's `Cargo.toml` manifest
- [ ] https://github.com/rust-lang/cargo/issues/10083

**Comment by seanmonstar** [comment]
It's now possible in nightly to enable this at runtime:

```
cargo rustc -Z unstable-options --crate-type cdylib
```

Since the C API is "experimental", perhaps we can require that nightly cargo be used already...

**Comment by seanmonstar** [comment]
@bagder how do you feel about using "nightly" cargo. If installing Rust with `rustup`, you can just run `rustup install nightly` and then run `cargo +nightly blah blah` (or `rustup default nightly` to skip needing to add `+nightly` for a directory).

The background here is that currently hyper sets in its manifest to build both a Rust lib (`rlib`) and a C lib (`cdylib`) at the same time. This is wasteful, and causes some problems for people building Rust in some environments. But it's the only "stable" way to specify library type. We've added the ability to cargo to specify this at command-line time, but it will take a while to become part of "stable" cargo. By using this now, we can a) fix some of those other Rust builds, and b) test the nightly feature so it can become stable.

**Comment by bagder** [comment]
Whatever helps you go about this in a more convenient manner I will adapt to. Using nightly like this sounds totally doable in my end!
