### ISSUE TITLE
Cancel blocking DNS lookup if GaiFuture dropped

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2686]
The `GaiFuture` owns a Tokio `JoinHandle`, spawning a call to `getaddrinfo` in a blocking thread. If a request times out before the blocking thread started the call, we should have it removed from the queue. That can be done with `impl Drop for GaiFuture` that calls `JoinHandle::abort()`.

**Comment by ahmedsobeh** [comment]
Hi! Looking to get into the code-base and contributing to it, so I will give this a shot as a start!

**Comment by sfackler** [comment]
You shouldn't need any special permissions to open a pull request. You will need to make a fork of the repo and push your changes to that, though.

**Comment by ahmedsobeh** [comment]
Ah yeah, all good 👍
