### ISSUE TITLE
When the URL contains more than 65534 characters, the error code returned by Hyper is not 414.

### ISSUE THREAD

**Issue by silence-coding** [hyperium/hyper#2701]
The length of the from_shared method of the third-party library http::Uri is verified， The maximum length is (u16::MAX - 1).

**Comment by seanmonstar** [comment]
Good catch! We could add a check for the length just before calling `Uri::from_shared`, and if too long, return a `Parse` error. An integration test in `tests/server.rs` would be good too.

**Comment by rajing** [comment]
First pull request. Happy to change based on feedback.
