### ISSUE TITLE
HTTP/1.1 Trailers

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2702]
Add support for HTTP/1.1 chunked encoding trailers.

- [x] #2703
- [x] #2719

**Comment by Xuanwo** [comment]
Let's me have a try, this issue will be company with https://github.com/hyperium/hyper/issues/2699

**Comment by seanmonstar** [comment]
Thanks for offering! Which would you like to try to tackle first? Sending or receiving? I imagine sending will be less complicated. Whichever you pick, I can add some mentoring instructions in the relevant issue.

**Comment by Xuanwo** [comment]
It's so nice! I prefer to start with the `sending` side.

**Comment by Xuanwo** [comment]
Sorry for the long time delay. I don't have enough bandwidth for this issue now, feel free to pick this up if interested!

**Comment by Nugine** [comment]
Hi! Is there any update? Will hyper 1.0 support this feature?

**Comment by Nugine** [comment]
If hyper 1.0 does not support HTTP/1.1 Trailers yet, I can pick this issue up.

---

Why was my comment marked as spam? I was asking the status. 
Can someone please explain it?

![2023-04-12_21-15](https://user-images.githubusercontent.com/30099658/231469247-0e1f63ad-e3f2-4dbd-9db1-0ebae5974dbf.png)

**Comment by seanmonstar** [comment]
The status in these issues is kept up-to-date. We don't keep status stored anywhere else. Many people ask for status updates in issues when there is nothing else to say, so those comments get hidden.

**Comment by yedayak** [comment]
Should this be closed since both sending and receiving was implemented?

**Comment by seanmonstar** [comment]
All relevant work has been done :)
