### ISSUE TITLE
Have wildcard header value const

### ISSUE THREAD

**Issue by Stargateur** [hyperium/hyper#2713]
Why ? I don't like unwrap and I'm lazy. I think it's reasonable, wildcard as header value is a lot used.

Request: A prebuild HeaderValue for `"*"` like `HeaderValue::WILDCARD` or `header::WILDCARD`

**Comment by davidpdrsn** [comment]
You can do

```rust
use http::HeaderValue;

const WILDCARD: HeaderValue = HeaderValue::from_static("*");
```

With [`HeaderValue::from_static`](https://docs.rs/http/latest/http/header/struct.HeaderValue.html#method.from_static).

**Comment by Stargateur** [comment]
and the function is `const` nice... well I still think it wouldn't hurt to have a `Wildcard` directly in the crate but I will use your solution for now thanks.

**Comment by seanmonstar** [comment]
Since you can make a const in your code, I think I'll close this one. Thanks for the suggestion, though.
