### ISSUE TITLE
How prompt an error if the status code is not OK

### ISSUE THREAD

**Issue by PAN-Ziyue** [hyperium/hyper#2725]
**Is your feature request related to a problem? Please describe.**
Yes. I want to return an error if the status code of the response is not OK. Yet I found no guides on how to reach this.

**Describe the solution you'd like**
A method to turn response to `hyper::Error`

**Comment by PAN-Ziyue** [comment]
One ugly workaround I came through was to use `anyhow::Result` and `anyhow!()` to manually create an error return. Yet I still want to know whether hyper has a more elegant way.

**Comment by davidpdrsn** [comment]
Hyper is compatible with tower, which (among other things) allows you to write middleware.

You use [`and_then`](https://docs.rs/tower/0.4.11/tower/trait.ServiceExt.html#method.and_then) to do this.

I'm curious what your use case is though 🤔

**Comment by seanmonstar** [comment]
I'm guessing your using hyper as a client. hyper is lower level, and so there isn't a built-in way to convert a `StatusCode` into an error. You can `match resp.status() { .. }` and create an error for your application that way.

Or, if you're interested in a more opinionated HTTP client, you can use [`reqwest`](https://crates.io/crates/reqwest), which does have `Response::error_for_status()`.
