### ISSUE TITLE
Something wrong with hyper server behavior

### ISSUE THREAD

**Issue by uniconductive** [hyperium/hyper#2741]
**Version**
0.4.16

**Platform**
Linux 5.16.2-1-MANJARO x86_64 GNU/Linux

**Description**
Enter your issue details here.
One way to structure the description:

I got strange behavior of two hyper server instances.

I tried this code:

```
use std::{convert::Infallible, net::SocketAddr, task::{Context, Poll}};
use hyper::{Server, Body, Request, Response, service::make_service_fn};
use futures::future::{ready, Ready};
use tower::Service;
use tokio::{task::JoinHandle, time};

struct HelloWorld {
    data: String
}

impl Service<Request<Body>> for HelloWorld {
    type Response = Response<Body>;
    type Error = Infallible;
    type Future = Ready<Result<Self::Response, Self::Error>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        println!("poll_ready: {}", self.data.clone());
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, req: Request<Body>) -> Self::Future {
        ready(Ok(Response::new(Body::from(format!("{}: {}", &self.data, req.uri().to_string())))))
    }
}

fn start_one(addr: SocketAddr, return_str: String) -> JoinHandle<()> {
    tokio::spawn(async move {
        let make_service = make_service_fn(|_conn| {
            let svc = HelloWorld { data: return_str.clone() };
            async move { Ok::<_, Infallible>(svc) }
        });
        let server = Server::bind(&addr).serve(make_service);
        println!("{} runned", &return_str);
        let _ = server.await;
    })
}

#[tokio::main]
async fn main() {
    let h1 = start_one(SocketAddr::from(([127, 0, 0, 1], 3001)), "Server 1".into());
    time::sleep(std::time::Duration::from_secs(1)).await;
    let _ = webbrowser::open("http://127.0.0.1:3001/must_be_of_server1");
    time::sleep(std::time::Duration::from_secs(1)).await;
    // without abort() we have panic on next start_one(..): "thread 'tokio-runtime-worker' panicked at 'error binding to 127.0.0.1:3001: error creating server listener: Address already in use (os error 98)'"
    h1.abort();
    println!("aborted 1");

    time::sleep(std::time::Duration::from_secs(5)).await;
    // this works, so port 3001 still opened
    let _ = webbrowser::open("http://127.0.0.1:3001/cant_be_");
    time::sleep(std::time::Duration::from_secs(5)).await;

    // but if port 3001 still opened, how we can bind to it here?
    let h2 = start_one(SocketAddr::from(([127, 0, 0, 1], 3001)), "Server 2".into());
    time::sleep(std::time::Duration::from_secs(1)).await;
    // and why we still have response from Server 1 here?
    let _ = webbrowser::open("http://127.0.0.1:3001/must_be_of_server2");
    time::sleep(std::time::Duration::from_secs(1)).await;
    h2.abort();
    println!("aborted 2");

    time::sleep(std::time::Duration::from_secs(5)).await;
    // and here we got response from Server 1:
    let _ = webbrowser::open("http://127.0.0.1:3001/cant_be__");
    time::sleep(std::time::Duration::from_secs(5)).await;

    std::thread::sleep(std::time::Duration::from_secs(60));
    println!("finished");
}

```

Cargo.toml:
tokio = { version = "1.16.1", features = ["full"] }
hyper = { version = "0.14.16", features = ["full"] }
tower = { version = "0.4.11", features = ["default"] }
futures = { version = "0.3.19" }
webbrowser = "0.5.5"

I expected to see this happen (in case if h1.abort() closes port 3001): 
Server 1 runned
poll_ready: Server 1
aborted 1
Server 2 runned
poll_ready: Server 2
aborted 2
finished

or this (in case if port still opened after h1.abort()):

Server 1 runned
poll_ready: Server 1
aborted 1
poll_ready: Server 1
thread 'tokio-runtime-worker' panicked at 'error binding to 127.0.0.1:3001: error creating server listener: Address already in use (os error 98)'

Instead, this happened: 
Server 1 runned
poll_ready: Server 1
aborted 1
poll_ready: Server 1
Server 2 runned
poll_ready: Server 1
aborted 2
poll_ready: Server 1
finished

But, if we comment h1.abort() we will have this:
Server 1 runned
poll_ready: Server 1
aborted 1
poll_ready: Server 1
thread 'tokio-runtime-worker' panicked at 'error binding to 127.0.0.1:3001: error creating server listener: Address already in use (os error 98)'

Moreover, if we comment this two lines in original code above
let _ = webbrowser::open("http://127.0.0.1:3001/must_be_of_server1");
let _ = webbrowser::open("http://127.0.0.1:3001/cant_be_");
we will have this: 
Server 1 runned
aborted 1
Server 2 runned
poll_ready: Server 2
aborted 2
poll_ready: Server 2
finished

I see dirty side effects here (previously we have "poll_ready: Server 1" everywhere).

**Comment by seanmonstar** [comment]
I have no idea what the `webbrowser` code does fully. I assume it fetched the url. Still, it looks like what you're seeing is that the server is reserving the port of the closing server. That's common for an operating system to do, to prevent any mid-transmission packets that arrive to the port late from being misinterpreted for the new socket (listener).

I don't see anything that is specific to hyper doing something wrong.
