### ISSUE TITLE
ContentType import from hyper::header

### ISSUE THREAD

**Issue by ribrea** [hyperium/hyper#2750]
**Version**
hyper = { version = "0.14", features = ["full"] }

**Platform**
Linux skrilla 5.13.0-27-generic #29-Ubuntu SMP Wed Jan 12 17:36:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Description**
error[E0432]: unresolved import `hyper::header::ContentType`
 --> src/main.rs:4:35
  |
4 | use hyper::header::{CONTENT_TYPE, ContentType};
  |                                   ^^^^^^^^^^^ no `ContentType` in `header`

[short summary of the bug]
I can't import ContentType

I tried this code:
use hyper::header::{CONTENT_TYPE, ContentType};

[code sample that causes the bug]
use hyper::header::{CONTENT_TYPE, ContentType};

**Comment by ribrea** [comment]
Same reason Status code is exist,

I was writing a macro to response as JSON, 
i thought is better to use "application/json" as a constant.

**Comment by olix0r** [comment]
There's a separate [`mime` crate](https://docs.rs/mime/0.3.16/mime/) that includes types for handling content-type, etc. I assume the context for keeping them separate is to avoid these types being a part of Hyper's stable API.

**Comment by ribrea** [comment]
@olix0r  Thank you very much
