### ISSUE TITLE
Regression in ability to get a TcpStream from a Request or Response on the Server.

### ISSUE THREAD

**Issue by reem** [hyperium/hyper#277]
Somewhere in the HttpReader/Writer and keep-alive refactors we silently lost the ability to do this through the downcasting abilities of NetworkStream and such. We should figure out a way to provide this feature, as it is very important for web sockets and other such libraries that need low-level access.

cc @rphmeier who brought this to my attention on IRC.

**Comment by seanmonstar** [comment]
There's still `deconstruct` on `Request`, that yiels an `HttpReader`. You can use `unwrap` on that (should be renamed to into_inner), to get the `&Reader`. From there, you can downcast, no?

**Comment by reem** [comment]
No, you can't downcast from `&Reader` - we used to let you get an `&NetworkStream`, which you can downcast from, but that changed.

**Comment by reem** [comment]
Closed now that we re-exposed NetworkStream.
