### ISSUE TITLE
Run Server with user-supplied thread pool.

### ISSUE THREAD

**Issue by rphmeier** [hyperium/hyper#278]
Is there a reason why this would be unfeasible or impractical? It seems useful in cases where your application uses a TaskPool and you'd prefer not to have more than one created.

**Comment by reem** [comment]
This should be possible in some form.

**Comment by rphmeier** [comment]
Update: It looks like Hyper has moved to an internal thread pool rather than the deprecated (?) TaskPool since the this issue was posted. 

I'd suggest probably to close this, since I'm not sure anyone wants this feature or whether it's even useful.

**Comment by seanmonstar** [comment]
master no longer uses a thread pool at all. It is up to the user to spawn any threads they want.

**Comment by u2** [comment]
How to spawn any threads for one server?
