### ISSUE TITLE
TcpListenerStream

### ISSUE THREAD

**Issue by Ilqjx** [hyperium/hyper#2781]
Hello, what should I do to convert `TcpListenerStream` to http request or service in hyper?

```rust
let listener = tokio::net::TcpListener::bind("127.0.0.1:9981").await.unwrap();
let mut stream = tokio_stream::wrappers::TcpListenerStream::new(listener);
Http::new().http1_only(true).serve_connection(&mut stream, service_fn(hello)).await;
```
![image](https://user-images.githubusercontent.com/53934234/158930059-05907c81-4654-4c56-abb2-e74f1d81a83f.png)

**Comment by seanmonstar** [comment]
Not with a listener. You accept connections from the listener, and pass those to `serve_connection`. Take a look at the doc example.

**Comment by Ilqjx** [comment]
Thanks for your reply.
