### ISSUE TITLE
Hyper Curl Test 718

### ISSUE THREAD

**Issue by DanielVZ96** [hyperium/hyper#2783]
**Version**
 hyper::ffi current version

**Platform**

```
5.13.0-7614-generic #14~1631647151~20.04~930e87c-Ubuntu SMP Fri Sep 17 00:26:31 UTC  x86_64 x86_64 x86_64 GNU/Linux
```
but i suppose it's also for any platform

**Description**

The test 718 is failing with the following error from hyper:  `0curl: (56) Hyper: [3] connection closed before message completed`. 

After inspecting the test, I noticed that there's no EOF before closing the connection, so I guess there's no issue on hyper's side. My intuition of the underlying problem is that the test expects hyper to process the data from the connection, but hyper isn't doing anything after noticing there's no EOF.

Test Case:
```
# Server-side
<reply>

# this is returned first since we get no proxy-auth
<connect>
HTTP/1.1 407 Authorization Required to proxy me swsclose
Proxy-Authenticate: Digest realm="weirdorealm", nonce="12345"
</connect>

<datacheck>
HTTP/1.1 407 Authorization Required to proxy me swsclose
Proxy-Authenticate: Digest realm="weirdorealm", nonce="12345"
</datacheck>
</reply>
```

If i add the EOF to both connect and datacheck the test passes both with and without hyper.

Updated Test case:
```
# Server-side
<reply>

# this is returned first since we get no proxy-auth
<connect>
HTTP/1.1 407 Authorization Required to proxy me swsclose
Proxy-Authenticate: Digest realm="weirdorealm", nonce="12345"

</connect>

<datacheck>
HTTP/1.1 407 Authorization Required to proxy me swsclose
Proxy-Authenticate: Digest realm="weirdorealm", nonce="12345"

</datacheck>
</reply>
```

With hyper:
```
********* System characteristics ******** 
* curl 7.83.0-DEV (x86_64-pc-linux-gnu) 
* libcurl/7.83.0-DEV OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) Hyper/0.14.17
* Features: alt-svc AsynchDNS brotli Debug HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL TLS-SRP TrackMemory UnixSockets
* Disabled: 
* Host: daniel
* System: Linux daniel 5.13.0-7614-generic #14~1631647151~20.04~930e87c-Ubuntu SMP Fri Sep 17 00:26:31 UTC  x86_64 x86_64 x86_64 GNU/Linux
* OS: linux
*
*** DISABLES memory tracking when using threaded resolver
*
* Servers: HTTP-IPv6 HTTP-unix FTP-IPv6 
* Env: 
* Seed: 259306
***************************************** 
Warning: test718 is explicitly disabled
test 0718...[HTTP proxy CONNECT (no auth) with proxy returning 407 and closing]
--pd---e--- OK (1   out of 1  , remaining: 00:00, took 1.071s, duration: 00:01)
TESTDONE: 1 tests were considered during 1 seconds.
TESTDONE: 1 tests out of 1 reported OK: 100%
```

Without hyper
```
********* System characteristics ******** 
* curl 7.83.0-DEV (x86_64-pc-linux-gnu) 
* libcurl/7.83.0-DEV OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0)
* Features: alt-svc AsynchDNS brotli Debug HSTS HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL TLS-SRP TrackMemory UnixSockets
* Disabled: 
* Host: daniel
* System: Linux daniel 5.13.0-7614-generic #14~1631647151~20.04~930e87c-Ubuntu SMP Fri Sep 17 00:26:31 UTC  x86_64 x86_64 x86_64 GNU/Linux
* OS: linux
*
*** DISABLES memory tracking when using threaded resolver
*
* Servers: HTTP-IPv6 HTTP-unix FTP-IPv6 
* Env: 
* Seed: 224910
***************************************** 
test 0718...[HTTP proxy CONNECT (no auth) with proxy returning 407 and closing]
--pd---e--- OK (1   out of 1  , remaining: 00:00, took 1.143s, duration: 00:01)
TESTDONE: 1 tests were considered during 1 seconds.
TESTDONE: 1 tests out of 1 reported OK: 100%
```

@seanmonstar would updating the test case be a solution?

**Comment by seanmonstar** [comment]
Oh, I see what you mean. That the test case doesn't include a blank line after the headers indicating the headers are done. Ya, so hyper thinks that means the connection terminated before the headers were finished.

I... don't know if hyper is wrong here. I think it's right, that's not a complete headers without the newline...

**Comment by seanmonstar** [comment]
It might that the unit test could be updated, I don't know if it was meant to test this specific case. The one who could answer that is @bagder. It looks like the unit test is expecting error code 56, which i think is [`CURLE_RECV_ERROR`](https://curl.se/libcurl/c/libcurl-errors.html#CURLERECVERROR). So, I think it's expected to be an error, but the handling is just slightly different.

**Comment by bagder** [comment]
The 718 test case shows hyper being more picky on HTTP than native libcurl. I can be fixed by fixing the test case like this: https://github.com/curl/curl/pull/8614

(and maybe it also shows that hyper isn't always making it very easy to understand why it returns error...)

**Comment by bagder** [comment]
Now fixed in curl's git repo.

**Comment by DanielVZ96** [comment]
Sorry for not responding earlier, i had a tight weekend

@bagder thanks for fixing the test so promptly!

@seanmonstar I've been thinking about this and maybe hyper should support only having CR as an EOF in order to match the compatibility of libcurl. it could be under a `#[cfg(feature = "ffi")]`. i can't pin where this change should be implemented though.

**Comment by seanmonstar** [comment]
> hyper should support only having CR as an EOF

I don't think we want to do that. The specs and real world that _I've_ seen only ever have `LF` or `CRLF`.

Otherwise, seems this test case is fixed, ya? Thanks for helping us figure it out!! 🎉
