### ISSUE TITLE
hyper::Server::serve does not accept Services that use Requests containing generic implementers of HttpBody

### ISSUE THREAD

**Issue by AshleySchaeffer** [hyperium/hyper#2788]
**Version**
0.14.17

**Platform**
`Linux <SNIP> 5.15.21-1-MANJARO #1 SMP PREEMPT <SNIP> 2022 x86_64 GNU/Linux`

**Description**
The issue appears to be in the `hyper::Server::serve` method. However, I'm reasonably new to Rust so it could really be me being a moron. 

I'm using a custom struct that implements `HttpBody` to wrap `hyper::Body` within `hyper::Request`s and `hyper::Response`s, as I need more control over how bodies are processed. This approach was sort of recommended by seanmonstar (https://github.com/hyperium/hyper/discussions/2785) but I'm trying to implement it for both requests and responses rather than handling requests separately. To create the `Service`, I'm using the `hyper::service::service_fn` helper function which I believe will permit the use of any type that implements `HttpBody`. I then have this wrapped in a call to `hyper::service::make_service_fn`, the output of which (the `MakeService`) I pass to `hyper::Server::serve` where I get the following compilation error:

```
error[E0277]: the trait bound `hyper::service::util::ServiceFn<[closure@src/bin.rs:135:52: 137:22], BodyWrapper<Body>>: Service<hyper::Request<Body>>` is not satisfied
   --> src/bin.rs:143:24
    |
143 |                 .serve(make_service)
    |                  ----- ^^^^^^^^^^^^ the trait `Service<hyper::Request<Body>>` is not implemented for `hyper::service::util::ServiceFn<[closure@src/bin.rs:135:52: 137:22], BodyWrapper<Body>>`
    |                  |
    |                  required by a bound introduced by this call
    |
    = help: the following implementations were found:
              <hyper::service::util::ServiceFn<F, ReqBody> as Service<hyper::Request<ReqBody>>>
    = note: required because of the requirements on the impl of `hyper::service::http::HttpService<Body>` for `hyper::service::util::ServiceFn<[closure@src/bin.rs:135:52: 137:22], BodyWrapper<Body>>`
```

I could be wrong, but it looks like `hyper::Server::serve` explicitly requires the `Service` use `hyper::body::Body` within `hyper::Request`s and not any generic type that implements the `HttpBody` trait, where as it does accept such types within `hyper::Response`s:

https://github.com/hyperium/hyper/blob/740654e55d2bb2f50709f20fb4054a5504d8c2fb/src/server/server.rs#L505-L520

Where `Body` is found defined here:

https://github.com/hyperium/hyper/blob/740654e55d2bb2f50709f20fb4054a5504d8c2fb/src/server/server.rs#L20

Given that the `hyper::service::service_fn` helper accepts generic implementers of `HttpBody`, I would expect `hyper::Server::serve` to do the same, but it doesn't seem to be the case, unless I am indeed a moron.

**Comment by sfackler** [comment]
Hyper doesn't know how to construct an arbitrary implementor of HttpBody. You will have to make your service take in a `hyper::Body` and then wrap it in your type.

**Comment by AshleySchaeffer** [comment]
Thanks, I get what you mean now. I will try it out. I'll close this on the premise that I'm a moron :)
