### ISSUE TITLE
`Response` and `Response Body` should be clonable

### ISSUE THREAD

**Issue by firstdorsal** [hyperium/hyper#2799]
**Is your feature request related to a problem? Please describe.**
I want to clone a `Response` and `Response Body` so that I can pregenerate them, store them in memory and then just clone and serve them when the request comes.

**Describe the solution you'd like**
The ability to clone `Responses` and `Reponse Bodies`

**Comment by seanmonstar** [comment]
The multi-purpose `hyper::Body` cannot be `Clone`, because it may contain state that isn't cloneable. An easy solution is to have the full body in a `Bytes`, which is cheaply cloned and can be converted into a new body via `Body::from(bytes)`.

A `Response` also cannot be `Clone`. See https://github.com/hyperium/http/pull/280 for history.

**Comment by firstdorsal** [comment]
Uhm, this is too bad because this has some notable performance downsides.

Without setting any Headers on the `Builder`, Hyper is capable of delivering an incredible **300k** requests per second on my machine (nginx does ~30k), but when adding multiple headers from Scratch for every request this goes down to 180k, even when reusing and cloning the `HeaderMap` it does not get above 233k (Don't get me wrong, this is still incredible but also quite a noticeable drop, especially as the bodies contents are quite cheaply clonable).

# Body

Just sending a string:
```rs
res.body(Body::from("test")).unwrap();
```
287k/s

compared to cloning in the real body contents from memory

```rs
res.body(Body::from(fsmap.get(&access_path).unwrap().clone())).unwrap();
```
281k/s

This is quite cheap.

# Headers

But sending headers:

With DOCUMENT_MAP containing ~10 headers
```rs
res.headers_mut().unwrap().extend(DOCUMENT_MAP.clone());
```
233k/s

compared to not sending headers

281k/s


Thank you! Hyper is awesome!

**Comment by seanmonstar** [comment]
You could skip the clone, and just `.extend(&DOCUMENT_MAP)`, I think. That should save a bit of allocations.

**Comment by firstdorsal** [comment]
Thank you for the suggestion but this doesn't work.
``&DOCUMENT_MAP` is not an iterator
the trait `std::iter::Iterator` is not implemented for `&DOCUMENT_MAP``

**Comment by seanmonstar** [comment]
Perhaps calling the `.iter()` method. Might be because lazy static wraps it in a smart pointer.
