### ISSUE TITLE
X.509 HTTP client example

### ISSUE THREAD

**Issue by overheat** [hyperium/hyper#2800]
**Describe the solution you'd like**
An example shown how to send a HTTP request with X.509 certificate. Like this curl command:
```
curl --cert < certificate> --key < device certificate key pair> -H <HTTP header> --cacert <CA> <URI>
```

**Comment by seanmonstar** [comment]
That depends on the TLS library you may use with hyper (it can be any). But I see you also opened an issue in the reqwest repo, so I'll close this one.
