### ISSUE TITLE
Building for MSVC and libcurl

### ISSUE THREAD

**Issue by gvanem** [hyperium/hyper#2811]
I'm struggling with how to build a `Hyper.dll` + `Hyper.lib` for use in libcurl.

I'm a *n00b* when it comes to Rust + Cargo. So I've used the below GNU-makefile for some time. 
But it has stopped working in producing a normal lib-file.
Instead I get a `target/i686-pc-windows-msvc/release/libhyper.rlib` built instead. A static library (?) that is of no use in MSVC's linker.
And no .dll or import library gets produced.

So what exact  `cargo build` flags and `RUSTFLAGS` are needed to built a `Hyper.dll` + `Hyper.lib` for use in libcurl?

My `<Hyper-root>/Makefile.Windows`:
```
#
# Create 'hyper.lib' for MSVC (x86 / x64, release + debug)
#
green_msg = @echo -e "\e[1;32m$(strip $(1))\e[0m"

ifeq ($(CPU),x86)
  TARGET = i686-pc-windows-msvc
else
  TARGET = x86_64-pc-windows-msvc
endif

HYPER_LIB_RELEASE = target/$(TARGET)/release/hyper.rlib
HYPER_LIB_DEBUG   = target/$(TARGET)/debug/hyper.rlib

TARGETS = $(HYPER_LIB_RELEASE) \
          $(HYPER_LIB_DEBUG)

INSTALL_ROOT = $(realpath $(VSINSTALLDIR))

export RUSTFLAGS= --cfg hyper_unstable_ffi 

#
# These flags does trigger a compile error:
#   error: language item required, but not found: `eh_personality`
#
# export RUSTFLAGS= --cfg hyper_unstable_ffi --crate-type staticlib,cdylib

#
# And these from 'https://seanmonstar.com/post/678895803144830976/help-stabilize-hyper-in-curl'
# does not work:
#   export RUSTFLAGS=--cfg hyper_unstable_ffi --features client,http1,http2,ffi --crate-type staticlib,cdylib
#

all: $(TARGETS)
	$(call green_msg, Do a 'make -f Makefile.Windows install' at own risk.)

$(HYPER_LIB_RELEASE): Cargo.toml
	$(call cargo_build, $@, --release)

$(HYPER_LIB_DEBUG): Cargo.toml
	$(call cargo_build, $@, )

install: $(HYPER_LIB_RELEASE)
	$(call green_msg, Copying $(1))
	cp --update target/$(TARGET)/release/hyper.{dll,pdb}  $(INSTALL_ROOT)/bin
	cp --update $(HYPER_LIB_RELEASE)                      $(INSTALL_ROOT)/lib/hyper.lib
	@echo

clean vclean distclean:
	rm -f $(TARGETS) Cargo.lock target/.rustc_info.json
	rm -fr target

define cargo_build
  $(call green_msg, Building $(1))
  cargo build --no-default-features $(2) --target $(TARGET)
  @echo
endef

```

And adding a `--crate-type staticlib` to the `RUSTFLAGS`, causes these errors:
```rust
   Compiling cfg-if v1.0.0
error: language item required, but not found: `eh_personality`
  |
  = note: this can occur when a binary crate with `#![no_std]` is compiled for a target where 
`eh_personality` is defined in the standard library
  = help: you may be able to compile for a target that doesn't need `eh_personality`, specify a target with 
`--target` or in `.cargo/config`

error: `#[panic_handler]` function required, but not found

error: could not compile `pin-project-lite` due to 2 previous errors
```

**Comment by seanmonstar** [comment]
Hey there! So, I haven't tried on Windows, but maybe it's not too different. For starters, most of the options shouldn't be set in the `RUSTFLAGS` environment variable, but passed as options to `cargo rustc`.

So, something like this:

```
export RUSTFLAGS= --cfg hyper_unstable_ffi

cargo rustc -Z unstable-options --crate-type cdylib --features client,http1,http2,ffi
```

**Comment by gvanem** [comment]
Thanks for replying. But `cargo rustc` and not `cargo build`? Like I wrote, I'm a *n00b* when it comes to this.

But these commands:
```
cargo rustc -Z unstable-options --crate-type cdylib --features client,http1,http2,ffi  --release --target i686-pc-windows-msvc
cargo rustc -Z unstable-options --crate-type cdylib --features client,http1,http2,ffi            --target i686-pc-windows-msvc
```
gives me these:
```
target\i686-pc-windows-msvc\debug\hyper.dll.lib
target\i686-pc-windows-msvc\release\hyper.dll.lib
target\i686-pc-windows-msvc\debug\hyper.dll
target\i686-pc-windows-msvc\release\hyper.dll
```

And a `_RELEASE` static lib with:
```
cargo rustc -Z unstable-options --crate-type staticlib --features client,http1,http2,ffi --release --target i686-pc-windows-msvc
```
producing this 16 MByte lib `target\i686-pc-windows-msvc\release\hyper.lib`

So I guess these are good to use in libcurl.

BTW. How come there is no `--debug` flags AFAICS?

**Comment by seanmonstar** [comment]
> But `cargo rustc` and not `cargo build`?

Yep! The `rustc` subcommand of cargo is for configuring more advanced options, and chose the crate-type is one of those.

> How come there is no --debug flags AFAICS?

The default build if you don't specify `--release` is the debug version. It includes debug data, debug assertions, etc. It's possible to pass extra options to change the defaults, but if you don't, most is on until you write `--release`. The docs on cargo's [default profiles](https://doc.rust-lang.org/stable/cargo/reference/profiles.html) has more info.

**Comment by gvanem** [comment]
Ok, thanks for the details. It's working in libcurl now. Hence I'm closing.
