### ISSUE TITLE
C compilation without using nightly

### ISSUE THREAD

**Issue by kevinburke** [hyperium/hyper#2832]
I maintain a Homebrew formula that can be used to install rustls-ffi, Hyper, curl, git (and hopefully other software), using the Rust backends. You can view the repo and instructions here: https://github.com/kevinburke/homebrew-safe

I've had to pin the Hyper formula to 0.14.17 because the 0.14.18 release depends on the nightly Rust release, and Homebrew makes it difficult to install the nightly.

Because of this I've also had to pin curl at version 7.82, which is now two point releases behind.

I'm wondering if there's a time frame when I might be able to get back up to tip again - if it's possible to not have to depend on the nightly at some point in the near future.

**Comment by memoryruins** [comment]
> I'm wondering if there's a time frame when I might be able to get back up to tip again - if it's possible to not have to depend on the nightly at some point in the near future.

As far as I know, the only nightly feature hyper uses for the C API is <https://github.com/rust-lang/cargo/issues/10083>. which was motivated by hyper's needs in <https://github.com/hyperium/hyper/issues/2685>. It should be possible to use the first stable rust toolchain that feature ships with.

**Comment by seanmonstar** [comment]
Yep exactly that. The `cargo rustc --crate-type cdylib` command line option (https://github.com/rust-lang/cargo/issues/10083) needs to stabilize to be able to use it on a non-nightly toolchain.

**Comment by nnethercote** [comment]
Nightly hasn't been necessary since Rust 1.64.0 was released. See the build instructions in https://github.com/hyperium/hyper/blob/master/capi/README.md.

Which means this issue can be closed.
