### ISSUE TITLE
Remove high-level pooling Client

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2841]
The `hyper::Client` and support modules `hyper::client::connect` should be removed from hyper, and parts should reappear in hyper-util.

- [ ] #2860 
- [x] #2859

**Comment by cameronelliott** [comment]
@seanmonstar I was going to submit a one line PR to the docs of hyper::client::Client
along the lines of "Client supports concurrent requests to multiple different host names".
(I wrote a simple test harness & used two different slow http servers to verify how this worked)

But I just discovered this PR+issue. 

For me, it was hinted, but not clear that I could use Client concurrently for different hostnames.
I really think the docs would benefit from an explicit statement regarding this.
Let me know if I can help on that somehow.
