### ISSUE TITLE
Document that Error::source() types can not be depended on

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2843]
All sources/causes in `hyper::Error` should be wrapped in a private `Opaque` type that still prints (`impl Debug` and `impl Display`) the message, but makes the type no longer leak through `err.downcast::<Blah>()`.

**Comment by sfackler** [comment]
Is it not going to expose sources either? Since the opaque wrapping can only happen at the first level

**Comment by seanmonstar** [comment]
I suppose it "couldn't" expose the next source, since it can't wrap a reference, and exposing it would potentially include unstable dependencies... If the second option in #2844 happens, the unexposed sources would still be printable at least.

**Comment by seanmonstar** [comment]
I filed a proposal for the error handling WG, since that could affect the formatting needed for an "opaque" type.

**Comment by seanmonstar** [comment]
I suppose a question to consider is: is it fair to simply document "The types in `Error::source()` are not part of the public API, and are subject to change at any time"?

**Comment by davidpdrsn** [comment]
imo that's fine. It's what axum does for [extractor rejections](https://docs.rs/axum/latest/axum/extract/index.html#accessing-inner-errors). While not _great_ I think its pragmatic and acceptable.
