### ISSUE TITLE
Chop AddrStream out completely

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2850]
The `AddrStream` type can just go. Get out of here. Gone. It provides no benefit over `tokio::net::TcpStream`.

**Comment by oddgrd** [comment]
Hi! I'd like to start contributing to this project, and this issue looks like a good place to start. I'm a bit of a rust and OSS noob, so I may need some guidance even though it should be easy.

**Comment by nyetwurk** [comment]
Is there a porting guide for code that refers to `AddrStream`?

**Comment by seanmonstar** [comment]
There isn't currently such a guide, but I suggested making one in #3411.

**Comment by nyetwurk** [comment]
https://github.com/hyperium/hyper/pull/2869/files is somewhat self explanatory.
