### ISSUE TITLE
Move the Pool to hyper-util

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2860]
Once the [`connect` module is moved to hyper-util](https://github.com/hyperium/hyper/issues/2859), we can move `pool.rs` to hyper-util as well.

**Comment by Michael-J-Ward** [comment]
Does https://github.com/hyperium/hyper-util/pull/3 complete this?

**Comment by seanmonstar** [comment]
Yes it looks like it, thanks! (We need to make that Pool usable, but that's a new ticket.)
