### ISSUE TITLE
Support different upstream URL and absolute URL for CONNECT

### ISSUE THREAD

**Issue by howardjohn** [hyperium/hyper#2863]
**Is your feature request related to a problem? Please describe.**
I am trying to send CONNECT requests. I want to send a request to one URL (`proxy-server`) but have the request container another URL (`target-server`).

Here is my closest attempt:
```
let request = Request::builder()
    .method("CONNECT")
    .uri("http://proxy-server")
    .header("host", "target-server")
    .version(Version::HTTP_2)
    .body(Body::empty())
    .unwrap();
```

Which ends up sending a request to `proxy-server` with:
```
CONNECT proxy-server HTTP/1.1
host: target-server
```

A concrete example of what I want to do (but with hyper instead of `nc`):

```
$ echo 'CONNECT target-server:9090 HTTP/1.1
Host: target-server:9090
' | nc proxy-server proxy-port
```

Note: used HTTP/1.1 to show text examples, but in real world I care about HTTP2 if that is relevant.

**Describe the solution you'd like**
I'm not sure of the exact API that is ideal, but it would be nice to decouple the URI and the target destination.

**Describe alternatives you've considered**
I looked into using a custom connector but as far as I can tell that only gets passed the original URI (https://github.com/hyperium/hyper/blob/775fac114bdfb4b477f0fe62475c7c077c10a6ce/src/client/client.rs#L435), so even with a custom connector it doesn't seem like we can get enough context.

https://github.com/tafia/hyper-proxy - this would be one pattern that could be used (by creating a similar custom connector), but would be a pretty heavyweight solution since we would need one client/connector per `proxy-server`

**Additional context**
Example using `curl` to generate these (not 100% the same since this is a proxy):

![2022-05-20_12-21-00](https://user-images.githubusercontent.com/623453/169597360-f32e7390-46d6-4bc9-9a46-3eb861d21d3d.png)

Example of using `go` to make a request like this: https://go.dev/play/p/cTHnVb-1tTY

**Comment by seanmonstar** [comment]
Right, and so if you did similar right now, the Rust would output something like this, ya?

```
CONNECT proxy HTTP/1.1
Host: destination
```

So far, what things have done (like reqwest) is to make the connector have a map that takes the destination, looks up if a proxy is needed, and if so, does the tunnel directly. It's also easier to do this with the `hyper::client::conn` API, since in that case, you establish the connection yourself, and then just tell hyper what to write for the request-target.

I don't know yet a good way to do otherwise, but open to suggestions.

**Comment by howardjohn** [comment]
Yep, I updated the description with my current code + output, forgot that original.

> make the connector have a map that takes the destination, looks up if a proxy is needed, and if so, does the tunnel directly

That does seem like something that would work in most cases, but in my case just knowing the destination isn't entirely sufficient; within the same process I will want to send to the destination directly and via proxy other times. Just knowing the destination isn't enough to make that decision; but other request metadata would be (headers, probably). However, I do think that just having 2 clients/connectors (such as `proxy_client` and `direct_client`) and then using that pattern would work.

The alternative I think would be to allow the `request` type to contain an explicit destination instead of deriving it from `uri`, but can definitely see that may be a pretty niche case given the flexibility offered with the custom connectors.

**Comment by howardjohn** [comment]
I think the connector method is pretty reasonable to do this, and after thinking about it more I don't actually need 2 clients (because the direct_client will be a plain tcp connection, not http). I'll close this out. Thanks!
