### ISSUE TITLE
cannot be compiled

### ISSUE THREAD

**Issue by NikosEfthias** [hyperium/hyper#2867]
**Version**
List the version(s) of `hyper`, and any relevant hyper dependency (such as `h2` if this is related to HTTP/2).
0.14.18

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
```
Darwin nikoss-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
```

**Description**
cargo check on an empty project fails to compile

[short summary of the bug]

I tried this code:
- `cargo add hyper`
- `cargo check`
[code sample that causes the bug]
empty main function

I expected to see this happen: [explanation]
Successful compilation 
Instead, this happened: [explanation]
```
    Checking hyper v0.14.18
error[E0596]: cannot borrow `self.data_tx` as mutable, as `self` is not declared as mutable
   --> /Users/nikos/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.18/src/body/body.rs:658:11
    |
656 |       pub fn abort(self)
    |                    ---- help: consider changing this to be mutable: `mut self`
657 |       {
658 |           let _ = self
    |  _________________^
659 | |             .data_tx
660 | |             // clone so the send works even if buffer is full
661 | |             .try_send(Err(crate::Error::new_body_write_aborted()));
    | |__________________________________________________________________^ cannot borrow as mutable

For more information about this error, try `rustc --explain E0596`.
error: could not compile `hyper` due to previous error
```

**Comment by seanmonstar** [comment]
Do you have an older version of rustc?

**Comment by NikosEfthias** [comment]
@seanmonstar i have the latest version and  v0.13 compiles just fine but as it turned out this was an issue with cargo not hyper itself. for whatever reason cargo registry got corrupted
