### ISSUE TITLE
Add server option to disable mid-message EOF detection

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2911]
After reading the request headers and body, and before a response is ready, hyper will read from the socket once more to make sure it has registered interest in case the socket ever hangs up. In some cases, though, users would prefer not to pay the cost of that syscall, and simply notice when the response is written instead.

The action here is:

- Add `http1_mid_message_eof_detection(bool)`, where the default is true.
- Update [`Conn::mid_message_detect_eof`](https://github.com/hyperium/hyper/blob/3660443108e22c063cd98906edffb3cff7e9afb6/src/proto/h1/conn.rs#L413) to check if the detection option is false, and if so, return `Poll::Pending`, just as the `allow_half_close` option does.

**Comment by oddgrd** [comment]
Hi Sean! I'd like to work on this one.

**Comment by seanmonstar** [comment]
One thing I'd like for this one is some benchmarks that prove having the extra API surface area is worth it. I wrote the issue when a user suggested it might help, but data would be good to verify :)

**Comment by oddgrd** [comment]
Sure! I'll change my PR to a draft and have a look at benchmarking.

**Comment by oddgrd** [comment]
I am having some difficulty getting conclusive results on the benchmarks. There is some variation in benchmark results between runs, even without changes, and I would expect the impact of this change to be small. I am also new to benchmarking, so if you have any tips here I would appreciate it. I will push a commit to my PR so you can see how I implemented the change in the benches.

I ran the benchmarks with `cargo +nightly bench --features full --bench end_to_end`, first with `mid_message_eof_detection` saved to a file called `e2e-control`, and then without `mid_message_eof_detection` saved to a file called `e2e-variable`. I then compared the runs with [benchcmp](https://github.com/BurntSushi/cargo-benchcmp), and these are the results:

Run 1:
![image](https://user-images.githubusercontent.com/29732646/178142083-a0092347-6d3b-41f6-a6c7-adb4749be099.png)

Run 2:
![image](https://user-images.githubusercontent.com/29732646/178142090-0713bd17-0149-4ef1-bda3-2b5534565ec2.png)

Run 3:
![image](https://user-images.githubusercontent.com/29732646/178142094-0659caf6-2bfa-4b16-a9f3-7c53b569012e.png)

Run 4:
![image](https://user-images.githubusercontent.com/29732646/178142126-65eb578b-6ea5-4d25-a7bd-8e92e8818756.png)

CPU: i7-9700K CPU @ 3.60GHz × 8

**Comment by seanmonstar** [comment]
Yea, it'd likely need a specialized benchmark, running the `hello_world` example and using `wrk` against it. Tagging @bartlomieju, since they said it seemed noticeable on their internal benchmarks.

**Comment by oddgrd** [comment]
Hello again, I had another go at benchmarking as you suggested. I've learned a bit about benchmarking now, mainly that it isn't easy :smile:. I am happy to run them again with different settings/examples if you have any suggestions. I saw a slight improvement with `mid_message_eof_detection` disabled, but the difference is small so it's difficult to conclude.

## Environment
Two digital ocean droplets: `2 GB Memory / 2 Intel vCPUs / 60 GB Disk ∕ NVMe SSD`, one running the Hyper `hello.rs` example with `cargo run --example hello --release --features="full"` in Docker. The other running [wrk](https://github.com/wg/wrk) in Docker with `docker run --rm williamyeh/wrk -t4 -c200 -d30s` against the Hyper droplet. I experimented a bit with the `wrk` settings until I got stable results.

I used two versions of Hyper, one on `master` for control and one on a branch of my PR (rebased to master today) with `mid_message_eof_detection` disabled in `hello.rs`.

<details>
<summary><h2>Benchmarks</h2></summary>

I ran the the benchmark against one version of Hyper 5 times, discarding the first run, before restarting with a different version of Hyper and repeating.

## Master benchmarks
```
4 threads and 200 connections 30 seconds
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.29ms    1.91ms  16.44ms   70.90%
    Req/Sec     9.16k     1.47k   13.27k    64.25%
  1094693 requests in 30.09s, 91.87MB read
Requests/sec:  36378.62
Transfer/sec:      3.05MB
```
```
4 threads and 200 connections 30 seconds
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.08ms    1.96ms 216.10ms   74.08%
    Req/Sec     9.53k     1.33k   13.19k    68.17%
  1139746 requests in 30.08s, 95.65MB read
Requests/sec:  37895.96
Transfer/sec:      3.18MB
```
```
4 threads and 200 connections 30 seconds
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.13ms    1.92ms  14.78ms   70.70%
    Req/Sec     9.39k     1.36k   13.56k    67.83%
  1122451 requests in 30.07s, 94.20MB read
Requests/sec:  37325.91
Transfer/sec:      3.13MB
```
```
4 threads and 200 connections 30 seconds
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.41ms    2.12ms  24.95ms   69.22%
    Req/Sec     8.89k     1.38k   13.18k    66.75%
  1063479 requests in 30.08s, 89.25MB read
Requests/sec:  35352.07
Transfer/sec:      2.97MB
```

## Mid-message-eof-detection disabled benchmarks
```
4 threads and 200 connections 30 seconds
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.11ms    1.87ms  17.62ms   70.45%
    Req/Sec     9.47k     1.49k   13.06k    67.17%
  1132031 requests in 30.08s, 95.00MB read
Requests/sec:  37639.49
Transfer/sec:      3.16MB
```
```
4 threads and 200 connections 30 seconds
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.22ms    1.93ms  17.13ms   70.45%
    Req/Sec     9.23k     1.31k   13.73k    69.17%
  1103604 requests in 30.09s, 92.62MB read
Requests/sec:  36679.78
Transfer/sec:      3.08MB
```
```
4 threads and 200 connections 30 seconds
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.13ms    1.82ms  14.46ms   71.80%
    Req/Sec     9.41k     1.27k   12.86k    68.42%
  1125706 requests in 30.08s, 94.47MB read
Requests/sec:  37426.17
Transfer/sec:      3.14MB
```
```
4 threads and 200 connections 30 seconds
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.04ms    1.95ms  17.28ms   68.82%
    Req/Sec     9.56k     1.59k   20.22k    67.50%
  1142952 requests in 30.09s, 95.92MB read
Requests/sec:  37985.02
Transfer/sec:      3.19MB
```

</details>

**Comment by bartlomieju** [comment]
Sorry for late response, pinging @littledivy who has more context on this

**Comment by seanmonstar** [comment]
So, it sounds like the changes in benchmarks here are nearly unnoticeable. In that case, it seems like the extra complexity in the code isn't really worth it. Thanks for exploring this @oddgrd!

**Comment by oddgrd** [comment]
No problem, I learned a lot about benchmarking and a little bit more about http. Thanks!
