### ISSUE TITLE
Add `Request::protocol()`

### ISSUE THREAD

**Issue by daxpedda** [hyperium/hyper#2921]
**Is your feature request related to a problem? Please describe.**
I'm currently working with `axum` trying to solve the issue of redirecting users from HTTP to HTTPS. To that end I ended up designing an Endpoint that currently handles both protocols on the same port.

The next step would have been to make a service that responds with the redirect when the user connects through HTTP. But `Request` doesn't hold this information.

**Describe the solution you'd like**
Add a new method to `Request` called `protocol()`, returning a new type:
```rust
enum Protocol {
    Http,
    Https,
}
```
It would probably be good to add this to `Response` too.

I'm not entirely sure if this can be considered a breaking change, because implementations have to actually fill in this field correctly, otherwise it will always be the default. If this is considered a breaking change, we can let `protocol()` return an `Option` instead until the next major release.

**Describe alternatives you've considered**
Using extensions here is totally viable too.

**Additional context**
Happy to do the PR if this is considered in scope.

**Comment by seanmonstar** [comment]
Is this supposed to be the scheme part of the request-target? There is currently `req.uri().scheme()`, which if the request headers include, it is set. For example, in these cases:

```
GET http://localhost:1234/yolo HTTP/1.1

```

```
(in HTTP/2)
:scheme = http
:authority = localhost:1234
:path = /yolo
```

**Comment by daxpedda** [comment]
I just verified this again, but HTTP request consistently have no scheme and authority in the `Uri` of their `Request`, I only get the path and query.
I encountered this in `hyper`, wen hacking around with `warp` and now with `axum` (they all use `hyper` underneath anyway).

Is this a bug?

I was wondering if checking the URI scheme might be vulnerable to an attack. If somebody changes a client to send HTTPS requests with the `http://` scheme, the user would be wrongly informed about which protocol is actually used.
We might also just add a check in the HTTPS resolver to check if the correct scheme is used.

**Comment by daxpedda** [comment]
> I just verified this again, but HTTP requests consistently have no scheme and authority in the `Uri` of their `Request`, I only get the path and query.

To demonstrate, I adjusted the `hello` example in `hyper`:
<details>
  <summary>Code</summary>

```rust
use std::convert::Infallible;

use hyper::service::{make_service_fn, service_fn};
use hyper::{Body, Request, Response, Server};

async fn hello(request: Request<Body>) -> Result<Response<Body>, Infallible> {
    println!("{}", request.uri());

    Ok(Response::new(Body::from("Hello World!")))
}

#[tokio::main]
pub async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    pretty_env_logger::init();

    // For every connection, we must make a `Service` to handle all
    // incoming HTTP requests on said connection.
    let make_svc = make_service_fn(|_conn| {
        // This is the `Service` that will handle the connection.
        // `service_fn` is a helper to convert a function that
        // returns a Response into a `Service`.
        async { Ok::<_, Infallible>(service_fn(hello)) }
    });

    let addr = ([127, 0, 0, 1], 3000).into();

    let server = Server::bind(&addr).serve(make_svc);

    println!("Listening on http://{}", addr);

    server.await?;

    Ok(())
}
```

</details>

Output:
```
Listening on http://127.0.0.1:3000
/
/favicon.ico
```

**Comment by seanmonstar** [comment]
> Is this a bug?

No, this is the case with many HTTP/1.1 requests. They arrive like this:

```
GET /favicon.ico HTTP/1.1
Host: localhost:3000

```

Note that there is no scheme in there at all. So in most HTTP/1.1, hyper doesn't have enough information to fill in the `scheme` part. If you as the application developer knew that the connection was always TLS, you can make a middleware filling in that part of the `uri`.

**Comment by daxpedda** [comment]
> If you as the application developer knew that the connection was always TLS, you can make a middleware filling in that part of the `uri`.

So should we just do that then instead of introducing a new type? If yes, I guess we can close this.

**Comment by seanmonstar** [comment]
Yep!
