### ISSUE TITLE
Consider various rewrites of the Headers implementation

### ISSUE THREAD

**Issue by reem** [hyperium/hyper#293]
Through various discussions on PRs here and IRC it's become clear that the header implementation requires some changes.

This is a sort of meta-bug for the various issues, such as #230, #231, #252, and #253.

One possible RC-based rewrite: https://gist.github.com/reem/1ee3162ace6bcdeab239

**Comment by pyfisch** [comment]
This should also take #80, #243 into account.

Probably it would be a good idea to write out before what features the new header implementation should provide. You can extend this wiki page https://github.com/hyperium/hyper/wiki/Header-implementation

**Comment by reem** [comment]
I'd like to bump this issue again - I really think a more safety-first approach is appropriate here. The header logic is almost never going to be the bottleneck, and we can optimize later. Correctness is far more valuable right now.

**Comment by seanmonstar** [comment]
I'm not particularly worried about the performance of `Rc`. My concern instead is that I'd rather not return any kind of smart pointer, if possible. I was experimenting with `Rc` myself, and found that it ruined match statements.

Take this simple example:

```rust
match headers.get() {
    Some(Host { port: Some(3000), .. }) => something(),
    Some(Host { port: Some(9000), .. }) => something_else(),
    _ => ()
}
```

With a smart pointer, it becomes:

```rust
match headers.get() {
    Some(host) if host.port == Some(3000) => something(),
    Some(host) if host.port == Some(9000) => something_else(),
    _ => ()
}
```

Take a look at [this branch](https://github.com/hyperium/hyper/compare/reparsing) that adds reparsing. It's encapsulated all of it's unsafeness into internal modules, and uses a safe API to do everything. The performance impact is minimal, and it allows return `&T` instead of `Ref<T>`.

**Comment by pyfisch** [comment]
Seanmonstars branch looks good to me.

**Comment by pyfisch** [comment]
I think we should use `HeaderMarker` like teepee does: https://github.com/teepee/teepee/blob/6da58b4f2b92b41aee85f8b9490533b040b10954/src/httpcommon/headers/mod.rs#L112

This allows to strongly type the `Connection` header, and other things where you want to refer to a header without actually using a header. 

To prepare for HTTP/2 we should provide 2 header name methods. One that returns the all lowercase name and one that returns the "pretty" name usually used in HTTP/1.x.
```rust
pub trait HeaderMarker {
    type Output: ToHeader + Header + Clone + 'static;
    // e.g. `accept-encoding`
    fn header_name(&self) -> Cow<'static, str>;
    // e.g. `Accept-Encoding`
    fn nice_header_name(&self) -> Cow<'static str>;
}
```
By using the lowercase name everywhere except for formatting we can drop the dependency on unicase.

**Comment by pyfisch** [comment]
I played a little bit with `HeaderMarker` and realised that there is no way to get the "nice" name from a header, if it is saved in `Headers` if using `HeaderMarker`.

So keeping the name part of the Header is better I think. Additionally Rust does not like the UPPERCASE_WITH_UNDERSCORE names the Teepee example uses for `HeaderMarker`
