### ISSUE TITLE
Re-enable the end-to-end, pipeline, and server benchmarks

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2930]
This were disabled as part of #2929, since they depended on `HttpConnector` or `Server::bind`. The first two are easier than the last:

- [x] `benches/pipeline.rs`
- [x] `benches/server.rs`
- [ ] `benches/end_to_end.rs`

**Comment by Robertoskr** [comment]
I will start with reenabling benches/end_to_end.rs

**Comment by seanmonstar** [comment]
There's a comment in #2934 about what makes it a little harder, which may help in writing the PR.

**Comment by Robertoskr** [comment]
I'm a bit new to open source, i did the changes, but need a bit of help for pushing the branch to this repo, when i try to push i get the following error: 
```
Username for 'https://github.com': robertoskr
Password for 'https://robertoskr@github.com': 
remote: Permission to hyperium/hyper.git denied to Robertoskr.
fatal: unable to access 'https://github.com/hyperium/hyper.git/': The requested URL returned error: 403
```

Do you have any idea ? @seanmonstar @oddgrd

**Comment by seanmonstar** [comment]
You can click the "Fork" button at the top right of this page, and then you can `git remote add` your fork, and then push to it. Once you have a branch in your fork, you can make a pull request referencing it.

**Comment by Robertoskr** [comment]
Thank you ! here is the pr: https://github.com/hyperium/hyper/pull/2937
