### ISSUE TITLE
how can i get addr from req when  req.uri().authority() is None

### ISSUE THREAD

**Issue by kulame** [hyperium/hyper#2943]
hi 
    i want to convert a http reqeust to a sockaddr  like the golang hijack.
    https://pkg.go.dev/net/http#Hijacker

i try to follow the example https://github.com/hyperium/hyper/blob/master/examples/http_proxy.rs  
but failed.

because the  uri.authority() is None.
 how can I fetch the addr from req with the uri.authority() is None?

**Comment by seanmonstar** [comment]
Depends if the client sent a request with the address in URI or not. Many are just `GET / HTTP/1.1`, so then you need to check the host header instead, if it is sent.

**Comment by kulame** [comment]
does hyper have a similar function like golang hijack?
it convert a req to a TCPStream directly.
