### ISSUE TITLE
lowercase issue 

### ISSUE THREAD

**Issue by kulame** [hyperium/hyper#2946]
**Version**
0.4.19

**Platform**
Linux home 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Description**
i set response header  X-DTLS-MTU, 
```rust
    let mut res = Response::builder().status(StatusCode::OK);

    let headers = res.headers_mut().unwrap();
    headers.insert("X-DTLS-MTU","1500");
```

and make server 
  .http1_title_case_headers(true)
  .http1_preserve_header_case(true)

it return X-Dtls-Mtu

I expected to see this happen: 
expect return  X-DTLS-MTU

**Comment by seanmonstar** [comment]
I see you've found the other issues, so I'll close this one.
