### ISSUE TITLE
http_proxy example no longer works

### ISSUE THREAD

**Issue by andrewhickman** [hyperium/hyper#2950]
**Version**
git bisect says the first bad commit is 0c8ee93d7f557afc63ca2a5686d19071813ab2b7

**Platform**
64-bit (Windows)

**Description**
When running the `http_proxy` example, it does not work with powershell's `Invoke-WebRequest -Proxy` command.

Server output:
```
> cargo run --features=full --example http_proxy
Listening on http://127.0.0.1:8100
req: Request { method: CONNECT, uri: example.com:443, version: HTTP/1.1, headers: {"host": "example.com:443", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19042; en-GB) PowerShell/7.2.5"}, body: Body(Empty) }
upgrade error: upgrade expected but low level API in use
```

Client output:
```
> Invoke-WebRequest https://example.com -Proxy http://127.0.0.1:8100
Invoke-WebRequest: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
```
Using the previous commit, I get the expected client output:
```
> iwr https://example.com -Proxy http://127.0.0.1:8100

StatusCode        : 200
StatusDescription : OK
Content           : <!doctype html> ...
```

I will test with curl when I get a chance

**Comment by seanmonstar** [comment]
Thanks for noticing this! I think the fix is just adding `.with_upgrades()` after [`.serve_connection` in the example](https://github.com/hyperium/hyper/blob/5e206883984fe6de2812861ec363964d92b89b06/examples/http_proxy.rs#L34). Would you like to file a PR fixing it? :D
