### ISSUE TITLE
Client example doesn't send Host header

### ISSUE THREAD

**Issue by dengzhq** [hyperium/hyper#2951]
**Version**
0.14.20 ,maybe all version
**Platform**
64-bit (Windows) and linux 3.10.0-1160.el7.x86_64

**Description**
when runing `client` example，and my server is a  spring boot server （it is the lib where used by most javaers） ,the dependency version is 
```java
    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>1.5.12.RELEASE</version>
        </dependency>
    </dependencies>
```
and my code is
```java
@SpringBootApplication
@RestController
public class SpringBootBenchApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringBootBenchApplication.class, args);
    }

    @RequestMapping("/java/fiber")
    public String fiber() {
        return "Hello,World";
    }

}
```
and i set the client uri is : http://127.0.0.1:8090/java/fiber and run the client

I expected to see this happen:
```java
Response: 200 OK
Headers: {
    "date": "Fri, 19 Aug 2022 07:39:16 GMT",
    "content-type": "text/plain; charset=utf-8",
    "content-length": "12",
}
```
Instead, this happened:
```java
Response: 400 Bad Request
Headers: {
    "transfer-encoding": "chunked",
    "date": "Fri, 19 Aug 2022 07:49:46 GMT",
    "connection": "close",
}
```
it means that hyper can't as the client  request the spring boot server

**Comment by dengzhq** [comment]
I captured the packets and compared the requests made using `Client::new().get()` and the example `client`，the client not set header,so it received a failure
```rust
header("host", host)
```
From the `Client::new().get()` source code, set_host defaults = true, so Client::new().get()  is success.
This document [host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) shows that host must be set,and rfc docment too,Whether to modify the example？

**Comment by seanmonstar** [comment]
Which example are you using? The `examples/client.rs` one from master? Or from the 0.14.x branch?

**Comment by dengzhq** [comment]
Sorry for replying  now, because I was on vacation two days ago,i used the example The examples/client.rs one from master.

**Comment by dengzhq** [comment]
Maybe it's because I'm not familiar with the use of the method, the api doc shows that if someone use [send_request](https://docs.rs/hyper/0.14.20/hyper/client/conn/struct.SendRequest.html#method.send_request)， must add a Host header yourself before calling this method. But the example/client doesn't explain it，It is easy to cause misunderstanding，Not all users know the need to add a host header。

**Comment by seanmonstar** [comment]
You are right, the example on master recently was changed, and the host header is no longer added automatically. The example should be updated to add the host header.
