### ISSUE TITLE
Make `body::Sender` type and `Body::channel()` constructor private.

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2962]
This is an "easy" task, in that the changes aren't *complicated*:

- Change the `hyper::body::Sender` type to `pub(crate)`.
- Change the `Body::channel()` method to `pub(crate)`.
- Replace any usage in the examples, tests, or docs with an appropriate alternative.
  - This might be as simple as a `Full`, but if specifically showing a channel usage, or needing a channel behavior for a test, a `tokio::sync::mpsc` wrapped in `StreamBody` should work.

**Comment by oddgrd** [comment]
I'll get started on this.
