### ISSUE TITLE
Must be inside a runtime to call Server::bind

### ISSUE THREAD

**Issue by zmitchell** [hyperium/hyper#2980]
**Is your feature request related to a problem? Please describe.**
This is more of a documentation issue. I don't see any mention of needing to be inside the runtime in order to call `Server::bind`, just that the server future must be run by an executor.

In my case I was trying to create a function that would return a future that the caller could spawn at their convenience e.g. they could create the future before starting the runtime, then spawn the future once the runtime was started.

**Describe the solution you'd like**
I would just like the documentation to reflect which functions should be executed in the context of a runtime. I couldn't find this requirement mentioned in the documentation anywhere.

**Comment by seanmonstar** [comment]
That's a fair point... The `Server::bind` concept is gone from 1.0, leaving however a user wants to bind some sort of listener up to them, so hopefully that should be clear based on the runtime types a user picks.
