### ISSUE TITLE
hot upgrade and restart

### ISSUE THREAD

**Issue by GOVYANSONG** [hyperium/hyper#2992]
Is your feature request related to a problem? Please describe.

We would like to achieve high availability and zero downtime in our micro service architecture. We use tonic/hyper stack. particularly, we use unix domain socket transport. In our own research, we have identified solutions employed by envoy, mosn etc. But we lack of insights on how the potential solution would transpire.

Describe the solution you'd like

Since hyper has knowledge of live / open connections, it would be ideal to have access to them during live migration from current binary to newer version. I am not sure the responsibility can be solely born upon hyper. Certain integration is certainly required.

Describe alternatives you've considered

Hyper graceful shutdown is a big plus. live connection and listener migration may be a bit of elusive at the moment. but definitely doable given sufficient resource and knowledge.

Additional context

**Comment by malaire** [comment]
My understanding is that hot restart would require sending file/socket descriptors of live connections via unix socket from old process to new one. (At least this is a possible option of how that could be implemented.)

Stable Rust doesn't yet support sending file/socket descriptors, but this feature is being developed currently: [unix_socket_ancillary_data](https://github.com/rust-lang/rust/issues/76915)

**Comment by malaire** [comment]
Well of course after that required low-level feature is available, it's still a lot of work to actually support hot restart.
