### ISSUE TITLE
Is there any way to remove the 'Date' response header?

### ISSUE THREAD

**Issue by yc-huang** [hyperium/hyper#2998]
It seems that the 'Date' header can't be removed by response.headers_mut().remove() or clear(), and in my case I need to clear all unnecessary response headers to reduce network traffic cost...

**Comment by bossmc** [comment]
`Date` is possibly the only header that `MUST` (in the sense of RFC 2119) be included in an HTTP response (unless the server doesn't have a way to determine the date/time).  See the specification in https://www.rfc-editor.org/rfc/rfc9110#name-date (or earlier RFCs that this obsoletes).  Removing it would thus technically mean you're no longer talking HTTP(S).

Unclear if this means hyper shouldn't expose an "I know what I'm doing" flag to disable the auto-addition of this header...
