### ISSUE TITLE
Make `hyper::Error` public and expose underlying `Kind`

### ISSUE THREAD

**Issue by Ezrashaw** [hyperium/hyper#3007]
**Is your feature request related to a problem? Please describe.**
It seems like a Rust anti-pattern to expose the underlying cause of an error by implementing many methods on `hyper::Error`. We also don't have a easy way to expose metadata related to each error. For example, with `Kind::Listen` we could potentially be more transparent about the underlying TCP listener error, instead of having a generic "operation failed" message. Also, things like: 
```rust
type Cause = Box<dyn StdError + Send + Sync>;
```
are hard to understand and don't give the user a simple and `match`able interface for understanding what went wrong.

**Describe the solution you'd like**
Somehow making `Kind` public so that it can be matched on and error handling can be simplified. This would probably require some refactoring of all those types (why does `ErrorImpl` need to exist?). 

(I'd be happy to do this)

**Describe alternatives you've considered**
Leaving it the way it is: this leaves error handling difficult and not future-compatible.

**Additional context**
None given

**Comment by Ezrashaw** [comment]
This is more a user-facing refactor (does that exist?) than a feature or bug-fix. This seemed the most matching template.

**Comment by seanmonstar** [comment]
While many _do_ open up their error types as a giant enum, I'm of the opinion that that is a mistake. It prevents internal refactoring of how the error type is stored, and makes tight coupling of the library with its dependencies (and their versions). That is much less forwards-compatible.

We do hope to find a medium between a giant enum and the `is_blah` methods, tracked in #2845.
