### ISSUE TITLE
Timer::reset can't soundly have an optimized implementation

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#3027]
In 1.0.0-rc.1, the new `Timer` trait has a method to reset an existing `Sleep` to a new deadline. The default implementation simply creates a new `Sleep` and writes it over the old one, but presumably this method exists to it can be overridden with a better implementation when working with a timer like Tokio's that can have its deadline dynamically adjusted.

However, since the `Sleep` is provided as a `dyn Sleep` and `Sleep` has no downcasting APIs, there is no safe way to confirm that the `Sleep` instance is one created by this `Timer` implementation. That effectively means that the current default implementation is the only sound way of implementing the method.

**Comment by seanmonstar** [comment]
Sigh, yea, I forgot about this. And Rust still hasn't made this any easier; we can't just say `trait Sleep: Any`. So, let's see, I think these are the options:

- Copy the methods from `Any` into `Sleep`, which allows checking `type_id` and then calling `downcast_mut`. To make it safe, it probably needs to implement those methods in a blanket impl. Do we just `impl<F: Future> Sleep for F {}`?
- Maybe we can move the method to `trait Sleep { fn reset(self: Pin<&mut Self>, timer: &dyn Timer) {}`? That might just require having downcast methods on `Timer` instead...
- Ugh.
