### ISSUE TITLE
no `http1` in `server::conn`

### ISSUE THREAD

**Issue by xor5** [hyperium/hyper#3029]
**Version**
0.14.20

**Platform**
Linux xornet 5.19.16-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 16 22:50:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Description**
The gateaway server example

[dependencies]
hyper = { version = "0.14.20", features = ["full"] }
tokio = { version = "1", features = ["full"] }
pretty_env_logger = "0.4"
futures = "0.3"

Instead when running it i get the error
```
error[E0432]: unresolved import `hyper::server::conn::http1`
 --> src/main.rs:3:13
  |
3 | use hyper::{server::conn::http1, service::service_fn};
  |             ^^^^^^^^^^^^^^^^^^^ no `http1` in `server::conn`

error[E0433]: failed to resolve: could not find `http1` in `conn`
  --> src/main.rs:47:42
   |
47 |                     hyper::client::conn::http1::handshake(client_stream).await?;
   |                                          ^^^^^ could not find `http1` in `conn`

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `xorproxy` due to 2 previous errors```

**Comment by seanmonstar** [comment]
As mentioned in the README, the master branch has breaking changes. If you want to use 0.14.x, you see the [relevant branch](https://github.com/hyperium/hyper/tree/0.14.x/examples).
