### ISSUE TITLE
Is `hyper::client::conn::http1::Builder::executor` really needed?

### ISSUE THREAD

**Issue by hatoo** [hyperium/hyper#3035]
**Version**
List the version(s) of `hyper`, and any relevant hyper dependency (such as `h2` if this is related to HTTP/2).

hyper = "1.0.0-rc.1"

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)

**Description**

I'm trying to migrate `hyper = "1.0.0-rc.1"` in my application.
And I've found [`hyper::client::conn::http1::Builder::executor`](https://docs.rs/hyper/1.0.0-rc.1/hyper/client/conn/http1/struct.Builder.html#method.executor).
According to the document, this method is related to HTTP2 but this is a struct for HTTP1.
So I think maybe this method is not needed and can be removed.

Thanks.

**Comment by notgull** [comment]
A client can be upgraded to HTTP2 at any time, so I think that it is necessary.

**Comment by seanmonstar** [comment]
I think the documentation might just need to be updated. Both versions use the executor to spawn a dispatcher task.

**Comment by hatoo** [comment]
Thanks, I understand that the method is needed.

I would like to ask one question before closing this issue, 
> Both versions use the executor to spawn a dispatcher task.

Is this means it is necessary to set `executer` even in the http1 client?
My application seems to work nicely without setting executer.
When executer is used in http1 client?

**Comment by notgull** [comment]
> When executer is used in http1 client?

By default Hyper uses an executor that just spawns the tasks in Tokio.

**Comment by hatoo** [comment]
> By default Hyper uses an executor that just spawns the tasks in Tokio.

I think it panics without setting executer in [this line](https://github.com/hyperium/hyper/blob/master/src/common/exec.rs#L37)
and it actually panics on http2 client with `hyper::client::conn::http2::handshake`.

But I've looked at the comment [here](https://github.com/hyperium/hyper/blob/master/src/common/exec.rs#L19), I'll wait for the default runtime.
