### ISSUE TITLE
Should client::conn::http2::SendRequest be Clone?

### ISSUE THREAD

**Issue by vi** [hyperium/hyper#3036]
Should [`hyper::client::conn::http2::SendRequest`](https://docs.rs/hyper/1.0.0-rc.1/hyper/client/conn/http2/struct.SendRequest.html) be `Clone`, just like [`h2::client::SendRequest`](https://docs.rs/h2/0.3.15/h2/client/struct.SendRequest.html)?

**Comment by seanmonstar** [comment]
Hm, probably yes. It should also likely internally use the `UnboundedSender` (if it isn't already) which allows it to be cloned and so on.

**Comment by LucioFranco** [comment]
This should probably extend to h1 as well?

**Comment by seanmonstar** [comment]
h1 can't send multiple requests concurrently.

**Comment by seanmonstar** [comment]
I don't believe the h1 side has much of a buffer... I think only a slot of 1, where the `SendRequest` puts the next request, and then the dispatch task can poll and take it to serialize to IO. Any more of a buffer for h1 should like be done with `tower::buffer`, I think.

**Comment by LucioFranco** [comment]
@seanmonstar so for a thick client, the idea will be that it will add that clone portion on top of the h1 portion to make the h1 and h2 api's match? That was my concern was that these two very (same named) similar types have different implementations.

**Comment by seanmonstar** [comment]
If a client wanted to serialize requests over the single connection, they could. What `hyper::Client` used to do was reuse the same HTTP/2 connection by cloning it, and use new HTTP/1 connections by calling `connect()`.

I don't think at the `conn::http1` layer we should be making work exactly the same as `conn::http2`.
