### ISSUE TITLE
 Hyper client reuses closed connection

### ISSUE THREAD

**Issue by maxbear1988** [hyperium/hyper#3077]
**Version**
List the version(s) of `hyper`, and any relevant hyper dependency (such as `h2` if this is related to HTTP/2).
0.14.20
**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
Linux kwephis1142986 4.18.0-147.5.2.1.h579.eulerosv2r10.x86_64 #1 SMP Sat Jul 31 09:58:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**Description**
Enter your issue details here.
One way to structure the description:
I write a client program using hyper. client send a request to server,server repsonse 500 and send fin to client after handle the request while connection is put back to connection pool.client immediately send another request, client borrow the last connection and send data to server，server will send a rst to client. client report err connction is reset by peer

[short summary of the bug]

I tried this code:

[code sample that causes the bug]

I expected to see this happen: [explanation]
i expected second request not to use the previous connection

Instead, this happened: [explanation]

**Comment by seanmonstar** [comment]
Does the server send a `connection: close`? Otherwise, if there's some latency in the server sending its FIN packet, then these are natural race conditions that can exist.
