### ISSUE TITLE
Remove version-specific prefixes from builder methods

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#3085]
With the split of the builders into per-version kinds (see #2842 and #2851), I feel there's a new question around whether we should remove the prefixes from the method names. They used to exist because the builders were combined over multiple HTTP versions, so the options were scoped to a version. But now:

```rust
mod http1 {
    impl Builder {
        pub fn http1_title_case_headers() {
            // ...
        }
    }
}
```

It seems all those can have the `http1_` prefix removed, and same for the `http2::Builder`s.

Noticed in https://github.com/hyperium/hyper-util/pull/11#discussion_r1035315089.

**Comment by seanmonstar** [comment]
Leaving for comments for a few days.

**Comment by seanmonstar** [comment]
So, `http1::Http1Builder`? Seems contrary [RFC 356](http://rust-lang.github.io/rfcs/0356-no-module-prefixes.html). Users who want it can rename it on import: `use hyper::client::conn::http1::Builder as Http1Builder`.

**Comment by LucioFranco** [comment]
Oh didn't even know that existed! Yeah seems fine to me.

**Comment by bossmc** [comment]
The APIs are already inconsistent today (e.g. there's `http1_title_case_headers` but also `max_buffer_size` on `http1::Builder`).

Agree with this proposal, the prefixing is now an indirect stutter-naming (`conn::http1::Builder::http1_...`).
