### ISSUE TITLE
Memory increasing with every request

### ISSUE THREAD

**Issue by lab360-ch** [hyperium/hyper#3116]
**Version**

Tested with `1.0.0-rc.2` and `0.14.23`

**Platform**
Linux 5.15.0-57-generic 63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Description**

The memory usage of a hyper server is increasing with every request and never decreasing afterwords.

To reproduce this behavior, I just started the [hello world example](https://github.com/hyperium/hyper/blob/v1.0.0-rc.2/examples/hello.rs) from this repository.

When I start the server with `cargo run --release` the memory usage is: 1680.

![image](https://user-images.githubusercontent.com/38225706/212026590-b1c8aa50-bbb3-4413-a879-62c07a76ac87.png)

After some load generated with `ab -n 20000 -c 30 http://localhost:3000/` the memory is increasing but never decreasing.

After 1. run memory is: 7240
![image](https://user-images.githubusercontent.com/38225706/212027682-8545ff9c-3229-4424-91fe-1a5342e879c2.png)
After 2. run memory is: 7572
![image](https://user-images.githubusercontent.com/38225706/212027810-075c7ca4-9d91-4447-be19-a74a1237d680.png)
After 3. run memory is: 8548
![image](https://user-images.githubusercontent.com/38225706/212027924-6ab96991-de79-4749-99a9-3df0f8d4ba19.png)
After 4. run memory is: 8620
![image](https://user-images.githubusercontent.com/38225706/212028065-320954fe-f154-4a2f-afe2-36a305921cb8.png)
After 5. run memory is: 9384
![image](https://user-images.githubusercontent.com/38225706/212028731-8b50362d-330f-41a0-a19e-afa41764092d.png)

After the five tests, I let the service just run for one hour, but no memory decreasing was shown.

Am I wrong to expect that the server should release the memory they used during high load after the load disappears?

**Comment by LucioFranco** [comment]
The OS can take a while to release memory or may not release it until it needs too. There is nothing specific here with tonic and its likely just what your os is setup to do. You can try using different allocators to see if that improves things. Its quite common to see memory increases like this. You can try to use valgrind to see if there are actually any leaks.
