### ISSUE TITLE
`http2::handshake()` is useless in 1.0 given no default executor

### ISSUE THREAD

**Issue by conradludgate** [hyperium/hyper#3128]
**Version**

hyper 1.0.0-rc2

**Description**

`hyper::client::conn::http2::handshake(io).await` causes an instant panic. Internally it performs `Builder::new().handshake(io).await` which uses the `Exec::Default` executor. There is no longer a default `tokio` runtime implied since the removal of the `runtime` feature. 

https://github.com/hyperium/hyper/blob/master/src/common/exec.rs#L36-L38

There is a TODO in this file to refactor executors. But I couldn't find a relevant issue, so I wanted to open one to ensure this doesn't get included in the official release

**Comment by seanmonstar** [comment]
Good catch, thank you!
