### ISSUE TITLE
Server: Limit or configure request body buffering

### ISSUE THREAD

**Issue by ramiroaisen** [hyperium/hyper#3133]
**Is your feature request related to a problem? Please describe.**
I need to create a server that read request's bodies at low kbps even if clients send data faster.
The problem is that hyper is buffering data of bodies for several minutes ahead of the needed kbps. `Body::data()` is returning chunks of more or less 3 MB. We need a way to get chunks of near 16 KB.

**Describe the solution you'd like**
It would be nice if body buffering could be configured, or at least if someone can point me to the right location in the source where this could be changed.

I'm using hyper with http1 only, as the server sits behind a reverse proxy

**Comment by seanmonstar** [comment]
> Body::data() is returning chunks of more or less 3 MB

That shouldn't be the case, the [default maximum buffer size is currently ~400kb](https://docs.rs/hyper/0.14.*/hyper/server/struct.Builder.html#method.http1_max_buf_size). Unless told not to, hyper will increase it's read buffer until it detects optimum throughput. But it will only do 1 read at a time, until you stream that chunk from the `Body`.
