### ISSUE TITLE
hyper 0.10.x depends on traitobject 0.1.0, which may error in future Rust versions

### ISSUE THREAD

**Issue by phansel** [hyperium/hyper#3136]
**Version**
hyper 0.10.x (e.g. 0.10.15)

**Platform**
Linux m1-asahi 6.1.0-asahi-2-2-edge-ARCH #2 SMP PREEMPT_DYNAMIC Fri, 16 Dec 2022 05:04:23 +0000 aarch64 GNU/Linux

**Description**
hyper 0.10.x (ancient, I know) depends on traitobject 0.1.0, which "contains code which will become an error in future versions of Rust."

See: https://github.com/reem/rust-traitobject/issues/8

This is likely not an issue with versions of hyper newer than 0.10.x (e.g. 0.11.x) as they don't appear to depend on traitobject.

**Comment by seanmonstar** [comment]
There's nothing for us to do, 0.10 is not supported at all.

**Comment by phansel** [comment]
Thanks Sean!
