### ISSUE TITLE
Support for pervasive timeouts

### ISSUE THREAD

**Issue by reem** [hyperium/hyper#315]
We need to provide timeouts for all of our blocking APIs and ways to set timeouts for all internal blocking actions.

**Comment by seanmonstar** [comment]
Indeed, and we had a PR offering timeouts, but the IO reform currently means there is no API to do so for TcpStreams.

**Comment by reem** [comment]
There is now going to be a stable way to timeout on condition variables, so we could implement *something*.

**Comment by seanmonstar** [comment]
Link?

**Comment by reem** [comment]
https://github.com/rust-lang/rust/pull/23949

**Comment by seanmonstar** [comment]
I see. So, to support a timeout using those, I imagine having to kick off 2 threads, one that is parked for X ms, the other that tries to `read()`, and we use a `select! {}` on the 2 receivers.

Doesn't sound cheap...

**Comment by Wilfred** [comment]
If you're not happy using `select!` in hyper itself, how about adding an example to the README? It took me a little fiddling to get it working, so having an example would have helped me.

**Comment by wezm** [comment]
Once `set_read_timeout` is stabilised it can be used to add timeout support, yes?

* http://doc.rust-lang.org/nightly/std/net/struct.TcpStream.html#method.set_read_timeout
* http://doc.rust-lang.org/nightly/std/net/struct.UdpSocket.html#method.set_read_timeout

**Comment by seanmonstar** [comment]
Yep! I'd like to try to start nowish on an API, and put it behind a Cargo feature `timeouts`. Then anyone could use it if they're using a nightly rustc, and we can maybe provide feedback after trying real use. I've just been busy on other parts, but PRs always welcome!
