### ISSUE TITLE
Feature request: send proto upgrade `Response` from handler.

### ISSUE THREAD

**Issue by nurmohammed840** [hyperium/hyper#3157]
The [upgrade example](https://github.com/hyperium/hyper/blob/master/examples/upgrades.rs) from `1.0.0-rc.3` looks odd (in my opinion).

In web socket context, If the server decides to upgrade the connection, It just send a 101 Switching Protocols response, and immediately use internal TCP as WebSocket protocol. 

No need for extra `task::spawn`:
https://github.com/hyperium/hyper/blob/9ed175d1545fa338b6212c4f48be9b3d12821c7a/examples/upgrades.rs#L58-L59

Sure, Its only possible, If there is an option to write response directly (rather then returning writable `Response` object) 

Maybe add such API ?

For example:
```rust
async handle(req: Request<Incoming>) -> Result<Response<..> {
    match hyper::upgrade::send_response_and_upgrade(resp_body, req).await {
        Err(msg) => eprintln!("upgrade error: {msg}"),
        Ok(upgraded) => { ... }
    }
}
```

**Comment by Noah-Kennedy** [comment]
@nurmohammed840 why was this closed?
