### ISSUE TITLE
provide examples of http posts

### ISSUE THREAD

**Issue by softprops** [hyperium/hyper#316]
Im new to rust and am having a hard time figuring out how to compose an  simple http post request. I did find and example in an older 24 days of rust blog but it seems way out of date with current versions of the library

**Comment by reem** [comment]
For clarification, you'd like to see a client post example?

**Comment by softprops** [comment]
Yes please :)

**Comment by seanmonstar** [comment]
```rust
use hyper::Client;

fn main() {
    let mut client = Client::new();
    let res = client.post("https://example.domain/path")
            .body("foo=bar")
            .send();
    match res {
        Ok(res) => println!("Response: {}", res.status),
        Err(e) => println!("Err: {:?}", e)
    }
}
```

See more about the Client: http://hyperium.github.io/hyper/hyper/client/index.html

**Comment by softprops** [comment]
Wow. Super simple. Thanks!

**Comment by softprops** [comment]
Just a quick followup. I wanted to make sure request bodies were encoded correctly and I found a library for doing [form encoding](https://github.com/servo/rust-url) but I'm stumbling on what may be some basic rust basics

Building your example above I'm still running into some rust newbie issues

```rust
extern crate url;
use url::form_urlencoded;

let mut builder = client.post("https://example.domain/path")

let params = vec![("foo", "bar")];

// this fails with the following compiler message
// error: the trait `hyper::client::IntoBody<'_>` is not implemented for the type `collections::string::String` [E0277]
let body = form_urlencoded::serialize(params.into_iter());
builder.body(body);
```

I found the [IntoBody](https://github.com/hyperium/hyper/blob/fcefda091ff02d31677c3b43e5da9734078463d0/src/client/mod.rs#L284-L289) trait impl that seems to point to basic string slices

so I tried to `slice` up the `String` ` form_urlencoded::serialize` returns and I get a borrowing error
 
```rust
extern crate url;
use url::form_urlencoded;

let mut builder = client.post("https://example.domain/path")

let params = vec![("foo", "bar")];

// this now fails because
// src/main.rs:48:15: 48:61 error: borrowed value does not live long enough
//src/main.rs:48    let body = form_urlencoded::serialize(params.into_iter()).as_slice();
//
let body = form_urlencoded::serialize(params.into_iter()).as_slice();
builder.body(body);
```

do you have any pointers for what I'm maybe doing wrong?

**Comment by seanmonstar** [comment]
Yep, your slice doesn't live long enough, because you don't store the backing `String` in a variable on the stack. Try:

```rust
let body = form_urlencoded::serialize(params.into_iter())
build.body(&body)
```

**Comment by softprops** [comment]
without the `as_slice()` and with  `&`. I still run into the missing `IntoBody` impl for `String`

```rust
//src/main.rs:50:12: 50:23 error: the trait `hyper::client::IntoBody<'_>` is not implemented for the type `&collections::string::String` [E0277]
//src/main.rs:50    builder.body(&body);
let body = form_urlencoded::serialize(params.into_iter());
builder.body(&body);
```

adding the `as_slice()`

```rust
// src/main.rs:49:12: 49:34 error: the trait `hyper::client::IntoBody<'_>` is not implemented for the type `&&str` [E0277]
//src/main.rs:49    builder.body(&body.as_slice());
let body = form_urlencoded::serialize(params.into_iter());
builder.body(&body.as_slice());
```

I feel like I'm probably missing something very fundamental.

**Comment by seanmonstar** [comment]
Hm, I assumed the deref coercions would work for that. You could use `&*body`. `*String` gives you a `str`, and then add `&` to get a `&str`.

You can use `as_slice()`, but I believe that is going away in favor of using deref or slicing syntax `&body[]`.

**Comment by softprops** [comment]
it looks like `*body` does give me back a `str` but adding the `&` gets me back to "error:  `body` does not live long enough"

Here's a more cut & paste example

```rust
extern crate hyper;
extern crate url;

use hyper::{ Client, Url };
use url::form_urlencoded;

fn main() {
  let mut client = Client::new();
  let uri = Url::parse("https://api.service.com").ok().expect("malformed url");
  let mut builder = client.post(uri);
  let params = vec![("foo", "bar")];
  let body = form_urlencoded::serialize(params.into_iter());
  builder.body(&*body);
}
```

**Comment by Ryman** [comment]
@softprops It's due to the new scoping rules, you need to bring `params` and `body` to be declared above `builder`.

```rust
fn main() {
  let mut client = Client::new();
  let uri = Url::parse("https://api.service.com").ok().expect("malformed url");
  let params = vec![("foo", "bar")];
  let body = form_urlencoded::serialize(params.into_iter());
  let mut builder = client.post(uri);

  builder.body(&*body);
}
```

**Comment by softprops** [comment]
@Ryman @seanmonstar thanks for rounding this out for me. I got up an running after following @Ryman's last suggestion. Thanks for your patience.
