### ISSUE TITLE
gateway.rs example works slower under load on v1 hyper vs 0.14

### ISSUE THREAD

**Issue by ivanitskiy** [hyperium/hyper#3164]
**Version**
v0.14.24 and v1.0.0-rc3

**Platform**

Ubuntu 20.04 LTS:
> Linux max 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Description**
Compared performance of v0.14.24 and v1.0.0-rc3 using gateway.rs As a result hyper v1.0.0-rc3 is 1.8 times slower than v0.14.24. 

steps:
1. I cloned the hyper repo, then `git checkout` tags (v0.14.24 and v1.0.0-rc3) used in testing
2.  Built  `gateway` example by doing `cargo build --release --example gateway --features="full"` for each git tag at step 1
3. started application server `fortio server -http-port 3000` this will listen on 127.0.0.1:3000 so we can use the gateway to proxy requests to `fortio` application (just serves as an HTTP echo application in that case)
4. using `wrk` as a loading tool to generate load against the gateway

#### against v0.14.24 results 
```
wrk -c 500 -t 500 -d 10s --latency http://localhost:3001/
Running 10s test @ http://localhost:3001/
  500 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    30.08ms   18.26ms 205.30ms   76.47%
    Req/Sec    34.82     16.38   630.00     90.26%
  Latency Distribution
     50%   26.46ms
     75%   38.30ms
     90%   53.07ms
     99%   92.27ms
  176287 requests in 10.10s, 12.61MB read
Requests/sec:  17450.56
Transfer/sec:      1.25MB
```

#### against v1.0.0-rc3
```
wrk -c 500 -t 500 -d 10s --latency http://localhost:3001/
Running 10s test @ http://localhost:3001/
  500 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    51.61ms   27.06ms 315.66ms   74.17%
    Req/Sec    20.06      9.74   398.00     49.24%
  Latency Distribution
     50%   46.54ms
     75%   64.47ms
     90%   86.55ms
     99%  139.68ms
  100284 requests in 10.10s, 7.17MB read
Requests/sec:   9928.33
Transfer/sec:    727.17KB
```

I expected to see this happen: I would expect not a significant perf degradation. More thorough e2e perf testing is needed. This somewhat confirms perf issues with hyper v1-rc3 vs 0.14

Instead, this happened: 1.756 x times o performance degradation in the same gateway example on my setup, just comparing two existing examples and they might have different implementations under the hood.

**Comment by seanmonstar** [comment]
Do the requests or responses have much of a payload? Or just headers?

**Comment by ivanitskiy** [comment]
> Do the requests or responses have much of a payload? Or just headers?
Just a few headers and because there is no body in request nothing to echo.

here is what happening without gateway:
```
# start an application in a separate terminal: `fortio server -http-port 3000` 
# sending a request with curl 
$ curl -v 127.0.0.1:3000
*   Trying 127.0.0.1:3000...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Thu, 09 Mar 2023 19:43:32 GMT
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
```



The same response as expected when sending to a gateway (port 3001) (which reverse proxy to fortio)
```
## gateway-v0.14.24 
curl http://127.0.0.1:3001/ -v
*   Trying 127.0.0.1:3001...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3001 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:3001
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Thu, 09 Mar 2023 19:46:10 GMT
< content-length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
## gateway-v1.0.0-rc3 
$  curl http://127.0.0.1:3001/ -v
*   Trying 127.0.0.1:3001...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3001 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:3001
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Thu, 09 Mar 2023 19:48:14 GMT
< content-length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by seanmonstar** [comment]
Oh, I think this would be because the new code on master no longer uses a client connection pool, because we moved that out of hyper core.

**Comment by ivanitskiy** [comment]
@seanmonstar  could you please provide some references for that? I may try to look at updating gateway.rs to incorporate the connection pool in the master branch. I was under impression that gateway.rs is very fundamentally different v1.0 vs 0.14.

**Comment by seanmonstar** [comment]
Well, looking at the `examples/gateway.rs`, it's not longer just using a `hyper::Client<HttpConnector>`, but rather doing `TcpStream::connect` each time. The pool moved to the hyper-util crate, but we can't make any of the examples in hyper depend on hyper-util, because hyper-util already depends on hyper :)

**Comment by ivanitskiy** [comment]
@seanmonstar  thanks for the detailed info and quick updates. I updated gateway.rs example to use hyper-util, but having some problems due to this in hyper repo, and giving me a hard time (as you mentioned previously a dependency issue)

Having said that, I don't think there is a significant perf degradation. Ideally, perf testing can be redone on HW devices without "noise neighbor" type of issues to have a more reliable result. relatively I don't see a significant perf issue in the gateway.rs using hyper v1 + client from hyper-util.

here are all the details I have:
```
gateway-v1-rc3--with-client-pooling

  500 threads and 500 connections
Running 10s test @ http://localhost:3001
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    29.46ms   18.12ms 206.53ms   78.47%
    Req/Sec    35.82     12.41   100.00     60.59%
  Latency Distribution
     50%   25.46ms
     75%   36.44ms
     90%   51.54ms
     99%   93.92ms
  180856 requests in 10.10s, 12.94MB read
Requests/sec:  17902.61
Transfer/sec:      1.28MB
```


main.rs
```rust
#![deny(warnings)]

use hyper::{server::conn::http1, service::service_fn};
use std::net::SocketAddr;
use tokio::net::{TcpListener};
use hyper_util::client::{connect::HttpConnector, legacy::Client};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    pretty_env_logger::init();

    let in_addr: SocketAddr = ([127, 0, 0, 1], 3001).into();
    let out_addr: SocketAddr = ([127, 0, 0, 1], 3000).into();

    let out_addr_clone = out_addr.clone();

    let client_main = Client::builder(hyper_util::rt::TokioExecutor::new()).build(HttpConnector::new());


    let listener = TcpListener::bind(in_addr).await?;

    println!("Listening on http://{}", in_addr);
    println!("Proxying on http://{}", out_addr);

    loop {
        let (stream, _) = listener.accept().await?;
        let client = client_main.clone();
        // This is the `Service` that will handle the connection.
        // `service_fn` is a helper to convert a function that
        // returns a Response into a `Service`.
        let service = service_fn(move |mut req| {
            let client = client.clone();

            let uri_string = format!(
                "http://{}{}",
                out_addr_clone,
                req.uri()
                    .path_and_query()
                    .map(|x| x.as_str())
                    .unwrap_or("/")
            );
            let uri = uri_string.parse().unwrap();
            *req.uri_mut() = uri;

            async move {
                client.request(req).await
            }

        });

        tokio::task::spawn(async move {
            if let Err(err) = http1::Builder::new()
                .serve_connection(stream, service)
                .await
            {
                println!("Failed to serve connection: {:?}", err);
            }
        });
    }
}
```

```toml
[package]
name = "gateway-v1-rc3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "1.0.0-rc.3", features = ["full"] }
pretty_env_logger = "0.4.0"
tokio = { version = "1.26.0", features = ["net", "rt", "time", "full"] }
hyper-util = { git = "https://github.com/hyperium/hyper-util", features = ["full"] }
```

**Comment by ivanitskiy** [comment]
If that's fine, I can submit a PR with an example of the gateway using `hyper_util::client::legacy::Client` into `hyper_utils` repo.  @seanmonstar any thoughts? This issue can be closed as there is no perf degradation in hyper, but rather a different implementation as a result of decommission of the hyper::client.

**Comment by seanmonstar** [comment]
I'm less certain about putting examples in hyper-util... It has been suggested recently (and a few times) that perhaps we move it all to a `hyperium/examples` repo, instead. That might be a good idea.

But for now, glad to see there wasn't an internal degradation.

**Comment by imgurbot12** [comment]
It's a shame the client is being phased out. I'm sure there are legitimate reasons, but after implementing the same reverse-proxy with and without the connecting pooling, the legacy client is quite literally 4x faster than without.

without client:

```
$ wrk http://127.0.0.1:8001 --latency                                                                                                                                   v3.8.19  time=10s
Running 10s test @ http://127.0.0.1:8001
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.29ms    1.72ms  13.14ms   82.96%
    Req/Sec     8.30k     7.29k   17.70k    32.50%
  Latency Distribution
     50%  341.00us
     75%    1.88ms
     90%    4.01ms
     99%    7.44ms
  165145 requests in 10.01s, 21.73MB read
Requests/sec:  16503.38
Transfer/sec:      2.17MB
```

with-client:

```
$ wrk http://127.0.0.1:8001 --latency                                                                                                                                   v3.8.19  time=10s
Running 10s test @ http://127.0.0.1:8001
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   141.12us   49.59us   2.00ms   90.42%
    Req/Sec    34.80k     1.49k   36.73k    71.50%
  Latency Distribution
     50%  131.00us
     75%  153.00us
     90%  183.00us
     99%  317.00us
  692503 requests in 10.00s, 91.14MB read
Requests/sec:  69246.47
Transfer/sec:      9.11MB
```

Here's the project and [code diff](https://github.com/imgurbot12/httpf/commit/50099c1f2c2e93c7aff9b0181a9aa6baf651d9db) if you're interested.

**Comment by seanmonstar** [comment]
It's not that connection pooling is bad, it's that the public API of it wasn't as stable, so it couldn't be in hyper v1.0. The existing pool exists in hyper-util, and there's an effort (that can always use more help) to redesign it, and then perhaps it _can_ reappear in hyper directly.
