### ISSUE TITLE
Rename `Service` to `Handler` to reduce confusion?

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/hyper#3175]
Currently, we have both a `tower::Service` and `hyper::service::Service` that are not the same trait and differ slightly. I suggest we rename the hyper trait to be called `Handler` since this more closely resembles what it does and leave the name `Service` for tower. This will reduce confusion for users since it can be hard to disambiguate between traits of the same name that come from different crates.

cc @seanmonstar

**Comment by djc** [comment]
I feel like "handler" is typically used to describe a function (or type) that handles requests. Services instead handle a stream of requests (a connection). Therefore I don't think renaming to Handler would be an improvement.

**Comment by ztj** [comment]
Perhaps, as an alternative to `Handler`, `Adaptor` would be suitable.

**Comment by rob2244** [comment]
@seanmonstar Is this still relevant since the removal of the tower dependency? If so I can take it.

**Comment by seanmonstar** [comment]
It is relevant, but still needs a decision. I'm so far not certain it's worth changing the name, but I'm open to hearing convincing arguments for why it should be.

**Comment by seanmonstar** [comment]
With no other arguments in favor of changing the name, I'm inclined to close this as not-planned.
