### ISSUE TITLE
Consider changing the service_fn input to FnOnce

### ISSUE THREAD

**Issue by alkarkhi** [hyperium/hyper#3198]
**Is your feature request related to a problem? Please describe.**

Consider the following code

```
let router = Arc::new("// Router type".to_string()); // to make it non-copy

let listener = TcpListener::bind("127.0.0.1:8080").await.unwrap();

loop {
    let (stream, _) = listener.accept().await.unwrap();
    let router = Arc::clone(&router);

    tokio::spawn(async move {
        if let Err(e) = Http::new()
            .serve_connection(
                stream,
                service_fn(|_req| {
                    // only works with this line
                    // let router = Arc::clone(&router);
                    async move { Ok::<Response<Body>, hyper::Error>(Response::new(Body::from(format!("hello world {}", router)))) }
                }),
            )
            .await
        {
            error!("server error: {}", e);
        }
    });
}
```

Because of the constraints of FnMut, I need to clone the router 2 times. I can't reference it because then it doesn't live long enough.

**Describe the solution you'd like**
Change the service_fn input closure to FnOnce. If one needs to borrow, they could just reference explicitly.

**Describe alternatives you've considered**

**Additional context**

**Comment by seanmonstar** [comment]
Thanks for the proposal! Some thoughts:

- the `FnMut` mirrors the signature of `Service::call`.
- The service can be called multiple times on the same connection, if the closure were `FnOnce`, it couldn't be called again.

**Comment by alkarkhi** [comment]
Hello!

> the FnMut mirrors the signature of Service::call.

Could you explain what you mean here?

> The service can be called multiple times on the same connection, if the closure were FnOnce, it couldn't be called again.

afaik if you only use references, you could call the service multiple times since it'd be treated as a Fn or FnMut.

**Comment by alkarkhi** [comment]
>Could you expand on this?

Nevermind i was wrong. I confused it for something else.

What use cases are there for calling the service multiple times on the same connection?

**Comment by seanmonstar** [comment]
The service is called for every request that is received on that connection. So, of reused by the client, such as with HTTP/1 keep-alive, but also HTTP/2 and 3 reuse the connection much more.
