### ISSUE TITLE
Add internal serialization of debug_data to HTTP/2 GOAWAY frames

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#3200]
It would be useful to be able to send the additional `debug_data` in HTTP/2 GOAWAY frames. The frame currently has a field to hold it, and uses that when decoding, but if we try to _send_ a frame with extra data, it gets ignored. Here's some steps to get this done:

- Set the payload length and serialize the `debug_data` in [`GoAway::encode`](https://github.com/hyperium/h2/blob/8088ca658d90a3874fb6b136b85776424265295b/src/frame/go_away.rs#L52)
- Add a `fn data(self, b: Into<Bytes>)` method to the [frames test support](https://github.com/hyperium/h2/blob/8088ca658d90a3874fb6b136b85776424265295b/tests/h2-support/src/frames.rs#L283).
- Add a unit test to `h2-tests` showing debug data was serialized.

**Comment by Herbstein** [comment]
I picked this up in the linked PR. Though I do expect a bit of guidance is necessary to bring it up to snuff
