### ISSUE TITLE
Export `ServiceFn` type

### ISSUE THREAD

**Issue by jjant** [hyperium/hyper#3208]
**Is your feature request related to a problem? Please describe.**
The function `hyper::service::service_fn` uses a private return type, making it more difficult to compose.

**Describe the solution you'd like**
Make `ServiceFn` `pub`.

**Comment by bdferul** [comment]
I second this

**Comment by seanmonstar** [comment]
For now, I don't think this is likely. `service_fn` is a simple utility, and if you need to compose with more service things, you likely want the adapter in `hyper-util` and to use `tower::ServiceFn`.

**Comment by monoid** [comment]
In my use case, I need to use it in `hyper_server::accept::Accept<I, S>` as a second trait argument.  The project doesn't use `tower`.
