### ISSUE TITLE
peer_certificate returns None, even if there is a secure connection with a client certificate

### ISSUE THREAD

**Issue by jarlah** [hyperium/hyper#3218]
**Version**
hyper 1.0.0-rc.3
tokio-native-tls 0.3.1
native-tls 0.2.11

**Platform**
Darwin [....]  22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64
aka macOS 13.3.1 Ventura

**Description**
tls_stream.get_ref().peer_certificate() returns None, even if there is a secure connection with a client certificate. I have a full working example, where I am struggling to find out why hyper is not able to find the peer certificate. I expect it to return the peer certificate, the certificate passed into the curl command with `--cacert ca.pem --cert client.pem --cert-type PEM`.

See https://github.com/guillaumepellegrino/acsrs/pull/6#issuecomment-1534588288 for a concrete example reproducing the exact behaviour. Are we doing it wrong? Or are we assuming that peer certificate should return something it can't?

**Comment by seanmonstar** [comment]
I don't think this has anything to do with hyper. You're trying access the certificate from the IO transport, which seems to be from native-tls?

**Comment by jarlah** [comment]
Fair point @seanmonstar but is there no examples of an hyper server that uses Peer cert ? Do you know of any ? I will Close this and make issue in native tls or tokio native tls.

**Comment by jarlah** [comment]
made issue in rust-native-tls, with a concrete non hyper related repository. Raw usage of rust-native-tls. and it still doesn't give me peer cert .... https://github.com/sfackler/rust-native-tls/issues/262
