### ISSUE TITLE
Main README server framework recommendation

### ISSUE THREAD

**Issue by thegreathir** [hyperium/hyper#3222]
The main README is recommending Warp as a high level HTTP server library, but there are other choices and it seems Axum is a better one to recommend because it is developed by Tokio organization similar to Hyper itself.

**Comment by seanmonstar** [comment]
I happen to think warp is a decent option, but I'm biased :). However, I do agree that if people have no idea what they want, Axum is a better default. So, I'd probably lean towards this adjustment:

- Suggest Axum as a great default, especially if you're not sure what you want.
- Keep warp as a suggestion, pointing out "it's a little different, meant for people who like Functional Programming and type ~~ab~~use."
- I wish we could point at some sort of directory, such as arewewebyet.org, but it's rather outdated.
