### ISSUE TITLE
Unresolved import when trying to use impl_header!

### ISSUE THREAD

**Issue by maximih** [hyperium/hyper#323]
I am trying to implement a custom HTTP header using impl_header macro from hyper crate but it seems it cannot resolve the hyper::header module.

Here is my code:

    #[macro_use] extern crate hyper;

    use hyper::header;

    struct CustomHeader(String);
    impl_header!(CustomHeader, "name", String);

And here is the compiler error:

 	<hyper macros>:11:14: 11:20 error: unresolved import `header::HeaderFormat`. Maybe a missing `extern crate header`?
  	<hyper macros>:11 Result { use header:: HeaderFormat ; self . fmt_header ( f ) } } }
                               ^~~~~~
	<hyper macros>:1:1: 11:67 note: in expansion of impl_header!
	lib.rs:4:1: 4:45 note: expansion site
	error: aborting due to previous error
	Could not compile `macro_issue`.

**Comment by seanmonstar** [comment]
Tried against master? I think a fix for this was merged in this morning (so
hasn't been published via cargo yet).

**Comment by maximih** [comment]
Seems parts of it was fixed on master but there is one issue left (check ` use header::HeaderFormat;` below) causing the whole macro to fail:

        impl ::std::fmt::Display for $from {
            fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
                use header::HeaderFormat;
                self.fmt_header(f)
            }
        }

    <hyper macros>:11:14: 11:20 error: unresolved import `header::HeaderFormat`. Maybe a missing `extern crate header`?
    <hyper macros>:11 Result { use header:: HeaderFormat ; self . fmt_header ( f ) } } }

**Comment by naps62** [comment]
I'm getting the exact same issue. Also tried against master, resulting in the same partial fix
