### ISSUE TITLE
Replacing the URL parser for 2x performance

### ISSUE THREAD

**Issue by anonrig** [hyperium/hyper#3238]
**Is your feature request related to a problem? Please describe.**
I'm one of the authors of [Ada URL](https://ada-url.com). Ada is currently used by Node.js and is well-tested and used by millions of developers of Ada. Right now; Ada is the default URL parser starting from Node 18, 19, and 20.

We recently created a [Rust crate](https://github.com/ada-url/rust), which provides 2x faster URL parsing with more up-to-date conformance to the WHATWG standard.

Replacing the `url` package with `ada-url` will improve the performance, and wanted to ask if you're interested in replacing it.

**Describe the solution you'd like**
Replacing the default URL parser with `ada-url`

**Comment by seanmonstar** [comment]
Hey there! hyper doesn't use the `url` crate, so we wouldn't need to do any replacement here. Thanks for the offer though!

**Comment by seanmonstar** [comment]
As more of a side note, I imagine people using Rust will probably prefer dependencies also written in Rust, even if a C or C++ project does appear to be more performant. It's always possible to update the Rust dependency to be faster. Just my thoughts.

**Comment by Darksonn** [comment]
Your main priorities for a url parser (or any other kind of parser) should be correctness and memory safety. Speed is a distant third on that list. Replacing a Rust implementation with a C++ one is just not justifiable at all IMO. 

A good way to think of this is the rule of two:

![rule of two](https://github.com/hyperium/hyper/assets/928074/dbdec0a6-36b8-438c-9307-80b15eddae06)

[source](https://security.googleblog.com/2021/04/rust-in-android-platform.html)
