### ISSUE TITLE
Removing a raw header

### ISSUE THREAD

**Issue by filsmick** [hyperium/hyper#326]
Currently, I can insert or overwrite a header by doing, for example:
```
request_headers.set_raw("Accept-Encoding", vec![b"gzip, deflate".to_vec()]);
```
But apparently, I cannot remove it, only set it to a different value.
Wouldn't it be useful to add a remove_raw() method to Headers?
Raw headers are very useful if you don't know what headers to send at compile time, for example, or for quick prototyping.

**Comment by seanmonstar** [comment]
Good call, this would be needed to support XHR's `removeHeader` method.

**Comment by jdm** [comment]
removeRequestHeader is unspecc'd, so I don't expect Servo to make use of this.
