### ISSUE TITLE
How do I create an `impl Stream` from `body::Incoming` in hyper 1.*.*

### ISSUE THREAD

**Issue by alkarkhi** [hyperium/hyper#3268]
I want to implement file upload using hyper. In hyper 0.14.\*, `Body` implemented the `Stream` trait but in hyper 1.\*.\* it got removed for stability reasons. However crates like `multer` require a body which implements `Stream` as seen in their [hyper example](https://github.com/rousan/multer-rs/blob/master/examples/hyper_server_example.rs). Its the same with other async formdata/multipart crates. I was wondering if someone could help me with this.

Thank you!

**Comment by seanmonstar** [comment]
You could make use of: https://docs.rs/http-body-util/0.1.*/http_body_util/struct.StreamBody.html

**Comment by alkarkhi** [comment]
> You could make use of: https://docs.rs/http-body-util/0.1.*/http_body_util/struct.StreamBody.html

I did try this initially but it'll only implement `Stream` when `Incoming` implements `Stream` so I still get the trait bounds issue
