### ISSUE TITLE
Streaming/Chunked Response Performance Issues [Resolved: Nagle's]

### ISSUE THREAD

**Issue by Clueliss** [hyperium/hyper#3269]
**Version**
```
hyper = "0.14.27"
```

**Platform**
```
$ uname -a
Linux lpf-main 6.3.12-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul  6 04:05:18 UTC 2023 x86_64 GNU/Linux
```

**Description**
The following description is mostly copied from my bug report which I made to axum, because I didn't think about the fact that it uses hyper for transport (https://github.com/tokio-rs/axum/issues/2107).

Hello there,
we are trying to figure out chunked HTTP responses and have observed performance issues when the server is
loaded with just a few clients (< ~12) which each sends some number of requests. This issue seems to disappear once the server is properly loaded with more clients.

We have two routes: one regular and one streaming. Both routes to basically the same thing; the streaming route is basically just indented for cases where responses get very large. The following code is a sketch of how the routes roughly look like.
```rust
async fn regular_route(query: String /*extracted from url query params*/) -> Response<Body> {
    let (tx, rx) = tokio::sync::oneshot::channel();

    rayon::spawn(move || {
        let mut buf = Vec::with_capacity(16 * 4096);
        // some potentially expensive work here (not async)
        // is in different thread to not block the executor
        tx.send(Ok(buf)); // or send Err(...)
    });
    
    let res = rx.recv().await.unwrap();
    // error handling here
    
    Response::builder()
        ... set headers
        .body(Body::from(res.unwrap()))
        .unwrap()
}

async fn streaming_route(query: String /*extracted from url query params*/) -> Response {
    let (tx, rx) = tokio::sync::mpsc::channel();

    rayon::spawn(move || {
        let mut buf = Vec::with_capacity(16 * 4096);
        loop {
            // potentially expensive work here
            // then write chunk of calculated data into buf
            // maybe send Err(...) over the channel if something went wrong
            // break out at some point

            if buf.len() >= 16 * 4096 {
                tx.send(Ok(std::mem::replace(&mut buf, Vec::with_capacity(16 * 4096))));
            }
        }

        tx.send(Ok(buf));
    });
    
    Response::builder()
        ... set headers
        .body(Body::wrap_stream(tokio_stream::wrappers::UnboundedReceiverStream::new(rx))))
        .unwrap()
}
```

While the performance of the regular route is very good the streaming route is roughly 8 times slower on the same requests.
As of right now we have no idea why it behaves this way. We would have expected a slight performance decrease but certainly not that much. Especially because an otherwise equivalent server in C++ (using restinio) does not have this large performance gap between streaming and regular routes. (Note: hyper outperforms restinio basically everywhere except this one special case: few clients + streaming route)

If you have any insights for us that would be greatly appreciated.
Have a nice day.

**Comment by seanmonstar** [comment]
The weird part to me is that you say with more clients, the performance improves? Huh...

Could it be that threads in the thread pool are all spawned and going... I don't know how to finish that thought, each ending doesn't make much sense to me...

**Comment by Clueliss** [comment]
Oh and would you be interested in some general performance data? It probably doesn't make much sense to go into much of the details of what exactly is measured but maybe just to see the perf difference between the scenarios and the reference implementation in restinio (?)

The workload is querying a graph database btw.

**Comment by seanmonstar** [comment]
I suppose a question I'm wondering about is: is the slow down in hyper, or is it the work being done to fulfill the streaming response?

**Comment by Clueliss** [comment]
I found a kind of minimal example with which you can probably reproduce the bug. 

But first some notes: I did some profiling and it seems like the CPU time spent on actual work is virtually identical in both routes, but in the streaming route the CPU spends a lot of time waiting for something, no idea what its waiting for.

In this specific example on my machine the streaming route is roughly twice as slow as the regular one. Even though they are doing virtually the same thing.

Server:
```rust
async fn hyper_regular() -> Response<Body> {
    let (tx, rx) = oneshot::channel();

    std::thread::spawn(move || {
        let chunk_sz = 16 * 4096;

        let mut buf = Vec::with_capacity(chunk_sz);

        for _ in 0..1000 {
            let mut ix = 0;
            for _ in 0..100_000 {
                ix += 1;
                std::hint::black_box(ix);
            }

            buf.extend_from_slice(&vec![b'a'; 10]); // *1 HERE
        }

        let _ = tx.send(Ok::<_, io::Error>(buf));
    });

    let response = rx.await.unwrap().unwrap();

    Response::builder()
        .body(response.into())
        .unwrap()
}

async fn hyper_stream() -> Response<Body> {
    let (tx, rx) = mpsc::unbounded_channel();

    std::thread::spawn(move || {
        let chunk_sz = 16 * 4096;

        let mut buf = Vec::with_capacity(chunk_sz);

        for _ in 0..1000 {
            let mut ix = 0;
            for _ in 0..100_000 {
                ix += 1;
                std::hint::black_box(ix);
            }

            buf.extend_from_slice(&vec![b'a'; 10]); // *1 HERE
        }

        let _ = tx.send(Ok::<_, io::Error>(buf));
    });

    let response_stream = Body::wrap_stream(UnboundedReceiverStream::new(rx));

    Response::builder()
        .body(response_stream)
        .unwrap()
}

async fn hyper_route(req: Request<Body>) -> Result<Response<Body>, io::Error> {
    if req.uri().path().ends_with("/stream") {
        Ok(hyper_stream().await)
    } else if req.uri().path().ends_with("/regular") {
        Ok(hyper_regular().await)
    } else {
        unreachable!()
    }
}

#[tokio::main]
async fn main() {
    let ms = make_service_fn(move |conn: &AddrStream| {
        let s = service_fn(move |req: Request<Body>| hyper_route(req));
        async move { Ok::<_, Infallible>(s) }
    });

    hyper::Server::bind(&"0.0.0.0:9080".parse().unwrap()).serve(ms)
        .await
        .unwrap();
}
```

Client:
```rust
#[tokio::main]
async fn main() {
    let endpoint = std::env::args().nth(1).unwrap();
    let endpoint: Uri = endpoint.parse().unwrap();

    let client = hyper::Client::new();

    let start = Instant::now();

    for _ in 0..200 {
        let mut resp = client.get(endpoint.clone())
            .await
            .unwrap();

        while let Some(Ok(chunk)) = resp.body_mut().next().await {
            std::hint::black_box(chunk);
        }
    }

    let end = Instant::now();
    println!("took: {}s", end.duration_since(start).as_secs_f64());
}
```

The regular route takes ~4s and the streaming one ~8s.
Curiously, if you increase the size of the vecs at `*1 HERE` to e.g. 1000, the streaming route is suddenly taking less time than before (~4.8s).

Hope this helps

**Comment by huntharo** [comment]
@Clueliss - I really wanted to help explore this as I have an idea (and I like using Wireshark for fun).   But the examples left out the `Cargo.toml` files and the `use` statements.  It's clear this is using some old versions because some of the functionality has been moved or removed.

Could you post a repo to GitHub that has a complete and buildable example?  If you do, I will try to take a look and I'll appreciate it because I want to avoid just such a performance problem.  Thanks!

**Comment by Clueliss** [comment]
I've created the repository now at https://github.com/dice-group/hyper-issue-example

What I noticed is that, if you _reuse_ the client the issue appears, if you don't  it doesn't.
In the repo you will find the `client0x` which has lines commented with `variant 1` and `variant 2`. They are mutually exclusive. If you use the one where the client is reused the issue appears, in the other case it does not.

This is very confusing because `reqwest` which uses `hyper<1` internally explictly tells you to reuse the client and it has the exact same problem ("The Client holds a connection pool internally, so it is advised that you create one and reuse it." - https://docs.rs/reqwest/0.11.23/reqwest/struct.Client.html).

I encountered this because in hyper>=1.0 (`client1x` in the repo) I couldn't figure out how to reuse the connection (client was sometimes erroring with ECANCELED) so I just didn't and the bug never appeared.

**Comment by Clueliss** [comment]
I just remembered something: We also saw this issue using another http client (a java one) so this probably has nothing to do with the hyper client

**Comment by huntharo** [comment]
@Clueliss - As I suspected, `Nagle's algorithm` was not being disabled in the `server`.  The issue was NOT in the `client`.

On Linux this led to a small delay that was cumulative in your tests and that was large relative to the time it took to send your test response.  If the machines were further away (e.g. 500 miles) and/or the response was larger (e.g. > 100 KB) then the impact of this delay would have been less noticeable.

@seanmonstar - I would suggest that the performance impacts of not disabling Nagle's algorithm (by calling `set_nodelay(true)` should be mentioned in the docs and in the code examples.  Giving folks a hint that they should be looking into this an evaluating if they want to disable it for both the client and server would be very helpful.  I can put together a PR for that if you'd like.

## PR that Fixed Example in this Issue

https://github.com/dice-group/hyper-issue-example/pull/2

### After - Nagle's Algorithm Disabled - No Delays on Chunked Responses

```
Server running as pid 52560
Listening on http://127.0.0.1:3000 routes /stream and /regular

Using ENDPOINT_BASE: http://127.0.0.1:3000

Hyper<1.0
Using regular route
Using path: /regular
Default nodelay: false ❌ 

Set nodelay: true ✅ 

took: 6.139572461s
Using stream route
Using path: /stream
took: 6.015059211s ✅ 

Hyper>=1.0
Using regular route
Using path: /regular
took: 5.937338878s
Using stream route
Using path: /stream
took: 5.954765711s ✅ 
```

### Before - Delays when Reusing Connections on Chunked (Streamed) Responses

Note: this happened only when the `server` was running on Linux.  On Mac OS there was no difference in performance between`/stream` and `/regular` and this probably has to do with a slight difference in the implementation details or settings tuning of Nagle's algorithm across the two OSes.

```
Server running as pid 55182
Listening on http://127.0.0.1:3000 routes /stream and /regular

Using ENDPOINT_BASE: http://127.0.0.1:3000

Hyper<1.0
Using regular route
Using path: /regular
Default nodelay: false ❌ 

Set nodelay: false ❌ 

took: 6.040918837s
Using stream route
Using path: /stream
took: 8.620580588s ❌ 

Hyper>=1.0
Using regular route
Using path: /regular
took: 5.923212336s
Using stream route
Using path: /stream
took: 8.755907796s ❌ 
```


## No mentions of `nodelay` in docs or code

<img width="1196" alt="image" src="https://github.com/hyperium/hyper/assets/5617868/80d9208a-a73b-4086-be57-391905481de0">

**Comment by huntharo** [comment]
> I encountered this because in hyper>=1.0 (`client1x` in the repo) I couldn't figure out how to reuse the connection (client was sometimes erroring with ECANCELED) so I just didn't and the bug never appeared.

The `ECANCELED` issue was happening because `poll_ready` was not being called and awaited before `send_request` was called.  This lead to a race condition where the last byte of the response body stream would be read and then `send_request` would get called just before the code that would mark the prior response as completed was run.

This was fixed in this PR:
https://github.com/dice-group/hyper-issue-example/pull/1

**Comment by Clueliss** [comment]
Wow thank you for all your work and explainations, really appreciated 🙂

I will be trying that out in our actual use case (probably next week)

**Comment by seanmonstar** [comment]
Thanks for looking into it, I'm glad it was able to be solved!
