### ISSUE TITLE
What's the maximum header size limit?

### ISSUE THREAD

**Issue by bagder** [hyperium/hyper#3283]
**Version**
current from master

**Platform**
Linux

**Description**
I'm using hyper in curl, and when I receive a HTTP/1 response with **many** response headers, hyper cuts off the response and returns an error due to `message head is too large`. (With a `HYPERE_INVALID_PEER_MESSAGE` error)

I cannot find what this exact limit is. I can't even find it in the hyper source code.

**Comment by seanmonstar** [comment]
To be more specific, are you asking about the list of headers, or the length of any single header? If receiving a _lot_ of headers, the current limit of name/value pairs in hyper is 100. That was picked somewhat arbitrarily, and could be increased if more than that were common, but so far no one has ever needed it 🤷 .

**Comment by bagder** [comment]
Thanks for this.

I can't tell you what's right but it seems Firefox, Chrome (and curl) all accept name/value pairs all the way until they reach the maximum response header size. Which seems to be limited to somewhere between 256KB and 1MB.

**Comment by ajgh1** [comment]
I'm not sure about client-side, but Apache httpd 2.4's default `LimitRequestFields` (100) and `LimitRequestFieldSize` (8190) settings imply if a request's headers go much over 800KB, default httpd configurations will reject it.  These limits can be changed of course, but the manual cautions that should not be necessary under normal circumstances.

**Comment by seanmonstar** [comment]
No, that limit is for the HTTP/1 decoder. HTTP/2 has a setting that you can send, `SETTINGS_MAX_HEADER_LIST_SIZE `, to tell peer how much you're willing to accept, and hyper will enforce it for you.

**Comment by f3lixding** [comment]
> the current limit of name/value pairs in hyper is 100. That was picked somewhat arbitrarily, and could be increased if more than that were common, but so far no one has ever needed it

I ran into the same problem (message head is too large) for reqwest and I found my way here to this thread. 
Just wanted to +1 on this. It would be fantastic if we can have the MAX_HEADERS be configurable.

**Comment by Millione** [comment]
need to be increased or can be configurable.

**Comment by PureWhiteWu** [comment]
Hi, we've encountered same problem here. Our HTTP request has 100+ headers and hyper failed with error.

Is there any plan to make it configurable?

**Comment by grodin** [comment]
I think this was resolved in #3532 but the issue seems to have been left open

**Comment by seanmonstar** [comment]
Good call, thanks for conneting the issue!
