### ISSUE TITLE
Change QualityItem to use a newtype Quality(u16) instead of f32

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#330]
f32 gives more precission than we need, since the only valid values are `0.000 - 1.000`. Also, by their very implementation, compare floats can be tricky.

Instead, we should have a `pub struct Quality(u16)`. The value inside should be between `0 - 1000`. With a simple integer, comparison can be exact, and we also shave off half the memory size.

Formatting can be easily done, however a convenience method would be required, such as `q(value: f32) -> Quality`, that converts an `f32` into the appropriate `u16`. This allows users to still write using float syntax, without the downsides (example: `QualityItem { item: "en-US", quality: q(0.9) }`).

**Comment by reem** [comment]
This is such a good idea. We should have a convention for no floats in headers.

**Comment by pyfisch** [comment]
+1 I did not think this far. Using integers  is much better here.

**Comment by pyfisch** [comment]
I am working on this.

**Comment by pyfisch** [comment]
Close this.
