### ISSUE TITLE
Introduce `tracing` as a feature flag

### ISSUE THREAD

**Issue by suryapandian** [hyperium/hyper#3304]
**Is your feature request related to a problem? Please describe.**
Downstream crates that use `hyper` have feature flag `tracing` using which users can choose not to download tracing library  or use `tracing`.  Ex: [octocrab](https://docs.rs/crate/octocrab/latest/features#tracing) has this feature. Even though [octocrab](https://github.com/XAMPPRocky/octocrab) has this feature `tracing`, the `tracing` library anyway gets downloaded since `hyper` is a dependency of octocrab and hyper downloads `tracing` libraries by default.

**Describe the solution you'd like**
Hyper to hide `tracing` behind a feature flag. That way, downstream crates that use `hyper` can choose not to have `tracing` if needed.

**Describe alternatives you've considered**
Downstream crates start using `tracing` by default

**Additional context**
By allowing `tracing` as a feature flag, users can opt out of `tracing` and avoid having to download `tracing` related libraries

**Comment by seanmonstar** [comment]
It would be nice. As part of #2874, we'll move `tracing` to an unstable feature in 1.0. We can't move it to a feature in 0.14, since it could suddenly mean tracing is disabled for people who have `default-features = false`.

**Comment by seanmonstar** [comment]
This was done as part of v1.
