### ISSUE TITLE
Backport Http1 Graceful Shutdown Fix

### ISSUE THREAD

**Issue by bonedaddy** [hyperium/hyper#3306]
# Overview

https://github.com/hyperium/hyper/pull/3261 introduced a fix for slow graceful shutdowns, however it is only available in a release candidate version which introduces breaking api changes.

# Suggestion

Backport the graceful shutdown fix into v0.14.27  and cut a new release allowing third-party packages like axum to implement the fix.

**Comment by seanmonstar** [comment]
This was considered a behavioral breaking change, which is why it was only included in 1.0.
