### ISSUE TITLE
Extracting Proxy from TCP request

### ISSUE THREAD

**Issue by 0xAlcibiades** [hyperium/hyper#3313]
**Is your feature request related to a problem? Please describe.**
As a developer developing a tonic gRPC streaming application (based on hyper) behind a layer 3 load balancing technology, I need to extract the clients IP, which is passed through with Proxy Protocol: https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt 

**Describe the solution you'd like**
I'd like to have hyper optionally decode PROXY from the tcp request and add it as an X-Forwarded-For header to the HTTP request.

**Describe alternatives you've considered**
Implementing from scratch vs trying to get a feature in hyper, as I haven't found anything which does this.

**Additional context**
https://github.com/Proximyst/proxy-protocol/blob/main/src/version2.rs
https://www.haproxy.com/blog/use-the-proxy-protocol-to-preserve-a-clients-ip-address
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#client-ip-preservation

**Comment by seanmonstar** [comment]
Dealing with the PROXY protocol is out of scope for hyper, but since you can provide custom IO, you could apply a layer that does that before giving the IO to hyper.

**Comment by 0xAlcibiades** [comment]
> Dealing with the PROXY protocol is out of scope for hyper, but since you can provide custom IO, you could apply a layer that does that before giving the IO to hyper.

So do you think this would be more something to be dealt with in Tokio?

**Comment by seanmonstar** [comment]
No, not likely in Tokio. There might be an existing library that is able to handle it. If not, you could make a small piece of code to read off the `TcpStream` before handing it to hyper.
