### ISSUE TITLE
Make `tracing` an unstable feature

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#3319]

**Comment by RamziA961** [comment]
Hello, I'm currently working on this.
I've already marked all usages of tracing and imports with `#[cfg(feature = "tracing")]`.

I've also modified `Cargo.toml`, to make the `tracing` optional and added tracing as a feature as such:
```toml
# Utilize tracing (currently unstable)
tracing = ["dep:tracing"]
```
Is there anything I am missing? If not, I can open a PR.
