### ISSUE TITLE
Do you plan to release 'mock.rs' for external use ?

### ISSUE THREAD

**Issue by Byron** [hyperium/hyper#334]
I am currently using hyper for making client side requests and would like to use the code and macro defined in the `mock.rs` module. However, it seems impossible right now without copying and altering the code.

Nonetheless, mocking the client seems like something everyone using it would want to do.

**Would you consider releasing something like `hyper-test`, similar to `iron-test`, to help users of `hyper` to test their programs ?**

**Comment by Byron** [comment]
I have quickly put together my own version of it - it's by now means representative in terms of quality, but it is something I can use for now.

https://github.com/Byron/yup/tree/master/lib/hyper-mock

**Comment by reem** [comment]
This seems like a great idea. I've long wanted a supertest-like wrapper around hyper's client.

**Comment by Byron** [comment]
Good - I will keep working on my own little fork for my own use, and in time, it will be published on crates as `yup-hyper-mock`, with all the due credits intact. Unless you have a better idea, or concerns, of course.

**Comment by talevy** [comment]
++ I would also love to see this! thank you @Byron for extracting this and republishing it as a crate!

**Comment by seanmonstar** [comment]
I don't want to make the mock module part of the public API (I'd hate that improving hyper tests might be a breaking change). Also, since there's already a crate that provides this functionality published, I'll just close this.
