### ISSUE TITLE
unresolved import `hyper::Client`

### ISSUE THREAD

**Issue by MarkSwanson** [hyperium/hyper#335]
I can't seem to build a simple test that uses hyper; rustc gives me:

hyper_client.rs:8:5: 8:10 error: unresolved import `hyper::Client`. Did you mean `self::hyper`?
hyper_client.rs:8 use hyper::Client;
                      ^~~~~
error: aborting due to previous error

I simply copy/pasted the examples/client.rs into my own test project/hyper_client.rs.
Any idea why this isn't working?

hyper_client.rs:

#![feature(env, old_io)]
extern crate hyper;

use std::env;
use std::old_io::stdout;
use std::old_io::util::copy;

use hyper::Client;
...

Cargo.toml:

[package]
name = "rust-test"
version = "0.0.1"

[dependencies]
hyper = "*"

**Comment by seanmonstar** [comment]
Only possible thing I can think of is that you need to put `extern crate` rules inside your `lib.rs` (or main.rs if an executable).

**Comment by MarkSwanson** [comment]
Ok, I'm sure it's not your fault.
It's probably my fault, or I may have found an issue. 
I'll close this and circle back for a deeper look shortly.
