### ISSUE TITLE
Improvements to the Headers.set_raw API

### ISSUE THREAD

**Issue by sbstp** [hyperium/hyper#336]
Is there a particular or technical reason why the API of `set_raw` takes a `Vec<Vec<u8>>`? It would be a lot nicer to use if it also accepted strings. This is something I'm willing to create a pull request for (with guidance), if you're interested in it.

**Comment by seanmonstar** [comment]
We specifically haven't made that more ergonomic. It exists for the cases
that MUST use it, like in Servo to provide XMLHttpRequest. Otherwise, it's
safer to use the typed API. Mistakes will be caught at compile time.

**Comment by SBSTP** [comment]
People are probably going to use it anyway, it would be nice for it to have a clean API. People should know the risks taken by using this method. 

For instance, I'm currently working on a tiny library that gets your external ip address using UPNP. There is a mandatory header called "SOAPAction" whose value never changes. I have to take a `&'static str` and convert it into a vector, and then put that inside another vector. I could also create a custom header, but that would generate a lot boilerplate which is for the most part, unnecessary.

**Comment by seanmonstar** [comment]
You can easily create a simple header type using the impl_header! macro.

**Comment by reem** [comment]
I think we should move to marker types and get rid of this distinction.

**Comment by seanmonstar** [comment]
@reem that wouldn't change this particular issue. This issue would just be
asking for a more ergonomic implementation of a `Raw` marker.

**Comment by reem** [comment]
You're right, this issue might still be here. It would be pretty easy to add an `IntoRawHeader` for and implement it for `String`, `&str`, `&[u8]`, `&[Vec<u8>]`, `Vec<u8>`, `Vec<Vec<u8>>`, `Vec<String>`, etc.

**Comment by SBSTP** [comment]
I can create a pull request for this if you want it. There's still the issue of this bypassing the safety mechanisms though.
