### ISSUE TITLE
publishing hyper-util?

### ISSUE THREAD

**Issue by mattklein123** [hyperium/hyper#3410]
Just saw https://seanmonstar.com/blog/hyper-v1/, congrats! I'm noticing that a lot of code I use has been moved to hyper-util, but it doesn't look like hyper-util is actually currently published.

What is the plan for publishing hyper-util with versioning? Or is there a different way I'm supposed to consume it (direct git reference, etc.). If this is documented somewhere please let me know. I could not find it. 

Thank you.

**Comment by seanmonstar** [comment]
Publishing it is the next step, it'll be tracking in [this milestone](https://github.com/hyperium/hyper/milestone/8). There's no more issues pending at the moment, but I think after we kick the tires, we'll find the minimal needed changes to be able to ship it, and those will become issues so we can track them easily.

**Comment by mattklein123** [comment]
> but I think after we kick the tires, we'll find the minimal needed changes to be able to ship it, and those will become issues so we can track them easily.

OK if you end up publishing even with some RC version I would be happy to help test the upgrade.
