### ISSUE TITLE
hyper-util: move connect under legacy module?

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#3414]
I suspect an eventual next-gen `Client` would be [something like this](https://github.com/hyperium/hyper-util/blob/master/src/client/client.rs):

```rust
pub struct Client<M> {
    // Hi there. So, let's take a 0.14.x hyper::Client, and build up its layers
    // here. We don't need to fully expose the layers to start with, but that
    // is the end goal.
    //
    // Client = MakeSvcAsService<
    //   SetHost<
    //     Http1RequestTarget<
    //       DelayedRelease<
    //         ConnectingPool<C, P>
    //       >
    //     >
    //   >
    // >
    make_svc: M,
}
```

Which would likely mean some improvements and changes to the `connect` module. In order to break less people, we could move what's currently in [connect](https://github.com/hyperium/hyper-util/tree/master/src/client/connect) to be at `hyper_util::client::legacy::connect`.

**Comment by kaffarell** [comment]
Opened up a PR!
