### ISSUE TITLE
Add a example using tests like httptest for mock

### ISSUE THREAD

**Issue by SandHilt** [hyperium/hyper#3421]
**Is your feature request related to a problem? Please describe.**
I use httptest to mock calls and test expectations on test but dont since reworking to v1

**Describe the solution you'd like**
I'd like some examples to mock my test like httptest do.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by seanmonstar** [comment]
We don't have any control over the `httptest` crate. So I'm going to close this.

But as I mentioned in a similar issue, I'd be open to a `hyper-test` crate, if someone wanted to put together a more detailed proposal.
