### ISSUE TITLE
Hyper 0.14.27 deprecated/backports features don't produce any warnings, but can't upgrade to hyper 1.0

### ISSUE THREAD

**Issue by carols10cents** [hyperium/hyper#3425]
**Version**

0.14.27 and 1.0+ :)

**Platform**

macOS arm64 (development) and linux 64 bit (server), I don't think this is relevant

**Description**

👋🏻 Hi! I'm trying to help [InfluxDB](https://github.com/influxdata/influxdb) upgrade from hyper 0.14.27 to hyper 1.0.

A bunch of code uses `hyper::Body` from 0.14, which [used to be a struct](https://docs.rs/hyper/0.14.27/hyper/body/struct.Body.html), and in hyper 1.0 [it's a trait](https://docs.rs/hyper/latest/hyper/body/trait.Body.html). So I know we're not compatible for that reason, and likely others as well. 

I was hoping to get some guidance on how the code needs to be updated to enable upgrading to 1.0. I saw in the [1.0 release post](https://seanmonstar.com/blog/hyper-v1/) the link to [this hyper blog post from March 2023](https://seanmonstar.com/blog/this-month-in-hyper-march-2023/) that said hyper starting in version 0.14.25 would have the features `deprecated` and `backports` to help people prepare to upgrade. Great!

So [I turned these features on everywhere that lists hyper as a dependency](https://github.com/integer32llc/influxdb/commit/6ce1b9b12b89107a7d0394c2efa801ee392d979b), ran `cargo check --all-features --all-targets --workspace`, and I'm not seeing any warnings as I expected to. Checking out [this branch on my fork](https://github.com/integer32llc/influxdb/tree/upgrade-hyper) should allow for reproducing.

However, if I try changing all those hyper dependencies to 1.0, everything breaks 😂 

Am I doing something wrong with the deprecated/backports features?

**Comment by seanmonstar** [comment]
We added the warnings to things that people could upgrade while still using 0.14. Those warnings came out several months ago. We felt it would just be annoying to people if there were warnings on types that they _couldn't_ fix yet. So, the change from `Body` being a type to a trait, or `Client` and `Server` being moved to a different crate. (See #3052).

I would like to put together a longer guide "how to upgrade from 0.14", mentioned in #3411.

**Comment by izderadicka** [comment]
Same problem here - just started looking at way to upgrade to 1.0.  Used deprecated feature - no warnings, but upgrade to 1.0 breaks project completely.  Looks like changes in 1.0 are massive, most visible is missing Body struct, but also others - make_service_fn, already mentioned Server, AddrIncomming, AddrStream  to start with.

I was hoping that with deprecated I can gradually prepare for upgrade in 0.14, but it does not seem to work. Feeling bit desperate now, not knowing where to start - so the guide would be very much welcomed. Especially how to replace Body struct with something similar and universal (can serve bytes, stream of chunks ...) as Body is omnipresent in my program.

**Comment by seanmonstar** [comment]
I've published that guide: https://hyper.rs/guides/1/upgrading/

It's certainly missing something I'm sure. If there's a question that it doesn't cover, we can fix it (file an issue).

For now, I'll close this as answered.
