### ISSUE TITLE
Make send_file example streaming

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#3432]
The `send_file` example currently reads the entire file into memory. It would be better to stream the file, to show how to do so in case of large files.

- Instead of using `tokio::fs::read()`, we can use `tokio::fs::File::open()``.
  - Then, the `File` can be wrapped in a `tokio_util::io::ReaderStream`.
  - That stream can be converted into a body with `http_body_util::StreamBody`.
- But the "not found" body is not a stream, it is still a `Full<Bytes>`. So, to be able to return both, the final body type needs to a `http_body_util::combinators::BoxBody<Bytes, std::io::Error>`. You can use `http_body_util::BodyExt::boxed()` to create one.

**Comment by acedogblast** [comment]
How would we add tokio_util as a new dependency?
I get this error when building the example.

**Comment by seanmonstar** [comment]
You can add `tokio-util` to the `[dev-dependencies]` in the root `Cargo.toml`.

**Comment by seanmonstar** [comment]
Done in #3433.
