### ISSUE TITLE
[SSRF] Ability to prohibit connections to subnet ranges

### ISSUE THREAD

**Issue by TroyKomodo** [hyperium/hyper#3437]
**Is your feature request related to a problem? Please describe.**
In an effort to prevent SSRF (Server Side Request Forgery) there should be a way to prevent hyper clients from connecting to servers in particular subnets. For example, we can prevent all internal communications. Meaning, the client will not connect to any IPv4 or IPv6 address that is inside of the VPC (the private ranges). This includes if the remote server responds with a redirect which instructs the client to connect to a different IP than initially advertised.

**Describe the solution you'd like**
Ideally as part of the request builder, we could specify blacklisted subnets or whitelisted subnets.

**Describe alternatives you've considered**
I have not looked much into the problem of SSRF using user provided data and URLS (like a webhook service) but I was wondering why there is no solution at the HTTP Client Layer.

**Additional context**

Our use case is for webhooks and S3 endpoint addresses.

**Comment by seanmonstar** [comment]
If you're using hyper's pooling client (`hyper::Client` in 0.14, `hyper_util::client::legacy::Client` for 1.0), it is generic over any connector. So you could create a custom connector that checks for any IP ranges and returns an error if you dislike it.
