### ISSUE TITLE
First byte timeout

### ISSUE THREAD

**Issue by DFINITYManu** [hyperium/hyper#3454]
We have in hyper a HTTP1 header read timeout (which is strangely not available for HTTP?) and this works great... if the client sends at least one byte (or a newline?).

If the client never sends a single byte, and just holds the connection open, the timeout never triggers.

I suggest we either make the timeout trigger even when no bytes have been sent (make the timer start ticking the minute `serve_connection()` is called) or we introduce another field explicitly for first byte timeout.

This will harden hyper servers against clients who attempt to open and hog connections open without any intention of sending any data.

**Comment by seanmonstar** [comment]
Yes, several have indicated that a separate timeout makes sense: https://github.com/hyperium/hyper/pull/3185#issuecomment-1728216663

**Comment by finnbear** [comment]
Now that [the header read timeout starts immediately](https://github.com/hyperium/hyper/commit/0eb1b6cf4d914ce9c3f8e92a8b43754eba27a327), this issue can be closed as resolved :rocket:
