### ISSUE TITLE
Can not create hyper::Error

### ISSUE THREAD

**Issue by incker** [hyperium/hyper#3459]
You are advising to make `TcpStream::connect(addr).await` That returns io::Error
But I can not convert io::Error to hyper::Error - everything is private

Next you recommend to do is handshake. handshake already returns hyper::Error.
This 2 steps will always go together. And no ability to convert one error into each other is not good.

thank you, if you could help

**Comment by GlenDC** [comment]
I think the rational is that `hyper` should be in full control in where a `hyper::Error` comes from and how it was created. Next to that in a sufficient complex scenario you'll anyway also end up with other possible error types that have nothing to do with `std` or `hyper` and that you within the same code path have to return.

I think the answer is the same either way, box it or wrap it in a type such as an enum.

That is at least how I see it. I am however not a contributor or maintainer. So not sure how much that is worth.

**Comment by seanmonstar** [comment]
The error from `TcpStream::connect()` is not a hyper error. You could define your own Error type, maybe an enum, or you could use a `Box<dyn std::error::Error>`, or one of the crates like `anyhow`.
