### ISSUE TITLE
hyper-util missing `max_pending_accept_reset_streams`

### ISSUE THREAD

**Issue by allan2** [hyperium/hyper#3461]
hyper 0.14.27 has it <sup>[[1]](https://docs.rs/hyper/0.14.27/hyper/server/struct.Builder.html#method.http2_max_pending_accept_reset_streams)</sup>. It was merged [here](https://github.com/hyperium/hyper/pull/3201).

hyper-util 0.1.1 is missing it <sup>[[2]](https://docs.rs/hyper-util/latest/hyper_util/server/conn/auto/struct.Http2Builder.html)</sup>.

The other 10 http2 methods are present. This is the only one missing.

PR incoming

**Comment by dsgallups** [comment]
It appears that [the referenced PR](https://github.com/hyperium/hyper/pull/3201/files/e8296d1c5bded88a508f1ca1f35791c30803182d)'s changes didn't make the cut into 1.0.0. Is there any reason why the pattern of calling the `inner` value on the builder's internal builder should not also occur for `max_pending_accept_reset_streams`? If it should, then this parameter should be readded to `hyper/src/proto/h2/server.rs`.

I'm no git wizard, but I could copy/paste those changes into a new PR for `hyper 1.x`
