### ISSUE TITLE
Provide public constructur for Incoming - for testing

### ISSUE THREAD

**Issue by izderadicka** [hyperium/hyper#3475]
**Is your feature request related to a problem? Please describe.**
Incoming cannot be constructed in client code, which is generally fine apart of TESTS.
I do have some test, where I test incoming requests against some modules.
In pre 1.0 It was just fine, as for Incoming request there were exact type, which could be created in tests.
Now I need to make code generic, only because of tests, which sucks, as regular code is just happy with concrete Incoming type.

**Describe the solution you'd like**
Make some public method to construct Incoming -  is necessary just limited to test cfg 

**Describe alternatives you've considered**
Make main code generic,  but if this is just for tests to work, it's kinda of overkill

**Additional context**
Maybe I'm missing something, if there is already some good way how to test code that accept Request<Incoming>?

**Comment by seanmonstar** [comment]
Currently, it's recommended to make the handlers generic, so that you can provide a mocked body type in tests.
