### ISSUE TITLE
Re-enable end-to-end request chunks benchmarks

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#3477]
The request chunks benchmarks were disabled as part of the upgrade to v1.0. It should now be easier to re-enable them.

- Update the [code](https://github.com/hyperium/hyper/blob/d3cfb9e0b1928701cfdd96c9551c4bd81c24e83a/benches/end_to_end.rs#L347-L358) to use an async `mpsc` channel, and wrap it in a `http_body_util::StreamBody`.
- Remove `#[ignore]` from the benchmarks that were using chunks.

**Comment by GlenDC** [comment]
Can I take this one?
