### ISSUE TITLE
Suggestion to Include 'Salvo' in Framework Recommendations

### ISSUE THREAD

**Issue by fankaiLiu** [hyperium/hyper#3487]
I'd like to extend my gratitude for developing hyper , it's a  tool that's been essential for the Rust community.
Could you consider adding [salvo](https://github.com/salvo-rs/salvo) to your list? It's a user-friendly server framework that relies on hyper.Including salvo might help users exploring their server options in Rust. :)

**Comment by seanmonstar** [comment]
Thanks for the kind words :)

I'd personally rather not grow a list of recommendations, generally, and leave that up to something like arewewebyet.rs and other things.

**Comment by fankaiLiu** [comment]
> Thanks for the kind words :)
> 
> I'd personally rather not grow a list of recommendations, generally, and leave that up to something like arewewebyet.rs and other things.

Thanks for the reply and have a great day!
