### ISSUE TITLE
hyper-util's auto conn cannot be used without h2

### ISSUE THREAD

**Issue by davidpdrsn** [hyperium/hyper#3493]
For axum I'd like to give users the choice to only use http1 or http2 to avoid pulling in extra dependencies such as the h2 crate. That is not currently possible since enabling hyper-util's `server-auto` feature unconditionally enables `http1` and `http2`.

**Comment by seanmonstar** [comment]
Ah yea, that seems like a mistake. Removing it now would be breaking, right?

I haven't thought it all the way through, but could we add some way to detect if the features weren't enabled specifically, and add a warning, and then "break" a few releases later?

Or we could release 0.2 on the quicker side.

**Comment by davidpdrsn** [comment]
I think we have to make some breaking changes to the API because it currently uses things like [`Http2ServerConnExec`](https://github.com/hyperium/hyper-util/blob/master/src/server/conn/auto.rs#L77) which are only available when h2 is. Haven't thought hard about it but not sure if we can somehow change the trait bounds depending on which features are enabled 🤔

**Comment by seanmonstar** [comment]
As of hyper-util v0.1.2, it can be.
