### ISSUE TITLE
Change client example to only pass uri.path()

### ISSUE THREAD

**Issue by JadKHaddad** [hyperium/hyper#3519]
https://github.com/hyperium/hyper/blob/b1ee2284e25864c64ee608e237e607667c6e648e/examples/client.rs#L59

Cloned main, ran `cargo run --features="full" --example client http://167.99.134.66:8888/`, server response: `"GET http://167.99.134.66:8888/ HTTP/1.1" 404`

Request was sent to `http://167.99.134.66:8888/http://167.99.134.66:8888/`: `<url>/<url>`

Uri should be `.uri(url.path())` not `.uri(url)`

**Comment by seanmonstar** [comment]
Ah yes, good point. The example used to be correct, when the URL was used for the pooled client to make the connection, but now that the connection is made separately, just the path should be passed.

**Comment by IvanLi-CN** [comment]
why not `path_and_query()`?

additionally, It seems that many examples have this problem, but httpbin.org will not complain about this problem, depending on the implementation of the HTTP server.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#http_requests

> The request target, usually a [URL](https://developer.mozilla.org/en-US/docs/Glossary/URL), or the absolute path of the protocol, port, and domain are usually characterized by the request context. The format of this request target varies between different HTTP methods. It can be
- An absolute path, ultimately followed by a '?' and query string. This is the most common form, known as the origin form, and is used with GET, POST, HEAD, and OPTIONS methods.
`POST / HTTP/1.1`
`GET /background.png HTTP/1.0`
`HEAD /test.html?query=alibaba HTTP/1.1`
`OPTIONS /anypage.html HTTP/1.0`
- A complete URL, known as the absolute form, is mostly used with GET when connected to a proxy. GET https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages HTTP/1.1`
- The a`uthority component of a URL, consisting of the domain name and optionally the port (prefixed by a ':'), is called the authority form. It is only used with CONNECT when setting up an HTTP tunnel. `CONNECT developer.mozilla.org:80 HTTP/1.1`
- The asterisk form, a simple asterisk ('*') is used with OPTIONS, representing the server as a whole. `OPTIONS * HTTP/1.1`
