### ISSUE TITLE
http1 Connection no longer Send in 1.0

### ISSUE THREAD

**Issue by cbiffle** [hyperium/hyper#3526]
**Version**
`hyper` 1.1.0, specifically.

**Platform**
Linux, though this is a compile-time error so the platform shouldn't matter.

**Description**
I'm attempting to port a Tokio-based HTTP/1-only server from hyper 0.14 to hyper 1.1. The server accepts connections and then spawns a tokio task to handle each one.

In 0.14, I created an `Http` and set `http1_only`. I've guessed that the equivalent in 1.1 is creating a `hyper::server::conn::http1::Builder` and then using that to make `...::Connection` objects.

However, unlike the http1-only Connections produced by 0.14, the `...http1::Connection` object is not `Send`. This makes using it with `tokio::spawn` difficult. Architecturally it's not clear to me why an HTTP1 Connection state object would be allergic to being sent across threads, so I'm wondering if this is an accidental oversight.

I'm considering using the `hyper_util` `auto` connection, which _is_ `Send`, but I'd be a lot more comfortable if I could disable http2 explicitly, and `hyper_util` doesn't appear to have an equivalent to 0.14's `http1_only` setting.

What have I missed? Thanks in advance.

**Comment by sfackler** [comment]
Here is the Send implementation for Connection: https://docs.rs/hyper/latest/hyper/server/conn/http1/struct.Connection.html#impl-Send-for-Connection%3CT,+S%3E

**Comment by cbiffle** [comment]
Wow, it seems like I completely misdiagnosed the issue I'm having then. Please disregard.
