### ISSUE TITLE
Partial connection close via `SendRequest`

### ISSUE THREAD

**Issue by sinui0** [hyperium/hyper#3533]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to gracefully close the connection from the client side after ownership of the IO has been passed to `hyper::client::conn::http1::Connection`. This presents an issue if the server does not respond to a request, as it will just hang. If the client application wants to timeout it has to manually `Drop` the `Connection`. But the appropriate thing to do would be to call close on the pipe (which if using TLS would compliantly send a `CloseNotify` alert prior to closing).

**Describe the solution you'd like**
I think a good feature to have available is to add a `close` method to `SendRequest`, which would signal to `Connection` that it should `poll_close` the connection to shutdown the write half. After which it will just continue polling the read half until it closes. If the server is still totally unresponsive to this then it would be appropriate for the user to just `Drop` the connection.

**Describe alternatives you've considered**
Alternatively a `shutdown` method could be added to `SendRequest` which would force `Connection` to return `Poll::Ready` early so the user could retrieve the IO from it and close it themselves. I think it would be important for `Connection` to finish sending any in-progress requests prior to doing so.

**Comment by seanmonstar** [comment]
If you drop both the `SendRequest` and any `ResponseFuture`, the `Connection` will see that it should tear the connection down. Is that not sufficient?
