### ISSUE TITLE
Help with Frame Mapping

### ISSUE THREAD

**Issue by janbraunsdorff** [hyperium/hyper#3550]
**Is your feature request related to a problem? Please describe.**
I was wondering, how to manipultate single Frames in one Request. So I discoverd, that the body has an Method called 'map_frame' an takes an clousure. But when I call this function, nothing happends.

Is this function for this purpose or do I miss something?

**Describe the solution you'd like**
```rust
fn transform_request(req: Request<Incoming>) -> Request<Incoming> {
    let (parts, body) = request.into_parts();
    let new_body = body.map_frame(do_byte_manipulation_here).into_inner();
    Request::from_parts(parts, new_body)
}

fn do_byte_manipulation_here(fame: Frame<Bytes>) -> Frame<Bytes> {}
```
**Describe alternatives you've considered**
One more elegant solution could be an interception during the dispatch operation.

Maybe there is already a solution for this problem, but I am not able to find them.

**Additional context**
Example frame:
Frame<16384 bytes> => checking for some specific byte Patterns => returing Frame<15336 bytes>

**Comment by seanmonstar** [comment]
Calling `into_inner()` undoes the map calm you just did. Bodies are streamed, so the mapping isn't instantaneous but rather applied as each frame arrives.

**Comment by janbraunsdorff** [comment]
Hi,
Thank you for your Quick Response.
Could you provide a  code snippet how to subscribe or intercept this steaming event?

**Comment by seanmonstar** [comment]
You nearly had it, just remove the `into_inner()` call and you can map the frames.

**Comment by janbraunsdorff** [comment]
now I am  confusied. If I remove the ```into_inner()```, I can not construct a new request to send it to the Server behind the proxy. 

```rust
fn transform_request(req: Request<Incoming>) -> Request<Incoming> {
    let (parts, body) = req.into_parts();
    let new_body = body.map_frame(do_byte_manipulation_here);
    Request::from_parts(parts, new_body)
}

```

```
 --> src/handler/body_mapper.rs:22:32
    |
22  |     Request::from_parts(parts, new_body)
    |     -------------------        ^^^^^^^^ expected `Incoming`, found `MapFrame<Incoming, fn(Frame<...>) -> ... {remove_signuter}>`
    |     |
    |     arguments to this function are incorrect
    |
    = note: expected struct `hyper::body::Incoming`
               found struct `MapFrame<hyper::body::Incoming, fn(hyper::body::Frame<bytes::Bytes>) -> hyper::body::Frame<bytes::Bytes> {do_byte_manipulation_here}>`
```

**Comment by seanmonstar** [comment]
Mapping the frames is changing the body type. So you'll need to change your return type. The [Rust book](https://doc.rust-lang.org/book/) should be a helpful resource for learning Rust.

Since this isn't a bug in hyper, I'm going to close the issue.
