### ISSUE TITLE
need help hyper::Error(User(ManualUpgrade))

### ISSUE THREAD

**Issue by thedtvn** [hyperium/hyper#3558]
**Version**
```
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1.3", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["full"] }
hyper-tls = "0.6.0"
md-5 = "0.10.6"
base64 = "0.21.7"
tokio = { version = "1", features = ["full"] }
url = "2.4.1"
bytes = "1.5.0"
http-body-util = "0.1.0"
openssl = { version = "0.10", features = ["vendored"]}
```
**Platform**
Windows 64-bit

**Description**
i try to open upgrade tcp but it raise hyper::Error(User(ManualUpgrade))

I tried this code:

![image](https://github.com/hyperium/hyper/assets/80153297/ef011e81-f645-47ab-95c0-f6371638bbe6)

I expected to see this happen: 
try to make `hyper::upgrade::on` and run it on tokio::spawn
then make tunnel in there and then it open 

Instead, this happened: 
but it return 101 Switching Protocols but it not on tunnel it just return 101 Switching Protocols and then close
![image](https://github.com/hyperium/hyper/assets/80153297/5ca04e6f-ebe8-4432-a6f6-3c5107d1ee47)

**Comment by Borber** [comment]
May I ask how you solved this problem? I am also facing this problem.
