### ISSUE TITLE
Documentation for `header_read_timeout` is incomplete

### ISSUE THREAD

**Issue by jorendorff** [hyperium/hyper#3567]
Three mini-issues here:

- [Documentation for `.header_read_timeout()`](https://docs.rs/hyper/latest/hyper/server/conn/http1/struct.Builder.html#method.header_read_timeout) doesn't mention that it requires `.timer()` or it'll panic.

- The example in [the docs for `http1::Builder`](https://docs.rs/hyper/latest/hyper/server/conn/http1/struct.Builder.html) uses `header_read_timeout` without `timer`. It's not meant as complete running code, but still, it's weird that if you did try to use it, you'd panic.

- No pointer to an implementation of Timer for tokio. I found [a full implementation in a doc-comment](https://github.com/hyperium/hyper/blob/7206fe30302937075c51c16a69d1eb3bbce6a671/src/rt/timer.rs#L3), but unfortunately that's a private module.

**Comment by dswij** [comment]
The example Timer implementation for `Tokio` is a working example. The module is private, but we're exposing `hyper::rt::{Sleep, Timer}` [here](https://github.com/hyperium/hyper/blob/7206fe30302937075c51c16a69d1eb3bbce6a671/src/rt/mod.rs#L15), which is what you'd need to implement this.

**Comment by jorendorff** [comment]
I agree with all of that. I think the three points all still stand, as opportunities for improvement. Will eventually give it a shot if nobody beats me to it.

**Comment by dswij** [comment]
That's fair. The doc for `rt::{Timer,Sleep}` is also asked in #3411.

**Comment by james58899** [comment]
There is an implementation available in [hyper-util](https://docs.rs/hyper-util/0.1.3/hyper_util/rt/tokio/struct.TokioTimer.html), maybe this can be mentioned in the documentation.

**Comment by dswij** [comment]
The docs for hyper::rt will be added in https://github.com/hyperium/hyperium.github.io/pull/121.

Will close this issue since we're also tracking it in #3411, and `header_read_timeout` docs were updated.

Thanks for the report @jorendorff
