### ISSUE TITLE
Constantly get a 'Failed to connect: HttpStatusError' when querying the Github API

### ISSUE THREAD

**Issue by davidrhyswhite** [hyperium/hyper#361]
Trying to make a simple request to the Github API but keep getting a HttpStatusError returned.

```
let mut client = Client::new();
let mut res = match client.get("https://api.github.com/users/octocat").send() {
    Ok(res) => res,
    Err(err) => panic!("Failed to connect: {:?}", err.message())
}
println!("Response: {:?}", res.status_raw());
```

A curl request reveals the following:

```
$ curl -i https://api.github.com/users/octocat
HTTP/1.1 200 OK
Server: GitHub.com
Date: Wed, 04 Mar 2015 20:21:05 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1276
Status: 200 OK
...
```

**Comment by seanmonstar** [comment]
Ah, it seems Github doesn't use `\r\n` for line endings. Shame on Github, spec says they should. Shame on hyper, spec says it should be robust enough to accept just `\n`.

I've been working on a new parser that already handles this.

**Comment by davidrhyswhite** [comment]
Ah, shame on Github. Guess I'll need to find a different API to play around with Rust and Hyper.

**Comment by pyfisch** [comment]
@davidrhyswhite It kind of works now with the [client example](https://github.com/hyperium/hyper/blob/932baac1717d892af4ee908a7c9237784286cced/examples/client.rs) but Github returns a 403:

```
$ cargo run --example client https://api.github.com/users/octocat
     Running `target/debug/examples/client https://api.github.com/users/octocat`
Response: 403 Forbidden
Headers:
Content-Type: text/html
Cache-Control: no-cache
Connection: close
```

Looks like Github does not like Hyper.

**Comment by pyfisch** [comment]
`User-Agent` header is required: https://developer.github.com/v3/#user-agent-required

**Comment by reem** [comment]
I'm going to close this and open a new issue about `User-Agent` handling.
