### ISSUE TITLE
Testing libraries that use hyper

### ISSUE THREAD

**Issue by jimmycuadra** [hyperium/hyper#362]
I'm building a library that uses hyper for making HTTP requests and looking for a way to test methods that make a request. The only code I can find that might allow a request to be stubbed is the `mock_connector` macro from the `mock` module, but it's not exported. What is the recommended way to test HTTP requests from a library using hyper?

**Comment by seanmonstar** [comment]
The design of hyper is such that you can provide a custom connector or listener (client or server), which helps specific app needs, but also allows testing implementations to exist. Perhaps multiple mocking crates will exist at some point.

For now, the `mock` module in hyper isn't exported because I wasn't sure it was any good. I certainly didn't want to stabilize on it (and have people's libraries break if I change it). I'm undecided which way is better.

**Comment by jimmycuadra** [comment]
Different apps may have different use cases, but I think the most common use cases would be the ability to return a canned response for all requests, or specific requests based on properties of the request. In most cases, this would probably just be the URL, but potentially people might have needs to return different responses based on headers, body, etc.

Do you think a stubbing system would be appropriate to include in hyper? Or as a separate crate? Having test-specific hyper code end up compiled into a non-test binary of someone's app is not desirable, and I'm not sure how rustc treats code marked with `#[cfg(test)]` in dependent crates. If it's not possible to compile a dependent crate's test code only when the main crate is being compiled in test mode, perhaps the hyper stubbing system would need to be in another crate.

**Comment by seanmonstar** [comment]
If I were to expose the the `mock` module and remove the `#[cfg(test)]`, then rustc would compile it. However, llvm (or the linker) *should* kill dead code, so I wouldn't worry about that myself.

My concern is: I'm certain I'll want to add things to `mock` as hyper grows/matures, and eventually adding more things will make me want to refactor some of it. If it's part of a public API, then I have to worry about breaking people's tests. I don't want to feel hesitant to improve the testing of hyper itself.

In the mean time, @Byron has published a crate of the current mock module that you can use: https://crates.io/crates/yup-hyper-mock

**Comment by jimmycuadra** [comment]
Fair enough. Thanks for the responses!
