### ISSUE TITLE
Include addresses in error messages

### ISSUE THREAD

**Issue by jdm** [hyperium/hyper#364]
It would be nice if printing out an HttpIoError showed the problem address: `HttpIoError(IoError { kind: OtherIoError, desc: "unknown error", detail: Some("Name or service not known") })`

**Comment by seanmonstar** [comment]
Is it difficult to match the Url with the error? It's a sync function
call...

Also, perhaps that information could be included in std::net?

**Comment by jdm** [comment]
I suppose we could print the address ourselves, but it seems like an easy papercut to avoid at the library level. Maybe libstd is the right place, however.
