### ISSUE TITLE
You should provide a command-line downloader

### ISSUE THREAD

**Issue by vporton** [hyperium/hyper#3680]
**Is your feature request related to a problem? Please describe.**
I am trying to understand why a certain HTTPS-only software does not work with my certificate authority for localhost settings.

**Describe the solution you'd like**
I want you to distribute with hyper a simplest HTTP and HTTPS downloader/streamer. It should be installable by `cargo install hyper`. So, I could test hyper without writing software for it first. I tried ChatGPT to write for me, but it produces erroneous code.

This will also serve as an example code. (`examples/client` does not support the most tricky part - HTTPS).

**Describe alternatives you've considered**
Forking the above mentioned HTTPS-only software and debugging it. It is not easy, because some components for it are missing in my OS. Or writing a hyper-based downloader by myself, also not easy.

**Comment by seanmonstar** [comment]
hyper purposefully does not pick what library to use for TLS, which is needed for HTTPS. This is because there are many options, and trade-offs for each. hyper wants you to be able to pick.

However, the `reqwest` crate does pick one by default, which you may find more useful.

**Comment by vporton** [comment]
> However, the `reqwest` crate does pick one by default, which you may find more useful.

As it is clear from my original post, I am dealing with third-party software, in which I cannot replace `hyper` by `reqwest`.
