### ISSUE TITLE
Very slow body read times on hyper 1+

### ISSUE THREAD

**Issue by jhewt** [hyperium/hyper#3692]
**Version**
```
hyper = "1.3.1"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
http-body-util = "0.1.2"
hyper-util = { version = "0.1.5", features = ["full"] }
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
bytes = "1.6.0"
```

**Platform**
```
Darwin MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64
```

**Description**

While upgrading from 0.14, I've noticed the body parsing time increased significantly and sometimes, it went from 100μs all the way up to 100ms with bigger responses. It became very apparent when I tried to implement a fuzzer using Hyper, and for some reason is *way slower* than the most unmantained fuzzer tool written in JS

`res.collect().await?.aggregate();` seems to take longer than expected, same output running as release is just as slow (just 1-2ms difference, still up to 30ms using the example code below).

I tried this code, adapted from the examples to read the fake comments json (157.75 kB uncompressed):

```rust
#![deny(warnings)]
#![warn(rust_2018_idioms)]

use std::time::Instant;
use bytes::Bytes;
use http_body_util::{BodyExt, Empty};
use hyper::{body::Buf, Request};
use hyper_util::rt::TokioIo;
use serde::Deserialize;
use tokio::net::TcpStream;

type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

#[tokio::main]
async fn main() -> Result<()> {
    let url = "http://jsonplaceholder.typicode.com/comments".parse().unwrap();
    let comments = fetch_json(url).await?;

    println!("Got {} comments", comments.iter().len());
    Ok(())
}

async fn fetch_json(url: hyper::Uri) -> Result<Vec<Comment>> {
    let host = url.host().expect("uri has no host");
    let port = url.port_u16().unwrap_or(80);
    let addr = format!("{}:{}", host, port);

    let stream = TcpStream::connect(addr).await?;
    let io = TokioIo::new(stream);

    let (mut sender, conn) = hyper::client::conn::http1::handshake(io).await?;
    tokio::task::spawn(async move {
        if let Err(err) = conn.await {
            println!("Connection failed: {:?}", err);
        }
    });

    let authority = url.authority().unwrap().clone();

    let req = Request::builder()
        .uri(url)
        .header(hyper::header::HOST, authority.as_str())
        .body(Empty::<Bytes>::new())?;

    let res = sender.send_request(req).await?;

    let read_body_time = Instant::now();
    let body = res.collect().await?.aggregate();
    
    println!("Read body time: {:?}", read_body_time.elapsed());

    let comments = serde_json::from_reader(body.reader())?;

    Ok(comments)
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "camelCase")]
struct Comment {
    #[allow(unused)]
    id: i32,
    #[allow(unused)]
    post_id: i32,
    #[allow(unused)]
    name: String,
    #[allow(unused)]
    email: String,
    #[allow(unused)]
    body: String
}
```

Results on a M2 Max 32GB:

```
cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/hyper-tests`
Read body time: 30.642833ms
Got 500 comments

cargo run --release
    Finished `release` profile [optimized] target(s) in 0.02s
     Running `target/release/hyper-tests`
Read body time: 32.694959ms
Got 500 comments
```

I expected to see way lower read times, but got insanely high read times compared to 0.14 and gets worse with bigger responses. About 30ms on average seems to be very high for just 157 kB of data, both dev and release gets those times in average, while in release mode just a couple of ms lower, but still high.

**Comment by jhewt** [comment]
Actually, I tried the very same with 0.14 and still gets 30ms for reading the body on both, release and dev. So, this time requesting `http://www.google.com` (with User-Agent header, otherwise Google returns polyfills) the average response size is 19 KB instead of 157 KB but still it's 30-ish ms.
Deps: 
```toml
hyper = { version = "0.14.29", features = ["client", "http1", "tcp"] }
tokio = { version = "1.38.0", features = ["full"] }
```
Code: 

```rust
use std::time::Instant;
use hyper::{Body, Client, Method, Request, Uri};

type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

#[tokio::main]
async fn main() -> Result<()> {
    let url = "http://www.google.com".parse().unwrap();
    let response = fetch(url).await?;

    println!("Response length: {:?}", response.len());
    
    Ok(())
}

async fn fetch(uri: Uri) -> Result<String> {
    let client = Client::new();

    let req = Request::builder()
        .method(Method::GET)
        .header("User-Agent", "hyper-tests")
        .header("Accept", "*/*")
        .uri(&uri)
        .body(Body::empty())?;
    
    let resp = client.request(req).await?;
    
    println!("Got response from {:?}: {:?}", uri, resp.status());
    
    let read_body_time = Instant::now();
    let body = hyper::body::to_bytes(resp).await?;
    println!("Read body time: {:?}", read_body_time.elapsed()); 
    
    Ok(String::from_utf8_lossy(&body).to_string())
}
```

Results for example to www.google.com (19kB-ish):

```bash
cargo run --release
   Compiling signal-hook-registry v1.4.2
   Compiling tokio v1.38.0
   Compiling hyper v0.14.29
   Compiling hyper-tests-14 v0.1.0 (/Users/josesachs/Animus/Rust/hyper-tests-14)
    Finished `release` profile [optimized] target(s) in 5.97s
     Running `target/release/hyper-tests-14`
Got response from http://www.google.com/: 200
Read body time: 33.167875ms
Response length: 19879
```

Results for the comments json (157 kB):
```bash
cargo run --release
   Compiling hyper-tests-14 v0.1.0 (/Users/josesachs/Animus/Rust/hyper-tests-14)
    Finished `release` profile [optimized] target(s) in 3.04s
     Running `target/release/hyper-tests-14`
Got response from http://jsonplaceholder.typicode.com/comments: 200
Read body time: 31.33975ms
Response length: 157745
```

I'm always getting 30ms, any ideas as to why? It happens too in 1.x

**Comment by seanmonstar** [comment]
I just tried it myself on `http://www.google.com`, which only ever gives me some small HTML about a redirect, and takes ~400 microseconds. On `http://jsonplaceholder.typicode.com/comments`, a couple runs shows it taking ~16ms.

On a somewhat separate note, however:

```rust
let body = res.collect().await?.aggregate();
let comments = serde_json::from_reader(body.reader())?;
```

If you're going to pass it to serde-json, you will likely find the performance is better with `.to_bytes()`. serde-json parses significantly faster with a single slice, as opposed to with the generic `Read` interface.

**Comment by jhewt** [comment]
> I just tried it myself on `http://www.google.com`, which only ever gives me some small HTML about a redirect, and takes ~400 microseconds. On `http://jsonplaceholder.typicode.com/comments`, a couple runs shows it taking ~16ms.

I give a bad example with Google, seems they vary the response widely depending on the location, in my location I'm able to get a http version without a redirection to the https version.

Could it be a bit slower on arm? I think I was too ambitious with the parsing time as Chrome seems to take about the same but a bit less.

> On a somewhat separate note, however:
> 
> ```rust
> let body = res.collect().await?.aggregate();
> let comments = serde_json::from_reader(body.reader())?;
> ```
> 
> If you're going to pass it to serde-json, you will likely find the performance is better with `.to_bytes()`. serde-json parses significantly faster with a single slice, as opposed to with the generic `Read` interface.

Yep, thank you! In this case I was just adapting what's on the example page to give a quick code to test. In my use case I'm just parsing as string as it's a RESTful client app (kinda like Insomina, Postman, etc)
