### ISSUE TITLE
I hope the code can be modified as follows

### ISSUE THREAD

**Issue by lo-ferris** [hyperium/hyper#3697]
https://github.com/hyperium/hyper/blob/master/src/body/incoming.rs

// This is the source code
<img width="418" alt="WeChatae98761c2031281a9fa89685cd9deec8" src="https://github.com/hyperium/hyper/assets/118798799/e2a9b95c-1b76-4764-8d31-0a66ede4a796">

// Change to
<img width="278" alt="WeChat3021ad1d0b2f38bd1ad30ba25c75a755" src="https://github.com/hyperium/hyper/assets/118798799/ca17a331-c96e-43ed-b4ba-ac68e800d73f">

**Comment by seanmonstar** [comment]
This type purposefully does not expose a public constructor.

The recommendation if you feel you need to construct one is to change your function to accept a generic body, and then you can pass some other type with a public constructor.

**Comment by lo-ferris** [comment]
Great, thank you.
