### ISSUE TITLE
The script that generates the header file is not available

### ISSUE THREAD

**Issue by spongehah** [hyperium/hyper#3708]
When I delete the header file under `capi/include`, run the command: 
```SH
(base) spongehah@MacBook capi % ./gen_header.sh
cp: /Users/spongehah/Document/src/hyper/capi/include/hyper.h: No such file or directory
rm: /Users/spongehah/Document/src/hyper/capi/include/hyper.h.backup: No such file or directory
```

**Comment by seanmonstar** [comment]
Why are you deleting the file first?

---

As I look through the script again, I see it creates a backup to be able to `diff` them, if you passed `--verify` (which is what we used in CI). I suppose the script could be modified to only create a backup if `--verify` was passed.

**Comment by spongehah** [comment]
> Why are you deleting the file first?
> 
> As I look through the script again, I see it creates a backup to be able to `diff` them, if you passed `--verify` (which is what we used in CI). I suppose the script could be modified to only create a backup if `--verify` was passed.

I just want to verify that the script works
