### ISSUE TITLE
No `Connection: close` on HTTP1 Connection Drain

### ISSUE THREAD

**Issue by Clendenin** [hyperium/hyper#3720]
When HTTP1 connection draining is activated, the Connection: close header is not attached to responses sent to active connections. This prevents active clients from realizing that the server is requesting that the connection be closed and prevents graceful draining of HTTP1 connections.

**Comment by seanmonstar** [comment]
Thanks for the report! I could have sworn we did this, but then tweaked the test and you're right, not done. PR is up at #3725.

**Comment by Clendenin** [comment]
Thank you @seanmonstar!

**Comment by Catwoman08** [comment]
Reopened this until the PR #3725 gets merged.
