### ISSUE TITLE
hang when client receives header response that's too big in http2

### ISSUE THREAD

**Issue by ajwerner** [hyperium/hyper#3724]
**Version**
Hyper @ 7de02373f5e4ce392587a4d9d7710c6faf9c6165

**Platform**
`Linux 6.5.0-42-generic`

**Description**
When the server sends a response with headers that are too big, hyper can sometimes just hang. 

I wrote this test:

https://github.com/hyperium/hyper/blob/bdd112e9ea7df40bed65922faac68d77543e1763/tests/integration.rs#L64-L86

I expected to see an error. Instead the test just blocks forever.

See https://github.com/hyperium/tonic/issues/1834 and https://discord.com/channels/500028886025895936/1268954374634471484 for context.

**Comment by futile** [comment]
Mhhm, could it be possible to increase the header size limit on-demand (up to a fixed maximum)? Just thinking about a version that will allow clients/servers to work with large headers, instead of throwing an error.
