### ISSUE TITLE
Poor performance in http/1.1 with many socket connections

### ISSUE THREAD

**Issue by alshdavid** [hyperium/hyper#3728]
**Version**
Using http 1.1
```toml
tokio = { version = "*", features = ["full"] }
hyper = { version = "*", features = ["full"] }
http-body-util = "*"
hyper-util = { version = "*", features = ["full"] }
```

## Platform
Main benchmarks are on:
|~|~|
|-|-|
|CPU|AMD 7950x (16 cores @ 5ghz)|
|RAM|100gb 6400|
|OS|Fedora Server 40|

I have unlimited file descriptors and have tried compiling the web server as a release build with and without LTO with no difference. I have also tried Ubuntu on another computer and Amazon Linux on an AWS EC2 with the same effect.

## Description

I've been investigating the viability of using Rust as a language for http-server projects due to its great ergonomics (at least I think so 😆), incredible speed and deterministic performance.

Typically I would evaluate the performance of a server technology using a real production workload so I don't usually hold too much weight in synthetic http benchmarks that test a simple echo response - but in this case I have noticed anomalous behaviour in Rust http servers that has put a stop to adopting it in the first place. 

I wanted to reach out for insight on what is happening and if there is anything I can do to improve it.

## The Test

I have a simple http 1.1 server that returns "hello world" on a `GET` request written using Rust + Hyper ([source](https://github.com/alshdavid/rust-http-benchmarks/blob/main/rust_hyper/src/main.rs)) and tested using [Vegeta](https://github.com/tsenart/vegeta) and [Oha](https://github.com/hatoo/oha)

After I got a weird result, I sanity checked by implementing the server in these technologies:
- Rust (Actix)
- Rust (Tokio bare)
- Rust (Std + thread bare)
- Rust (May http bare)
- Go (std)
- Nodejs (std)

## Benchmark 1: Test 10 clients making 50k requests

This is the typical test you see on most online benchmarks. A few client connections that reuse a single socket to make a lot of requests on.

Rust + Hyper perform fantastic in this scenario.

### Results

<details>
  <summary>Rust+Hyper Results</summary>
  <img src="https://github.com/user-attachments/assets/eb82e58a-7eae-4de2-99f3-f225bb37c6d0" />
</details>

<details>
  <summary>Go Results</summary>
  <img src="https://github.com/user-attachments/assets/bd2b1c97-3038-45a0-b8da-d704715f600e" />
</details>

<details>
  <summary>Nodejs Results</summary>
  <img src="https://github.com/user-attachments/assets/75e89946-6d4d-4ccf-bf2b-33381eb9d300" />
</details>

**[Full results page](https://alshdavid.github.io/rust-http-benchmarks/_reports/saved/r-1000_c-50000_keepalive-true.html)**

## Benchmark 2: Test 50k clients making 1 request

This test aims to be a little more representative of a large scale production use case where many clients send few requests to an http server. 

To simulate this I use the `--disable-keep-alive` flag on oha/vegeta, forcing each client to create a new TCP socket for each request. 

This is where things get weird, under these conditions; Rust + hyper has a success rate of 25%, poor latency for the requests that do succeed and actually performs worse than Nodejs.

Both Go and Nodejs are able to reliably respond to requests with a 100% success rate and reasonable response latency.

### Results

<details>
  <summary>Rust+Hyper Results</summary>
  <img src="https://github.com/user-attachments/assets/5d67b870-ac68-455e-bcf5-2c9cea4c35c7" />
</details>

<details>
  <summary>Go Results</summary>
  <img src="https://github.com/user-attachments/assets/cef90827-7bd6-4383-9ba2-f00ececd0d55" />
</details>

<details>
  <summary>Nodejs Results</summary>
  <img src="https://github.com/user-attachments/assets/6298ca61-c75a-43b7-a55b-929c406310ab" />
</details>

**[Full results page - requests 500 clients 10,000](https://alshdavid.github.io/rust-http-benchmarks/_reports/saved/r-1000_c-50000_keepalive-false.html)**
**[Full results page - requests 500 clients 10,000](https://alshdavid.github.io/rust-http-benchmarks/_reports/saved/r-500_c-10000_keepalive-false.html)**

Another strange behaviour is Rust servers displaying a "surging" then pausing - where the server appears to stall as it presumably catches up to buffered requests (I don't know what is actually happening here), video:

https://github.com/user-attachments/assets/2945d789-7392-48ed-805b-0936cc5e2674

## Sources

- [Rust+Hyper](https://github.com/alshdavid/rust-http-benchmarks/blob/main/rust_hyper/src/main.rs)
- [Go](https://github.com/alshdavid/rust-http-benchmarks/tree/main/go_std)
- [Nodejs](https://github.com/alshdavid/rust-http-benchmarks/blob/main/nodejs_std/index.js)

## Thoughts & Questions

What is strange about this result is that this behaviour appears to be present on all Rust implementations. Is this due to how the Rust standard library wraps the OS TCP APIs?

Am I doing something wrong in the way I am compiling my Rust http server?

Is there something wrong with my computer setup?

**Comment by seanmonstar** [comment]
I'm not _sure_ what may be causing what you're seeing. One easy thing to try is to make use of a better memory allocator. By default, Rust will use the system allocator, but it's usually pretty bad. Most production software will make use of a better one, such as [jemalloc](https://crates.io/crates/jemallocator) or [mimalloc](https://crates.io/crates/mimalloc).

Regarding the performance in general, I just wanted to provide some more context: Rust on servers, and in particular hyper, is _extremely_ fast and robust. hyper topped the TechEmpower benchmarks a [few years ago](https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=plaintext) (and then we stopped playing the benchmark optimization game). hyper is trusted to power billions of requests a second, at Amazon, Discord, Microsoft, Cloudflare, OneSignal, Fly.io, Deno, Neon, Surreal, and many many others.

**Comment by alshdavid** [comment]
Thanks! I just retried the benchmarks with jemalloc and mimalloc with the same result.

It appears that the techempower benchmarks also use the `keep-alive` option which tests the "a few users making a lot of requests/reusing a single socket" case. Their results were reproduced in my above benchmarks, where Hyper was faster than other tested technologies.

What I noticed is that all Rust servers, regardless of framework, have issues when they get a high number of socket connections doing few requests (i.e. "lots of users making few requests").

Perhaps this is related to the underlying `TCPListener` implementation in Rust's stdlib and might be a question for them?

Sadly, being unable to prove the "many users making few requests" case is better than other technologies (or even the same) is a hard blocker for adoption to my company and I'd really like to understand why the results are so catastrophic there (Rust with a 75% failure rate vs Nodejs & Go with a 0% failure rate on the same test).

**Comment by seanmonstar** [comment]
You could try taking a look at the errors you're getting, and even digging deeper with something like `strace`. One more thing that comes to mind is the backlog. That is how many sockets the kernel can keep in the accept queue before refusing new connections.

I see that Golang reads the system max, which as of Linux 5.4, now defaults to 4096. Nodejs chooses to set 512. Whereas I see that Rust picks a conservative 128. You could construct a `TcpListener` manually setting all the options using the `socket2` crate (don't forget to call `set_nonblocking(true)` before converting into a Tokio listener).

**Comment by alshdavid** [comment]
Thanks! The error I am getting is "connection refused" so that makes sense. I'll give that a shot

**Comment by milen-denev** [comment]
> You could try taking a look at the errors you're getting, and even digging deeper with something like `strace`. One more thing that comes to mind is the backlog. That is how many sockets the kernel can keep in the accept queue before refusing new connections.
> 
> I see that Golang reads the system max, which as of Linux 5.4, now defaults to 4096. Nodejs chooses to set 512. Whereas I see that Rust picks a conservative 128. You could construct a `TcpListener` manually setting all the options using the `socket2` crate (don't forget to call `set_nonblocking(true)` before converting into a Tokio listener).

Hey, could you please elaborate a little more on the matter? I have the same issue, by "K6ing" the axum server it crumbles, here is what I have done:
```rust
pub fn get_tcp_listener(port: u16) -> TcpListener {
    let addr = if cfg!(debug_assertions) {
        SocketAddr::from(([127, 0, 0, 1], port))
    } else {
        SocketAddr::from(([0, 0, 0, 0], port))
    };

    let socket = Socket::new(Domain::IPV4, Type::STREAM, None).unwrap();
    _ = socket.set_nonblocking(true);
    _ = socket.set_nodelay(true);
    _ = socket.bind(&SockAddr::from(addr));
    _ = socket.listen(i32::MAX);
    
    let listener: TcpListener = socket.into(); //std  TcpListener because axum_server::from_tcp doesn't support the Tokio TcpListener

    listener
}

let listener_tls = get_tcp_listener(443);
let s2 = axum_server::from_tcp(listener_tls)
        .handle(handle) // graceful shutdown 
        .acceptor(acceptor) // rustls acceptor
        .serve(app.into_make_service_with_connect_info::<SocketAddr>());
```

I am getting the following error logs: 

```
Caused by: client error (Connect)
Caused by: tcp open error: Too many open files (os error 24)
Caused by: Too many open files (os error 24)
```

the ulimit -u is 500,000. 

Am I doing something wrong? Is it related to Hyper or any configuration of it?

**Comment by milen-denev** [comment]
> That looks like a different error, not related to this one. You're noticing _on the client_ that the OS has not allowed it to open any more files. You'll want to check the file limit set on that process.
> 
> Since there's no more follow-up on the original issue, I'm going to close this.

I do confirm that is it an issue with the file limit, it seems it was using more than 500,000. The new limit is u64::MAX set-up programmatically. Thank you very much.
