### ISSUE TITLE
Hyper doesn't automatically send the User-Agent header

### ISSUE THREAD

**Issue by reem** [hyperium/hyper#373]
A variety of APIs, including github's, mark this header as mandatory. We should set a default value of `hyper` if someone tries to send a request without a `User-Agent` header.

**Comment by pyfisch** [comment]
+1

**Comment by reem** [comment]
We can place it in requests created by Clients then users can just remove or replace that header.

**Comment by seanmonstar** [comment]
It could be an Option<String> on the Client struct. Default is Some("hyper"), and a set_user_agent method could be used to change it.

**Comment by reem** [comment]
If we are going to continue to add options to Client and RequestBuilder, I think we should move to a modifiers-based API. Modifiers have worked out astoundingly well in Iron, and I think they could be useful here too.

**Comment by seanmonstar** [comment]
Looking through Clients in other languages (nodejs, Python, Go, libcurl), a default user agent is not sent. To send one, the user must be explicit about it.

**Comment by Byron** [comment]
To my mind, if hyper is supposed to be low-level, it shouldn't try to be particularly smart and try to 'help' the user with default values. Those usually cause confusion if they are not totally obvious. If someone writes a client or uses a default one to communicate to a particular server, he or she will notice soon enough that the server isn't happy without a user agent field.

From my own experience, and I am a total beginner when it comes to anything related to the web, it's quite hard to miss something like the user-agent. In my case, it was set in the reference implementation I looked at, and I had no doubt I want to set it as well.
