### ISSUE TITLE
Documentation: Lack of a Quick Start/Basic Usage section

### ISSUE THREAD

**Issue by akneni** [hyperium/hyper#3732]
I've been learning about some lower level networking fundamentals recently and decided to learn hyper as a part of that. However, I've run into some problems with the lack of documentation. 

For example, the page on `docs.rs` [here](https://docs.rs/hyper/latest/hyper/client/index.html), links to [this page](https://github.com/hyperium/hyper/blob/master/examples/client.rs) on GitHub to show an example usage of the client. However, I don't think this is as clear as it could be. For example, it doesn't make it clear that the `TokioIo` object is from a separate `hyper_utils` crate. 

Additionally, I think a "quick start" page would be useful to help newcomers get up to speed on the basics. I think [Axum](https://docs.rs/axum/latest/axum/) does a good job with this. 

Hyper's own website has great documentation on the other hand. I just think the `docs.rs` page would benefit from either some polishing or explicitly linking to Hyper's website (since `docs.rs` is the first place most developers will go for documentation on a rust library).

**Comment by seanmonstar** [comment]
I wasn't sure if by closing you already found it, but there is https://hyper.rs/guides/1/

I'm always interested in making them better (https://github.com/hyperium/hyper/issues/3411), and also in making sure that it's easy to find them from where people would expect to find them.

**Comment by akneni** [comment]
Yeah, I found the `hyper.rs` site. It pretty much solves what I had initially submitted the issue for, but I also agree with (#3411) in that it could have some more extensive docs. After I get a chance to dive deeper into hyper, I also plan on contributing to the guides.
