### ISSUE TITLE
Hyper-util is incompatible with tower 0.5

### ISSUE THREAD

**Issue by kanpov** [hyperium/hyper#3757]
**Version**
List the version(s) of `hyper`, and any relevant hyper dependency (such as `h2` if this is related to HTTP/2).
Hyper 1.4.1
Hyper-util 0.1.8

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
Linux localhost.localdomain 6.10.11-1-default #1 SMP PREEMPT_DYNAMIC Thu Sep 19 07:33:24 UTC 2024 (bd33620) x86_64 x86_64 x86_64 GNU/Linux

**Description**
`tower-http` and `axum` have all migrated to `tower` 0.5.x on their stable releases, yet `hyper-util` which is a semi-mandatory dependency of `axum` is stuck on `tower` 0.4.x, resulting in two versions of `tower` needing to be pulled in for every `axum` project.

**Comment by Catwoman08** [comment]
Thank you for reporting this. That should be easy to do @seanmonstar already has a PR up that will address this.
