### ISSUE TITLE
Incorrect HTTP header location

### ISSUE THREAD

**Issue by simonmicro** [hyperium/hyper#3762]
**Version**
```
hyper = { version = "1.4.1", features = ["client", "http1"] }
tokio = { version = "1.40.0", features = ["full"] }
```
(only the most important dependencies)

**Platform**
Linux --- 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Description**
The HTTP client header is not correctly being built in accordance to [RFC 9110](https://httpwg.org/specs/rfc9110.html#GET): The location also contains the URI protocol and authority.

I tried this code:

```rust
use http_body_util::Empty;
use hyper::body::Bytes;
use hyper::Request;
use hyper_util::rt::TokioIo;
use tokio::net::TcpStream;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let url = "http://localhost:8000".parse::<hyper::Uri>()?;
    let host = url.host().expect("uri has no host");
    let port = url.port_u16().unwrap_or(80);
    let address = format!("{}:{}", host, port);
    let stream = TcpStream::connect(address).await?;
    let io = TokioIo::new(stream);
    let (mut sender, conn) = hyper::client::conn::http1::handshake(io).await?;
    tokio::task::spawn(async move {
        if let Err(err) = conn.await {
            println!("Connection failed: {:?}", err);
        }
    });
    let authority = url.authority().unwrap().clone();
    let req = Request::builder()
        .uri(url)
        .header(hyper::header::HOST, authority.as_str())
        .body(Empty::<Bytes>::new())?;
    let res = sender.send_request(req).await?;
    println!("Response status: {}", res.status());
    Ok(())
}

```

...for demonstration, I just copy-pasted the official [getting started](https://hyper.rs/guides/1/client/basic/) client example and filled in the values. For testing, just start a local Python HTTP server:

```bash
python3 -m http.server
```

I expected to see this happen:

The Python server should serve a directory listing with code 200.

Instead, this happened:

It instead replies with...

```
127.0.0.1 - - [***] "GET http://localhost:8000/index.html HTTP/1.1" 404 -
```

...but why? Turns out, the sent HTTP packets header does not look like the specified one:

```
GET http://localhost:8000/index.html HTTP/1.1\r\n
host: localhost:8000\r\n
\r\n
```

...but as RFC 9110 (translated to match this case) it should look like:

```
GET /index.html HTTP/1.1\r\n
Host: localhost:8000\r\n
\r\n
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) this behavior is to be expected, only if communicating with a proxy. Maybe I overlook something, but I see no way of changing this behavior in the API to differentiate between proxy or non-proxy communication.

**Comment by seanmonstar** [comment]
This is on purpose: https://docs.rs/hyper/latest/hyper/client/conn/http1/struct.SendRequest.html#method.send_request

The example you linked used to use a higher-level client that needed the full URL to also create the connection, but now with 1.0, it's a little different. It could be adjusted to only pass the path portion into the request.

**Comment by simonmicro** [comment]
@seanmonstar Oh, damn - I have not read that notice:

> This is however not enforced or validated and it is up to the user of this method to ensure the Uri is correct for their intended purpose.

Thank you very much for clarification - I'll fix it on my side, if I'm able to parse such `Uri`. Thank you!
