### ISSUE TITLE
Consider the extensibility of Client and RequestBuilder

### ISSUE THREAD

**Issue by reem** [hyperium/hyper#378]
See some early discussion in #346 

The two main approaches I can think of here are similar to the ones used to make types fully extendable in iron - namely embedding a `TypeMap` in these structs to allow storing arbitrary metadata and using modifiers to manipulate them. 

`TypeMap` allows adding new fields and modifier enables adding new builder-style methods. Plugins can be used to add new getters by building on `TypeMap`, but I think they might be a bit heavy for hyper.

That this features so prominently in the design of iron makes me think that this might be a bit much for hyper to do vs. a higher-level client abstraction; it's possible this kind of stuff just doesn't belong.

**Comment by pyfisch** [comment]
Isn't this belong to #373? I looked at modifiers and I like the idea to use them for the client. 

> That this features so prominently in the design of iron makes me think that this might be a bit much for hyper to do vs. a higher-level client abstraction; it's possible this kind of stuff just doesn't belong.

What is the goal of hyper? I know hyper is currently more low level, but I think people will need an HTTP client like Pythons [requests](http://docs.python-requests.org/en/latest/) lib. Since we already provide a client we should be able to make this client powerful.

**Comment by seanmonstar** [comment]
I don't think an `extensions` or whatever map needs to be on `Client`. Any extensions desired can be handled by a higher level Client, as https://github.com/hyperium/hyper/issues/346#issuecomment-82574384 states.

Modifiers may make creating a new Client more ergonomic, as opposed to one-off methods like `set_redirect_policy`, but without an extensions map to edit, they lose much of their worth.

@pyfisch The goal is to provide a fast, correct, and safe implementation of HTTP. I'm less interested in including specializations that only some people need (when I look at npm's request package and see `hawk` and `aws` options, I shudder). It should be ergonomic to use, such that if someone thinks "Hey, I need to make some HTTP requests", they can use hyper without wanting to faceroll their keyboard.

**Comment by seanmonstar** [comment]
RequestBuilder is no more (on master).
