### ISSUE TITLE
Provide an HttpClient trait

### ISSUE THREAD

**Issue by WhyNotHugo** [hyperium/hyper#3784]
**Is your feature request related to a problem? Please describe.**

I've implemented a library to interact with [WebDav (rfc3744)](https://www.rfc-editor.org/rfc/rfc3744) servers.

This library provides a `WebDavClient`, which would ideally have a generic `HttpClient` parameter: a the client that us used for the underlying http requests. This would allow consumers to supply their `HttpClient` of choice which can implement any necessary middleware, authentication, etc.

Pretty much any library that uses HTTP as a transport would benefit from this design: allow consumers to provide their own `HttpClient` type which handles any custom transport requirements, authentication, logging, etc.

**Describe the solution you'd like**

An `HttpClient` trait, which is essentially of `hyper::service::Service<Response=hyper::Response>`.

By providing this trait upstream, different client implementation can `impl` this trait. `hyper_util::client::legacy::Client` and some future/non-legacy/third-party client can implement this trait.

**Describe alternatives you've considered**

My `WebDavClient` type currently uses the `hyper_util::client::legacy::Client` type directly. This doesn't let a consumer provide a different type (for example, one that adds a custom header to all requests).

I could define this `HttpClient` trait downstream, but due to the orphan rule, consumers need to create a newtype wrapper around existing clients. This could work as a short-term workaround, but is not an ideal direction for the ecosystem.

**Additional context**

Perhaps this isn't the *perfect* approach, but I'd at least like to start a discussion on the topic. I'm happy to hear of other alternative approaches.

**Comment by seanmonstar** [comment]
So far, I've recommended that people be generic over `tower::Service`. That's what I would continue to recommend, for now.

**Comment by WhyNotHugo** [comment]
Would you take a patch that implements `tower::Service<Response=hyper::Response>` for `hyper_util::client::legacy::Client`?

Tentatively, a library which takes `tower::Service<Response=hyper::Response>` as input could be used with the legacy client now, and with a future non-legacy client when we have one.

**Comment by WhyNotHugo** [comment]
Right, I somehow missed that when checking the docs.

I'm trying to use this implementation, the compiler thinks that `Client` doesn't implement `Service<Request>`:

```
error[E0277]: the trait bound `hyper_util::client::legacy::Client<HttpsConnector<HttpConnector>, _>: hyper::service::service::Service<http::Request<String>>` is not satisfied
   --> examples/find_calendars.rs:54:52
    |
54  |     let webdav = WebDavClient::new(base_url, auth, https_client);
    |                  -----------------                 ^^^^^^^^^^^^ the trait `hyper::service::service::Service<http::Request<String>>` is not implemented for `hyper_util::client::legacy::Client<HttpsConnector<HttpConnector>, _>`
    |                  |
    |                  required by a bound introduced by this call
    |
    = help: the following other types implement trait `hyper::service::service::Service<Request>`:
              `&S` implements `hyper::service::service::Service<Request>`
              `&mut S` implements `hyper::service::service::Service<Request>`
              `Arc<S>` implements `hyper::service::service::Service<Request>`
              `Box<S>` implements `hyper::service::service::Service<Request>`
              `Rc<S>` implements `hyper::service::service::Service<Request>`
              `hyper::service::util::ServiceFn<F, ReqBody>` implements `hyper::service::service::Service<http::Request<ReqBody>>`
note: required by a bound in `WebDavClient::<C>::new`
   --> /home/hugo/src/git.sr.ht/~whynothugo/libdav/src/dav.rs:136:8
    |
136 |     C: Service<http::Request<String>, Response = Response<Incoming>>
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `WebDavClient::<C>::new`
...
147 |     pub fn new(base_url: Uri, auth: Auth, http_client: C) -> WebDavClient<C> {
    |            --- required by a bound in this associated function
```

Am I missing something obvious here?

**Comment by seanmonstar** [comment]
Perhaps that `tower::Service` and `hyper::service::Service` are two separate traits. The hyper one is only meant for the server, and had to be separate since hyper 1.0 couldn't depend on tower publicly (not yet 1.0).

**Comment by WhyNotHugo** [comment]
Thanks for the clarification. I guess that downstream consumers will have depend on the unstable `tower::Service` until upstream stabilised it.

I do have one final question with regards to `tower_service::Service::call`. Given the this takes a `&mut self`, does this mean that the client can only handle a single concurrent request?

**Comment by seanmonstar** [comment]
> Given the this takes a &mut self, does this mean that the client can only handle a single concurrent request?

No, because the lifetime of the returned future does not capture `&mut self`.

It was originally made `&mut` because we thought people may want to update their service as it processes requests. But I believe we settled on that not really being necessary, or if it is, most applications include some synchronization _anyways_, so requiring `&mut self` tends to just be worse. It will likely change to `&self` before Tower is stabilized.
