### ISSUE TITLE
cargo-c integration and dynamic linking

### ISSUE THREAD

**Issue by kpcyrd** [hyperium/hyper#3786]
**Is your feature request related to a problem? Please describe.**
I'm trying to get the FFI interface of hyper up to speed with rustls-ffi, for integration in an operating system.

Compare the current [curl hyper documentation](https://github.com/curl/curl/blob/cb2ae6e8a8614a34bbe7f77f0540cd27aa890b59/docs/internals/HYPER.md) (which wants you to manually build and link cdylib objects) to the current [curl rustls documentation](https://github.com/curl/curl/blob/cb2ae6e8a8614a34bbe7f77f0540cd27aa890b59/docs/RUSTLS.md) (~~that generates and installs a .so file, headers and and pkg-config integration for you~~ @cpu has pointed out this document is not using cargo-c, the rustls-ffi pull request linked below is a better resource to look into).

Most of the work to get rustls to this point was done in this pull request: https://github.com/rustls/rustls-ffi/pull/274

**Describe the solution you'd like**
I'd like hyper to integrate with the pkg-config ecosystem that Linux distributions build upon, preferably through cargo-c.

**Describe alternatives you've considered**
The curl hyper integration is currently [planned for removal](https://github.com/curl/curl/blob/7b12c36ca972d9e9a14088cdd88232385e619d44/docs/DEPRECATE.md#Hyper) in January 2025.

**Additional context**
There may be some additional context in https://github.com/rustls/rustls-ffi/issues/345.

There was development work done on cargo-c itself specifically for rustls-ffi that you may want to consider, in case you have concerns about dynamic linking and ABI stability: https://github.com/lu-zero/cargo-c/issues/345

**Comment by cpu** [comment]
For what it's worth I've been happy with cargo-c and the upstream maintainers have been very helpful. In rustls-ffi I'm moving towards replacing the old `Makefile` approach (as linked to from the current curl docs) and instead recommending cargo-c as the blessed path for building the library (static or dynamic).

**Comment by seanmonstar** [comment]
I've installed `cargo-c` locally and tried it out, seems like the only thing that is missing is adding a `capi` feature, and perhaps some options to use the pre-existing header file, and... that's it?

**Comment by seanmonstar** [comment]
Started #3787.
