### ISSUE TITLE
`H2Upgraded::poll_write` returns `Ok(0)` while `tokio-rustls` assumes `Ok(0)` is 'successful'

### ISSUE THREAD

**Issue by hatoo** [hyperium/hyper#3801]
**Version**
List the version(s) of `hyper`, and any relevant hyper dependency (such as `h2` if this is related to HTTP/2).
hyper: commit 12717d16594debd8f2b1e3e169cc9b4700ee25b3

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)

WSL2 Ubuntu on Windows 11
```
❯ uname -a
Linux WindowsNVMe 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Description**

When we wrap `tokio-rustls` around HTTP2 Upgraded stream, `tokio-rustls` will infinite loop because Upgraded stream returns `Ok(0)` on `poll_write` when shutdown. relevant issue https://github.com/rustls/tokio-rustls/issues/92

https://github.com/hyperium/hyper/blob/12717d16594debd8f2b1e3e169cc9b4700ee25b3/src/proto/h2/mod.rs#L329-L337

I've found that when I replace `None => Some(0), ` to `None => None`, it works fine.

Honestly, I don't know the issue should be resolved in either `hyper` or `tokio-rustls`. But this issue is important when I implement HTTP2 proxy.

**Comment by seanmonstar** [comment]
> tokio-rustls will infinite loop because Upgraded stream returns Ok(0) on poll_write when shutdown.

What do you mean? As opposed to what?

**Comment by hatoo** [comment]
https://github.com/rustls/tokio-rustls/blob/66fb0ae98fbc9e71d5aa855d45e88ca8d53f95f3/src/common/mod.rs#L330-L334

`tokio-rustls` writes the remaining data on `poll_shutdown` and because `H2Upgraded::poll_write` always returns `Ok(0)` on the write (perhaps because the stream is already closed by the other side), `tokio-rustls` goes an infinite loop.

**Comment by seanmonstar** [comment]
Oh OK. That's a bug in tokio-rustls, then. Returning `Ok(0)` is the normal way for IO resources to indicate no more bytes are allowed (see https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.write).
