### ISSUE TITLE
Reducing even eliminating all `clippy` warning 

### ISSUE THREAD

**Issue by linyihai** [hyperium/hyper#3802]
**Is your feature request related to a problem? Please describe.**

Running `clippy` cmd, current workspace generate serval warnings 

`cargo clippy --workspace --all-targets --no-deps -- -D warnings`

output is

```
...

error: non-binding `let` on a future
   --> src/client/dispatch.rs:455:9
    |, 
455 |         let _ = tx.try_send(Custom(3)).unwrap();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider awaiting the future or dropping explicitly with `std::mem::drop`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_future

error: could not compile `hyper` (lib test) due to 49 previous errors
```

**Describe the solution you'd like**

- Some of the more obvious fixes and can be automatically adopted, can be repaired
- Something that requires a little bit of thinking about how to improve, like defining types for complex expressions, like `Poll<Option<crate::Result<(MessageHead<T::Incoming>, DecodedLength, Wants)>>>`, 
- Add `clippy` CI workflow

**Describe alternatives you've considered**

**Additional context**

**Comment by linyihai** [comment]
I would love to reduce clippy error prompts :)

**Comment by seanmonstar** [comment]
Some of the things clippy finds are worth fixing! But just enough things I disagree with that I therefore don't automatically run clippy, nor do I keep it in a CI job.

So, if you see some things that seem like obvious wins, those are welcome in a PR! I might comment on some of them that I disagree with what clippy recommends, just so you know ahead of time :)

**Comment by linyihai** [comment]
> Some of the things clippy finds are worth fixing! But just enough things I disagree with that I therefore don't automatically run clippy, nor do I keep it in a CI job.
> 
> So, if you see some things that seem like obvious wins, those are welcome in a PR! I might comment on some of them that I disagree with what clippy recommends, just so you know ahead of time :)

Thanks for you clarification.
