### ISSUE TITLE
Shoud bump rust-version in Cargo.toml due to faild build with rustc 1.63

### ISSUE THREAD

**Issue by linyihai** [hyperium/hyper#3804]
**Version**

hyper version is 1.5.0, use default feature.

**Platform**

Linux linlaptop 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Description**

Although rustc-version with 1.63 defined in Cargo.toml, the below build failed:

```
 cargo +1.63-x86_64-unknown-linux-gnu check
warning: unused manifest key: lints
error: package `tokio v1.41.1` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.63.0
```

Should we bump rust-version to rustc 1.70 ?

```
cargo +1.70-x86_64-unknown-linux-gnu check
warning: unused manifest key: lints
    Checking bytes v1.8.0
    Checking fnv v1.0.7
    Checking itoa v1.0.11
    Checking pin-project-lite v0.2.15
    Checking tokio v1.41.1
    Checking http v1.1.0
    Checking http-body v1.0.1
    Checking hyper v1.5.0 (/root/workspace/hyper)
    Finished dev [unoptimized + debuginfo] target(s) in 1.47s
```

**Comment by seanmonstar** [comment]
No, we don't need to. hyper itself doesn't need a newer compiler, and can work with older versions of Tokio that support Rust 1.63. That's why we pin Tokio in the MSRV CI job.
