### ISSUE TITLE
Can't build Hyper-Util, on Haiku

### ISSUE THREAD

**Issue by vmlemon** [hyperium/hyper#3817]
**Version**
List the version(s) of `hyper`, and any relevant hyper dependency (such as `h2` if this is related to HTTP/2).
```
hyper-util v0.1.10
   Compiling num-iter v0.1.45
   Compiling num-bigint v0.4.6
```

**Platform**
```
~/rustic> uname -a
Haiku shredder 1 hrev58440 Dec 20 2024 07:16:01 x86_64 x86_64 Haiku
```

**Description**
As part of trying to build the Rustic-RS project, on Haiku, I encountered the following error, involving the prerequisite "hyper-util" Cargo package:

```
~/rustic> ./build.sh 
   Compiling hyper-util v0.1.10
   Compiling num-iter v0.1.45
   Compiling num-bigint v0.4.6
error[E0599]: no method named `with_interval` found for struct `TcpKeepalive` in the current scope
   --> /boot/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-util-0.1.10/src/client/legacy/connect/http.rs:122:12
    |
122 |         ka.with_interval(interval)
    |            ^^^^^^^^^^^^^ method not found in `TcpKeepalive`

error[E0599]: no method named `with_retries` found for struct `TcpKeepalive` in the current scope
   --> /boot/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-util-0.1.10/src/client/legacy/connect/http.rs:144:12
    |
144 |         ka.with_retries(retries)
    |            ^^^^^^^^^^^^
    |
help: there is a method `with_time` with a similar name
    |
144 |         ka.with_time(retries)
    |            ~~~~~~~~~

For more information about this error, try `rustc --explain E0599`.
error: could not compile `hyper-util` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

```

Unfortunately, as I am unfamiliar with the Hyper-Utils codebase, and am not massively familiar with the Rust ecosystem/language, I'm unsure of the best place to deal with this, although I've also posted a sibling issue, to track this, at https://github.com/haikuports/haikuports/issues/11501.

**Comment by linyihai** [comment]
It's seems copy the[ target_os array](https://docs.rs/socket2/latest/src/socket2/lib.rs.html#511-524) from the upstream socket2 crate can fix this problem. 

I'll submit a PR later. :)
