### ISSUE TITLE
Hyper client fails if the header isn't fully received in the first read

### ISSUE THREAD

**Issue by r-darwish** [hyperium/hyper#389]
Some HTTP servers do not send the entire HTTP header in a single chunk. Hyper assumes that the entire header is received when calling fill_buf, which isn't always the case.

Running the client example in the documentation against a [Flask test server](http://flask.pocoo.org/) causes it to panic:

thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: HttpTooLargeError'

**Comment by seanmonstar** [comment]
True, I was hoping that the BufReader would fill it's entire buffer before yielding, which [by default is 64kb](https://github.com/rust-lang/rust/blob/master/src/libstd/io/mod.rs#L50). Is the test server head bigger than this? Or BufReader is yielding earlier?

**Comment by r-darwish** [comment]
The head is a few bytes long. By looking at Wireshark I could see that the different lines of the head are spread among multiple TCP packets, which cause BufReader to yield the first received packet, which contains only the first head line.
