### ISSUE TITLE
Generating a RequestUri::Star on a client Request

### ISSUE THREAD

**Issue by GGist** [hyperium/hyper#408]
I am having trouble trying to generate an http request that uses a single asterisk in place of the path. An example of the request I would like to generate would be
```
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 5
ST: ssdp:all 
```
which is a standard SSDP request. I suspect that this may have to be implemented via the Url object that the Request object is currently relying on to provide information like this but I am not sure.

**Comment by seanmonstar** [comment]
Hm. So, it can't be as simple as `client.get("*")`, since the Url is currently used to find the address to connect on. Before worrying about the `Client`, and just thinking of about `Request`, it could probably use a `set_uri` method, that would allow adjust which `RequestUri` was used when building the request line. This would enable:

```rust
let mut req = Request::new(Method::Unregistered("M-SEARCH"), "http://239.255.255.250:1900");
req.set_uri(RequestUri::Star);
```

**Comment by GGist** [comment]
@seanmonstar That could work, of course you would be allowing anyone to also call set_uri() with other variants of RequestUri which is easier (albeit more error prone) than modifying the Url directly. I am also not sure about spanning the construction process (as far as this request is concerned) across two different methods.

I am not too versed on the Http standard, but it looks like the asterisk represents a request that applies server wide instead of pointing to one specific resource. As such, we could probably represent it with a simple flag within the Request object that we check before converting the request to text. In an attempt to reuse the Url structure for location information (and nothing more, ex: path) I think a step in the right direction would be:
```
let req = Request::server_wide(Method::Extension("M-SEARCH".to_string()), "http://239.255.255.250:1900");
```
Now ideally we would throw an error if the user entered in any path to the Url so that they arent confused when what they think is being sent, isn't actually sent. This is assuming we actually want to reuse the Url object in this scenario and throw that error if it occurs. 

However, we could make it so that we are explicit to the user that we are interested in a location and nothing more by doing:
```
impl Request {
fn server_wide<T>(method: Method, addr: T) -> Request where T: ToSocketAddrs;
}

let req = Request::server_wide(Method::Extension("M-SEARCH".to-string()), "239.255.255.250:1900");
```
which would help the user understand that we are using the location and nothing more. I believe ToSocketAddrs accepts host names that can be resolved through DNS (not sure if it accepts protocol info like http).

The only problem here is if the user tries going into the Url object that is still being exposed by the request and manually adds some path elements thinking they will be used when they wont.

@reem Unfortunately I am not too versed on modifiers to comment on them, but hey, whatever provides a good interface works for me.

**Comment by GGist** [comment]
On second thought, I just realized that my proposed solution may not work because we would have to have another, duplicate method, to support the Request::with_connector() for server wide requests.

I will keep thinking this over, in the meantime, if we want to proceed with the solution proposed by @seanmonstar or anyone else, then that sounds fine to me.
