### ISSUE TITLE
Dependency (libressl-pnacl-sys) cannot be retrieved via cargo

### ISSUE THREAD

**Issue by jonalmeida** [hyperium/hyper#411]
While trying to start a new hyper hello world server, cargo is unable to fetch all the dependencies for hyper (see the error below):
```
[hyper-test] cargo fetch
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.1.4
 Downloading openssl v0.5.3
 Downloading lazy_static v0.1.8
 Downloading hyper v0.3.6
 Downloading rustc-serialize v0.3.10
 Downloading cookie v0.1.16
 Downloading pkg-config v0.3.2
 Downloading url v0.2.28
 Downloading time v0.1.22
 Downloading log v0.3.1
 Downloading httparse v0.0.5
unable to get packages from source

Caused by:
  failed to parse manifest at `/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/libressl-pnacl-sys-2.1.4/Cargo.toml`

Caused by:
  library target names cannot contain hyphens: libressl-pnacl-sys
```

The dependency in question is [`libressl-pnacl-sys`](https://crates.io/crates/libressl-pnacl-sys) while running on rust nightly:

```
[~] cargo --version                                                   15:25:01 
cargo 0.0.1-pre-nightly (9f265c8 2015-03-25) (built 2015-03-25)
[~] rustc --version                                                   15:25:05 
rustc 1.0.0-nightly (199bdcfef 2015-03-26) (built 2015-03-27)
```

Cargo.toml of the hello world app:
```
[package]
name = "hyper-test"
version = "0.0.1"
authors = ["Jonathan Almeida <git@jonalmeida.com>"]

[dependencies]
hyper = "*" 
```

Trying to build the libressl-pnacl-sys library on my own, I found that it uses outdated data structures in std (i.e. RingBuf), which is another error you will encounter if you to build it after changing the package name to use underscores instead of hypens.

**Comment by jonalmeida** [comment]
I'm curious to know how others are building hyper or if I've done something wrong in my build process.

**Comment by seanmonstar** [comment]
It seems it's a target specific dependency in openssl:
https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/Cargo.toml
