### ISSUE TITLE
Specify timeout for client requests?

### ISSUE THREAD

**Issue by jimmycuadra** [hyperium/hyper#417]
A few times while integration testing a library I'm building with Hyper, the test runner has hung infinitely due to what I assume is an HTTP request that's never timing out. Is it possible to specify a timeout for a request? Should the default be infinite, as it seems to be?

IIRC there isn't an implementation of network timeouts in std, which might explain the current behavior. Any tips on debugging a request that hangs to figure out what it's doing?

**Comment by Ryman** [comment]
Could be related to #368

**Comment by seanmonstar** [comment]
Yep, the removal of timeouts from std means we don't have an easy way to do this. cc #315 

@jimmycuadra as for debugging, you could set up a logger (such as env_logger, or log4rs). With env_logger, you could use `RUST_LOG=hyper` to get the full firehose of logs.

**Comment by adimarco** [comment]
@jimmycuadra Did you ever figure this out?  And/or was this related to integration testing with Rusoto?  I'm seeing the same behavior there.

**Comment by jimmycuadra** [comment]
I believe I came across this when working on either rust-fleet or rust-etcd, and eventually figured out what was wrong with my connection settings using the logger.
