### ISSUE TITLE
add more tests

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#43]

**Comment by pyfisch** [comment]
I think it is useful. If @seanmonstar and @reem want to use it I will write some end-to-end tests using it.

**Comment by seanmonstar** [comment]
@winding-lines this would be useful. You could look at the coveralls report to see where some test cases are missing...

**Comment by winding-lines** [comment]
@seanmonstar sounds good. I have been looking a bit at adding proxy to client but it would be useful to know more of the code first :+1:
