### ISSUE TITLE
Accept-Encoding only accepting QualityItems

### ISSUE THREAD

**Issue by mattnenterprise** [hyperium/hyper#434]
It looks like the Accept-Encoding header can only be given q values with the items it is given. 
It looks like it can't be given values that don't have a q value such as:
`Accept-Encoding: gzip, deflate`

**Comment by jdm** [comment]
Items without a quality value default to 1.0 in implementation terms, AFAIK.

**Comment by pyfisch** [comment]
@jdm is right.
