### ISSUE TITLE
HttpTooLargeError after the response

### ISSUE THREAD

**Issue by mikedilger** [hyperium/hyper#437]
Ever since the new buffering code, I get `HttpTooLargeError`s after almost every response.  It is after the handler returns and the response has been sent, and so the site continues to function.  But clearly something is amiss.   The requests are rather normal small requests, nothing large, nothing fancy.

````
ERROR:hyper::server: request error = HttpTooLargeError
````
in `server/mod.rs` `handle_connection()` `while keep_alive` loop, the `Request::new()` calls `http::parse_request()` which fails with HttpTooLargeError at some point around this keep_alive loop, which means that `read_into_buf()` must have returned `Ok(0)` which means that `self.cap < v.capacity()`, but I haven't looked further as to why that is for small requests that are only handled once.

**Comment by hoxnox** [comment]
I maked a pull request: https://github.com/hyperium/hyper/pull/454
