### ISSUE TITLE
Chunked responses return a zero-length response after the first chunk

### ISSUE THREAD

**Issue by jdm** [hyperium/hyper#441]
http://mxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/XMLHttpRequest/getresponseheader-chunked-trailer.htm?force=1 fails in Servo, since we only receive the first chunk. See http://mxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/XMLHttpRequest/resources/chunked.py?force=1 for the generated response.

**Comment by seanmonstar** [comment]
Any more details? This test case in hyper https://github.com/hyperium/hyper/blob/master/src/client/response.rs#L140 should mean that the chunked reader works...

**Comment by seanmonstar** [comment]
Looking at the python some more, I don't think it's outputting [proper chunked data](https://tools.ietf.org/html/rfc7230#section-4.1).

1. It's including the ending CRLF as part of the chunk size, but that's not what the spec says.
2. It's reporting the chunk size as a decimal, but it's supposed to hexidecimal. So, when it claims the 3rd line is 27, hyper reads that as 0x27.

**Comment by jdm** [comment]
It actually looks like hyper doesn't even yield the first chunk. I wonder if Firefox deals with the test output differently?

**Comment by seanmonstar** [comment]
This is a bug in web-platform-tests. See https://github.com/w3c/web-platform-tests/pull/1736
