### ISSUE TITLE
Custom HTTP Methods

### ISSUE THREAD

**Issue by nicholaswyoung** [hyperium/hyper#450]
I'm looking at Rust and Hyper for building out an Icecase-compliant streaming audio server. After looking at the docs, I don't see if it's possible to hook up custom HTTP methods or not. 

For instance, Icecast uses the SOURCE method to authenticate mount points. Is it possible to handle a SOURCE request to the server using Hyper?

Next up, handling incoming binary data streams... But that's a topic for a different issue.

**Comment by seanmonstar** [comment]
Yep, there's `Method::Extension(String)` for extension methods: http://hyperium.github.io/hyper/hyper/method/enum.Method.html

**Comment by nicholaswyoung** [comment]
@seanmonstar Awesome. Thanks for the link to documentation. Do you have opinions or links on how to handle binary data transfer?

**Comment by seanmonstar** [comment]
I'm not sure what you mean. Hyper Request and Response objects implement
std::io::Read and Write, and so operate as a stream of bytes. How you deal
with the bytes is up to you.

**Comment by nicholaswyoung** [comment]
You answered the question. So long as I have access to the raw stream of bytes, I'm good to go. Thanks!

**Comment by nicholaswyoung** [comment]
A month later, and I'm still trying to wrap my head around Hyper. I'm implementing an HTTP server that needs to respond to SOURCE requests, for Icecast emulation. Do you have an example of how I might reason about this?

**Comment by reem** [comment]
@nicholaswyoung just match on the method field of the Request and check for a `Method::Extension` which contains the expected string (`SOURCE`).
