### ISSUE TITLE
arithmetic operation overflowedarithmetic operation overflowed

### ISSUE THREAD

**Issue by whispermemory** [hyperium/hyper#452]
Thread '<main>' panicked at 'arithmetic operation overflowed', github.com-1ecc6299db9ec823/hyper-0.3.11/src/server/mod.rs:90

pub fn listen<T: ToSocketAddrs>(self, addr: T) -> HttpResult<Listening> {
    self.listen_threads(addr, num_cpus::get() * 5 / 4);`
}

**Comment by whispermemory** [comment]
13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64

**Comment by seanmonstar** [comment]
Fixed with num_cpus v0.2.1
