### ISSUE TITLE
Exposing SslContext for flexibility (e.g. client-side certs, etc)

### ISSUE THREAD

**Issue by mikedilger** [hyperium/hyper#471]
Currently, `net::HttpListener::https()` takes a certificate and a key, and sets up an SslContext with a lot of assumptions.  For example, it sets the DEFAULT cipher list.  It also sets SSL_VERIFY_NONE.
This is called by `Server::listen_threads()`.   I'm trying to make changes that allow the caller to pass in an SslContext.

Currently the SSL configuration is declared when the Server is created, by passing a certificate and a key to `Server::https()`.  Unfortunately this scheme will not direclty work with a passed in `SslContext`, because if an `SslContext` is setup in the `Server` struct, it *moves* when passed on to HttpListener::https(), causing a "use of partially moved value" error.   This cannot be solved via `clone()` because `SslContext` does not implement `clone()`.

If `Server::listen_threads()` accepted the SSL information at that point (rather than owning it in it's struct), this would cause a lot of breaking changes.

OTOH, If `HttpListener` kept a reference to an `SslContext` (instead of owning it), it would propagate another annoying lifetime parameter over a lot of code.

I don't see a clearly preferable way of implementing this. Given a preferred direction, I'd be happy to make the changes necessary.

**Comment by mikedilger** [comment]
Another option I thought of:  `HttpListener` could get a separate `listen` method (where `http` and `https` would do everything except the `bind` step),  and then a new method could be created that gets a mutable reference to the `SslContext`, to be called prior to `listen`.

Also I forgot to cc @seanmonstar

**Comment by seanmonstar** [comment]
@mikedilger I'm not sure I follow. In `listen_threads`, the Server is taken by value. You can move the context out of the Server in this method.

**Comment by mikedilger** [comment]
`self.with_listener(listener, threads)` requires both self (Server) and listener.  If the context is moved, then 'self' is no longer available.  See https://github.com/mikedilger/hyper/tree/ssl_context

**Comment by seanmonstar** [comment]
Ohhh, I see what you mean. Ok, so the `with_listener` method takes `self`, but it only needs to access `self.handler`. What about creating a private free function `with_listener`, that the method calls as `with_listener(self.handler, listener, threads)`. Then, `listen_threads` can skip the internal method, and just move out both the `ssl` and the `handler` in the same function. Make sense?

**Comment by mikedilger** [comment]
I'm glad I asked, because I hadn't thought of that.

I did this in 3 commits.  See PR #479
