### ISSUE TITLE
Reminder: Upgrade header Protocols should support version

### ISSUE THREAD

**Issue by pyfisch** [hyperium/hyper#480]
As defined in http://tools.ietf.org/html/rfc7230#section-6.7 a protocol consists of a name and an optional version token.

**Comment by seanmonstar** [comment]
I don't understand what the action is for this issue. Does the `Upgrade` header need to be changed?

**Comment by pyfisch** [comment]
Yes we need to change `Upgrade` header field. (What means "need" we can also keep it but do not implement the RFC)

The RFC says:
```
     Upgrade          = 1#protocol
     protocol         = protocol-name ["/" protocol-version]
     protocol-name    = token
     protocol-version = token
```

We do:
```
     Upgrade          = 1#protocol
     protocol         = text
```
