### ISSUE TITLE
Client: Setting a custom SSL verifier discards previous Connector

### ISSUE THREAD

**Issue by mlalic** [hyperium/hyper#495]
When the `Client::set_ssl_verifier` method is called, it will discard any previously existing `Connector` instance that the `Client` was instantiated to use. This wasn't a problem before, when the connectors were largely stateless, but with the introduction of a `Pool` connector, this means that the pool's config will be dropped (replaced with the default one) and the client will use a brand new set of connections, instead of the originally intended ones.

**Comment by seanmonstar** [comment]
This is true. Before, it was possible when `Client` was generic over the NetworkConnector. Perhaps such a method `set_ssl_verifier` should be added to the `NetworkConnector` trait...
