### ISSUE TITLE
Getting back a response given raw request bytes

### ISSUE THREAD

**Issue by ucarion** [hyperium/hyper#496]
Given `host: &str`, `port: u16`, `scheme: &str`, and `data: &[u8]`, how do I get back the raw bytes of a http response? `data` would contain the bytes corresponding to a string like `"GET / HTTP/1.1\r\nHost: example.com\r\n\r\n"`.

Context: I've been creating a `MockConnector` and `MockStream` that implement their `Network{Connector, Stream}` counterparts, and now I'm trying to send an actual request given what has been written to a `MockStream`.

Also, thanks for making hyper. I'm really enjoying using it. :)

**Comment by seanmonstar** [comment]
I'm sorry, I don't follow that well. You have a `data: &[u8]` already? Or you wish to receive one from a response?

**Comment by ucarion** [comment]
`data` is what would have been written to a `NetworkConnector` -- in hyper's `mock.rs`, it corresponds to the contents of this variable:

https://github.com/hyperium/hyper/blob/master/src/mock.rs#L9

I have this already, and what I want to get is the response of the remote HTTP server.

Sorry for the imprecise wording; I don't really know what things are called here.

**Comment by seanmonstar** [comment]
I suppose some code of what you're trying to do would help.

**Comment by ucarion** [comment]
You're absolutely right. Here's the function I'm trying to write, as well as an example of how I'd like to call it. It doesn't work right now.

```rust
use std::io::{self, Read, Write};
use std::net::Shutdown;
 
use hyper::net::{HttpConnector, NetworkConnector, HttpStream};
 
fn fetch_http(host: &str, port: u16, scheme: &str, data: &[u8]) -> io::Result<Vec<u8>> {
    let mut connector = HttpConnector(None);
    let mut stream = connector.connect(host, port, scheme).unwrap();
 
    println!("{:?}", stream);
 
    stream.write(data).unwrap();
 
    let mut buf = Vec::new();
    stream.read_to_end(&mut buf).unwrap();
    Ok(buf)
}
 
fn main() {
    let msg = b"GET / HTTP/1.1\r\nHost: example.com\r\n\r\n";

    // I would like this to output the response from the server, including HTTP headers and whatnot.
    println!("{:?}", fetch_http("example.com", 80, "http", msg));
}
```

**Comment by seanmonstar** [comment]
With all of that, you could just use plain TcpStreams.

Have you seen the [Client](http://hyperium.github.io/hyper/hyper/client/index.html) API, to take over this for you?

**Comment by ucarion** [comment]
I tried using TcpStream, but the problem is that I don't know in advance how long the server's response is. `Response::new(stream)` (where `stream` is the result of `HttpConnector(None).connect`) *almost* works, but it doesn't give me back the headers.

Perhaps I'm approaching this entire problem in the wrong way: do you know of a way to implement an HTTP recorder/replayer (à la [vcr](https://github.com/vcr/vcr)) with hyper? I tried making a `MockConnector` so that in my tests I could simply write `Client::with_connector(MockConnector)` in order to replace actual HTTP responses with replayed ones, but as you can see I'm having trouble with this approach.

(I was trying to make the `fetch_http` above because the only things NetworkConnector and NetworkStream know about are the URL of the server and the data being sent to the server.)

**Comment by seanmonstar** [comment]
Oh, so you want to see the raw bytes, not have hyper handle them using `hyper::Client`. Reading from the `hyper::client::Response` will only read the body; the status-line and headers are available on the `Response` as `status`, `version`, and `headers` properties.

Reading your proposed `fetch_http` function, it *looks* like it should all work. What wasn't, specifically?

**Comment by ucarion** [comment]
> Reading your proposed fetch_http function, it looks like it should all work. What wasn't, specifically?

Actually, I went back and it turns out I misspoke. `fetch_http` does return the correct result, but it takes multiple seconds for the call to `read_to_end` to terminate. I'm guessing some sort of timeout is forcing termination. Is there a way for the stream to know when the server doesn't have anything more to send?

**Comment by seanmonstar** [comment]
Oh, that could be the case.If you want to use `Response`'s readers (which handle chunked and content-length correctly), you could just read from Response.

```rust
let mut raw = Vec::new();
let mut res = Response::new(stream);
writeln!(&mut raw, "{} {}", res.version, res.status);
write!(&mut raw, "{}", res.headers);
io::copy(&mut res, &mut raw);
```

**Comment by seanmonstar** [comment]
Though, that will copy the decoded body (in case you need to replay the body encoded in chunks, you'd need to do figure something else out).

**Comment by ucarion** [comment]
> Though, that will copy the decoded body (in case you need to replay the body encoded in chunks, you'd need to do figure something else out).

I understand that I wouldn't be able to replay the chunks individually with this approach, but I'd still be able to read the complete response, right?

**Comment by ucarion** [comment]
I think I've got something that works now, thanks! For future internet people, this is what I've come up with:

```rust
pub fn fetch_http(host: &str, port: u16, scheme: &str, data: &[u8]) -> io::Result<Vec<u8>> {
    let mut connector = HttpConnector(None);
    let mut stream = try!(connector.connect(host, port, scheme));

    try!(stream.write(data));

    let mut buf = Vec::new();
    let mut res = Response::new(Box::new(stream)).unwrap();
    try!(write!(&mut buf, "{} {}\r\n", res.version, res.status));
    try!(write!(&mut buf, "{}\r\n", res.headers));
    try!(io::copy(&mut res, &mut buf));

    Ok(buf)
}
```
