### ISSUE TITLE
Server listening on 0.0.0.0:8000 hangs forever

### ISSUE THREAD

**Issue by dschneider** [hyperium/hyper#505]
Hello there,

When binding the server to 0.0.0.0:8000, a response takes either very long to come back or it times out. I experienced this problem on Ubuntu 14.04, 64 Bit. It runs without problems on Mac OS X 10.10.4. I created a Gist to illustrate the problem: https://gist.github.com/dschneider/2f845820ce1f5afc8c77

The code also includes an example of a small echo server that works without any problems on Ubuntu. I also tested it with a small web server written in Ruby that was bound to 0.0.0.0:8000 and it worked without any problems.

FYI: Binding it to 127.0.0.1/localhost works as well. It only seems to be 0.0.0.0

**Comment by seanmonstar** [comment]
A single request? Can you paste the raw request message? That server works
on my Ubuntu...

**Comment by dschneider** [comment]
@seanmonstar I have set up an Ubuntu virtual machine to verify. It works indeed. So it's most likely a configuration issue on our AMI. Thank you for looking into this!
