### ISSUE TITLE
add Windows CI using AppVeyor

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#513]
http://www.appveyor.com/

**Comment by superlogical** [comment]
I don't mind having a go at getting this setup if nobody else has already volunteered :)

**Comment by seanmonstar** [comment]
Go for it!

**Comment by superlogical** [comment]
Looks like a few other projects are doing this:

https://github.com/rust-lang/log/blob/master/appveyor.yml
https://github.com/tomaka/glutin/blob/master/appveyor.yml
https://github.com/tomaka/cpal/blob/master/appveyor.yml#L4

**Comment by superlogical** [comment]
It would be nice if OpenSSL also used appveyor https://github.com/sfackler/rust-openssl/issues/212
