### ISSUE TITLE
Expose NetworkStream+Send to the server

### ISSUE THREAD

**Issue by kempchee** [hyperium/hyper#521]
I need access to the downcast methods on NetworkStream+Send on the server in order to gain access to a TcpStream object.  This will allow me to implement an iron middleware to upgrade connections to websocket connections, following the work already done in rust-websockets.  

Iron currently only has access to a NetworkStream which is obtained by calling "deconstruct" on the request object provided by hyper.

**Comment by seanmonstar** [comment]
The changes to do here is to change the `&'a NetworkStream` in `hyper::server::Request` to be `&'a (NetworkStream + Send)`.

**Comment by reem** [comment]
Alternatively just add downcasting to `NetworkStream` proper, in addition to the impl for `NetworkStream + Send`.

**Comment by seanmonstar** [comment]
Ah yes, we could duplicate the definition for `impl NetworkStream` (grumble grumble)...

**Comment by kempchee** [comment]
I'm going to attempt to make the changes myself using the first proposed solution.  If I get stuck I'll post on this thread

**Comment by seanmonstar** [comment]
The second one would be easier. The first would be preferred if there's a need to send that trait object to another thread...

**Comment by kempchee** [comment]
Wouldn't that be useful?  For instance, I initialize a websocket connection.  Later on, my client makes an http request and that request wants to be able to send data through the websocket while the new request is still processing.  I'm just not sure if this scenario would require passing NetworkStream+Send to more than one thread(my intuition tells me it would)
