### ISSUE TITLE
Consider adding license badge from shields.io

### ISSUE THREAD

**Issue by ssokolow** [hyperium/hyper#525]
There are three reasons why I think you should at least consider using a badge from [shields.io](http://shields.io/) to indicate the license in README.md:

1. It allows you to comfortably put the license at the top of the file so people dropping in don't have to scroll down past the examples. (I don't know about you but I always check a library's license before I consider the merits of its API.)
2. Depending on the user, it may be significantly more eye-catching than plain text.
2. Having a section (License) with just one word in it (MIT) looks unpolished.

Here's the badge and the markdown involved:

[![MIT licensed](https://img.shields.io/badge/license-MIT-blue.svg)](https://raw.githubusercontent.com/hyperium/hyper/master/LICENSE)
```markdown
[![MIT licensed](https://img.shields.io/badge/license-MIT-blue.svg)](https://raw.githubusercontent.com/hyperium/hyper/master/LICENSE)
```

...or you could pull it dynamically from the GitHub or crates.io metadata APIs by using one of these image URLs:

https://img.shields.io/github/license/hyperium/hyper.svg
https://img.shields.io/crates/l/hyper.svg

**Comment by reem** [comment]
@ssokolow I agree this would be nice. If you're up to PR the changes to the README, I'd be happy to review/merge.

**Comment by ssokolow** [comment]
Sure. My main concern is that I'm not sure what ordering to use. 

In my projects, I tend to block things out as "[CI] [Coverage] [Static Analysis] [Release Metadata] [License]"

[![Build Status](https://travis-ci.org/hyperium/hyper.svg?branch=master)](https://travis-ci.org/hyperium/hyper) [![Coverage Status](https://coveralls.io/repos/hyperium/hyper/badge.svg?branch=master)](https://coveralls.io/r/hyperium/hyper?branch=master) [![crates.io](http://meritbadge.herokuapp.com/hyper)](https://crates.io/crates/hyper) [![MIT licensed](https://img.shields.io/badge/license-MIT-blue.svg)](https://raw.githubusercontent.com/hyperium/hyper/master/LICENSE)

...but, here, the colours make me want to organize it like this instead...

[![MIT licensed](https://img.shields.io/badge/license-MIT-blue.svg)](https://raw.githubusercontent.com/hyperium/hyper/master/LICENSE) [![Build Status](https://travis-ci.org/hyperium/hyper.svg?branch=master)](https://travis-ci.org/hyperium/hyper) [![Coverage Status](https://coveralls.io/repos/hyperium/hyper/badge.svg?branch=master)](https://coveralls.io/r/hyperium/hyper?branch=master) [![crates.io](http://meritbadge.herokuapp.com/hyper)](https://crates.io/crates/hyper)

**Comment by reem** [comment]
I'd prefer build, crates, coverage, license. Since the colors might change, we shouldn't organize by color.

**Comment by ssokolow** [comment]
I normally wouldn't organize by colour either, but that crates.io badge really throws off my usual rules.

Normally, my rationale is:

1. The left 2/3rds change colour to indicate problems and should be a mass of green.
2. The right 1/3rd don't indicate status and should be a neutral blue.

Sticking the crates badge so close to the status-indicating badges knocks my brain off the fast-path evaluation.

Perhaps this so that it's clear that the "blue stuff" section has already started?

[![Build Status](https://travis-ci.org/hyperium/hyper.svg?branch=master)](https://travis-ci.org/hyperium/hyper) [![Coverage Status](https://coveralls.io/repos/hyperium/hyper/badge.svg?branch=master)](https://coveralls.io/r/hyperium/hyper?branch=master) [![MIT licensed](https://img.shields.io/badge/license-MIT-blue.svg)](https://raw.githubusercontent.com/hyperium/hyper/master/LICENSE) [![crates.io](http://meritbadge.herokuapp.com/hyper)](https://crates.io/crates/hyper)

**Comment by reem** [comment]
@ssokolow sorry for just dropping this, I just found it again and still want to do this. Feel free to PR build, coverage, license, crates.
