### ISSUE TITLE
Add Proxy support to Client

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#531]
I imagine some sort of `Proxy` type being added a property of `Client`, with a corresponding `set_proxy(Option<Proxy>)` method.

Use of a proxy can have different requirements: all requests, only https requests, only http... So it would probably mean `Proxy` would be an enum... and the proxy would be consulted in the `RequestBuilder.send` method.

**Comment by messense** [comment]
It would be awesome to have this feature!

**Comment by shaleh** [comment]
Yes please. Some of us need this to use Rust at work.

**Comment by shaleh** [comment]
Something like:

    let proxy = Proxy::new(server, port, scheme);  // AuthProxy::new for the more complicated cases
    let mut client = Client::new();
    client.add_proxy(proxy);  // set_proxy, which ever. Bike shed as needed
    // now a request using 'scheme' will be proxied
    client.get(....)

**Comment by mattnenterprise** [comment]
I would like to give this a try.

**Comment by mattnenterprise** [comment]
@seanmonstar  Could you give more information on how you think this should be implemented?

**Comment by seanmonstar** [comment]
@mattnenterprise an api suggested by @shaleh looks fine. It'd likely require adding a method to `Request` to change the `RequestUri`, since the full url is needed instead of just the path.

**Comment by shaleh** [comment]
Note the requirement for a list of proxies. When the final HTTP call is made it should check the request's scheme against defined proxies for a matching scheme.

**Comment by shaleh** [comment]
Since Rust does not support optional arguments I used ``AuthProxy`` in my example for the case where the proxy needs authentication. If this is too cumbersome using ``Option`` for the credentials is probably OK.

**Comment by shaleh** [comment]
I think using a container for the proxies avoids the need for ``Option<Proxy>``. Just walk it and compare schemes. Since the list will only every be a few items long it is sane to walk it. No need for a hash or other lookup table.

**Comment by seanmonstar** [comment]
There's a PR for this at #639, if others interested in this feature could help looking it over.

**Comment by winding-lines** [comment]
Hello everybody, I have been working on the proxy implementation for a while (on and off) but I missed this conversation :-) I will evolve my PR based on this feedback.

**Comment by kikokikok** [comment]
Hi All,
I've just been tracking down the reason why multirust-rs is not able to work behind a proxy, It seems like the Http Client used in multirust is the Hyper one which leads me to this discussion and the associated PR.

Do you have an ETA on this one ? it seems like it hasn't evolved since October. Any chance to see this merged or is it still not mature enough. 
I see a lot of value in having this functionality built-in Hyper as it serves a lot of tools/libs in the ecosystem and could clearly help to drive Enterprise adoption.

Thanks !

**Comment by mitsuhiko** [comment]
I'm in the same boat. I really need proxy support. Is there any chance I can help out with this?

**Comment by maximih** [comment]
Any updates on this?

**Comment by seanmonstar** [comment]
My focus is entirely on the async branch, which makes this easy:

```rust
struct ProxiedHandler(hyper::Method, &'static str);

impl Handler for ProxiedHandler {
    fn on_request(&mut self, req: &mut Request) -> Next {
        req.set_method(self.0);
        req.set_uri(RequestUri::AbsoluteUri(self.1.parse().unwrap());
        Next::read()
    }
    // ...
}
client.request("http://proxy.server", ProxiedHandler(GET, "http://target.domain/path")); 
```

I can try to add in some support to the sync branch, such that if the `Request.url` does not match the `Host` header, then assume it is a proxied request and send the full URI...

**Comment by seanmonstar** [comment]
See #771 to add simple support to the sync branch. This will be released in hyper 0.9.2.

@shaleh this doesn't add support for lists, or `Proxy-Authorization` or the like. I believe those can be handled outside of hyper. The parts fixed in this PR were things that could not be done without hyper's help.

**Comment by shaleh** [comment]
No worries, I do not need either lists or Proxy-Authorization.

**Comment by JeffBelgum** [comment]
@seanmonstar I am in need of `Proxy-Authorization` for a project at work. In a comment above, you suggest that it could be handled outside of hyper. Would you be able to provide some guidance as to how to do this? Would it involve creating a new `NetworkConnector` or some other approach?

**Comment by seanmonstar** [comment]
@JeffBelgum possibly. When exactly should the header be sent, as part of the normal request, or as part of the `CONNECT` tunnel request?

**Comment by JeffBelgum** [comment]
It's send as part of the `CONNECT` tunnel request.

**Comment by seanmonstar** [comment]
Then it seems that would require a new `NetworkConnector`, as the current `Proxy` doesn't have a way to customize the headers sent: https://github.com/hyperium/hyper/blob/0.10.x/src/client/proxy.rs#L47

It probably should, and I think it can be done in a backwards compatible way, by adding a method to `ProxyConfig`, and then making use of that in the `Proxy`.

**Comment by JeffBelgum** [comment]
Great, thanks for the help! Would you be open to a PR against the 10.x branch that implements proxy authorization?

**Comment by seanmonstar** [comment]
@JeffBelgum for increased flexibility, I'd probably suggest allowing the `ProxyConfig` to accept a `Headers` struct, that is applied to each `CONNECT` request.

Some proxies use different headers for auth, and may or may not require other headers like User-Agent. Best to just let people configure any header.
