### ISSUE TITLE
Add a complete simple use case for how to download a page and use its contents for the client

### ISSUE THREAD

**Issue by unfo** [hyperium/hyper#532]
The current documentation is complete nor very beginner friendly:

```
let mut client = Client::new();

let res = client.get("http://example.domain").send().unwrap();
assert_eq!(res.status, hyper::Ok);
```

Things that should be added:
* What are the full rust includes (extern crate / use lines) that are needed
* How to read the contents and possibly just print it

For example if you just add 
```
extern crate hyper;
use hyper::*;
```

And then try to read the body with this additional code to the example:
```
	let mut contents = String::new();
	res.read_to_string(&mut contents);

```

You will get the following error: 
```
src/main.rs:11:22: 11:51 error: type `hyper::client::response::Response` does not implement any method in scope named `read_to_string`
src/main.rs:11 	let body = try!(res.read_to_string(&mut contents));
               	                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Which is not clear for beginners since the documentation says that this function is implemented for the Response.

The missing code was:
```
use std::io::prelude::*;
```

or 

```
use std::io::Read;
```

Please provide a complete tutorial on how to correctly download a page and use its contents in a idiomatic rust way. Extra points for good error handling also.

**Comment by brycefisher** [comment]
My vote here is to provide two client examples:

 * The existing, overly-simplistic client.rs (for quickly wrapping your around a simple example)
 * A new example that DOES something more interesting, like:
   * try to print your GPS coordinates from your IP address (using freegeoip.net etc)
   * print the an issue number, title, and url from this repo using the github api (would require parsing json)
   * scrape craigslist for a used guitar
   * find an interesting piece of trivia from an [opengov API](http://catalog.data.gov/dataset?res_format=JSON&q=-aapi+api+OR++res_format%3Aapi)

**Comment by pyros2097** [comment]
Yeah More docs please. I Couldn't  even get google.com it gave me this error.
```
thread 'send_request' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }) }', src/libcore/result.rs:741
```

**Comment by mfarrugi** [comment]
The front page readme / examples of this project are still broken, and also requires the Response to be mutable.

**Comment by seanmonstar** [comment]
@mfarrugi broken? seemed there was an unused_mut warning, which has been fixed in https://github.com/hyperium/hyper/commit/b98662ab6db6b65b8310dc0f76374cdc8fc9c627, but I don't otherwise see them broken...

**Comment by mfarrugi** [comment]
I've got no idea what I thought was broken. Forgive me :)

**Comment by seanmonstar** [comment]
Closing in favor of #805
