### ISSUE TITLE
Can't POST a variable

### ISSUE THREAD

**Issue by AAG81** [hyperium/hyper#535]
I can't post variable to a PHP test page,
I want to pass 3 POST variable to a test page, works fine with cURL
but when I use rust hyper I see variable in tcpdump but won't work
cUrl header has Content-Type="application/x-www-form-urlencoded"
which I didn't find it in Struct hyper::header::ContentType Methods
how can I add Content-Type: application/x-www-form-urlencoded
Thanks

**Comment by Ryman** [comment]
```rust
#[macro_use] extern crate mime;
extern crate hyper;

use hyper::header::ContentType;

fn main() {
    // With macro
    println!("{}", ContentType(mime!(Application/("x-www-form-encoded"))))

    // With unwrap
    println!("{}", ContentType("application/x-www-form-encoded".parse().unwrap()))
}
```

**Comment by AAG81** [comment]
Id on't lnow how to add that For example How to replace that with json
extern crate hyper;
use std::io::Read;

use hyper::header::ContentType;
use hyper::Client;
fn main() {
    let mut client = Client::new();
    let res = client.post("http://127.0.0.1")
        .header(ContentType::json())
        .body("caller=09121571&callee=502&uid=234567")
        .send()
        .unwrap();
    assert_eq!(res.status, hyper::Ok);

**Comment by AAG81** [comment]
I changed content_type.rs in hyper src compiled it again add new method 
now I have it and works fine;
is there a better way without changing the hyper src?

**Comment by Ryman** [comment]
@AAG81 In your above example you can do `.header(ContentType("application/x-www-form-encoded".parse().unwrap()))`

**Comment by seanmonstar** [comment]
@AAG81 

```rust
#[macro_use] extern crate mime;
extern crate hyper;
use std::io::Read;

use hyper::header::ContentType;
use hyper::Client;
fn main() {
    let mut client = Client::new();
    let res = client.post("http://127.0.0.1")
        .header(ContentType(mime!(Application/WwwFormUrlEncoded)))
        .body("caller=09121571&callee=502&uid=234567")
        .send()
        .unwrap();
    assert_eq!(res.status, hyper::Ok);
}
```

**Comment by AAG81** [comment]
Thanks a lot
