### ISSUE TITLE
POST a request without waiting for response

### ISSUE THREAD

**Issue by AAG81** [hyperium/hyper#537]
I want to POST a request without waiting for response,
I don't care if server is ok or not I just want to send some notification
How can I do that, is HTTP post ok for this or I should use something else.
If http post is ok how can I do this with hyper client?

**Comment by seanmonstar** [comment]
You may want UDP instead of TCP/HTTP, in that case.

-----

However, this isn't quite a help forum. It's a place to file bugs and feature requests regarding hyper. If you have general questions, I'd recommend the #rust IRC channel, or StackOverflow, as you'll get quicker answers from more people.

**Comment by AAG81** [comment]
I don't mean TCP acknowledge, I mean don't wait for HTTP response
in hyper client.
