### ISSUE TITLE
Bug: POST + not reading the body + keepalive => parser leaks the body to next request

### ISSUE THREAD

**Issue by golddranks** [hyperium/hyper#540]
When sending payload from client to Hyper server using POST, but not reading the body when handling the Request, the body is never consumed from the buffered network stream. If the connection stays alive, and the next message is sent, the body of the previous message is going to mess up the following message, like this: 

    Request Line: Extension("email=pyry.kontio%40drasa.eu&password=supersecretpasswordGET") AbsolutePath("/") Http11

I think we should consume the body after the request has been handled (row 212 of https://github.com/hyperium/hyper/blob/master/src/server/mod.rs ), and after it's clear we'll continue the loop (row 219).

**Comment by seanmonstar** [comment]
Looks like https://github.com/hyperium/hyper/issues/309

**Comment by seanmonstar** [comment]
Closing as dupe
