### ISSUE TITLE
Connection: close on request that uses Transfer-Encoding: chunked on the response does not read full response

### ISSUE THREAD

**Issue by wezm** [hyperium/hyper#547]
Sample program that reads entire response:

```rust
extern crate hyper;
extern crate env_logger;

use std::io::Read;

use hyper::Client;
use hyper::header::Connection;

fn main() {
    env_logger::init().unwrap();

    // Create a client.
    let mut client = Client::new();

    // Creating an outgoing request.
    let mut res = client.get("http://promodj.com/taga/rss.xml")
        // set a header
        // .header(Connection::close())
        // let 'er go!
        .send().unwrap();

    // Read the Response.
    let mut body = String::new();
    res.read_to_string(&mut body).unwrap();

    println!("Response: {}", body);
}
```

Running this gives the following trace: https://gist.github.com/wezm/962eb2c7b16b908256f3

Uncommenting the `Connection::close` line gives the following: https://gist.github.com/wezm/3942e9d33add01c789a2

I'm not sure if this is bug in hyper or the server misbehaving (I don't control the server). I note that curl downloads the full response even when the `Connection: close` header is specified via `-H "Connection: close"`.

**Comment by wezm** [comment]
I tracked down the problem and have come up with this as a fix but I'm new to Rust and this project so you may have a better approach: https://github.com/wezm/hyper/commit/4a42f43cefca076fc3dd3bdf871e19292b23e3b1

**Comment by seanmonstar** [comment]
Sorry about that, I had merged a fix into master already, but haven't published a new version yet. I'll do that right away.
