### ISSUE TITLE
Can't set server headers

### ISSUE THREAD

**Issue by steveklabnik** [hyperium/hyper#558]
If this isn't the right place to get help like this, please let me know. Thanks :)

I'm trying to set a few headers when sending a response. here's my code: https://gist.github.com/steveklabnik/3be1a0bfbf45e60ac60b

No matter which APIs I try, I always get just this:

```
$ curl http://0.0.0.0:8080/plaintext
Hello, World!
$ curl http://0.0.0.0:8080/plaintext -I
HTTP/1.1 200 OK
Date: Thu, 04 Jun 2015 14:23:25 GMT
Transfer-Encoding: chunked
$
```

Why isn't hyper properly setting the headers here? This code compiles...

**Comment by zr40** [comment]
Instead of `-I`, try either `-i` or `-X GET -I`. With `-I`, curl will send a `HEAD` request unless you tell it otherwise with `-X`.

**Comment by steveklabnik** [comment]
bah! of course. :cry: 

Thank you so much, @zr40. I knew I had to be doing something stupid....
