### ISSUE TITLE
Use WinAPI for SSL on Windows

### ISSUE THREAD

**Issue by retep998** [hyperium/hyper#573]
As an alternative to OpenSSL (which is generally quite annoying to build on Windows), it would be nice if Hyper had the option to use methods that WinAPI provides for SSL instead.

Bindings to the relevant WinAPI methods will be provided by me https://github.com/retep998/winapi-rs

Will use the abstraction provided by https://github.com/hyperium/hyper/pull/577

Related repos:
https://github.com/steffengy/rust-schannel

Relevant links:
[Authentication Functions](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374731%28v=vs.85%29.aspx)
[Using SSPI with a Windows Socket Client](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380536%28v=vs.85%29.aspx)
[Creating a Secure Connection Using Schannel](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374782%28v=vs.85%29.aspx)
[Secure Channel](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380123%28v=vs.85%29.aspx)
[SSPI with Schannel example](http://www.coastrd.com/c-schannel-smtp)

**Comment by steffengy** [comment]
Now also available through https://crates.io/crates/schannel

**Comment by luser** [comment]
In https://github.com/hyperium/hyper/issues/755, someone linked to https://github.com/sfackler/rust-native-tls, which is a crate wrapping openssl/security-framework/schannel, which might be a good way to go in the future.

**Comment by p-jackson** [comment]
Created a gist that shows how to get schannel working with hyper, just incase someone encounters this thread while looking for that info.
https://gist.github.com/p-jackson/198dd5de05b53d14b533d272f2eaefce

schannel needs an update before it'll work with hyper 0.9

**Comment by steffengy** [comment]
@p-jackson 
Be aware that it very likely won't work that way anymore for any future version.

In the future the usage of https://github.com/sfackler/rust-native-tls
or https://github.com/sfackler/schannel-rs (currently escpecially the rewrite branch).
will likely allow a similar usage.

**Comment by nshtg** [comment]
Are there any plans to integrate `rust-native-tls` using a special feature flag? Easy usage of hyper without openssl would be really exciting!

**Comment by sinhpham** [comment]
What is blocking this issue? I may find some time to work on this, however I'm not familiar with the code base. Can someone give me an overview of what needs to be done and what potential obstacles there are?

**Comment by seanmonstar** [comment]
This is waiting on the development of https://github.com/sfackler/rust-native-tls. It looks like releases are happening in the past couple days, but there were bad bugs until then.

**Comment by Diggsey** [comment]
`rustup` has been using `native-tls` as the default on windows for a while now. Are there any outstanding bugs that are blocking this?

**Comment by seanmonstar** [comment]
Probably not, other than all focus is on master, using async IO (and thus probably something like tokio-tls).

**Comment by Arnavion** [comment]
I think this can be closed now?

**Comment by seanmonstar** [comment]
Ah correct! TLS is no longer in hyper, see #985 for details.
