### ISSUE TITLE
Optimization issue?

### ISSUE THREAD

**Issue by DoumanAsh** [hyperium/hyper#574]
While learning a bit of hyper i made simple script:
https://github.com/DoumanAsh/collectionScripts/tree/master/rust/vim_updater

When i builds it with opt-level 2 or 3 the produced executable is not always work properly.
Sometimes it can stuck forever and only interrupt can stop it.

On other hand without or with opt-level 1 it works just fine.
Some dude tried to reproduce it on Linux, but it works fine with any optimization.

You can find all used flags for release: https://github.com/DoumanAsh/collectionScripts/blob/master/rust/vim_updater/Cargo.toml

And application itself: https://github.com/DoumanAsh/collectionScripts/blob/master/rust/vim_updater/src/main.rs

For openSSL i used 1.02c and gcc is 4.9.2

**Comment by seanmonstar** [comment]
Which operating system did you see this on?

Also, if you could enable logging, that would greatly help find where it
stops. Easiest may be using the env_logger crate.

**Comment by DoumanAsh** [comment]
Windows 8.1. x64

What sort of logging do you need?
It's easy to add prints at each step :)

**Comment by seanmonstar** [comment]
Oh, if you use something like env_logger, you can turn on hyper's logging.

**Comment by DoumanAsh** [comment]
I can try that later on and will put log here

**Comment by seanmonstar** [comment]
Yep, debug would be the most useful. After adding `env_logger::init().unwrap()` into your main function, you can set some env variables and then run the executable.

If you're using Powershell, it'd be `set $env:RUST_LOG="hyper=debug"`.

**Comment by DoumanAsh** [comment]
made quick look:
http://pastebin.com/Ay03qLms

A lot of directs...

**Comment by seanmonstar** [comment]
Yea, that's quite odd. The "normal" case is when run with opt-level < 2? Even weirder.

I assume you're using hyper v0.5.2 from crates.io. Would you mind trying a run using the latest commit? That'd be a change in your Cargo.toml to have:

```
[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
```

**Comment by DoumanAsh** [comment]
@seanmonstar 
Actually the normal case is the lucky run with opt-level 3 :)

**Comment by seanmonstar** [comment]
Additional weirdness:

The first debug line about redirect outputs the whole line, but the rest are all chopped.

```
DEBUG:hyper::client: redirect code MovedPermanently for https://tuxproject.de/projects/vim
...
DEBUG:hyper::client: redirect code
```

**Comment by DoumanAsh** [comment]
Hm... maybe it is powershell's doing...

**Comment by DoumanAsh** [comment]
Just in case i will try more tomorrow. Just to be sure it is not related to moon phase or random...

**Comment by DoumanAsh** [comment]
Re-checked again. Master has no issue.
So this problem will be fixed in next update of crate.

Will keep in mind to check master next time :)
