### ISSUE TITLE
OS X error: undefined symbols for architecture x86_64:   "_TLSv1_2_method"

### ISSUE THREAD

**Issue by winding-lines** [hyperium/hyper#575]
I am getting an undefined symbol related to openssl when I try to compile the latest on OS X. More detail below.

git log
```
commit e5dfb8233f25a4c57f2c6a68e8a7a854e42295b6
Merge: 41823ca edf6ac2
Author: Sean McArthur <sean.monstar@gmail.com>
Date:   Tue Jun 16 22:51:13 2015 -0700

    Merge pull request #572 from giftcards/master

    feat(headers): add bearer token support
```

rustc version
```
rustc -V
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
```

OS X version
```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D136
````

Libssl

```
ls -l /usr/lib/libssl.*
-rwxr-xr-x  1 root  wheel  400608 Sep  9  2014 /usr/lib/libssl.0.9.7.dylib
-rwxr-xr-x  1 root  wheel  616512 Mar 19 19:16 /usr/lib/libssl.0.9.8.dylib
lrwxr-xr-x  1 root  wheel      18 Feb 22 00:56 /usr/lib/libssl.dylib -> libssl.0.9.8.dylib
```

Actual error.

```
➜  cargo clean
➜  cargo test
   Compiling traitobject v0.0.1
   Compiling gcc v0.3.8
   Compiling pkg-config v0.3.5
   Compiling lazy_static v0.1.11
   Compiling rustc-serialize v0.3.15
   Compiling httparse v0.1.4
   Compiling unicase v0.1.0
   Compiling regex-syntax v0.1.2
   Compiling libc v0.1.8
   Compiling matches v0.1.2
   Compiling typeable v0.1.2
   Compiling bitflags v0.1.1
   Compiling time v0.1.26
   Compiling openssl-sys v0.6.2
   Compiling memchr v0.1.3
   Compiling log v0.3.1
   Compiling num_cpus v0.2.6
   Compiling aho-corasick v0.1.3
   Compiling mime v0.0.11
   Compiling hpack v0.2.0
   Compiling regex v0.1.35
   Compiling openssl v0.6.2
   Compiling solicit v0.2.0
   Compiling env_logger v0.3.1
   Compiling url v0.2.35
   Compiling cookie v0.1.21
   Compiling hyper v0.5.2 (file:///Users/user/oss/hyperium/hyper)
error: linking with `cc` failed: exit code: 1
note: "cc" "-m64" "-L" "/Users/user/.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/Users/user/oss/hyperium/hyper/target/debug/examples/client" "/Users/user/oss/hyperium/hyper/target/debug/examples/client.o" "-Wl,-force_load,/Users/user/.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib/libmorestack.a" "-Wl,-dead_strip" "-nodefaultlibs" "/Users/user/oss/hyperium/hyper/target/debug/libhyper.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libtypeable-10065b0bbdf3bed9.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libunicase-29c711cff0d04b16.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libsolicit-cd95e739c5df31f7.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libmime-e3d384f950d18291.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libhttparse-7ecdaf5da0017654.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libhpack-0002de409367b417.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libnum_cpus-d64cdaf0c78cf4e8.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libtraitobject-dc1e70e5c4501fdd.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libenv_logger-63352e48193fbb80.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libregex-8de7cf8d3c57f864.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libregex_syntax-8db057a1d27b1529.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libaho_corasick-02c11d7f79c63f6b.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libmemchr-ce56c6a379c614cd.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/liblog-54cf393d3c69686f.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libcookie-ac7973d866daef44.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/liburl-a4f53e129e04fc84.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/librustc_serialize-0e2cbfb69293d88f.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libtime-f08bec52f4924e95.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libmatches-68db25b520030534.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libopenssl-a36d86f1beea2185.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libbitflags-518ea12e21428edd.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/liblazy_static-7e1b752366784e2f.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/libopenssl_sys-5040130ff99796a0.rlib" "/Users/user/oss/hyperium/hyper/target/debug/deps/liblibc-2eda841eb12a3090.rlib" "/Users/user/.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib/libstd-4e7c5e5c.rlib" "/Users/user/.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib/libcollections-4e7c5e5c.rlib" "/Users/user/.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib/libunicode-4e7c5e5c.rlib" "/Users/user/.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib/librand-4e7c5e5c.rlib" "/Users/user/.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib/liballoc-4e7c5e5c.rlib" "/Users/user/.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib/liblibc-4e7c5e5c.rlib" "/Users/user/.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib/libcore-4e7c5e5c.rlib" "-L" "/Users/user/oss/hyperium/hyper/target/debug" "-L" "/Users/user/oss/hyperium/hyper/target/debug/deps" "-L" "/usr/lib" "-L" "/Users/user/oss/hyperium/hyper/target/debug/build/openssl-sys-5040130ff99796a0/out" "-L" "/Users/user/oss/hyperium/hyper/target/debug/build/time-f08bec52f4924e95/out" "-L" "/Users/user/.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib" "-L" "/Users/user/oss/hyperium/hyper/.rust/lib/x86_64-apple-darwin" "-L" "/Users/user/oss/hyperium/hyper/lib/x86_64-apple-darwin" "-lssl" "-lcrypto" "-lz" "-lc" "-lm" "-lSystem" "-lpthread" "-lc" "-lm" "-Wl,-rpath,@loader_path/../../../../../../.multirust/toolchains/stable/lib/rustlib/x86_64-apple-darwin/lib" "-Wl,-rpath,/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lcompiler-rt"
note: ld: warning: directory not found for option '-L/Users/user/oss/hyperium/hyper/.rust/lib/x86_64-apple-darwin'
ld: warning: directory not found for option '-L/Users/user/oss/hyperium/hyper/lib/x86_64-apple-darwin'
Undefined symbols for architecture x86_64:
  "_TLSv1_2_method", referenced from:
      ssl::SslMethod::to_raw::h7b8cbd53c0831aeeOLc in libopenssl-a36d86f1beea2185.rlib(openssl-a36d86f1beea2185.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by seanmonstar** [comment]
Hrm, no idea. Try the rust-openssl repo?

**Comment by winding-lines** [comment]
@seanmonstar good call, the tests are failing in rust-openssl.

{code}
 cargo test
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading byteorder v0.3.10
 Downloading connected_socket v0.0.6
 Downloading bitflags v0.2.1
   Compiling byteorder v0.3.10
   Compiling rustc-serialize v0.3.15
   Compiling gcc v0.3.8
   Compiling libc v0.1.8
   Compiling pkg-config v0.3.5
   Compiling bitflags v0.2.1
   Compiling lazy_static v0.1.11
   Compiling time v0.1.26
   Compiling openssl-sys v0.6.2 (file:///Users/use/oss/hyperium/rust-openssl/openssl)
   Compiling openssl v0.6.2 (file:///Users/user/oss/hyperium/rust-openssl/openssl)
   Compiling connected_socket v0.0.6
     Running target/debug/openssl-b3a0b1bcbf1488a6

running 61 tests
test bn::tests::test_to_from_slice ... ok
test bn::tests::test_negation ... ok
test crypto::hash::tests::test_clone ... ok
test crypto::hash::tests::test_finish_twice ... ok
test crypto::hash::tests::test_md5_recycle ... ok
test crypto::hash::tests::test_md5 ... ok
test crypto::hash::tests::test_sha1 ... ok
test crypto::hash::tests::test_ripemd160 ... ok
test crypto::hash::tests::test_sha256 ... ok
test crypto::hmac::tests::test_clone ... ok
test crypto::hmac::tests::test_finish_twice ... ok
test crypto::hmac::tests::test_hmac_md5 ... ok
test crypto::hmac::tests::test_hmac_md5_recycle ... ok
test crypto::hmac::tests::test_hmac_sha1 ... ok
test crypto::hmac::tests::test_hmac_sha1_recycle ... ok
test crypto::hmac::tests::test_hmac_sha224 ... ok
test crypto::hmac::tests::test_hmac_sha256 ... ok
test crypto::memcmp::tests::test_diff_lens ... ok
test crypto::memcmp::tests::test_eq ... ok
test crypto::hmac::tests::test_hmac_sha384 ... ok
test crypto::hmac::tests::test_hmac_sha512 ... ok
test crypto::pkey::tests::test_encrypt ... ok
test crypto::pkey::tests::test_encrypt_pkcs ... ok
test crypto::pkey::tests::test_gen_priv ... ok
test bn::tests::test_prime_numbers ... ok
test crypto::pkey::tests::test_private_key_from_pem ... ok
test crypto::pkey::tests::test_eq ... ok
test crypto::pkey::tests::test_gen_pub ... ok
test crypto::rand::tests::test_rand_bytes ... ok
test crypto::symm::tests::test_aes_256_cbc_decrypt ... ok
test crypto::symm::tests::test_aes_256_ecb ... ok
test crypto::symm::tests::test_rc4 ... ok
test ssl::error::test_uknown_error_should_have_correct_messages ... ok
test ssl::tests::clear_ctx_options::sslv23 ... FAILED
test ssl::tests::get_ctx_options::sslv23 ... FAILED
test ssl::tests::get_peer_certificate::sslv23 ... FAILED
test ssl::tests::new_ctx::sslv23 ... FAILED
test ssl::tests::new_sslstream::sslv23 ... FAILED
test ssl::tests::set_ctx_options::sslv23 ... FAILED
test ssl::tests::test_pending ... FAILED
test ssl::tests::test_read ... FAILED
test crypto::pkey::tests::test_sign_hashes ... ok
test ssl::tests::test_write ... FAILED
test ssl::tests::test_set_certificate_and_private_key ... ok
test ssl::tests::verify_callback_data::sslv23 ... FAILED
test ssl::tests::verify_callback_load_certs::sslv23 ... FAILED
test ssl::tests::verify_trusted::sslv23 ... FAILED
test ssl::tests::verify_trusted_callback_override_bad::sslv23 ... FAILED
test ssl::tests::verify_trusted_callback_override_ok::sslv23 ... FAILED
test ssl::tests::verify_trusted_get_error_err::sslv23 ... FAILED
test ssl::tests::verify_trusted_get_error_ok::sslv23 ... FAILED
test ssl::tests::verify_untrusted::sslv23 ... FAILED
test ssl::tests::verify_untrusted_callback_override_bad::sslv23 ... FAILED
test ssl::tests::verify_untrusted_callback_override_ok::sslv23 ... FAILED
test x509::test_negative_serial ... ok
test ssl::tests::test_write_hits_stream ... ok
test x509::tests::test_cert_loading ... ok
test x509::tests::test_subject_read_cn ... ok
test crypto::pkey::tests::test_sign ... ok
test x509::tests::test_cert_gen ... ok
test crypto::pkcs5::tests::test_pbkdf2_hmac_sha1 ... ok

failures:

---- ssl::tests::clear_ctx_options::sslv23 stdout ----
	thread 'ssl::tests::clear_ctx_options::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::get_ctx_options::sslv23 stdout ----
	thread 'ssl::tests::get_ctx_options::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::get_peer_certificate::sslv23 stdout ----
	thread 'ssl::tests::get_peer_certificate::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::new_ctx::sslv23 stdout ----
	thread 'ssl::tests::new_ctx::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::new_sslstream::sslv23 stdout ----
	thread 'ssl::tests::new_sslstream::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::set_ctx_options::sslv23 stdout ----
	thread 'ssl::tests::set_ctx_options::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::test_pending stdout ----
	thread 'ssl::tests::test_pending' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::test_read stdout ----
	thread 'ssl::tests::test_read' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::test_write stdout ----
	thread 'ssl::tests::test_write' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_callback_data::sslv23 stdout ----
	thread 'ssl::tests::verify_callback_data::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_callback_load_certs::sslv23 stdout ----
	thread 'ssl::tests::verify_callback_load_certs::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_trusted::sslv23 stdout ----
	thread 'ssl::tests::verify_trusted::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_trusted_callback_override_bad::sslv23 stdout ----
	thread 'ssl::tests::verify_trusted_callback_override_bad::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_trusted_callback_override_ok::sslv23 stdout ----
	thread 'ssl::tests::verify_trusted_callback_override_ok::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_trusted_get_error_err::sslv23 stdout ----
	thread 'ssl::tests::verify_trusted_get_error_err::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_trusted_get_error_ok::sslv23 stdout ----
	thread 'ssl::tests::verify_trusted_get_error_ok::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_untrusted::sslv23 stdout ----
	thread 'ssl::tests::verify_untrusted::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_untrusted_callback_override_bad::sslv23 stdout ----
	thread 'ssl::tests::verify_untrusted_callback_override_bad::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_untrusted_callback_override_ok::sslv23 stdout ----
	thread 'ssl::tests::verify_untrusted_callback_override_ok::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729



failures:
    ssl::tests::clear_ctx_options::sslv23
    ssl::tests::get_ctx_options::sslv23
    ssl::tests::get_peer_certificate::sslv23
    ssl::tests::new_ctx::sslv23
    ssl::tests::new_sslstream::sslv23
    ssl::tests::set_ctx_options::sslv23
    ssl::tests::test_pending
    ssl::tests::test_read
    ssl::tests::test_write
    ssl::tests::verify_callback_data::sslv23
    ssl::tests::verify_callback_load_certs::sslv23
    ssl::tests::verify_trusted::sslv23
    ssl::tests::verify_trusted_callback_override_bad::sslv23
    ssl::tests::verify_trusted_callback_override_ok::sslv23
    ssl::tests::verify_trusted_get_error_err::sslv23
    ssl::tests::verify_trusted_get_error_ok::sslv23
    ssl::tests::verify_untrusted::sslv23
    ssl::tests::verify_untrusted_callback_override_bad::sslv23
    ssl::tests::verify_untrusted_callback_override_ok::sslv23

test result: FAILED. 42 passed; 19 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libtest/lib.rs:259
{code}

**Comment by sfackler** [comment]
The version of openssl that ships with OSX is v0.9.8zd, which does not include TLSv1.2 support. As a result, TLSv1.2 bindings are opt-in in rust-openssl via the `tlsv1_2` Cargo feature: https://github.com/sfackler/rust-openssl/blob/master/openssl/Cargo.toml#L13. If you want to use it, you'll need to install a newer copy of openssl and link to that instead.

**Comment by winding-lines** [comment]
@sfackler thanks for the pointers! The hyper library is intended to be used by other people, so I don't feel that just installing a different openssl library on my computer is sufficient.

It's unclear to me how to use features, I tried the following but I get the same error.

```
[dependencies.openssl]
version = "0.6"
features = ["tlsv1_1"]
```

It feels to me that the best approach would be to detect which library is available and then enable one feature or the other. 

Do you know of any client of your library doing something similar.

**Comment by seanmonstar** [comment]
I'm surprised actually. @reem develops on a macbook, and I must assume it's
been working for him...

**Comment by reem** [comment]
I use a later version of openssl then what ships with OS X (from brew), so I didn't have this problem.

**Comment by seanmonstar** [comment]
I've actually been working a bunch on a patch that changes up the design of Ssl usage, to facilitate using different ssl libraries, and disabling ssl altogether. I hope to have that finished tomorrow.

**Comment by winding-lines** [comment]
Sounds good, I can always brew a newer ssl library in the mean time.

**Comment by seanmonstar** [comment]
The new ssl merged, so if it's causing issues, you can disable the "feature".
