### ISSUE TITLE
Hyper is not listed as an HTTP/2 implementation!

### ISSUE THREAD

**Issue by bagder** [hyperium/hyper#585]
Please add it here: https://github.com/http2/http2-spec/wiki/Implementations

**Comment by seanmonstar** [comment]
The actual http2 bits are from the solicit crate, not actually hyper itself.

**Comment by Aintaer** [comment]
As far as I can tell, hyper only has the http2 client wrapper around solicit. There's no server implementation.

I took a whack at it, but ran into some conceptual difficulties.
Right now, `server::Server` only deals with `net::HttpListener`s, which in turn wraps around `TcpListener`. This makes the assumption that an `HttpListener` is a one-to-one correlation with a tcp connection, which is true of http1, but not in the multiplexed world of http2.
Additionally, `server::Handler` has a singular tuple of `(Request, Response)`, but http2 allows for, essentially, multiple `Response`s.

Would love to see/hack on a Rust implementation of http2! (Or at least a wrapper around solicit)
