### ISSUE TITLE
HTTPS server support

### ISSUE THREAD

**Issue by coder543** [hyperium/hyper#586]
Has the option to run an https server off of hyper been removed in the latest version because of all of the SSL restructuring? You used to simply be able to specific a certificate and a key and have an https server running. It was pretty convenient. If it has been removed, is it planned to be added back in soon?

**Comment by seanmonstar** [comment]
It is not removed, just requires that you pick a Ssl implementation
yourself. You can use the Openssl one, and it includes a function to accept
a cert and key. http://hyper.rs/hyper/hyper/net/struct.Openssl.html

**Comment by coder543** [comment]
alright, thanks!
