### ISSUE TITLE
Utilize travis-cargo for travis config file

### ISSUE THREAD

**Issue by frewsxcv** [hyperium/hyper#588]
In my opinion, the travis.yml file is a little messy with the kcov installing and GitHub pages uploading.

There's a tool available called [traivs-cargo](https://github.com/hyperium/hyper/blob/master/.travis.yml) which aims to make this easier.

If this sounds like a good idea, I can open a PR to utilize it

**Comment by seanmonstar** [comment]
Yea, travis-cargo didn't exist when I fiddled around and made the build matrix and docs uploading work. I'm not too worried about it's current messiness, but am not opposed to cleaner things as long as the following can be handled:

1. kcov can be used without `sudo`, but travis-cargo doesn't yet do that.
2. I'm working on uploading docs to a path based on the minor version, and no longer destroying the gh-pages on each push.

**Comment by frewsxcv** [comment]
> kcov can be used without sudo, but travis-cargo doesn't yet do that.

https://huonw.github.io/blog/2015/06/travis-cargo-0.1.3/

**Comment by seanmonstar** [comment]
Have been working on a per-version doc upload script, so I'll just close this.
