### ISSUE TITLE
Compile error due to openssl on Linux

### ISSUE THREAD

**Issue by Ivo-Balbaert** [hyperium/hyper#591]
Building a hyper project on Ubuntu 14  64 bit, Rust nightly 1.3, does not work at this moment because there seems to be a problem compiling the crate openssl:

On Ubuntu 14, Rust nightly 1.3 I get the following error:
ivo@ivo-SATELLITE-L50D-B:~/rust_programs/using_hyper$ cargo build
   Compiling url v0.2.35
   Compiling openssl-sys v0.6.3
   Compiling solicit v0.4.0
   Compiling time v0.1.26
Build failed, waiting for other jobs to finish...
failed to run custom build command for `openssl-sys v0.6.3`
Process didn't exit successfully: `/home/ivo/rust_programs/using_hyper/target/debug/build/openssl-sys-f1940735b7e345d7/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-flags= -l dylib=crypto -l dylib=ssl
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
CARGO_MANIFEST_DIR = Some("/home/ivo/.cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.3")
OUT_DIR = Some("/home/ivo/rust_programs/using_hyper/target/debug/build/openssl-sys-f1940735b7e345d7/out")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
debug 0
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
running: "cc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "/home/ivo/.cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.3/src/old_openssl_shim.c" "-o" "/home/ivo/rust_programs/using_hyper/target/debug/build/openssl-sys-f1940735b7e345d7/out/src/old_openssl_shim.o"

command did not execute successfully, got: exit code: 1

--- stderr
/home/ivo/.cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.3/src/old_openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
 #include <openssl/hmac.h>
                          ^
compilation terminated.
thread '<main>' panicked at 'explicit panic', /home/ivo/.cargo/registry/src/github.com-0a35038f75765ae4/gcc-0.3.8/src/lib.rs:497

Thanks,
Ivo

**Comment by Arrem** [comment]
Same issue on Windows 8.1 using Rust 1.1

**Comment by seanmonstar** [comment]
It'd be worth knowing what version of openssl you have installed on your machine. As for solutions, I can think of 2:

1. I noticed that https://github.com/sfackler/rust-openssl has seen a few commits after v0.6.3 regarding hmac, so you could try pinning to the git version using `.cargo/config`, and/or reporting errors on the openssl repo.
2. Also, if you do not with to use openssl at all, you can disable the `ssl` feature: https://github.com/hyperium/hyper/blob/990819a6d667161f494882117af243cdd1fcdf3a/Cargo.toml#L43

**Comment by seanmonstar** [comment]
Looking more, it seems likely the header files aren't installed. See the [README](https://github.com/sfackler/rust-openssl#building) regarding building openssl.

**Comment by Ivo-Balbaert** [comment]
Thanks Sean that was the solution!

 

Ivo
