### ISSUE TITLE
Allow passing a local address to a http request.

### ISSUE THREAD

**Issue by muja** [hyperium/hyper#602]
If I am connected to the internet with multiple network interfaces, I want to be able to specify which one hyper should use - basically, which local address it should use to connect to the web.

Is this possible already?

**Comment by seanmonstar** [comment]
Hm, interesting question. Looking at the TcpStream docs, it doesn't seem to
be exposed any way. Worth a look around in here to see what would be
needed, and propose an RFC to rust-lang
https://github.com/rust-lang/rust/blob/master/src/libstd/sys/common/net.rs

**Comment by seanmonstar** [comment]
This can be done thanks to #622
