### ISSUE TITLE
How to send Authorization: Token token=blah

### ISSUE THREAD

**Issue by arnm** [hyperium/hyper#604]
I need to send `Authorization:Token token=blah` header. How could I do it?

Can the current [Authorization header implementation](http://hyper.rs/hyper/hyper/header/struct.Authorization.html) do this?

**Comment by reem** [comment]
Yes, you'll need to implement the `Scheme` trait (http://hyper.rs/hyper/hyper/header/trait.Scheme.html) with the scheme name ("Token") and format.

**Comment by reem** [comment]
Then you can use that type with the Authorization header type, which is generic over Schemes.

**Comment by arnm** [comment]
Thanks. That worked.

For those who need to do something similar:

```rust

#[derive(Clone, PartialEq, Debug)]
///Token holder for Token Authentication, most often seen with oauth
pub struct Token {
        ///Actual bearer token as a string
        pub token: String
}

impl Scheme for Token {
        fn scheme() -> Option<&'static str> {
                Some("Token")
        }

        fn fmt_scheme(&self, f: &mut fmt::Formatter) -> fmt::Result {
                write!(f, "token={}", self.token)
        }
}

impl FromStr for Token {
        type Err = error::Error;
        fn from_str(s: &str) -> error::Result<Token> {
                Ok(Token { token: s.to_owned()})
        }
}
```

Then I could pass this `Token` into `Authorization`:

```rust
    let mut headers = Headers::new();
    headers.set(
        Authorization(
            Token {
                token: "blah".to_owned()
            }
        )
    );
```

**Comment by reem** [comment]
@arnm there's a little bit of a bug in your `FromStr` impl, it will make the token include `token=`.

**Comment by arnm** [comment]
@reem That was the only way I got it to work.

This is the curl command I need to replicate in Rust: `curl -H "Authorization: Token token=token" -X GET -G "http://domain.com"`

**Comment by reem** [comment]
@arnm it will work when sending `Authorization<Token>`s but not when receiving them.

**Comment by arnm** [comment]
@reem ya the FromStr implementation is wrong but I actually only making requests so I don't even need it.
