### ISSUE TITLE
[doc][client] Client request methods return value

### ISSUE THREAD

**Issue by DoumanAsh** [hyperium/hyper#605]
According to documentation request methods of client return ```RequestBuilder<U>``` -> http://hyper.rs/hyper/hyper/client/struct.Client.html#method.get 
But it is actually ```Result(Response)```

I'm not sure why it is so, but it looks strange when you see examples and when you see actual documentation for these methods.

Is it wrong or am i missing something?

**Comment by DoumanAsh** [comment]
It is not actually doc issue, but function signature issue i suppose?

**Comment by seanmonstar** [comment]
Not an issue. Most examples include calling the send() method, which is
what returns the Response.
