### ISSUE TITLE
Specifying Common Request Data

### ISSUE THREAD

**Issue by arnm** [hyperium/hyper#608]
I'm looking for a way to be able to specify a subset of a request with some common data every request I'm going to make will require. For example, every request should have `ContentType::json())` header and specific query parameters set.

I'm mainly coming from a Java background where we have [rest-assured](https://code.google.com/p/rest-assured/wiki/Usage#Specifying_Request_Data) which makes these kinds of things easy. I really like the way it lets me specify common data and later on decide the type and destination of the request.

Is there anyway to do this currently?

**Comment by Ms2ger** [comment]
This might be useful for Servo; otoh, we'll probably channel all calls into hyper through a single point anyway.

**Comment by arnm** [comment]
So, I guess there is no way to do this currently? At least that is what I gathered from The `Client` implementation where you have to specify the request type and destination to get a `RequestBuilder` where you can specify all of the other things.

I would like for there to be no predetermined order of operations when defining a request. Meaning, I could specify the request data before specifying request type or vice versa. I think this allows for the most flexible interface and could bring performance improvement.

**Comment by reem** [comment]
@arnm you could probably apply most of the things iron does on the server to a client, namely modifiers, an extensions map, etc. A Modifier that you apply to every request basically does what you want.

**Comment by seanmonstar** [comment]
I've sometimes thought of the Client having a default_headers field, that
could accomplish this. But, I also noticed that most other http libraries
don't have this, so I've so far felt that this could be provided per app,
or perhaps in a separate crate...

**Comment by arnm** [comment]
@seanmonstar It's not only the header fields but I have noticed that most libraries do not offer this sort of API. I'm no sure why though. Anyways, If there is no interest in introduction something like this I guess this issue can be closed.
