### ISSUE TITLE
Specifying encoding in HTTP headers

### ISSUE THREAD

**Issue by k0pernicus** [hyperium/hyper#610]
Hi!
I ran the code in the README but i've found an error with the method 'read_to_string' for the response of the server : error: StringError("stream did not contain valid UTF-8").
So, I tried to custom the header (see below), but I don't find in the documentation a good way to add in the request this custom header...
Header:
```
let mut headers = Headers::new();
headers.set(
        AcceptCharset(vec![qitem(Charset::Ext("utf-8".to_owned()))])
);
...
let mut res = client.get("http://www.google.com")
                .header(headers) // ERROR HERE BECAUSE header() DOES NOT EXPECTED HEADERS...
                .send();
```
If anyone can help me please... Thank you!

**Comment by k0pernicus** [comment]
Ok, my bad - I not used ```headers(...)``` but ```header(...)```... (newbie here)

But, with that custom header, i don't receive again any UTF-8 response... :-/

**Comment by seanmonstar** [comment]
What headers do you receive back? What is the body of the response? An
image or file of some sort?
