### ISSUE TITLE
readme 2nd example: StringError not valid UTF-8

### ISSUE THREAD

**Issue by bsansouci** [hyperium/hyper#613]
Hey guys, I'm super noob and was trying to run the 2nd example but got an error. Here is the exact error I'm getting:

``` sh
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("stream did not contain valid UTF-8") }) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729
An unknown error occurred
```

I didn't change the example code, I just copy pasted it.

**Comment by bsansouci** [comment]
I noticed the typo in the url `"http://www.gooogle.com/"` but correcting it didn't change anything. It worked for `"http://www.reddit.com/"` for some reasons :p

**Comment by seanmonstar** [comment]
I've changed the example to download rust-lang.org.

**Comment by bsansouci** [comment]
Awesome :)

**Comment by Programming4life** [comment]
For anyone running into this problem: I ran into this same problem with ``"http://www.google.com/"`` and some other sites I did some digging and realized the response is gziped you have to decompress it fist thats why you get ``"stream did not contain valid UTF-8"``.

**Comment by jonfk** [comment]
@Programming4life  I got the same issue and I see why that is happening. I am wondering why hyper doesn't decompress the response transparently, I am guess it's to be more explicit about what is happening. Does hyper offer a way to decompress the gzipped response or do I have to get another library to do the decompression? 

Thanks if you can help.

Here is the code I am using:
```rust
extern crate hyper;

use hyper::client;
use std::io::Read;

fn main() {
    let client = client::Client::new();

    let mut res = client.get("https://www.google.com").send().unwrap();
    assert_eq!(res.status, hyper::Ok);
    let mut response_string = String::new();
    res.read_to_string(&mut response_string).unwrap();
    println!("{}", response_string);
}
```
