### ISSUE TITLE
Implement Hash for StatusCode

### ISSUE THREAD

**Issue by havarnov** [hyperium/hyper#614]
Implementing Hash for StatusCode will make it possible to use the status code as key in a HashMap.

I.e.:
 ```rust
let handlers: HashMap<StatusCode, Handler> = HashMap::new();
```

**Comment by jdm** [comment]
It's also possible to do `struct HashableStatusCode(StatusCode)` and implement Hash on that.

**Comment by havarnov** [comment]
Yes, but you'd also had to implement `Deref` for `HashableStatusCode`. Not a big deal, but a little smoother IMO.

I've submitted a pull request, so it's up to you if you think it's useful.
