### ISSUE TITLE
Changing the source IP address of the request

### ISSUE THREAD

**Issue by filsmick** [hyperium/hyper#620]
Is it possible to change the source IP addresse of a request? I need to choose which of the 16 IPv6 addresses of my server to use for a request, dynamically.

**Comment by seanmonstar** [comment]
I think this can be solved using the `TcpBuilderConnector` that is in #618. I've restarted those tests, and will merge once green.

**Comment by muja** [comment]
https://github.com/hyperium/hyper/pull/622 with this pull request it's possible now, filsmick: Add the net2 crate as a dependency, and follow the example that I've provided.
