### ISSUE TITLE
How to set ContentType for client.post(..).send(...)

### ISSUE THREAD

**Issue by GildedHonour** [hyperium/hyper#628]
I want to set `ContentType = application/x-www-form-urlencoded` for a **request**. I wonder, why do **all** the examples in the documentation show how to set headers **only** and not how to set headers **and** send a request? For example:

1) Sending a request:
```
let res = client.post("url123").send().unwrap(); 
```
2) Setting headers:
```
let mut headers = Headers::new();
headers.set(Location("some location".to_owned());
```

But what's the point of showing how to set headers without making a request? How can I apply 2nd to 1st?

Anyway, how can I set `ContentType = application/x-www-form-urlencoded` and send a request using the code from 1)?

**Comment by Ryman** [comment]
To get you unstuck, this example should help: https://github.com/hyperium/hyper/blob/master/examples/client.rs

**Comment by GildedHonour** [comment]
you're right but in the examples throughout the code  we have header(s) created separately, whereas in that example one header created through fluid interface. So if we create  `let mut headers = Headers::new();` how to add them to the  `client`?

**Comment by GildedHonour** [comment]
In curl I can do this:
```
curl -d '{"key":"api key"} my url
```
and the same thing in Rust:

```
let res = client.post("my url")
      .body("key=api key")
      .send()
      .unwrap();
```

And how can I do this in Rust (nested keys and arrays)?
```
curl -d '{"key":"api key","key1":{"key2":"<p>fdsfdsfdsfdsfd<\/p>","key3":[{"key4":"fdsfdsfd","key5":"fdsfdsfd"}],"key5":{ and so on....

```

**Comment by Ryman** [comment]
@GildedHonour http://hyper.rs/hyper/hyper/client/struct.RequestBuilder.html#method.headers
```rust
let res = client.post("..")
                .headers(headers)
                .send()
                .unwrap()
```

For the second, you might want to look at http://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/fn.encode.html

**Comment by seanmonstar** [comment]
@GildedHonour the examples of headers are specifically only for how to create headers. You might be creating them for a `client::Request`, or for a `server::Response`. How to pass the headers along is the in the documentation for the relevant sections (client and server).

I don't see an actionable bug here, so I'm going to close this. If I'm wrong, let me know.
