### ISSUE TITLE
implement AsRef<str> for RequestUri

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#630]

**Comment by manuel-woelker** [comment]
I was trying to implement this today, but I hit a snag on the AbsoluteUri(Url) part. url::Url does not implement AsRef<str>, and there does not seem to be a way to get a cheap &str ref out of it.

Apparently I wasn't to first taking a stab at this, googling turned up this discussion, which looked very familiar:
http://stackoverflow.com/questions/32062866/how-to-use-the-lifetime-on-asref

But with the implementation of std::fmt::Display, UriRequest now also supports to_string(), which is probably sufficient.

**Comment by seanmonstar** [comment]
Ah good point, it won't be possible to get `AsRef<str>` working for `Url`, since it's split the data among multiple `String`s. There's no way to get a simple reference, since there's no contiguous String.
