### ISSUE TITLE
Server Request SSL Stream

### ISSUE THREAD

**Issue by andrewgross** [hyperium/hyper#633]
Having some issues getting access to the SSL Stream for an HTTPS request.  I am using the example code, though it still seems to be unhappy.  

On Rust 1.2, `hyper = "0.6.9"`

```rust
fn doc_ssl(req: hyper::server::Request) {
    let maybe_ssl = req.ssl::<SslStream>();
}

src/main.rs:105:31: 105:40 error: wrong number of type arguments: expected 1, found 0 [E0243]
src/main.rs:105     let maybe_ssl = req.ssl::<SslStream>();
                                              ^~~~~~~~~
```

It seems no matter how many type annotations I give, and how I try to `match` that it refuses to accept it.  Due to recent addition of this feature, I am not sure if is a bug, or if I am just unable to implement it correctly.  Apologies if this is a trivial issue, I am still quite new to rust.

**Comment by seanmonstar** [comment]
The SslStream from openssl has a type parameter. Try SslStream<HttpStream>.
