### ISSUE TITLE
Connection Header case insensitivity

### ISSUE THREAD

**Issue by mikedilger** [hyperium/hyper#635]
http://tools.ietf.org/html/rfc7230#section-6.1:

    ... "Connection options are case-insensitive." ...

I noticed that Apache Bench sends "Keep-Alive" and hyper misinterprets it

    DEBUG:hyper::server::request: Headers { Connection: Keep-Alive, Host: 192.168.66.62:8881, Accept: */*, User-Agent: ApacheBench/2.3, }
    TRACE:hyper::http: should_keep_alive( Http10, Some(Connection([ConnectionHeader(UniCase("Keep-Alive"))])) )

I think this may also apply to most other headers

**Comment by seanmonstar** [comment]
That's what the use of `UniCase` is for. However, I think the issue is in the parsing of the Connection header, in this case. Instead of being parsed as the `KeepAlive` variant, it's the `ConnectionHeader` variant.

**Comment by seanmonstar** [comment]
Specifically, this method: https://github.com/hyperium/hyper/blob/master/src/header/common/connection.rs#L28

Instead, it should do a couple comparisons instead of a `match`.

```rust
if s == KEEP_ALIVE {
// ...
} else if s == CLOSE {
// ...
}
```
With the constants being `UniCase("keep-alive")` and `UniCase("close")`.
