### ISSUE TITLE
Can't fix note: ld: cannot find -leay32

### ISSUE THREAD

**Issue by Programming4life** [hyperium/hyper#637]
I'm new to rust and cant seem to fix this error. When using this library.
`
note: ld: cannot find -leay32
`
I'm using the current stable release of rust(32Bit) along with Mingw-w64. Mingw-w64 is in the path environment variable.

**Comment by seanmonstar** [comment]
That's part of OpenSSL. You have 2 options resolving this:

1. Trying to get [rust-openssl](https://github.com/sfackler/rust-openssl) to properly compile.
2. Disable openssl in hyper, by adjusting your Cargo.toml to have `hyper = { version = "0.6", no-default-features = true }`.

**Comment by Programming4life** [comment]
@seanmonstar Adding `hyper = { version = "0.6", no-default-features = true }` doesn't fix it.

**Comment by retep998** [comment]
It should actually be
`hyper = { version = "0.6", default-features = false }`

**Comment by Programming4life** [comment]
Switched languages. Solved :)

**Comment by zoumi** [comment]
I think it a bug of rust-openssl ,you can put the libssl32.dll, and libeay32.dll to your:
target\debug\deps
or 
target\release\deps
to solve this problem temporarily.

**Comment by Maplicant** [comment]
Same issue happened to me on Windows 10, Rust 1.14.0 (nightly) (GNU). Does anyone know which version of libssl32 and libeay32 I have to use? I'm getting errors about the dll's being uncompatible with every dll I've tried,
