### ISSUE TITLE
Url paths not percent-encoded

### ISSUE THREAD

**Issue by cmbrandenburg** [hyperium/hyper#638]
Using `Url::path_mut()` to set path components individually doesn't result in a percent-encoded URI. For example:

    let mut u = hyper::Url::parse("http://www.example.com/").unwrap();
    u.path_mut().unwrap()[0] = "foo/bar".to_string();
    println!("{}", u);
    u.path_mut().unwrap()[0] = "foo?bar".to_string();
    println!("{}", u);

Output:

    http://www.example.com/foo/bar
    http://www.example.com/foo?bar

I expect to see:

    http://www.example.com/foo%2Fbar
    http://www.example.com/foo%3Fbar

Maybe I'm missing something here, but I don't see any workaround for this problem except to explicitly percent-encode path components in my own code.

    let mut u = hyper::Url::parse("http://www.example.com/").unwrap();
    u.path_mut().unwrap()[0] = "foo%2Fbar".to_string();
    println!("{}", u);
    u.path_mut().unwrap()[0] = "foo%3Fbar".to_string();
    println!("{}", u);

Yuk!

**Comment by seanmonstar** [comment]
Hm, that does seem gross. A brief glance in the docs doesn't show an
alternative. I'd recommend filing an issue on the Url repo:
https://github.com/servo/rust-url
