### ISSUE TITLE
RedirectPolicy should not follow unsafe methods

### ISSUE THREAD

**Issue by matthewkmayer** [hyperium/hyper#641]
The Hyper client doesn't resend the body when following redirect requests.  

Snippet of the issue:

```rust
let client = Client::new();
let payload_contents = "a test payload";
let result = client.request(Method::Put, "http://localhost:8080/").body(payload_contents).send().unwrap();
```

When testing with https://github.com/matthewkmayer/redirtester , I see this:

```
2015/08/31 14:07:29 In redirect, got a body of  a test payload
2015/08/31 14:07:29 After redirect, got a body of  
```

When testing the same program with Postman, I get:

```
2015/08/31 14:01:59 In redirect, got a body of  bleh1
2015/08/31 14:01:59 After redirect, got a body of  bleh1
```

Found when trying to follow a 307 redirect and the server responded with an error, stating the client computed payload SHA didn't match the server's calculated payload SHA.  They calculated an empty string.

My redirtester program has an OSX binary in there if you don't have Go installed.

**Comment by seanmonstar** [comment]
Looking in the [spec](https://tools.ietf.org/html/rfc7231#section-6.4), redirection of methods should only be done automatically for 'safe' methods, which PUT is not.

So, this would require config to explicitly redirect the method and payload even if `method.is_safe()` is false. Perhaps a modification to the `RedirectPolicy` enum. Also, this might be tricky with the body being a `Reader`. Once the body has been copied into the request body, it probably can't be re-read again...

**Comment by seanmonstar** [comment]
I agree on both accounts: the behavior should be adjusted, and document should be updated to reflect that adjustment.

It'd probably also be useful to improve the design of `FollowIf`, to provide enough information to implement a sort of `FollowUnsafe` that one requires. That'd need the `Method`, `Url`, and anything else?

**Comment by matthewkmayer** [comment]
A good first step would be to allow following all redirects.  

If I'm understanding right, you describe something more fine-grained where a user can specify to only follow certain verbs and destinations.  EG "only follow redirects for PUTs to this URL."  Is that right?

If so, that's more work and I'm not sure of what use cases it would be useful for.

**Comment by seanmonstar** [comment]
The `FollowIf` policy would actually need mutable access to headers as well. The `RedirectPolicy` cannot be used in servo yet, since depending on the method, some headers must be removed or added. They also keep track of every Url seen, so that redirect loops can be detected and aborted. But that's probably worth a separate issue, so the action here is a `FollowSafe` policy.

**Comment by matthewkmayer** [comment]
FYI in my project I switched to FollowNone and handled the redirect in my code.  I think that was the only option available to me due to signed header authorization that includes the destination host name.  Works like a charm!

**Comment by seanmonstar** [comment]
I'm removing `RedirectPolicy` in the async branch.
