### ISSUE TITLE
Server HTTP Method parsing error

### ISSUE THREAD

**Issue by fuchsnj** [hyperium/hyper#652]
I was able to reproduce an error where an "OPTIONS" request was parsed as "Extension("{}"OPTIONS)"

```rust
extern crate hyper;
use hyper::server::{Server, Request, Response};
use hyper::header;

fn hello(req: Request, mut res: Response) {
    println!("method: {:?}", req.method);
	res.headers_mut().set(header::AccessControlAllowOrigin::Any);
	if let Some(requested_headers) = req.headers.get::<header::AccessControlRequestHeaders>()
	.map(|h|h.0.clone()){
		res.headers_mut().set(header::AccessControlAllowHeaders(requested_headers));
	}
}

fn main(){
	Server::http("0.0.0.0:8081").unwrap()
	.handle(hello).unwrap();
}
```

If you run this code, and access the server from a browser console (something that will trigger a CORS pre-flight OPTIONS request), you will notice the first request is fine, but every other request is parsed incorrectly.

This is the output I get with 5 post requests:
```
method: Options
method: Post
method: Extension("\"{}\"OPTIONS")
method: Post
method: Extension("\"{}\"OPTIONS")
method: Post
method: Extension("\"{}\"OPTIONS")
method: Post
method: Extension("\"{}\"OPTIONS")
method: Post
```

I checked the HTTP request using Wireshark, and on the wire each request is identical.

**Comment by seanmonstar** [comment]
I imagine this occurs because the string `{}` is being posted as the request body, and then it's not being read in the `hello` handler. Hyper then wrongly continues the next request starting from those bytes.

**Comment by fuchsnj** [comment]
That seems to be correct. I am sending "{}" in the POST body

**Comment by seanmonstar** [comment]
Yep, just browsed the code, this is the case. See https://github.com/hyperium/hyper/issues/309

**Comment by fuchsnj** [comment]
Was able to fix this by making sure the request stream was read completely, closing as a duplicate of #309
