### ISSUE TITLE
Access-Control-Allow-Credentials header

### ISSUE THREAD

**Issue by fuchsnj** [hyperium/hyper#655]
the Access-Control-Allow-Credentials header is missing

http://www.w3.org/TR/2008/WD-access-control-20080912/#access-control-allow-credentials

ABNF:
```
Access-Control-Allow-Credentials: "Access-Control-Allow-Credentials" ":" "true"
```

**Comment by gsquire** [comment]
I can take a shot at this if nobody else has claimed it.

**Comment by brycefisher** [comment]
I'd like to tackle this one.

I started looking the spec, and I realized there is only ever one valid value for this header. For example, this value could never be false.

Given that invariant, I would probably want users to set this header without needing to pass in a bool. Ex:

```
extern crate hyper;

use hyper::header::{Headers, AccessControlAllowCredentials};

fn main() {
    let mut headers = Headers::new();
    headers.set(AccessControlAllowCredentials);

    // Do something with headers...
}
```

However, we probably would want to parse raw AccessControlAllowCredentials headers values of any case. For example an HTTP client should probably still parse this sort of response:

```
HTTP/1.1 200 Not Modified
// ...
AccessControlAllowCredentials:TrUE
```

**Comment by brycefisher** [comment]
Can't get tests to pass tonight...trying tomorrow:
https://github.com/brycefisher/hyper/commit/29c33f59586976ac87b8de1c38bcc48e89d4dcc8

**Comment by brycefisher** [comment]
Gave up on any casing

**Comment by Ryman** [comment]
@brycefisher You should be able to replicate something like this https://github.com/hyperium/hyper/blob/388ddf6f3b1ea734bc28f6b161bb9d52643d49a6/src/header/common/expect.rs#L47 

Good luck!

**Comment by brycefisher** [comment]
@Ryman oh nice, that's exactly what I was looking for!
