### ISSUE TITLE
RequestBuilder isn't very flexible

### ISSUE THREAD

**Issue by anowell** [hyperium/hyper#660]
I had wrapped `Client` and `RequestBuilder` in a client of my own just fine until I had a reason to add multipart support. The [multipart](https://crates.io/crates/multipart) crate really expects you to implement everything with the lower-level `Request` type. I started down that road, but I found myself basically reinventing RequestBuilder which was a lot of overhead for one extra feature that could conceivably fit into the `RequestBuilder` paradigm. I tried to get [multipart to play nice with RequestBuilder](https://github.com/cybergeek94/multipart/issues/23), but hit too many walls. Notably the way that all RequestBuilder methods consume self (and return it) proved too inflexible in that particular case.

It seems to me that if `RequestBuilder` methods just borrowed self mutably (and returned that mutable reference) you could still achieve the ergonomics of the builder pattern while making it more flexible to work with. Am I overlooking some obvious reason why that would be a bad idea?

**Comment by seanmonstar** [comment]
Indeed, the builder pattern kinda sucks both ways in Rust. When using `&mut self`, you get 2 annoying issues:

- `let builder = Builder::new().set_foo(1).set_bar(2)` ends up with `foo` being `&mut Builder`, pointing at a value that has been dropped (the compiler complains the original value doesn't live long enough).
- `let foo = builder.set_foo(1).consume()` You cannot chain into the consume method, since all those methods return `&mut self`, and to end, `self` is required.

This ends up requiring that you split into at minimum three lines:

```rust
let builder = Builder::new();
builder.set_foo(1).set_bar(2);
let foo = builder.consume();
```

**Comment by anowell** [comment]
Thanks. That's helpful, and at least helps me understand the tradeoff that was made for `RequestBuilder`.

**Comment by reem** [comment]
@anowell a possible solution to this problem is through something like modifiers (github.com/reem/rust-modifier, shameless plugs!) which allow you to define the modification once then apply it as both `self -> Self` and `&mut self -> &mut Self`.

**Comment by seanmonstar** [comment]
@reem yea, i was actually looking at that crate last night when answering this. Only thing I dislike is that it requires a bunch more imports to use the `RequestBuilder`.

From:

```rust
let res = client.get(url).header(foo).header(bar).body("baz").send();
```

To:

```rust
let res = client.get(url).set(Header(foo)).set(Header(bar)).set(Body("baz")).send();
```

**Comment by reem** [comment]
Very true, it's certainly a tradeoff. The type-driven nature can also be confusing in generic contexts.

**Comment by reem** [comment]
The ergonomics are nice though because you can define new modifiers outside of the crate that defines the type being modified, so others could publish their own extensions to the RequestBuilder interface.

**Comment by cybergeek94** [comment]
Can `RequestBuilder` have a method that consumes it and creates a writable HTTP-stream that `multipart` can write to?

**Comment by seanmonstar** [comment]
Maybe. Some of what happens in Client is redirect policy stuff, which I felt logically was separate from the `Request` class.

**Comment by seanmonstar** [comment]
`RequestBuilder` has been removed in master.
