### ISSUE TITLE
Error while compiling hyper 0.6.15 with last version of nickel.rs

### ISSUE THREAD

**Issue by myabdelis** [hyperium/hyper#663]
Hello,

First of all, I'd like to thank you all of the creators of Rust and all of its libraries.

I have caught some errors while I have been building a project with a nickel.rs dependency (version 0.7.0) . 
![error](https://cloud.githubusercontent.com/assets/15084683/10423177/01a7b076-70c4-11e5-845a-2423fa7d5a78.png)
I did an `cargo update`, change the version of Hyper, ... but it's the same thing :(

I didn't know if I should post an issue here or in the nickel.rs repository, so that's why I am here.

Thank you very much :)

PS : Here is my Cargo project configuration :

```
[package]
name = "nickel-demo"
version = "0.1.0"
authors = ["Me"]

[dependencies.nickel]
version = "*"
git = "https://github.com/nickel-org/nickel.rs"

[dependencies.hyper]
version = "*"
git = "https://github.com/hyperium/hyper"
```

The git adresses are modified. Even if I comment those lines, it will be the same result : 9 errors as listed before in the screenshot.

**Comment by myabdelis** [comment]
Here is my Cargo project configuration :

```
[package]
name = "nickel-demo"
version = "0.1.0"
authors = ["Me"]

[dependencies.nickel]
version = "*"
git = "https://github.com/nickel-org/nickel.rs"

[dependencies.hyper]
version = "*"
git = "https://github.com/hyperium/hyper"
```

The git adresses are modified. Even if I comment those lines, it will be the same result : 9 errors as listed before in the screenshot.

**Comment by mlalic** [comment]
You probably need to update your `rustc` to the latest stable version (1.3.0), as that's when the `Duration` API [got stabilized](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-130-2015-09-17).

**Comment by seanmonstar** [comment]
Yea, this requires rust 1.3+.

It's unfortunate that this happened in a "patch" version, but prior to 1.0, all versions are pretty much shifted over one. Come hyper 1.0, I'd expect any change requiring a newer rustc to bump the minor version.

**Comment by myabdelis** [comment]
Thanks a lot guys !
