### ISSUE TITLE
Expires header doesn't accept "0" as value

### ISSUE THREAD

**Issue by untitaker** [hyperium/hyper#666]
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21

>HTTP/1.1 clients and caches MUST treat other invalid date formats, especially including the value "0", as in the past (i.e., "already expired"). 

I need to return "Expires: 0" to implement another RFC. Is there a possibility to do this without `set_raw`?

**Comment by seanmonstar** [comment]
Newer RFC: http://tools.ietf.org/html/rfc7234#section-5.3 . It says similar.

I don't see a way (for now) to do this without `set_raw`, or implementing your own `Expires` header. (All implementations that exist in hyper don't prevent custom implementations).

If there is great need, *maybe* Expires could be an `enum Expires { At(HttpDate), Past }`. Which RFC requires this?

**Comment by reem** [comment]
I think an enum might be reasonable, depending on how common this is.

**Comment by untitaker** [comment]
@seanmonstar To be fair, a *draft* requires it: https://datatracker.ietf.org/doc/draft-dejong-remotestorage/?include_text=1

The endpoints used are APIs, and caching is handled via ETag headers. I assume the requirement was primarily added to avoid leaking user data through cached responses.

**Comment by untitaker** [comment]
FWIW, google.de replies with `Expires: -1`.

**Comment by untitaker** [comment]
See also https://stackoverflow.com/questions/11357430/http-expires-header-values-0-and-1

**Comment by untitaker** [comment]
I've concluded that this is an edgecase. I don't think it's a priority to support right now, so I'll close this for now.
