### ISSUE TITLE
Separate path and query information in RequestUri.

### ISSUE THREAD

**Issue by krsnik02** [hyperium/hyper#667]
The `hyper::uri::RequestUri` enum currently defines a variant `AbsolutePath(String)` where the string is both the (required) path *and* optional query parameters. It would be better if these two parts were separated.

I suggest either defining it as `AbsolutePath(String, Optional<String>)` or creating a new struct, e.g.
```rust
enum RequestUri {
    AbsolutePath(QueryPath),
    \\ ...
}

struct QueryPath {
    path: String,
    query: Optional<String>,
}
```
similar to what is currently done for `AbsoluteUrl(Url)`.

**Comment by mikeycgto** [comment]
This looks like a duplicate (or is superseded by) #298

**Comment by seanmonstar** [comment]
Yep, the solution is described in #298
