### ISSUE TITLE
Multiple POST in one connection

### ISSUE THREAD

**Issue by nnovikov** [hyperium/hyper#668]
It's possible?
I try create one client and run post() many time. Hyper close connection and reopen it again. With  client.clone() code works in the same way.

**Comment by seanmonstar** [comment]
The Client does support connection pooling. To reuse an existing
connection, you must wait for the first connection to complete its request.
Also, there are some conditions that it won't reuse the connection:

- the server sent back 'Connection: close'
- there was an IO or http error while using the connection
- the response was not fully read, which would prevent parsing of the
second response.

**Comment by nnovikov** [comment]
Big tnx!
After res.read_to_string() I have what I want!
Hyper superb!
