### ISSUE TITLE
Is it possible to read client certificates in a server?

### ISSUE THREAD

**Issue by boghison** [hyperium/hyper#675]
I've been digging around the docs for this, but haven't found anything :(

**Comment by seanmonstar** [comment]
You can try to get a reference to the ssl stream, if you know what it is (by default, openssl's SslStream), and from there, its up to the implementation.

hyper.rs/hyper/hyper/server/request/struct.Request.html#method.ssl

**Comment by boghison** [comment]
Oh OK, thanks!
