### ISSUE TITLE
Request body should be allowed with GET/HEAD requests 

### ISSUE THREAD

**Issue by kaedroho** [hyperium/hyper#698]
Currently, the body is ignored when the request method is either GET or HEAD.

I had a look through the HTTP 1.1 spec and didn't find any mention of restricting request bodies to certian methods (http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3).

I have also seen this behaviour used in the wild. For example, Elasticsearch uses it for passing the search query when performing a search request (https://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-request-body.html).

Relevant code: https://github.com/hyperium/hyper/blob/master/src/server/request.rs#L44-L45
Introduced in: https://github.com/hyperium/hyper/commit/a60a67cd1e0a67c3348c34b4e3bd933557c07671

**Comment by jdm** [comment]
2616 has been [superseded](https://www.mnot.net/blog/2014/06/07/rfc2616_is_dead). See http://tools.ietf.org/html/rfc7231#section-4.3.2 for the relevant MUST NOT.

**Comment by kaedroho** [comment]
@jdm Thanks!

The excerpt you referenced refers to the body on HEAD _responses_. Here, I'm refering to the body on GET/HEAD _requests_. This is actually mentioned in that spec in a separate paragraph:

> A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.

"no defined semantics" does sound a little worrying, but nothing here disallows it.
