### ISSUE TITLE
Allow to specify the number of threads that l can handle incomming connection

### ISSUE THREAD

**Issue by musitdev** [hyperium/hyper#701]
I work on HTML5 SSE connection that never answer and block the listening thread on Hyper. On machine that has only one CPU, the server number of listening thread is 1 calculated from number of CPU:
server/mod.rs line 229 self.handle_threads(handler, num_cpus::get() * 5 / 4)
With this configuration, I can't handle any more connection when the SSE connection is started.
It will be interesting to add a way to force the min / max number of thread, or to add a new thread when all connection is busy or under specific condition, ....

**Comment by seanmonstar** [comment]
You can call 'handle_threads(handler, num)' to do exactly that.

**Comment by musitdev** [comment]
Sorry I didn't see it. I look the code to understand my problem and didn't think to look at the doc after.
