### ISSUE TITLE
Genericize TLS support

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#706]
Hyper currently supports TLS through an optional dependency on rust-openssl. As we all know, that library's a source of unending pain for people on not-Linux. I think we can make this world a bit less painful by altering Hyper to support other TLS implementations. As an example, I've done this in rust-postgres through a [`NegotiateSsl`](http://sfackler.github.io/rust-postgres/doc/v0.10.2/postgres/io/trait.NegotiateSsl.html) trait. The library has features that implement the trait for rust-openssl's [`SslContext`](http://sfackler.github.io/rust-openssl/doc/v0.7.3/openssl/ssl/struct.SslContext.html) as well as rust-security-framework's [`ClientBuilder`](http://sfackler.github.io/rust-security-framework/doc/v0.1.1/security_framework/secure_transport/struct.ClientBuilder.html). In the future when someone implements a library on top of SChannel or GnuTLS or whatever else, everything "just works" with the addition of one more trait implementation.

The nice thing about this setup is that most stuff built on top of rust-postgres only needs to know about `NegotiateSsl` trait objects and the end user gets to pick what TLS implementation they want.

**Comment by seanmonstar** [comment]
Something like this [`Ssl`](http://hyper.rs/hyper/hyper/net/trait.Ssl.html) trait?

**Comment by sfackler** [comment]
Ah, great!
