### ISSUE TITLE
Provide methods to split response into header and body so both can be borrowed independently

### ISSUE THREAD

**Issue by muja** [hyperium/hyper#710]
Borrowed response header prevents the body from being read - this becomes especially problematic if you need to read the body based upon header values e.g. Content-Length or Content-Encoding (which are quite common).

A possible solution is to provide a method that decouples both, possibly along these lines:

`let (headers, body) = response.split();`

**Comment by Gyscos** [comment]
Handlers get an owned `Response`, which implements [deconstruct](http://hyper.rs/hyper/hyper/server/response/struct.Response.html#method.deconstruct), is this not what you're looking for?

**Comment by seanmonstar** [comment]
The async API already provides `Response` and `&mut Decoder` separately, so I think this will be solved with that.
