### ISSUE TITLE
Client: timeout when unable to connect (link local address only?)

### ISSUE THREAD

**Issue by matthewkmayer** [hyperium/hyper#721]
When testing client side timeout for querying an AWS EC2 instance instance metadata, http://169.254.169.254/latest/meta-data/ on an EC2 instance, I found timeouts don't work all the time when setting the client read timeout.  This code, for a link local IP address, doesn't time out in 10ms as expected:

```rust
extern crate hyper;
extern crate chrono;

use hyper::Client;
use std::time::Duration;
use chrono::UTC;

fn main() {
  let mut client = Client::new();
  client.set_read_timeout(Some(Duration::from_millis(10)));
  println!("{} making request", UTC::now());
  match client.get("http://169.254.169.254/latest/meta-data/iam/security-credentials").send()
  {
      Err(why) => println!("{} Error: {:?}", UTC::now(), why),
      Ok(_) => println!("{} we're good.", UTC::now()),
  }
}
```

Outputs

```bash
2016-01-22 05:50:07.631185 UTC making request
2016-01-22 05:51:23.058323 UTC Error: Io(Error { repr: Os { code: 60, message: "Operation timed out" } })
```

Not the 10ms timeout expected.

If running against a different URL such as google.com it works as expected with the timeout.

My assumption is the request would return earlier for success or near the specified timeout value, like this curl command, run on my laptop:

```bash
$ curl -i --max-time 5 http://169.254.169.254/latest/meta-data/
curl: (28) Connection timed out after 5004 milliseconds
```

I'm not sure where in the network stack this issue is actually at, but if nothing else we can ensure the hyper docs show it won't time out for every case at the moment.

**Comment by seanmonstar** [comment]
This is because there's actually 1 more timeout we would want, but we cannot currently set using `std::net`. This would be the connect timeout, for resolving the DNS. Current `std::net` uses a blocking request [getaddrinfo](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/common/net.rs#L123), which doesn't have a way to specify a timeout.

Hopefully async resolve can be figured out and added in to the async version of hyper (when that comes out).

**Comment by matthewkmayer** [comment]
Is there a rust ticket for that?  I gave the existing issues, open and closed, a look and didn't see a relevant one.  I'd like to keep my eyes on that.

The ... happy path for our need for this timeout appears to work with the latest hyper release, thanks for your hard work!

**Comment by seanmonstar** [comment]
The is a connect timeout on master, so closing this.
