### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by ogham** [hyperium/hyper#722]
Hi, just a small note to say that there's a broken link in the hyper docs:

http://hyper.rs/hyper/hyper/header/struct.ContentType.html

The "Mime" in `pub struct ContentType(pub Mime);` points to `hyperium.github.io` rather than `hyper.rs`, and clicking it returns a 404 GitHub Pages page. It's being set by [this line](https://github.com/hyperium/hyper/blob/e8245aa7fb67ba767327fb709045f947979825ec/src/lib.rs#L1). I'm not sure what the consequences of changing that link will be, but just thought I'd point it out.

**Comment by seanmonstar** [comment]
Seems this isn't an issue anymore.
