### ISSUE TITLE
Implement Last-Event-ID header

### ISSUE THREAD

**Issue by KiChjang** [hyperium/hyper#723]
This is defined in the WHATWG HTML specification https://html.spec.whatwg.org/multipage/#last-event-id.

**Comment by puhrez** [comment]
I think this should be easy with the `header!` macro from what I read here: https://www.w3.org/TR/2011/WD-eventsource-20110310/, ctrl-f "Last-Event-ID header"

**Comment by seanmonstar** [comment]
The spec does a poor job of define exactly what it is, it's only ever mentioned briefly in paragraphs "if there is a last event id, set this header".

Is it basically just `struct LastEventId(pub String)`?

**Comment by puhrez** [comment]
that what it seems like

**Comment by KiChjang** [comment]
Fixed by #862.
