### ISSUE TITLE
GET body

### ISSUE THREAD

**Issue by nnovikov** [hyperium/hyper#724]
Please add the ability for send GET request with body. Some servers (elasticsearch for example) require this feature.
Simply, remove Method::Get from here:
http://hyper.rs/hyper/src/hyper/client/mod.rs.html#242-245

**Comment by ozten** [comment]
I think keeping `GET` and `HEAD`'s no body constraint is a good idea, to follow HTTP's standards.

According to elastic search's [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html), I think you can use `POST`.

> Both HTTP GET and HTTP POST can be used to execute search with body. Since not all clients support GET with body, POST is allowed as well.

**Comment by seanmonstar** [comment]
The [spec](https://tools.ietf.org/html/rfc7231#section-4.3.1) actually says that a payload is allowed:

> A payload within a GET request message has no defined semantics;
> sending a payload body on a GET request might cause some existing
> implementations to reject the request.

It says the same thing for `HEAD` requests. How horrid.

**Comment by seanmonstar** [comment]
@nnovikov I meant that you are right, the spec technically allows it. I just feel icky thinking about it.
