### ISSUE TITLE
Split server and client into separate crates

### ISSUE THREAD

**Issue by raindev** [hyperium/hyper#728]
Hyper would be more useful in form of two pluggable modules: client and server. Obviously one may need an HTTP client only. A server without need for an HTTP client is not impossible to imagine. Hyper could be used in such cases now but it would carry over all the unused dependencies together. And to not depend on what you aren't using is a very good idea.

**Comment by Victor-Savu** [comment]
I would go even further and suggest a 3-way split: `http` , `server` and `client`. The `hyper-http` crate would jut implement the protocol in a network-agnostic way.

**Comment by seanmonstar** [comment]
I'm going to close this in favor or #894, as there is more discussion there.
