### ISSUE TITLE
Make README server example warning-less

### ISSUE THREAD

**Issue by pandeiro** [hyperium/hyper#734]
While the Hello World server example compiles and works, for beginners it would probably be nicer to avoid producing warning output, e.g.:

> src/main.rs:26:5: 26:59 warning: unused result which must be used, #[warn(unused_must_use)] on by default
src/main.rs:26     Server::http("127.0.0.1:3000").unwrap().handle(hello);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

As I barely know Rust, I'm not even really able to understand why this is, or recommend a fix.

**Comment by seanmonstar** [comment]
Thanks for pointing this out. I've fixed it in https://github.com/hyperium/hyper/commit/63b2759e2fbf55dbf28289681d5fadc20f714138

For learning purposes, the warning is that `Server::handle` returns a `Result<(), hyper::Error>`, depending on if the spawning of the threads succeeded or failed. A common bug in applications is ignoring that an error occurred, so a default warning in Rust is that you should check what happened with a `Result`. In that commit, the solution is to `unwrap` the Result, which basically says "if the threads didn't spawn, we should panic." That may not be the best solution in all applications, but it works for an example.

**Comment by pandeiro** [comment]
Much appreciated, with the additional explanation. Very helpful.
