### ISSUE TITLE
buf_redux: The last buffer you'll ever need

### ISSUE THREAD

**Issue by cybergeek94** [hyperium/hyper#735]
I noticed I ended up duplicating some work [from this repo](https://github.com/hyperium/hyper/blob/master/src/buffer.rs) in [buf_redux](https://github.com/cybergeek94/buf_redux) (which I use in [multipart](https://github.com/cybergeek94/multipart)). Since we have the same need for an extensible `BufReader`, I figure, hey, why not just use `buf_redux` in Hyper? 

Once specialization lands, I'll be using it to [elide buffer zeroing for trusted `Read` impls](https://www.reddit.com/r/rust/comments/477gk3/the_specialization_rfc_has_just_been_accepted/d0badjn). It would be cool to have `UninitSafe` implemented by `server::Request` so this optimization will apply in `multipart`.

**Comment by seanmonstar** [comment]
buf_redux looks interesting! All my current work is trying to get the async IO support done, in the mio branch, which no longer uses a big BufReader.

**Comment by cybergeek94** [comment]
It'll be cool to see when that's done! I've been wanting to add support in `multipart` for `rotor`.

**Comment by seanmonstar** [comment]
Yes, synchronous I/O is being removed from hyper. A "hypersync" or similar crate will likely exist. I'm close to merging that into master, so I'm going to close this issue for now. Thanks for the suggestion though!
