### ISSUE TITLE
Add prefer header

### ISSUE THREAD

**Issue by calebmer** [hyperium/hyper#747]
I'd like to use the [`Prefer`](http://tools.ietf.org/html/rfc7240) header, could types for this header be added?

**Comment by seanmonstar** [comment]
This is the first I've heard of this header. Is there a situation where its usage is common?

**Comment by calebmer** [comment]
If you look at the [PostgREST](http://postgrest.com/api/reading/) project you'll see it's being used to suppress counts and in a few other cases. The [spec](http://tools.ietf.org/html/rfc7240#section-2.1) also gives some interesting examples. For my usage of like to explore the header in a scenario for style of response. For example: `Prefer: case=camel` or `Prefer: envelope`.

To me, the `Prefer` header represents the configuration of some niche behaviors.

**Comment by calebmer** [comment]
Basically it's an optional `Expect`.
