### ISSUE TITLE
Move hyper::header::Charset to mime crate

### ISSUE THREAD

**Issue by matt2xu** [hyperium/hyper#748]
I was a bit surprised to see that Charset has no UTF-8, 16, etc. variants. Given that at least UTF-8 is pretty common nowadays, why not include it in the Charset? UTF might be more useful than say the E/I versions of 8859-6 and 8 ;-)

If you agree, I could add the different UTF-\* variants: 7, 8, 16 + BE/LE, 32 + BE/LE. What do you think?

**Comment by seanmonstar** [comment]
I recall finding that weird as well, but I was also left wondering if this fit better into the `mime` crate, or here in hyper.

**Comment by matt2xu** [comment]
+1 for moving the Charset to the mime crate. It would improve it, too, as
we could replace the lone Utf8 charset Value by a Charset value. Hyper
would have to reexport Charset from mime for compatibility, right ?
Le 24 mars 2016 9:18 PM, "Sean McArthur" <notifications@github.com> a
écrit :

**Comment by puhrez** [comment]
This would be a PR against the ng branch yea?

**Comment by seanmonstar** [comment]
@puhrez probably, though I think I'd like to the get ng branch finished and merged to master first.

**Comment by puhrez** [comment]
fair fair

**Comment by seanmonstar** [comment]
For now, the new version of hyper won't be including the typed headers directly, so I'm closing this here as a won't fix.
