### ISSUE TITLE
Mio branch fails to build on ARM

### ISSUE THREAD

**Issue by nokaa** [hyperium/hyper#749]
I'm not sure how important the ARM architecture is to hyper, but I thought that you might want to know that mio, and by extension rotor, does not build on ARM. I have written a more detailed explanation [here](https://github.com/nokaa/cedalion#install), but basically it is due to [nix](https://github.com/nix-rust/nix) v0.4.2 failing to build on ARM.

To be certain, I attempted to build the `master` and `mio` branches of hyper on my server. The `master` branch builds properly, but the `mio` branch fails as expected.

Let me know if I can provide any more information.

**Comment by seanmonstar** [comment]
That's disappointing. The blocker here is that mio needs to update to nix@0.5?

**Comment by nokaa** [comment]
That is correct. It looks as though there is [an open pull request](https://github.com/carllerche/mio/pull/368) to fix this, so hopefully it will be remedied soon.

**Comment by seanmonstar** [comment]
With mio@0.5.1, seems this can closed.
