### ISSUE TITLE
header::internal::Item.to_string() does not handle multiple headers with the same key

### ISSUE THREAD

**Issue by PeterSP** [hyperium/hyper#754]
See https://gist.github.com/PeterSP/cfe911de5bcdeac823d66784abc68b92 for example:

```
Set-Cookie: foo
Set-Cookie: bar
```

gets turned into:

```
Set-Cookie: foobar
```

This also applies to the Debug `fmt` of `Item`, and thus of `Headers` and of `Response`.

Instead of:

```
... Set-Cookie: foo, Set-Cookie: bar, ...
```

fmt gets:

```
... Set-Cookie: foobar, ...
```

**Comment by mjkillough** [comment]
This seems to be working on master. A [similar program](https://gist.github.com/mjkillough/77310bba33d5bff5774a70fa2293af0d) now outputs:

```
hv.to_string() -> Set-Cookie: foo
Set-Cookie: bar
```

(Full output [is here](https://gist.github.com/mjkillough/77310bba33d5bff5774a70fa2293af0d#file-output))

**Comment by seanmonstar** [comment]
Thanks for noticing!
