### ISSUE TITLE
Incorporate rust-security-framework as backend for hyper::net::Ssl

### ISSUE THREAD

**Issue by frewsxcv** [hyperium/hyper#755]
https://github.com/sfackler/rust-security-framework

A potential remedy for https://github.com/hyperium/hyper/issues/709, https://github.com/servo/servo/issues/7930, https://github.com/servo/servo/issues/7888

Relevant conversation on #rust today with @seanmonstar and @sfackler:

>10:54 PM \<frewsxcv> sfackler: is there any reason why the hyper openssl backend couldn't be rewritten in rust-security-framework?
> 10:55 PM \<seanmonstar> frewsxcv: hyper has an Ssl trait that allows other ssl impls
>10:56 PM \<frewsxcv> seanmonstar: yeah, am looking at it now. it's more of a question about rust-security-framework and less-so about hyper
>10:56 PM — frewsxcv has never looked at OSX's Security Framework docs until now
>11:15 PM \<sfackler> seanmonstar: hyper's Ssl trait unfortunately doesn't play super nice with non-Openssl APIs. I've been meaning to file an issue about it, but it'd basically consist of splitting it into one trait for clients and one for servers
>11:29 PM \<sfackler> in something like secure transport, you create an SslContext for each connection, and have to pick at construction time if it's client or server side
>11:29 PM \<sfackler> there are then some builders to help cache configuration for client and server side stuff and handle some weird handshake logic: http://sfackler.github.io/rust-security-framework/doc/v0.1.3/security_framework/secure_transport/struct.ClientBuilder.html
>11:29 PM \<sfackler> but there isn't a unified one for servers and clients
>11:30 PM \<seanmonstar> sfackler: so the 1 associated Stream type is the problem? 
>11:30 PM \<sfackler> no, not that, the end result is an SslStream in both cases
>11:30 PM \<sfackler> the issue is that if you want to run clients, you're going to configure a ClientBuilder, but you then can't make server-side SslStreams
>11:30 PM \<sfackler> so half of the Ssl trait has to unconditionally fail
>11:31 PM \<sfackler> same for the server side
>11:36 PM \<seanmonstar> sfackler: so currently, a context would be an enum, and if it's ServerCtx when wrap_client is called, it'd return an Err (or panic)? 
>11:37 PM \<sfackler> probably just separate structs for the client and server side, but either way, yeah, one of the two wrap methods would not work
>11:56 PM \<frewsxcv> sfackler: why not just create two separate structs within the would-be 'security_framework' submodule within src/net.rs?
>11:57 PM \<sfackler> frewsxcv: I mean that's what would happen, but each of those structs could only actually support half of the trait they have to implement
>11:59 PM \<frewsxcv> oh, i understand
>12:01 AM \<seanmonstar> It'd work with an enum, but maybe it'd be better to split the traits... 
>12:01 AM \<frewsxcv> Ssl: SslServer + SslClient ?
>12:01 AM \<frewsxcv> wouldn't that also be backwards compatible?
>12:02 AM \<sfackler> you couldn't use SslServer or SslClient in hyper apis though
>12:03 AM \<sfackler> oh maybe blanket impls would let you
>12:03 AM \<sfackler> seems like it should

**Comment by frewsxcv** [comment]
Note to selves: if this ever happens, we should enable OSX on Travis CI.

**Comment by seanmonstar** [comment]
Note that while the current traits require the `Stream` to be `Clone`, this is not necessary on the mio branch.

**Comment by sfackler** [comment]
Looks like this is blocked until the `Clone` requirement is dropped.

**Comment by frewsxcv** [comment]
Update: this is now merged in https://github.com/hyperium/hyper/pull/762, but [OpenSSL is still the default on OS X](https://github.com/hyperium/hyper/blob/635622c37fa93e32fecb9378a8aab1e2117064d1/Cargo.toml#L52). In a future breaking change release, the default should probably switch to security-framework? Then https://github.com/hyperium/hyper/issues/709 could probably be closed (if not already).

On a side note, @sfackler started https://github.com/sfackler/rust-native-tls which is Yet Another Layer Of Abstraction that wraps around the system native TLS bindings. So Hyper could potentially use this to offload system TLS logic.

**Comment by seanmonstar** [comment]
I was wondering, is it possible to conditionally set the default based on
OS? Or would that require a separate crate to do it?

**Comment by frewsxcv** [comment]
> I was wondering, is it possible to conditionally set the default based on
OS? 

You can probably accomplish that with something like [this](https://github.com/sfackler/rust-native-tls/blob/master/Cargo.toml#L6)

**Comment by seanmonstar** [comment]
@frewsxcv yea, that's what I meant by using a separate crate. I'm not sure I can use those directives, and also have it be a feature that you can turn on or off.

**Comment by seanmonstar** [comment]
This is has landed, so closing.
