### ISSUE TITLE
mio branch: single thread?

### ISSUE THREAD

**Issue by daogangtang** [hyperium/hyper#767]
hi, I tested hyper mio branch, found that only one cpu occupied. Did hyper mio branch use only one thread now?

thx.

**Comment by seanmonstar** [comment]
Yes, a hyper server will create one event loop. If you'd like to use
multiple (which likely makes sense if you have many cores), you can spawn
multiple servers.

**Comment by daogangtang** [comment]
spawn multiple servers? listening the same port?

**Comment by seanmonstar** [comment]
Yep, you can definitely listen on the same port, the OS buffers incoming
sockets and hands them to the first listener that takes them.

**Comment by TileHalo** [comment]
And how multiple servers should be spawned? This code doesn't work
```rust
   pub fn listen(self) -> Vec<thread::JoinHandle<Result<Listening, Error>>> {
        let address = self.addr.to_string();
        let mut vec: Vec<thread::JoinHandle<Result<Listening, Error>>> = Vec::new();
        for _ in 0..num_cpus::get() * 4 {
            let handler: FabricHandler<'static, D> = self.handler.clone();
            let addr = address.clone();
            vec.push(thread::spawn(move||{
                Server::http(&addr.parse().unwrap()).unwrap().handle(move |_| handler.clone())
            }));
        }
        vec
    }
```
address is 0.0.0.0:3000

**Comment by seanmonstar** [comment]
What is the error? From looking it over, it looks correct...

**Comment by TileHalo** [comment]
Code 98, "Address already in use"

**Comment by bonifaido** [comment]
I think the option you are looking for is SO_REUSEPORT (which does load balancing between listeners only on Linux, on OSX the last opened listener receives all the traffic). If this option is not set down the line somewhere (hyper, rotor, mio, net2) it won't work. I guess it isn't.

**Comment by TileHalo** [comment]
Little digging into mio documentation told  that mio's `TcpListener::bind()` sets SO_REUSEADDR. Hypers `HttpsListener` uses this but `HttpListener` doesn't.

**Comment by daogangtang** [comment]
wow

**Comment by TileHalo** [comment]
Actually Both `HttpListener` and `HttpsListener` uses `TcpListener::bind()
`

**Comment by seanmonstar** [comment]
Oh right, I forgot that in the example I had used mysql, I created the listener, and cloned it for each thread.

```rust
for _ in 0..threads {
    let listener = listener.try_clone().unwrap();
    thread::spawn(move || Server::new(listener) ... );
}
```

**Comment by TileHalo** [comment]
Ok, that explains alot. Thank you. Could it be possible to make example how to spawn multiple processes or should `hyper::server::Server` have some way of doing it? I assume that one must create `mio::tcp::TcpListener` by hand.

**Comment by seanmonstar** [comment]
@TileHalo I've added that to the Hello World example: https://github.com/hyperium/hyper/blob/mio/examples/hello.rs#L35-L47

**Comment by daogangtang** [comment]
nice, perfect work.

**Comment by daogangtang** [comment]
and I must said [sapper](https://github.com/sappworks) on hyper mio branch is now very clear and comfortable to write, next we will explore how to work with diesel, db conn pool, background tasks, im chatroom and so on. 

Thanks for async hyper, a perfect design.
