### ISSUE TITLE
Client: Choose default port in Protocol or NetworkStream?

### ISSUE THREAD

**Issue by erikjohnston** [hyperium/hyper#776]
I work on a project where we use HTTPS to talk between servers, but resolve the host via SRV records rather than A records. The flow from going from a host name to an IP is as follows:

1. Does the URL have a port? If so then resolve using normal A records and use the given port
2. If not, resolve via SRV and use the ports returned by the SRV lookup

I was going to write a custom Protocol that matched against the scheme, but the Client object has already resolved the port (using `Url::port_or_default`), which means that I can no longer do the check in step 1 above.

Is there a reason why `Protocol::new_message` doesn't take an `Option<u16>`, and have `Protocol::{Http11Protocol, Http2Protocol}` check the scheme is either `http` or `https` and default the port as required there?

This seems helpful more generally as well, particularly for implementing schemes that have default ports but that aren't known by `url::Url`

**Comment by seanmonstar** [comment]
Interesting issue. I've since decided in the async  branch to adjust the
Connect trait to accept &Url instead of deciding beforehand what a
Connector may or may not need.

If there is no port, will the server expect the Host header to include the
port from the SRV record?

**Comment by erikjohnston** [comment]
> Interesting issue. I've since decided in the async  branch to adjust the Connect trait to accept &Url instead of deciding beforehand what a Connector may or may not need.

That sounds like it would solve this then.

> If there is no port, will the server expect the Host header to include the
port from the SRV record?

No, the Host header would be without the port.

**Comment by seanmonstar** [comment]
The `Connect` trait in master receives a `&Url` instead of an explicit `port` argument.
