### ISSUE TITLE
Trying to use mock::MockStream;

### ISSUE THREAD

**Issue by afiune** [hyperium/hyper#786]
I would like to ask if there is a way to use the `MockStream` trait in my tests.. I saw this other repository (https://github.com/Byron/yup-hyper-mock) but I wonder what you guys recommend. Thanks!

**Comment by seanmonstar** [comment]
Yes, I would recommend something like that crate. I chose not to expose the
`mock` module in hyper because I use it for tests, and I didn't want to
feel like I couldn't expand the tests because of backwards compatibility.

**Comment by afiune** [comment]
Awesome thank you @seanmonstar !!
