### ISSUE TITLE
mio branch: example server hangs up curl for NotFound

### ISSUE THREAD

**Issue by siddontang** [hyperium/hyper#791]
@seanmonstar 

I try to run the server example like `cargo run --example server` and use curl `curl http://127.0.0.1:1337/get` to test it, I expect I will get a NotFound error, but the curl hangs up. 

```
curl http://127.0.0.1:1337/get -v
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 1337 (#0)
> GET /get HTTP/1.1
> Host: 127.0.0.1:1337
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Date: Fri, 13 May 2016 02:05:23 GMT
< Transfer-Encoding: chunked
< 
```

Using curl `-v` to see that the server responses a chunked header which causes it. 
I force to set a 0 Content length and fix it.  But I think we should not return chunked header here.

**Comment by seanmonstar** [comment]
The actual bug was that even though the chunked header was used, it wasn't writing the last zero chunk if `encoder.write()` was never called. I've fixed that.

It would be a nice enhancement to notice if `on_response` returns `Next::end()`, that it shouldn't set the `Transfer-Encoding` header.
