### ISSUE TITLE
Openssl vs opensslclient

### ISSUE THREAD

**Issue by softprops** [hyperium/hyper#792]
I recently noticed that the ssl trait was deprecated. I've been using the openssl struct as a network connector for clients. I seems that is just an impl for the deprecated form of secure network connectors. I looked at opensslclient, an impl of sslclient, but it seems it's ssl context member is private, meaning I can only use the default impl. Is this by design or should I be able to provide my own ssl context? If it's just a matter of adding a pub keyword to it I can submit that pull

**Comment by seanmonstar** [comment]
I think I made the field private on purpose, because public fields mean I cannot refactor when I need to. It's likely instead missing a constructor that accepts a pre-made `SslContext`.
