### ISSUE TITLE
SSL Error on HTTPS client request.

### ISSUE THREAD

**Issue by novacrazy** [hyperium/hyper#794]
For even something as simple as: 
```rust
extern crate hyper;

use hyper::Client;

fn main() {
    let client = Client::new();
    let mut res = client.get("https://www.google.com/").send().unwrap();

    let mut body = String::new();
    res.read_to_string(&mut body).unwrap();
    println!("Test: {}", body);
}
```

I get this panic:
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: 
Ssl(
    OpenSslErrors(
        [
            UnknownError { 
                library:  "SSL routines", 
                function: "SSL3_GET_SERVER_CERTIFICATE", 
                reason:   "certificate verify failed" 
            }
        ]
    )
)', ../src/libcore\result.rs:785
```

So either I'm missing something crucial like how to add root certs to hyper or something, I'm not sure. I don't really have anything to go on.

I'm on Windows 10.0.10586, using Rust 1.10.0-nightly (8492b6aa4 2016-05-14), and the Win32OpenSSL/Win64OpenSSL v1.0.2h 64-bit OpenSSL implementation for rust-openssl.

I have a feeling this isn't really a "bug" with either hyper or rust-openssl, but rather I simply don't know how to properly initialize whatever it is I need to in order to use HTTPS.

**Comment by seanmonstar** [comment]
What version of hyper is this with?

**Comment by looah-bmtmch** [comment]
I'm getting the same problem whenever trying to use https, I tried the same code as shown by novacrazy while using version 0.9.4, and I'm getting the same error.

**Comment by seanmonstar** [comment]
@looah-bmtmch on Windows?

**Comment by looah-bmtmch** [comment]
@seanmonstar windows 10

**Comment by novacrazy** [comment]
@seanmonstar This was with hyper version 0.9.4

Any thoughts on why it would fail like this?

**Comment by sfackler** [comment]
@novacrazy Hyper previously didn't validate a server's certificates at all. This is *super* bad. That was fixed, but openssl doesn't know how find a trusted certificate list on Windows by default, hence the errors, since there are no trusted roots.

**Comment by dwillie** [comment]
I'm experiencing this on Raspbian armhf cross compiled from Debian 64bit with Hyper 0.9.6

**Comment by MrSpock** [comment]
I have exact the same error on MacOS for signed certificate:

`Hyper(Ssl(OpenSslErrors([UnknownError { library: "SSL routines", function: "ssl3_get_server_certificate", reason: "certificate verify failed" }])))`

**Comment by seanmonstar** [comment]
@MrSpock SSL is no longer in this library. From that error, it looks like you're using openssl. You may wish to check there.
