### ISSUE TITLE
Connection Aborted / Keep alive timeout

### ISSUE THREAD

**Issue by Mickacka** [hyperium/hyper#796]
Hello,

Using hyper 0.9.4, this code may fail depending on the duration of the sleep.

``` rust
fn main() {
    let client = Client::new();

    {   
        let mut res = client.get("http://www.example.com").send().unwrap();
        assert_eq!(res.status, hyper::Ok);
        let mut buffer = String::new();
        res.read_to_string(&mut buffer);
        // drain it to avoid drop message
    }   
    thread::sleep(Duration::from_millis(360000));
    // exceed timeout of keep alive     ~~~~~^
    let res = client.get("http://www.example.com").send().unwrap();
    assert_eq!(res.status, hyper::Ok);
}
```
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Custom(Custom { kind: ConnectionAborted, error: StringError("Connection closed") }) })', ../src/libcore/result.rs:785
```
because the connection is re-used from the pool of client and the timeout was exceeded. 
Is it intended to not checking if the connector is still usable (i.e. should the user verify it) ?

**Comment by seanmonstar** [comment]
This is current expected behavior. The status of a socket cannot be
determined without using it. While in blocking mode, that means hyper
cannot try a check without possibly blocking the thread forever.

In non-blocking mode, hyper can poll for a hang up, and remove the
connection from the pool.

Current master has moved to non blocking io.

**Comment by cristicbz** [comment]
I think I'm still seeing this in current release, reading your last comments it sounds like maybe, whilst the move to non-blocking IO happened, the fix for dead connections has not?

**Comment by seanmonstar** [comment]
@cristicbz yes, in v0.9.x, this still exists. The explanation for why is in the previous comment.

**Comment by cristicbz** [comment]
Apologies, saw 'current master' in may and I thought it'd have been merged by now. Didn't realise it was a big year long refactor. Thanks!

**Comment by cetra3** [comment]
@seanmonstar what version is this fixed in?
