### ISSUE TITLE
ControlError not public

### ISSUE THREAD

**Issue by bfrog** [hyperium/hyper#802]
The http module is private, Control may return a ControlError, however ControlError is not re-used in src/lib.rs like Control is.

I think ControlError should be pub use'd in lib.rs along with Control

**Comment by seanmonstar** [comment]
Looking at the implementation again, there's not much to these errors. Is there any reason you would need to name them? They pretty much only exist in hyper so that `unwrap` or debug printing them will give a more useful message.

**Comment by bfrog** [comment]
When creating a enum'ed error wrapper around my method which may return
several error kinds, its impossible to create a From<ControlError> for
MyError which is annoying
