### ISSUE TITLE
Add Guides

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#805]
Create a series of guides explaining different topics in hyper, along the lines of https://tokio.rs/docs/getting-started/tokio/

Some topics that seem like good ideas, though organization can be re-worked:

- Server
  - [x] Hello World
  - [x] Echo
  - [ ] File Server/Reverse proxy?
  - [ ] Advanced specifics on server's `Http`, `Service`, and `NewService`
- Client
  - [x] Getting Started
  - [x] Posting a Request Body
  - [ ] Configuration/Using TLS

**Comment by drusellers** [comment]
OMG YES

**Comment by pimeys** [comment]
I'd add "Stopping a server cleanly".

**Comment by seanmonstar** [comment]
I actually wonder if some of the topics are too small (the routing guide I just wrote feels so tiny). Maybe instead, a list of sufficiently more complicated topics that explore all of the required topics, such as:

1. hello world
2. echo
3. file serving

They would definitely cover all the topics original topics, but it may not be obvious from their titles?

**Comment by hjr3** [comment]
I think showing the examples is a good place to start. One of the more challenging things about understanding futures, tokio and hyper is context. Examples, such a hello world, show more of that context and give people a better chance of solving their problem.

I do think there is value in doing a deep-dives on a particular topic, but I think examples and spelunking through source is good enough until things really stabilize.

**Comment by seanmonstar** [comment]
The docs that will exist for the v0.11 release are done. Clearly, there is always room for more, and better, docs.
