### ISSUE TITLE
Add a Server Guide

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#806]
Add a guide on how to do more and more complicated things with the Server/Handler in `docs/guide/server.md`.

**Comment by puhrez** [comment]
So what sort of spec would you hold for this guide? like what points should it cover?

**Comment by seanmonstar** [comment]
I could imagine the guide going in steps:

- Introduce the `Handler` trait. Such as show how to make a simple "Hello World" handler, like from the `examples/hello.rs`.
- Explain `WouldBlock`, and/or `try_read`/`try_write`, and repeating with `Next` until the IO is done.
- Introduce some routing, using `req.uri()`.
- Add an additional blocking service, like a worker pool. This would show off how to use `Next::wait()` and `Control.ready()`.

Somewhere in there, sometimes it makes sense to skip explaining all the pieces, and then eventually explain "So remember `Handler<HttpStream>`? That's actually a `Transport`, go read about the Transport docs." or something.

----

I'm currently fiddling with the docs script, to try to pull in any `.md` file in the `doc` directory, so that the guides will be part of the docs at http://hyper.rs/hyper, and can even be versioned.
