### ISSUE TITLE
HTTP/2 client.rs example causes StringError

### ISSUE THREAD

**Issue by verandaguy** [hyperium/hyper#807]
Building and running the `client_http2.rs` file from the `examples` directory on the `v0.9.6` branch, produces no compile-time errors under Rust 1.8.0, however a runtime panic occurs when trying to pass a valid URL to the program after building.

**Steps to reproduce:**

1. Create a new Cargo project with contents of `client_http2.rs` in `src/main.rs`.

2. Add `hyper = "0.9.6"` as a dependency in `Cargo.toml`.

3. `cargo build`

4. `./target/debug/{target_name} "http://example.com"`

**Output as tested:**

    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Http2(IoError(Error { repr: Custom(Custom { kind: Other, error: StringError("Not enough bytes") }) }))', src/libcore/result.rs:746

**Expected output:**

The status, headers, and body of the requested webpage, printed to the command line.

**Test environment:**

This was tested on a machine running OS X 10.11.3 with Rust 1.8.0 and Cargo 0.10.0, with `zsh` 5.2 and a working internet connection over Wi-Fi.

Several HTTP/2-capable websites were tested; including

- http://http2.akamai.com/demo.

- http://google.com

**Additional notes:**

- Appropriate, non-ambiguous warnings are raised if an invalid URL or no URL are supplied.

- The HTTP/1.1 version of `client.rs` does not have this issue, and fetches the requested webpage without issue, printing the contents to the console.

- This issue exists both when surrounding the requested URL with quotes and when passing it un-quoted.

- The issue may be caused by the fact that websites supporting HTTP/2 overwhelmingly upgrade requests to SSL (totally unsure)

**Comment by seanmonstar** [comment]
Thanks for the thorough report! I'd love it if all reports were this detailed.

I've removed the HTTP/2 client from master, as it wasn't complete, nor was the design compatible with the async IO rework. I plan to work on full HTTP/2 integration for v0.11. As this isn't an issue on master, the only thing I can see to do is close it, but again, thank you so much the report.
