### ISSUE TITLE
Versions 0.9.5 and 0.9.6 have been published, but no record in Cargo.toml nor CHANGELOG.md

### ISSUE THREAD

**Issue by frewsxcv** [hyperium/hyper#812]
Would be nice to know what changed in these releases.

**Comment by seanmonstar** [comment]
Yes, master merged the mio branch, and is on the path to 0.10. The 0.9.x branch exists to continue to accept bug fixes.

**Comment by seanmonstar** [comment]
I do try to keep the [releases](https://github.com/hyperium/hyper/releases) page up-to-date with changes.

**Comment by frewsxcv** [comment]
Ah, right the mio stuff, makes sense. Thanks!
