### ISSUE TITLE
Add docs for features

### ISSUE THREAD

**Issue by Keats** [hyperium/hyper#815]
The `ssl` feature is quite explicit but the `serde-serialization` one is not explained anywhere.
Looking at the code, it seems to use Serde to serialize/deserialize status/method/header but it doesn't explain the benefits of using it.

**Comment by seanmonstar** [comment]
I haven't publicly documented them since I'm not actually sure about their use. I know servo needed them for ipc serialization (I think?).

**Comment by frewsxcv** [comment]
> (I think?)

[Yes](https://github.com/servo/servo/blob/3fead5a3988c67340a3a1ccb001c0c5ddf2bf9ba/components/net/Cargo.toml#L19)

**Comment by seanmonstar** [comment]
Currently, there no longer exists any "features" in hyper, so closing for now.
