### ISSUE TITLE
Windows aborts sockets on drop

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#816]
The event loop will drop a socket once the `Handler` declares the response is done (and keep alive is disabled). When the Server is running on Windows, it seems that this behavior causes a client to receive a WSACONNABORTED error. The docs of msdn say that this means the server is aborting the socket before the TCP shutdown is completed.

This might be related to how mio imitates readiness on Windows: the `is_writable` event doesn't mean the socket can actually send more data right away, but that it has finished sending it's last queued buffer. So calling `socket.write(data)` for the last time means the data is queued, and it could be that dropping the socket then makes the IOCP thread decide to abort completely.

**Comment by arkpar** [comment]
I've been investigating this issue but still not sure what causes it. First I patched hyper to drop the socket after everything have been written and the final write have been confirmed with `write_done` in mio/tcp. Introduced an additional `Writing::Flushing` state in which connection waited for the socket to be writable again before closing it. That did not help much. 
This commit resolved it but I have no idea why and I'm quite sure that's not the best way to fix it:
https://github.com/ethcore/mio/commit/3842d3b250ffd7bd9b16f9586b875ddcbac2b0dd 

Setting `SO_LINGER` socket option might also help, but I haven't tried this.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms738547(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740476(v=vs.85).aspx

**Comment by seanmonstar** [comment]
This appears to be fixed in newer mio, will close this bug once hyper has incorporated it.

**Comment by seanmonstar** [comment]
This is no longer happening in the tokio branch.
