### ISSUE TITLE
TLS mutual auth

### ISSUE THREAD

**Issue by ryansroberts** [hyperium/hyper#823]
Is this on anyone's roadmap? If not I'd be happy to add it.

**Comment by seanmonstar** [comment]
I have not thought about it at all. Is there a particular RFC or spec I should read up on?

**Comment by ryansroberts** [comment]
https://tools.ietf.org/html/rfc6101#section-5.6.2

Rust openssl bindings provide all the needed calls by the look of it. The client x509 cert will need to be made available to middleware as its often used to identify the client.

https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/mod.rs#L224
https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/mod.rs#L1052

**Comment by seanmonstar** [comment]
All TLS is now handled outside of hyper proper, so I'm going to close this. See #985 for reasons.
