### ISSUE TITLE
No way to use a custom TLS wrapper for proxy connections

### ISSUE THREAD

**Issue by inejge** [hyperium/hyper#824]
[Motivation: rust-lang-nursery/rustup.rs#509]

The function `client::Client::with_http_proxy` constructs a `Proxy` struct (via `hyper::client::proxy::tunnel`) with the `ssl` field which depends on build-time configuration of the TLS library. Rustup compiles hyper with no TLS support, using its own TLS wrapper based on rust-native-tls. In this case, hyper will use the built-in `no_ssl::Plaintext` wrapper, which will preclude using `https` URLs with proxy support.

There is currently no way to specify a custom TLS wrapper when initializing a proxied `Client`.

**Comment by seanmonstar** [comment]
I've merge the accompanying PR.
