### ISSUE TITLE
ask: how to abstract stream from new async hyper

### ISSUE THREAD

**Issue by daogangtang** [hyperium/hyper#832]
Hi, I ask this question in reddit some days ago, but don't get clear answers now, so I post it here,

https://www.reddit.com/r/rust/comments/4n9vq0/ask_how_to_abstract_stream_from_new_async_hyper/

can some one give a solution?

thx.

**Comment by matt2xu** [comment]
In my framework, I've also chosen the simplest approach: read the whole body from the Decoder into a Buffer (essentially a Vec<u8> + position). See [Handler::on_request_readable](https://github.com/matt2xu/edge-rs/blob/master/src/handler.rs#L181) and [Buffer::read_from](https://github.com/matt2xu/edge-rs/blob/master/src/buffer.rs#L48) methods.

Probably in case of file upload you might want to store the request body in a file to avoid consuming too much memory. This could be a configuration option when initializing the server. Alternatively if you want to use a callback with a Read argument, you can use Cursor over a Vec<u8> read from the Decoder in on_request_readable.

**Comment by seanmonstar** [comment]
@daogangtang The answer from @matt2xu is what I would say as well. Some message formats require buffering before you can understand the full message. You can either do that yourself, or make the users of your library do it.

**Comment by daogangtang** [comment]
ok
