### ISSUE TITLE
Multipart with Client / Proxy

### ISSUE THREAD

**Issue by mitsuhiko** [hyperium/hyper#837]
I just upgraded to a newer hyper hoping I can use the proxy support but I need to send multipart requests which is currently only possible with a `Request<Fresh>` and the only way to get one of those is with `Request::new`, never from a client.

However it looks like the proxy support is public API way contained within the client only.

Can't say I have any ideas how to fix this though :(

**Comment by cybergeek94** [comment]
Author of `multipart` here. You can use the `Client` struct with `client::lazy::Multipart` via the following method:  http://cybergeek94.github.io/multipart/doc/multipart/client/lazy/struct.Multipart.html#method.client_request

**Comment by seanmonstar** [comment]
Going forward, hyper won't provide a proxy API built-in. All the pieces are now exposed to allow 3rd party proxy implementations, and multipart, albeit it's a fair amount of work.

I expect both proxy and multipart support to exist in https://github.com/seanmonstar/request, though they don't currently.
