### ISSUE TITLE
clarify timeout semantics

### ISSUE THREAD

**Issue by stapelberg** [hyperium/hyper#839]
http://hyper.rs/hyper/v0.9.8/hyper/client/struct.Client.html#method.set_read_timeout describes “Set the read timeout value for all requests.”, the method takes an `Option<Duration>`.

It’s not clear to me what this timeout does specifically. Is it applied to each underlying `read()` call, or does it cover the entire request duration (multiple `read()` calls)? Does it cover resolving the hostname and connecting as well?

The specifics are relevant for being resilient against https://en.wikipedia.org/wiki/Slowloris_(computer_security): I’d like to perform a request which should complete in, say, 5 seconds.

For inspiration/illustration, in the Go 1.7 standard library, `net/http` requests support `context`s, i.e. one could do:
```go
	req, err := http.NewRequest("GET", "http://www.google.com", nil)
	if err != nil {
		log.Fatal(err)
	}
	// Between here…
	ctx := context.WithDeadline(context.Background(), time.Now().Add(5*time.Second))
	resp, err := http.DefaultClient.Do(req.WithContext(ctx))
	// …and here, at most 5 seconds have passed, regardless how long
	// resolving, connecting and reading took individually.
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("resp = %+v\n", resp)
```

Can the documentation be clarified? Can a total operation timeout/deadline be specified? If not, can we treat this issue as a feature request please? :)

**Comment by seanmonstar** [comment]
In the 0.9.x branch, the timeouts relate directly to [TcpStream.set_read_timeout](http://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_read_timeout).

So every single read will block *up to* the timeout.

On master (with async IO), the timeout is for each specific event.

**Comment by stapelberg** [comment]
Thanks. What do you mean by “event”? Could you give a code example maybe, similar to what I provided?

**Comment by seanmonstar** [comment]
With async IO, the `Handler` returns a desired "next" event to listen for.

```rust
fn on_request_readable(&mut self, decoder: &mut Decoder) -> Next {
    // try to read
    // and then return desired next event
    if NO_TIMEOUT {
        Next::read()
    } else {
        Next::read().timeout(Duration::from_secs(10))
    }
}
```

The timeout in this case is for this specific read event. If/when the socket is readable again, the timeout is cleared, and you could provide a different timeout (or none).
