### ISSUE TITLE
Remote Address Might Not Always Available

### ISSUE THREAD

**Issue by bfrog** [hyperium/hyper#843]
So looking more carefully at how hyper does its thing it looks like the remote address (from the transport) might not always be available.

In the case of a GET request there likely won't be a body and it looks like https://github.com/hyperium/hyper/blob/master/src/server/mod.rs#L329
won't be called then.

If thats the case then the remote address is never available for certain request types which would seem to be a bug.

**Comment by seanmonstar** [comment]
I've also simply felt that it'd be better to have access to the `Transport` in the `on_request` event. So to do this, I've been thinking of adding a `&'a T` field to the `Request` struct.

```rust
fn on_request<'a>(&mut self, req: Request<'a>) -> Next {
    let addr = req.transport().peer_addr().unwrap();
}
```

I wonder if lifetime elision can remove the need for those `'a`s...

@Ogeon @Ryman would this hurt ergonomics for frameworks much that you could no longer hold on to the `Request` object? You could still get the underlying fields with `req.deconstruct()`...

**Comment by Ogeon** [comment]
I don't think it will be a problem. I'm consuming the request in `on_request`, so it won't leave the scope. I'm quite sure the `'a`s will be elided, as well. It's the same for the `Handler` trait in Rustful.

**Comment by Ryman** [comment]
I haven't spent enough time with the new api to know if it'll be a problem, but I imagine if `deconstruct` is available it'll probably be fine :)
