### ISSUE TITLE
Provide a normal way to generate parameters body for POST requests in Hyper::Client

### ISSUE THREAD

**Issue by vityafx** [hyperium/hyper#849]
Now to send a parameters in `POST` HTTP request we need to do some magic or use external `url` crate. I respect rust's philosophy about responsibility splitting or UNIX-paradigm that one library/program should do only one thing. But, `hyper` is a powerful HTTP library which should give all tools to use it in one package (library). This is very ugly that need external useless library to do something than you already have one which is designed for that actually.

[This post](https://github.com/hyperium/hyper/issues/316) has code examples where we need a `url` crate. If this way is right then we also need to split `hyper` into `hyper-header`, `hyper-body`, `hyper-requestbuilder`, etc.

**Comment by seanmonstar** [comment]
hyper, especially what now exists on master, will purposeful stay a lower-level HTTP implementation.

I have begun work on [request](https://github.com/seanmonstar/request) which will be a batteries-included HTTP Client crate. The benefit here is this new crate can be much more opinionated and include other crates to provide easy APIs, without bogging down the HTTP crate.
