### ISSUE TITLE
Question about default number of threads for server::Server 

### ISSUE THREAD

**Issue by Cobrand** [hyperium/hyper#852]
I noticed that the default number of threads used by hyper wasn't the number of cpus, but the number of cpus * 5 / 4 : see [here](http://hyper.rs/hyper/v0.9.9/src/hyper/src/server/mod.rs.html#229)

It means that for 2 cpus, it will have 2 threads spawning, but for 4 cpus 5 threads spawning, 8 cpus 10 threads spawning, etc ; but why it not have a 1 thread <-> 1 cpu ratio ? What directed that decision ?

It is simply a mere question, not an issue what-so-ever, but maybe we can add an explanation in the comments so people that are wondering this like me won't have to post another question here. Don't worry, if anyone properly explain I will can the PR myself if needed.

**Comment by seanmonstar** [comment]
It was just a gut decision. It's being deprecated, so people can pick the
number of threads themselves.

**Comment by Cobrand** [comment]
I understand that you might want to deprecate this and let the users pick the number of threads they want themselves, but what if people don't want to pick themselves ?

At the very least make something that allows to pick the number of threads depending on the number of cpus you have (with a closure I guess) directly in hyper. It would be quite cumbersome to extern the crate num_cpus on everything depending on hyper (since the number of threads depends heavily on the number of cpus you have anyway).

If you agree with this, I could make a PR for this.

**Comment by seanmonstar** [comment]
Hyper is moving away from spawning threads for the server. This is already
done on master. This is because it's using non-blocking IO, so the event
loop lives on one thread.

**Comment by Cobrand** [comment]
I did not see that master's src what different, thank you for the explanation.
