### ISSUE TITLE
basic http authentication

### ISSUE THREAD

**Issue by lcowell** [hyperium/hyper#854]
As far as I can tell, hyper does not support basic http authentication in the client. Here is my code (as I likely may have done something wrong):

```rust
fn main() {
    let client = Client::new();
    let mut response = client.get("http://user:pass@localhost:3000").send().unwrap();
    let mut s = String::new();
    response.read_to_string(&mut s);
    println!("{}", s);
}
```
Can someone confirm whether basic auth is supported? Are there any alternatives? Should I hand-roll the header?

If nothing else comes of this request I'm ok. Simply by filing this issue the next guy trying to use basic auth is going see this and save some time.

**Comment by jdm** [comment]
Servo ended up [writing this by hand](https://dxr.mozilla.org/servo/source/components/net/http_loader.rs#701) after https://github.com/hyperium/hyper/pull/727 was closed.

**Comment by lcowell** [comment]
Thanks for the response. This behaviour is a little confusing and unexpected. I'd think if I pass hyper a url with parts that it isn't going to pass to the server, that it would make some noise.

I'll have a look at rolling it in myself too.

**Comment by seanmonstar** [comment]
I'm still conflicted. RFC7230 pretty much just says "Don't put userinfo in the URL". It's not specced that it should read it and instead change it into an `Authorization` header.

On the other hand, other clients I looked at (nodejs, golang) do this automatic conversion.

I still want to say that maybe it doesn't belong in the HTTP library, but I do expect things like https://github.com/seanmonstar/request to do this sort of thing automatically.
