### ISSUE TITLE
Proxy server can only be set with 'static string

### ISSUE THREAD

**Issue by natemara** [hyperium/hyper#868]
Unless I am misunderstanding the type signature (a realistic possibility), according to the documentation for the methods [hyper::client::Client::with_http_proxy](http://hyper.rs/hyper/v0.9.10/hyper/client/struct.Client.html#method.with_http_proxy) and [hyper::client::Client::with_proxy_config](http://hyper.rs/hyper/v0.9.10/hyper/client/struct.Client.html#method.with_http_proxy), the only way that a proxy server host can be specified is with a static string. This means that it would be impossible to use hyper to create a HTTP client like cURL that respected the `HTTP_PROXY` env variable, as for this the proxy host string would have to be stored in dynamic memory.

Could a user of Hyper possibly get around this by using a static buffer to hold the proxy host? Or would it be possible to change this to an owned string?

**Comment by seanmonstar** [comment]
No, the type `Into<Cow<'static, str>>` means any type that create that `Cow`. This one sepcifically says "any static string, or an owned String". It is this, after the generic parameters are subbed in:

```rust
enum Cow {
    Borrowed(&'static str),
    Owned(String)
}
```

**Comment by natemara** [comment]
Thanks! I thought that seemed like an overly restrictive API and I was just misunderstanding it.
