### ISSUE TITLE
Add Content-Location header

### ISSUE THREAD

**Issue by Stebalien** [hyperium/hyper#870]
See https://tools.ietf.org/html/rfc7231#section-3.1.4.2

**Comment by koivunej** [comment]
I'd like to take a shot at this. ABNF from RFC here is:

```
Content-Location = absolute-URI / partial-URI
```

ABNF is exactly same as with `Referer` which is implemented as

```
header! {
    // TODO Use URL
    (Referer, "Referer") => [String]

    // testcase
}
```

`/TODO:? Use URL/` is mentioned for `Location` and `Referer` headers, so I guess it'd be best to implement `Content-Location` as simple `(ContentLocation, "Content-Location") => [String]` for consistency?
