### ISSUE TITLE
The OpenSSL library reported an error: bad write retry

### ISSUE THREAD

**Issue by taheris** [hyperium/hyper#872]
With the async branch, when POSTing a large body the following error is returned: `The OpenSSL library reported an error: bad write retry`

The exact amount of data that causes the error seems to be OS/hardware dependant (possibly related to the size of buffers). I've set up an example project at https://github.com/taheris/bad-write-retry-example which should trigger the error.

By patching the openssl library to set the [`SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER`](https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_set_mode.html) flag, the error goes away. Uncomment the `[replace]` line in the `Cargo.toml` file to verify this.

The patched line is https://github.com/taheris/rust-openssl/commit/7b7a2e2fef207786a74708b11624f02153e54c32. I've used a hardcoded value of [`0x00000002`](https://github.com/openssl/openssl/blob/1d97c8435171a7af575f73c526d79e1ef0ee5960/ssl/ssl.h#L656) as the specific `SSL_MODE` flag is not available (see [here](https://github.com/sfackler/rust-openssl/blob/a1cce676aab14c59e44f6e039ebd12fdedbd78ce/openssl-sys/src/lib.rs#L275) for the relevant section).

**Comment by seanmonstar** [comment]
@taheris wow, thanks for all the troubleshooting! If you file a PR to rust-openssl, can you update this issue?

**Comment by taheris** [comment]
@seanmonstar: no problem, [PR created](https://github.com/sfackler/rust-openssl/pull/423)

**Comment by seanmonstar** [comment]
Looks fixed, closing.
