### ISSUE TITLE
TLS Certificate validation is disabled on Windows

### ISSUE THREAD

**Issue by frewsxcv** [hyperium/hyper#880]
Disabled in https://github.com/hyperium/hyper/pull/795 presumably because of https://github.com/hyperium/hyper/issues/794

[Code in question](https://github.com/hyperium/hyper/blob/9456738ee136158c10681b41c4038c1bf8639664/src/net.rs#L506-L513)

Route forward here might be to incorporate schannel?

**Comment by seanmonstar** [comment]
Yep, eventually hope to replace the different TLS impls with the native-tls crate.

**Comment by frewsxcv** [comment]
Next step here is to incorporate native-tls now that it's published, right? Need any help with that?

**Comment by seanmonstar** [comment]
Starting with 0.10, hyper no longer bundles a TLS implementation, so this issue no longer applies.
