### ISSUE TITLE
Proposal: async Handler API

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#881]
Thanks to utilizing [tokio](https://github.com/tokio-rs/tokio) internally, there is no longer a need to explicitly declare your interest for events on the socket. With that in mind, I've brainstormed a revised API to use async hyper with @carllerche, and wanted to share it here before I implement it.
# Handler

``` rust
trait Handler<T: Transport> {
    fn ready(&mut self, txn: &mut Transaction<T>);
}
```
# Transaction

``` rust
pub struct Transaction<T> {
    // fields private
}

impl<T: Transport> Transaction<T> {
    pub fn request(&mut self) -> hyper::Result<Request>;
    pub fn read(&mut self, buf: &mut [u8]) -> io::Result<usize>;
    pub fn try_read(&mut self, buf: &mut [u8]) -> io::Result<Option<usize>>;

    pub fn response(&mut self) -> &mut Response;
    pub fn write(&mut self, data: &[u8]) -> io::Result<usize>;
    pub fn try_write(&mut self, data: &[u8]) -> io::Result<Option<usize>>;

    pub fn abort(&mut self);
    pub fn end(&mut self);
}
```

---

This requires importing fewer types from hyper, and allows you to more easily try multiple actions in the same "tick".

Missing pieces are:
- Timeouts
  - these could either be internal, such that you call `txn.timeout(some_dur)`, and if the timeout triggers, then the next time `ready` is called, and you try to `read` (or `write`), the `Err` will include the timeout instead of just `WouldBlock`
  - or they can be external of hyper, and instead the user can take advantage of Tokio's `Timer` themselves. Tokio will trigger `ready` if the timeout expires, and a user can check the timer before doing something else. 
- Wakeup
  - This could with a `Sender<T>`, similar to `Control` currently,
  - or this could take advantage of Tokio's knowledge of `Futures`, which are actually quite similar to `Sender<T>`

My current thinking is to add this to the `Transaction`:

``` rust
fn timeout(&mut self, dur: Duration) -> tokio::TImer;
fn channel<T>(&mut self) -> (tokio::Sender<T>, tokio::Receiver<T>);
fn future<T>(&mut self) -> tokio::Future<T>;
```
# Example

``` rust
enum State {
    Init,
    Write(&'static str),
    Done
}

impl<T: Transport> Handler<T> for State {
    fn ready(&mut self, txn: &mut Transaction<T>) {
        match self {
            State::Init => {
                let req = match txn.request() {
                    Ok(req) => req,
                    Err(e) => {
                        println!("request error: {}", e);
                        // you could inspect error and send a more specific status code
                        txn.response_mut().set_status(StatusCode::BadRequest);
                        txn.end();
                        return;
                    }
                }
                println!("{} {}", req.method(), req.uri());

                let mut res = txn.response_mut();
                res.set_status(StatusCode::Ok);
                res.headers_mut().set(ContentLength(11));

                // body isnt too big, maybe it fits with the headers
                let body = "Hello World";
                match txn.try_write(body) {
                    Ok(Some(n)) => {
                        if n == body.len() {
                            txn.end(); // optional if not chunked
                        } else {
                            *self = State::Write(&body[n..]);
                        }
                    },
                    Ok(None) => (),
                    Err(e) => {
                        println!("write error: {}", e);
                        txn.abort();
                    }
                }
            }
            State::Write(body) => {
                match txn.try_write(body) {
                    Ok(Some(n)) => {
                        if n == body.len() {
                            txn.end(); // optional if not chunked
                        } else {
                            *self = State::Write(&body[n..]);
                        }
                    },
                    Ok(None) => (),
                    Err(e) => {
                        println!("write error: {}", e);
                        txn.abort();
                    }
                }
            }
        }
    }
}

// takes a factory creating a Handler for each incoming req/res
server.handle(|| State::Init);
```

**Comment by cybergeek94** [comment]
It would still be nice to receive the request in the `HandlerFactory` method, so anything in the `Handler` that needs to be constructed from the headers in the request doesn't need to do funky stuff with `Option`. Barring that, one callback method is much easier to implement than four, so I guess I can live with it.

**Comment by mikeycgto** [comment]
Definitely think this greatly simplifies the API. I'm interested in migrating my [Event Source server](https://github.com/mikeycgto/esper) to any new async API when it's ready. Would be happy to even start implementing changes against a development branch!

I do need the ability to wake up arbitrary connections from another connection. To achieve this, I'm using a `HashMap` that maps to `Control` instances (or more specifically: `HashMap<Topic, Vec<(Client, Control)>>`. Once an outgoing message is queued, I call `ready()` on the `Control` instances.

**Comment by matt2xu** [comment]
I agree with @cybergeek94 on receiving the Request earlier.

Also, maybe wrap the `&mut Response;` in a `hyper::Result` or an option, to disallow modifying the response once you've started to write to the transport?

**Comment by yazaddaruvala** [comment]
@seanmonstar nit: I think you missed the handling of State::Done in the match.

Why not `fn ready(self, txn: &mut Transaction<T>) -> State` and deal with state transitions inside Hyper code? Seems like a better utilization of the type system.

**Comment by Ogeon** [comment]
This looks really nice! I think having just one handler method and getting rid of the explicit intent should make it a lot easier to implement frameworks and wrappers. I do agree that having access to the request in the factory, as well, would make it even nicer. That would probably allow me to simplify some parts of my current implementation.

**Comment by seanmonstar** [comment]
I haven't been ignoring the idea of providing the request to the factory, I just don't see a nice, logical way to do so. How would you expect the API to look with that difference?

**Comment by cybergeek94** [comment]
I'm guessing `Transaction::request()` will attempt to read the request from the stream on-demand, given it's returned in a `hyper::Result`. Naturally, the request will have to be switched to being eagerly read, which I don't think should be an issue as almost any request handler will want information from it anyway.

You haven't shown how `HandlerFactory` will change. I'm guessing you'll be dropping the `Control` parameter, so it will just be an empty method call like:

```rust
trait HandlerFactory<T: Transport> {
    type Output: Handler<T>;

    fn create(&mut self) -> Self::Output;
}
``` 

There's a couple possible approaches I would suggest, and both involve eagerly reading the request head before calling `HandlerFactory::create()` which would mean one or two more states in the internal state machine.

First approach would be to pass `hyper::Result<Request>` to `HandlerFactory::create()`; if the request could not be read, the factory can modify some state in the created `Handler` instance to return a response with an error message or what-have-you:

```rust
trait HandlerFactory<T: Transport> {
    type Output: Handler<T>;

    fn create(&mut self, req: hyper::Result<Request>) -> Self::Output;
}
```

Second approach would be to have `Request` passed to `HandlerFactory::create()`, and add a second method and associated type for dealing with the case where the request could not be read; the second associated type would be the `Handler` impl that will be sending the error response:

```rust
trait HandlerFactory<T: Transport> {
    type Output: Handler<T>;
    type Error: Handler<T> = DefaultErrorHandler;

    fn create(&mut self, req: Request) -> Self::Output;

    fn error(&mut self, err: hyper::Error) -> Self::Error {
        DefaultErrorHandler(err)
    }    
}

pub struct DefaultErrorHandler(hyper::Error);

impl<T: Transport> Handler<T> { /. ./ }
```

A default error handler could be provided so that a single closure can still be used as a `HandlerFactory`. It could send an appropriate error code back to the client and print the error to stdout. It might also be possible to impl `HandlerFactory` for a 2-tuple of closures with signatures which match `create()` and `error()` respectively.

**Comment by seanmonstar** [comment]
I've worried about receiving the `Request` in the factory, and then later in a `Handler` callback, not being able to get the `Request` from `txn`. I suppose the proper thing to do is just shove the `Request` into the `Handler` if you wish to look at it more than once? `|req| Handler { request: req, .. }`.

The request is already eagerly parsed, the idea would be that the result of the parse (`hyper::Result<Request>`) would be put into the `txn`, and then you would receive it via `txn.request()`. So, it is indeed already available when the factory is called.

----

Until now, hyper has just dumped sockets when a request has a parse error, but a goal of this proposal was to pass the parse error to the `Handler`. It seems receiving a `Result<Request>` in the factory is kinda gross. However, having the factory possibly return 2 different `Handler`s means I'd need to store that inside hyper as an `enum` with 2 variants, and then matching on it with every tick... That'd be unfortunate if you chose to deal with errors in the same `Handler`, since then the enum isn't needed. The match is likely negligible, though...

**Comment by cybergeek94** [comment]
Yes, I assumed that the request could be just be moved into the `Handler` if there was reason to retain it. As an upside, this allows the allocations in the `Request` to be eagerly freed if it won't be used later, which might help keep peak memory usage down for lightweight servers. Or, it can be stored in `Arc`/`Rc` and clones of that can be given out freely (but then you pay the cost for the box). 

You're already matching on the state machine enum in each tick, right?  I assumed that the error state above would be just another item in that enum, so it's still only one match per tick. At least, that's how it seems like it would fit into the current implementation, your plan for implementing the proposed API is still a little bit fuzzy. I haven't looked into the Tokio API too deeply.

I personally prefer the single factory method receiving the result, this keeps the implementation from having to do an extra `match`, especially when the user doesn't really care about errors.

**Comment by seanmonstar** [comment]
> I personally prefer the single factory method receiving the result, this keeps the implementation from having to do an extra match, especially when the user doesn't really care about errors. It also simplifies the success/error code path into an explicit branch in the handler, which might be easier to keep track of and build on.

You said "result", which means to me `fn create(::Result<Request>) -> Self::Output`. The rest of your statements could be applied to either option, so I cannot decide which you mean :)

**Comment by cybergeek94** [comment]
Second paragraph is talking about the two-method factory. First is either, I guess, but mainly talking about single-method factory.

However, I realized that the two `HandlerFactory` layouts I demonstrated can be unified, because the latter can be implemented for an instance of the former: https://is.gd/3GMd6N

Unfortunately, coherence prevents the impl for the 2-tuple I mentioned above, though this could be substituted with a macro, maybe.

**Comment by seanmonstar** [comment]
To be clear, which seems better from a user perspective?

1. Receive a `Result:
  
  ```rust
  server.handle(|incoming| match incoming {
      Ok(req) => Handle { request: Some(req), err: None, .. },
      Err(e) => Handle { request: None, err: Some(e), .. }
  })
  ```

2. Two different methods, with a default `ErrorHandler`:
  
  ```rust
  server.handle(|req| Handle { request: req, .. })
  ```

  A **pro** is that the `DefaultErrorHandler` can be defined in hyper to respond with certain status codes based on what the spec says to do depending on the various parse errors. A **con** is that it is more work if you want to handle errors yourself, instead of Option 1.

**Comment by cybergeek94** [comment]
Having a default error handler seems elegant, but the diverging code path disgusts me for some reason. It seems like a greater maintenance burden on the user, even if they end up making the two converge later.

What if the `HandlerFactory` returned `hyper::Result<Self::Output>`? You could unwrap the error with `try!()` or the `?` operator if you didn't care about the error state, in which case it gets passed back to Hyper, or you could handle it yourself. Same factory method, same handler implementation.

**Comment by seanmonstar** [comment]
Indeed, I had meant to propose that the Factory would return Option<H>, in
case there is an error try to prepare to construct a new Handler. It could
be a Result instead.

Returning an Err would likely just mean drop the socket.

>

**Comment by cybergeek94** [comment]
Returning `Result` means `try!()` works for unwrapping the request passed to the factory. The `?` operator would work with `Option` and would probably be the more elegant solution, but there's still a lot of churn in that area so I don't think we should base API design on that yet.

However, if we don't expect most use cases to handle the error, we probably shouldn't concern the average user about it. But I'm sure there will still be some that want control over what's done when an error occurs, and we should give them that control somehow.

Perhaps this could be done with a separate trait, and a builder method on `Server` to supply an implementation and replace the default. `HandlerFactory::create()` would simply be `(Request) -> Self::Output`.

```rust

pub trait ErrorHandlerFactory<T: Transport> {
    type Output: Handler<T>;

    // If the returned value is `None`, drop the socket. Otherwise, continue the request with the supplied handler.
    fn create(&mut self, err: hyper::Error) -> Option<Self::Output>;
}

pub struct Server<A, E> {}

impl<A: Accept> Server<A, DefaultErrorHandlerFactory<A::Output>> {
    pub fn new<...>(...) -> Self;
}

impl Server<HttpListener, DefaultErrorHandlerFactory<<HttpListener as Accept>::Output>> {
    pub fn http(...) -> Result<Self>;
}

// same for https()

impl<A: Accept, E> Server<A, E> {
    pub fn error_handler<E_: ErrorHandlerFactory<A::Output>>(handler: E_) -> Server<A, E_> {
        //...
    }
}
```

**Comment by Ogeon** [comment]
I somehow like this variant the most:

```rust
trait HandlerFactory<T: Transport> {
    type Output: Handler<T>;

    fn create(&mut self, req: hyper::Result<Request>) -> hyper::Result<Self::Output>;
}
```

Sure, it requires you to be aware of the error case, but handling it is trivial. The only risk is that its purpose may be unclear. What I like with it is that it's high control with low effort. There's only one trait (apart from `Handler`) to care about and only one method to implement, but you can still have access to the error case or just dismiss it with very little effort. For example:

```rust
//Using try!, as mentioned above, to just dismiss it and get the default error response
impl<T: Transport> HandlerFactory<T> for MyFactory {
    type Output = MyHandler;

    fn create(&mut self, req: hyper::Result<Request>) -> hyper::Result<MyHandler> {
        let request = try!(req);
        //do stuff
        Ok(handler)
    }
}

//Using req.map to just dismiss it and get the default error response
impl<T: Transport> HandlerFactory<T> for MyFactory {
    type Output = MyHandler;

    fn create(&mut self, req: hyper::Result<Request>) -> hyper::Result<MyHandler> {
        req.map(|req| self.make_request(req)) //something like this
    }
}

//The error can be ignored with req.ok
impl<T: Transport> HandlerFactory<T> for MyFactory {
    type Output = MyHandler;

    fn create(&mut self, req: hyper::Result<Request>) -> hyper::Result<MyHandler> {
        let request = req.ok();
        //do stuff
        Ok(handler)
    }
}

//And the return type can, of course, be a combination of handler and error handler
enum OkOrErrHandler {
    Ok(MyHandler),
    Err(MyErrorHandler),
}

impl<T: Transport> HandlerFactory<T> for MyFactory {
    type Output = OkOrErrHandler;

    fn create(&mut self, req: hyper::Result<Request>) -> hyper::Result<OkOrErrHandler> {
        Ok(match req {
            Ok(req) => OkOrErrHandler::Ok(MyHandler::new(req)),
            Err(e) => OkOrErrHandler::Err(MyErrorHandler::new(e)),
        })
    }
}
```

I have a feeling that the underlying implementation may become very complicated if we want to make the error invisible until someone asks for it. I'm also afraid that some people may not realize that there is an error case. They may end up wondering why their requests doesn't reach their handlers and the connection just closes or sends a canned error response. Simplification is good, but too much of it may make the alternative scenarios more complex.

**Comment by seanmonstar** [comment]
I'm feeling similar to @Ogeon

**Comment by cybergeek94** [comment]
Ultimately, I agree. It's the simplest to implement while giving the user the choice between control and convenience.

I realized that we've been discussing the server-side API all this time. How would the client-side work?

**Comment by seanmonstar** [comment]
I imagine the Client would continue to not have a factory, instead you pass
a Handler to the request method. It would receive a Transaction object
similar to the server, but request() doesn't need to return an Error, but
response() does.

**Comment by abonander** [comment]
@seanmonstar any movement on this? It seems like there's still a lot going on in `master`, which is still based on `rotor`, though I guess a lot of the work is framework-agnostic. Do you need someone working on it? If so, I have some free time here and there.

**Comment by seanmonstar** [comment]
You can actually see the server side of this proposed API in the tokio
branch: https://github.com/hyperium/hyper/tree/tokio

At RustConf, I had a good discussion with Alex, Aaron, and Carl about hyper
and tokio, and was convinced to expose a fully futurized API, like tokio's
Service. I've been meaning to write up about that and post it here, but
I've been cramming on work the past 3 weeks trying to ship my Q3 goal (Q3
ended yesterday).

**Comment by daogangtang** [comment]
Come on baby, I want to ask when will  the initial workable version of hyper on tokio be ready more or less?  Could we participate in? Thx.

**Comment by farodin91** [comment]
Any progress? Could I help?

**Comment by seanmonstar** [comment]
I still haven't filed specific issues on what is needed, but the last comments in #934 describe what is missing at a higher level.

I'm going to close this, since this API is not what is going to happen, but instead that Futures API in the above issue.
