### ISSUE TITLE
Accept header drops */* MIMEs

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#885]

**Comment by seanmonstar** [comment]
This should be fixed in mime@0.2.3. Just running `cargo update -p mime` should be enough. Sorry for taking so long on this.

**Comment by seanmonstar** [comment]
I just ran some updated tests in hyper and confirmed that this is fixed. Since there is no needed code to change in hyper, I'm going to close without a PR.

**Comment by sfackler** [comment]
Awesome thanks!
