### ISSUE TITLE
Scheme trait implementors not shown

### ISSUE THREAD

**Issue by jethrogb** [hyperium/hyper#886]
In the [Scheme documentation](http://hyper.rs/hyper/v0.9.10/hyper/header/trait.Scheme.html), you can't find out with schemes exist since the implementors list is empty.

**Comment by seanmonstar** [comment]
Hrm, frustrating rustdoc bug. I imagine it's been fixed in nightly, since the docs are published using the stable release...

**Comment by seanmonstar** [comment]
Noticed that the previous version of the docs did show the list: http://hyper.rs/hyper/v0.9.9/hyper/header/trait.Scheme.html

**Comment by jethrogb** [comment]
That's frustating indeed...

**Comment by seanmonstar** [comment]
The latest docs seem to work: http://hyper.rs/hyper/v0.10.0/hyper/header/trait.Scheme.html
