### ISSUE TITLE
Impossible to configure custom TLS validation

### ISSUE THREAD

**Issue by jethrogb** [hyperium/hyper#887]
Regardless of what was previously configured in `SslContext`, [this line](https://github.com/hyperium/hyper/blob/9456738ee136158c10681b41c4038c1bf8639664/src/net.rs#L499) simply overrides any verification settings.

**Comment by seanmonstar** [comment]
True. Does `SslContext` have a way of setting that? I imagine it didn't, and so the verify option was set on the `Ssl` instead. If it does, that line could be moved the `Default` implementation.

**Comment by jethrogb** [comment]
`SslContext` has [the same functions](https://sfackler.github.io/rust-openssl/doc/v0.7.14/openssl/ssl/struct.SslContext.html#method.set_verify) for verification as `Ssl`.

**Comment by seanmonstar** [comment]
I just looked again, and clearly that isn't possible, because the hostname must be passed to the verify callback. Is there a different verification you'd hope to do, or just hoping to disable it?

**Comment by jethrogb** [comment]
I want to pin to a specific certificate and don't care about hostname verification.

**Comment by seanmonstar** [comment]
To unblock your use-case, you can `impl SslClient for PinnedCert` to do exactly as you like, and then use `Client::with_connector(HttpsConnector::new(PinnedCert))`

I feel the SSL/TLS design needs a bit of help in general.

**Comment by jethrogb** [comment]
Yup, did that. :) 

You could do
```
pub struct OpensslClient {
	ctx: SslContext,
	default_verify: bool,
}
```

**Comment by tatref** [comment]
I would like to connect to a fake certificate (the certificate does not match the domain), which is currently impossible.

It would be really great if we could connect to an invalid domain/ expired certificate / unknown issuer...

Can I just `impl SslClient` to make this work?

**Comment by seanmonstar** [comment]
Yes, you can implement SslClient however you'd like.

**Comment by seanmonstar** [comment]
With the release of [0.10](https://github.com/hyperium/hyper/releases/tag/v0.10.0), hyper no longer bundles a default SslClient, and instead proposes use of pluggable crates to provide it. So I'm going to close this.
