### ISSUE TITLE
Using 2 types for same Header can cause a panic

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#888]
``` rust
impl Header for MyFoo {}
impl Header for YourFoo {}

let mut headers = Headers::new();
headers.set(MyFoo);
headers.get(YourFoo); // panic
```

**Comment by smithsps** [comment]
```rust
#[macro_use] extern crate hyper;

use hyper::header::{Headers, From};

fn main() {
    header! { (MyFoo, "Foo") => [String]  }
    header! { (YourFoo, "Foo") => [String] }

    let mut headers = Headers::new();
    headers.set(MyFoo("bar".to_owned()));
    headers.get::<YourFoo>(); //panic
}
```
When headers.set() is called and a new Item is created with Item::new_typed(), Item raw is only [initialized to None](https://github.com/hyperium/hyper/blob/8b3c1206846cb96be780923952eafe0dde7850bf/src/header/internals/item.rs#L30). 
Then when Item::typed() is called in headers.get() and there isn't a matching tid, there is a [expect ](https://github.com/hyperium/hyper/blob/8b3c1206846cb96be780923952eafe0dde7850bf/src/header/internals/item.rs#L59) on the type's item's raw, but as its None it panics.

And if you intialize it with Item::raw(), everything seems to work fine.
But I'm not confident in my solution, so would it be better to have it in Item::new_typed()?
```rust
pub fn new_typed(ty: Box<Header + Send + Sync>) -> Item {
        ...
        let item = Item {
            raw: OptCell::new(None),
            typed: map,
        };
        item.raw();
        item
    }
```
Or is it better to use raw() in this fashion, in Item::typed()?
```rust
    pub fn typed<H: Header + Any>(&self) -> Option<&H> {
        ...
                match parse::<H>(self.raw()) {
                // replacing: self.raw.as_ref().expect("item.raw must exist")
                    Ok(typed) => {
                        unsafe { self.typed.insert(tid, typed); }
                        self.typed.get(tid)
                    },
         ...
    }
```

**Comment by seanmonstar** [comment]
For now, the new version of hyper won't be including the typed headers directly, so I'm closing this here as a won't fix.
