### ISSUE TITLE
Using Hyper's HTTP20Adapter with requests-futures

### ISSUE THREAD

**Issue by bek0s** [hyperium/hyper#890]
Hi guys,

Has anyone tried to use `HTTP20Adapter` with requests-futures? It appears to hang/freeze when trying to send requests from multiple workers. Here are some details: https://github.com/ross/requests-futures/issues/37
Is this related to the fact that some Hyper objects are not thread-safe? Or maybe because in my case I use the same session object for all the workers?
Thank you.

**Comment by seanmonstar** [comment]
This likely isn't the project you're looking for. This is an http library for the Rust language. Looks like you want the Python library.
