### ISSUE TITLE
Headers should offer method to remove and return header

### ISSUE THREAD

**Issue by untitaker** [hyperium/hyper#891]
If I take a `Headers` by value (moving it into my function), I want to avoid copying them. For that reason it would be useful if either `Headers::remove` would return the popped item (as `HashMap::remove` does), or if a new method was added.

**Comment by untitaker** [comment]
(I'm willing to write a PR for this)

**Comment by seanmonstar** [comment]
Hm, I agree with this entirely, 👍 . This would be a breaking change, since `remove` currently returns a `bool`, but it seems like the right one to make. As such, I'd aim it for master and not for the 0.9.x branch. Basically:

```rust
fn remove<H: Header>(&mut self) -> Option<H>;
```

**Comment by untitaker** [comment]
Great, I will write a PR as soon as possible.

**Comment by untitaker** [comment]
@seanmonstar Work in progress at #898, I underestimated the effort and need some guidance about further procedure.
