### ISSUE TITLE
Add `query()` method to `server::Request`

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#897]
Similar to #896 

```rust
fn query(&self) -> Option<&str>;
```

**Comment by jonashagstedt** [comment]
What about using a hashmap for the query string?
I imagine that any time you want to work with the querystring you want to work with the values.

e.g

```
let page = request.query["page"].unwrap();
```

**Comment by seanmonstar** [comment]
You might want the query params, but not necessarily. A somewhat common usecase for a query string is as a cache buster, i.e. `/foo/bar.js?abcdef`, such as adding a timestamp or sha to the end. I'd also prefer leaving the choice of what to parse them into up to the user. Whether that is `Vec<(Name, Value)>`, a HashMap, or whatever.
