### ISSUE TITLE
Add support for picoTCP

### ISSUE THREAD

**Issue by kmcallister** [hyperium/hyper#90]
http://www.picotcp.com/picotcp-bindings-rust

Example applications:

* Servo on embedded systems
* Internet of Things devices that use web APIs
* In-browser management interfaces for network devices, which are usually security disasters cobbled together in C and shell script

**Comment by hexsel** [comment]
PicoTCP's rust bindings haven't been updated since way before the 1.0 release (2014/12/17), is this still pursuing for now?

**Comment by seanmonstar** [comment]
It's not something that I think hyper should pursue. Support can be added with an external crate by implementing `Transport` and `Connect` on some picoTCP types.
