### ISSUE TITLE
Misorder handler and response in async client request

### ISSUE THREAD

**Issue by huachaohuang** [hyperium/hyper#901]
Seems `hyper::client::Client::request()` will queue the handlers for the same url, and call the first handler on the first response.
But if I send more requests on the same url at the same time, it will a problem because the handlers order may not match the responses.

**Comment by seanmonstar** [comment]
@huachaohuang do you have a specific instance? This shouldn't be true, at least the exact steps you described.

It's true that the `Handler`s will be queued in a `Vec`, waiting for DNS to come back with a TcpStream to use. However, once it has been assigned, the request/response will be part of the same stream.

**Comment by seanmonstar** [comment]
The Client no longer uses this code at all, so I'm going to close.
