### ISSUE TITLE
configure ssl

### ISSUE THREAD

**Issue by fanyer** [hyperium/hyper#903]
Cargo.toml contains dependencies as below
```
[dependencies]
hyper="0.9.10"
```
when type `cargo run` in cli , error shows as below
```
error: failed to run custom build command for `openssl v0.7.14`
```
Then how to configure ssl on hyper, could you give some examples

**Comment by fanyer** [comment]
or should I compile hyper locally ,and Then  introduct it into my project, rather than get hyper with cargo on site of cr]ate.io?  It seems work, but how to add ssl certification

**Comment by seanmonstar** [comment]
If you want to figure out how to get openssl building, look at https://github.com/sfackler/rust-openssl

If you like to disable SSL, you can try this in your Cargo.toml:

```toml
[dependencies]
hyper = { version="0.9.10", default-features=false }
```
