### ISSUE TITLE
Text was not valid unicode

### ISSUE THREAD

**Issue by alexmironof** [hyperium/hyper#904]
Hi! I've got an error `ERROR:on_response_readable: text was not valid unicode` on client with `examples/client.rs`.

Headers are
```
Response: 200 OK
Headers:
Date: Fri, 26 Aug 2016 12:55:31 GMT
Server: Apache/1.3.42 (Unix)
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=WINDOWS-1251
```

What can I do with it?

**Comment by seanmonstar** [comment]
Do you have a little more information? What is the exact code in `on_response_readable` that errors?

**Comment by alexmironof** [comment]
I copied whole ```example/client.rs``` from master. That server doesn't return utf-8 even if i set AcceptCharset header.

I've got a workaround using 0.9 version of hyper and encoding crate:

```
    let client = Client::new();
    
    let mut res = client.get(&*url)
        .header(AcceptCharset(vec![qitem(Charset::Ext("UTF-8".to_owned()))]))
        .header(Connection::close())
        .send().unwrap();

    let mut buffer: Vec<u8> = Vec::new();
    res.read_to_end(&mut buffer);

    let decoded = UTF_8.decode(&buffer, DecoderTrap::Ignore).unwrap();

```

but can't figure out how to use it with ```on_response_readable ```

**Comment by seanmonstar** [comment]
You can do similar. Keep reading in to a `Vec<u8>` buffer until end of file, and then use your `UTF_8.decode` utility.

**Comment by alexmironof** [comment]
Thanks for the response!:+1: I've got it working now :smile:
