### ISSUE TITLE
"early eof" error reading from decoder in on_response_readable()

### ISSUE THREAD

**Issue by shanegibbs** [hyperium/hyper#908]
Encountering the error using the client example yields:
```
ERROR:example: early eof
```
This requires hitting a URL that responds with Chunked encoding.

It does not happen very often, however, increasing the buffer size when reading from the decoder appears to increase the chances.

**Comment by shanegibbs** [comment]
@seanmonstar you mentioned that the decoder needed some work. Should I take a pass at a fix for this? Or are you planning on a re-write?

**Comment by seanmonstar** [comment]
I don't have a specific plan, I just recall that the current chunked decoding code started when hyper used blocking IO, and it likely doesn't handle blocks perfectly: https://github.com/hyperium/hyper/blob/master/src/http/h1/decode.rs#L152

Actually, looking it over, I'm surprised it works as much as it does! It could definitely do with some tests using `mock::Async`, which allows simulating blocking IO.

**Comment by shanegibbs** [comment]
As an initial step, I took a quick look at an async test. How does this look: https://github.com/hyperium/hyper/pull/909

**Comment by shanegibbs** [comment]
Fix merged 👍
