### ISSUE TITLE
why `send` method automatic set `Date` header?

### ISSUE THREAD

**Issue by fengcen** [hyperium/hyper#912]
I found the code in `write_head()`:

    if !self.headers.has::<header::Date>() {
        self.headers.set(header::Date(header::HttpDate(now_utc())));
    }

I don't want to set `Date` header. What should I do?

**Comment by seanmonstar** [comment]
The spec says it's required. See the last sentence of the second paragraph in [RFC7231#7.1.1.2](https://tools.ietf.org/html/rfc7231#section-7.1.1.2):

> An origin server MUST send a Date header field[...].

**Comment by smithsps** [comment]
RFC7231#7.1.1.2 - ` An origin server MUST NOT send a Date header field if it does not
   have a clock capable of providing a reasonable approximation of the
   current instance in Coordinated Universal Time.`

It'd be uncommon, but it's technically possible that hyper could be used on such a system.

**Comment by fengcen** [comment]
Ok. Thank you for the information.

**Comment by seanmonstar** [comment]
@smithsps it could be, so I wouldn't object to some sort of config, I suppose, but I'm left wondering if it realistically ever happens.

**Comment by smithsps** [comment]
@seanmonstar agreed, the only thing I could think of could be clockless embedded device that for some reason didn't have a NTP sync.
