### ISSUE TITLE
Zero-copy techniques

### ISSUE THREAD

**Issue by DemiMarie** [hyperium/hyper#926]
This is a feature request for the use of zero-copy techniques by Hyper.

These include:
- scatter-gather IO
- linked strings of smaller parts, as read from IO.

See [this blog post](http://www.rubyraptor.org/how-we-made-raptor-up-to-4x-faster-than-unicorn-and-up-to-2x-faster-than-puma-torquebox/) for details.

**Comment by seanmonstar** [comment]
Did you have specific concerns in hyper? You can see in master that we use
vecio, which provides writev.

**Comment by seanmonstar** [comment]
I'm going to close this, since hyper uses the `bytes` crate to reduce copies, and `write_buf` allows for using `writev`.
