### ISSUE TITLE
Consider using custom allocators

### ISSUE THREAD

**Issue by DemiMarie** [hyperium/hyper#929]
For an HTTP server, standard allocators leave much to be desired.  It might be possible to use custom allocators to improve performance.

Examples of custom allocators are NGINX's palloc system.

The allocators should use Rust's type system to ensure that invariants are not violated.  For instance, it should be a lifetime error for a reference to an arena-allocated object to outlive its arena.

**Comment by seanmonstar** [comment]
The rust ecosystem has settled on this pattern: libs use the system
allocator, but rust binaries by default override that with jemalloc, which
is considered to be quite excellent.

**Comment by DemiMarie** [comment]
@seanmonstar By "custom allocator" I mean something like arena allocation for strings, not a better `malloc`.

**Comment by seanmonstar** [comment]
Then this sounds identical to #927

**Comment by DemiMarie** [comment]
Not quite; this is more about using techniques like arena allocation, while
#927 is more about pooling.  But if you want to handle both as one issue
that's fine.

**Comment by Hoverbear** [comment]
Proposing this issue can be closed, in such a case.

**Comment by seanmonstar** [comment]
Recent benchmarks show hyper to extremely competitive. I'm not against using an arena for things in hyper, but I'd rather specific issues be opened about certain parts, when its shown that using an arena would have a meaningful improvement.
