### ISSUE TITLE
How to get the best performance?

### ISSUE THREAD

**Issue by dpc** [hyperium/hyper#937]
Hi,

How should I benchmark hyper http server to get the best possible performance?

Basically I'm benchmarking example [mioco http server](https://github.com/dpc/mioco/blob/master/examples/http-server.rs) vs example hyper server:

```
[I] dpc@futex ~/l/r/3/hyper (master) [I]> wrk -t8 -c100 -d10s http://localhost:1337
Running 10s test @ http://localhost:1337
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.12ms  520.18us   6.59ms   94.00%
    Req/Sec    11.99k     2.03k   14.67k    87.60%
  904028 requests in 10.00s, 77.59MB read
Requests/sec:  90404.81
Transfer/sec:      7.76MB
[I] dpc@futex ~/l/r/3/hyper (master) [I]> wrk -t8 -c100 -d10s http://localhost:5555
Running 10s test @ http://localhost:5555
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.42ms    6.41ms  36.59ms   95.84%
    Req/Sec    96.74k    54.04k  224.67k    60.08%
  6911985 requests in 10.00s, 349.36MB read
Requests/sec: 691238.73
Transfer/sec:     34.94MB
```

I thought that now that rotor is integrated, the performance should be very good. Mioco http example is a bit different, but it does http parsing of some kind etc. so I was expecting hyper to win easily. What am I missing?

**Comment by seanmonstar** [comment]
What version of hyper were you using? The asynchronous version is on the
master branch, not 0.9.

**Comment by dpc** [comment]
`7de6f2b Merge pull request #933 from jwilm/misc-client-fixes`

**Comment by seanmonstar** [comment]
Try the hello.rs example. It uses all threads, the server.rs only uses 1,
and has some states to handle as an http echo server.

**Comment by dpc** [comment]
hello.rs example:

```
[I] dpc@futex ~/l/r/3/hyper (master) [I]> wrk -t8 -c100 -d10s http://localhost:3000
Running 10s test @ http://localhost:3000
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   349.14us    1.12ms  29.04ms   98.12%
    Req/Sec    44.40k    19.14k  168.10k    74.20%
  3290810 requests in 10.00s, 276.18MB read
Requests/sec: 329100.55
Transfer/sec:     27.62MB
```

Still a bit slower (2x) - why could it be? Is it because mioco example is really not formatting any real response and just writes the whole response in one go?

**Comment by seanmonstar** [comment]
I'm sure that is a noticeable part of it.

I imagine another part is that mioco likely is doing a better job of saturating your CPUs automatically, whereas the hyper example could probably use some fine tuning per machine and use case to make sure TCP is the bottleneck.
