### ISSUE TITLE
Percent decoding server request URI

### ISSUE THREAD

**Issue by mitchhentges** [hyperium/hyper#939]
I'm attempting to decode a server request URI that will have spaces `%20` in it. I've noticed that the [`Url`](http://hyper.rs/hyper/0.8.0/hyper/struct.Url.html#method.lossy_percent_decode_query) struct has a `lossy_percent_decode_query()` method.

I'm looking for a similar approach for handling [`RequestUri`](http://hyper.rs/hyper/0.8.0/hyper/uri/enum.RequestUri.html). It's an enum, and chances are, I'm getting an `AbsolutePath`. I cannot load the `AbsolutePath: String` as a `Url`, because it's missing a "base". Is there a standalone method for decoding `Uri` strings with percentages in them? How are most people decoding `Uri`s on the server-side?

**Comment by seanmonstar** [comment]
Yes, there is [`url::percent_encoding`](https://docs.rs/url/1.2.2/url/percent_encoding/index.html) that can decode any string.
