### ISSUE TITLE
keepalive requests hitting Nagle's algorithm delays

### ISSUE THREAD

**Issue by scottlamb** [hyperium/hyper#944]
I puzzled for an embarrassingly long time over some HTTP request benchmarks being horrendously slow before realizing that (A) it only happened when I reused a `hyper::Client` between requests, and (B) there was a lot of real time going by but not a lot of user+sys time, so I was hitting a sleep/timeout. Eventually I boiled the test down to this:

```rust
#![feature(test)]

extern crate env_logger;
#[macro_use] extern crate lazy_static;
#[macro_use] extern crate log;
extern crate test;
extern crate hyper;

use std::thread;

static PAYLOAD: [u8; 9000] = [0; 9000];

/// Starts the test http server on an ephemeral port, returning its base URL.
fn start_server() -> String {
    let mut listener = hyper::net::HttpListener::new("127.0.0.1:0").unwrap();
    use hyper::net::NetworkListener;
    let addr = listener.local_addr().unwrap();
    let server = hyper::Server::new(listener);
    thread::spawn(move || {
        use hyper::server::{Request, Response, Fresh};
        let _ = server.handle(move |_: Request, res: Response<Fresh>| {
            res.send(&PAYLOAD[..]).unwrap();
        });
    });
    format!("http://{}:{}/", addr.ip(), addr.port())
}

lazy_static! {
    /// Servers [can't be shut down](https://github.com/hyperium/hyper/issues/338), so start
    /// just one for all calls to `requests`. Otherwise if the benchmark framework calls
    /// `requests` many times (which it appears to do, in addition to many iterations per
    /// time), the program may run out of file descriptors / localhost may run out of ephemeral
    /// sockets.
    static ref SERVER_URL: String = start_server();
}

#[bench] fn requests(b: &mut test::Bencher) {
    let _ = env_logger::init();
    let url = &*SERVER_URL;
    let mut buf = Vec::with_capacity(PAYLOAD.len());
    b.iter(|| {
        let client = hyper::Client::new();
        for _ in 0..10 {
            let mut resp = client.get(url).send().unwrap();
            buf.clear();
            use std::io::Read;
            let _ = resp.read_to_end(&mut buf).unwrap();
            assert_eq!(&PAYLOAD[..], &buf[..]);
        }
    });
}
```

On my Ubuntu 16.04.1 LTS VM using rustc 1.14.0-nightly (6dc035ed9 2016-10-15) and hyper v0.9.x head, this happens:

```
$ cargo bench --no-run && time target/release/hypertest-* --bench
   Compiling hypertest v0.1.0 (file:///home/slamb/git/hypertest)
    Finished release [optimized] target(s) in 14.35 secs

running 1 test
test requests ... bench: 360,014,403 ns/iter (+/- 1,154,082)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured


real    1m48.477s
user    0m0.520s
sys     0m0.520s
```

If I patch hyper to disable [Nagle's algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm), the same test runs at a more reasonable speed:

```
$ cargo bench --no-run && time target/release/hypertest-* --bench
   Compiling hyper v0.9.10 (file:///home/slamb/git/crates/hyper)
   Compiling hypertest v0.1.0 (file:///home/slamb/git/hypertest)
    Finished release [optimized] target(s) in 60.27 secs

running 1 test
test requests ... bench:   1,807,322 ns/iter (+/- 272,899)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured


real    0m3.839s
user    0m1.432s
sys     0m2.024s
```

Here's my quick patch to the 0.9.x branch:

```
diff --git a/src/net.rs b/src/net.rs
index 25b09b7..a5f1755 100644
--- a/src/net.rs
+++ b/src/net.rs
@@ -236,7 +236,9 @@ impl NetworkListener for HttpListener {

     #[inline]
     fn accept(&mut self) -> ::Result<HttpStream> {
-        Ok(HttpStream(try!(self.0.accept()).0))
+        let raw = try!(self.0.accept()).0;
+        try!(raw.set_nodelay(true));
+        Ok(HttpStream(raw))
     }

     #[inline]
@@ -374,7 +376,9 @@ impl NetworkConnector for HttpConnector {
         Ok(try!(match scheme {
             "http" => {
                 debug!("http scheme");
-                Ok(HttpStream(try!(TcpStream::connect(addr))))
+                let raw = try!(TcpStream::connect(addr));
+                try!(raw.set_nodelay(true));
+                Ok(HttpStream(raw))
             },
             _ => {
                 Err(io::Error::new(io::ErrorKind::InvalidInput,
```

I don't know the best test strategy. The requests still work without my patch; they're just horrendously slow. And the slowness is finicky; it depends on the size/sequence of writes. [This page](https://www.w3.org/Protocols/HTTP/Performance/Nagle/) mentions the effect I noticed.

The downside of this approach (just disabling Nagle's algorithm when building the `HttpStream`) is that it may cause more packets to be sent, wasting bandwidth and potentially CPU. That could be avoided by using `TCP_CORK` until a complete HTTP message is sent (completely eliminating partial frames while sending a message) or probably by just calling `set_nodelay(true); set_nodelay(false)` just after sending each complete TCP message. I think the latter would be most similar to the old behavior except that full messages would never be delayed, as described in the last sentence of this `man 7 tcp` snippet on Linux:

```
       TCP_NODELAY
              If  set,  disable the Nagle algorithm.  This means that segments are always sent as
              soon as possible, even if there is only a small amount of data.  When not set, data
              is  buffered  until  there is a sufficient amount to send out, thereby avoiding the
              frequent sending of small packets, which results in poor utilization  of  the  net‐
              work.   This  option is overridden by TCP_CORK; however, setting this option forces
              an explicit flush of pending output, even if TCP_CORK is currently set.
```

I suppose though there might be circumstances in which the remote side wants to see something right away so maybe the choice should be exposed to hyper's caller somehow, probably defaulting to the efficient/fast thing. Not sure what other HTTP servers/libraries do either. `¯\_(ツ)_/¯`

**Comment by seanmonstar** [comment]
Whether or not to use Nagle's algorithm seems to be a popular topic without an obvious answer for all use cases. I very briefly checked what other popular libraries have for default:

- nodejs: enabled by default
- golang: disabled by default

I don't have a strong feeling either way yet, but I imagine if i read a convincing paper or article, I could become convinced.

**Comment by jwilm** [comment]
As another data point, it sounds as if nginx uses TCP_NODELAY when a connection enters the keep-alive state but is otherwise off.

**Comment by scottlamb** [comment]
Also relevant in the tokio-based master branch. I confused myself with poor benchmark results (again!) until @carllerche mentioned Nagle's algorithm. When I applied this hacky patch:

```
diff --git a/src/server/mod.rs b/src/server/mod.rs
index eb87a62..d6d54d7 100644
--- a/src/server/mod.rs
+++ b/src/server/mod.rs
@@ -378,6 +378,7 @@ impl<S, B> Server<S, B>

         // Future for our server's execution
         let srv = listener.incoming().for_each(|(socket, addr)| {
+            socket.set_nodelay(true).unwrap();
             let s = NotifyService {
                 inner: try!(new_service.new_service()),
                 info: Rc::downgrade(&info),
```

it got better.

**Comment by arthurprs** [comment]
It's _probably_ reasonable to disable NO_DELAY by default with an option to enable.
