### ISSUE TITLE
How to ignore certificate verification?

### ISSUE THREAD

**Issue by little-dude** [hyperium/hyper#947]
Hi,

I cannot figure out from the documentation how to tell my `hyper::client::Client` to ignore invalid certificates from the server. I see that there is an `hyper::net::OpensslClient` struct that holds an `openssl::ssl::SslContext` but I don't really see how it all comes together.

**Comment by little-dude** [comment]
It seems that I can create a client with something like

```rust
Client::with_connector(
    HttpsConnector::new(
        OpensslClient::new( // here I need a custom SslContext, that ignore insecure connections but not sure how to do
                          )
        )
    )
```

But I don't know what the ssl context should be.

**Comment by seanmonstar** [comment]
Here's the docs for the `SslContext`: https://docs.rs/openssl/0.7.14/openssl/ssl/struct.SslContext.html

You can set `ssl_context.set_verify_mode(SSL_VERIFY_NONE, None)` to disable verification.

**Comment by banool** [comment]
For people coming to this many years later, check this out: https://stackoverflow.com/a/79772409/3846032.
