### ISSUE TITLE
Bump from 0.9.10 to 0.9.11 was breaking.

### ISSUE THREAD

**Issue by emilio** [hyperium/hyper#948]
It at least added two new variants to the referrer policy header. Not a huge deal, feel free to close, just wanted to report it.

cc @nox

**Comment by richardwhiuk** [comment]
Prior to 1.0, any change in the version number can be breaking, right? At least that's how I've always interpreted [semver](http://semver.org/) ...

**Comment by SimonSapin** [comment]
That’s not what Cargo does. It considers 0.x.y+1 to be compatible with 0.x.y, and updates to it automatically (either when running `cargo update` or when there isn’t a `Cargo.lock` file already).

**Comment by seanmonstar** [comment]
The bug report is correct, it was technically a breaking change. It was made on the assumption that:

- the only user of ReferrerPolicy is Servo
- Servo submitted an update to header
- I assumed they would want the update before async hyper came out, and assumed they expected the enum to change.

So I made an exception. If it is absolutely definitely the wrong call, I can revert the ReferrerPolicy commit and publish again.

**Comment by nox** [comment]
I wonder if it could be removed from Hyper entirely and defined in a separate crate, but for that we would have to be sure that we are the only users. Maybe though given no one reported any failure with 0.9.11 it means there is indeed no other user but Servo.
