### ISSUE TITLE
Use new version of rust-openssl

### ISSUE THREAD

**Issue by Maplicant** [hyperium/hyper#949]
[v0.9.0](https://github.com/sfackler/rust-openssl/releases/tag/v0.9.0) should make it significantly easier to get rust-openssl to compile on Windows and macOS devices, a problem many Windows users using Hyper have had.

**Comment by sdroege** [comment]
It will also allow people to actually compile rust-openssl (and thus hyper) if they have openssl 1.1 installed

**Comment by sdroege** [comment]
Unfortunately porting to the new API either means not making use of all the new improvements (SslConnector / SslAcceptor), or breaking public API.

**Comment by seanmonstar** [comment]
Updating it would be a breaking change anyways, since you can only have 1 version of openssl-sys, so this could conflict with out dependencies.

---

I'm curious, since I believe that the majority of people who need openssl are using the client. Is this correct?

**Comment by sdroege** [comment]
Question is also which branch to work on, master and 0.9.x are somewhat different in that regard (and I have a simple port for master here that compiles but is otherwise untested)

**Comment by seanmonstar** [comment]
Well, master is where asynchronous IO work is happening, and that will take advantage of tokio-tls, which wraps the new openssl and native-tls in `Future`s.

If people are in need of this for a Client, I have a higher level crate (https://github.com/seanmonstar/reqwest) that works with native-tls, and is just waiting on that crate to be published (which should be early this week).

**Comment by e-oz** [comment]
> I'm curious, since I believe that the majority of people who need openssl are using the client. Is this correct?

Yes, it's correct, but it's very desired change - without it it's impossible to use openssl 0.9.0 and it, therefore, makes impossible to use ssh2 0.3.14 and other things.

> If people are in need of this for a Client, I have a higher level crate 

For us it will mean rewrite all code, related to hyper::client, for contributors of this crate it would mean just fix few lines to achieve compatibility with openssl 0.9.0. At least I hope so :)

As I can see, master and tokio are far from stable, so it's not a replacement.

**Comment by seanmonstar** [comment]
> For us it will mean rewrite all code, related to hyper::client

I really hope not! I've made the `reqwest::Client` API very very similar to `hyper::Client`, so the only changes required should be a replacement of your `extern` and `use` lines. I wanted `reqwest` to be a drop-in replacement, as much as possible.

> for contributors of this crate it would mean just fix few lines to achieve compatibility with openssl 0.9.0. At least I hope so :)

It's true that the amount of code required in hyper to make the change is small. However, with hyper being core to web development, I've found that when a new breaking change version is published, it takes a while for the community to catch up. And in the meantime, people have conflicts of 1 framework using hyper 0.9, and another using hyper 0.10. It seems like a shame to make that ripple through the community and then not too long from now make a newer version to introduce async IO.

My thought has been that people can use the `reqwest` crate, and then there isn't that ripple. Maybe I'm wrong. Maybe it is better to just release hyper 0.10 with openssl updated (or using native-tls even), and then let asynchronous hyper be 0.11.

**Comment by e-oz** [comment]
I agree that this approach is more flexible. Thank you, will try reqwest.

**Comment by e-oz** [comment]
Sorry, @seanmonstar , but reqwest is some experimental code with 0.0.0 version and it has hyper 0.9 in dependencies so there is no point to replace.

**Comment by seanmonstar** [comment]
Sorry, the code for reqwest is not published on crates.io yet, because it
uses the native-tls crate, which is also not published. The author of that
said he'd be able to publish it this week, as he cleaned up the updates for
the new OpenSSL. Once it is, reqwest will be published after.

You can try the crate now by using a git dependency, and I'll update this
issue when it is published.

It's using hyper 0.9 is not an issue, it disables the ssl feature of hyper.
That removes the dependency on openssl 0.7 and openssl-verify. Reqwest then
uses the native-tls crate to implement a new https connector.

**Comment by seanmonstar** [comment]
And, it's now published as 0.1.0! I'll have an article explaining it tomorrow, but if you wish to grab it now, it's there: https://crates.io/crates/reqwest

**Comment by e-oz** [comment]
@seanmonstar 
works fine, thank you *very* much! Just few lines were changed, now all tests are green.

To use openssl 0.9 I still need to vendor hyper, because hyper have dependency on older openssl and even if I write `default-features=false, features=[]`, Cargo adds it to Cargo.lock anyway.

But at least it compiles :)

**Comment by seanmonstar** [comment]
> To use openssl 0.9 I still need to vendor hyper, because hyper have dependency on older openssl and even if I write default-features=false, features=[], Cargo adds it to Cargo.lock anyway.

That shouldn't be the case. Try a `cargo clean`. I know it doesn't, because otherwise `reqwest` could not work, since it depends on the newer openssl 0.9, after disabling hyper's.

**Comment by e-oz** [comment]
That's exactly what happens and that's why I need to vendor hyper. "cargo
clean" was the most often used line these days, but now everything is fine.
Thank you for help.

**Comment by Philipp91** [comment]
I'm using hyper through iron. The rust-openssl version 0.7.x fails to build on my Windows machine, even if I use it in a standalone project:
```
error: failed to run custom build command for `openssl-sys-extras v0.7.14`
process didn't exit successfully: `C:\...\iron-test\target\debug\build\openssl-sys-extras-4d40c2369b784529\build-script-build` (exit code: 101)
```

rust-openssl version 0.9.x works fine. What should I do?

**Comment by e-oz** [comment]
@Philipp91 if you don't use tls connections in your app, you can try to declare dependency as 
```
hyper = { version = "0.9", default-features=false, features=[] }
```
If it will not help, try to fork repo and in your version of Hyper remove dependency of openssl (as I did here: https://github.com/e-oz/hyper/blob/0.9.13/Cargo.toml - don't rely on my repository, it can be removed).

If you do use tls connections, you can use `reqwest` crate for them and again remove openssl dependency from Hyper (see above). But it will work only on mac and windows, not on linux.
