### ISSUE TITLE
Canno't get the value of a custom header

### ISSUE THREAD

**Issue by k0pernicus** [hyperium/hyper#951]
Hi,

I am working on a Github API for Rust, using `hyper`.
Currently, I want to get the remaining rates parsing the header of my response, like that:

```
...
Content-Length: 1219
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 58
X-RateLimit-Reset: 1478459149
Cache-Control: public, max-age=60, s-maxage=60
Vary: Accept
...
```

I'm interested by `X-RateLimit-Limit` and `X-RateLimit-Remaining` values.
So, I wrote those custom headers:

```
header! { (XRateLimitLimit, "X-RateLimit-Limit") => [usize] }
header! { (XRateLimitRemaining, "X-RateLimit-Remaining") => [usize] }
```

The problem here is I don't understand how to get values from those headers...
I tried the example bellow, but the compiler give me the following error "Some(new_rate) => self.rate_limit = *new_rate, expected usize, found struct `client::XRateLimitRemaining`"

```
match response.headers.get::<XRateLimitRemaining>() {
        Some(new_rate) => self.rate_limit = *new_rate,
        None => (),
}
```

Is anybody here has a solution please?

**Comment by seanmonstar** [comment]
The header macro is confusing. It might be more clear to implement Header yourself. But, in this case, it is defining a tuple struct, `XRateLimitRemaining(pub usize)`, so you can access the usize by pattern matching, or accessing `new_rate.0`.

**Comment by k0pernicus** [comment]
Oh ok, I don't understand that the header macro was actually a tuple struct...
Thanks a lot :-)
