### ISSUE TITLE
Build is failing on travis

### ISSUE THREAD

**Issue by vigneshsarma** [hyperium/hyper#955]
Eg: https://travis-ci.org/hyperium/hyper/jobs/174671542

<img width="1026" alt="screen shot 2016-11-13 at 12 59 35 pm" src="https://cloud.githubusercontent.com/assets/889999/20244285/1c070cb6-a9a1-11e6-8229-f8fd29bc2da3.png">

I dont understand the issue. Otherwise I can fix it.

**Comment by seanmonstar** [comment]
The master branch had been neglected, but it is now up-to-date and passing.
