### ISSUE TITLE
Ask the server to split the file to download

### ISSUE THREAD

**Issue by k0pernicus** [hyperium/hyper#959]
It's just a general question to know what are the containers to set in the header (client -> server) to download a file in _X_ chunks?
I checked the doc' and I saw these contents:
* `AcceptRanges`,
* `ContentRangeSpec`,
* `TransferEncoding` (using `chunked`),
* etc...

The problem here is I don't know what are the containers to set to send from client to server.
Is anyone here can help me please?

**Comment by seanmonstar** [comment]
That depends on the server. You can ask it however you'd like, but if the server hasn't decided to allow that, you cannot do it. I can use Amazon's S3 as an example: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html

It says to pass a `Range` header if you wish to download specific pieces of a resource.
