### ISSUE TITLE
Panic in openssl code when using encrypted CookieJar

### ISSUE THREAD

**Issue by stearnsc** [hyperium/hyper#964]
I've been attempting to debug this, but it feels to me like a problem somewhere between hyper and openssl, and I'm over my head.

When running this:
```
extern crate hyper;

use hyper::header::{CookiePair, CookieJar};

fn main() {
    let site_key = b"hVyWYHHFg8k9m1ibs8qCHQ";
    let jar = CookieJar::new(&site_key[..]);
    jar.encrypted().add(CookiePair::new("key".to_owned(), "value".to_owned()));
}
```
I get this:
```
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `-1087632235`, right: `1`)', /Users/cstearns/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.7.14/src/crypto/hmac.rs:100
```

I'm on hyper 0.9.13, which is pulling in openssl 0.7.14. I'm not sure if it's relevant, but in order to get openssl to compile, I need to run:
```
export OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
export DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include
```
in the shell before building to get the compiler to pick up the homebrew openssl (I'm on OSX El Capitan, homebrew openssl version 1.0.2j).

Any ideas?

**Comment by seanmonstar** [comment]
That's an interesting panic, for sure. It seems to be this line right here: https://github.com/sfackler/rust-openssl/blob/v0.7.14/openssl/src/crypto/hmac.rs#L100

Is it just certain keys that panic? Or it always does?

**Comment by stearnsc** [comment]
I tried with two randomly generated keys of different sizes and it panicked for both. That was enough to convince me it wasn't a magic-number kinda scenario, but I don't know more than that.

**Comment by stearnsc** [comment]
Some more digging; it also fails using "signed" instead of "encrypted" (which maybe isn't surprising?). However, I tried using the newest version of cookie directly (https://github.com/alexcrichton/cookie-rs), and it succeeds. That uses cookie 0.3.1 (hyper uses 0.2.5), which pulls in openssl 0.8.3, so my working hypothesis is that this is somehow a bug in openssl that got fixed. What's confusing me is why nobody else seems to be having this issue; iron brings in hyper, which brings in the old version of cookie, which brings in the old version of openssl; I can't imagine nobody using these tools does anything with signed or encrypted cookies.. Maybe whatever's triggering this bug is also tied with the homebrew openssl issue?

Does hyper have plans to upgrade to openssl 0.8 at some point? If so, (and if that's not in the _too_ distant future), I might just punt on this issue and hope the upgrade fixes it..

**Comment by rvolgers** [comment]
That return value is 0xbf2c0c95, which looks like a random stack address instead of a status code. 

Seems plausible that it has to do with this: https://marc.info/?l=openssl-cvs&m=122564502632730

On my Ubuntu system I have libcrypto libraries with both the 0.9.8 and the 1.0.0 API. At the 0.9.8 API level HMAC_Init_ex does not return anything (void), at the 1.0.0 API version it returns an int status code.

**Comment by seanmonstar** [comment]
hyper no longer includes the cookie crate, so signing of cookies can be done with any method one prefers. Closing.
