### ISSUE TITLE
A sample for HTTPS server?

### ISSUE THREAD

**Issue by halmohri** [hyperium/hyper#965]
I'm doing some tests with hyper. I wonder if there's a bare minimum sample HTTPS server similar to the one provided with `HttpListener`? 

Thanks.

**Comment by seanmonstar** [comment]
There currently is in the docs of the `Openssl` type: http://hyper.rs/hyper/v0.9.12/hyper/net/struct.Openssl.html

**Comment by halmohri** [comment]
Thanks for the response. I'm still a bit troubled here. I downloaded the code and added hyper as a local extern in my code (I needed this for testing). When I want to specify a handler for the server, the compiler expects me to specify a type argument for `Request` and `Handler`. But this doesn't happen if I include hyper as a dependency in Cargo. 

```
use hyper::server::{Handler,Request,Response};

struct SenderHandler {
    sender: Mutex<Sender<&'static str>>
}

impl Handler for SenderHandler {
    fn handle(&self, req: Request, res: Response) {
        self.sender.lock().unwrap().send("start").unwrap();
    }
}
```

Error: `Expected 1 type arguments, found 0`. I get this for both `Request` and `Handler`.

**Comment by seanmonstar** [comment]
Indeed, look at the docs for Handler. You receive a Request<Fresh>.

**Comment by seanmonstar** [comment]
Sorry, a Response<Fresh>.

**Comment by halmohri** [comment]
Can you point me to where this `handle` function is defined? (`server.handle(|_| Echo::new()).unwrap()`)

**Comment by jwilm** [comment]
http://hyper.rs/hyper/v0.9.12/hyper/server/struct.Server.html#method.handle
