### ISSUE TITLE
`tokio_proto` API surface update breaks tokio branch

### ISSUE THREAD

**Issue by ashleysommer** [hyperium/hyper#966]
I've been eagerly tracking the tokio branch with the tokio wip commits (because I am interested in both tokio and hyper).

Very recently (4 hours ago) there was a commit on the `tokio_proto` repo that drastically changed the `tokio_proto` API surface, and stopped me from being able to build my project.

I tried to modify the `hyper/tokio` source to match the new `tokio_proto` API, some changes were simple, but there are more complex changes that I couldn't handle myself without a deeper knowledge of both `hyper` and `tokio_proto`.

See the breaking commit here: https://github.com/tokio-rs/tokio-proto/commit/596005a36b5b5e28bb3a0a1690a8c71199c53f06
Edit: This is the source commit, it has more explanation about the changes: https://github.com/tokio-rs/tokio-proto/commit/9dc19d7705a51008b8c9d9d867cecbdc6a8a8ab4

From what I can tell, the basic changes are:
`tokio_proto::{Message, Body}` are changed to `tokio_proto::streaming::{Message, Body}`
`tokio_proto::pipeline` changed to `tokio_proto::streaming::pipeline`
`tokio_proto::multiplex` changed to `tokio_proto::streaming::multiplex`
`tokio_proto::easy::multiplex` changed to `tokio_proto::multiplex`
`tokio_proto::easy::pipeline` changed to `tokio_proto::pipeline`
`tokio_proto::pipeline::server::listen` no longer exists, I believe you must use `tokio_proto::TcpServer` with a `tokio_proto::pipeline::ServerProto` implementation.
That is as far as I got before I was beyond my depth.

What I will do for now (on my local system) is pin the `tokio_proto` package to the last commit before the API update: https://github.com/tokio-rs/tokio-proto/commit/b654c3317dd5fd25e61439eba888dfa9520f96d6

**Comment by seanmonstar** [comment]
I started working on it as soon as I saw that PR was merged. It's fairly close, but I stopped for the night.

**Comment by ashleysommer** [comment]
Thanks for jumping on it so quickly. I'm excited about this work.

**Comment by seanmonstar** [comment]
I've pushed to the tokio branch with a working server. The client module is commented out, as I didn't have time to fix it, but many are probably more interested in the server, so I've got that working now.

**Comment by ashleysommer** [comment]
I believe this can be closed now.
