### ISSUE TITLE
client takes ~500ms for simple request where browsers need ~10ms

### ISSUE THREAD

**Issue by Auruss** [hyperium/hyper#986]
```
Connection →keep-alive
Content-Length →537
Content-Type →text/html
Date →Thu, 05 Jan 2017 15:17:13 GMT
ETag →"5800e28f-219"
Server →nginx/1.10.1
```
Is the response header from nginx. When testing in the browser the request takes ~10ms while in rust using hyper it takes ~500ms every singletime.

`let response = self.client.get(&url).header(Connection::keep_alive()).send()`
Is what I'm using for the connection. I'm also reusing the client for all requests but the request time does not decrease.
TCP_NODELAY is turned on in nginx for fast responses, do I need to turn it on for hyper as well?

**Comment by seanmonstar** [comment]
The comparison isn't entirely fair, which I'll explain why.

In the browser's case:

- It's likely already cached the DNS lookup
- It likely already has a waiting connection, so it can skip TCP and TLS handshake
- It probably even has an HTTP2 connection waiting, which allows even slightly faster performance

A more apt comparison is something like curl, or a browser with its cache wiped.

When I compare `time curl https://some.url` versus hyper's example client (something like `time client https://some.url`), they are pretty even in time.
