### ISSUE TITLE
Conn::write_body panics when encoder returns WouldBlock Error [tokio branch]

### ISSUE THREAD

**Issue by markuskobler** [hyperium/hyper#988]
The following [line](https://github.com/hyperium/hyper/blob/tokio/src/http/conn.rs#L224) panics when you try write a response that would cause the write to block.

**Error**:
```
`Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: WouldBlock, error: StringError("chunked incomplete") }) }'
```

**Line**:
```
   let n = encoder.encode(&mut self.io, wbuf.buf()).unwrap();
```

**Example**: On Mac OS this is a simple way of reproducing the issue.
```
Response::new()
        .with_header(ContentType(mime!(Text/Plain)))
        .with_body(vec![b'0'; 4096])
```

I'm not familiar enough with `tokio` or `hyper` to know the right way of fixing this but if you have any pointers happy to have a go.

**Comment by seanmonstar** [comment]
I forgot to update, but this was fixed in the tokio branch. Thanks for the report!

**Comment by markuskobler** [comment]
Great thank you!
